### PR TITLE
fix(changelog): add a check for exact match of a release

### LINKED ISSUE #15088: Wrong release notes
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Example

See "Release Notes" here: https://github.com/mx-space/kami/pull/1177

The bot is pulling in the wrong tag (v0.6.2 without the new monorepo namespaced tags). The repository recently changed its name and the new package starts from `v0`, which has unprefixed tags already.

### Releases

https://github.com/floating-ui/floating-ui/releases

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by hasanwhitesource**
## Changes

Refactored a few cases and made the check of an exact match of a release take precedence over other checks.

## Context

Renovate was taking the first release that matches the new version of a dep update which is wrong in the case of https://github.com/floating-ui/floating-ui, there could be many releases having the same version but with a different prefix.

Closes #15088 
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/repository/update/pr/changelog/release-notes.ts [hunk 1]
```diff
@@ -97,40 +97,71 @@ export async function getReleaseNotes(
...
+    releaseNotes = await setReleaseNotesResult(exactReleaseMatch, project);
+  } else {
+    // no exact match of a release then check other cases
+    const matchedRelease = releaseList.find((r) => {
+      return (
+        r.tag === version ||
+        r.tag === `v${version}` ||
+        r.tag === `${depName}-${version}` ||
+        r.tag === `${depName}_v${version}` ||
+        r.tag === `${depName}@${version}`
```
Comment (viceice) [inline lib/workers/repository/update/pr/changelog/release-notes.ts:123]: Do we still need those cases?

File: lib/workers/repository/update/pr/changelog/source-github.ts [hunk 2]
```diff
@@ -105,10 +105,12 @@ export async function getChangeLogJSON({
     if (!tags) {
       tags = await getCachedTags(apiBaseUrl, repository);
     }
-    const regex = regEx(`(?:${depName}|release)[@-]`, undefined, false);
-    const tagName = tags
-      .filter((tag) => version.isVersion(tag.replace(regex, '')))
-      .find((tag) => version.equals(tag.replace(regex, ''), release.version));
+    const tagName: string = findTagOfRelease(
```
Comment (viceice) [inline lib/workers/repository/update/pr/changelog/source-github.ts:108]:
```suggestion
    const tagName = findTagOfRelease(
```
shouldn't required

File: lib/workers/repository/update/pr/changelog/source-github.ts [hunk 3]
```diff
@@ -179,3 +181,27 @@ export async function getChangeLogJSON({
...
+  depName: string,
+  depNewVersion: string,
+  tags: string[]
+): string {
+  const regex = regEx(`(?:${depName}|release)[@-]`, undefined, false);
+  const excactReleaseRegex = regEx(`${depName}[@-_]v?${depNewVersion}`);
+  const exactTagsList = tags.filter((tag) => {
+    return excactReleaseRegex.test(tag);
+  });
+  let tagName: string = null;
```
Comment (viceice) [inline lib/workers/repository/update/pr/changelog/source-github.ts:196]:
```suggestion
  let tagName: string | null | undefined = null;
```
ts null check

`.find` returns undefined

File: lib/workers/repository/update/pr/changelog/source-github.ts [hunk 4]
```diff
@@ -179,3 +181,27 @@ export async function getChangeLogJSON({
 
   return res;
 }
+
+function findTagOfRelease(
+  version: allVersioning.VersioningApi,
+  depName: string,
+  depNewVersion: string,
+  tags: string[]
+): string {
```
Comment (viceice) [inline lib/workers/repository/update/pr/changelog/source-github.ts:190]:
```suggestion
): string | null | undefined {
```

File: lib/workers/repository/update/pr/changelog/release-notes.ts [hunk 5]
```diff
@@ -97,40 +97,65 @@ export async function getReleaseNotes(
...
-            releaseNotes.body = await linkify(releaseNotes.body, {
-              repository: `${baseUrl}${repository}`,
-            });
-          }
-        } catch (err) /* istanbul ignore next */ {
-          logger.warn({ err, baseUrl, repository }, 'Error linkifying');
-        }
-      } else {
-        releaseNotes = null;
+  let matchedRelease: ChangeLogNotes | undefined | null = null;
```
Comment (viceice) [inline lib/workers/repository/update/pr/changelog/release-notes.ts:105]:
```suggestion
  let matchedRelease: ChangeLogNotes | undefined;
```

locks cleaner to me 🙃

File: lib/workers/repository/update/pr/changelog/release-notes.ts [hunk 6]
```diff
@@ -97,40 +97,65 @@ export async function getReleaseNotes(
...
+  const exactReleaseReg = regEx(`${depName}[@_-]v?${version}`);
+
+  const candidateReleases = releaseList.filter((r) => {
+    return r.tag?.endsWith(version);
+  });
+  matchedRelease = candidateReleases.find((r) => {
+    return exactReleaseReg.test(r.tag);
+  });
```
Comment (viceice) [inline lib/workers/repository/update/pr/changelog/release-notes.ts:113]:
```suggestion
  const candidateReleases = releaseList.filter((r) => r.tag?.endsWith(version));
  matchedRelease = candidateReleases.find((r) => exactReleaseReg.test(r.tag));
```

looks cleaner

File: lib/workers/repository/update/pr/changelog/release-notes.ts [hunk 7]
```diff
@@ -97,40 +97,65 @@ export async function getReleaseNotes(
...
+
+  if (!matchedRelease) {
+    // no exact match of a release then check other cases
+    matchedRelease = releaseList.find((r) => {
+      return r.tag === version || r.tag === `v${version}`;
+    });
```
Comment (viceice) [inline lib/workers/repository/update/pr/changelog/release-notes.ts:119]: see other comment

File: lib/workers/repository/update/pr/changelog/release-notes.ts [hunk 8]
```diff
@@ -97,40 +97,65 @@ export async function getReleaseNotes(
...
+  }
+  releaseNotes = await releaseNotesResult(matchedRelease, project);
+  logger.trace({ releaseNotes });
+  return releaseNotes;
+}
+
+async function releaseNotesResult(
+  releaseMatch: ChangeLogNotes,
```
Comment (viceice) [inline lib/workers/repository/update/pr/changelog/release-notes.ts:127]:
```suggestion
  releaseMatch: ChangeLogNotes | undefined,
```

File: lib/workers/repository/update/pr/changelog/source-github.ts [hunk 9]
```diff
@@ -179,3 +176,27 @@ export async function getChangeLogJSON({
...
+  depName: string,
+  depNewVersion: string,
+  tags: string[]
+): string | null | undefined {
+  const regex = regEx(`(?:${depName}|release)[@-]`, undefined, false);
+  const excactReleaseRegex = regEx(`${depName}[@-_]v?${depNewVersion}`);
+  const exactTagsList = tags.filter((tag) => {
+    return excactReleaseRegex.test(tag);
+  });
+  let tagName: string | null | undefined = null;
```
Comment (viceice) [inline lib/workers/repository/update/pr/changelog/source-github.ts:191]:
```suggestion
  let tagName: string | undefined;
```

only use undefiend

File: lib/workers/repository/update/pr/changelog/source-github.ts [hunk 10]
```diff
@@ -179,3 +176,27 @@ export async function getChangeLogJSON({
 
   return res;
 }
+
+function findTagOfRelease(
+  version: allVersioning.VersioningApi,
+  depName: string,
+  depNewVersion: string,
+  tags: string[]
+): string | null | undefined {
```
Comment (viceice) [inline lib/workers/repository/update/pr/changelog/source-github.ts:185]:
```suggestion
): string | undefined {
```

File: lib/workers/repository/update/pr/changelog/release-notes.ts (hunk 6 above)
Comment (hasanwhitesource) [reply lib/workers/repository/update/pr/changelog/release-notes.ts:113]: You think it will also look much cleaner and readable if I move the regex with find part to a function ?

**Review by viceice — DISMISSED** [review]

**Review by rarkins — APPROVED** [review]
