### PR TITLE
fix(manager/gradle-wrapper): distributionSha256Sum is inconsistent with the gradle version

### LINKED ISSUE #13081: gradle-wrapper not updating distributionSha256Sum if grouped with other update
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Describe the bug

Reproduction: https://github.com/henrist/renovate-repro-gradle-wrapper

Note the `dep.txt` which has a regex match. Both the gradle wrapper and Docker reference is having the dependency name `gradle`.

If only having the update in `gradle-wrapper.propertes` (no `dep.txt`) it works fine, but when coupled with another update it seems that `gradle-wrapper.properties` is not "reverted" before the special gradle wrapper task is executed, causing `gradle-wrapper.properties` to be inconsistent (invalid sha for the new version).

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/gradle-7.x")
DEBUG: Starting search at index 0(packageFile="dep.txt", branch="renovate/gradle-7.x")
{
  "depName": "gradle"
}
DEBUG: Found match at index 0(packageFile="dep.txt", branch="renovate/gradle-7.x")
{
  "depName": "gradle"
}
DEBUG: Contents updated(packageFile="dep.txt", branch="renovate/gradle-7.x")
{
  "depName": "gradle"
}
DEBUG: Starting search at index 168(packageFile="gradle/wrapper/gradle-wrapper.properties", branch="renovate/gradle-7.x")
{
  "depName": "gradle"
}
DEBUG: Found match at index 168(packageFile="gradle/wrapper/gradle-wrapper.properties", branch="renovate/gradle-7.x")
{
  "depName": "gradle"
}
DEBUG: Contents updated(packageFile="gradle/wrapper/gradle-wrapper.properties", branch="renovate/gradle-7.x")
{
  "depName": "gradle"
}
DEBUG: gradle-wrapper.updateArtifacts()(branch="renovate/gradle-7.x")
{
  "updatedDeps": [
    {
      "detectGlobalManagerConfig": false,
      "detectHostRulesFromEnv": false,
      "postUpgradeTasks": {
        "commands": [],
        "fileFilters": [],
        "executionMode": "update"
      },
      "onboardingBranch": "renovate/configure",
      "onboardingCommitMessage": null,
      "onboardingConfigFileName": "renovate.json",
      "onboardingNoDeps": true,
      "onboardingPrTitle": "Configure Renovate",
      "productLinks": {
        "documentation": "https://docs.renovatebot.com/",
        "help": "https://github.com/renovatebot/renovate/discussions",
        "homepage": "https://github.com/renovatebot/renovate"
      },
      "deepExtract": false,
      "draftPR": false,
      "printConfig": false,
      "composerIgnorePlatformReqs": [],
      "logContext": null,
      "dependencyDashboard": true,
      "dependencyDashboardApproval": false,
      "dependencyDashboardAutoclose": false,
      "dependencyDashboardTitle": "Dependency Dashboard",
      "dependencyDashboardHeader": "This issue provides visibility into Renovate updates and their statuses. [Learn more](https://docs.renovatebot.com/key-concepts/dashboard/)",
      "dependencyDashboardFooter": "\n- [ ] <!-- manual job -->Check this box to trigger a request for Renovate to run again on this repository\n",
      "dependencyDashboardLabels": null,
      "configWarningReuseIssue": true,
      "timezone": null,
      "schedule": [
        "at any time"
      ],
      "updateNotScheduled": true,
      "persistRepoData": false,
      "ignorePlugins": false,
      "ignoreScripts": false,
      "platform": "github",
      "endpoint": "https://api.github.com/",
      "npmrc": null,
      "npmrcMerge": false,
      "npmToken": null,
      "updateLockFiles": true,
      "skipInstalls": null,
      "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
      "excludeCommitPaths": [],
      "aliases": {},
      "registryUrls": null,
      "extractVersion": null,
      "versioning": "gradle",
      "azureWorkItemId": 0,
      "azureAutoApprove": false,
      "pinDigests": false,
      "separateMajorMinor": true,
      "separateMinorPatch": false,
      "rangeStrategy": "auto",
      "branchPrefix": "renovate/",
      "bumpVersion": null,
      "semanticCommits": "disabled",
      "semanticCommitType": "chore",
      "semanticCommitScope": "deps",
      "rollbackPrs": false,
      "recreateClosed": true,
      "rebaseWhen": "auto",
      "rebaseLabel": "rebase",
      "stabilityDays": 0,
      "internalChecksFilter": "none",
      "prCreation": "immediate",
      "prNotPendingHours": 25,
      "prHourlyLimit": 2,
      "prConcurrentLimit": 10,
      "branchConcurrentLimit": null,
      "prPriority": 0,
      "bbUseDefaultReviewers": true,
      "automerge": false,
      "automergeType": "pr",
      "automergeStrategy": "auto",
      "automergeComment": "automergeComment",
      "ignoreTests": false,
      "transitiveRemediation": true,
      "branchName": "renovate/gradle-7.x",
      "additionalBranchPrefix": "",
      "branchTopic": "{{{depNameSanitized}}}-{{{newMajor}}}{{#if separateMinorPatch}}{{#if isPatch}}.{{{newMinor}}}{{/if}}{{/if}}.x{{#if isLockfileUpdate}}-lockfile{{/if}}",
      "commitMessage": "Update dependency gradle",
      "commitBody": null,
      "commitBodyTable": false,
      "commitMessagePrefix": null,
      "commitMessageAction": "Update",
      "commitMessageTopic": "dependency {{depName}}",
      "commitMessageSuffix": null,
      "prBodyTemplate": "{{{header}}}{{{table}}}{{{notes}}}{{{changelogs}}}{{{configDescription}}}{{{controls}}}{{{footer}}}",
      "prTitle": "Update dependency gradle",
      "prHeader": "[![WhiteSource Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)",
      "prFooter": "This PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#{{platform}}/{{repository}}).",
      "hashedBranchLength": null,
      "groupSlug": null,
      "labels": [],
      "addLabels": [],
      "assignees": [],
      "assigneesFromCodeOwners": false,
      "assigneesSampleSize": null,
      "assignAutomerge": false,
      "reviewers": [],
      "reviewersFromCodeOwners": false,
      "filterUnavailableUsers": false,
      "confidential": false,
      "reviewersSampleSize": null,
      "additionalReviewers": [],
      "postUpdateOptions": [],
      "constraints": {},
      "prBodyDefinitions": {
        "Package": "{{{depNameLinked}}}",
        "Type": "{{{depType}}}",
        "Update": "{{{updateType}}}",
        "Current value": "{{{currentValue}}}",
        "New value": "{{{newValue}}}",
        "Change": "`{{{displayFrom}}}` -> `{{{displayTo}}}`",
        "References": "{{{references}}}",
        "Package file": "{{{packageFile}}}",
        "Age": "[![age](https://badges.renovateapi.com/packages/{{datasource}}/{{replace '/' '%2f' depName}}/{{{newVersion}}}/age-slim)](https://docs.renovatebot.com/merge-confidence/)",
        "Adoption": "[![adoption](https://badges.renovateapi.com/packages/{{datasource}}/{{replace '/' '%2f' depName}}/{{{newVersion}}}/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)",
        "Passing": "[![passing](https://badges.renovateapi.com/packages/{{datasource}}/{{replace '/' '%2f' depName}}/{{{newVersion}}}/compatibility-slim/{{{currentVersion}}})](https://docs.renovatebot.com/merge-confidence/)",
        "Confidence": "[![confidence](https://badges.renovateapi.com/packages/{{datasource}}/{{replace '/' '%2f' depName}}/{{{newVersion}}}/confidence-slim/{{{currentVersion}}})](https://docs.renovatebot.com/merge-confidence/)"
      },
      "prBodyColumns": [
        "Package",
        "Type",
        "Update",
        "Change"
      ],
      "prBodyNotes": [],
      "suppressNotifications": [
        "deprecationWarningIssues"
      ],
      "pruneStaleBranches": true,
      "unicodeEmoji": true,
      "gitLabIgnoreApprovals": false,
      "fetchReleaseNotes": true,
      "cloneSubmodules": false,
      "ignorePrAuthor": false,
      "updatePinnedDependencies": true,
      "writeDiscoveredRepos": null,
      "platformAutomerge": false,
      "userStrings": {
        "ignoreTopic": "Renovate Ignore Notification",
        "ignoreMajor": "As this PR has been closed unmerged, Renovate will ignore this upgrade and you will not receive PRs for *any* future {{{newMajor}}}.x releases. However, if you upgrade to {{{newMajor}}}.x manually then Renovate will reenable minor and patch updates automatically.",
        "ignoreDigest": "As this PR has been closed unmerged, Renovate will ignore this upgrade and you will not receive PRs for *any* future {{{depName}}}:{{{currentValue}}} digest updates. Digest updates will resume if you update the specified tag at any time.",
        "ignoreOther": "As this PR has been closed unmerged, Renovate will now ignore this update ({{{newValue}}}). You will still receive a PR once a newer version is released, so if you wish to permanently ignore this dependency, please add it to the `ignoreDeps` array of your renovate config."
      },
      "repository": "henrist/renovate-repro-gradle-wrapper",
      "cloneDir": "/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper",
      "isGitHub": true,
      "renovateUsername": "renovate[bot]",
      "errors": [],
      "warnings": [],
      "branchList": [],
      "defaultBranch": "main",
      "isFork": false,
      "baseBranch": "main",
      "repoIsOnboarded": true,
      "$schema": "https://docs.renovatebot.com/renovate-schema.json",
      "renovateJsonPresent": true,
      "dependencyDashboardChecks": {},
      "dependencyDashboardIssue": 2,
      "dependencyDashboardRebaseAllOpen": false,
      "manager": "gradle-wrapper",
      "packageFile": "gradle/wrapper/gradle-wrapper.properties",
      "parentDir": "wrapper",
      "packageFileDir": "gradle/wrapper",
      "depName": "gradle",
      "currentValue": "7.2",
      "replaceString": "https\\://services.gradle.org/distributions/gradle-7.2-all.zip",
      "datasource": "gradle-version",
      "depIndex": 0,
      "sourceUrl": "https://github.com/gradle/gradle",
      "homepage": "https://gradle.org",
      "currentVersion": "7.2",
      "isSingleVersion": true,
      "fixedVersion": "7.2",
      "bucket": "non-major",
      "newVersion": "7.3.1",
      "newValue": "7.3.1",
      "releaseTimestamp": "2021-12-01T15:42:20.000Z",
      "newMajor": 7,
      "newMinor": 3,
      "updateType": "minor",
      "isMinor": true,
      "depNameSanitized": "gradle",
      "sourceRepoSlug": "gradle-gradle",
      "baseDeps": [
        {
          "depName": "gradle",
          "currentValue": "7.2",
          "replaceString": "https\\://services.gradle.org/distributions/gradle-7.2-all.zip",
          "datasource": "gradle-version",
          "versioning": "gradle",
          "depIndex": 0,
          "updates": [
            {
              "bucket": "non-major",
              "newVersion": "7.3.1",
              "newValue": "7.3.1",
              "releaseTimestamp": "2021-12-01T15:42:20.000Z",
              "newMajor": 7,
              "newMinor": 3,
              "updateType": "minor",
              "branchName": "renovate/gradle-7.x"
            }
          ],
          "warnings": [],
          "sourceUrl": "https://github.com/gradle/gradle",
          "homepage": "https://gradle.org",
          "currentVersion": "7.2",
          "isSingleVersion": true,
          "fixedVersion": "7.2"
        }
      ],
      "logJSON": {
        "project": {
          "apiBaseUrl": "https://api.github.com/",
          "baseUrl": "https://github.com/",
          "type": "github",
          "repository": "gradle/gradle",
          "sourceUrl": "https://github.com/gradle/gradle",
          "depName": "gradle"
        },
        "versions": [
          {
            "version": "7.3.1",
            "date": "2021-12-01T15:42:20.000Z",
            "changes": [],
            "compare": {},
            "releaseNotes": {
              "url": "https://github.com/gradle/gradle/releases/v7.3.1",
              "notesSourceUrl": "https://api.github.com/repos/gradle/gradle/releases",
              "id": 54421375,
              "tag": "v7.3.1",
              "name": "7.3.1",
              "body": "This is a patch release for Gradle 7.3.\n\nIt fixes the following issues:\n\n-   [#19058](https://github.com/gradle/gradle/issues/19058) Consider reverting breaking change about test configuration\n-   [#19067](https://github.com/gradle/gradle/issues/19067) Fix multiple annotation processing issues discovered by Micronaut\n\nWe recommend users upgrade to 7.3.1 instead of 7.3.\n\n#### Upgrade Instructions\n\nSwitch your build to use Gradle 7.3.1 by updating your wrapper:\n\n    ./gradlew wrapper --gradle-version=7.3.1\n\nSee the [Gradle 7.x upgrade guide](https://docs.gradle.org/7.3.1/userguide/upgrading_version\\_7.html#changes\\_7.3) to learn about deprecations, breaking changes and other considerations when upgrading to Gradle 7.3.1.\n\n#### Reporting Problems\n\nIf you find a problem with this release, please file a bug on [GitHub Issues](https://github.com/gradle/gradle/issues) adhering to our issue guidelines.\nIf you're not sure you're encountering a bug, please use the [forum](https://discuss.gradle.org/c/help-discuss).\n"
            }
          },
          {
            "version": "7.3",
            "date": "2021-11-09T20:40:36.000Z",
            "changes": [],
            "compare": {},
            "releaseNotes": null
          }
        ],
        "hasReleaseNotes": true
      },
      "displayFrom": "7.2",
      "displayTo": "7.3.1",
      "prettyDepType": "dependency"
    }
  ]
}
DEBUG: Updating gradle wrapper: "./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.3.1-all.zip --gradle-distribution-sha256-sum b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce"(branch="renovate/gradle-7.x")
DEBUG: Using docker to execute(branch="renovate/gradle-7.x")
DEBUG: Found version constraint - checking for a compatible image to use(branch="renovate/gradle-7.x")
{
  "depName": "docker.io/renovate/java",
  "scheme": "npm",
  "constraint": "^16.0.0"
}
DEBUG: getLabels(https://index.docker.io, renovate/java, latest)(branch="renovate/gradle-7.x")
DEBUG: Found compatible image version(branch="renovate/gradle-7.x")
{
  "depName": "docker.io/renovate/java",
  "scheme": "npm",
  "constraint": "^16.0.0",
  "version": "16.0.2"
}
DEBUG: Resolved tag constraint(branch="renovate/gradle-7.x")
{
  "image": "docker.io/renovate/java",
  "tagConstraint": "^16.0.0",
  "tagVersioning": "npm",
  "tag": "16.0.2"
}
DEBUG: Fetching Docker image: docker.io/renovate/java:16.0.2(branch="renovate/gradle-7.x")
DEBUG: Finished fetching Docker image(branch="renovate/gradle-7.x")
DEBUG: Executing command(branch="renovate/gradle-7.x")
{
  "command": "docker run --rm --name=renovate_java --label=renovate_child -v \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\":\"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" docker.io/renovate/java:16.0.2 bash -l -c \"./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.3.1-all.zip --gradle-distribution-sha256-sum b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce\""
}
DEBUG: rawExec err(branch="renovate/gradle-7.x")
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_java --label=renovate_child -v \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\":\"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" docker.io/renovate/java:16.0.2 bash -l -c \"./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.3.1-all.zip --gradle-distribution-sha256-sum b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce\"",
    "stdout": "Downloading https://services.gradle.org/distributions/gradle-7.3.1-all.zip\n...............10%...............20%...............30%...............40%...............50%...............60%................70%...............80%...............90%...............100%\n",
    "stderr": "Exception in thread \"main\" java.lang.RuntimeException: Verification of Gradle distribution failed!\n\nYour Gradle distribution may have been tampered with.\nConfirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.\n\n Distribution Url: https://services.gradle.org/distributions/gradle-7.3.1-all.zip\nDownload Location: /home/ubuntu/.gradle/wrapper/dists/gradle-7.3.1-all/1cx39h5havz97e1a3lk0ekaa5/gradle-7.3.1-all.zip\nExpected checksum: 'a8da5b02437a60819cad23e10fc7e9cf32bcb57029d9cb277e26eeff76ce014b'\n  Actual checksum: 'b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce'\n\n\tat org.gradle.wrapper.Install.verifyDownloadChecksum(Install.java:165)\n\tat org.gradle.wrapper.Install.access$800(Install.java:27)\n\tat org.gradle.wrapper.Install$1.call(Install.java:78)\n\tat org.gradle.wrapper.Install$1.call(Install.java:48)\n\tat org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)\n\tat org.gradle.wrapper.Install.createDist(Install.java:48)\n\tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)\n\tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)\n",
    "message": "Command failed: docker run --rm --name=renovate_java --label=renovate_child -v \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\":\"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" docker.io/renovate/java:16.0.2 bash -l -c \"./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.3.1-all.zip --gradle-distribution-sha256-sum b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce\"\nException in thread \"main\" java.lang.RuntimeException: Verification of Gradle distribution failed!\n\nYour Gradle distribution may have been tampered with.\nConfirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.\n\n Distribution Url: https://services.gradle.org/distributions/gradle-7.3.1-all.zip\nDownload Location: /home/ubuntu/.gradle/wrapper/dists/gradle-7.3.1-all/1cx39h5havz97e1a3lk0ekaa5/gradle-7.3.1-all.zip\nExpected checksum: 'a8da5b02437a60819cad23e10fc7e9cf32bcb57029d9cb277e26eeff76ce014b'\n  Actual checksum: 'b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce'\n\n\tat org.gradle.wrapper.Install.verifyDownloadChecksum(Install.java:165)\n\tat org.gradle.wrapper.Install.access$800(Install.java:27)\n\tat org.gradle.wrapper.Install$1.call(Install.java:78)\n\tat org.gradle.wrapper.Install$1.call(Install.java:48)\n\tat org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)\n\tat org.gradle.wrapper.Install.createDist(Install.java:48)\n\tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)\n\tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_java --label=renovate_child -v \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\":\"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" docker.io/renovate/java:16.0.2 bash -l -c \"./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.3.1-all.zip --gradle-distribution-sha256-sum b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce\"\nException in thread \"main\" java.lang.RuntimeException: Verification of Gradle distribution failed!\n\nYour Gradle distribution may have been tampered with.\nConfirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.\n\n Distribution Url: https://services.gradle.org/distributions/gradle-7.3.1-all.zip\nDownload Location: /home/ubuntu/.gradle/wrapper/dists/gradle-7.3.1-all/1cx39h5havz97e1a3lk0ekaa5/gradle-7.3.1-all.zip\nExpected checksum: 'a8da5b02437a60819cad23e10fc7e9cf32bcb57029d9cb277e26eeff76ce014b'\n  Actual checksum: 'b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce'\n\n\tat org.gradle.wrapper.Install.verifyDownloadChecksum(Install.java:165)\n\tat org.gradle.wrapper.Install.access$800(Install.java:27)\n\tat org.gradle.wrapper.Install$1.call(Install.java:78)\n\tat org.gradle.wrapper.Install$1.call(Install.java:48)\n\tat org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)\n\tat org.gradle.wrapper.Install.createDist(Install.java:48)\n\tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)\n\tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)"
  }
}
WARN: Error executing gradle wrapper update command. It can be not a critical one though.(branch="renovate/gradle-7.x")
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_java --label=renovate_child -v \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\":\"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" docker.io/renovate/java:16.0.2 bash -l -c \"./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.3.1-all.zip --gradle-distribution-sha256-sum b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce\"",
    "stdout": "Downloading https://services.gradle.org/distributions/gradle-7.3.1-all.zip\n...............10%...............20%...............30%...............40%...............50%...............60%................70%...............80%...............90%...............100%\n",
    "stderr": "Exception in thread \"main\" java.lang.RuntimeException: Verification of Gradle distribution failed!\n\nYour Gradle distribution may have been tampered with.\nConfirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.\n\n Distribution Url: https://services.gradle.org/distributions/gradle-7.3.1-all.zip\nDownload Location: /home/ubuntu/.gradle/wrapper/dists/gradle-7.3.1-all/1cx39h5havz97e1a3lk0ekaa5/gradle-7.3.1-all.zip\nExpected checksum: 'a8da5b02437a60819cad23e10fc7e9cf32bcb57029d9cb277e26eeff76ce014b'\n  Actual checksum: 'b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce'\n\n\tat org.gradle.wrapper.Install.verifyDownloadChecksum(Install.java:165)\n\tat org.gradle.wrapper.Install.access$800(Install.java:27)\n\tat org.gradle.wrapper.Install$1.call(Install.java:78)\n\tat org.gradle.wrapper.Install$1.call(Install.java:48)\n\tat org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)\n\tat org.gradle.wrapper.Install.createDist(Install.java:48)\n\tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)\n\tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)\n",
    "message": "Command failed: docker run --rm --name=renovate_java --label=renovate_child -v \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\":\"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" docker.io/renovate/java:16.0.2 bash -l -c \"./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.3.1-all.zip --gradle-distribution-sha256-sum b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce\"\nException in thread \"main\" java.lang.RuntimeException: Verification of Gradle distribution failed!\n\nYour Gradle distribution may have been tampered with.\nConfirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.\n\n Distribution Url: https://services.gradle.org/distributions/gradle-7.3.1-all.zip\nDownload Location: /home/ubuntu/.gradle/wrapper/dists/gradle-7.3.1-all/1cx39h5havz97e1a3lk0ekaa5/gradle-7.3.1-all.zip\nExpected checksum: 'a8da5b02437a60819cad23e10fc7e9cf32bcb57029d9cb277e26eeff76ce014b'\n  Actual checksum: 'b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce'\n\n\tat org.gradle.wrapper.Install.verifyDownloadChecksum(Install.java:165)\n\tat org.gradle.wrapper.Install.access$800(Install.java:27)\n\tat org.gradle.wrapper.Install$1.call(Install.java:78)\n\tat org.gradle.wrapper.Install$1.call(Install.java:48)\n\tat org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)\n\tat org.gradle.wrapper.Install.createDist(Install.java:48)\n\tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)\n\tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_java --label=renovate_child -v \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\":\"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/henrist/renovate-repro-gradle-wrapper\" docker.io/renovate/java:16.0.2 bash -l -c \"./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.3.1-all.zip --gradle-distribution-sha256-sum b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce\"\nException in thread \"main\" java.lang.RuntimeException: Verification of Gradle distribution failed!\n\nYour Gradle distribution may have been tampered with.\nConfirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.\n\n Distribution Url: https://services.gradle.org/distributions/gradle-7.3.1-all.zip\nDownload Location: /home/ubuntu/.gradle/wrapper/dists/gradle-7.3.1-all/1cx39h5havz97e1a3lk0ekaa5/gradle-7.3.1-all.zip\nExpected checksum: 'a8da5b02437a60819cad23e10fc7e9cf32bcb57029d9cb277e26eeff76ce014b'\n  Actual checksum: 'b75392c5625a88bccd58a574552a5a323edca82dab5942d2d41097f809c6bcce'\n\n\tat org.gradle.wrapper.Install.verifyDownloadChecksum(Install.java:165)\n\tat org.gradle.wrapper.Install.access$800(Install.java:27)\n\tat org.gradle.wrapper.Install$1.call(Install.java:78)\n\tat org.gradle.wrapper.Install$1.call(Install.java:48)\n\tat org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)\n\tat org.gradle.wrapper.Install.createDist(Install.java:48)\n\tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)\n\tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)"
  }
}
DEBUG: Returning updated gradle-wrapper files(branch="renovate/gradle-7.x")
{
  "files": [
    "gradle/wrapper/gradle-wrapper.properties"
  ]
}
```
</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by hasanwhitesource**
## Changes

Will update distributionSha256Sum in the gradle-wrapper.properties if it should be updated.

Here is an example of renovate running on this branch : [example repo](https://github.com/hasanwhitesource/renovate-repro-gradle-wrapper/pull/10#issue-1158270497)

## Context

Closes #13081 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 1]
```diff
@@ -80,11 +80,16 @@ export async function updateArtifacts({
...
         await writeLocalFile(
           packageFileName,
-          newPackageFileContent.replace(config.newValue, config.currentValue)
+          newPackageFileContent
+            .replace(config.newValue, config.currentValue)
+            .replace(
+              /distributionSha256Sum=.*/,
+              `distributionSha256Sum=${checksum}`
+            )
         );
```
Comment (henrist) [inline lib/manager/gradle-wrapper/artifacts.ts:92]: How does the file look after this operation?

I'm a bit surprised here since it's actually doing the following:

- Replace the _new_ version with the _old_
- But set the _new_ checksum

I can't see how that can be consistent. Old version with new checksum doesn't make sense?

I think, as I noted in https://github.com/renovatebot/renovate/issues/13081#issuecomment-992302289, that `replace(config.newValue, config.currentValue)` is not actually doing anything. If that's true it should be OK to remove that operation, but the comment above this code should be changed.

Comment (henrist) [reply lib/manager/gradle-wrapper/artifacts.ts:92]: For the gradle specifics its worth reading https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

As it's noted the gradle wrapper should be run _twice_ to also update the other wrapper files. This is because the first time we run gradle it will run on the old version, and second time it will run using the new version, and only then update other files.

If we do _not_ reset version, we have actually done the first run using Renovate alone. So the "first" gradle run will act as the second run. It will download the _new_ version and upgrade the related wrapper files using the correct version.

Comment (hasanwhitesource) [reply lib/manager/gradle-wrapper/artifacts.ts:92]: @henrist Here is how it'll look : https://github.com/hasanwhitesource/renovate-repro-gradle-wrapper/blob/9aad840f190804136b6ae918aaf281b8c5f80b12/gradle/wrapper/gradle-wrapper.properties#L3
`replace(config.newValue, config.currentValue)` is replacing the new version with the old version in your gradle-wrapper.properties.
It was updating the gradle with no problem but we weren't setting the new sha.

Comment (henrist) [reply lib/manager/gradle-wrapper/artifacts.ts:92]: You are referring to the final result, not the intermediate result I was refering to. I'm thinking of how it looks at the time the "gradlew" command is run (the data written by the call to `writeLocalFile`).

The code _tries_ to "revert" the contents of the file. But I suspect it is not doing that for some reason. Looking at the contents of the file _at this point in code_ will show if the replace operation worked or not.

Comment (hasanwhitesource) [reply lib/manager/gradle-wrapper/artifacts.ts:92]: @henrist I have tried it and also saw that the command is being executed with the correct sha. The gradle command was executing correctly.
The problem here was simply we didn't have a logic that was updating the sha in the file (in case of a sha)

This is the "gradlew" command that is being executed in your case : 
`'gradlew.bat wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.4-all.zip --gradle-distribution-sha256-sum cd5c2958a107ee7f0722004a12d0f8559b4564c34daad7df06cffd4d12a426d0'`

This is the correct sha.

Comment (viceice) [reply lib/manager/gradle-wrapper/artifacts.ts:92]: We previously reset the version in file to the old, because it was already done by the renovate auto replace.

If we then run Gradle without resetting, there is a checksum mismatch, as the new version and the old checksum collides.

Which checksum is written with this change?

Comment (viceice) [reply lib/manager/gradle-wrapper/artifacts.ts]: > Note that running the wrapper task once will update gradle-wrapper.properties only, but leave the wrapper itself in gradle-wrapper.jar untouched. This is usually fine as new versions of Gradle can be run even with ancient wrapper files. If you nevertheless want all the wrapper files to be completely up-to-date, you’ll need to run the wrapper task a second time.

So instead of reset the version to the old value, we need to update the checksum to the new value and then run Gradle to update wrapper.

The checksum should only be fetched, if there is an existing value.

Comment (hasanwhitesource) [reply lib/manager/gradle-wrapper/artifacts.ts]: @viceice  @henrist The new checksum is being written as see.
Here is an example repo : https://github.com/hasanwhitesource/renovate-repro-gradle-wrapper/pull/12/files#diff-40640fe1078ece83d7ea8fb67daacd77923a86d13447baf9769660b3b46f2eceR3

Comment (hasanwhitesource) [reply lib/manager/gradle-wrapper/artifacts.ts]: @viceice So we only need to update the sha in the file and remove the change from old version to new version?
Tried it that way and it worked, just want to make sure if updating the file is necessary here.

Comment (viceice) [reply lib/manager/gradle-wrapper/artifacts.ts]: It can be done here to fix the issue.

A better solution would be to use renovate digest update, so the checksum will be updated in same step as the new version is written.

**Comment by hasanwhitesource** [comment]
@viceice Any updates here ?

**Review by viceice — APPROVED** [review]
