### PR TITLE
fix(lookup): avoid unstable versions when rolling back

### LINKED ISSUE #14878: Rollback installing an unstable version
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.10.2

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.4.2-ee

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When rolling back a package version, Renovate will use an unstable version even though `ignoreUnstable` is set to `true` (the default value). Normal updates work as supposed to and unstable versions are ignored.

This only happens if the latest version in a package source happens to be an unstable one. The problem applies at least to NuGet and npm packages.

We are using a self-hosted version with GitLab, but I have created a [minimal reproduction repository](https://github.com/johannesvaltonen/renovate-rollback) in GitHub.

- There is a [.NET project file having a single dependency](https://github.com/johannesvaltonen/renovate-rollback/blob/main/Test.csproj#L11) with a version number that doesn't exist in nuget.org.
- At the time of writing this, the latest version of the dependency is an unstable one ([7.0.0-preview.2.22152.2](https://www.nuget.org/packages/Microsoft.NETCore.Platforms/7.0.0-preview.2.22152.2)).
- Renovate configuration has `"rollbackPrs": true`
- As far as I understand, the default value of `ignoreUnstable` should be `true`. In our internal environment we have it explicitly set.
- Running Renovate leads to a [pull request to update to the unstable version](https://github.com/johannesvaltonen/renovate-rollback/pull/4) created.

The logs do not contain any errors.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: No dangling containers to remove
INFO: Repository started
{
  "renovateVersion": "32.10.0"
}
DEBUG: Using localDir: /mnt/renovate/gh/johannesvaltonen/renovate-rollback
DEBUG: Repository cache is valid
DEBUG: initRepo("johannesvaltonen/renovate-rollback")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: johannesvaltonen/renovate-rollback default branch = main
DEBUG: Using app token for git init
DEBUG: resetMemCache()
DEBUG: Resetting npmrc
DEBUG: detectSemanticCommits()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: Checking cached config file name
DEBUG: Existing config file confirmed
DEBUG: Repo is onboarded
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ],
    "rollbackPrs": true
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ],
    "rollbackPrs": true
  }
}
DEBUG: Setting hostRules from config
DEBUG: Found repo ignorePaths
{
  "ignorePaths": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/examples/**",
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**",
    "**/__fixtures__/**"
  ]
}
DEBUG: No vulnerability alerts found
DEBUG: No vulnerability alerts found
DEBUG: findIssue(Dependency Dashboard)
DEBUG: Retrieving issueList
DEBUG: Retrieved 1 issues
DEBUG: Found issue 2
DEBUG: No baseBranches
DEBUG: extract()
DEBUG: Setting current branch to main
DEBUG: Initializing git repository into /mnt/renovate/gh/johannesvaltonen/renovate-rollback
DEBUG: Performing blobless clone
DEBUG: git clone completed
{
  "durationMs": 1104
}
DEBUG: latest repository commit
{
  "latestCommit": {
    "hash": "63f633f8d981f7d24047e46691214d6491fb5b0d",
    "date": "2022-03-31T14:02:16+03:00",
    "message": "Update Test.csproj",
    "refs": "HEAD -> main, origin/main, origin/HEAD",
    "body": "",
    "author_name": "Johannes Valtonen",
    "author_email": "johannes.valtonen@cgi.com"
  }
}
DEBUG: latest commit
{
  "branchName": "main",
  "latestCommitDate": "2022-03-31T14:02:16+03:00"
}
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible
DEBUG: Using file match: (^|/)requirements\.ya?ml$ for manager ansible-galaxy
DEBUG: Using file match: (^|/)galaxy\.ya?ml$ for manager ansible-galaxy
DEBUG: Using file match: azure.*pipelines?.*\.ya?ml$ for manager azure-pipelines
DEBUG: Using file match: (^|/)batect(-bundle)?\.yml$ for manager batect
DEBUG: Using file match: (^|/)batect$ for manager batect-wrapper
DEBUG: Using file match: (^|/)WORKSPACE(|\.bazel)$ for manager bazel
DEBUG: Using file match: \.bzl$ for manager bazel
DEBUG: Using file match: (^|/)\.?bitbucket-pipelines\.ya?ml$ for manager bitbucket-pipelines
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite
DEBUG: Using file match: (^|/)Gemfile$ for manager bundler
DEBUG: Using file match: \.cake$ for manager cake
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci
DEBUG: Using file match: (^|/)cloudbuild.ya?ml for manager cloudbuild
DEBUG: Using file match: (^|/)Podfile$ for manager cocoapods
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer
DEBUG: Using file match: (^|/)conanfile\.(txt|py)$ for manager conan
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: Using file match: (^|/|\.)Dockerfile$ for manager dockerfile
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci
DEBUG: Using file match: (^|/)flux-system/gotk-components\.yaml$ for manager flux
DEBUG: Using file match: (^|\/)\.fvm\/fvm_config\.json$ for manager fvm
DEBUG: Using file match: (^|/).gitmodules$ for manager git-submodules
DEBUG: Using file match: (^workflow-templates|\.github\/workflows)\/[^/]+\.ya?ml$ for manager github-actions
DEBUG: Using file match: (^|\/)action\.ya?ml$ for manager github-actions
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci-include
DEBUG: Using file match: (^|/)go.mod$ for manager gomod
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle
DEBUG: Using file match: (^|\/)gradle\.properties$ for manager gradle
DEBUG: Using file match: (^|\/)gradle\/.+\.toml$ for manager gradle
DEBUG: Using file match: \.versions\.toml$ for manager gradle
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper
DEBUG: Using file match: (^|/)requirements\.yaml$ for manager helm-requirements
DEBUG: Using file match: (^|/)values.yaml$ for manager helm-values
DEBUG: Using file match: (^|/)helmfile.yaml$ for manager helmfile
DEBUG: Using file match: (^|/)Chart.yaml$ for manager helmv3
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew
DEBUG: Using file match: \.html?$ for manager html
DEBUG: Using file match: (^|/)plugins\.(txt|ya?ml)$ for manager jenkins
DEBUG: Using file match: (^|/)jsonnetfile.json$ for manager jsonnet-bundler
DEBUG: Using file match: (^|/)kustomization\.ya?ml$ for manager kustomize
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen
DEBUG: Using file match: (^|/|\.)pom\.xml$ for manager maven
DEBUG: Using file match: ^(((\.mvn)|(\.m2))/)?settings\.xml$ for manager maven
DEBUG: Using file match: (^|/)package.js$ for manager meteor
DEBUG: Using file match: (^|/)mix\.exs$ for manager mix
DEBUG: Using file match: (^|/).node-version$ for manager nodenv
DEBUG: Using file match: (^|/)package.json$ for manager npm
DEBUG: Using file match: \.(?:cs|fs|vb)proj$ for manager nuget
DEBUG: Using file match: \.(?:props|targets)$ for manager nuget
DEBUG: Using file match: (^|\/)dotnet-tools\.json$ for manager nuget
DEBUG: Using file match: (^|\/)global\.json$ for manager nuget
DEBUG: Using file match: (^|/)\.nvmrc$ for manager nvm
DEBUG: Using file match: (^|/)([\w-]*)requirements\.(txt|pip)$ for manager pip_requirements
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup
DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry
DEBUG: Using file match: (^|/)\.pre-commit-config\.yaml$ for manager pre-commit
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub
DEBUG: Using file match: (^|/).python-version$ for manager pyenv
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version
DEBUG: Using file match: \.sbt$ for manager sbt
DEBUG: Using file match: project/[^/]*.scala$ for manager sbt
DEBUG: Using file match: (^|/)setup\.cfg$ for manager setup-cfg
DEBUG: Using file match: (^|/)Package\.swift for manager swift
DEBUG: Using file match: \.tf$ for manager terraform
DEBUG: Using file match: (^|/)\.terraform-version$ for manager terraform-version
DEBUG: Using file match: (^|/)terragrunt\.hcl$ for manager terragrunt
DEBUG: Using file match: (^|/)\.terragrunt-version$ for manager terragrunt-version
DEBUG: Using file match: ^.travis.yml$ for manager travis
DEBUG: Matched 1 file(s) for manager nuget: Test.csproj
DEBUG: Found nuget package files
DEBUG: Found 1 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "main",
  "stats": {
    "managers": {
      "nuget": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 1
    }
  }
}
DEBUG: Current version not found - rolling back(packageFile="Test.csproj")
{
  "depName": "Microsoft.NETCore.Platforms",
  "currentValue": "8.0.0"
}
DEBUG: Versions found before rolling back (Microsoft.NETCore.Platforms)(dependency="Microsoft.NETCore.Platforms")
{
  "versions": [
    {
      "version": "1.0.0-beta-23019",
      "releaseTimestamp": "2015-06-30T16:50:16.507Z"
    },
    {
      "version": "1.0.0-beta-23109",
      "releaseTimestamp": "2015-07-27T16:30:54.927Z"
    },
    {
      "version": "1.0.0",
      "releaseTimestamp": "2015-07-29T09:09:48.817Z"
    },
    {
      "version": "1.0.1-beta-23225",
      "releaseTimestamp": "2015-09-01T23:30:21.950Z"
    },
    {
      "version": "1.0.1-beta-23409",
      "releaseTimestamp": "2015-10-15T16:37:33.077Z"
    },
    {
      "version": "1.0.1-beta-23516",
      "releaseTimestamp": "2015-11-18T12:56:45.340Z"
    },
    {
      "version": "1.0.1-rc2-24027",
      "releaseTimestamp": "2016-05-16T13:47:52.787Z"
    },
    {
      "version": "1.0.1",
      "releaseTimestamp": "2016-06-27T11:54:44.760Z"
    },
    {
      "version": "1.0.2",
      "releaseTimestamp": "2016-12-13T00:24:55.837Z"
    },
    {
      "version": "1.1.0-preview1-24530-04",
      "releaseTimestamp": "2016-10-24T16:17:40.857Z"
    },
    {
      "version": "1.1.0",
      "releaseTimestamp": "2016-11-15T23:22:26.640Z"
    },
    {
      "version": "1.1.1",
      "releaseTimestamp": "2018-07-10T15:35:26.940Z"
    },
    {
      "version": "1.1.2",
      "releaseTimestamp": "2019-02-12T16:16:00.870Z"
    },
    {
      "version": "2.0.0-preview1-25305-02",
      "releaseTimestamp": "2017-05-09T22:22:59.300Z"
    },
    {
      "version": "2.0.0-preview2-25405-01",
      "releaseTimestamp": "2017-06-27T23:15:05.337Z"
    },
    {
      "version": "2.0.0",
      "releaseTimestamp": "2017-08-11T18:12:28.793Z"
    },
    {
      "version": "2.0.1",
      "releaseTimestamp": "2017-11-14T17:23:28.990Z"
    },
    {
      "version": "2.0.2",
      "releaseTimestamp": "2018-04-16T20:06:15.107Z"
    },
    {
      "version": "2.1.0-preview1-26216-02",
      "releaseTimestamp": "2018-02-26T21:18:35.350Z"
    },
    {
      "version": "2.1.0-preview2-26406-04",
      "releaseTimestamp": "2018-04-10T01:12:57.140Z"
    },
    {
      "version": "2.1.0-rc1",
      "releaseTimestamp": "2018-05-06T23:05:33.720Z"
    },
    {
      "version": "2.1.0",
      "releaseTimestamp": "2018-05-29T20:11:24.037Z"
    },
    {
      "version": "2.1.1-servicing-26724-03",
      "isDeprecated": true,
      "releaseTimestamp": "1900-01-01T00:00:00.000Z"
    },
    {
      "version": "2.1.1-servicing-26902-02",
      "isDeprecated": true,
      "releaseTimestamp": "1900-01-01T00:00:00.000Z"
    },
    {
      "version": "2.1.1",
      "releaseTimestamp": "2018-08-21T15:07:38.580Z"
    },
    {
      "version": "2.1.2",
      "releaseTimestamp": "2018-11-13T00:03:23.097Z"
    },
    {
      "version": "2.1.3",
      "releaseTimestamp": "2019-03-11T23:01:10.643Z"
    },
    {
      "version": "2.1.4",
      "releaseTimestamp": "2019-04-09T15:10:33.257Z"
    },
    {
      "version": "2.1.5",
      "releaseTimestamp": "2019-07-09T14:51:33.417Z"
    },
    {
      "version": "2.1.6",
      "releaseTimestamp": "2019-09-10T14:13:58.513Z"
    },
    {
      "version": "2.1.7",
      "releaseTimestamp": "2019-11-18T23:33:11.410Z"
    },
    {
      "version": "2.1.8",
      "releaseTimestamp": "2020-02-18T16:26:46.250Z"
    },
    {
      "version": "2.1.9",
      "releaseTimestamp": "2020-03-24T17:09:44.473Z"
    },
    {
      "version": "2.1.10",
      "releaseTimestamp": "2020-05-12T14:53:39.240Z"
    },
    {
      "version": "2.1.11",
      "releaseTimestamp": "2020-08-11T14:12:25.593Z"
    },
    {
      "version": "2.1.12",
      "releaseTimestamp": "2020-09-08T14:10:04.107Z"
    },
    {
      "version": "2.1.13",
      "releaseTimestamp": "2021-03-09T14:18:33.850Z"
    },
    {
      "version": "2.1.14",
      "releaseTimestamp": "2021-05-11T14:02:10.257Z"
    },
    {
      "version": "2.2.0-preview2-26905-02",
      "releaseTimestamp": "2018-09-12T15:01:46.450Z"
    },
    {
      "version": "2.2.0-preview3-27014-02",
      "releaseTimestamp": "2018-10-17T15:04:31.263Z"
    },
    {
      "version": "2.2.0",
      "releaseTimestamp": "2018-12-03T23:04:23.440Z"
    },
    {
      "version": "2.2.1",
      "releaseTimestamp": "2019-05-14T12:40:48.230Z"
    },
    {
      "version": "2.2.2",
      "releaseTimestamp": "2019-07-09T14:44:42.970Z"
    },
    {
      "version": "2.2.3",
      "releaseTimestamp": "2019-09-10T14:13:51.160Z"
    },
    {
      "version": "2.2.4",
      "releaseTimestamp": "2019-11-18T23:13:12.427Z"
    },
    {
      "version": "3.0.0-preview.18571.3",
      "releaseTimestamp": "2018-12-03T23:40:06.363Z"
    },
    {
      "version": "3.0.0-preview.19073.11",
      "releaseTimestamp": "2019-01-29T16:14:17.893Z"
    },
    {
      "version": "3.0.0-preview3.19128.7",
      "releaseTimestamp": "2019-03-06T17:10:16.070Z"
    },
    {
      "version": "3.0.0-preview4.19212.13",
      "releaseTimestamp": "2019-04-18T21:00:20.553Z"
    },
    {
      "version": "3.0.0-preview5.19224.8",
      "releaseTimestamp": "2019-05-06T12:31:18.783Z"
    },
    {
      "version": "3.0.0-preview6.19264.9",
      "releaseTimestamp": "2019-09-04T15:50:26.790Z"
    },
    {
      "version": "3.0.0-preview6.19303.8",
      "releaseTimestamp": "2019-06-12T03:47:48.273Z"
    },
    {
      "version": "3.0.0-preview7.19362.9",
      "releaseTimestamp": "2019-07-23T14:05:09.980Z"
    },
    {
      "version": "3.0.0-preview8.19405.3",
      "releaseTimestamp": "2019-08-13T15:34:49.457Z"
    },
    {
      "version": "3.0.0-preview9.19416.11",
      "releaseTimestamp": "2019-09-04T15:50:29.433Z"
    },
    {
      "version": "3.0.0-preview9.19421.4",
      "releaseTimestamp": "2019-09-04T15:50:32.223Z"
    },
    {
      "version": "3.0.0-rc1.19456.4",
      "releaseTimestamp": "2019-09-16T15:27:27.323Z"
    },
    {
      "version": "3.0.0",
      "releaseTimestamp": "2019-09-23T14:14:34.590Z"
    },
    {
      "version": "3.0.1",
      "releaseTimestamp": "2020-01-14T17:14:43.437Z"
    },
    {
      "version": "3.1.0-preview1.19504.10",
      "releaseTimestamp": "2019-10-15T15:52:28.597Z"
    },
    {
      "version": "3.1.0-preview2.19523.17",
      "releaseTimestamp": "2019-11-01T22:08:48.363Z"
    },
    {
      "version": "3.1.0-preview3.19551.4",
      "releaseTimestamp": "2019-11-13T23:07:52.100Z"
    },
    {
      "version": "3.1.0",
      "releaseTimestamp": "2019-12-03T16:39:41.167Z"
    },
    {
      "version": "3.1.1",
      "releaseTimestamp": "2020-05-12T14:56:37.330Z"
    },
    {
      "version": "3.1.2",
      "releaseTimestamp": "2020-08-11T14:15:19.880Z"
    },
    {
      "version": "3.1.3",
      "releaseTimestamp": "2020-09-08T14:09:16.367Z"
    },
    {
      "version": "3.1.4",
      "releaseTimestamp": "2021-02-09T14:32:08.780Z"
    },
    {
      "version": "3.1.5",
      "releaseTimestamp": "2021-03-09T14:24:53.387Z"
    },
    {
      "version": "3.1.6",
      "releaseTimestamp": "2021-04-06T21:12:30.767Z"
    },
    {
      "version": "3.1.7",
      "releaseTimestamp": "2021-06-08T13:58:17.660Z"
    },
    {
      "version": "3.1.8",
      "releaseTimestamp": "2021-09-14T13:46:07.920Z"
    },
    {
      "version": "3.1.9",
      "releaseTimestamp": "2021-10-11T21:07:26.317Z"
    },
    {
      "version": "5.0.0-preview.1.20120.5",
      "releaseTimestamp": "2020-03-16T16:37:58.113Z"
    },
    {
      "version": "5.0.0-preview.2.20160.6",
      "releaseTimestamp": "2020-04-02T14:08:15.257Z"
    },
    {
      "version": "5.0.0-preview.3.20214.6",
      "releaseTimestamp": "2020-04-23T15:37:03.290Z"
    },
    {
      "version": "5.0.0-preview.4.20251.6",
      "releaseTimestamp": "2020-05-18T22:08:23.953Z"
    },
    {
      "version": "5.0.0-preview.5.20278.1",
      "releaseTimestamp": "2020-06-10T15:15:53.680Z"
    },
    {
      "version": "5.0.0-preview.6.20305.6",
      "releaseTimestamp": "2020-06-25T15:03:33.190Z"
    },
    {
      "version": "5.0.0-preview.7.20364.11",
      "releaseTimestamp": "2020-07-21T14:54:21.520Z"
    },
    {
      "version": "5.0.0-preview.8.20407.11",
      "releaseTimestamp": "2020-08-25T14:45:34.243Z"
    },
    {
      "version": "5.0.0-rc.1.20451.14",
      "releaseTimestamp": "2020-09-14T14:46:42.303Z"
    },
    {
      "version": "5.0.0-rc.2.20475.5",
      "releaseTimestamp": "2020-10-13T14:44:18.757Z"
    },
    {
      "version": "5.0.0",
      "releaseTimestamp": "2020-11-09T23:41:36.223Z"
    },
    {
      "version": "5.0.1",
      "releaseTimestamp": "2021-02-09T14:35:32.943Z"
    },
    {
      "version": "5.0.2",
      "releaseTimestamp": "2021-04-06T11:27:45.927Z"
    },
    {
      "version": "5.0.3",
      "releaseTimestamp": "2021-09-14T13:45:10.167Z"
    },
    {
      "version": "5.0.4",
      "releaseTimestamp": "2021-10-12T14:04:59.117Z"
    },
    {
      "version": "6.0.0-preview.1.21102.12",
      "releaseTimestamp": "2021-02-12T23:46:17.987Z"
    },
    {
      "version": "6.0.0-preview.2.21154.6",
      "releaseTimestamp": "2021-03-11T16:41:51.573Z"
    },
    {
      "version": "6.0.0-preview.3.21201.4",
      "releaseTimestamp": "2021-04-08T19:50:18.713Z"
    },
    {
      "version": "6.0.0-preview.4.21253.7",
      "releaseTimestamp": "2021-05-24T21:51:35.757Z"
    },
    {
      "version": "6.0.0-preview.5.21301.5",
      "releaseTimestamp": "2021-06-15T19:16:27.940Z"
    },
    {
      "version": "6.0.0-preview.6.21352.12",
      "releaseTimestamp": "2021-07-14T13:48:59.550Z"
    },
    {
      "version": "6.0.0-preview.7.21377.19",
      "releaseTimestamp": "2021-08-10T18:35:46.453Z"
    },
    {
      "version": "6.0.0-rc.1.21451.13",
      "releaseTimestamp": "2021-09-14T15:18:13.277Z"
    },
    {
      "version": "6.0.0-rc.2.21480.5",
      "releaseTimestamp": "2021-10-12T14:21:32.147Z"
    },
    {
      "version": "6.0.0",
      "releaseTimestamp": "2021-11-08T06:30:01.450Z"
    },
    {
      "version": "6.0.1",
      "releaseTimestamp": "2021-12-14T14:39:20.213Z"
    },
    {
      "version": "6.0.2-mauipre.1.22054.8",
      "releaseTimestamp": "2022-01-19T18:01:20.957Z"
    },
    {
      "version": "6.0.2-mauipre.1.22102.15",
      "releaseTimestamp": "2022-02-15T21:14:42.963Z"
    },
    {
      "version": "6.0.2",
      "releaseTimestamp": "2022-03-08T14:53:10.387Z"
    },
    {
      "version": "7.0.0-preview.1.22076.8",
      "releaseTimestamp": "2022-02-17T15:56:17.220Z"
    },
    {
      "version": "7.0.0-preview.2.22152.2",
      "releaseTimestamp": "2022-03-14T20:46:21.007Z"
    }
  ]
}
DEBUG: Package releases lookups complete
{
  "baseBranch": "main"
}
DEBUG: branchifyUpgrades
DEBUG: 1 flattened updates found: Microsoft.NETCore.Platforms
DEBUG: Returning 1 branch(es)
DEBUG: Fetching changelog: https://github.com/dotnet/runtime (8.0.0 -> 7.0.0-preview.2.22152.2)
DEBUG: No releases
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "nuget": [
      {
        "packageFile": "Test.csproj",
        "deps": [
          {
            "datasource": "nuget",
            "depType": "nuget",
            "depName": "Microsoft.NETCore.Platforms",
            "currentValue": "8.0.0",
            "depIndex": 0,
            "updates": [
              {
                "bucket": "rollback",
                "newMajor": 7,
                "newValue": "7.0.0-preview.2.22152.2",
                "newVersion": "7.0.0-preview.2.22152.2",
                "updateType": "rollback",
                "branchName": "renovate/microsoft.netcore.platforms-rollback"
              }
            ],
            "warnings": [],
            "versioning": "nuget",
            "sourceUrl": "https://github.com/dotnet/runtime",
            "homepage": "https://dot.net/",
            "currentVersion": "8.0.0",
            "fixedVersion": "8.0.0"
          }
        ]
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 1 branch: renovate/microsoft.netcore.platforms-rollback
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 2 Pull Requests
DEBUG: currentHourStart=2022-03-31T11:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating prConcurrentLimit (10)
DEBUG: getBranchPr(renovate/microsoft.netcore.platforms-rollback)
DEBUG: findPr(renovate/microsoft.netcore.platforms-rollback, undefined, open)
DEBUG: findPr(renovate/microsoft.netcore.platforms-rollback, undefined, closed)
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 10
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 2
}
DEBUG: PullRequests limit = 2
DEBUG: Calculating hourly PRs remaining
DEBUG: currentHourStart=2022-03-31T11:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating branchConcurrentLimit (10)
DEBUG: 0 already existing branches found:
DEBUG: Branch concurrent limit remaining: 10
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 2
}
DEBUG: Branches limit = 2
DEBUG: Setting current branch to main(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: latest commit(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "branchName": "main",
  "latestCommitDate": "2022-03-31T14:02:16+03:00"
}
DEBUG: getBranchPr(renovate/microsoft.netcore.platforms-rollback)(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: findPr(renovate/microsoft.netcore.platforms-rollback, undefined, open)(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: findPr(renovate/microsoft.netcore.platforms-rollback, undefined, closed)(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: branchExists=false(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: recreateClosed is false(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: findPr(renovate/microsoft.netcore.platforms-rollback, Roll back dependency Microsoft.NETCore.Platforms to 7.0.0-preview.2.22152.2, !open)(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: prAlreadyExisted=false(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: Checking schedule(at any time, null)(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: No schedule defined(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: Branch needs creating(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: Using reuseExistingBranch: false(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: Starting search at index 321(packageFile="Test.csproj", branch="renovate/microsoft.netcore.platforms-rollback")
{
  "depName": "Microsoft.NETCore.Platforms"
}
DEBUG: Found match at index 321(packageFile="Test.csproj", branch="renovate/microsoft.netcore.platforms-rollback")
{
  "depName": "Microsoft.NETCore.Platforms"
}
DEBUG: Contents updated(packageFile="Test.csproj", branch="renovate/microsoft.netcore.platforms-rollback")
{
  "depName": "Microsoft.NETCore.Platforms"
}
DEBUG: nuget.updateArtifacts(Test.csproj)(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: No lock file found beneath package file.(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "packageFileName": "Test.csproj"
}
DEBUG: Updated 1 package files(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: No updated lock files in branch(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: 1 file(s) to commit(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: Preparing files for committing to branch renovate/microsoft.netcore.platforms-rollback(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: Setting git author name(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: git commit(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/microsoft.netcore.platforms-rollback",
    "commit": "7cbecc7",
    "root": false,
    "summary": {
      "changes": 1,
      "insertions": 1,
      "deletions": 0
    }
  }
}
DEBUG: Pushing branch renovate/microsoft.netcore.platforms-rollback(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: git push(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "result": {
    "pushed": [
      {
        "deleted": false,
        "tag": false,
        "branch": true,
        "new": true,
        "alreadyUpdated": false,
        "local": "refs/heads/renovate/microsoft.netcore.platforms-rollback",
        "remote": "refs/heads/renovate/microsoft.netcore.platforms-rollback"
      }
    ],
    "branch": {
      "local": "renovate/microsoft.netcore.platforms-rollback",
      "remote": "renovate/microsoft.netcore.platforms-rollback",
      "remoteName": "origin"
    },
    "ref": {
      "local": "refs/remotes/origin/renovate/microsoft.netcore.platforms-rollback"
    },
    "remoteMessages": {
      "all": [
        "Create a pull request for 'renovate/microsoft.netcore.platforms-rollback' on GitHub by visiting:",
        "https://github.com/johannesvaltonen/renovate-rollback/pull/new/renovate/microsoft.netcore.platforms-rollback"
      ],
      "pullRequestUrl": "https://github.com/johannesvaltonen/renovate-rollback/pull/new/renovate/microsoft.netcore.platforms-rollback"
    }
  }
}
INFO: Branch created(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "commitSha": "7cbecc7e2272c7c012418772fec8f9ebbff9006f"
}
DEBUG: Ensuring PR(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: getBranchPr(renovate/microsoft.netcore.platforms-rollback)(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: findPr(renovate/microsoft.netcore.platforms-rollback, undefined, open)(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: findPr(renovate/microsoft.netcore.platforms-rollback, undefined, closed)(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: Creating PR(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "prTitle": "Roll back dependency Microsoft.NETCore.Platforms to 7.0.0-preview.2.22152.2"
}
INFO: Creating Rollback PR(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: Creating PR(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "title": "Roll back dependency Microsoft.NETCore.Platforms to 7.0.0-preview.2.22152.2",
  "head": "johannesvaltonen:renovate/microsoft.netcore.platforms-rollback",
  "base": "main",
  "draft": false
}
DEBUG: PR created(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "pr": 4,
  "draft": false
}
DEBUG: Adding labels '' to #4(branch="renovate/microsoft.netcore.platforms-rollback")
INFO: PR created(branch="renovate/microsoft.netcore.platforms-rollback")
{
  "pr": 4,
  "prTitle": "Roll back dependency Microsoft.NETCore.Platforms to 7.0.0-preview.2.22152.2"
}
DEBUG: addAssigneesReviewers(pr=4)(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: Created Pull Request #4(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: PR is not configured for automerge(branch="renovate/microsoft.netcore.platforms-rollback")
DEBUG: getBranchPr(renovate/microsoft.netcore.platforms-rollback)
DEBUG: findPr(renovate/microsoft.netcore.platforms-rollback, undefined, open)
DEBUG: Found PR #4
DEBUG: Returning from graphql open PR list
DEBUG: Ensuring Dependency Dashboard
DEBUG: ensureIssue(Dependency Dashboard)
DEBUG: Patching issue
DEBUG: Issue updated
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/microsoft.netcore.platforms-rollback"
  ],
  "renovateBranches": [
    "renovate/microsoft.csharp-rollback",
    "renovate/microsoft.netcore.platforms-rollback"
  ]
}
DEBUG: remainingBranches=renovate/microsoft.csharp-rollback
DEBUG: findPr(renovate/microsoft.csharp-rollback, undefined, open)
DEBUG: Found PR #3
DEBUG: Branch has not been modified
{
  "branchName": "renovate/microsoft.csharp-rollback"
}
INFO: Autoclosing PR
{
  "branchName": "renovate/microsoft.csharp-rollback",
  "prNo": 3,
  "prTitle": "Roll back dependency Microsoft.CSharp to 4.7.0"
}
DEBUG: updatePr(3, Roll back dependency Microsoft.CSharp to 4.7.0 - autoclosed, body)
DEBUG: PR updated
{
  "pr": 3
}
DEBUG: Deleted remote branch
{
  "branchName": "renovate/microsoft.csharp-rollback"
}
DEBUG: No local branch to delete
{
  "branchName": "renovate/microsoft.csharp-rollback"
}
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {
    "init": 2040,
    "extract": 2414,
    "lookup": 625,
    "update": 2963
  },
  "total": 11414
}
DEBUG: http statistics
{
  "urls": {
    "https://api.github.com/graphql (POST)": 4,
    "https://api.github.com/repos/johannesvaltonen/renovate-rollback/contents/renovate.json (GET)": 1,
    "https://api.github.com/repos/johannesvaltonen/renovate-rollback/issues/2 (GET)": 2,
    "https://api.github.com/repos/johannesvaltonen/renovate-rollback/issues/2 (PATCH)": 1,
    "https://api.github.com/repos/johannesvaltonen/renovate-rollback/pulls (GET)": 1,
    "https://api.github.com/repos/johannesvaltonen/renovate-rollback/pulls (POST)": 1,
    "https://api.github.com/repos/johannesvaltonen/renovate-rollback/pulls/3 (PATCH)": 1,
    "https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json (GET)": 1,
    "https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/6.0.2/microsoft.netcore.platforms.nuspec (GET)": 1,
    "https://api.nuget.org/v3/registration5-gz-semver2/microsoft.netcore.platforms/index.json (GET)": 1
  },
  "hostStats": {
    "api.github.com": {
      "requestCount": 12,
      "requestAvgMs": 370,
      "queueAvgMs": 0
    },
    "api.nuget.org": {
      "requestCount": 2,
      "requestAvgMs": 211,
      "queueAvgMs": 0
    }
  },
  "totalRequests": 14
}
INFO: Repository finished
{
  "durationMs": 11414
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by MaronHatoum**
## Changes
 fix Rollback installing an unstable version 

## Context
Closes https://github.com/renovatebot/renovate/issues/14878

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [X] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/repository/process/lookup/rollback.ts [hunk 1]
```diff
@@ -38,12 +39,18 @@ export function getRollbackUpdate(
...
   // istanbul ignore if
   if (!newVersion) {
     logger.debug('No newVersion to roll back to');
     return null;
   }
+  while (
+    lessThanVersions.length !== 0 &&
+    !isVersionStable(newVersion, lessThanVersions, version)
+  ) {
+    newVersion = lessThanVersions.pop()?.version;
```
[the remark this answers is not in the document]
Comment (Gabriel-Ladzaretti) [reply lib/workers/repository/process/lookup/rollback.ts:52]: And we probably should `ignoreUnstable` into account before filtering unstable versions.

[the remark this answers is not in the document]
Comment (Gabriel-Ladzaretti) [reply lib/workers/repository/process/lookup/rollback.ts:52]: if we got to the while block and we couldnt find a stable version we will still return the last unstable vertion we checked. 
currently pop will never return `undefined` because of `lessThanVersions.length !== 0`.

thats why i suggest filtering the list if `ingoreUnstable == true` and then doing a single pop

**Review by PhilipAbed — DISMISSED** [review]
LGTM

File: lib/workers/repository/process/lookup/rollback.ts [hunk 2]
```diff
@@ -38,7 +40,16 @@ export function getRollbackUpdate(
     'Versions found before rolling back'
   );
   lessThanVersions.sort((a, b) => version.sortVersions(a.version, b.version));
-  const newVersion = lessThanVersions.pop()?.version;
+  let stableVersions;
+  let newVersion;
+  if (ignoreUnstable) {
+    stableVersions = lessThanVersions.filter((v) =>
+      isVersionStable(v.version, lessThanVersions, version)
```
Comment (Gabriel-Ladzaretti) [inline lib/workers/repository/process/lookup/rollback.ts:47]:
```suggestion
    stableVersions = lessThanVersions.filter(v =>
     version.isStable(v.version));
```
Could `isStable` be enough here?

**Review by Gabriel-Ladzaretti — DISMISSED** [review]

**Comment by Gabriel-Ladzaretti** [comment]
nit: `stableVersions` can be `const`
LGTM

**Review by Gabriel-Ladzaretti — DISMISSED** [review]

**Review by PhilipAbed — DISMISSED** [review]

**Review by rarkins — CHANGES_REQUESTED** [review]
If the currentVersion (which is missing) is unstable, we should be fine to roll back to an unstable.

Also, if *no* prior versions are stable, we should roll back to the highest unstable.

**Review by rarkins — CHANGES_REQUESTED** [review]
If `currentValue` is unstable then we should rollback to the highest lessThanVersion

**Comment by MaronHatoum** [comment]
> If `currentValue` is unstable then we should rollback to the highest lessThanVersion

even if we have a stable version?

**Comment by MaronHatoum** [comment]
> If `currentValue` is unstable then we should rollback to the highest lessThanVersion

even if we have a stable version?

File: lib/workers/repository/process/lookup/rollback.ts [hunk 3]
```diff
@@ -38,7 +38,19 @@ export function getRollbackUpdate(
...
+  const stableVersions = lessThanVersions.filter((v) =>
+    version.isStable(v.version)
+  );
+  if (version.isStable(currentValue)) {
+    newVersion = stableVersions.pop()?.version;
+  }
+  if (!version.isStable(currentValue)) {
+    newVersion = lessThanVersions.pop()?.version;
+  }
+  if (!newVersion) {
```
Comment (rarkins) [inline lib/workers/repository/process/lookup/rollback.ts:51]: The use of this if and the if above it makes no sense because they have the same code inside

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/workers/repository/process/lookup/index.spec.ts [hunk 4]
```diff
@@ -1038,6 +1038,7 @@ describe('workers/repository/process/lookup/index', () => {
       config.datasource = NpmDatasource.id;
       config.followTag = 'insiders';
       config.rollbackPrs = true;
+      config.ignoreUnstable = false;
```
Comment (rarkins) [inline lib/workers/repository/process/lookup/index.spec.ts:1041]: Is this needed?

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/workers/repository/process/lookup/rollback.ts [hunk 5]
```diff
@@ -39,7 +39,15 @@ export function getRollbackUpdate(
     'Versions found before rolling back'
   );
   lessThanVersions.sort((a, b) => version.sortVersions(a.version, b.version));
-  const newVersion = lessThanVersions.pop()?.version;
+  let newVersion;
+  if (version.isStable(currentValue)) {
```
Comment (rarkins) [inline lib/workers/repository/process/lookup/rollback.ts]:
```suggestion
  if (version.isStable(currentValue!)) {
```

Comment (MaronHatoum) [reply lib/workers/repository/process/lookup/rollback.ts]: image

Comment (rarkins) [reply lib/workers/repository/process/lookup/rollback.ts]: Your way of solving was fine too. It's acceptable to put an eslint ignore for this particular case if necessary in future

**Review by rarkins — APPROVED** [review]
