### PR TITLE
fix: Pass PROXY in child Process

### LINKED ISSUE #3733: proxy settings are not passed into external tools
Using Renovate CLI. While following up #3600, I came across the behaviour in the snippet below.

The machine this runs on must connect to the internet through a proxy, and environment variables *HTTP(S)_PROXY* are set for this purpose. `renovate` does successfully create "update dependency MRs", so the main renovate process is able to reach out to the internet to determine latest versions. The issue appears to be [here](https://github.com/renovatebot/renovate/blob/master/lib/manager/poetry/artifacts.js#L47) where proxy variables are not passed into the child environment. I will test this with a `trustLevel=high`, but I'm unsure of what the full implications of this setting are.

The process accepts a connection failure as "returning updated poetry.lock", this is probably not the intended behavior (lock file is unchanged because the process errored).

```
DEBUG: processBranch with 1 upgrades (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: getBranchPr(renovate/cryptography-2.x) (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: branchExists=false (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Branch has 1 upgrade(s) (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: recreateClosed is false (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: findPr(renovate/cryptography-2.x, Update dependency cryptography to v2.6.1, !open) (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: prAlreadyExisted=false (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Checking schedule(at any time, null) (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: No schedule defined (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
 INFO: Branch needs creating (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Using parentBranch: undefined (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: manager.getUpdatedPackageFiles() (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Replacing "=2.3.1" with "=2.6.1" at index 393 (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Updating packageFile content (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: poetry.getArtifacts(pyproject.toml) (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Updating poetry.lock (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
 INFO: Running poetry via global poetry (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
 INFO: Updated lockfile (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
       "seconds": 510,
       "type": "poetry.lock",
       "stdout": "Skipping virtualenv creation, as specified in config file.
Updating dependencies
Resolving dependencies...
",
       "stderr": "                                                                                
[ConnectionError]                                                
HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with ur  
l: /pypi/cfn-lint/0.9.0/json (Caused by NewConnectionError('<urllib3.connect  
ion.VerifiedHTTPSConnection object at 0x7fe17da18b00>: Failed to establish a  
 new connection: [Errno 110] Connection timed out'))                                                    
                                                                                
update [--no-dev] [--dry-run] [--lock] [--] [<packages>]...

"
DEBUG: Returning updated poetry.lock (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: poetry.lock is unchanged (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Updated 1 package files (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: No updated lock files in branch (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: 1 file(s) to commit (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Committing files to branch renovate/cryptography-2.x (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Checking if we can automerge branch (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: mergeStatus=no automerge (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Ensuring PR (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: There are 0 errors and 0 warnings (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: getBranchPr(renovate/cryptography-2.x) (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: getChangeLogJSON(args) (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
       "args": {
         "manager": "poetry",
         "versionScheme": "poetry",
         "depType": "dependencies",
         "depName": "cryptography",
         "fromVersion": "2.3.1",
         "toVersion": "2.6.1",
         "sourceUrl": "https://github.com/pyca/cryptography"
       }
DEBUG: Repository URL does not match any known hosts (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Creating PR (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
       "prTitle": "Update dependency cryptography to v2.6.1"
DEBUG: Creating Merge Request: Update dependency cryptography to v2.6.1 (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: POST (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
       "path": "projects/my/repo/merge_requests"
 INFO: PR created (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
       "pr": 10
 INFO: Created Merge Request #10 (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
DEBUG: Checking #10 for automerge (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
       "automerge": false,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: No automerge (repository=my/repo, dependencies=cryptography, branch=renovate/cryptography-2.x)
```

```
diff --git a/pyproject.toml b/pyproject.toml
index 5d9313d25197ac5044c3ca143b0fc1130a392b4b..e0b96f64bab6d22270d8328327f909f9cb5b45bd 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -12,7 +12,7 @@ requests_oauthlib = "^1.0"
 requests = "^2.19"
 pyjwt = {version = "^1.6",extras = ["crypto"]}
 aws-xray-sdk = "<2.2.0"  # moto conflict
-cryptography = "=2.3.1"  # weird install error with 2.4.1, released a few hours ago
+cryptography = "=2.6.1"  # weird install error with 2.4.1, released a few hours ago
 
 [tool.poetry.dev-dependencies]
 pytest-mock = "^1.10"
```

### PR DESCRIPTION
**Pull request by praveshtora**
Closes #3733

### CODE REVIEW

**Comment by praveshtora** [comment]
@rarkins is this what the intention is? If yes, then may be is it good to move env to globals?

**Comment by rarkins** [comment]
I discovered thanks to #4014 that the mere presence of process.env proxy variables can have an unintended affect on certain libs/apps, even if the value is undefined. It probably wouldn’t affect a child process but I think we should adopt an approach similar to #4015 and only pass through these bars if they are defined. 

This would add even more duplicate code so maybe we should centralise/DRY this env filtering first, and then add proxy env logic.

File: lib/workers/global/index.js [hunk 1]
```diff
@@ -56,6 +56,15 @@ async function start() {
       delete config[key];
     });
     global.trustLevel = config.trustLevel || 'low';
+    if (global.trustLevel === 'low') {
+      global.env = {
```
Comment (rarkins) [inline lib/workers/global/index.js]: Instead of global, let's create a new file lib/util/env.js that exports a function `getUntrustedEnv()`.

File: lib/util/env.js [hunk 2]
```diff
@@ -0,0 +1,13 @@
+function getUntrustedEnv() {
+  return {
+    HTTP_PROXY: process.env.HTTP_PROXY,
+    HTTPS_PROXY: process.env.HTTPS_PROXY,
+    NO_PROXY: process.env.NO_PROXY,
```
Comment (rarkins) [inline lib/util/env.js]: These need to be set only if defined. Check the other open PR for an example

File: lib/util/env.js [hunk 3]
```diff
@@ -0,0 +1,23 @@
+function getUntrustedEnv(...customEnvVars) {
+  const envVars = [
+    'HTTP_PROXY',
+    'HTTPS_PROXY',
+    'NO_PROXY',
+    'HOME',
+    'PATH',
+    ...customEnvVars,
```
Comment (rarkins) [inline lib/util/env.js]: Does this syntax definitely work? I thought passing an array of variables (as the one and only parameter) is maybe clearer.

File: lib/util/env.js [hunk 4]
```diff
@@ -0,0 +1,23 @@
+function getUntrustedEnv(...customEnvVars) {
```
Comment (rarkins) [inline lib/util/env.js]:
```suggestion
function getUntrustedEnv(customEnvVars = []) {
```

File: lib/util/env.js (hunk 3 above)
Comment (rarkins) [reply lib/util/env.js]: I've suggested the interface change above. Also for each variable we want to check first that it's defined, e.g. `if (typeof process.env[var] !== 'undefined')` similar to https://github.com/renovatebot/renovate/pull/4015/files#diff-aa656697b9687f2941a8a6da52236c18R13

**Review by rarkins — CHANGES_REQUESTED** [review]
Slight change to the structure of `getUntrustedEnv()`, plus make sure variables are set before copying them into the result.

File: lib/util/env.js (hunk 3 above)
Comment (praveshtora) [reply lib/util/env.js]: Yes most probably this function does the same thing, It first checks for environment variables definitions in Capital letters, if undefined it checks for lower case. If it's not defined it not set.This is the intent right?
And yes syntax works but it's not readable. I ll refactor it.

**Comment by rarkins** [comment]
Yes but we don’t care about lower case here. I just meant the way you first check if the variable is defined or not first.

**Comment by praveshtora** [comment]
I have updated the env.js. Is this a better approach?

File: lib/manager/composer/artifacts.js [hunk 5]
```diff
@@ -98,11 +99,7 @@ async function updateArtifacts(
     const env =
       global.trustLevel === 'high'
         ? process.env
-        : {
-            HOME: process.env.HOME,
-            PATH: process.env.PATH,
-            COMPOSER_CACHE_DIR: process.env.COMPOSER_CACHE_DIR,
-          };
+        : getUntrustedEnv('COMPOSER_CACHE_DIR');
```
Comment (rarkins) [inline lib/manager/composer/artifacts.js]:
```suggestion
        : getUntrustedEnv(['COMPOSER_CACHE_DIR']);
```

File: lib/manager/gomod/artifacts.js [hunk 6]
```diff
@@ -39,13 +40,7 @@ async function updateArtifacts(
...
     const localGoSumFileName = upath.join(config.localDir, sumFileName);
     const env =
-      global.trustLevel === 'high'
-        ? process.env
-        : {
-            HOME: process.env.HOME,
-            PATH: process.env.PATH,
-            GOPATH: process.env.GOPATH,
-          };
+      global.trustLevel === 'high' ? process.env : getUntrustedEnv('GOPATH');
```
Comment (rarkins) [inline lib/manager/gomod/artifacts.js]:
```suggestion
      global.trustLevel === 'high' ? process.env : getUntrustedEnv(['GOPATH']);
```

File: lib/manager/pipenv/artifacts.js [hunk 7]
```diff
@@ -34,13 +35,7 @@ async function updateArtifacts(
...
       global.trustLevel === 'high'
         ? process.env
-        : {
-            HOME: process.env.HOME,
-            PATH: process.env.PATH,
-            LC_ALL: process.env.LC_ALL,
-            LANG: process.env.LANG,
-            PIPENV_CACHE_DIR: process.env.PIPENV_CACHE_DIR,
-          };
+        : getUntrustedEnv('LANG', 'PIPENV_CACHE_DIR');
```
Comment (rarkins) [inline lib/manager/pipenv/artifacts.js]:
```suggestion
        : getUntrustedEnv(['LANG', 'PIPENV_CACHE_DIR']);
```

**Review by rarkins — CHANGES_REQUESTED** [review]
Pass env vars as an array

**Comment by praveshtora** [comment]
@rarkins shall I proceed for writing test cases for it?

File: lib/manager/pipenv/artifacts.js [hunk 8]
```diff
@@ -34,13 +35,7 @@ async function updateArtifacts(
...
       global.trustLevel === 'high'
         ? process.env
-        : {
-            HOME: process.env.HOME,
-            PATH: process.env.PATH,
-            LC_ALL: process.env.LC_ALL,
-            LANG: process.env.LANG,
-            PIPENV_CACHE_DIR: process.env.PIPENV_CACHE_DIR,
-          };
+        : getUntrustedEnv(['LANG', 'PIPENV_CACHE_DIR']);
```
Comment (rarkins) [inline lib/manager/pipenv/artifacts.js]:
```suggestion
        : getUntrustedEnv(['LC_ALL', 'LANG', 'PIPENV_CACHE_DIR']);
```

Comment (praveshtora) [reply lib/manager/pipenv/artifacts.js]: My bad, I missed it.

**Comment by rarkins** [comment]
@kadrach are you able to test this PR if it works in your environment? In short: it will pass proxy variables to child processes by default.

**Review by rarkins — APPROVED** [review]

**Comment by rarkins** [comment]
- [ ] Awaiting tests. Need to make sure child process still gets passed the required existing vars in addition to proxy ones if available.

**Review by rarkins — CHANGES_REQUESTED** [review]
@praveshtora I think we can improve this even further:

- Rename `getUntrustedEnv` to be `getChildProcessEnv`
- Move `if (global.trustLevel === 'high')` logic into `lib/util/env.js` so that it's not repeated in each manager

**Comment by praveshtora** [comment]
@rarkins I have updated the code as per up your review comments

File: lib/util/env.js [hunk 9]
```diff
@@ -0,0 +1,24 @@
+function getChildProcessEnv(customEnvVars = []) {
+  if (global.trustLevel === 'high') {
+    return process.env;
```
Comment (rarkins) [inline lib/util/env.js]: To be safe, let's return a copy of process.env so that it doesn't matter if it's later modified.

**Review by rarkins — APPROVED** [review]
