### PR TITLE
fix(maven): Fix recursive props check

### LINKED ISSUE #18619: Does not detect some Maven plugin dependencies
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate doesn't seem to detect all dependencies.

I just activated Renovate in this repository: https://github.com/REGnosys/rosetta-dsl

In the [dashboard](https://github.com/REGnosys/rosetta-dsl/issues/435), I see for example that it detects [the pom file inside the submodule com.regnosys.rosetta.rosetta](https://github.com/REGnosys/rosetta-dsl/blob/master/com.regnosys.rosetta/pom.xml), but it doesn't show the dependency on xtext-maven-plugin; see [here](https://github.com/REGnosys/rosetta-dsl/blob/master/com.regnosys.rosetta/pom.xml#L67) (although it does detect dependencies on other plugins, such as exec-maven-plugin; see [here](https://github.com/REGnosys/rosetta-dsl/blob/master/com.regnosys.rosetta/pom.xml#L35)). There are other dependencies like this that don't get detected.

### Relevant debug logs

Gist: https://gist.github.com/SimonCockx/6087fa57fa026869f29b77f041acd342

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

Allow more than one placeholder occurrence

## Context

- Fixes: #18619

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/maven/extract.ts [hunk 1]
```diff
@@ -225,6 +227,7 @@ function applyPropsInternal(
     result.editFile = propSource;
   }
 
+  seenProps.forEach((prop) => previouslySeenProps.add(prop));
```
Comment (viceice) [inline lib/modules/manager/maven/extract.ts:230]: please use a normal for-of loop

**Review by viceice — COMMENTED** [review]
otherwise LGTM

**Review by rarkins — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
