### PR TITLE
fix(conan): improve dependency detection

### LINKED ISSUE #38161: Conan: incorrect dependencies detection
### Discussed in https://github.com/renovatebot/renovate/discussions/38160

<div type='discussions-op-text'>

<sup>Originally posted by **ericLemanissier** September 22, 2025</sup>
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

v41.123.0 on docker, in gitea

### Please tell us more about your question or problem

Hi, it's great to see conan dependencies being updated by renovate !
I just noticed a bug though: the presence of a `#` in some strings seems to be analysed as a dependency declaration, even if the string is not used in any `requires()` function call. for example:
```
                raise ConanInvalidConfiguration(
                    f"structopt: Unsupported compiler: {self.settings.compiler}-{self.settings.compiler.version} "
                    f"(https://github.com/p-ranav/structopt#compiler-compatibility)."
                )
```
Triggers the following PR:
| Package | Type | Update | Change |
|---|---|---|---|
| com | requires | digest | `co` ->  |

---

> ⚠️ **Warning**
> 
> Some dependencies could not be looked up. Check the Dependency Dashboard for more information.

Also, the code `raise ConanInvalidConfiguration("gssapi cannot be enabled until conan-io/conan-center-index#4102 is closed")`
triggers the following PR:
| Package | Type | Update | Change |
|---|---|---|---|
| conan-io | requires | digest | `4102 ` ->  |

---

> ⚠️ **Warning**
> 
> Some dependencies could not be looked up. Check the Dependency Dashboard for more information.

In both cases, the code is in the `validate(self)` method, which should not be examined according to https://docs.renovatebot.com/modules/manager/conan/#additional-information

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
</div>

### PR DESCRIPTION
**Pull request by ericLemanissier**
## Changes

This PR improves dependencies detection for conan. it simply makes sure that all dependencies appear either at the beginning of a line (for conanfile.txt), or that they start with a quote (for conanfile.py)

## Context

Please select one of the below:

- [x] This closes an existing Issue: #38161
- [ ] This doesn't close an Issue, but I accept the risk that this PR may be closed if maintainers disagree with its opening or implementation

## AI assistance disclosure

Did you use AI tools to create any part of this pull request?

Please select one option and, if yes, briefly describe how AI was used (e.g., code, tests, docs) and which tool(s) you used.

- [X] No — I did not use AI for this contribution.
- [ ] Yes — minimal assistance (e.g., IDE autocomplete, small code completions, grammar fixes).
- [ ] Yes — substantive assistance (AI generated non‑trivial portions of code, tests, or documentation).
- [ ] Yes — other (please describe):

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [X] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

The public repository: <URL>

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Currently working on fixing the tests. I'll push when it passes locally

**Comment by ericLemanissier** [comment]
⚠️ I did not test this in a real-world scenario, only with the unit tests. It will break if the filename is not passed to `extractPackageFile` or if it contains folder names. I don't know how to run renovate locally.  `--platform=local`  fails with `Invalid configuration: repositories list not supported when platform=local`

File: lib/modules/manager/conan/extract.ts [hunk 1]
```diff
@@ -11,68 +11,98 @@ function setDepType(content: string, originalType: string): string {
   let depType = originalType;
   if (content.includes('python_requires')) {
     depType = 'python_requires';
-  } else if (content.includes('build_require')) {
```
Comment (viceice) [inline lib/modules/manager/conan/extract.ts:14]: why drop Conan v1 support?

**Review by viceice — COMMENTED** [review]
please split the refactor from the new feature

**Comment by ericLemanissier** [comment]
Thanks for the review. Which new feature are you talking about?
I'll re-add the support for conan v1, but the rest is only bug-fix

**Comment by ericLemanissier** [comment]
Ok, I found a way simpler fix: modify the regex so that it checks that the reference is either at the beginning of the string (for conanfile.txt), or it starts with a `"` or `'` (for conanfile.py)

With the new test fixture, but without the fix to the regex, the test fails with:

```
> renovate@0.0.0-semantic-release vitest /workspaces/renovate
> GIT_ALLOW_PROTOCOL=file LOG_LEVEL=fatal vitest run --logHeapUsage lib/modules/manager/conan/


 RUN  v3.2.4 /workspaces/renovate
      Coverage enabled with v8

 ✓ lib/modules/manager/conan/range.spec.ts (2 tests) 6ms 114 MB heap used
 ✓ lib/modules/manager/conan/artifacts.spec.ts (10 tests) 24ms 115 MB heap used
 ❯ lib/modules/manager/conan/extract.spec.ts (4 tests | 1 failed) 30ms 116 MB heap used
   ✓ modules/manager/conan/extract > extractPackageFile > returns null for empty 3ms
   ✓ modules/manager/conan/extract > extractPackageFile > extracts multiple image lines from conanfile.txt 3ms
   ✓ modules/manager/conan/extract > extractPackageFile > extracts multiple 0 lines from conanfile.txt 0ms
   × modules/manager/conan/extract > extractPackageFile > extracts multiple image lines from conanfile.py 21ms
     → expected [ { depName: 'pyreq', …(4) }, …(20) ] to deeply equal [ Array(19) ]

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  lib/modules/manager/conan/extract.spec.ts > modules/manager/conan/extract > extractPackageFile > extracts multiple image lines from conanfile.py
AssertionError: expected [ { depName: 'pyreq', …(4) }, …(20) ] to deeply equal [ Array(19) ]

- Expected
+ Received

@@ -132,6 +132,24 @@
      "depName": "tool_win",
      "depType": "build_requires",
      "packageName": "tool_win/0.1@user/stable",
      "replaceString": "tool_win/0.1@user/stable",
    },
+   {
+     "autoReplaceStringTemplate": "{{depName}}/{{newValue}}@_/_{{#if newDigest}}#{{newDigest}}{{/if}}",
+     "currentDigest": "4102 ",
+     "currentValue": "conan-center-index",
+     "depName": "conan-io",
+     "depType": "build_requires",
+     "packageName": "conan-io/conan-center-index@_/_",
+     "replaceString": "conan-io/conan-center-index#4102 ",
+   },
+   {
+     "autoReplaceStringTemplate": "{{depName}}/{{newValue}}@_/_{{#if newDigest}}#{{newDigest}}{{/if}}",
+     "currentDigest": "co",
+     "currentValue": "p-ranav/structopt",
+     "depName": "com",
+     "depType": "build_requires",
+     "packageName": "com/p-ranav/structopt@_/_",
+     "replaceString": "com/p-ranav/structopt#co",
+   },
  ]

 ❯ lib/modules/manager/conan/extract.spec.ts:136:25
    134|     it('extracts multiple image lines from conanfile.py', () => {
    135|       const res = extractPackageFile(conanfile3);
    136|       expect(res?.deps).toEqual([
       |                         ^
    137|         {
    138|           currentValue: '0.1',

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯


 Test Files  1 failed | 2 passed (3)
      Tests  1 failed | 15 passed (16)
   Start at  10:06:45
   Duration  12.28s (transform 1.96s, setup 1.24s, collect 13.15s, tests 60ms, environment 1ms, prepare 636ms)

 ELIFECYCLE  Command failed with exit code 1.
```

with the regex, it passes

**Review by viceice — APPROVED** [review]
