### PR TITLE
fix(proxy): only set variables if they they existed before

### LINKED ISSUE #4014: Not setting HTTP_PROXY, HTTPS_PROXY or NO_PROXY will result in an error
**What Renovate type are you using?**
Renovate CLI (self hosted)

**Describe the bug**
This bug happens since this commit: https://github.com/renovatebot/renovate/commit/36b938cd1dbe4b459ec42cf6f85295680a295d07

When not setting any of the env vars, authentication will fail:

>  Error authenticating with GitLab. Check that your token includes "user" permissions

and

> "message": "Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be \"http:\"."

**Did you see anything helpful in debug logs?**
see above

**To Reproduce**
Do not set any of the variables and try to run it via cli

**Expected behavior**
Should work as usual. By commenting out the changes in the mentioned commit, everything works.

**Additional context**
I will create a merge request following up this issue

### PR DESCRIPTION
**Pull request by Tanuel**
Only set environment variables if they they existed before

Closes #4014

### CODE REVIEW

File: lib/proxy.js [hunk 1]
```diff
@@ -4,7 +4,17 @@ module.exports = {
   bootstrap,
 };
 
+const envVars = ['HTTP_PROXY', 'HTTPS_PROXY', 'NO_PROXY'];
+
 function bootstrap() {
+  envVars.forEach(envVar => {
+    if (
+      typeof process.env[envVar] === 'undefined' &&
+      typeof process.env[envVar.toUpperCase()] !== 'undefined'
```
Comment (rarkins) [inline lib/proxy.js]: Should this be `toLowerCase()` ?

Comment (Tanuel) [reply lib/proxy.js]: Yes, my bad. fixed it

**Comment by rarkins** [comment]
Looks good but I’m going to wait to test it thoroughly to make sure!
