### PR TITLE
fix: remove authorization header from core.windows.net requests for Azure docker registries

### LINKED ISSUE #6640: Azure ACR authentication information is not given in the correct format
**What Renovate type are you using?**

CLI 21.21.2.

**Describe the bug**

Renovate is unable to fetch Docker manifest information from Azure Container Registry. See logs below.

It seems that during a refactoring the following change related to Azure blob were removed:

- initial issue: https://github.com/renovatebot/renovate/issues/5273
- fix PR: https://github.com/renovatebot/renovate/pull/5274
- revert commit by @rarkins: https://github.com/renovatebot/renovate/commit/74f24d5b0c8f5b7d9b721f4215a72e62b610130b

Any idea why those change were reverted?

**Did you see anything helpful in debug logs?**

```
         "statusMessage": "Authentication information is not given in the correct format. Check the value of Authorization header.",
         "headers": {
           "content-length": "298",
           "content-type": "application/xml",
           "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
           "x-ms-request-id": "4aa458b1-601e-000f-35c9-4e22e5000000",
           "date": "Tue, 30 Jun 2020 10:30:45 GMT",
           "connection": "close"
         },
         "body": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.\nRequestId:4aa458b1-601e-000f-35c9-4e22e5000000\nTime:2020-06-30T10:30:45.3074549Z</Message></Error>",
         "message": "Response code 400 (Authentication information is not given in the correct format. Check the value of Authorization header.)",
         "stack": "HTTPError: Response code 400 (Authentication information is not given in the correct format. Check the value of Authorization header.)\n    at EventEmitter.<anonymous> (/usr/src/app/node_modules/got/source/as-promise.js:74:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

**To Reproduce**

Run Renovate against a repository that make use of Docker containers hosted on a private Azure container registry. I used the kustomize manager for the test.

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by etiennetremel**
Add back the logic that remove the authorization header for requests made against Azure blob storage. 

It was initially added via this PR https://github.com/renovatebot/renovate/pull/5274, then reverted https://github.com/renovatebot/renovate/commit/74f24d5b0c8f5b7d9b721f4215a72e62b610130b.

For the unit tests, I'm struggling with mocking the redirect via nock, I'm available on Slack if someone could find time to give me a hint on how to implement that. I couldn't find similar unit tests for the [similar Amazon ECR logic](https://github.com/renovatebot/renovate/blob/master/lib/util/http/index.ts#L85-L97).

Closes #6640

### CODE REVIEW

File: lib/util/http/index.ts [hunk 1]
```diff
@@ -81,8 +81,11 @@ export class Http<GetOptions = HttpOptions, PostOptions = HttpPostOptions> {
     options.hooks = {
       beforeRedirect: [
         (opts: any): void => {
-          // Check if request has been redirected to Amazon
-          if (opts.search?.includes('X-Amz-Algorithm')) {
+          // Check if request has been redirected to Amazon or an Azure blob (ACR)
+          if (
+            opts.search?.includes('X-Amz-Algorithm') ||
+            opts.hostname?.endsWith('blob.core.windows.net')
```
Comment (viceice) [inline lib/util/http/index.ts:87]:
```suggestion
            opts.search?.includes('X-Amz-Algorithm') ||
            opts.hostname?.endsWith('blob.core.windows.net')  // lgtm [js/incomplete-url-substring-sanitization]
```

@etiennetremel Maybe we should check for the token in `search` like amazon instead of `hostname` test

Comment (etiennetremel) [reply lib/util/http/index.ts:87]: It's a bit tricky, Azure has a different behavior. There is nothing in `ops.search` that provide something similar to Amazon. Here is an example:

```
search: '?se=2020-07-01T07%3A44%3A59Z&sig=<sig>&sp=r&sr=b&sv=2016-05-31&regid=<regid>',
```

If you are worried about the host check, I can make it a bit more strict and match both the hostname and the presence of the path `/docker/registry` in the `opts.href`, which look like this:

```
href: 'https://<store>.blob.core.windows.net/<some id>//docker/registry/v2/blobs/sha256/53/<some id>/data?se=2020-07-01T07%3A44%3A59Z&sig=<sig>&sp=r&sr=b&sv=2016-05-31&regid=<regid>',
```

What do you think?

Comment (viceice) [reply lib/util/http/index.ts]: ok, please make it more strict. you can add a module scoped function to extract the azure check, so we don't have a huge if condition.

File: lib/util/http/index.ts [hunk 2]
```diff
@@ -57,6 +57,40 @@ async function resolveResponse<T>(
...
+function isAmazon(opts: any): boolean {
+  return opts.search?.includes('X-Amz-Algorithm');
+}
+
+// isAzureBlob return true if request options contains Azure container registry related data
+function isAzureBlob(opts: any): boolean {
+  return (
+    opts.hostname?.endsWith('blob.core.windows.net') &&
+    opts.href?.includes('/docker/registry')
+  ); // lgtm [js/incomplete-url-substring-sanitization]
```
Comment (viceice) [inline lib/util/http/index.ts:70]: I think this must be on same line as the test

File: lib/util/http/index.ts [hunk 3]
```diff
@@ -57,6 +57,40 @@ async function resolveResponse<T>(
...
 
+// isAmazon return true if request options contains Amazon related headers
+function isAmazon(opts: any): boolean {
+  return opts.search?.includes('X-Amz-Algorithm');
+}
+
+// isAzureBlob return true if request options contains Azure container registry related data
+function isAzureBlob(opts: any): boolean {
+  return (
+    opts.hostname?.endsWith('blob.core.windows.net') &&
```
Comment (viceice) [inline lib/util/http/index.ts:68]:
```suggestion
    opts.hostname?.endsWith('.blob.core.windows.net') &&
```
just make sure we also match the dot

File: lib/util/http/index.ts [hunk 4]
```diff
@@ -57,6 +57,40 @@ async function resolveResponse<T>(
...
+    opts.href?.includes('/docker/registry')
+  ); // lgtm [js/incomplete-url-substring-sanitization]
+}
+
+// removeAuthorizationHeaders from the redirect options
+export function removeAuthorizationHeaders(opts: any): any {
```
Comment (viceice) [inline lib/util/http/index.ts:74]: @rarkins I think it makes sense to move this to `util/http/auth.ts`. What do you think?

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/util/http/index.ts (hunk 4 above)
Comment (rarkins) [reply lib/util/http/index.ts:74]: I don't mind either way

Comment (viceice) [reply lib/util/http/index.ts:74]: Ok, for me it looks cleaner to move it to auth. So @etiennetremel can you please move that to the suggested file. 🙃

**Review by viceice — APPROVED** [review]
