### PR TITLE
fix: modify regex to be re2 compatbile

### LINKED ISSUE #12070: Refactor marked regex to be re2 compatible
### Describe the proposed change(s).

Renovate recently updated most of the normal regex to re2 format, but in some cases the new regex was not working as intended so we decided to keep them as it is with a flag `// TODO #12070`
For this issue, we need to make the normal regex with the flag `// TODO #12070` compatible with re2.
For eg. 
Old Code => ```npmrc.registry?.replace(/\/?$/, '/')   // TODO #12070```
New Code using re2 => ```npmrc.registry?.replace(regEx(("/?$", 'g'))```

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes:

Modified re2 incompatible  to be compatible.

## Context:

Closes #12070 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by RahulGautamSingh** [comment]
@viceice I need some help with  this regex, I cannot figure out why it doesn't work with re2.
https://github.com/renovatebot/renovate/blob/2754c58f0d2042111ae905776e80c43254b2aada/lib/util/emoji.ts#L58

File: lib/versioning/hashicorp/index.ts [hunk 1]
```diff
@@ -49,14 +49,14 @@ function getNewValue({
...
-        /(?<prefix>~>\s*0\.)\d+(?<suffix>.*)$/, // TODO #12070
+        regEx(`(?<prefix>~>\\s*0\\.)\\d+(?<suffix>.*)$`), // TODO #12071
         replaceValue
       );
     }
     // handle special ~> 1.2 case
     if (regEx(/(~>\s*)\d+\.\d+$/).test(currentValue)) {
       return currentValue.replace(
-        /(?<prefix>~>\s*)\d+\.\d+$/, // TODO #12070
+        regEx(`(?<prefix>~>\\s*)\\d+\\.\\d+$`), // TODO #12071
```
Comment (viceice) [inline lib/versioning/hashicorp/index.ts:59]:
```suggestion
        regEx(`(?<prefix>~>\\s*)\\d+\\.\\d+$`),
```

I think #12071 no longer applies, as we're cache the regex instances.

https://github.com/renovatebot/renovate/blob/32d397348996ebe580a9eda4a0506f56728a680a/lib/util/regex.ts#L22-L39

So i think we can remove that todo from all `regEx` calls

File: lib/datasource/npm/npmrc.ts [hunk 2]
```diff
@@ -112,8 +112,7 @@ export function resolvePackage(packageName: string): PackageResolution {
     !authInfo &&
     npmrc &&
     npmrc._authToken &&
-    registryUrl.replace(regEx(/\/?$/), '/') ===
-      npmrc.registry?.replace(/\/?$/, '/') // TODO #12070
+    registryUrl.replace(/\/?$/, '/') === npmrc.registry?.replace(/\/?$/, '/') // TODO #12070
```
Comment (viceice) [inline lib/datasource/npm/npmrc.ts:115]: why this revert?

File: lib/logger/cmd-serializer.ts [hunk 3]
```diff
@@ -3,7 +3,7 @@ export default function cmdSerializer(
   cmd: string | string[]
 ): string | string[] {
   if (typeof cmd === 'string') {
-    return cmd.replace(/https:\/\/[^@]*@/g, 'https://**redacted**@'); // TODO #12070
+    return cmd.replace(/https:\/\/[^@]*@/g, 'https://**redacted**@'); // TODO #12070 RE2 causes circular dependency
```
Comment (viceice) [inline lib/logger/cmd-serializer.ts:6]: We should open an issue upstream for this.

File: lib/manager/npm/update/package-version/index.ts [hunk 4]
```diff
@@ -31,7 +32,7 @@ export function bumpPackageVersion(
     }
     logger.debug({ newPjVersion });
     bumpedContent = content.replace(
-      /(?<version>"version":\s*")[^"]*/, // TODO #12070
+      regEx(`(?<version>"version":\\s*")[^"]*`), // TODO #12071
```
Comment (viceice) [inline lib/manager/npm/update/package-version/index.ts:35]:
```suggestion
      regEx(`(?<version>"version":\\s*")[^"]*`)
```

File: lib/manager/terraform/lockfile/hash.ts [hunk 5]
```diff
@@ -31,7 +32,7 @@ export class TerraformProviderHash {
 
       // add double space, the filename and a new line char
       rootHash.update('  ');
-      const fileName = file.replace(/^.*[\\/]/, ''); // TODO #12070
+      const fileName = file.replace(regEx(/^.*[\\/]/), '');
```
Comment (viceice) [inline lib/manager/terraform/lockfile/hash.ts:35]: i think we should use a `upath` function to extract filename instead of regex.
```suggestion
      const fileName = upath.basename(file);
```

File: lib/util/ignore.ts [hunk 6]
```diff
@@ -3,7 +3,7 @@ import { regEx } from './regex';
 
 export function isSkipComment(comment?: string): boolean {
   if (regEx(/^(renovate|pyup):/).test(comment)) {
-    // TODO #12070 #12071 needs to be checked manually
+    // TODO #12071
```
Comment (viceice) [inline lib/util/ignore.ts:6]:
```suggestion
```

File: lib/versioning/swift/index.ts [hunk 7]
```diff
@@ -37,7 +37,7 @@ const getSatisfyingVersion = (versions: string[], range: string): string =>
   );
 const minSatisfyingVersion = (versions: string[], range: string): string =>
   minSatisfying(
-    versions.map((v) => v.replace(regEx(/^v/), '')), // TODO #12071 #12070
+    versions.map((v) => v.replace(regEx(/^v/), '')), // TODO #12070
```
Comment (viceice) [inline lib/versioning/swift/index.ts:40]: Are you sure about the todo?

File: lib/versioning/hashicorp/index.ts (hunk 1 above)
Comment (rarkins) [reply lib/versioning/hashicorp/index.ts:59]: I think we should ideally still move them to the module scope, or do you think there's no benefit?

Comment (viceice) [reply lib/versioning/hashicorp/index.ts:59]: It would only make a little difference, as the function call will be saved. I don't think this will make a big difference.

File: lib/datasource/npm/npmrc.ts (hunk 2 above)
Comment (RahulGautamSingh) [reply lib/datasource/npm/npmrc.ts:115]: Both regex are same so it is illogical how one could work with re2 and not the other.

File: lib/versioning/swift/index.ts (hunk 7 above)
Comment (RahulGautamSingh) [reply lib/versioning/swift/index.ts:40]: It's inside a map function so it will have to be created each time.

I have a doubt regarding this which is like this:-
1) I create a regex like this - `re = /abs/;`
2) I create a regex like this - `re = new re2(/abs/);`

in 1)  from the Regex docs we know that even if it is inside a loop  it will only be constructed once.
But I couldn't fond any info about the creation of regex in 2) case which leaves me with doubt when I encounter such regex

If we use a string to create regex then it will be re-constructed for each iteration. For now I think it is going to be same in cases where we use an object to create a regex.

Comment (RahulGautamSingh) [reply lib/versioning/swift/index.ts:40]: It's inside a map function so it will have to be created each time.

I have a doubt regarding this which is like this:-

I create a regex like this - re = /abs/;
I create a regex like this - re = new re2(/abs/);
in 1) from the Regex docs we know that even if it is inside a loop it will only be constructed once.
But I couldn't fond any info about the creation of regex in 2) case which leaves me with doubt when I encounter such regex

If we use a string to create regex then it will be re-constructed for each iteration. For now I think it is going to be same in cases where we use an object to create a regex.

File: lib/util/ignore.ts (hunk 6 above)
Comment (RahulGautamSingh) [reply lib/util/ignore.ts:6]: If we export a function and if the function is inside a for loop in the file it is being imported to, will the regex be created for each loop or it won't be?

Comment (viceice) [reply lib/util/ignore.ts:6]: nope, the `regEx` function will always return the same instance for same input. Thats how our simple cache works.

File: lib/versioning/swift/index.ts (hunk 7 above)
Comment (viceice) [reply lib/versioning/swift/index.ts:40]: As told above `regEx` function is caching all re2 instances, so you can call that function with same string / regex multiple times and always get same re2 instance back. So the only overhead is the function call and a cache lookup.

File: lib/logger/cmd-serializer.ts (hunk 3 above)
Comment (RahulGautamSingh) [reply lib/logger/cmd-serializer.ts:6]: This can only be solved by using re2 directly here, right?

File: yarn.lock [hunk 8]
```diff
@@ -1564,6 +1564,11 @@
   resolved "https://registry.yarnpkg.com/@aws-sdk/types/-/types-3.40.0.tgz#a9d7926fcb9b699bc46be975033559d2293e60d1"
   integrity sha512-KpILcfvRaL88TLvo3SY4OuCCg90SvcNLPyjDwUuBqiOyWODjrKShHtAPJzej4CLp92lofh+ul0UnBfV9Jb/5PA==
 
+"@aws-sdk/types@^3.1.0":
```
Comment (rarkins) [inline yarn.lock:1567]: I don't understand why yarn.lock would be updated

**Review by rarkins — COMMENTED** [review]
@RahulGautamSingh can you create new issues for some of the more common reasons why we can't fully support re2? E.g. moo, lookaheads, etc. Then we need a plan for addressing them.

File: yarn.lock (hunk 8 above)
Comment (viceice) [reply yarn.lock:1567]: please revert this

File: lib/manager/terraform/lockfile/hash.ts (hunk 5 above)
Comment (viceice) [reply lib/manager/terraform/lockfile/hash.ts:35]: Why do you resolved this without comment?

File: lib/manager/npm/update/package-version/index.ts [hunk 9]
```diff
@@ -31,7 +32,7 @@ export function bumpPackageVersion(
     }
     logger.debug({ newPjVersion });
     bumpedContent = content.replace(
-      /(?<version>"version":\s*")[^"]*/, // TODO #12070
+      regEx(`(?<version>"version":\\s*")[^"]*`),
       `$<version>${newPjVersion}`
```
Comment (viceice) [inline lib/manager/npm/update/package-version/index.ts:36]: I think we should also match trailing `"` 🤔

File: lib/manager/helmv3/update.ts [hunk 10]
```diff
@@ -20,7 +21,7 @@ export function bumpPackageVersion(
     }
     logger.debug({ newChartVersion });
     bumpedContent = content.replace(
-      /^(?<version>version:\s*).*$/m, // TODO #12070
+      regEx(`^(?<version>version:\\s*).*$`, 'm'), // TODO #12071
```
Comment (viceice) [inline lib/manager/helmv3/update.ts:24]: This will replace any comments after the version, we should open a new issue

File: lib/logger/cmd-serializer.ts (hunk 3 above)
Comment (viceice) [reply lib/logger/cmd-serializer.ts:6]: Why this causes circular dependency? Looks like a re2 bug to me.

File: yarn.lock (hunk 8 above)
Comment (RahulGautamSingh) [reply yarn.lock:1567]: On my local machine @aws-sdk/client-ec2 was causing errors, so I compared the versions and found that main branch uses 3.35.0 and I was on older so I updated the package. I will revert this and pull from the main.

File: lib/manager/npm/update/package-version/index.ts (hunk 9 above)
Comment (RahulGautamSingh) [reply lib/manager/npm/update/package-version/index.ts:36]: Will modify the regex to achieve the same.

File: lib/datasource/npm/npmrc.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (RahulGautamSingh) [reply lib/datasource/npm/npmrc.ts:115]: I am thinking of handling this one and similar changes will be handles in #12071.
The issue #12071 is almost irrelevant now since the regex is being cached, still regex like this and some others can be moved up in scope so that in future we don't need to change multiple instances of same regex.

**Comment by RahulGautamSingh** [comment]
> @RahulGautamSingh can you create new issues for some of the more common reasons why we can't fully support re2? E.g. moo, lookaheads, etc. Then we need a plan for addressing them.

Sure thing, that was the goal from the beginning to write concise , readable comments once all issues are discussed.

File: lib/manager/terraform/lockfile/hash.ts (hunk 5 above)
Comment (RahulGautamSingh) [reply lib/manager/terraform/lockfile/hash.ts:35]: Sorry for that I thought I committed this change.
Will it be okay to apply this change in #12071 where all similar changes will be handled?

File: lib/logger/cmd-serializer.ts (hunk 3 above)
Comment (RahulGautamSingh) [reply lib/logger/cmd-serializer.ts]: When re2 is used here it causes the logger class to become undefined in the `lib/logger/index.spec.ts` tests, I have updated the comment to say so.

I will look some more into it to find why  that happens.

Comment (viceice) [reply lib/logger/cmd-serializer.ts]: I understand now, we get a circular module dependency, as regex is using logger and logger is using this.

@rarkins i think we need to stay on normal regex for logger stuff. 🤔

File: lib/manager/helmv3/update.ts (hunk 10 above)
Comment (RahulGautamSingh) [reply lib/manager/helmv3/update.ts:24]: Removing `.*` from the regex solves the issue.

Updated: ```   regEx(`^(?<version>version:\\s*)$`, 'm'), ```

File: lib/manager/npm/update/package-version/index.ts (hunk 9 above)
Comment (RahulGautamSingh) [reply lib/manager/npm/update/package-version/index.ts:36]: We are matching the front `"` in this example. So not including the trailing `"` in the match makes sense.

For eg:-

In this string: `"version": "1.1.1"` the regex matches `"version": "1.1.1` and replaces it with `"vesrion": "1.2.3`, therefore matching trailingSlash is not necessary.

File: yarn.lock (hunk 8 above)
Comment (RahulGautamSingh) [reply yarn.lock]: reverted

File: lib/datasource/npm/npmrc.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (rarkins) [reply lib/datasource/npm/npmrc.ts:115]: We have a special function for this though, wouldn't it be more readable to use it?

[the remark this answers is not in the document]
Comment (RahulGautamSingh) [reply lib/datasource/npm/npmrc.ts:115]: Yes, I meant the same thing. Including this instance there are some more places where we need to add ensureTrailingSlash so I wanted to implement this in another PR.

**Comment by RahulGautamSingh** [comment]
Moo state error explained in this issue #12870

**Comment by RahulGautamSingh** [comment]
Lookahead, backreference and all syntax related re2 issues are handles in this issue #12872

**Comment by RahulGautamSingh** [comment]
This PR is ready to be merged.

**Comment by RahulGautamSingh** [comment]
This PR is ready to be merged.

File: lib/manager/gitlabci/extract.ts [hunk 11]
```diff
@@ -120,15 +124,15 @@ export async function extractAllPackageFiles(
...
+          const fileObj = includeObj.local.replace(regEx(/^\//), '');
           if (!seen.has(fileObj)) {
             seen.add(fileObj);
             filesToExamine.push(fileObj);
           }
         }
       }
     } else if (is.string(doc?.include)) {
-      const fileObj = doc.include.replace(/^\//, ''); // TODO #12071  #12070
+      const fileObj = doc.include.replace(/^\//, ''); // TODO  #12070
```
Comment (viceice) [inline lib/manager/gitlabci/extract.ts:135]: the same regex is modified above
```suggestion
      const fileObj = doc.include.replace(regEx(/^\//), '');
```

File: lib/manager/terraform/lockfile/hash.ts (hunk 5 above)
Comment (viceice) [inline lib/manager/terraform/lockfile/hash.ts:35]:
```suggestion
      const fileName = file.replace(regEx(/^.*[\\/]/), '');  // TODO #12071
```

File: lib/workers/repository/model/commit-message.ts [hunk 12]
```diff
@@ -43,6 +45,14 @@ export class CommitMessage {
...
     return [prefix, message].join(' ').trim();
   }
+  public static formatCasing(commitMessage: string): string {
+    return commitMessage.replace(
+      regEx(/^([\w]+:|[\w]+\(.*\):)/).test(commitMessage)
+        ? regEx(/: \w+/)
+        : regEx(/^\w+/),
+      (match) => match.toLowerCase()
+    );
+  }
```
Comment (viceice) [inline lib/workers/repository/model/commit-message.ts:55]: wrong merge?

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/workers/repository/model/commit-message.ts (hunk 12 above)
Comment (RahulGautamSingh) [reply lib/workers/repository/model/commit-message.ts:55]: I added this code to solve issue #12062.

Comment (viceice) [reply lib/workers/repository/model/commit-message.ts:55]: yes, but that shouln'd part of this PR, please extract to separate PR.

**Review by viceice — COMMENTED** [review]
plese move commit-message changes to separate PR

File: lib/workers/repository/model/commit-message.ts (hunk 12 above)
Comment (RahulGautamSingh) [reply lib/workers/repository/model/commit-message.ts]: Done.

**Review by viceice — APPROVED** [review]
