### PR TITLE
fix(github): Use GraphQL for initRepo

### LINKED ISSUE #6686: Refactor GitHub initRepo to use GraphQL instead of REST
Rewrite `github.initRepo()` so that it uses a repository GraphQL query. The main reason is so that we can retrieve the default branch's commit `sha` without an extra query, and that `sha` will be used as a cache lookup key.

I think this example query captures everything we need:

```graphql
{
  repository(owner: "renovatebot", name: "renovate") {
    isFork
    isLocked
    isMirror
    isPrivate
    isArchived
    nameWithOwner
    mergeCommitAllowed
    rebaseMergeAllowed
    squashMergeAllowed
    defaultBranchRef {
      name
    }
  }
}

```

### PR DESCRIPTION
**Pull request by zharinov**
Closes #6686

### CODE REVIEW

File: lib/util/http/github.ts [hunk 1]
```diff
@@ -223,14 +223,18 @@ export class GithubHttp extends Http<GithubHttpOptions, GithubHttpOptions> {
     return result;
   }
 
-  private async getGraphql<T = unknown>(
+  public async getGraphql<T = unknown>(
```
Comment (viceice) [inline lib/util/http/github.ts:226]:
```suggestion
  public async postGraphql<T = unknown>(
```
We do a post internally, so to be consistent.

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/util/http/github.ts (hunk 1 above)
Comment (zharinov) [reply lib/util/http/github.ts:226]: Well, it was named together with `getGraphqlItems()`, so maybe should be changed to something not interferring with HTTP in any way

Comment (viceice) [reply lib/util/http/github.ts:226]: I don't mind, but `get` should be removed as it implies a `GET` request on http layer. So feel free to name it `postGraphql` or simply `graphql`.

@rarkins @JamieMagee Any suggestion here?

Comment (rarkins) [reply lib/util/http/github.ts:226]: I'm ok with "graphql". All lower case to match with get, put, etc

Comment (zharinov) [reply lib/util/http/github.ts:226]: So, I think it will be single `graphql` to rule them all, single items like `repository` and many like `edges` and `nodes`.

**Comment by rarkins** [comment]
@zharinov can we still get the refactoring split out into its own PR first?

**Comment by rarkins** [comment]
Ready for merge from master

File: lib/platform/github/index.ts [hunk 2]
```diff
@@ -215,12 +216,28 @@ export async function initRepo({
...
+        mergeCommitAllowed
+        rebaseMergeAllowed
+        squashMergeAllowed
+        defaultBranchRef {
+          name
+        }
+      }
+    }`,
+      {
+        acceptHeader: 'application/vnd.github.v3+json',
```
Comment (rarkins) [inline lib/platform/github/index.ts:236]: I don't like having this here as it shouldn't be necessary

Comment (rarkins) [reply lib/platform/github/index.ts:236]: Also need to make 100% sure that the app header gets sent instead when in app mode

**Comment by zharinov** [comment]
Ready for review
