### PR TITLE
fix(gomod): Commit updated go.mod when only go.mod changes

### LINKED ISSUE #20316: gomod: pseudeo zero-versions are update to just the digest
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

tested as well with 34.128.3

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

_I think I saw that working, but I'm not exactly sure_

When using packages without a version golang uses a pseudo version (v0.0.0-<date>-<commit-sha>). 
Renovate as well detects and proposes and update, but replaces the full version with just the commit, instead of updating the date/commit sha. 
image

I assume the problem is somewhere in this area, I wasn't able to pinpoint it yet exactly.
https://github.com/renovatebot/renovate/blob/d19effc48d0d2ba8cbf6f2805c567132fc70eab8/lib/modules/manager/gomod/update.ts#L72-L88

Reproduction PR: https://github.com/Shegox/renovate-go-update/pull/2/files

### Relevant debug logs

<details><summary>Logs</summary>

```
# extraction logs
               {
                 "managerData": {"lineNumber": 4},
                 "depName": "github.com/elazarl/goproxy",
                 "depType": "require",
                 "currentValue": "v0.0.0-20200809112317-0581fc3aee2d",
                 "datasource": "go",
                 "currentDigest": "0581fc3aee2d",
                 "digestOneAndOnly": true,
                 "depIndex": 1,
                 "updates": [
                   {
                     "updateType": "digest",
                     "newValue": "v0.0.0-20200809112317-0581fc3aee2d",
                     "newDigest": "a0805db90819b464f8fadc660e23a6a6b9d4942f",
                     "branchName": "renovate/github.com-elazarl-goproxy-digest"
                   }
                 ],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/elazarl/goproxy",
                 "currentVersion": "v0.0.0-20200809112317-0581fc3aee2d",
                 "fixedVersion": "v0.0.0-20200809112317-0581fc3aee2d"
               }
               
 # actual update: 
 EBUG: syncBranchState() (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: syncBranchState(): Branch cache not found, creating minimal branchState (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: getBranchPr(renovate/github.com-elazarl-goproxy-digest) (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: findPr(renovate/github.com-elazarl-goproxy-digest, undefined, open) (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Found PR #1 (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: branchExists=true (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: dependencyDashboardCheck=undefined (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: PR rebase requested=true (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Checking if PR has been edited (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: branch.isModified(): using git to calculate (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: branch.isModified() = false (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Found existing branch PR (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Checking schedule(null, null) (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: No schedule defined (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Manual rebase requested via Dependency Dashboard (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Using reuseExistingBranch: false (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Setting current branch to main (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: latest commit (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
       "branchName": "main",
       "latestCommitDate": "2023-02-09T15:37:01+01:00"
DEBUG: manager.getUpdatedPackageFiles() reuseExistingBranch=false (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: gomod.updateDependency: v0.0.0-20200809112317-0581fc3aee2d (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: gomod: need to update digest (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
       "depName": "github.com/elazarl/goproxy",
       "lineToChange": "require github.com/elazarl/goproxy v0.0.0-20200809112317-0581fc3aee2d",
       "newDigestRightSized": "a0805db90819"
DEBUG: Updating github.com/elazarl/goproxy in go.mod (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: gomod.updateArtifacts(go.mod) (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Adding Git authentication for Go Module retrieval for https://github.tools.sap/ using token auth. (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Setting CONTAINERBASE_CACHE_DIR to /var/folders/y0/9m0z3k5n6xngc1x88_7jkkwm0000gn/T/renovate/cache/containerbase (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Falling back to binarySource=global (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Executing command (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
       "command": "go get -d -t ./..."
DEBUG: exec completed (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
       "durationMs": 6194,
       "stdout": "",
       "stderr": "go: warning: \"github.tools.sap/gh-testing/go-digest-update/...\" matched no packages\n"
DEBUG: Updated 1 package files (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: No updated lock files in branch (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: isBranchConflicted(main, renovate/github.com-elazarl-goproxy-digest) (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: branch.isConflicted(): using git to calculate (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Setting git author name: Renovate Bot (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Setting git author email: renovate@whitesourcesoftware.com (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: branch.isConflicted(): false (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: 1 file(s) to commit (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Preparing files for committing to branch renovate/github.com-elazarl-goproxy-digest (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: git commit (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/github.com-elazarl-goproxy-digest",
         "commit": "8e65df2b23aafdb06d6acdf4ba1a09f8713475bc",
         "root": false,
         "summary": {"changes": 1, "insertions": 1, "deletions": 1}
       }
DEBUG: Pushing refSpec renovate/github.com-elazarl-goproxy-digest:renovate/github.com-elazarl-goproxy-digest (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: git push (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
       "result": {
         "pushed": [],
         "ref": {
           "local": "refs/remotes/origin/renovate/github.com-elazarl-goproxy-digest"
         },
         "remoteMessages": {
           "all": [
             "[Block File Extensions] Scanning for sensitive file extensions.",
             "[Block File Extensions] No sensitive file extensions found."
           ]
         }
       }
 INFO: Branch updated (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
       "commitSha": "8e65df2b23aafdb06d6acdf4ba1a09f8713475bc"
DEBUG: Ensuring PR (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: There are 0 errors and 0 warnings (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: getBranchPr(renovate/github.com-elazarl-goproxy-digest) (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: findPr(renovate/github.com-elazarl-goproxy-digest, undefined, open) (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Found PR #1 (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Found existing PR (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: Processing existing PR (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: updatePr(1, Update github.com/elazarl/goproxy digest to a0805db, body) (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: PR updated...prNo: 1 (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
 INFO: PR updated (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
       "pr": 1,
       "prTitle": "Update github.com/elazarl/goproxy digest to a0805db"
DEBUG: PR is not configured for automerge (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
DEBUG: setBranchCommit() (repository=D064687/go-digest-update, branch=renovate/github.com-elazarl-goproxy-digest)
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by Shegox**
## Changes

This PR will commit an updated `go.mod` file, if only the `go.mod` file changes and not the `go.sum` file.
There exist some corner cases there this could be the case

## Context

- Fixes #20316

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

Before implementing the change:
image

After implementing the change:
image

### CODE REVIEW

File: lib/modules/manager/gomod/artifacts.ts [hunk 1]
```diff
@@ -337,20 +337,23 @@ export async function updateArtifacts({
...
+      !status.modified.includes(goModFileName)
+    ) {
       return null;
     }
 
-    logger.debug('Returning updated go.sum');
-    const res: UpdateArtifactsResult[] = [
-      {
+    const res: UpdateArtifactsResult[] = [];
+    if (status.modified.includes(sumFileName)) {
```
Comment (rarkins) [inline lib/modules/manager/gomod/artifacts.ts:348]:
```suggestion
    if (status.modified.includes(sumFileName)) {
      logger.debug('Returning updated go.sum');
```

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/modules/manager/gomod/artifacts.ts (hunk 1 above)
Comment (Shegox) [reply lib/modules/manager/gomod/artifacts.ts:348]: I though I included that. Sorry about that :)

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
