### PR TITLE
fix(gradle-wrapper): update checksum

### LINKED ISSUE #6148: Gradle Wrapper update without updating distributionSha256Sum
**What Renovate type are you using?**

We are using self-hosted Renovate, with GitHub Enterprise.

**Describe the bug**

Renovate prepares a PR to update Gradle wrapper, but it updates `distributionUrl` settings only (in `gradle/wrapper/gradle-wrapper.properties` file).

If `distributionSha256Sum` property is present, it must be updated accordingly. If not updated, the project build fails with following error:
```
Verification of Gradle distribution failed!
  Your Gradle distribution may have been tampered with.
  Confirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.
```

### PR DESCRIPTION
**Pull request by viceice**
This pr updates the gradle `distributionSha256Sum` if it's found in `gradle-wrapper.properties`.
Throws artifact error if new checksum can't be fetched.

Closes #6148

### CODE REVIEW

**Comment by viceice** [comment]
Something wrong with my tests

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 1]
```diff
@@ -56,6 +63,10 @@ export async function updateArtifacts({
     const distributionUrl = getDistributionUrl(newPackageFileContent);
     if (distributionUrl) {
       cmd += ` --gradle-distribution-url ${distributionUrl}`;
+      if (newPackageFileContent.includes('distributionSha256Sum=')) {
+        const checksum = await getDistributionChecksum(distributionUrl);
```
Comment (rarkins) [inline lib/manager/gradle-wrapper/artifacts.ts:67]: Do you prefer to totally fail the artifacts updating if the checksum file is missing, or skip it and add a synthetic artifacts error message?

Comment (viceice) [reply lib/manager/gradle-wrapper/artifacts.ts:67]: If we don't update the checksum, gradle run will fail on ci, because it checks the sum on *next* run, not on self update

**Review by rarkins — DISMISSED** [review]

**Review by rarkins — APPROVED** [review]
