### PR TITLE
fix: rerun `applyPackageRules` after fetching sourceUrl from datasource

### LINKED ISSUE #532: allowedVersions does not work on monorepo presets
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I have my custom configuration here:

https://github.com/sarunint/renovate-config/blob/6cd8f806ada8f75782a0c9f8059617afe4dc8ef8/package.json#L49-L81

My intention was to hold the upgrade of Angular packages from v8 to v9 while I solve some bugs.

I have my repository here https://github.com/ivaothai/whazzup-tracker/issues/2

But Renovate still create PR that update Angular to v9. Why is this happening?

### LINKED ISSUE #4160: PackageRules exclusion not being applied for monorepo:angular
**What Renovate type are you using?**
Renovate CLI, Renovate GitHub App, or Renovate Pro?
GH App

**Describe the bug**

For a while (> 1yr), we've had a project which successfully fixed the max version of angular using the following config:
```
"packageRules": [
    {
      "extends": ["monorepo:angular", "monorepo:angularmaterial"],
      "packageNames": ["@angular/flex-layout", "rxjs"],
      "allowedVersions": "<6.0"
    },
```

Recently (since last week or so), renovate has been persistently opening PRs to update those specified dependencies to 8.x. Manually closing the PR causes it to almost immediately be reopened.

I've also tried augmenting the package rules to use this, just in case the monorepo preset had been changed, but to no avail:

```
"packageRules": [
    {
      "extends": ["monorepo:angular", "monorepo:angularmaterial"],
      "packageNames": ["@angular/flex-layout", "rxjs"],
      "allowedVersions": "<6.0",
      "packagePatterns": ["^@angular\\/(?:(?!cli).+)$"],
    },
```

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

https://renovatebot.com/dashboard#github/dialoguemd/care-platform/82343401

But you should see something similar in basically every log for that project in past few days.

Note that I have exclusions in place for other packages (e.g. @angular/cli), and those seem to be working fine.

**To Reproduce**

N/A

**Expected behavior**

Those specified deps should be ignored / not updated; like before :)

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by sarunint**
## Changes:

In previous versions, when the config has a packageRule that have `sourceUrl` conditions and `allowedVersions` restrictions, it does not work. This is due to Renovate fetch the sourceUrl after it resolves the version to update to. This commit will make renovate fetch the package metadata from the datasource and apply only `sourceUrl` property to the dependency object before resolving the version to update to.

## Context:

This PR intends to resolve https://github.com/renovatebot/config-help/issues/532. (I procrastinate for a very long time there LOL.)

EDIT: this also fixes #4160

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [x] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Sorry, but I have some doubts about this approach. I think a different type of refactoring is preferred.

Today we do like this:

- Extract from package files
- Apply packageRules to extracted dependencies (too early to know sourceUrl)
- Look up from datasource, now we know all versions and sourceUrl
- Apply all version filtering including allowedVersions
- Apply packageRules to updates (too late for allowedVersions)

I'd prefer a refactor like this:

- Extract from package files
- Apply packageRules to extracted dependencies
- Look up from datasource, now we know all versions and sourceUrl
- Apply packageRules to post-lookup dependencies (which would now take sourceUrl into consideration)
- Apply all version filtering including allowedVersions
- Apply packageRules to updates

Cc @viceice @zharinov

**Comment by sarunint** [comment]
> Today we do like this:
> 
> * Extract from package files
> * Apply packageRules to extracted dependencies (too early to know sourceUrl)
> * Look up from datasource, now we know all versions and sourceUrl
> * Apply all version filtering including allowedVersions
> * Apply packageRules to updates (too late for allowedVersions)

Correct me if I'm wrong, but currently, the "Apply all version filtering including allowedVersions" is tied to "Look up from datasource, now we know all versions and sourceUrl", right?

**Comment by rarkins** [comment]
Yes, the lookup is done here: https://github.com/renovatebot/renovate/blob/276a01fdd743d270fd2662cabb3b0e1e465aec83/lib/workers/repository/process/lookup/index.ts#L158

The filtering is called later down in the same function here: https://github.com/renovatebot/renovate/blob/276a01fdd743d270fd2662cabb3b0e1e465aec83/lib/workers/repository/process/lookup/index.ts#L283

And within that function `allowedVersions` is evaluated here: https://github.com/renovatebot/renovate/blob/276a01fdd743d270fd2662cabb3b0e1e465aec83/lib/workers/repository/process/lookup/filter.ts#L74

Your problem could perhaps be solved most simply (requiring no major refactor) by applying packageRules around here: https://github.com/renovatebot/renovate/blob/276a01fdd743d270fd2662cabb3b0e1e465aec83/lib/workers/repository/process/lookup/index.ts#L203

**Comment by sarunint** [comment]
@rarkins I've tried implemented the solution you provided. The code is a little bit messy though.

File: lib/workers/repository/process/lookup/index.ts [hunk 1]
```diff
@@ -131,8 +133,9 @@ function getBucket(config: LookupUpdateConfig, update: LookupUpdate): string {
 }
 
 export async function lookupUpdates(
-  config: LookupUpdateConfig
+  inconfig: LookupUpdateConfig
 ): Promise<UpdateResult> {
+  let config = { ...inconfig };
```
Comment (viceice) [inline lib/workers/repository/process/lookup/index.ts:138]:
```suggestion
  let config: LookupUpdateConfig = { ...inconfig };
```

File: lib/workers/repository/process/lookup/index.ts [hunk 2]
```diff
@@ -4,6 +4,7 @@ import {
   ValidationMessage,
 } from '../../../../config';
 import {
+  GetPkgReleasesConfig,
```
Comment (viceice) [inline lib/workers/repository/process/lookup/index.ts:7]:
```suggestion
```

File: lib/workers/repository/process/lookup/index.ts [hunk 3]
```diff
@@ -399,7 +406,9 @@ export async function lookupUpdates(
         });
       }
     } else if (config.datasource === datasourceGitSubmodules.id) {
-      const dependency = clone(await getPkgReleases(config));
+      const dependency = clone(
+        await getPkgReleases((config as any) as GetPkgReleasesConfig)
+      ); // fixme: typing
```
Comment (viceice) [inline lib/workers/repository/process/lookup/index.ts:411]:
```suggestion
      const dependency = clone(await getPkgReleases(config);
```

**Review by viceice — CHANGES_REQUESTED** [review]
This changes should fix your type issue

File: lib/workers/repository/process/lookup/index.ts [hunk 4]
```diff
@@ -200,6 +205,8 @@ export async function lookupUpdates(
         return res;
       }
     }
+    // Reapply package rules in case we missed something from sourceUrl
+    config = applyPackageRules(config);
```
Comment (rarkins) [inline lib/workers/repository/process/lookup/index.ts:209]:
```suggestion
    config = applyPackageRules({ ...config, sourceUrl: res.sourceUrl });
```

Could this line fix it by itself?

Comment (sarunint) [reply lib/workers/repository/process/lookup/index.ts]: Yeah, I think this looks better.

**Review by viceice — DISMISSED** [review]

File: lib/workers/repository/process/lookup/index.ts [hunk 5]
```diff
@@ -200,6 +204,8 @@ export async function lookupUpdates(
         return res;
       }
     }
+    // Reapply package rules in case we missed something from sourceUrl
+    config = applyPackageRules({ ...config, sourceUrl: res.sourceUrl });
```
Comment (rarkins) [inline lib/workers/repository/process/lookup/index.ts:208]: Can the config/inconfig part now be reverted too?

File: lib/workers/repository/process/lookup/index.ts [hunk 6]
```diff
@@ -131,8 +134,9 @@ function getBucket(config: LookupUpdateConfig, update: LookupUpdate): string {
 }
 
 export async function lookupUpdates(
-  config: LookupUpdateConfig
+  inconfig: LookupUpdateConfig
 ): Promise<UpdateResult> {
+  let config: LookupUpdateConfig = { ...inconfig };
```
Comment (rarkins) [inline lib/workers/repository/process/lookup/index.ts:139]:
```suggestion
  config: LookupUpdateConfig
): Promise<UpdateResult> {
```

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/workers/repository/process/lookup/index.ts [hunk 7]
```diff
@@ -50,6 +51,8 @@ export interface LookupUpdateConfig
   vulnerabilityAlert?: boolean;
   separateMajorMinor?: boolean;
   separateMultipleMajor?: boolean;
+  datasource: string;
+  depName: string;
```
Comment (viceice) [inline lib/workers/repository/process/lookup/index.ts:55]: Do we need this here?

Comment (rarkins) [reply lib/workers/repository/process/lookup/index.ts:55]: image

Comment (rarkins) [reply lib/workers/repository/process/lookup/index.ts:55]: I'm not sure why this check fails due to this PR but I'm ok to go with this unless you have something better

**Review by rarkins — APPROVED** [review]

File: lib/workers/repository/process/lookup/index.ts (hunk 6 above)
Comment (viceice) [inline lib/workers/repository/process/lookup/index.ts:139]: No longer revert this?

Comment (viceice) [reply lib/workers/repository/process/lookup/index.ts:139]: ok, we get eslint error because of param reassign 🤔  so leaving it as is here.

Comment (sarunint) [reply lib/workers/repository/process/lookup/index.ts:139]: image

Comment (rarkins) [reply lib/workers/repository/process/lookup/index.ts:139]: Yes, that was my mistake because I forgot the reassignment, so I deleted the suggestion.

**Review by viceice — APPROVED** [review]
