### PR TITLE
fix(gradle-wrapper): handle white space

### LINKED ISSUE #5739: Gradle Wrapper not Updated If Spaces in gradle.properties
**Describe the bug**

If `gradle.properties` is formatted to use whitespace around the `=` sign, the gradle wrapper is not being updated. Using whitespace there is valid for `properties` files and can happen if automatic formatting is applied.

**To Reproduce**

[Example File](https://github.com/renovatebot/renovate/pull/5740/files#diff-536b06f70d19b48a0e94f4ad32ce787e)
[Unit Test](https://github.com/renovatebot/renovate/pull/5740/files#diff-64412f80e84b76edfbe19dae011fada4R33)

### PR DESCRIPTION
**Pull request by jGleitz**
Closes #5739

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
Please fix errors

**Comment by jGleitz** [comment]
@viceice done.

File: lib/manager/gradle-wrapper/extract.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ export function extractPackageFile(fileContent: string): PackageFile | null {
 
   let lineNumber = 0;
   for (const line of lines) {
-    const match = /^distributionUrl=.*-((\d|\.)+)-(bin|all)\.zip\s*$/.exec(
+    const match = /^distributionUrl\s*=\s*\S*-((\d|\.)+)-(bin|all)\.zip\s*$/.exec(
```
Comment (viceice) [inline lib/manager/gradle-wrapper/extract.ts]: @rarkins @JamieMagee We should move the regexes to module scope, otherwise they are recreated on every loop iteration, which is unnessessary

**Review by viceice — APPROVED** [review]
