### PR TITLE
fix(github): compare repo names lower case

### LINKED ISSUE #19386: New PR's getting created for after previous PR was closed unmerged when upper case repository names in use
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.55.0

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitHub Enterprise Server 3.5.7

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

We close PR's for dependencies we can't yet merge, like `chalk v5`. 

Next time Renovate runs, it creates a new PR for that same dependency.

It is not re-opening the closed PR, it's creating a new one. It doesn't matter if the branch was left behind or deleted.

I created a fresh repo so the debug long wouldn't be _too_ long.

Screen Shot 2022-12-13 at 5 05 33 PM

The PR's are not marked `immortal`:
Screen Shot 2022-12-13 at 6 43 06 PM

Expectation: https://docs.renovatebot.com/key-concepts/pull-requests/#ignoring-prs

This has been happening for a while, possibly since I've added these settings: `platform: 'github'`,
    `endpoint: 'https://github.company.com/api/v3/'`, `timeout` `concurrentRequestLimit` `maxRequestsPerSecond`. Maybe one of them is causing this?

### Relevant debug logs

In this example, a PR for Chalk 5 is created, even though it's been closed before.

<details><summary>Logs</summary>

```
+ yarn renovate
 DEBUG: Using RE2 as regex engine
 DEBUG: Parsing configs
 DEBUG: Checking for config file in /home/jenkins/workspace/ia_medallia-org_renovate_PR-1838/renovate.js
 DEBUG: Converting GITHUB_COM_TOKEN into a global host rule
 DEBUG: File config
        "config": {
          "platform": "github",
          "endpoint": "https://github.medallia.com/api/v3/",
          "repositories": ["magic/test-renovate"],
          "schedule": [
            "every weekday before 10am",
            "every weekday after 9pm",
            "every weekend"
          ],
          "timezone": "US/Eastern",
          "npmrc": "***********",
          "packageRules": [
            {
              "matchDatasources": ["docker"],
              "registryUrls": ["https://virtual-docker.artifactory.eng.medallia.com/"]
            },
            {
              "matchDatasources": ["gradle"],
              "matchPackagePatterns": ["medallia"],
              "registryUrls": ["https://artifactory.eng.medallia.com/virtual-gradle"]
            }
          ],
          "hostRules": [
            {
              "hostType": "npm",
              "username": "fowler",
              "password": "***********",
              "timeout": 300000
            },
            {
              "hostType": "maven",
              "matchHost": "artifactory.eng.medallia.com",
              "username": "fowler",
              "password": "***********",
              "timeout": 300000
            },
            {
              "hostType": "gradle",
              "matchHost": "artifactory.eng.medallia.com",
              "username": "fowler",
              "password": "***********",
              "timeout": 300000
            },
            {
              "hostType": "docker",
              "matchHost": "virtual-docker.artifactory.eng.medallia.com",
              "username": "fowler",
              "password": "***********",
              "timeout": 300000
            },
            {
              "hostType": "docker",
              "matchHost": "virtual-docker.martifactory.io",
              "username": "fowler",
              "password": "***********",
              "timeout": 300000
            },
            {
              "matchHost": "api.github.com",
              "concurrentRequestLimit": 1,
              "maxRequestsPerSecond": 1
            },
            {
              "matchHost": "artifactory.eng.medallia.com",
              "concurrentRequestLimit": 5,
              "maxRequestsPerSecond": 5
            }
          ],
          "logFileLevel": "debug",
          "requireConfig": "optional",
          "allowCustomCrateRegistries": true,
          "allowPlugins": true,
          "allowScripts": true,
          "exposeAllEnv": true,
          "suppressNotifications": [],
          "executionTimeout": 60,
          "onboardingConfig": {
            "$schema": "https://docs.renovatebot.com/renovate-schema.json",
            "extends": [
              "config:base",
              ":rebaseStalePrs",
              ":semanticCommits",
              ":maintainLockFilesWeekly",
              "schedule:nonOfficeHours"
            ],
            "configMigration": true,
            "commitMessagePrefix": "chore(deps): {{{updateType}}} -",
            "postUpdateOptions": ["yarnDedupeFewer"],
            "ignoreDeps": [],
            "packageRules": [
              {"groupName": "Argus Packages", "matchPackagePatterns": ["^@m/argus"]},
              {
                "groupName": "Magic Packages",
                "matchPackagePatterns": [
                  "^@m/magic",
                  "^@m/babel-preset-magic",
                  "^@m/eslint-plugin-magic"
                ]
              },
              {"groupName": "Alchemy Packages", "matchPackagePatterns": ["^@m/alchemy"]}
            ]
          }
        }
 DEBUG: CLI config
        "config": {}
 DEBUG: Env config
        "config": {
          "hostRules": [
            {"hostType": "github", "matchHost": "github.com", "token": "***********"}
          ],
          "endpoint": "https://github.medallia.com/api/v3",
          "token": "***********"
        }
 DEBUG: Combined config
        "config": {
          "platform": "github",
          "endpoint": "https://github.medallia.com/api/v3",
          "repositories": ["magic/test-renovate"],
          "schedule": [
            "every weekday before 10am",
            "every weekday after 9pm",
            "every weekend"
          ],
          "timezone": "US/Eastern",
          "npmrc": "***********",
          "packageRules": [
            {
              "matchDatasources": ["docker"],
              "registryUrls": ["https://virtual-docker.artifactory.eng.medallia.com/"]
            },
            {
              "matchDatasources": ["gradle"],
              "matchPackagePatterns": ["medallia"],
              "registryUrls": ["https://artifactory.eng.medallia.com/virtual-gradle"]
            }
          ],
          "hostRules": [
            {
              "hostType": "npm",
              "username": "fowler",
              "password": "***********",
              "timeout": 300000
            },
            {
              "hostType": "maven",
              "matchHost": "artifactory.eng.medallia.com",
              "username": "fowler",
              "password": "***********",
              "timeout": 300000
            },
            {
              "hostType": "gradle",
              "matchHost": "artifactory.eng.medallia.com",
              "username": "fowler",
              "password": "***********",
              "timeout": 300000
            },
            {
              "hostType": "docker",
              "matchHost": "virtual-docker.artifactory.eng.medallia.com",
              "username": "fowler",
              "password": "***********",
              "timeout": 300000
            },
            {
              "hostType": "docker",
              "matchHost": "virtual-docker.martifactory.io",
              "username": "fowler",
              "password": "***********",
              "timeout": 300000
            },
            {
              "matchHost": "api.github.com",
              "concurrentRequestLimit": 1,
              "maxRequestsPerSecond": 1
            },
            {
              "matchHost": "artifactory.eng.medallia.com",
              "concurrentRequestLimit": 5,
              "maxRequestsPerSecond": 5
            },
            {"hostType": "github", "matchHost": "github.com", "token": "***********"}
          ],
          "logFileLevel": "debug",
          "requireConfig": "optional",
          "allowCustomCrateRegistries": true,
          "allowPlugins": true,
          "allowScripts": true,
          "exposeAllEnv": true,
          "suppressNotifications": [],
          "executionTimeout": 60,
          "onboardingConfig": {
            "$schema": "https://docs.renovatebot.com/renovate-schema.json",
            "extends": [
              "config:base",
              ":rebaseStalePrs",
              ":semanticCommits",
              ":maintainLockFilesWeekly",
              "schedule:nonOfficeHours"
            ],
            "configMigration": true,
            "commitMessagePrefix": "chore(deps): {{{updateType}}} -",
            "postUpdateOptions": ["yarnDedupeFewer"],
            "ignoreDeps": [],
            "packageRules": [
              {"groupName": "Argus Packages", "matchPackagePatterns": ["^@m/argus"]},
              {
                "groupName": "Magic Packages",
                "matchPackagePatterns": [
                  "^@m/magic",
                  "^@m/babel-preset-magic",
                  "^@m/eslint-plugin-magic"
                ]
              },
              {"groupName": "Alchemy Packages", "matchPackagePatterns": ["^@m/alchemy"]}
            ]
          },
          "token": "***********"
        }
 DEBUG: Adding trailing slash to endpoint
 DEBUG: Found valid git version: 2.34.1
 DEBUG: Detected GitHub Enterprise Server, version: 3.5.7
 DEBUG: Platform config
        "platformConfig": {
          "hostType": "github",
          "endpoint": "https://github.medallia.com/api/v3/",
          "isGHApp": false,
          "isGhe": true,
          "gheVersion": "3.5.7",
          "userDetails": {"username": "service-continuous-deliver", "name": null},
          "userEmail": "service-continuous-deliver@medallia.com"
        },
        "renovateUsername": "service-continuous-deliver"
 DEBUG: Using platform gitAuthor: null <service-continuous-deliver@medallia.com>
 DEBUG: Adding token authentication for github.medallia.com to hostRules
 DEBUG: Using baseDir: /tmp/renovate
 DEBUG: Using cacheDir: /tmp/renovate/cache
 DEBUG: Using containerbaseDir: /tmp/renovate/cache/containerbase
 DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
 DEBUG: Commits limit = null
 DEBUG: Setting global hostRules
 DEBUG: Adding password authentication for artifactory.eng.medallia.com to hostRules
 DEBUG: Adding password authentication for artifactory.eng.medallia.com to hostRules
 DEBUG: Adding password authentication for virtual-docker.artifactory.eng.medallia.com to hostRules
 DEBUG: Adding password authentication for virtual-docker.martifactory.io to hostRules
 DEBUG: Adding token authentication for github.com to hostRules
 DEBUG: Adding token authentication for github.medallia.com to hostRules
 DEBUG: validatePresets()
 DEBUG: Reinitializing hostRules for repo
 DEBUG: Clearing hostRules
 DEBUG: Adding password authentication for artifactory.eng.medallia.com to hostRules
 DEBUG: Adding password authentication for artifactory.eng.medallia.com to hostRules
 DEBUG: Adding password authentication for virtual-docker.artifactory.eng.medallia.com to hostRules
 DEBUG: Adding password authentication for virtual-docker.martifactory.io to hostRules
 DEBUG: Adding token authentication for github.com to hostRules
 DEBUG: Adding token authentication for github.medallia.com to hostRules
  INFO: Repository started (repository=magic/test-renovate)
        "renovateVersion": "34.55.0"
 DEBUG: Using localDir: /tmp/renovate/repos/github/magic/test-renovate (repository=magic/test-renovate)
 DEBUG: PackageFiles.clear() - Package files deleted (repository=magic/test-renovate)
 DEBUG: initRepo("magic/test-renovate") (repository=magic/test-renovate)
 DEBUG: magic/test-renovate default branch = master (repository=magic/test-renovate)
 DEBUG: Using personal access token for git init (repository=magic/test-renovate)
 DEBUG: Setting npmrc (repository=magic/test-renovate)
 DEBUG: detectSemanticCommits() (repository=magic/test-renovate)
 DEBUG: Initializing git repository into /tmp/renovate/repos/github/magic/test-renovate (repository=magic/test-renovate)
 DEBUG: Performing blobless clone (repository=magic/test-renovate)
 DEBUG: git clone completed (repository=magic/test-renovate)
        "durationMs": 1151
 DEBUG: latest repository commit (repository=magic/test-renovate)
        "latestCommit": {
          "hash": "296e4231d169887c80f6ec5f2c1be1eadafb3c59",
          "date": "2022-12-13T19:09:25-05:00",
          "message": "update renovate config",
          "refs": "HEAD -> master, origin/master, origin/HEAD",
          "body": "",
          "author_name": "Dylan Greene",
          "author_email": "dgreene@medallia.com"
        }
 DEBUG: getCommitMessages (repository=magic/test-renovate)
 DEBUG: Semantic commits detection: unknown (repository=magic/test-renovate)
 DEBUG: No semantic commits detected (repository=magic/test-renovate)
 DEBUG: checkOnboarding() (repository=magic/test-renovate)
 DEBUG: isOnboarded() (repository=magic/test-renovate)
 DEBUG: findFile(renovate.json) (repository=magic/test-renovate)
 DEBUG: Config file exists, fileName: renovate.json (repository=magic/test-renovate)
 DEBUG: Retrieving issueList (repository=magic/test-renovate)
 DEBUG: Retrieved 1 issues (repository=magic/test-renovate)
 DEBUG: Repo is onboarded (repository=magic/test-renovate)
 DEBUG: Found renovate.json config file (repository=magic/test-renovate)
 DEBUG: Repository config (repository=magic/test-renovate)
        "fileName": "renovate.json",
        "config": {
          "$schema": "https://json.schemastore.org/renovate",
          "extends": [
            "config:base",
            ":rebaseStalePrs",
            ":semanticCommits",
            ":automergeAll",
            ":maintainLockFilesWeekly",
            ":prHourlyLimitNone"
          ],
          "configMigration": true,
          "postUpdateOptions": ["yarnDedupeFewer"],
          "rangeStrategy": "bump",
          "schedule": ["every weekday", "every weekend"],
          "timezone": "America/New_York",
          "updateNotScheduled": false
        }
 DEBUG: migrateAndValidate() (repository=magic/test-renovate)
 DEBUG: No config migration necessary (repository=magic/test-renovate)
 DEBUG: massaged config (repository=magic/test-renovate)
        "config": {
          "$schema": "https://json.schemastore.org/renovate",
          "extends": [
            "config:base",
            ":rebaseStalePrs",
            ":semanticCommits",
            ":automergeAll",
            ":maintainLockFilesWeekly",
            ":prHourlyLimitNone"
          ],
          "configMigration": true,
          "postUpdateOptions": ["yarnDedupeFewer"],
          "rangeStrategy": "bump",
          "schedule": ["every weekday", "every weekend"],
          "timezone": "America/New_York",
          "updateNotScheduled": false
        }
 DEBUG: migrated config (repository=magic/test-renovate)
        "config": {
          "$schema": "https://json.schemastore.org/renovate",
          "extends": [
            "config:base",
            ":rebaseStalePrs",
            ":semanticCommits",
            ":automergeAll",
            ":maintainLockFilesWeekly",
            ":prHourlyLimitNone"
          ],
          "configMigration": true,
          "postUpdateOptions": ["yarnDedupeFewer"],
          "rangeStrategy": "bump",
          "schedule": ["every weekday", "every weekend"],
          "timezone": "America/New_York",
          "updateNotScheduled": false
        }
 DEBUG: Setting hostRules from config (repository=magic/test-renovate)
 DEBUG: Found repo ignorePaths (repository=magic/test-renovate)
        "ignorePaths": [
          "**/node_modules/**",
          "**/bower_components/**",
          "**/vendor/**",
          "**/examples/**",
          "**/__tests__/**",
          "**/test/**",
          "**/tests/**",
          "**/__fixtures__/**"
        ]
 DEBUG: No vulnerability alerts found (repository=magic/test-renovate)
 DEBUG: No vulnerability alerts found (repository=magic/test-renovate)
 DEBUG: findIssue(Dependency Dashboard) (repository=magic/test-renovate)
 DEBUG: Found issue 1 (repository=magic/test-renovate)
 DEBUG: No baseBranches (repository=magic/test-renovate)
 DEBUG: extract() (repository=magic/test-renovate)
 DEBUG: Setting current branch to master (repository=magic/test-renovate)
 DEBUG: latest commit (repository=magic/test-renovate)
        "branchName": "master",
        "latestCommitDate": "2022-12-13T19:09:25-05:00"
 DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)requirements\.ya?ml$ for manager ansible-galaxy (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)galaxy\.ya?ml$ for manager ansible-galaxy (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.tool-versions$ for manager asdf (repository=magic/test-renovate)
 DEBUG: Using file match: azure.*pipelines?.*\.ya?ml$ for manager azure-pipelines (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)batect(-bundle)?\.yml$ for manager batect (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)batect$ for manager batect-wrapper (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)WORKSPACE(|\.bazel)$ for manager bazel (repository=magic/test-renovate)
 DEBUG: Using file match: \.bzl$ for manager bazel (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)\.bazelversion$ for manager bazelisk (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.?bitbucket-pipelines\.ya?ml$ for manager bitbucket-pipelines (repository=magic/test-renovate)
 DEBUG: Using file match: buildkite\.ya?ml for manager buildkite (repository=magic/test-renovate)
 DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)Gemfile$ for manager bundler (repository=magic/test-renovate)
 DEBUG: Using file match: \.cake$ for manager cake (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)Cargo\.toml$ for manager cargo (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.circleci/config\.yml$ for manager circleci (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)cloudbuild\.ya?ml for manager cloudbuild (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)Podfile$ for manager cocoapods (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)([\w-]*)composer\.json$ for manager composer (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)conanfile\.(txt|py)$ for manager conan (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)(?:deps|bb)\.edn$ for manager deps-edn (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)(?:docker-)?compose[^/]*\.ya?ml$ for manager docker-compose (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/|\.)Dockerfile$ for manager dockerfile (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)Dockerfile[^/]*$ for manager dockerfile (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.drone\.yml$ for manager droneci (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)fleet\.ya?ml for manager fleet (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)flux-system\/(?:.+\/)?gotk-components\.yaml$ for manager flux (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)\.fvm\/fvm_config\.json$ for manager fvm (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.gitmodules$ for manager git-submodules (repository=magic/test-renovate)
 DEBUG: Using file match: ^(workflow-templates|\.github\/workflows)\/[^/]+\.ya?ml$ for manager github-actions (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)action\.ya?ml$ for manager github-actions (repository=magic/test-renovate)
 DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci (repository=magic/test-renovate)
 DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci-include (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)go\.mod$ for manager gomod (repository=magic/test-renovate)
 DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)gradle\.properties$ for manager gradle (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)gradle\/.+\.toml$ for manager gradle (repository=magic/test-renovate)
 DEBUG: Using file match: \.versions\.toml$ for manager gradle (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)versions.props$ for manager gradle (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)versions.lock$ for manager gradle (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper\.properties$ for manager gradle-wrapper (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)requirements\.yaml$ for manager helm-requirements (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)values\.yaml$ for manager helm-values (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)helmfile\.yaml$ for manager helmfile (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)Chart\.yaml$ for manager helmv3 (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)bin/hermit$ for manager hermit (repository=magic/test-renovate)
 DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew (repository=magic/test-renovate)
 DEBUG: Using file match: \.html?$ for manager html (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)plugins\.(txt|ya?ml)$ for manager jenkins (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)jsonnetfile\.json$ for manager jsonnet-bundler (repository=magic/test-renovate)
 DEBUG: Using file match: ^.+\.main\.kts$ for manager kotlin-script (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)kustomization\.ya?ml$ for manager kustomize (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/|\.)pom\.xml$ for manager maven (repository=magic/test-renovate)
 DEBUG: Using file match: ^(((\.mvn)|(\.m2))/)?settings\.xml$ for manager maven (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)package\.js$ for manager meteor (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)Mintfile$ for manager mint (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)mix\.exs$ for manager mix (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)flake\.nix$ for manager nix (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.node-version$ for manager nodenv (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)package\.json$ for manager npm (repository=magic/test-renovate)
 DEBUG: Using file match: \.(?:cs|fs|vb)proj$ for manager nuget (repository=magic/test-renovate)
 DEBUG: Using file match: \.(?:props|targets)$ for manager nuget (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)dotnet-tools\.json$ for manager nuget (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)global\.json$ for manager nuget (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.nvmrc$ for manager nvm (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)([\w-]*)requirements\.(txt|pip)$ for manager pip_requirements (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)setup\.py$ for manager pip_setup (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.pre-commit-config\.yaml$ for manager pre-commit (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)Puppetfile$ for manager puppet (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.python-version$ for manager pyenv (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version (repository=magic/test-renovate)
 DEBUG: Using file match: \.sbt$ for manager sbt (repository=magic/test-renovate)
 DEBUG: Using file match: project/[^/]*.scala$ for manager sbt (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)setup\.cfg$ for manager setup-cfg (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)Package\.swift for manager swift (repository=magic/test-renovate)
 DEBUG: Using file match: \.tf$ for manager terraform (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.terraform-version$ for manager terraform-version (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)terragrunt\.hcl$ for manager terragrunt (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.terragrunt-version$ for manager terragrunt-version (repository=magic/test-renovate)
 DEBUG: Using file match: \.tflint\.hcl$ for manager tflint-plugin (repository=magic/test-renovate)
 DEBUG: Using file match: ^\.travis\.yml$ for manager travis (repository=magic/test-renovate)
 DEBUG: Using file match: (^|/)\.vela\.ya?ml$ for manager velaci (repository=magic/test-renovate)
 DEBUG: Using file match: (^|\/)\.woodpecker[^/]*\.ya?ml$ for manager woodpecker (repository=magic/test-renovate)
 DEBUG: Matched 1 file(s) for manager npm: package.json (repository=magic/test-renovate)
 DEBUG: npm file package.json has name "@m/test-renovate" (repository=magic/test-renovate)
 DEBUG: Detecting pnpm Workspaces (repository=magic/test-renovate)
 DEBUG: Detecting Lerna and Yarn Workspaces (repository=magic/test-renovate)
 DEBUG: Finding locked versions (repository=magic/test-renovate)
 DEBUG: Found npm package files (repository=magic/test-renovate)
 DEBUG: Found 1 package file(s) (repository=magic/test-renovate)
  INFO: Dependency extraction complete (repository=magic/test-renovate, baseBranch=master)
        "stats": {
          "managers": {"npm": {"fileCount": 1, "depCount": 3}},
          "total": {"fileCount": 1, "depCount": 3}
        }
 DEBUG: Using throttle 200 intervalMs for host artifactory.eng.medallia.com (repository=magic/test-renovate)
 DEBUG: Using queue: host=artifactory.eng.medallia.com, concurrency=5 (repository=magic/test-renovate)
 DEBUG: PackageFiles.add() - Package file saved for base branch (repository=magic/test-renovate, baseBranch=master)
 DEBUG: Package releases lookups complete (repository=magic/test-renovate, baseBranch=master)
 DEBUG: branchifyUpgrades (repository=magic/test-renovate)
 DEBUG: 2 flattened updates found: chalk (repository=magic/test-renovate)
 DEBUG: Returning 2 branch(es) (repository=magic/test-renovate)
 DEBUG: config.repoIsOnboarded=true (repository=magic/test-renovate)
 DEBUG: packageFiles with updates (repository=magic/test-renovate, baseBranch=master)
        "config": {
          "npm": [
            {
              "packageFile": "package.json",
              "deps": [
                {
                  "depType": "dependencies",
                  "depName": "@m/magic-cli",
                  "currentValue": "40.2.0",
                  "datasource": "npm",
                  "prettyDepType": "dependency",
                  "lockedVersion": "40.2.0",
                  "depIndex": 0,
                  "updates": [],
                  "warnings": [],
                  "versioning": "npm",
                  "sourceUrl": "https://github.medallia.com/Magic/magic",
                  "registryUrl": "https://artifactory.eng.medallia.com/api/npm/virtual-npm",
                  "currentVersion": "40.2.0",
                  "fixedVersion": "40.2.0"
                },
                {
                  "depType": "dependencies",
                  "depName": "@m/magic-jenkins",
                  "currentValue": "40.2.0",
                  "datasource": "npm",
                  "prettyDepType": "dependency",
                  "lockedVersion": "40.2.0",
                  "depIndex": 1,
                  "updates": [],
                  "warnings": [],
                  "versioning": "npm",
                  "sourceUrl": "https://github.medallia.com/Magic/magic",
                  "registryUrl": "https://artifactory.eng.medallia.com/api/npm/virtual-npm",
                  "currentVersion": "40.2.0",
                  "fixedVersion": "40.2.0"
                },
                {
                  "depType": "dependencies",
                  "depName": "chalk",
                  "currentValue": "4.1.2",
                  "datasource": "npm",
                  "prettyDepType": "dependency",
                  "lockedVersion": "4.1.2",
                  "depIndex": 2,
                  "updates": [
                    {
                      "bucket": "major",
                      "newVersion": "5.2.0",
                      "newValue": "5.2.0",
                      "releaseTimestamp": "2022-12-08T18:46:27.169Z",
                      "newMajor": 5,
                      "newMinor": 2,
                      "updateType": "major",
                      "branchName": "renovate/chalk-5.x"
                    }
                  ],
                  "warnings": [],
                  "versioning": "npm",
                  "sourceUrl": "https://github.com/chalk/chalk",
                  "registryUrl": "https://artifactory.eng.medallia.com/api/npm/virtual-npm",
                  "currentVersion": "4.1.2",
                  "isSingleVersion": true,
                  "fixedVersion": "4.1.2"
                }
              ],
              "packageJsonName": "@m/test-renovate",
              "packageFileVersion": "1.0.0",
              "yarnLock": "yarn.lock",
              "managerData": {"yarnZeroInstall": false, "hasPackageManager": false},
              "skipInstalls": true,
              "constraints": {},
              "lockFiles": ["yarn.lock"]
            }
          ]
        }
 DEBUG: processRepo() (repository=magic/test-renovate)
 DEBUG: Processing 2 branches: renovate/chalk-5.x, renovate/lock-file-maintenance (repository=magic/test-renovate)
 DEBUG: Calculating prConcurrentLimit (10) (repository=magic/test-renovate)
 DEBUG: getBranchPr(renovate/chalk-5.x) (repository=magic/test-renovate)
 DEBUG: findPr(renovate/chalk-5.x, undefined, open) (repository=magic/test-renovate)
 DEBUG: getPrList success (repository=magic/test-renovate)
        "pullsTotal": 12,
        "requestsTotal": 1,
        "apiQuotaAffected": true
 DEBUG: findPr(renovate/chalk-5.x, undefined, closed) (repository=magic/test-renovate)
 DEBUG: getBranchPr(renovate/lock-file-maintenance) (repository=magic/test-renovate)
 DEBUG: findPr(renovate/lock-file-maintenance, undefined, open) (repository=magic/test-renovate)
 DEBUG: findPr(renovate/lock-file-maintenance, undefined, closed) (repository=magic/test-renovate)
 DEBUG: 0 PRs are currently open (repository=magic/test-renovate)
 DEBUG: PR concurrent limit remaining: 10 (repository=magic/test-renovate)
 DEBUG: Calculated maximum PRs remaining this run: 10 (repository=magic/test-renovate)
 DEBUG: PullRequests limit = 10 (repository=magic/test-renovate)
 DEBUG: Calculating branchConcurrentLimit (10) (repository=magic/test-renovate)
 DEBUG: 0 already existing branches found:  (repository=magic/test-renovate)
 DEBUG: Branch concurrent limit remaining: 10 (repository=magic/test-renovate)
 DEBUG: Calculated maximum branches remaining this run: 10 (repository=magic/test-renovate)
 DEBUG: Branches limit = 10 (repository=magic/test-renovate)
 DEBUG: syncBranchState() (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: syncBranchState(): Branch cache not found, creating minimal branchState (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: getBranchPr(renovate/chalk-5.x) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: findPr(renovate/chalk-5.x, undefined, open) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: findPr(renovate/chalk-5.x, undefined, closed) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: branchExists=false (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: dependencyDashboardCheck=undefined (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: recreateClosed is false (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: findPr(renovate/chalk-5.x, fix(deps): update dependency chalk to v5, !open) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: prAlreadyExisted=false (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Checking schedule(every weekday,every weekend, America/New_York) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Found timezone: America/New_York (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Adjusting now for timezone (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Checking 2 schedule(s) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Checking schedule "every weekday" (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "parsedSchedule": {"schedules": [{"d": [2, 3, 4, 5, 6]}], "exceptions": [], "error": -1}
 DEBUG: Matches schedule every weekday (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Branch needs creating (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Using reuseExistingBranch: false (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Setting current branch to master (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: latest commit (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "branchName": "master",
        "latestCommitDate": "2022-12-13T19:09:25-05:00"
 DEBUG: manager.getUpdatedPackageFiles() reuseExistingBranch=false (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: npm.updateDependency(): dependencies.chalk = 5.2.0 (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Updating chalk in package.json (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Updated 1 package files (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Getting updated lock files (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Writing package.json files (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "packageFiles": ["package.json"]
 DEBUG: Writing any updated package files (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Writing package.json (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: npmrc file found in repository (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Generating yarn.lock for . (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Spawning yarn install to create yarn.lock (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: No node constraint found - using latest (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Updating yarn.lock only - skipping node_modules (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Performing yarn dedupe fewer (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Setting CONTAINERBASE_CACHE_DIR to /tmp/renovate/cache/containerbase (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Falling back to binarySource=global (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Executing command (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "command": "yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts"
 DEBUG: exec completed (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "durationMs": 68832,
        "stdout": "",
        "stderr": "\u001b[2K\u001b[1G\u001b[33mwarning\u001b[39m \"@m/magic-jenkins > @m/magic-publish > @m/magic-build > @m/magic-webpack@40.2.0\" has unmet peer dependency \"@m/babel-preset-magic@*\".\n\u001b[2K\u001b[1G\u001b[33mwarning\u001b[39m \"@m/magic-jenkins > @m/magic-publish > @m/magic-build > @m/magic-webpack > webpack-filter-warnings-plugin@1.2.1\" has incorrect peer dependency \"webpack@^2.0.0 || ^3.0.0 || ^4.0.0\".\n\u001b[2K\u001b[1G\u001b[33mwarning\u001b[39m \"@m/magic-jenkins > @m/magic-publish > @m/magic-build > @m/magic-webpack > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.2\" has unmet peer dependency \"typescript@>= 2.7\".\n\u001b[2K\u001b[1G\u001b[33mwarning\u001b[39m Workspaces can only be enabled in private projects.\n\u001b[2K\u001b[1G\u001b[33mwarning\u001b[39m Ignored scripts due to flag.\n"
 DEBUG: Executing command (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "command": "npx yarn-deduplicate --strategy fewer"
 DEBUG: exec completed (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "durationMs": 5241,
        "stdout": "",
        "stderr": "npm WARN exec The following package was not found and will be installed: yarn-deduplicate\n"
 DEBUG: Executing command (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "command": "yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts"
 DEBUG: exec completed (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "durationMs": 11614,
        "stdout": "",
        "stderr": "\u001b[2K\u001b[1G\u001b[33mwarning\u001b[39m \"@m/magic-jenkins > @m/magic-publish > @m/magic-build > @m/magic-webpack@40.2.0\" has unmet peer dependency \"@m/babel-preset-magic@*\".\n\u001b[2K\u001b[1G\u001b[33mwarning\u001b[39m \"@m/magic-jenkins > @m/magic-publish > @m/magic-build > @m/magic-webpack > webpack-filter-warnings-plugin@1.2.1\" has incorrect peer dependency \"webpack@^2.0.0 || ^3.0.0 || ^4.0.0\".\n\u001b[2K\u001b[1G\u001b[33mwarning\u001b[39m \"@m/magic-jenkins > @m/magic-publish > @m/magic-build > @m/magic-webpack > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.2\" has unmet peer dependency \"typescript@>= 2.7\".\n\u001b[2K\u001b[1G\u001b[33mwarning\u001b[39m Ignored scripts due to flag.\n"
 DEBUG: yarn.lock needs updating (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: updateYarnOffline resolvedPaths (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "resolvedPaths": []
 DEBUG: Updated 1 lock files (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "updatedArtifacts": ["yarn.lock"]
 DEBUG: 2 file(s) to commit (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Preparing files for committing to branch renovate/chalk-5.x (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Setting git author name: null (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Setting git author email: service-continuous-deliver@medallia.com (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: git commit (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "deletedFiles": [],
        "ignoredFiles": [],
        "result": {
          "author": null,
          "branch": "renovate/chalk-5.x",
          "commit": "31b752a9b31b4f55edb98ae89905d9f978157214",
          "root": false,
          "summary": {"changes": 2, "insertions": 39, "deletions": 240}
        }
 DEBUG: Pushing branch renovate/chalk-5.x (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: git push (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "result": {
          "pushed": [
            {
              "deleted": false,
              "tag": false,
              "branch": true,
              "new": true,
              "alreadyUpdated": false,
              "local": "refs/heads/renovate/chalk-5.x",
              "remote": "refs/heads/renovate/chalk-5.x"
            }
          ],
          "branch": {
            "local": "renovate/chalk-5.x",
            "remote": "renovate/chalk-5.x",
            "remoteName": "origin"
          },
          "ref": {"local": "refs/remotes/origin/renovate/chalk-5.x"},
          "remoteMessages": {
            "all": [
              "This repository moved. Please use the new location:",
              "https://github.medallia.com/Magic/test-renovate.git",
              "Create a pull request for 'renovate/chalk-5.x' on GitHub by visiting:",
              "https://github.medallia.com/Magic/test-renovate/pull/new/renovate/chalk-5.x"
            ],
            "pullRequestUrl": "https://github.medallia.com/Magic/test-renovate/pull/new/renovate/chalk-5.x"
          }
        }
  INFO: Branch created (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "commitSha": "31b752a9b31b4f55edb98ae89905d9f978157214"
 DEBUG: Ensuring PR (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: There are 0 errors and 0 warnings (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: getBranchPr(renovate/chalk-5.x) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: findPr(renovate/chalk-5.x, undefined, open) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: findPr(renovate/chalk-5.x, undefined, closed) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Fetching changelog: https://github.com/chalk/chalk (4.1.2 -> 5.2.0) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Using throttle 1000 intervalMs for host api.github.com (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Using queue: host=api.github.com, concurrency=1 (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Creating PR (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "prTitle": "fix(deps): update dependency chalk to v5"
 DEBUG: Creating PR (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "title": "fix(deps): update dependency chalk to v5",
        "head": "magic:renovate/chalk-5.x",
        "base": "master",
        "draft": false
 DEBUG: PR created (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "pr": 14,
        "draft": false
 DEBUG: Adding labels '' to #14 (repository=magic/test-renovate, branch=renovate/chalk-5.x)
  INFO: PR created (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "pr": 14,
        "prTitle": "fix(deps): update dependency chalk to v5"
 DEBUG: resolveBranchStatus(branchName=renovate/chalk-5.x, ignoreTests=false) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: getBranchStatus(renovate/chalk-5.x) (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: branch status check result (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "state": "pending",
        "statuses": []
 DEBUG: No check runs found (repository=magic/test-renovate, branch=renovate/chalk-5.x)
        "result": {"total_count": 0, "check_runs": []}
 DEBUG: Branch status yellow (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Skipping assignees and reviewers as automerge=true (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: Created Pull Request #14 (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: PR is configured for automerge (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: setBranchCommit() (repository=magic/test-renovate, branch=renovate/chalk-5.x)
 DEBUG: syncBranchState() (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: syncBranchState(): Branch cache not found, creating minimal branchState (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: getBranchPr(renovate/lock-file-maintenance) (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: findPr(renovate/lock-file-maintenance, undefined, open) (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: findPr(renovate/lock-file-maintenance, undefined, closed) (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: branchExists=false (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: dependencyDashboardCheck=undefined (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: recreateClosed is true (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: Checking schedule(before 3am on Monday, America/New_York) (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: Found timezone: America/New_York (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: Adjusting now for timezone (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: Checking 1 schedule(s) (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: Checking schedule "before 3am on Monday" (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
        "parsedSchedule": {"schedules": [{"t_b": [10800], "d": [2]}], "exceptions": [], "error": -1}
 DEBUG: Package not scheduled (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: Skipping branch creation as not within schedule (repository=magic/test-renovate, branch=renovate/lock-file-maintenance)
 DEBUG: getBranchPr(renovate/chalk-5.x) (repository=magic/test-renovate)
 DEBUG: findPr(renovate/chalk-5.x, undefined, open) (repository=magic/test-renovate)
 DEBUG: findPr(renovate/chalk-5.x, undefined, closed) (repository=magic/test-renovate)
 DEBUG: branch.isBehindBase(): using cached result "false" (repository=magic/test-renovate)
 DEBUG: isBranchConflicted(master, renovate/chalk-5.x) (repository=magic/test-renovate)
 DEBUG: branch.isConflicted(): using cached result "false" (repository=magic/test-renovate)
 DEBUG: Ensuring Dependency Dashboard (repository=magic/test-renovate)
 DEBUG: ensureIssue(Dependency Dashboard) (repository=magic/test-renovate)
 DEBUG: Patching issue (repository=magic/test-renovate)
 DEBUG: Issue updated (repository=magic/test-renovate)
 DEBUG: checkConfigMigrationBranch() (repository=magic/test-renovate)
 DEBUG: checkConfigMigrationBranch() Config does not need migration (repository=magic/test-renovate)
 DEBUG: Removing any stale branches (repository=magic/test-renovate)
 DEBUG: config.repoIsOnboarded=true (repository=magic/test-renovate)
 DEBUG: Branch lists (repository=magic/test-renovate)
        "branchList": ["renovate/chalk-5.x", "renovate/lock-file-maintenance"],
        "renovateBranches": ["renovate/chalk-5.x"]
 DEBUG: remainingBranches= (repository=magic/test-renovate)
 DEBUG: No branches to clean up (repository=magic/test-renovate)
 DEBUG: PackageFiles.clear() - Package files deleted (repository=magic/test-renovate)
 DEBUG: Branch summary (repository=magic/test-renovate)
        "cacheModified": undefined,
        "baseBranches": [{"branchName": "master", "sha": "296e4231d169887c80f6ec5f2c1be1eadafb3c59"}],
        "branches": [
          {
            "automerge": true,
            "baseBranch": "master",
            "baseBranchSha": "296e4231d169887c80f6ec5f2c1be1eadafb3c59",
            "branchName": "renovate/chalk-5.x",
            "branchSha": "31b752a9b31b4f55edb98ae89905d9f978157214",
            "isModified": false,
            "isPristine": true
          }
        ],
        "inactiveBranches": ["renovate/lock-file-maintenance"]
 DEBUG: Renovate repository PR statistics (repository=magic/test-renovate)
        "stats": {"total": 13, "open": 1, "closed": 12, "merged": 0}
 DEBUG: Repository result: done, status: onboarded, enabled: true, onboarded: true (repository=magic/test-renovate)
 DEBUG: Repository timing splits (milliseconds) (repository=magic/test-renovate)
        "splits": {
          "init": 3360,
          "extract": 1046,
          "lookup": 21130,
          "onboarding": 2,
          "update": 94159
        },
        "total": 124405
 DEBUG: Package cache statistics (repository=magic/test-renovate)
        "get": {"count": 15, "avgMs": 3, "medianMs": 0, "maxMs": 22},
        "set": {"count": 12, "avgMs": 7, "medianMs": 6, "maxMs": 15}
 DEBUG: http statistics (repository=magic/test-renovate)
        "urls": {
          "https://api.github.com/repos/chalk/chalk (GET,200)": 1,
          "https://api.github.com/repos/chalk/chalk/git/trees/main (GET,200)": 1,
          "https://api.github.com/repos/chalk/chalk/releases (GET,200)": 1,
          "https://api.github.com/repos/chalk/chalk/tags (GET,200)": 1,
          "https://artifactory.eng.medallia.com/api/npm/virtual-npm/@m%2Fmagic-cli (GET,200)": 1,
          "https://artifactory.eng.medallia.com/api/npm/virtual-npm/@m%2Fmagic-jenkins (GET,200)": 1,
          "https://artifactory.eng.medallia.com/api/npm/virtual-npm/chalk (GET,200)": 1,
          "https://github.medallia.com/api/graphql (POST,200)": 2,
          "https://github.medallia.com/api/v3/repos/magic/test-renovate/commits/renovate/chalk-5.x/check-runs (GET,200)": 1,
          "https://github.medallia.com/api/v3/repos/magic/test-renovate/commits/renovate/chalk-5.x/status (GET,200)": 1,
          "https://github.medallia.com/api/v3/repos/magic/test-renovate/contents/renovate.json (GET,200)": 1,
          "https://github.medallia.com/api/v3/repos/magic/test-renovate/issues/1 (GET,200)": 2,
          "https://github.medallia.com/api/v3/repos/magic/test-renovate/issues/1 (PATCH,200)": 1,
          "https://github.medallia.com/api/v3/repos/magic/test-renovate/pulls (GET,200)": 1,
          "https://github.medallia.com/api/v3/repos/magic/test-renovate/pulls (POST,201)": 1
        },
        "hostStats": {
          "api.github.com": {"requestCount": 4, "requestAvgMs": 288, "queueAvgMs": 542},
          "artifactory.eng.medallia.com": {
            "requestCount": 3,
            "requestAvgMs": 6142,
            "queueAvgMs": 200
          },
          "github.medallia.com": {
            "requestCount": 10,
            "requestAvgMs": 304,
            "queueAvgMs": 0
          }
        },
        "totalRequests": 17
 DEBUG: dns cache (repository=magic/test-renovate)
        "hosts": []
  INFO: Repository finished (repository=magic/test-renovate)
        "cloned": true,
        "durationMs": 124405
 DEBUG: Renovate exiting
```

</details>

### Have you created a minimal reproduction repository?

I have created a minimal reproduction repository, but it is on Github Enterprise.

### PR DESCRIPTION
**Pull request by rarkins**
## Context

Fixes #19386

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/platform/github/index.ts [hunk 1]
```diff
@@ -719,7 +719,10 @@ export async function findPr({
       return false;
     }
 
-    if (!config.forkToken && config.repository !== p.sourceRepo) {
+    if (
+      !config.forkToken &&
+      config.repository?.toLowerCase() !== p.sourceRepo?.toLowerCase()
```
Comment (viceice) [inline lib/modules/platform/github/index.ts:724]:
```suggestion
      config.repository?.localeCompare(p.sourceRepo, undefined, { sensitivity: 'accent' }) === 0
```
better use `localeCompare`

- https://stackoverflow.com/a/2140723/10109857

File: lib/util/string.ts [hunk 2]
```diff
@@ -45,3 +45,13 @@ export function uniqueStrings(
...
   return elements.indexOf(element) === index;
 }
+
+export function looseEquals(
+  a: string | null | undefined,
+  b: string | null | undefined
+): boolean {
+  if (!(a && b)) {
+    return a === b;
+  }
```
Comment (rarkins) [inline lib/util/string.ts:55]: @viceice OK to do a raw equals like this if a or b is not truthy?

**Review by viceice — COMMENTED** [review]
needs import order and coverage

File: lib/util/string.ts (hunk 2 above)
Comment (viceice) [reply lib/util/string.ts:55]: so `null === undefined` will return `false`

**Review by viceice — APPROVED** [review]
