### PR TITLE
fix: commit message

### LINKED ISSUE #12062: Commit messages should not be fully lowercased
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Describe the bug

When Renovate opens a PR with semantic commits the entire commit message/PR title is lowercased. This is unnecessary, only the first letter needs to be lowercased ([per Angular commit guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#summary), I think most other semantic commit specs do the same).

Given the title:

```
fix(deps): Update My Org dependencies
```

Actual behavior:

```
fix(deps): update my org dependencies
```

Expected:

```
fix(deps): update My Org dependencies
```

Relevant code:
https://github.com/renovatebot/renovate/blob/00e191795ce9a56752ece1891b41d0b6b92cba77/lib/workers/repository/updates/generate.ts#L184-L189

### Relevant debug logs

_No response_

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by pret-a-porter**
## Changes:

1. Implemented abstract class CommitMessage
2. Implemented class CustomCommitMessage
3. Implemented class SemanticCommitMessage
4. Implemented factory CommitMessageFactory for creating instance of SemanticCommitMessage or CustomCommitMessage by provided shared renovate config
5. Logic of generating PR title improved by using CommitMessageFactory

## Context:

Fixes #12062

## Documentation

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/config/options/index.ts [hunk 1]
```diff
@@ -1472,7 +1472,7 @@ const options: RenovateOptions[] = [
     description: 'Message to use for commit messages and pull request titles.',
     type: 'string',
     default:
-      '{{{commitMessagePrefix}}} {{{commitMessageAction}}} {{{commitMessageTopic}}} {{{commitMessageExtra}}} {{{commitMessageSuffix}}}',
+      '{{{commitMessageAction}}} {{{commitMessageTopic}}} {{{commitMessageExtra}}} {{{commitMessageSuffix}}}',
```
Comment (viceice) [inline lib/config/options/index.ts:1475]: is this intended?

File: lib/workers/repository/model/commit-message-factory.ts [hunk 2]
```diff
@@ -0,0 +1,51 @@
+import { RenovateSharedConfig } from '../../../config/types';
+import { CommitMessage } from './commit-message';
```
Comment (viceice) [inline lib/workers/repository/model/commit-message-factory.ts:2]:
```suggestion
import type { RenovateSharedConfig } from '../../../config/types';
import type { CommitMessage } from './commit-message';
```

File: lib/workers/repository/onboarding/branch/commit-message.ts [hunk 3]
```diff
@@ -1,5 +1,6 @@
 import { RenovateConfig } from '../../../../config/types';
 import { CommitMessage } from '../../model/commit-message';
```
Comment (viceice) [inline lib/workers/repository/onboarding/branch/commit-message.ts:2]:
```suggestion
import type { RenovateConfig } from '../../../../config/types';
import type { CommitMessage } from '../../model/commit-message';
```

File: lib/workers/repository/model/semantic-commit-message.ts [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+  static fromString(value: string): SemanticCommitMessage {
+    const { groups } = value.match(SemanticCommitMessage.REGEXP);
+
+    const message = new SemanticCommitMessage();
+    message.setType(groups.type);
+    message.setScope(groups.scope);
+    message.setSubject(groups.description);
+
+    return message;
+  }
```
Comment (viceice) [inline lib/workers/repository/model/semantic-commit-message.ts:35]: Do we really need this? The regex is pretty bad!

File: lib/workers/repository/model/semantic-commit-message.ts [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+    this.scope = scope?.trim();
+  }
+
+  setType(type?: string): void {
+    this.type = type?.trim();
+  }
+
+  protected get prefix(): string {
+    if (!this.scope && !this.type) {
+      return '';
```
Comment (viceice) [inline lib/workers/repository/model/semantic-commit-message.ts:57]: Missing coverage 😉

File: lib/config/options/index.ts (hunk 1 above)
Comment (pret-a-porter) [reply lib/config/options/index.ts:1475]: Yeah, now it is responsibility of `SemanticCommitMessage` or `CustomCommitMessage`

File: lib/workers/repository/model/semantic-commit-message.ts (hunk 4 above)
Comment (pret-a-porter) [reply lib/workers/repository/model/semantic-commit-message.ts:35]: Yeah, we need it. I open for good suggestions about regex or another way to implement this function

Comment (pret-a-porter) [reply lib/workers/repository/model/semantic-commit-message.ts:35]: I have changed regex a bit, now it should be better

File: lib/config/options/index.ts (hunk 1 above)
Comment (rarkins) [reply lib/config/options/index.ts:1475]: I don't think we can make this change without it being breaking

Comment (rarkins) [reply lib/config/options/index.ts:1475]: And this is not the type of breaking where you can just add a breaking flag and move on

Comment (rarkins) [reply lib/config/options/index.ts:1475]: In future, avoid make such design decisions without discussing the issue first, because it can lead to PRs which get rejected

Comment (pret-a-porter) [reply lib/config/options/index.ts]: Sorry guys, it was unnecessary change. Unit tests for `generate.ts` works fine even without this change

**Comment by rarkins** [comment]
I feel concerned when there's so many changes to both implementation *and* tests at the same time - it's much easier for us to miss a regression test. @pret-a-porter can you split this, e.g. to change the tests part first with minimal changes to the implementation?

**Comment by pret-a-porter** [comment]
> I feel concerned when there's so many changes to both implementation _and_ tests at the same time - it's much easier for us to miss a regression test. @pret-a-porter can you split this, e.g. to change the tests part first with minimal changes to the implementation?

Yeah, I can. It can be two next PR's:
1.  Refactoring `CommitMessage` class and introducing new `SemanticCommitMessage` class
2. Changing `generateBranchConfig` functionality

**Comment by pret-a-porter** [comment]
@rarkins I have extracted https://github.com/renovatebot/renovate/pull/13328

**Review by viceice — CHANGES_REQUESTED** [review]
blocked by #13328

**Comment by rarkins** [comment]
Conflicted and blocked, so closing for now

**Comment by pret-a-porter** [comment]
Blocker merged and conflicts were solved. Ready to review again

**Review by rarkins — DISMISSED** [review]

File: lib/workers/repository/updates/generate.spec.ts [hunk 6]
```diff
@@ -482,7 +482,7 @@ describe('workers/repository/updates/generate', () => {
         }),
       ];
       const res = generateBranchConfig(branch);
-      expect(res.prTitle).toBe('chore(): update dependency some-dep to v1.2.0');
+      expect(res.prTitle).toBe('chore: update dependency some-dep to v1.2.0');
```
Comment (viceice) [inline lib/workers/repository/updates/generate.spec.ts:485]: another fixed bug?

File: lib/workers/repository/updates/generate.ts [hunk 7]
```diff
@@ -166,28 +167,30 @@ export function generateBranchConfig(
...
     // Compile a few times in case there are nested templates
-    upgrade.commitMessage = template.compile(
+    commitMessage.subject = template.compile(
       upgrade.commitMessage || '',
       upgrade
     );
-    upgrade.commitMessage = template.compile(upgrade.commitMessage, upgrade);
-    upgrade.commitMessage = template.compile(upgrade.commitMessage, upgrade);
+    commitMessage.subject = template.compile(
+      commitMessage.toJSON().subject,
```
Comment (viceice) [inline lib/workers/repository/updates/generate.ts:186]:
```suggestion
      commitMessage.subject,
```
i don't like this, can we make the getter public instead

File: lib/workers/repository/updates/generate.spec.ts (hunk 6 above)
Comment (pret-a-porter) [reply lib/workers/repository/updates/generate.spec.ts:485]: Seems like that

File: lib/workers/repository/updates/generate.ts (hunk 7 above)
Comment (pret-a-porter) [reply lib/workers/repository/updates/generate.ts]: Done

**Review by rarkins — DISMISSED** [review]

File: lib/workers/repository/updates/generate.ts [hunk 8]
```diff
@@ -196,23 +193,13 @@ export function generateBranchConfig(
       );
       throw new Error(CONFIG_SECRETS_EXPOSED);
     }
-    upgrade.commitMessage = upgrade.commitMessage.trim(); // Trim exterior whitespace
-    upgrade.commitMessage = upgrade.commitMessage.replace(regEx(/\s+/g), ' '); // Trim extra whitespace inside string
     upgrade.commitMessage = upgrade.commitMessage.replace(
       regEx(/to vv(\d)/),
       'to v$1'
     );
```
Comment (viceice) [inline lib/workers/repository/updates/generate.ts:199]: Wont this be lost when `commitBody` isa set now?

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/workers/repository/updates/generate.ts (hunk 8 above)
Comment (pret-a-porter) [reply lib/workers/repository/updates/generate.ts:199]: Sorry, I did not get the question. Could you please elaborate?

Comment (pret-a-porter) [reply lib/workers/repository/updates/generate.ts:199]: @viceice ?

Comment (viceice) [reply lib/workers/repository/updates/generate.ts:199]: please follow code flow. it looks like this code is no longer always applied

Comment (pret-a-porter) [reply lib/workers/repository/updates/generate.ts:199]: I have added new unit test, seems like everything works fine. Meanwhile I am not sure this functionality is still necessary

Comment (viceice) [reply lib/workers/repository/updates/generate.ts:199]: this will happen, when the `newValue` has a leading `v` like it's often used for git tags

Comment (viceice) [reply lib/workers/repository/updates/generate.ts:199]: You don't have a test with `commitBody` and `vv` `commitMessage`.

I think this code now needs to be moved below the `if (upgrade.commitBody) {` condition

File: lib/workers/repository/updates/generate.spec.ts [hunk 9]
```diff
@@ -908,5 +908,16 @@ describe('workers/repository/updates/generate', () => {
...
+    it('fixes commit message', () => {
+      const branch = [
+        partial<BranchUpgradeConfig>({
+          ...defaultConfig,
+          commitMessage: 'update to vv1.2.0',
+        }),
+      ];
+      const res = generateBranchConfig(branch);
+      expect(res.commitMessage).toBe('Update to v1.2.0');
+    });
```
Comment (viceice) [inline lib/workers/repository/updates/generate.spec.ts:921]:
```suggestion
    });

    it('fixes commit message with body', () => {
      const branch = [
        partial<BranchUpgradeConfig>({
          ...defaultConfig,
          commitMessage: 'update to vv1.2.0',
          commitBody: 'some body'
        }),
      ];
      const res = generateBranchConfig(branch);
      expect(res.commitMessage).toBe('Update to v1.2.0\n\nsome body');
    });
```

Comment (pret-a-porter) [reply lib/workers/repository/updates/generate.spec.ts:922]: Done

File: lib/workers/repository/updates/generate.ts (hunk 8 above)
Comment (pret-a-porter) [reply lib/workers/repository/updates/generate.ts]: I have added unit test proposed by you and changed code a bit

**Review by viceice — APPROVED** [review]
