### PR TITLE
fix(docker): Fixes issue with private docker registry on amazon s3

### LINKED ISSUE #3877: Private docker registry blob downloads fail when registry uses Amazon S3 Transfer Acceleration
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
When a private docker registry is hosted on aws and configured to use Amazon S3 Transfer Acceleration, any requests to actually download blobs are redirected, and the generated redirect url contains the required credentials to download the blob.

Currently renovate is including the Authentication header in the redirect request, which causes the redirect request to amazon to error with:

```xml
<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error>
    <Code>InvalidArgument</Code>
    <Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message>
    <ArgumentName>Authorization</ArgumentName>
    <ArgumentValue>Bearer some-bearer-token</ArgumentValue>
    <RequestId>some-request-id</RequestId>
    <HostId>some-host-id</HostId>
</Error>
```

**To Reproduce**
Difficult without having a private docker registry hosted on aws using Amazon S3 Transfer Acceleration.

**Expected behavior**
When a docker registry request for a block redirects, we should check the redirect url query string for 'X-Amz-Algorithm'. If it is found, delete the Authorization header from the request made to the redirect url.

**Additional context**
https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

### PR DESCRIPTION
**Pull request by gordlea**
When renovate goes to download a blob from a docker registry, if the response is a redirect, and the redirect url contains the string `X-Amz-Algorithm`, delete the `Authorization` header from the redirect request.

This solves an issue when private docker registries are hosted on amazon and use Amazon S3 Transfer Acceleration. See issue #3877 for more details.

Closes #3877

### CODE REVIEW

File: lib/datasource/docker/index.js [hunk 1]
```diff
@@ -388,6 +388,17 @@ async function getLabels(registry, repository, tag) {
       const url = `${registry}/v2/${repository}/blobs/${configDigest}`;
       const configResponse = await got(url, {
         headers,
+        hooks: {
+          beforeRedirect: [
+            options => {
+              if (options.search.indexOf('X-Amz-Algorithm') !== -1) {
```
Comment (rarkins) [inline lib/datasource/docker/index.js]: Can we add a defensive check that `option.search` exists, unless it's documented somewhere to be guaranteed? Don't want us blowing up some day because it stops being present.

**Comment by rarkins** [comment]
@gordlea this is a very clever fix, thank you for providing it. Have you also experienced the problem described in https://github.com/renovatebot/renovate/issues/3800 ?

File: lib/datasource/docker/index.js (hunk 1 above)
Comment (gordlea) [reply lib/datasource/docker/index.js]: Good idea, I'll add that in.

**Comment by gordlea** [comment]
Hi @rarkins, thank you, I tried to make the fix as unobtrusive as possible. I have not experienced #3800, as I don't believe we are actually using ECR (I may be wrong about that).

**Comment by rarkins** [comment]
Thanks again
