### PR TITLE
fix: force optional options

### LINKED ISSUE #6811: npm-shrinkwrap.json renovation failing
**What Renovate type are you using?**

Self hosted

**Describe the bug**

Lock file maintenance for `npm-shrinkwrap.json` does not get applied

**Relevant debug logs**

There is a `lock file error` log with the following stack trace:

```
TypeError: Cannot read property 'overwrite' of undefined
    at Object.move (/Users/dominykas/devel/projects/test/node_modules/fs-extra/lib/move/move.js:17:26)
    at /Users/dominykas/devel/projects/test/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.move (/Users/dominykas/devel/projects/test/node_modules/universalify/index.js:7:14)
    at Object.move (/Users/dominykas/devel/projects/test/node_modules/renovate/dist/util/fs/proxies.js:69:15)
    at Object.generateLockFile (/Users/dominykas/devel/projects/test/node_modules/renovate/dist/manager/npm/post-update/npm.js:87:24)
    at async Object.getAdditionalFiles (/Users/dominykas/devel/projects/test/node_modules/renovate/dist/manager/npm/post-update/index.js:349:21)
    at async Object.processBranch (/Users/dominykas/devel/projects/test/node_modules/renovate/dist/workers/branch/index.js:231:33)
    at async Object.writeUpdates (/Users/dominykas/devel/projects/test/node_modules/renovate/dist/workers/repository/process/write.js:25:21)
    at async Object.update (/Users/dominykas/devel/projects/test/node_modules/renovate/dist/workers/repository/process/extract-update.js:95:15)
    at async Object.renovateRepository (/Users/dominykas/devel/projects/test/node_modules/renovate/dist/workers/repository/index.js:41:21)
    at async Object.start (/Users/dominykas/devel/projects/test/node_modules/renovate/dist/workers/global/index.js:76:13)
    at async /Users/dominykas/devel/projects/test/node_modules/renovate/dist/renovate.js:28:24
```

**To Reproduce**

1. Have a repo with an `npm-shrinkwrap.json`
2. Perform a renovation there

**Additional context**

I suspect https://github.com/renovatebot/renovate/issues/6617 / https://github.com/renovatebot/renovate/pull/6683 might have broken it?

### PR DESCRIPTION
**Pull request by viceice**
`fs-extra` is using `arguments.length` to compute optional args and callback version. So if we pass `undefined` as options it will crash because of wrong argument count.

Closes #6811

### CODE REVIEW

File: lib/util/fs/proxies.ts [hunk 1]
```diff
@@ -68,5 +68,5 @@ export function move(
   dest: string,
   options?: MoveOptions
 ): Promise<void> {
-  return fs.move(src, dest, options);
+  return fs.move(src, dest, options ?? {});
```
Comment (zharinov) [inline lib/util/fs/proxies.ts:71]: 👍
