### PR TITLE
fix(circleci): add android to machine image skipping

### LINKED ISSUE #15788: CircleCI machine image extraction skipping not sufficient
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

The fix for the issue originally raised in #8656 (fixed in 264ff284e78724dda8d07b7c8421c998d56adbfc) is incomplete, as it only matches against circleci images that either start `ubuntu-` or `windows-server-`.

Some circleci machine images don't have this prefix, causing renovate to treat them like regular docker images and try to look them up on Docker Hub, which fails.

For example, in the circleci config:

``` yaml
...
job-name:
  machine:                                                                                                                                                                  
    image: android:2022.04.1
  resource-class: large
...
```
This refers to a circleci machine image called `android`, leading to the error below. This is currently failing on https://github.com/owntracks/android/commit/16a94e96a46c861b662c620a7be531720442e0d8

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: docker registry failure: unauthorized
{
  "registryHost": "https://index.docker.io",
  "dockerRepository": "library/android",
  "err": {
    "name": "HTTPError",
    "code": "ERR_NON_2XX_3XX_RESPONSE",
    "timings": {
      "start": 1653905325495,
      "socket": 1653905325495,
      "lookup": 1653905325511,
      "connect": 1653905325582,
      "secureConnect": 1653905325765,
      "upload": 1653905325765,
      "response": 1653905325862,
      "end": 1653905325862,
      "phases": {
        "wait": 0,
        "dns": 16,
        "tcp": 71,
        "tls": 183,
        "request": 0,
        "firstByte": 97,
        "download": 0,
        "total": 367
      }
    },
    "message": "Response code 401 (Unauthorized)",
    "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "options": {
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "authorization": "***********",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate, br"
      },
      "url": "https://index.docker.io/v2/library/android/tags/list?n=10000",
      "hostType": "docker",
      "username": "",
      "password": "",
      "method": "GET",
      "http2": false
    },
    "response": {
      "statusCode": 401,
      "statusMessage": "Unauthorized",
      "body": {
        "errors": [
          {
            "code": "UNAUTHORIZED",
            "message": "authentication required",
            "detail": [
              {
                "Type": "repository",
                "Class": "",
                "Name": "library/android",
                "Action": "pull"
              }
            ]
          }
        ]
      },
      "headers": {
        "content-type": "application/json",
        "docker-distribution-api-version": "registry/2.0",
        "www-authenticate": "Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:library/android:pull\",error=\"insufficient_scope\"",
        "date": "Mon, 30 May 2022 10:08:45 GMT",
        "content-length": "158",
        "strict-transport-security": "max-age=31536000",
        "connection": "close"
      },
      "httpVersion": "1.1"
    }
  }
}
WARN: Host error
{
  "hostType": "docker",
  "packageName": "android",
  "err": {
    "name": "HTTPError",
    "code": "ERR_NON_2XX_3XX_RESPONSE",
    "timings": {
      "start": 1653905325495,
      "socket": 1653905325495,
      "lookup": 1653905325511,
      "connect": 1653905325582,
      "secureConnect": 1653905325765,
      "upload": 1653905325765,
      "response": 1653905325862,
      "end": 1653905325862,
      "phases": {
        "wait": 0,
        "dns": 16,
        "tcp": 71,
        "tls": 183,
        "request": 0,
        "firstByte": 97,
        "download": 0,
        "total": 367
      }
    },
    "message": "Response code 401 (Unauthorized)",
    "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "options": {
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "authorization": "***********",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate, br"
      },
      "url": "https://index.docker.io/v2/library/android/tags/list?n=10000",
      "hostType": "docker",
      "username": "",
      "password": "",
      "method": "GET",
      "http2": false
    },
    "response": {
      "statusCode": 401,
      "statusMessage": "Unauthorized",
      "body": {
        "errors": [
          {
            "code": "UNAUTHORIZED",
            "message": "authentication required",
            "detail": [
              {
                "Type": "repository",
                "Class": "",
                "Name": "library/android",
                "Action": "pull"
              }
            ]
          }
        ]
      },
      "headers": {
        "content-type": "application/json",
        "docker-distribution-api-version": "registry/2.0",
        "www-authenticate": "Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:library/android:pull\",error=\"insufficient_scope\"",
        "date": "Mon, 30 May 2022 10:08:45 GMT",
        "content-length": "158",
        "strict-transport-security": "max-age=31536000",
        "connection": "close"
      },
      "httpVersion": "1.1"
    }
  }
}
INFO: External host error causing abort - skipping
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by Gabriel-Ladzaretti**
## Changes
Skip android machine images as per  [docs](https://circleci.com/docs/2.0/android-machine-image/#no-orb-example)

## Context
Closes #15788 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/circleci/extract.ts [hunk 1]
```diff
@@ -63,7 +63,8 @@ export function extractPackageFile(content: string): PackageFile | null {
         dep.versioning = 'docker';
         if (
           !dep.depName?.startsWith('ubuntu-') &&
-          !dep.depName?.startsWith('windows-server-')
+          !dep.depName?.startsWith('windows-server-') &&
+          !dep.depName?.startsWith('android')
```
Comment (viceice) [inline lib/modules/manager/circleci/extract.ts:67]:
```suggestion
          !dep.depName?.startsWith('android:')
```

Comment (Gabriel-Ladzaretti) [reply lib/modules/manager/circleci/extract.ts:67]: it doesn't work with colon, that was my first intuition too.

Comment (rarkins) [reply lib/modules/manager/circleci/extract.ts:67]: Should it be a strict equals?

Comment (Gabriel-Ladzaretti) [reply lib/modules/manager/circleci/extract.ts:67]: im not that familiar with circleci, but from what i gathered from their docs it might be.
https://circleci.com/docs/2.0/android-machine-image/#no-orb-example

Comment (viceice) [reply lib/modules/manager/circleci/extract.ts:67]: so check both equal for `android` only and `android-` prefix for te other?

Comment (Gabriel-Ladzaretti) [reply lib/modules/manager/circleci/extract.ts:67]: i searched github for [`android-` ](https://github.com/search?p=4&q=path%3A%2F.circleci%2F+filename%3Aconfig.yml+android-&type=Code) and it doesnt seems to be a thing.
while `android` without the dash yields much more results.
WDYT?

Comment (rarkins) [reply lib/modules/manager/circleci/extract.ts:67]: I think it's ok if we check for exactly android or starting with `android-`, in case they add that scheme in future.

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
