### PR TITLE
fix(versioning/ruby): prevent extra `vv` prefix addition

### LINKED ISSUE #35494: Bundler: git dependency tag update adds extra "v" (v13 -> vv14)
### Discussed in https://github.com/renovatebot/renovate/discussions/35231

<div type='discussions-op-text'>

<sup>Originally posted by **jgraichen** April  7, 2025</sup>
### How are you running Renovate?

A Mend.io-hosted app

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

_No response_

### Please tell us more about your question or problem

I have a PR [here](https://github.com/jgraichen/msgr/pull/57/files) where renovate updates a git dependency in a `Gemfile` but adds an extra `"v"` to the tag name, which breaks the file:

```diff
diff --git a/Gemfile b/Gemfile
index 4a0f91c..59ffe9e 100644
--- a/Gemfile
+++ b/Gemfile
@@ -12,7 +12,7 @@ gem 'rspec-rails'
 gem 'simplecov', require: false
 gem 'simplecov-cobertura', require: false
 
-gem 'rubocop-config', github: 'jgraichen/rubocop-config', tag: 'v13', require: false
+gem 'rubocop-config', github: 'jgraichen/rubocop-config', tag: 'vv14', require: false
 
 gem 'rails'
 gem 'sqlite3'

```

The logs show the new version correctly being detected as `v14`, but the `newValue` equals `vv14`.

Reproduction: https://github.com/jgraichen/renovate-bundler-git-tag/pull/2

### Logs (if relevant)

<details><summary>Logs</summary>

```
DEBUG: packageFiles with updates
{
  "baseBranch": "main"
  "config": {
    "bundler": [
      {
        "deps": [
          ...
          {
            "currentValue": "v13",
            "currentVersion": "v13",
            "datasource": "git-refs",
            "depName": "rubocop-config",
            "fixedVersion": "v13",
            "managerData": {
              "lineNumber": 14
            },
            "packageName": "https://github.com/jgraichen/rubocop-config",
            "sourceUrl": "https://github.com/jgraichen/rubocop-config",
            "versioning": "ruby",
            "warnings": [],
            "updates": [
              {
                "bucket": "major",
                "newVersion": "v14",
                "newValue": "vv14",
                "newMajor": 14,
                "newMinor": null,
                "newPatch": null,
                "updateType": "major",
                "isRange": true,
                "branchName": "renovate/rubocop-config-14.x"
              }
            ],
            "isSingleVersion": false
          },
          ...
...
DEBUG: branches info extended
{
  "branchesInformation": [
    {
      "branchName": "renovate/rubocop-config-14.x",
      "prNo": 57,
      "prTitle": "chore(deps): update dependency rubocop-config to v14",
      "result": "pr-created",
      "upgrades": [
        {
          "datasource": "git-refs",
          "depName": "rubocop-config",
          "displayPending": "",
          "fixedVersion": "v13",
          "currentVersion": "v13",
          "currentValue": "v13",
          "newValue": "vv14",
          "newVersion": "v14",
          "packageFile": "Gemfile",
          "updateType": "major",
          "packageName": "https://github.com/jgraichen/rubocop-config"
        }
      ]
    }
  ]
}
```

</details>
</div>

Reproduction forked to https://github.com/renovate-reproductions/35231

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
Modified the if check in `getNewValue` funciton so it only adds a `v` to the new value being computed if:
a) `currrentValue` has `v` preifx
b) `newVersion` doesn't have `v` prefix

## Context
- Closes: https://github.com/renovatebot/renovate/issues/35494

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository https://github.com/Rahul-renovate-testing/35231

### CODE REVIEW

File: lib/modules/versioning/ruby/index.ts [hunk 1]
```diff
@@ -103,7 +103,10 @@ const getNewValue = ({
 }: NewValueConfig): string | null => {
   let newValue = null;
   if (isVersion(currentValue)) {
-    newValue = currentValue.startsWith('v') ? 'v' + newVersion : newVersion;
+    newValue =
+      currentValue.startsWith('v') && !newVersion.startsWith('v')
+        ? 'v' + newVersion
```
Comment (viceice) [inline lib/modules/versioning/ruby/index.ts:108]: use string template

**Review by viceice — COMMENTED** [review]
we should also check docker versioning, it can flipping the v prefix if both tags are available. can be tested with traefik image

**Comment by RahulGautamSingh** [comment]
> we should also check docker versioning, it can flipping the v prefix if both tags are available. can be tested with traefik image

Seems to be working fine https://github.com/Rahul-renovate-testing/v-prefix-docker/pull/1/files

**Comment by viceice** [comment]
> > we should also check docker versioning, it can flipping the v prefix if both tags are available. can be tested with traefik image
> 
> Seems to be working fine https://github.com/Rahul-renovate-testing/v-prefix-docker/pull/1/files

use the three part tags

**Comment by RahulGautamSingh** [comment]
> use the three part tags

https://github.com/Rahul-renovate-testing/v-prefix-docker/pull/3 if `v` prefix present it stays
https://github.com/Rahul-renovate-testing/v-prefix-docker/pull/4 if `v` prefix absent it is being added

**Review by viceice — APPROVED** [review]
