### PR TITLE
fix(cache): use `bitbucket-server` as platform cache key

### LINKED ISSUE #39895: cache: use `platform` as the cache keys
It was recently noticed that [we use a camelCase variant of the platform name in `RepoCacheData`](https://github.com/renovatebot/renovate/blob/db824b9c85d3d2ceb8ec06a226d8e50ed945a2ae/lib/util/cache/repository/types.ts#L159-L161) only for `bitbucketServer`.

`bitbucketServer` should be cased as `bitbucket-server` (https://github.com/renovatebot/renovate/blob/db824b9c85d3d2ceb8ec06a226d8e50ed945a2ae/lib/constants/platforms.ts#L1-L13) as that matches the platform name.

We should fix this, so it's a 1-1 mapping between a platform name and a cache key _or_ make sure that there's a way to pass a `platform` and receive the cache settings for that platform.

This can either be done as a breaking change (in the next major) or as a non-breaking change for now, and then made breaking in the future, for consistency.

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

Change the Bitbucket Server platform cache key from `bitbucketServer` (camelCase) to `bitbucket-server` (kebab-case) to match the platform ID in `PLATFORM_HOST_TYPES`.

Adds migration logic to automatically convert existing caches using the old key to the new format, ensuring a non-breaking upgrade path.

## Context

- [x] This closes an existing Issue, Closes: #39895

## AI assistance disclosure

- [x] Yes — substantive assistance (AI-generated non‑trivial portions of code, tests, or documentation).

Claude Code was used to implement the fix, write tests, and create this PR.

## Documentation (please check one with an [x])

- [x] No documentation update is required

## How I've tested my work (please select one)

- [x] Newly added/modified unit tests

### CODE REVIEW

File: lib/modules/platform/bitbucket-server/pr-cache.ts [hunk 1]
```diff
@@ -9,6 +9,20 @@ import { getQueryString } from '../../../util/url';
...
 
+/* v8 ignore next */
+function migrateBitbucketServerCache(platform: unknown): void {
+  if (!isPlainObject(platform)) {
+    return;
+  }
+
+  if (!isPlainObject(platform.bitbucketServer)) {
+    return;
+  }
```
Comment (RahulGautamSingh) [inline lib/modules/platform/bitbucket-server/pr-cache.ts:20]:
```suggestion
  if (!isPlainObject(platform?.bitbucketServer)) {
    return;
  }
```

works?

**Review by RahulGautamSingh — CHANGES_REQUESTED** [review]
Else, LGTM

**Review by RahulGautamSingh — COMMENTED** [review]
lint issue 😖

**Review by viceice — DISMISSED** [review]

**Review by viceice — APPROVED** [review]
