### PR TITLE
fix(rubygems): Ensure consistency between versions and metadata

### LINKED ISSUE #25448: Rubygems cache: check package cache first
### Describe the proposed change(s).

For the rubygems datasource, we should default to caching package results for 30 minutes instead of always checking/syncing the `/versions` endpoint first.

Practically speaking this means that if we run Renovate two times in a row on the same repo, we should not see any queries to rubygems.org

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

Ensure `/versions` endpoint data is always consistent with `/api/v1/gems` responses, otherwise fallback to results containing only `version` field.

This is important, because `/versions` could contain fresh data, while `/api/v1/gems` endpoint still may return older data for some short amount of time. If we cache the data at this moment, we're are risking to store inconsistent data for very long period of time.

To solve this, we hash list of versions from the `/versions` endpoint, and if it has changed, we invalidate the cache.

The key point of this PR: when persisting the cache for long term, we don't use previously calculated hash from the `/versions` endpoint, we calculate it based on the `/api/v1/versions` response (which we are about to cache). This should make both cache layers consistent.

## Context

- Closes: #25448

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/datasource/rubygems/metadata-cache.ts [hunk 1]
```diff
@@ -46,19 +66,36 @@ export class MetadataCache {
...
+          ): Promise<Result<ReleaseResult, CacheError>> => {
+            const newHash = hashReleases(newData);
+            if (newHash === hash) {
+              await saveCache(newHash, newData);
+              return Result.ok(newData);
+            }
+
+            if (err.type === 'cache-outdated') {
+              return Result.ok(err.staleData);
+            }
```
Comment (zharinov) [inline lib/modules/datasource/rubygems/metadata-cache.ts:85]: I'm afraid there could be a problem with this stale data we now return explicitly.

Alternative is to just return values with `version` values only, but in this case we potentially may experience "flickering" `releaseTimestamp`.

**Review by rarkins — CHANGES_REQUESTED** [review]
Please add a readme.md to this datasource folder describing how the caching works, particularly for rubygems.org. Either that or much more commented code inline

**Comment by zharinov** [comment]
Here is the state diagram I'm about to place in the doc.
It isn't as visually appealing as I want it to be, but at least we have diagram form for this complex logic, instead of just text description.

```mermaid
stateDiagram-v2
  [*] --> Empty

  state "Empty" as Empty
  Empty --> FullSync: getPkgReleases()

  state "Synced" as Synced
  Synced --> DeltaSync

  state "Unsupported" as Unsupported
  Unsupported --> [*]

  state "Full sync" as FullSync : GET /versions (~20Mb)
  state full_sync_result <<choice>>
  FullSync --> full_sync_result: Response
  full_sync_result --> Synced: (1) Status 200
  full_sync_result --> Unsupported: (2) Status 404
  full_sync_result --> Empty: (3) Status other than 200 or 404\n Clear cache and throw ExternalHostError

  state "Delta sync" as DeltaSync: GET /versions with "Range" header
  state delta_sync_result <<choice>>
  DeltaSync --> delta_sync_result: Successful response
  delta_sync_result --> Synced: (1) Status other than 206\nFull data is received, extract and replace old cache\n (as if it is the full sync)
  delta_sync_result --> FullSync: (2) The head of response doesn't match\n the tail of the previously fetched data
  delta_sync_result --> Synced: (3) The head of response matches\n the tail of the previously fetched data

  state delta_sync_error <<choice>>
  DeltaSync --> delta_sync_error: Error response
  delta_sync_error --> FullSync: (1) Status 416 should not happen\nbut moves to full sync
  delta_sync_error --> Unsupported: (2) Status 404
  delta_sync_error --> Empty: (3) Status other than 404 or 416
```

File: lib/modules/datasource/rubygems/metadata-cache.spec.ts [hunk 2]
```diff
@@ -8,17 +8,18 @@ jest.mock('../../../util/cache/package');
...
+  const packageCacheMock: Map<string, unknown> = new Map();
 
   beforeEach(() => {
-    cache.clear();
+    packageCacheMock.clear();
 
     packageCache.get.mockImplementation(
-      (ns, key) => Promise.resolve(cache.get(`${ns}::${key}`)) as never
+      (ns, key) =>
+        Promise.resolve(packageCacheMock.get(`${ns}::${key}`)) as never
```
Comment (viceice) [inline lib/modules/datasource/rubygems/metadata-cache.spec.ts:18]: do we really need the never cast?

File: lib/modules/datasource/rubygems/metadata-cache.spec.ts [hunk 3]
```diff
@@ -8,17 +8,18 @@ jest.mock('../../../util/cache/package');
...
     );
 
     packageCache.set.mockImplementation((ns, key, value) => {
-      cache.set(`${ns}::${key}`, value);
+      packageCacheMock.set(`${ns}::${key}`, value);
       return Promise.resolve() as never;
```
Comment (viceice) [inline lib/modules/datasource/rubygems/metadata-cache.spec.ts:23]: same question

File: lib/modules/datasource/rubygems/metadata-cache.ts [hunk 4]
```diff
@@ -21,44 +32,61 @@ export class MetadataCache {
...
-          : Result.err('cache-outdated' as const);
+          : Result.err('cache-outdated');
       });
 
-    const saveCache = async (data: ReleaseResult): Promise<ReleaseResult> => {
+    const saveCache = async (
+      hash: string,
+      data: ReleaseResult,
+      ttlMinutes = 100 * 24 * 60,
+      ttlDelta = 10 * 24 * 60
```
Comment (viceice) [inline lib/modules/datasource/rubygems/metadata-cache.ts:51]: why as parameter? those params are never passed anywhere, so they should be const.

File: lib/modules/datasource/rubygems/readme.md [hunk 5]
```diff
@@ -0,0 +1,57 @@
+# Rubygems datasource
+
+Datasource query order depends on the registry:
```
Comment (viceice) [inline lib/modules/datasource/rubygems/readme.md:3]:
```suggestion
Datasource query order depends on the registry.
```

File: lib/modules/datasource/rubygems/readme.md [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+
+## Querying `rubygems.org`
+
+Rubygems rate limit are easy to hit, so we need to be careful with the queries.
```
Comment (viceice) [inline lib/modules/datasource/rubygems/readme.md:7]:
```suggestion
Rubygems rate limits are easy to hit, so we need to be careful with the queries.
```

File: lib/modules/datasource/rubygems/readme.md [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+    delta_sync_result --> Synced: (3) The head of response matches\n the tail of the previously fetched data
+
+    state delta_sync_error <<choice>>
+    DeltaSync --> delta_sync_error: Error response
+    delta_sync_error --> FullSync: (1) Status 416 should not happen\nbut moves to full sync
+    delta_sync_error --> Unsupported: (2) Status 404
+    delta_sync_error --> Empty: (3) Status other than 404 or 416
+  ```
+
+- Then, more data is obtained from `https://rubygems.org/api/v1/versions/<package>.json` and `https://rubygems.org/api/v1/gems/<package>.json.json`
```
Comment (viceice) [inline lib/modules/datasource/rubygems/readme.md:45]:
```suggestion
- Then, more data is obtained from `https://rubygems.org/api/v1/versions/<package>.json` and `https://rubygems.org/api/v1/gems/<package>.json`
```
double extension?

File: lib/modules/datasource/rubygems/metadata-cache.spec.ts (hunk 2 above)
Comment (zharinov) [reply lib/modules/datasource/rubygems/metadata-cache.spec.ts:18]: Either we cast to never or declare value type as `any`

**Review by viceice — COMMENTED** [review]
still an open question

**Comment by rarkins** [comment]
@zharinov so how many cache layers do we have for rubygems.org? Eg how is the /versions cached? And do we cache per-version too? How is the data in /versions joined with the API data?

**Comment by zharinov** [comment]
@rarkins Answered you in the readme

File: lib/modules/datasource/rubygems/metadata-cache.ts [hunk 8]
```diff
@@ -21,44 +32,61 @@ export class MetadataCache {
...
-      .catch(() =>
-        Result.ok({
-          releases: versions.map((version) => ({ version })),
-        })
+      .catch((err) =>
+        getV1Releases(this.http, registryUrl, packageName).transform(
+          async (
+            newData: ReleaseResult
+          ): Promise<Result<ReleaseResult, CacheError>> => {
+            const v1ReleasesHash = hashReleases(newData);
```
Comment (zharinov) [inline lib/modules/datasource/rubygems/metadata-cache.ts:72]: The key point of this PR: we don't use previously calculated hash from the `/versions` endpoint, we calculate it based on the `/api/v1/versions` response. This should make both cache layers consistent.

File: lib/modules/datasource/rubygems/readme.md [hunk 9]
```diff
@@ -42,7 +47,9 @@ Rubygems rate limits are easy to hit, so we need to be careful with the queries.
     delta_sync_error --> Empty: (3) Status other than 404 or 416
   ```
 
-- Then, more data is obtained from `https://rubygems.org/api/v1/versions/<package>.json` and `https://rubygems.org/api/v1/gems/<package>.json`
+- Then, more data is obtained from `https://rubygems.org/api/v1/versions/<package>.json` and `https://rubygems.org/api/v1/gems/<package>.json`.
+
+  Cache key is formed from the `packageName` and `version[]` from the previous layer, so that we reach these endpoints only when the list of versions has changed.
```
Comment (rarkins) [inline lib/modules/datasource/rubygems/readme.md]: Do you handle if there's a version mismatch between the two? i.e. don't treat it as a "finished" cache and retry again after some time?

Comment (zharinov) [reply lib/modules/datasource/rubygems/readme.md]: When the hash of `/versions` data doesn't match the `/api/v1/versions/<pkg>` response data, we return the `/versions` data (without `releaseTimestamp` and other metadata). It means querying `/api/v1/versions/<pkg>` until the consistency between two is achieved.

Comment (rarkins) [reply lib/modules/datasource/rubygems/readme.md]: So it keeps querying indefinitely?

Comment (zharinov) [reply lib/modules/datasource/rubygems/readme.md]: Okay, we have two options here:
1. Create additional code that protect us from this unfortunate case (which itself can be a source of bugs)
2. Leave as-is and observe how many log messages for inconsistent cache we get

Comment (zharinov) [reply lib/modules/datasource/rubygems/readme.md]: The downsides for both options are:
1. In similar conditions, instead of querying `/api/v1/versions/<pkg>` indefinitely, instead we'll return stale data indefinitely (can be logged and observed, though)
2. Creating PRs based only on the `version` fields will piss our users off time to time, so they'll come to report a bug. Not cool.

Comment (rarkins) [reply lib/modules/datasource/rubygems/readme.md]: If the API becomes correct then we want to pick it up. So this probably means retrying, such as daily. Maybe we could record the date when we first found the missing version and try up to a week?

Comment (zharinov) [reply lib/modules/datasource/rubygems/readme.md]: I don't think it's about days or weeks, for me it seems more like about minutes of inconsistency. If if there is something other than that, it looks like something we actually need to report to [rubygems.org](rubygems.org). But yes, I think we need some protective mechanism against us being rate limited.

File: lib/modules/datasource/rubygems/metadata-cache.ts [hunk 10]
```diff
@@ -20,45 +40,74 @@ export class MetadataCache {
...
+                hash: v1ReleasesHash,
+                data: newData,
+                createdAt,
+              });
+              return Result.ok(newData);
+            }
+
+            if (err.type === 'cache-stale') {
+              const cache = err.cache;
+              await saveCache(cache, 0);
```
Comment (viceice) [inline lib/modules/datasource/rubygems/metadata-cache.ts:95]: why do we cache stale data again? 🤔

File: lib/modules/datasource/rubygems/readme.md (hunk 9 above)
Comment (zharinov) [reply lib/modules/datasource/rubygems/readme.md]: Just implemented mechanism of marking the cache as fallback and setting 1 more hour of TTL for it

**Comment by rarkins** [comment]
When I run this locally, it appears to do a full `/versions` sync/download every run. i.e. if I run it against one repo over and over, it's downloading the full `/versions` every time without any caching. Is that both the current as well as new behavior, or did it change?

**Comment by zharinov** [comment]
Data from `/versions` always has been stored in-memory

**Comment by rarkins** [comment]
Is there any "hot" cache per package? e.g. if I have a repo with one ruby dependency, and I run on that repo two times in a row, I wouldn't expect to see any datasource lookups at all - just the package cache.

**Comment by zharinov** [comment]
It should query `/versions` endpoint 1 time and package-related endpoint 1 time, if two runs are in the same node process

**Comment by rarkins** [comment]
But why do we query `/versions` at all if we have a <1 minute "hot" cache of the exact dependency we are looking up?

**Comment by rarkins** [comment]
Remember that the hosted app does one repo per run so will never have `/versions` cached between jobs, meaning it downloads the entire `/versions` unnecessarily many times. It would be better if we consult the package cache for each package we look up and return that result without downloading or syncing `/versions`. But should it be a separate issue/PR?

**Comment by zharinov** [comment]
Just to clarify, Rubygems in-memory data is stored at the module level, so it isn't being reset between repo runs, like memory cache from `util` folder does. I.e. it exists during Node process run.

**Comment by rarkins** [comment]
I understand, but in the hosted app we have one run per job, so that doesn't help

**Comment by rarkins** [comment]
I'll create a new issue for this part then

File: lib/modules/datasource/rubygems/index.ts [hunk 11]
```diff
@@ -46,6 +47,16 @@ export class RubyGemsDatasource extends Datasource {
...
+  @cache({
+    namespace: `datasource-${RubyGemsDatasource.id}`,
+    key: ({ packageName, registryUrl }: GetReleasesConfig) =>
+      // TODO: types (#22198)
+      `releases:${registryUrl!}:${packageName}`,
+    cacheable: ({ registryUrl }: GetReleasesConfig) => {
+      const registryHostname = parseUrl(registryUrl)?.hostname;
+      return registryHostname === 'rubygems.org';
+    },
+  })
```
Comment (rarkins) [inline lib/modules/datasource/rubygems/index.ts:59]: Is it possible to cache only rubygems.org? So we don't cache private

**Review by rarkins — APPROVED** [review]
