### PR TITLE
fix(manager/gomod): add multi-line replace detection

### LINKED ISSUE #14504: Cannot update versions in multi-line `replace` block in go.mod
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.81.3, also 32.26.2

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

ubuntu-latest

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

renovate does not update versions in a multi-line `replace` block in a go.mod file. It only works for the single line replace.

I created an example repo [here](https://github.com/avorima/renovate-gomod-example).

Not updated: https://github.com/avorima/renovate-gomod-example/runs/5413565230?check_suite_focus=true

```
replace (
	k8s.io/client-go => k8s.io/client-go v0.21.9
	sigs.k8s.io/controller-runtime => sigs.k8s.io/controller-runtime v0.9.7
)
```

Updated: https://github.com/avorima/renovate-gomod-example/runs/5413625323?check_suite_focus=true

```
replace k8s.io/client-go => k8s.io/client-go v0.21.9

replace sigs.k8s.io/controller-runtime => sigs.k8s.io/controller-runtime v0.9.7
```

### Relevant debug logs

_No response_

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by hasanwhitesource**
## Changes

Added detection of deps under a multi-line replace directive.

## Context

Closes #14504 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
🤷‍♂️ I'm not a go user, so hope it works

File: lib/modules/manager/gomod/update.ts [hunk 1]
```diff
@@ -46,9 +46,15 @@ export function updateDependency({
...
-      updateLineExp = regEx(
-        /^(?<depPart>replace\s+[^\s]+[\s]+[=][>]+\s+)(?<divider>[^\s]+\s+)[^\s]+/
-      );
+      if (upgrade.managerData.multiLine) {
+        updateLineExp = regEx(
+          /^(?<depPart>\s+[^\s]+[\s]+[=][>]+\s+)(?<divider>[^\s]+\s+)[^\s]+/
+        );
+      } else {
+        updateLineExp = regEx(
+          /^(?<depPart>replace\s+[^\s]+[\s]+[=][>]+\s+)(?<divider>[^\s]+\s+)[^\s]+/
```
Comment (viceice) [inline lib/modules/manager/gomod/update.ts:55]:
```suggestion
          /^(?<depPart>replace\s+[^\s]+[\s]+=>+\s+)(?<divider>[^\s]+\s+)[^\s]+/
```
isn't this the same regex?
- are you sure `>` can occur multiple times?

Comment (hasanwhitesource) [reply lib/modules/manager/gomod/update.ts:55]: No just once. This regex is based on the original
