### PR TITLE
fix(versioning/pep440): log debug message if `newVersion` is excluded from range

### LINKED ISSUE #25501: pep440: failed to calculate newValue
### Discussed in https://github.com/renovatebot/renovate/discussions/25495

<div type='discussions-op-text'>

<sup>Originally posted by **nijel** October 30, 2023</sup>
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

When the current package version from PyPI is restricted in the dependencies, a warning appears: `pep440: failed to calculate newValue`.

It is also shown as an error in the Rennovate app:

obrazek

Presently, this can be reproduced with the following `requirements.txt`: 

```requirements-txt
sentry-sdk>=1.25.0,<2,!=1.32.0
```

I understand that there is no update possible, but the warning makes it quite hard to see what is going on.

EDIT: Reproducer repo is at https://github.com/nijel/renovate-25495

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: pep440: failed to calculate newValue
{
  "result": ">=1.25.0,<2,!=1.32.0"
  "newVersion": "1.32.0"
  "currentValue": ">=1.25.0,<2,!=1.32.0"
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above</div>

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
Add an if-statement to check if the `newVersion` is excluded from range, so that we can return early and also log a more informational debug message instead of the less useful warning we displaly currently.

## Context
Closes: https://github.com/renovatebot/renovate/issues/25501

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

**Review by rarkins — APPROVED** [review]

File: lib/modules/versioning/pep440/range.ts [hunk 1]
```diff
@@ -191,6 +203,7 @@ export function getNewValue({
     newVersion,
   );
 
+  // istanbul ignore if
```
Comment (viceice) [inline lib/modules/versioning/pep440/range.ts:206]: we should add a test instead
