### PR TITLE
fix(docker): ensure digest is updated only once with ARG and multiple FROM statements

### LINKED ISSUE #18022: Duplicated Dependency inside Dockerfile using ARG as image tag.
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.204.5

### If you're self-hosting Renovate, select which platform you are using.

Gitlab  self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

CE 15.3.3

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When using a Dockerfile with image in `FROM` including variable like this one:
```
ARG PYTHON_VERS=3.10-slim

FROM python:${PYTHON_VERS} AS builder

...

FROM python:${PYTHON_VERS}

...
```
an when `pinDigest` is activated, the resulting dependencies (see Logs) are applying twice the addition of the hash, as 2 deps are detected with the 2 FROMs, resulting in this updated Dockerfile:

```
ARG PYTHON_VERS=3.10-slim@sha256:6de22c9cf887098265b7614582b00641c0c8c6735af538d0f267d6bb457634f1@sha256:6de22c9cf887098265b7614582b00641c0c8c6735af538d0f267d6bb457634f1

FROM python:${PYTHON_VERS} AS builder

...

FROM python:${PYTHON_VERS}
```

As I explored a little bit the code, I'd say that a deduplication step of deps before the loop at `lib/modules/manager/dockerfile/extract.ts` at line 392 can make the job , or the extractor need to store which dependencies (one's detected by the FROM) are associated to the variable, in order to disable their changes when there is more than one deps associated to this variable

If there is a version update is available (3.10.1-slim to 3.10.7 with the addition of the hash), the bug doesn't occur.

here is the reproduction
https://github.com/Lowaiz/renovate-bug

### Relevant debug logs

<details><summary>Logs</summary>

```
"deps": [
               {
                 "depName": "python",
                 "currentValue": "3.10-slim",
                 "replaceString": "ARG PYTHON_VERS=3.10-slim",
                 "autoReplaceStringTemplate": "ARG PYTHON_VERS={{#if newValue}}{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "stage",
                 "depIndex": 0,
                 "updates": [
                   {
                     "isPinDigest": true,
                     "updateType": "pinDigest",
                     "newValue": "3.10-slim",
                     "newDigest": "sha256:6de22c9cf887098265b7614582b00641c0c8c6735af538d0f267d6bb457634f1",
                     "branchName": "renovate/pindigest-deps-update"
                   }
                 ],
                 "warnings": [],
                 "versioning": "docker",
                 "currentVersion": "3.10",
                 "fixedVersion": "3.10-slim"
               },
               {
                 "depName": "python",
                 "currentValue": "3.10-slim",
                 "replaceString": "ARG PYTHON_VERS=3.10-slim",
                 "autoReplaceStringTemplate": "ARG PYTHON_VERS={{#if newValue}}{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "final",
                 "depIndex": 1,
                 "updates": [
                   {
                     "isPinDigest": true,
                     "updateType": "pinDigest",
                     "newValue": "3.10-slim",
                     "newDigest": "sha256:6de22c9cf887098265b7614582b00641c0c8c6735af538d0f267d6bb457634f1",
                     "branchName": "renovate/pindigest-deps-update"
                   }
                 ],
                 "warnings": [],
                 "versioning": "docker",
                 "currentVersion": "3.10",
                 "fixedVersion": "3.10-slim"
               }
             ]
           }
         ]
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by Churro**
## Changes

Adds a linefeed to `replaceString` and `autoReplaceStringTemplate` if value is in ARG that is potentially used with multiple FROM statements, see https://github.com/renovatebot/renovate/issues/18022#issuecomment-1263098633.

## Context

Closes https://github.com/renovatebot/renovate/issues/18022

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

Test repository: https://github.com/renovate-demo/18022-dockerfile-duplicate/pull/1

### CODE REVIEW

File: lib/modules/manager/dockerfile/extract.ts [hunk 1]
```diff
@@ -88,6 +88,7 @@ function processDepForAutoReplace(
   dep.replaceString = unfoldedLineNumbers
     .map((lineNumber) => lines[lineNumber])
     .join(linefeed);
+  dep.replaceString += linefeed;
```
Comment (viceice) [inline lib/modules/manager/dockerfile/extract.ts:91]: it can be any `\s` so we need to also support a space

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/modules/manager/dockerfile/extract.ts (hunk 1 above)
Comment (Churro) [reply lib/modules/manager/dockerfile/extract.ts:91]: `lines[lineNumber]` contains the entire, untrimmed line, potentially with trailing spaces. That's why only \r?\n is added here.

Comment (rarkins) [inline lib/modules/manager/dockerfile/extract.ts:91]: Won't this break if the line somehow had a character before the line feed, such as whitespace? e.g. could the line be `ARG abc=1.0.0 `? Therefore I'd append the "next" character in the line and if none *then* newline. What do you think?

Comment (viceice) [reply lib/modules/manager/dockerfile/extract.ts:91]: i think it works as expected now.

@Churro please add or change a test to validate trailing content.

**Comment by Churro** [comment]
While drafting a testcase for this, I found that the given example `ARG abc=1.0.0 ` is not matched the way you would expect it to be. This PR doesn't change this but before merging it, I'd feel more comfortable to refine ARG handling (+ tests) and then come back to this with more confidence that adding a linefeed is a general solution and not only resolving https://github.com/renovatebot/renovate/issues/18022.

**Comment by Churro** [comment]
Also after some more thoughts on this, I think that adding a linefeed is a viable solution:
- It affects only Docker `pinDigest` PRs, i.e., those where there is no value to replace but append.
  - This means, there is no need to add a linefeed if `currentDigest` already exists (https://github.com/renovatebot/renovate/pull/18061/commits/50d2fa933060046158efa5b6f4a3ee68579bfcd0)
- The linefeed is only added if the string to replace consists of multiple lines. This is only the case for Dockerfiles with FROM statements referencing ARG values. Otherwise, `processDepForAutoreplace` returns earlier anyway: https://github.com/renovatebot/renovate/blob/07460542850cc79e934a8d4606371c88776e4c0c/lib/modules/manager/dockerfile/extract.ts#L76-L80

In other words, a linefeed is only added now if there is no digest yet and ARG values are used in FROM statements.

Applied on https://github.com/renovate-demo/18022-dockerfile-duplicate/pull/1 this results in the following, desired output:
```
DEBUG: Starting search at index 0 (repository=renovate-demo/18022-dockerfile-duplicate, packageFile=Dockerfile, branch=renovate/pindigest-deps-update)
       "depName": "python"
DEBUG: Found match at index 0 (repository=renovate-demo/18022-dockerfile-duplicate, packageFile=Dockerfile, branch=renovate/pindigest-deps-update)
       "depName": "python"
DEBUG: Found a multistage build stage name: builder (repository=renovate-demo/18022-dockerfile-duplicate, branch=renovate/pindigest-deps-update)
DEBUG: Contents updated (repository=renovate-demo/18022-dockerfile-duplicate, packageFile=Dockerfile, branch=renovate/pindigest-deps-update)
       "depName": "python"
 INFO: Cannot find replaceString in current file content. Was it already updated? (repository=renovate-demo/18022-dockerfile-duplicate, packageFile=Dockerfile, branch=renovate/pindigest-deps-update)
       "depName": "python",
       "existingContent": "ARG PYTHON_VERS=3.11-slim@sha256:f8cc89f5e47347703ec0c2b755464d7db2fa16f255ab860c4b24ba6ef2402020\n\nFROM python:${PYTHON_VERS} AS builder\n\nRUN echo \"test\"\n\nFROM python:${PYTHON_VERS}\n\nRUN echo \"final\"\n",
       "replaceString": "ARG PYTHON_VERS=3.11-slim\n"
DEBUG: No content changed (repository=renovate-demo/18022-dockerfile-duplicate, packageFile=Dockerfile, branch=renovate/pindigest-deps-update)
       "depName": "python"
DEBUG: Updated 1 package files (repository=renovate-demo/18022-dockerfile-duplicate, branch=renovate/pindigest-deps-update)
```

File: lib/modules/manager/dockerfile/extract.ts (hunk 1 above)
Comment (Churro) [reply lib/modules/manager/dockerfile/extract.ts]: Thank you for bringing up the `ARG abc=1.0.0 ` case. It revealed a deficiency that was addressed in PR https://github.com/renovatebot/renovate/pull/18592.

Adding a linefeed here is a "general" solution in the sense that a linefeed is always the next character to come. This is because `dep.replaceString` in line 88 comprises the entire line, incl potentially trailing spaces. 

There is a test now that exemplifies how this works with trailing spaces:
https://github.com/renovatebot/renovate/blob/056ff8c0fc61492ca538ca6ef938847fa7ea8854/lib/modules/manager/dockerfile/extract.spec.ts#L764-L782

**Comment by rarkins** [comment]
Doesn't this conflict with the sutoreplace template?

I'd like to test this out extensively just in case

**Comment by Churro** [comment]
No issues I'd be aware of, currently. 

In case container image parts are split across multiple lines, e.g. digest in ARG, image name in FROM, the auto replace template gets composed manually here. Adding a linefeed to `dep.replaceString` is done before `getAutoReplaceTemplate(dep)` is called, so they are kept in-sync:
https://github.com/renovatebot/renovate/blob/8414f44e42615feba0cc537ef12efb02f39c283d/lib/modules/manager/dockerfile/extract.ts#L92-L96

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
