### PR TITLE
fix!: prevent grouping of replacement updates

### LINKED ISSUE #39273: Use distinct branch prefix for replacement PRs
### Describe the proposed change(s).

As noted in https://github.com/renovatebot/renovate/discussions/38979, we're seeing `Error updating branch` errors when Renovate tries to update a `pom.xml`.

This happens when there are (at least 2) updates applied to the same branch, at least one of which is a replacement:

- `updateType=replacement` 
- `updateType=patch`

<details>

<summary><code>packageFiles with updates</code></summary>

```
DEBUG: packageFiles with updates
{
  "baseBranch": "main"
  "config": {
    "maven": [
      {
        "datasource": "maven",
        "deps": [
          {
            "currentValue": "8.0.28",
            "currentVersion": "8.0.28",
            "currentVersionAgeInDays": 1418,
            "currentVersionTimestamp": "2021-12-16T00:25:41.000Z",
            "datasource": "maven",
            "depName": "mysql:mysql-connector-java",
            "depType": "compile",
            "deprecationMessage": "MySQL Connector/J artifacts moved to reverse-DNS compliant Maven 2+ coordinates.",
            "fileReplacePosition": 853,
            "fixedVersion": "8.0.28",
            "isSingleVersion": true,
            "packageName": "mysql:mysql-connector-java",
            "packageScope": "mysql",
            "registryUrl": "https://repo.maven.apache.org/maven2",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2"
            ],
            "respectLatest": false,
            "versioning": "maven",
            "warnings": [],
            "updates": [
              {
                "bucket": "latest",
                "newVersion": "8.0.33",
                "newValue": "8.0.33",
                "releaseTimestamp": "2023-03-07T16:15:54.000Z",
                "newVersionAgeInDays": 971,
                "newMajor": 8,
                "newMinor": 0,
                "newPatch": 33,
                "updateType": "patch",
                "isBreaking": false,
                "libYears": 1.2237256785895485,
                "branchName": "renovate/all-dependencies"
              },
              {
                "updateType": "replacement",
                "newName": "com.mysql:mysql-connector-j",
                "newValue": "8.0.33",
                "branchName": "renovate/all-dependencies"
              }
            ]
          }
        ],
        "packageFile": "pom.xml",
        "packageFileVersion": "1.0.0"
      }
    ]
  }
}
```

</details>

This appears to be because:

- Renovate parses the package file (`packageFiles with updates`) (and determines that the package version is at character 853)
- Renovate performs the replacement (which modifies the file's contents
- Renovate attempts to perform the `patch` bump, but that fails

We can see this with:

```
// original content
      const fileContent =
        '<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">\n\n    <modelVersion>4.0.0</modelVersion>\n\n    <groupId>com.test</groupId>\n    <artifactId>test</artifactId>\n    <version>1.0.0</version>\n    <packaging>pom</packaging>\n\n    <properties>\n        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n        <java.version>21</java.version>\n        <maven.compiler.source>21</maven.compiler.source>\n        <maven.compiler.target>21</maven.compiler.target>\n    </properties>\n\n    <dependencyManagement>\n        <dependencies>\n            <dependency>\n                <groupId>mysql</groupId>\n                <artifactId>mysql-connector-java</artifactId>\n                <version>8.0.28</version>\n            </dependency>\n</dependencies>\n    </dependencyManagement>\n         \n</project>\n';

// then, when it fails to evaluate:
DEBUG: Error updating file (branch="renovate/all-dependencies")
...
  "existingContent": "<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">\n\n    <modelVersion>4.0.0</modelVersion>\n\n    <groupId>com.test</groupId>\n    <artifactId>test</artifactId>\n    <version>1.0.0</version>\n    <packaging>pom</packaging>\n\n    <properties>\n        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n        <java.version>21</java.version>\n        <maven.compiler.source>21</maven.compiler.source>\n        <maven.compiler.target>21</maven.compiler.target>\n    </properties>\n\n    <dependencyManagement>\n        <dependencies>\n            <dependency>\n                <groupId>com.mysql</groupId>\n                <artifactId>mysql-connector-j</artifactId>\n                <version>8.0.33</version>\n            </dependency>\n        </dependencies>\n    </dependencyManagement>\n         \n</project>\n"
```

Notice that the `existingContent` includes the replacement applied.

When we index into this for character 853, we see `>`, as we're now using one character fewer than when we first extracted the package.

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- For replacement updates ignore the `group` settings

## Context

Please select one of the following:

- [x] This closes an existing Issue, Closes: #39273
- [ ] This doesn't close an Issue, but I accept the risk that this PR may be closed if maintainers disagree with its opening or implementation

## AI assistance disclosure

Did you use AI tools to create any part of this pull request?

Please select one option and, if yes, briefly describe how AI was used (e.g., code, tests, docs) and which tool(s) you used.

- [x] No — I did not use AI for this contribution.
- [ ] Yes — minimal assistance (e.g., IDE autocomplete, small code completions, grammar fixes).
- [ ] Yes — substantive assistance (AI-generated non‑trivial portions of code, tests, or documentation).
- [ ] Yes — other (please describe):

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests, but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

The public repository: https://github.com/Rahul-renovate-testing/distinct-replacements/pulls

For Before, check this PR: https://github.com/Rahul-renovate-testing/distinct-replacements/pull/1
For After, check this PR: https://github.com/Rahul-renovate-testing/distinct-replacements/pull/2 (this was only created after excluding replacement PRs from grouping)

### CODE REVIEW

**Review by jamietanna — COMMENTED** [review]
LGTM - I'm wondering if there's anywhere else we can add this in to ensure tests cover this 🤔 

Also, maybe we should add a debug / trace log to indicate that it's being skipped?

File: lib/workers/repository/updates/branch-name.ts [hunk 1]
```diff
@@ -63,7 +63,8 @@ export function generateBranchName(update: BranchUpgradeConfig): void {
     );
     update.groupName = update.sharedVariableName;
   }
-  if (update.groupName) {
+
+  if (update.groupName && update.updateType !== 'replacement') {
```
Comment (viceice) [inline lib/workers/repository/updates/branch-name.ts]: it should als `lockFileMaintenance` 
```suggestion
  if (update.groupName && !['lockFileMaintenance', 'replacement'].includes(update.updateType)) {
```

Comment (RahulGautamSingh) [reply lib/workers/repository/updates/branch-name.ts]: Lets keep this one for replacements. I haven't tested how it will affect lockfile updates yet.

**Review by viceice — APPROVED** [review]

**Review by jamietanna — APPROVED** [review]
