### PR TITLE
fix(changelog): use sourceDirectory for monorepo changelogs

### LINKED ISSUE #2926: Improve changelog detection for monorepos
The original data model for changelog was to assume a 1:1 mapping between package and source repository.

For monorepos, there are multiple challenges:
- Nested `changelog.md` files (#2162)
- GitHub releases are sometimes done using raw version (e.g. `v6.0.0`) and sometimes with name+version, e.g. `package-name@v6.0.1`

So our challenge is:
1. Find the right GitHub Release or changelog file for the package
2. De-duplicate them in PR bodies

Also related: what to do if a changelog.md file is updated (e.g. improved) in `master` branch well after publication of the package? Most of the time we'd want to update the PRs with that new info, but perhaps not always.

- If it is a github repo and then look for a "Release" named package@v1.0.0, package@1.0.0, v1.0.0 and 1.0.0
- If there is a changelog file in the root of the repo, use it
- If there is a file like ........./package/changelog.md, then use it (i.e. changelog nested)

Then the challenge is how to de-duplicate it within the PR body. If each package has identical from/to versions and identical content, then we should just display it once. But what if it's a mix of shared and non-shared?

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Uses sourceDirectory to locate nested `CHANGELOG` files within monorepos.

## Context:

Closes #2926

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Additional context: https://github.com/renovatebot/renovate/issues/4724#issuecomment-862681819

File: lib/workers/pr/changelog/github/index.ts [hunk 1]
```diff
@@ -52,18 +54,30 @@ export async function getReleaseNotesMd(
 
   // https://docs.github.com/en/rest/reference/git#get-a-tree
   const res = await http.getJson<GithubGitTree>(
-    `${apiPrefix}/git/trees/${defaultBranch}`
+    `${apiPrefix}/git/trees/${defaultBranch}${
+      sourceDirectory ? '?recursive=1' : ''
```
Comment (viceice) [inline lib/workers/pr/changelog/github/index.ts:58]: If there are too many. Files in repower don't find what we like. Isn't it better to search in root first and fallback to source directory? So we would have one additional query?

Maybe we can cache the found file path per dep?

**Review by viceice — COMMENTED** [review]
Otherwise LGTM

File: lib/workers/pr/changelog/github/index.ts (hunk 1 above)
Comment (rarkins) [reply lib/workers/pr/changelog/github/index.ts:58]: We only search recursively if there's been a sourceDirectory configured, which is not that common and unlikely to be incorrect (because not even most monorepo authors know to use it). And the recursive query is actually a single API call - it's not like GitHub's usual. I think this is reasonably efficient for now

Comment (rarkins) [reply lib/workers/pr/changelog/github/index.ts:58]: If/when we support fetching and parsing arbitrary changelogUrls (today we just link to them) then we could also consider improvements here too.
