### PR TITLE
fix(git-refs): gracefully ignore git-refs auth error

### LINKED ISSUE #16616: Ignore git-refs auth error
### What would you like Renovate to be able to do?

Ignore auth errors from git-refs instead of logging an error.

Example log:

```
{
  "hostname": "ip-172-31-15-102",
  "level": 50,
  "logContext": 739455062,
  "currentDigest": "84464994799c499e8f2c447f15acb8dcfc3439f1",
  "currentValue": "master",
  "datasource": "git-refs",
  "depName": "components",
  "followTag": null,
  "packageFile": ".gitmodules",
  "pinDigests": false,
  "rollbackPrs": false,
  "updatePinnedDependencies": true,
  "unconstrainedValue": false,
  "err": {
    "task": {
      "commands": [
        "ls-remote",
        "https://**redacted**@github.com/other/repo.git"
      ],
      "format": "utf-8",
      "parser": "[function]"
    },
    "message": "fatal: could not read Password for 'https://**redacted**@github.com': No such device or address\n",
    "stack": "Error: fatal: could not read Password for 'https://**redacted**@github.com': No such device or address\n\n at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1194:25)\n at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1229:29)\n at /home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1590:43\n at new Promise (<anonymous>)\n at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1588:16)\n at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1572:44)\n at Generator.next (<anonymous>)\n at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:55:24)"
  },
  "msg": "lookupUpdates error",
  "time": "2022-07-16T12:11:43.443Z"
}
```

### If you have any ideas on how this should be implemented, please tell us here.

I think we should catch and ignore any `fatal: could not read Password for` error from `git-refs`. It's OK to treat it like any normal package lookup error

### Is this a feature you are interested in implementing yourself?

No

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Catches git-refs auth errors gracefully.

## Context

Closes #16616

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/datasource/git-refs/index.ts [hunk 1]
```diff
@@ -44,7 +51,7 @@ export class GitRefsDatasource extends GitDatasource {
       releases: uniqueRefs.map((ref) => ({
         version: ref,
         gitRef: ref,
-        newDigest: rawRefs.find((rawRef) => rawRef.value === ref)?.hash,
+        newDigest: rawRefs!.find((rawRef) => rawRef.value === ref)?.hash,
```
Comment (viceice) [inline lib/modules/datasource/git-refs/index.ts:54]: not required, as there is a null check before

Comment (rarkins) [reply lib/modules/datasource/git-refs/index.ts:54]: Unfortunately it failed the tests without it. I decided it was more elegant to add the ! than any other fix
