### PR TITLE
fix(config): changed digest commit message topic

### LINKED ISSUE #14471: PR title/commit message for update docker image digest is something wrong
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

It seems the notation was shaken by "Docker digest" or "docker digest".
And now it is "commit hash", it is not correct(docker image digest is not commit hash).
Additionally, it cause the lack of docker image tag information.

- "Docker digest"(2022/02/05): https://github.com/yr32infra/discord-tts/pull/10
- "docker digest"(2022/02/06): https://github.com/sksat/mc.yohane.su/pull/237
- "docker digest"(2022/02/12): https://github.com/sksat/mc.yohane.su/pull/242
- "commit hash"(2022/02/15~now) https://github.com/sksat/mc.yohane.su/pull/243

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Setting current branch to main(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Initializing git repository into /mnt/renovate/gh/sksat/mc.yohane.su(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Performing blobless clone(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: git clone completed(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "durationMs": 911
}
DEBUG: latest repository commit(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "latestCommit": {
    "hash": "2bd3cc1672386bbf69ddbb66b0473b3def846466",
    "date": "2022-02-25T08:28:09+00:00",
    "message": "chore(deps): update reviewdog/action-actionlint action to v1.20.0",
    "refs": "HEAD -> main, origin/main, origin/HEAD",
    "body": "",
    "author_name": "Renovate Bot",
    "author_email": "bot@renovateapp.com"
  }
}
DEBUG: latest commit(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "branchName": "main",
  "latestCommitDate": "2022-02-25T08:28:09+00:00"
}
DEBUG: branchExists=true(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: PR rebase requested=true(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Checking if PR has been edited(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Branch has not been modified(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "branchName": "renovate/ghcr.io-sksat-papermc-docker-digest"
}
DEBUG: Found existing branch PR(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Checking schedule(at any time, null)(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: No schedule defined(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Manual rebase requested via Dependency Dashboard(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Using reuseExistingBranch: false(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Starting search at index 46(packageFile="docker-compose.yml", branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "depName": "ghcr.io/sksat/papermc-docker"
}
DEBUG: Found match at index 46(packageFile="docker-compose.yml", branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "depName": "ghcr.io/sksat/papermc-docker"
}
DEBUG: docker-compose.extractPackageFile()(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Contents updated(packageFile="docker-compose.yml", branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "depName": "ghcr.io/sksat/papermc-docker"
}
DEBUG: Updated 1 package files(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: No updated lock files in branch(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: isBranchConflicted(main, renovate/ghcr.io-sksat-papermc-docker-digest)(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Setting git author name(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: Using cached result false for isBranchConflicted(main, renovate/ghcr.io-sksat-papermc-docker-digest)(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: 1 file(s) to commit(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Preparing files for committing to branch renovate/ghcr.io-sksat-papermc-docker-digest(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: git commit(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/ghcr.io-sksat-papermc-docker-digest",
    "commit": "0c00e3c",
    "root": false,
    "summary": {
      "changes": 1,
      "insertions": 1,
      "deletions": 0
    }
  }
}
DEBUG: Pushing branch renovate/ghcr.io-sksat-papermc-docker-digest(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: git push(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "result": {
    "pushed": [],
    "branch": {
      "local": "renovate/ghcr.io-sksat-papermc-docker-digest",
      "remote": "renovate/ghcr.io-sksat-papermc-docker-digest",
      "remoteName": "origin"
    },
    "ref": {
      "local": "refs/remotes/origin/renovate/ghcr.io-sksat-papermc-docker-digest"
    },
    "remoteMessages": {
      "all": []
    }
  }
}
DEBUG: Fetching branch renovate/ghcr.io-sksat-papermc-docker-digest(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
INFO: Branch updated(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "commitSha": "0c00e3cbfc5d0f3706ad2d7a1cae97e6b2bbf015"
}
DEBUG: Checking if we can automerge branch(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: mergeStatus=no automerge(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Ensuring PR(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Found existing PR(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: Processing existing PR(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: updatePr(250, chore(deps): update ghcr.io/sksat/papermc-docker commit hash to 76c019e, body)(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
DEBUG: PR updated(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "pr": 250
}
INFO: PR updated(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
{
  "pr": 250,
  "prTitle": "chore(deps): update ghcr.io/sksat/papermc-docker commit hash to 76c019e"
}
DEBUG: PR is not configured for automerge(branch="renovate/ghcr.io-sksat-papermc-docker-digest")
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by hasanwhitesource**
## Changes

Changes the content of the digest commit topic.

## Context

Closes #14471 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/config/options/index.ts [hunk 1]
```diff
@@ -1242,7 +1242,7 @@ const options: RenovateOptions[] = [
     default: {
       branchTopic: '{{{depNameSanitized}}}-digest',
       commitMessageExtra: 'to {{newDigestShort}}',
-      commitMessageTopic: '{{{depName}}} commit hash',
+      commitMessageTopic: '{{{depName}}} commit digest',
```
Comment (sksat) [inline lib/config/options/index.ts:1245]: Doesn't seem to give a good flow. What is "commit digest"?
I think the words "commit hash" and "docker (image) digest" exist, but not "commit digest".

**Review by sksat — CHANGES_REQUESTED** [review]
