### PR TITLE
fix(gitlabci): Update local include files

### LINKED ISSUE #6713: gitlab-ci include:local not working
**What Renovate type are you using?**

I'm using `renovate/renovate:21.25.0` with Gitlab CI.

**Describe the bug**

Gitlab CI `include:local` is still not working. I tried to add support with the following pr and now Renovate recognizes the dependencies but is unable to update: https://github.com/renovatebot/renovate/pull/6630

**Relevant debug logs**

```
[...]
DEBUG: latest commit (repository=jonmi/gitlab-include-demo)
        "branchName": "master",
        "latestCommitDate": "2020-07-08 20:00:35 +0000"
 DEBUG: getLabels(https://index.docker.io, library/node, latest) (repository=jonmi/gitlab-include-demo)
 DEBUG: getManifestResponse(https://index.docker.io, library/node, latest) (repository=jonmi/gitlab-include-demo)
 DEBUG: Package releases lookups complete (repository=jonmi/gitlab-include-demo)
        "baseBranch": "master"
 DEBUG: packageFiles with updates (repository=jonmi/gitlab-include-demo)
        "config": {
          "gitlabci": [
            {
              "packageFile": ".gitlab-ci.yml",
              "manager": "gitlabci",
              "deps": [
                {
                  "depName": "alpine",
                  "replaceString": "alpine",
                  "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                  "datasource": "docker",
                  "depType": "image",
                  "depIndex": 0,
                  "updates": [],
                  "warnings": [],
                  "skipReason": "unsupported-value"
                }
              ]
            }
          ],
          "gitlabci-include": [
            {
              "packageFile": ".gitlab-ci.yml",
              "manager": "gitlabci-include",
              "deps": [
                {
                  "depName": "node",
                  "currentValue": "12.18.2-alpine",
                  "replaceString": "node:12.18.2-alpine",
                  "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                  "datasource": "docker",
                  "commitMessageTopic": "Node.js",
                  "depType": "image",
                  "depIndex": 0,
                  "updates": [
                    {
                      "fromVersion": "12.18.2-alpine",
                      "toVersion": "12.18.2",
                      "newValue": "12.18.2",
                      "newMajor": 12,
                      "newMinor": 18,
                      "updateType": "minor",
                      "isSingleVersion": true
                    },
                    {
                      "fromVersion": "12.18.2-alpine",
                      "toVersion": "14.5.0",
                      "newValue": "14.5.0",
                      "newMajor": 14,
                      "newMinor": 5,
                      "updateType": "major",
                      "isSingleVersion": true
                    }
                  ],
                  "warnings": [],
                  "sourceUrl": "https://github.com/nodejs/node",
                  "dockerRegistry": "https://index.docker.io",
                  "dockerRepository": "library/node"
                }
              ]
            }
          ]
        }
 DEBUG: branchifyUpgrades (repository=jonmi/gitlab-include-demo)
 DEBUG: 1 flattened updates found: node (repository=jonmi/gitlab-include-demo)
 DEBUG: Returning 1 branch(es) (repository=jonmi/gitlab-include-demo)
  WARN: No github.com token has been configured. Skipping release notes retrieval (repository=jonmi/gitlab-include-demo)
        "manager": "gitlabci-include",
        "depName": "node",
        "sourceUrl": "https://github.com/nodejs/node"
 DEBUG: config.repoIsOnboarded=true (repository=jonmi/gitlab-include-demo)
 DEBUG: processRepo() (repository=jonmi/gitlab-include-demo)
 DEBUG: Processing 1 branch: renovate/docker-node-12.x (repository=jonmi/gitlab-include-demo)
 DEBUG: Calculating hourly PRs remaining (repository=jonmi/gitlab-include-demo)
 DEBUG: currentHourStart=1594238400000 (repository=jonmi/gitlab-include-demo)
 DEBUG: PR hourly limit remaining: 2 (repository=jonmi/gitlab-include-demo)
 DEBUG: Enforcing prConcurrentLimit (20) (repository=jonmi/gitlab-include-demo)
 DEBUG: 0 PRs are currently open (repository=jonmi/gitlab-include-demo)
 DEBUG: PR concurrent limit remaining: 20 (repository=jonmi/gitlab-include-demo)
 DEBUG: Calculated maximum PRs remaining this run (repository=jonmi/gitlab-include-demo)
        "prsRemaining": 2
 DEBUG: processBranch with 1 upgrades (repository=jonmi/gitlab-include-demo, dependencies=node, branch=renovate/docker-node-12.x)
 DEBUG: Setting baseBranch to master (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: Setting baseBranch to master (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: latest commit (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
        "branchName": "master",
        "latestCommitDate": "2020-07-08 20:00:35 +0000"
 DEBUG: getBranchPr(renovate/docker-node-12.x) (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: branchExists=false (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: Branch has 1 upgrade(s) (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: recreateClosed is false (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: findPr(renovate/docker-node-12.x, chore(deps): update node docker tag to v12.18.2, !open) (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: prAlreadyExisted=false (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: Checking schedule(at any time, null) (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: No schedule defined (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: Branch needs creating (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: Using reuseExistingBranch: false (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: manager.getUpdatedPackageFiles() (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
        "reuseExistingBranch": false,
        "branchName": "renovate/docker-node-12.x"
  WARN: Cannot find replaceString in current file content (repository=jonmi/gitlab-include-demo, packageFile=.gitlab-ci.yml, branch=renovate/docker-node-12.x)
        "depName": "node",
        "existingContent": "include:\n  - local: 'tag.yml'\n\nstages:\n- pass\n\npass:\n  stage: pass\n  image: alpine\n  script:\n    - echo pass\n",
        "replaceString": "node:12.18.2-alpine"
 DEBUG: No content changed (repository=jonmi/gitlab-include-demo, packageFile=.gitlab-ci.yml, branch=renovate/docker-node-12.x)
        "depName": "node"
[...]
```

**To Reproduce**

Demo Gitlab Repo: https://gitlab.com/jonmi/gitlab-include-demo

**Additional context**

It seems like the problem is that Renovate searches in the wrong file for the version string. I'm not 100% sure what's necessary but after looking into the existing code I think custom `extractAllPackageFiles` and `update` methods need to be implemented (as done for maven). Maybe somebody has the time to look into it.

### PR DESCRIPTION
**Pull request by l0nax**
## Changes:

This PR fixes the problems as described in #6713 where the `include:local` blocks from the GitLab CI YAML file where ignored by renovate.

## Context:

Fixes #6713 

Reimplementation of https://github.com/renovatebot/renovate/pull/8805.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/manager/gitlabci/index.ts [hunk 1]
```diff
@@ -1,9 +1,9 @@
 import { LANGUAGE_DOCKER } from '../../constants/languages';
-import { extractPackageFile } from './extract';
+import { extractAllPackageFiles, extractPackageFile } from './extract';
 
 const language = LANGUAGE_DOCKER;
 
-export { extractPackageFile, language };
+export { extractAllPackageFiles, extractPackageFile, language };
```
Comment (viceice) [inline lib/manager/gitlabci/index.ts:6]:
```suggestion
export { extractAllPackageFiles, language };
```

Only one of those functions should be exported

File: lib/manager/gitlabci/extract.ts [hunk 2]
```diff
@@ -79,3 +82,49 @@ export function extractPackageFile(content: string): PackageFile | null {
...
+  packageFiles: string[]
+): Promise<PackageFile[] | null> {
+  const filesToExamine = new Set<string>(packageFiles);
+  const results: PackageFile[] = [];
+
+  // extract all includes from the files
+  for (const file of packageFiles) {
+    const content = await readLocalFile(file, 'utf8');
+    const doc = yaml.safeLoad(content, { json: true }) as any;
+    if (doc?.include && is.array(doc.include)) {
```
Comment (viceice) [inline lib/manager/gitlabci/extract.ts:97]: Extract other deps here and push to results if any deps are found.

Also add a seen files list, so we can't get an endless loop because of circular includes.

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/manager/gitlabci/index.ts (hunk 1 above)
Comment (l0nax) [reply lib/manager/gitlabci/index.ts:6]: I tried that, but if I do this, renovate will not work anymore.
This is because the `doAutoReplace` in `lib/workers/branch/auto-replace.ts` does call `confirmIfDepUpdated` and this function does use the `extractPackageFile` function:
https://github.com/renovatebot/renovate/blob/cda66e08c533c400e8a44ccd23af31cd7e7de6ef/lib/workers/branch/auto-replace.ts#L24-L32

Either `confirmIfDedpUpdated` has to be refactored or `extractPackageFile` needs to be exported – like the `batect` manager:
https://github.com/renovatebot/renovate/blob/cda66e08c533c400e8a44ccd23af31cd7e7de6ef/lib/manager/batect/index.ts#L1-L3

**Comment by l0nax** [comment]
> @rarkins I think we should merge `gitlabci-include` to `gitlabci` as they both do nearly the same.

@viceice should this be part of this PR?

File: lib/manager/gitlabci/index.ts (hunk 1 above)
Comment (l0nax) [reply lib/manager/gitlabci/index.ts:6]: @viceice @rarkins What is the preferred way to do it?

**Comment by rarkins** [comment]
> > @rarkins I think we should merge `gitlabci-include` to `gitlabci` as they both do nearly the same.
> 
> @viceice should this be part of this PR?

No, it should be done before or after to keep the refactoring separate

**Comment by l0nax** [comment]
> > > @rarkins I think we should merge `gitlabci-include` to `gitlabci` as they both do nearly the same.
> > 
> > 
> > @viceice should this be part of this PR?
> 
> No, it should be done before or after to keep the refactoring separate

And what should we do for the things mentioned here https://github.com/renovatebot/renovate/pull/8810#discussion_r580839923?

**Comment by l0nax** [comment]
@rarkins @viceice

File: lib/manager/gitlabci/extract.spec.ts [hunk 3]
```diff
@@ -1,34 +1,61 @@
...
-);
-
-const yamlFile1 = readFileSync(
-  'lib/manager/gitlabci/__fixtures__/gitlab-ci.1.yaml',
-  'utf8'
-);
+import { PackageDependency } from '../common';
+import { extractAllPackageFiles } from './extract';
 
 describe('lib/manager/gitlabci/extract', () => {
```
Comment (viceice) [inline lib/manager/gitlabci/extract.spec.ts:4]:
```suggestion
describe(getName(__filename), () => {
```
import `getName` from `test/utils`

File: lib/manager/gitlabci/extract.ts (hunk 2 above)
Comment (viceice) [reply lib/manager/gitlabci/extract.ts:97]: ⬆️

File: lib/manager/gitlabci/index.ts (hunk 1 above)
Comment (viceice) [reply lib/manager/gitlabci/index.ts:6]: leave this as is for now

**Review by viceice — CHANGES_REQUESTED** [review]
needs deconflicting

**Comment by viceice** [comment]
first finish this, then merge managers in separate pr

**Comment by l0nax** [comment]
@viceice sorry for my late response, I had to finish some internal stuff. I've added a _seen file list_ to prevent an endless loop as requested by you.

File: lib/manager/gitlabci/extract.ts [hunk 4]
```diff
@@ -79,3 +82,60 @@ export function extractPackageFile(content: string): PackageFile | null {
...
+      for (const includeObj of doc.include) {
+        if (includeObj.local) {
+          const fileObj = (includeObj.local as string).replace(/^\//, '');
+          if (
+            !filesToExamine.has(fileObj) &&
+            !filesAlreadyProcessed.has(fileObj)
+          ) {
```
Comment (viceice) [inline lib/manager/gitlabci/extract.ts:109]:
```suggestion
          if (!filesAlreadyProcessed.has(fileObj)) {
```
i think adding again is a noop

File: lib/manager/gitlabci/extract.ts [hunk 5]
```diff
@@ -79,3 +82,60 @@ export function extractPackageFile(content: string): PackageFile | null {
...
+    filesAlreadyProcessed.delete(packageFile);
+
+    const content = await readLocalFile(packageFile, 'utf8');
+    const result = extractPackageFile(content);
+    if (result !== null) {
+      results.push({
+        packageFile,
+        deps: result.deps,
+      });
+    }
```
Comment (viceice) [inline lib/manager/gitlabci/extract.ts:133]: This should be done in the loop above, so we do not need to read the file more than one time

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/manager/gitlabci/extract.ts [hunk 6]
```diff
@@ -79,3 +82,49 @@ export function extractPackageFile(content: string): PackageFile | null {
...
+        if (includeObj.local) {
+          const fileObj = (includeObj.local as string).replace(/^\//, '');
+          if (!filesToExamine.has(fileObj)) {
+            filesToExamine.add(fileObj);
+          }
+        }
+      }
+    }
+
+    const result = extractPackageFile(content);
```
Comment (viceice) [inline lib/manager/gitlabci/extract.ts:111]: @HonkingGoose Please open a new issue:

Refactor `extractPackageFile` to use `js-yaml` and reuse already parsed object from `extractAllPackageFiles`.
So we should extract a new function `parseDoc` to be reused by both extract functions.

**Review by viceice — APPROVED** [review]

File: lib/manager/gitlabci/extract.ts (hunk 6 above)
Comment (HonkingGoose) [reply lib/manager/gitlabci/extract.ts:111]: Done, see #9115. 😉
