### PR TITLE
fix(datasource/npm): cache public modules

### LINKED ISSUE #9587: Use dynamic detection of public repos instead of a static list
**What would you like Renovate to be able to do?**

See: `whitelistedPublicScopes` in `lib/datasource/npm/get.ts`

**Did you already have any implementation ideas?**

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Uses `cache-control` header to determine whether package is private or public and can be cached.

## Context

Closes #9587

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/datasource/npm/get.ts [hunk 1]
```diff
@@ -171,26 +171,22 @@ export async function getDependency(
...
-      '@graphql-codegen',
-      '@storybook',
-      '@types',
-      '@typescript-eslint',
-    ];
     if (
-      !raw.authorization &&
-      (whitelistedPublicScopes.includes(packageName.split('/')[0]) ||
-        !packageName.startsWith('@'))
+      (raw.headers?.['cache-control'] || '')
```
Comment (viceice) [inline lib/modules/datasource/npm/get.ts:175]:
```suggestion
      (raw.headers?.['cache-control'] ?? '')
```

would a regex be faster? 🤔 

```js
/(^|,)\s*public\s*(,|$)/
```

**Review by viceice — COMMENTED** [review]
otherwise LGTM

File: lib/modules/datasource/npm/get.ts [hunk 2]
```diff
@@ -171,26 +171,17 @@ export async function getDependency(
...
-      '@storybook',
-      '@types',
-      '@typescript-eslint',
-    ];
-    if (
-      !raw.authorization &&
-      (whitelistedPublicScopes.includes(packageName.split('/')[0]) ||
-        !packageName.startsWith('@'))
-    ) {
+    if (/(^|,)\s*public\s*(,|$)/.test(raw.headers?.['cache-control'] ?? '')) {
```
Comment (secustor) [inline lib/modules/datasource/npm/get.ts:174]:
```suggestion
    const cacheControl = raw.headers?.['cache-control']
    if (is.nonEmptyString(cacheControl) && regEx(/(^|,)\s*public\s*(,|$)/).test(cacheControl)) {
```
We should use our regex utilities and this is IMO more readable.

**Review by secustor — APPROVED** [review]

**Review by viceice — APPROVED** [review]
