### PR TITLE
fix(config): add package rule to preserveSemverRanges

### LINKED ISSUE #13111: Setting `:preserveSemverRanges` or `rangeStrategy` together with `config:js-app` or `config:js-lib` has no effect and is not user-friendly.
#### Problem
`config:js-app` and `config:js-lib` set `:pinAllExceptPeerDependencies` and `:pinOnlyDevDependencies` respectively, both of which use `packageRules - matchPackagePatterns`.
https://docs.renovatebot.com/presets-default/#pinallexceptpeerdependencies

And these will probably override `rangeStrategy`.

Thus, if a user (like me) tries to write the configuration they are looking for in a straightforward way, the `rangeStrategy` will not be set as expected.

```json5
// https://github.com/ishowta/my-test-repo-of-renovate/blob/main/renovate.json
// https://github.com/ishowta/my-test-repo-of-renovate/pull/7
{
  "extends": [
    "config:js-app",
    ":preserveSemverRanges"
  ]
}
```

#### Hope

It would be nice if an explanation were added, or if the `packageRules` written in `extends` were overridden by the user-written settings.

#### Remarks

I thought I did a quick test to make sure, but I'm a newbie so I might be doing something wrong. Sorry.

### If you have any ideas on how this should be implemented, please tell us here.

It seems that `config:js-*` currently only adds pin settings, so why don't you rename it to something like `config:pin-js-*`?

### Is this a feature you are interested in implementing yourself?

No

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Adds packageRules to preserveSemverRanges preset

## Context:

Closes #13111

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/config/presets/internal/default.ts [hunk 1]
```diff
@@ -67,6 +67,7 @@ export const presets: Record<string, Preset> = {
     description:
       'Preserve (but continue to upgrade) any existing SemVer ranges',
     rangeStrategy: 'replace',
```
Comment (viceice) [inline lib/config/presets/internal/default.ts:69]: can't this be removed then?
```suggestion
```

**Review by viceice — APPROVED** [review]
