### PR TITLE
fix(manager:nuget): use git to read current lockfile

### LINKED ISSUE #15390: NuGet manager does not consider previously updated lockfiles
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.36.0 (latest version)

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab EE

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Consider folder structure
```
b/b.csproj
b.core/b.core.csproj
b.core.tests/b.core.tests.csproj
```
with project graph (`b` depends on `b.core`)
```
b.core/b.core.csproj
├─ b/b.csproj
└─ b.core.tests/b.core.tests.csproj
```
Renovate starts by invoking `dotnet restore` on `b/b.csproj`, probably because this project is encountered first (when sorted alphabetically, although the exact mechanics shouldn't matter). \
The important consideration is that this invocation on `b` will also update the lockfiles for `b.core`.

Now, when proceeding with the `b.core/b.core.csproj` project, its lockfile is already updated (an update lockfile for `b.core` is already in [`existingLockFileContentMap`](https://github.com/renovatebot/renovate/blob/32.15.0/lib/modules/manager/nuget/artifacts.ts#L138)), and they are considered [_not changed_](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/nuget/artifacts.ts#L177).

What's going wrong here seems to be Renovate [traversing down the dependency tree](https://github.com/renovatebot/renovate/blob/32.15.0/lib/modules/manager/nuget/artifacts.ts#L124) (from package to dependents), while the build system is traversing upwards (package to dependencies), generating new lockfiles for dependency projects in the process:

```json
{ "msg": "nuget.updateArtifacts(b/b.csproj)" }
{ "msg": "Found package files", "filteredPackageFiles": [ "b.core.tests/b.core.tests.csproj", "b.core/b.core.csproj", "b/b.csproj" ] }
{ "msg": "Found 1 dependent package files", "packageFiles": [ "b/b.csproj" ] }

{ "msg": "nuget.updateArtifacts(b.core/b.core.csproj)" }
{ "msg": "Found package files", "filteredPackageFiles": [ "b.core.tests/b.core.tests.csproj", "b.core/b.core.csproj", "b/b.csproj" ] }
{ "msg": "Found 3 dependent package files", "packageFiles": [ "b.core.tests/b.core.tests.csproj", "b/b.csproj", "b.core/b.core.csproj "] }
{ "msg": "Lock file b/packages.lock.json is unchanged" }
{ "msg": "Lock file b.core/packages.lock.json is unchanged" }

{ "msg": "nuget.updateArtifacts(b.core.tests/b.core.tests.csproj)" }
{ "msg": "Found package files", "filteredPackageFiles": [ "b.core.tests/b.core.tests.csproj", "b.core/b.core.csproj", "b/b.csproj" ] }
{ "msg": "Found 1 dependent package files", "packageFiles": [ "b.core.tests/b.core.tests.csproj" ] }
{ "msg": "Lock file b.core.tests/packages.lock.json is unchanged" }

{ "msg": "Updated 3 package files" }
{ "msg": "Updated 2 lock files", "updatedArtifacts": [ "b/packages.lock.json", "b.core.tests/packages.lock.json" ] }
{ "msg": "5 file(s) to commit" }
```

As you can see, one'd expect 6 files to be committed, and `b.core/packages.lock.json` is missing.

### Relevant debug logs

I could supply these privately if required. I used trace level logs plus some ad-hoc patches to infer what's causing the issue.
The static analysis in this issue should be sufficient, though.

### Have you created a minimal reproduction repository?

[Reproduction repository](https://github.com/wuhkuh/renovate-nuget-lockfile-reproduction), with the [missing file](https://github.com/wuhkuh/renovate-nuget-lockfile-reproduction/pull/1/files) in the generated pull request.

### PR DESCRIPTION
**Pull request by viceice**
## Changes
Read current lockfile from git, so we detect changes when multiple restore commands are run.
Currently the second restore causes a reset of previous run.

## Context
- fixes #15390

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
https://github.com/renovate-reproductions/15390-renovate-nuget-lockfile-reproduction/pull/1/files

File: lib/modules/manager/nuget/artifacts.ts [hunk 1]
```diff
@@ -175,15 +179,16 @@ export async function updateArtifacts({
...
         retArray.push({
           file: {
             type: 'addition',
             path: lockFileName,
-            contents: newLockFileContentMap[lockFileName],
+            contents: newLockFileContentMap[lockFileName]!,
           },
         });
       }
+      // TODO: else should we return an artifact error if new content is missing?
```
Comment (wuhkuh) [inline lib/modules/manager/nuget/artifacts.ts:191]: No:

Consider the case where the user reconfigures
```
<Project>
  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
```
to
```
<Project>
  <PropertyGroup>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
```

If the lockfiles don't match the requested version or are malformed, and `RestoreLockedMode` is configured as `true` (read: the build requires a valid lockfile), the Restore target will throw an error. There will be no need for additional logic in Renovate.

Comment (viceice) [reply lib/modules/manager/nuget/artifacts.ts:191]: this TODO means to return an error if there is a lockfile in repo and after running `dotnet restore` it's missing. So when somethinkg was wrong with running the dotnet executable but without error exit. Not sure if it can happen.

**Comment by rarkins** [comment]
I'm a bit lost. Could anyone summarize it simply?

**Comment by viceice** [comment]
> I'm a bit lost. Could anyone summarize it simply?

Scenario:
- We have 3 project files, a,b,c and b,c depend on a.
- Renovate updates same dep in all projects
- Renovate runs update artifacts on all projects
  - project a run: reads current lockfile, updates lockfile for all projects, because of detected transitive dep, returns all changed lockfiles
  - project b run: reads changed lockfiles, rund restore for a and b, returns only b lockfile, as a didn't change in this run (this overwrites the previous returned lickfile result)
  - project c run: like b, returns on c lockfile 
- renovate drops a lockfile from changes

So for correclty change detection we now read the lockfile from git and compare with current files, so all changes files are returned.

**Comment by rarkins** [comment]
So when you write:

> This will block lockfiule usage on nuget manager, so please review.

Do you mean it's currently blocked, and your PR fixes it? Or this PR blocks something?

**Review by rarkins — APPROVED** [review]

**Comment by viceice** [comment]
> So when you write:
> 
> > This will block lockfiule usage on nuget manager, so please review.
> 
> Do you mean it's currently blocked, and your PR fixes it? Or this PR blocks something?

This will block lockfile usage, see #15390
