### PR TITLE
fix(manager/npm): use root pnpm constraints for workspaces

### LINKED ISSUE #14233: Root-level workspace pnpm constraint not used when updating workspace package
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We've recently added a constraint to assert all team members and automations use the same `pnpm` version as described [here](https://pnpm.io/package_json#fields).  

It seems like when used in a workspaces setup Renovate always does not respect the version constraints set in the workspace root `package.json` and attempts the latest version of `pnpm`, which fails when `engines` is strict.  
I then tries to install on the entire monorepo this discrepancy causes it to fail and not update the lockfile:

```
Your pnpm version is incompatible with \"/tmp/renovate/gh/env0/env0\".
Expected version: =6.16.0\nGot: 6.31.0
This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.
To install the latest version of pnpm, run \"pnpm i -g pnpm\".
To check your pnpm version, run \"pnpm -v\",
```
[source](https://app.renovatebot.com/dashboard#github/env0/env0/578990013)

See a [minimal reproduction repository](https://github.com/roni-frantchi/renovate-repro-issue-14233/pull/5)

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: lock file error(branch="renovate/emotion-monorepo")
{
  "cmd": "pnpm",
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/tmp/renovate/gh/env0/env0\":\"/tmp/renovate/gh/env0/env0\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/tmp/renovate/gh/env0/env0\" docker.io/renovate/node bash -l -c \"install-tool pnpm 6.31.0 && pnpm install --recursive --lockfile-only --ignore-scripts --ignore-pnpmfile\"",
    "stdout": "Installing legacy tool pnpm v6.31.0\n\nadded 1 package, and audited 2 packages in 3s\n\n1 package is looking for funding\n  run `npm fund` for details\n\nfound 0 vulnerabilities\n6.31.0\n WARN  The \"store\" setting has been renamed to \"store-dir\". Please use the new name.\n ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)\n\nYour pnpm version is incompatible with \"/tmp/renovate/gh/env0/env0\".\n\nExpected version: =6.16.0\nGot: 6.31.0\n\nThis is happening because the package's manifest has an engines.pnpm field specified.\nTo fix this issue, install the required pnpm version globally.\n\nTo install the latest version of pnpm, run \"pnpm i -g pnpm\".\nTo check your pnpm version, run \"pnpm -v\".\n",
    "stderr": "npm notice \nnpm notice New minor version of npm available! 8.3.1 -> 8.5.0\nnpm notice Changelog: <https://**redacted**@8.5.0` to update!\nnpm notice \nnpm WARN using --force Recommended protections disabled.\n",
    "message": "Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/tmp/renovate/gh/env0/env0\":\"/tmp/renovate/gh/env0/env0\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/tmp/renovate/gh/env0/env0\" docker.io/renovate/node bash -l -c \"install-tool pnpm 6.31.0 && pnpm install --recursive --lockfile-only --ignore-scripts --ignore-pnpmfile\"\nnpm notice \nnpm notice New minor version of npm available! 8.3.1 -> 8.5.0\nnpm notice Changelog: <https://**redacted**@8.5.0` to update!\nnpm notice \nnpm WARN using --force Recommended protections disabled.\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/tmp/renovate/gh/env0/env0\":\"/tmp/renovate/gh/env0/env0\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/tmp/renovate/gh/env0/env0\" docker.io/renovate/node bash -l -c \"install-tool pnpm 6.31.0 && pnpm install --recursive --lockfile-only --ignore-scripts --ignore-pnpmfile\"\nnpm notice \nnpm notice New minor version of npm available! 8.3.1 -> 8.5.0\nnpm notice Changelog: <https://**redacted**@8.5.0` to update!\nnpm notice \nnpm WARN using --force Recommended protections disabled.\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)"
  },
  "type": "pnpm"
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a [minimal reproduction repository](https://github.com/roni-frantchi/renovate-repro-issue-14233/pull/5) in the bug description

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes

in the post-update of `pnpm` , we will take the root `package.json` and check if it has constraint.

Constraint assignment priority: 
1) we will check the config constraint as priority 
2) if the current workspace has constraint, it will be considered 
3) if the root has constraint it will be considered

## Context

Closes #14233
related: https://github.com/renovatebot/renovate/issues/14662

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/npm/post-update/pnpm.ts [hunk 1]
```diff
@@ -26,9 +27,18 @@ export async function generateLockFile(
       (upgrade) =>
         upgrade.depType === 'packageManager' && upgrade.depName === 'pnpm'
     );
+    let pnpmEngine;
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/pnpm.ts:30]: Config constraints should have highest prio. So only try to lookup when not already configured.

**Review by viceice — CHANGES_REQUESTED** [review]

**Comment by viceice** [comment]
- 👉 #14662

**Comment by PhilipAbed** [comment]
@viceice am i supposed to do anything with that comment?

**Comment by viceice** [comment]
> @viceice am i supposed to do anything with that comment?

Sure. please make code behaving as suggested in issue.

**Comment by PhilipAbed** [comment]
@viceice i already finished that part, now config.Constraints take priority.
and it is done in the "update" section instead of the extraction.

i meant if anything else is missing let me know it  LGTM

File: lib/modules/manager/npm/post-update/pnpm.ts [hunk 2]
```diff
@@ -26,9 +27,22 @@ export async function generateLockFile(
...
+      const engines = packageJson?.engines;
+      pnpmEngine = engines['pnpm'];
+    }
+    if (pnpmUpdate?.newValue) {
+      pnpmEngine = pnpmUpdate.newValue;
+    }
     const pnpmToolConstraint: ToolConstraint = {
       toolName: 'pnpm',
-      constraint: pnpmUpdate ? pnpmUpdate.newValue : config.constraints?.pnpm,
+      constraint: config.constraints?.pnpm
```
Comment (rarkins) [inline lib/modules/manager/npm/post-update/pnpm.ts:43]: Is this being set in the extract function, or will it only come from config?

Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.ts:43]: i dont think we should remove the one we set at the extract, as it is meant for the Update pnpm engine, if i remove it, then we won't be able to update it, that's regression.

and it will not override the value as `pnpmUpdate.newValue` will be changed only if we are in the pnpm version upgrade, and its not related to our issue, since we are trying to update a different dependency in the child workspace, but the problem is running the binary install constraint.

what we are saying is:
If the customer asked for pnpm version in config, then run that version.
if the `package.json` has pnpm constraint that needs an update, then update it and run the updated one.
if not, then go to the root, and check if the `package.json` has `engine.pnpm` and take the constraint from there.

the things that are actually worrying me are :
1) what if the `engine.pnpm` was on the workspace child instead of the root? is that an option? im not familiar with pnpm
2) what if the root workspace wasn't at the root of the folder? then we wont find a `package.json` there.. should we do a lookup until we find the last `package.json`?

Comment (rarkins) [reply lib/modules/manager/npm/post-update/pnpm.ts:43]: > i dont think we should remove the one we set at the extract, as it is meant for the Update pnpm engine, if i remove it, then we won't be able to update it, that's regression.

I don't mean to remove it from the dependencies list, but instead to remove it from `constraints.pnpm`.

Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.ts:43]: @rarkins i see, so i should remove `constraints.pnpm = dep.currentValue` from extract because it overrides the `constraints.config`?
if i remove it, then it will not override the `constraints.config`, and will just take the `pnpm.update` from the current `package.json`.

is that right? or am i still missing something?

Comment (rarkins) [reply lib/modules/manager/npm/post-update/pnpm.ts:43]: @PhilipAbed yes, you're right! In other words we extract the contraints "lazily". I think in such cases we probably don't even need to have the extra logic to check "is there an update in this PR for pnpm itself?" because if there was, it would have been written to package.json already, and we would extract it.

Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.ts:43]: @rarkins 
So you are saying that the Constraints aren't needed in the the Extract+lookup section, but needed in the Post-Update section.


so i should remove this section from pnpm.ts :: generateLockFile ?
```
const pnpmUpdate = upgrades.find(
  (upgrade) =>
    upgrade.depType === 'packageManager' && upgrade.depName === 'pnpm'
);
```

so we are checking if pnpm has an Upgrade, and then setting the upgrade new value as a constraint? 
and we want to remove that.
i agree.

Now here's a case i still don't think is solved yet:
What if the `package-x/package.json` ( child workspace package json) had the Constraint( engine->pnpm:version X), but the constraint wasn't found on the Root `package.json`, is that a valid case?

File: lib/modules/manager/npm/post-update/__snapshots__/pnpm.spec.ts.snap [hunk 3]
```diff
@@ -1,6 +1,8 @@
 // Jest Snapshot v1, https://goo.gl/fbAQLP
 
-exports[`modules/manager/npm/post-update/pnpm catches errors 1`] = `
+exports[`modules/manager/npm/post-update/pnpm catches errors 1`] = `Array []`;
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/__snapshots__/pnpm.spec.ts.snap:3]: Please don't use snapshot expectation for empty or small objects. Use other inline matchers instead.

File: lib/modules/manager/npm/post-update/pnpm.ts (hunk 2 above)
Comment (viceice) [reply lib/modules/manager/npm/post-update/pnpm.ts:43]: Yes.

If there is an `pnpm` update, the current or root `package.json` is already updated. So please refactor the code above to this:
1. Use `config.constraints?.pnpm` if defined
2. Extract from local `package.json`
3. Extract from root `package.json`

Comment (rarkins) [reply lib/modules/manager/npm/post-update/pnpm.ts:43]: Do we run the pnpm command on the local folder or the root?

Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.ts:43]: @rarkins only on the top folder to generate lock file

File: lib/modules/manager/npm/post-update/__snapshots__/pnpm.spec.ts.snap (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/__snapshots__/pnpm.spec.ts.snap:3]: i dont remmember changing this. i will check the tests O.o

Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/__snapshots__/pnpm.spec.ts.snap:3]: image

according to docs, its a field that should be on a project level, not workspace

File: lib/modules/manager/npm/post-update/pnpm.ts (hunk 2 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.ts:36]: image

i believe its on a project level and not workspace :D

File: lib/modules/manager/npm/post-update/__snapshots__/pnpm.spec.ts.snap (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/__snapshots__/pnpm.spec.ts.snap]: fixed test

File: lib/modules/manager/npm/post-update/pnpm.ts (hunk 2 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.ts:36]: i finished coding, considering its just on a root level.

so either Config or Root level engine. (config is priority)

File: lib/modules/manager/npm/post-update/pnpm.spec.ts [hunk 4]
```diff
@@ -25,56 +28,115 @@ describe('modules/manager/npm/post-update/pnpm', () => {
...
     ]);
-    expect(fs.readFile).toHaveBeenCalledTimes(1);
+    expect(fs.readFile).toHaveBeenCalledTimes(2);
     expect(res.lockFile).toBe('package-lock-contents');
     expect(execSnapshots).toMatchSnapshot();
     // TODO: check docker preCommands
   });
+
+  it('uses constraint version if parent json has constraints', async () => {
+    const childPkgJson = readFixture('parent/package.json');
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/pnpm.spec.ts:101]:
```suggestion
    const childPkgJson = Fixtures.get('parent/package.json');
```

File: lib/modules/manager/npm/post-update/pnpm.spec.ts [hunk 5]
```diff
@@ -11,6 +12,8 @@ jest.mock('../../../../util/exec/env');
 jest.mock('../../../../util/fs/proxies');
 jest.mock('./node-version');
 
+const readFixture = (x: string): string => Fixtures.get(x, '.');
+
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/pnpm.spec.ts:16]:
```suggestion
```
Why this, you don't need to pass baseDir by default, it's local `__fixtures__` directory by default and all fixtures should be in that directory. So this wrapper function should be removed.

File: lib/modules/manager/npm/post-update/pnpm.spec.ts [hunk 6]
```diff
@@ -25,56 +28,115 @@ describe('modules/manager/npm/post-update/pnpm', () => {
   });
   it('generates lock files', async () => {
     const execSnapshots = mockExecAll(exec);
-    fs.readFile = jest.fn(() => 'package-lock-contents') as never;
+    fs.readFile = jest
+      .fn()
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/pnpm.spec.ts:32]:
```suggestion
    fs.readFile
```

Thise are already mocked, so please use new syntax

File: lib/modules/manager/npm/post-update/pnpm.spec.ts [hunk 7]
```diff
@@ -11,6 +12,8 @@ jest.mock('../../../../util/exec/env');
 jest.mock('../../../../util/fs/proxies');
 jest.mock('./node-version');
 
+const readFixture = (x: string): string => Fixtures.get(x, '.');
+
 const exec: jest.Mock<typeof _exec> = _exec as any;
 const env = mocked(_env);
 const fs = mocked(_fs);
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/pnpm.spec.ts:19]: Please import from `test/util` and `test/exec-util`

File: lib/modules/manager/npm/post-update/pnpm.ts [hunk 8]
```diff
@@ -22,13 +23,19 @@ export async function generateLockFile(
...
+      const packageJson: NpmPackage = JSON.parse(content);
+      const engines = packageJson?.engines;
+      pnpmEngine = engines['pnpm'];
+    }
     const pnpmToolConstraint: ToolConstraint = {
       toolName: 'pnpm',
-      constraint: pnpmUpdate ? pnpmUpdate.newValue : config.constraints?.pnpm,
+      constraint: config.constraints?.pnpm
+        ? config.constraints.pnpm
+        : pnpmEngine,
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/pnpm.ts:38]:
```suggestion
      constraint: config.constraints?.pnpm?? await getPnpmContraint(),
```

Make reading pnpm contraints lazy, also try the new `packageManager` field.

- https://nodejs.org/api/packages.html#packages_packagemanager
- https://nodejs.org/api/corepack.html

Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.ts:38]: so the packageManager is the new field for deciding, now which one takes precedence? 
i cant find any connection between the two online, 
also
image
should i consider the flag? or just do the constraint anyway?

Comment (viceice) [reply lib/modules/manager/npm/post-update/pnpm.ts:38]: `packageManager` is the new way. I think `engines` should have preference for now as it's more commonly used.
@rarkins WDYT?

File: lib/modules/manager/npm/post-update/pnpm.spec.ts (hunk 6 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.spec.ts:32]: im not sure what you mean, i thought im already using the new syntax,
anyway im changing all these tests back as its not needed anymore after doing the Lazy approach..

Comment (viceice) [reply lib/modules/manager/npm/post-update/pnpm.spec.ts:32]: You should not overwrite functions with mocks, those cant be automatically reset, so use normal mosule mocking like we do on all other tests. 😉

**Comment by viceice** [comment]
Why do you resolved conversions without change or answer? 🤔

File: lib/modules/manager/npm/post-update/pnpm.ts (hunk 8 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.ts:38]: well, if everybody is using engine, and only 1 guy is using packageManager, we can check for packageManager first since its the new field, if people dont have it, then we fall back to engine.
that makes more sense to me.

the only reason why i would agree with you is because we could keep backward compatibility if the engines precedes the pacakgeManager.

ill let you and @rarkins decide though :D

Comment (viceice) [reply lib/modules/manager/npm/post-update/pnpm.ts:38]: You are right, in future corepack would probably enabled by default, so `packageManager` should have preference 👍

File: lib/modules/manager/npm/post-update/pnpm.spec.ts (hunk 6 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.spec.ts]: i submitted new code, im not sure what you mean, this is like my second time using JEST, so i'm not familiar with those phrasings.

do i still use bad mocks after my latest push?, if yes maybe help me make them better so i can learn how to do it, that's what i found when i researched jest mocks.

Comment (viceice) [reply lib/modules/manager/npm/post-update/pnpm.spec.ts]: I know, you are editing tests, which are old and not yet updated to use new mocking stuff we added for simplier testing. So iut's probably not your fault, you simply copied existing bad code😉

Comment (PhilipAbed) [reply lib/modules/manager/npm/post-update/pnpm.spec.ts]: can u give an example? or documentation on how to do things the right way? im new to this

**Comment by PhilipAbed** [comment]
:D i usually fix the code before i resolve the conversation , did i miss something?
you speak in puzzles, maybe just mention Which one you mean?
when you want me to fix a test, show me an example/link? 
just saying "this should change", "this is wrong" isnt enough for me to understand i need some pointers to know what you mean

File: lib/modules/manager/npm/post-update/pnpm.spec.ts [hunk 9]
```diff
@@ -77,4 +79,90 @@ describe('modules/manager/npm/post-update/pnpm', () => {
...
+      },
+    ]);
+  });
+
+  it('uses packageManager version and puts it into constraint', async () => {
+    const execSnapshots = mockExecAll(exec);
+    const configTemp = { cacheDir: 'some-cache-dir' };
+    const fileContent = Fixtures.get('manager-field/package.json');
+    fs.readFile = jest
+      .fn()
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/pnpm.spec.ts:131]:
```suggestion
    fs.readFile
```

**Review by viceice — COMMENTED** [review]
Those other comments are gone now. You probably resolved them before you pushed the actual code.

**Comment by rarkins** [comment]
> :D i usually fix the code before i resolve the conversation , did i miss something? you speak in puzzles, maybe just mention Which one you mean? when you want me to fix a test, show me an example/link? just saying "this should change", "this is wrong" isnt enough for me to understand i need some pointers to know what you mean

@PhilipAbed as a precaution, avoid clicking the "Resolve conversation" button for a while, so that comments don't disappear that way. If you have any questions about specific comments, reply to them inline so that it's obvious which one you're referring to.

**Review by rarkins — COMMENTED** [review]
Logic is looking good, LGTM after latest reviews changes are implemented

File: lib/modules/manager/npm/post-update/pnpm.spec.ts [hunk 10]
```diff
@@ -77,4 +79,90 @@ describe('modules/manager/npm/post-update/pnpm', () => {
     expect(execSnapshots).toMatchSnapshot();
     // TODO: check docker preCommands
   });
+
+  it('uses constraint version if parent json has constraints', async () => {
+    const execSnapshots = mockExecAll(exec);
+    const configTemp = { cacheDir: 'some-cache-dir' };
+    const fileContent = Fixtures.get('parent/package.json');
+    fs.readFile = jest
+      .fn()
```
[the remark this answers is not in the document]
Comment (rarkins) [reply lib/modules/manager/npm/post-update/pnpm.spec.ts:87]: @viceice looks like this approach is how the rest of the file is doing it, perhaps can we keep it as-is for now? Only npm and pnpm use this mock syntax, might be related to them using absolute fs directly instead of our util

[the remark this answers is not in the document]
Comment (viceice) [reply lib/modules/manager/npm/post-update/pnpm.spec.ts:87]: 🤔 OK. Should be fixed soon in another PR

**Review by viceice — APPROVED** [review]
