### PR TITLE
fix(pypi): package name with periods

### LINKED ISSUE #15782: Package update not found when name contains `.`
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:32.68.1-slim

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

7.21.1

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate is not finding any python package updates where the package name contains `.` but the wheel .whl filename has the `.` replaced with `_`.

The relevant spec: https://packaging.python.org/specifications/binary-distribution-format/#escaping-and-unicode

I have a python PEP420 namespace package with the name `testing.test-namespace-package` and I can upload it successfully to our internal private Nexus repository.

If I follow the URL that renovate is looking at on our Nexus instance, I get these filenames:
```
testing_test_namespace_package-1.0.0-py3-none-any.whl
testing_test_namespace_package-1.0.1-py3-none-any.whl
testing_test_namespace_package-1.0.2-py3-none-any.whl
testing_test_namespace_package-1.0.3-py3-none-any.whl
```

Looking at https://github.com/renovatebot/renovate/blob/13d0255d8d452b561183b0143f9190a358683aaf/lib/modules/datasource/pypi/index.ts#L170 it seems like `extractVersionFromLinkText` is correctly replacing `-` with `_` but is not replacing the `.` with `_` in the filename as per the packaging spec.

Reproduction repository: https://github.com/wwuck/renovate-pep420-namespace-package
This repository is an example PEP420 namespace package that contains `.` in the package name but when built into a .whl file the `.` are replaced with `_` in the filename.

There is currently a bug on pypi.org warehouse software that prevents uploading of packages in this format, but we are using them successfully with our internal private Nexus repository, so I can't link to any test package on https://test.pypi.org for this bug.

https://github.com/pypa/warehouse/pull/10072
https://github.com/pypa/flit/issues/442
https://github.com/pypa/flit/issues/473

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found no results from datasource that look like a version (repository=RT/test-renovate-bug, dependency=testing.test-namespace-package)
       "result": {"releases": [], "isPrivate": true}

...

DEBUG: packageFiles with updates (repository=RT/test-renovate-bug)
       "config": {
         "pip_requirements": [
           {
             "packageFile": "requirements-dev.txt",
             "deps": [
               {
                 "depName": "testing.test-namespace-package",
                 "currentValue": "==1.0.0",
                 "datasource": "pypi",
                 "currentVersion": "1.0.0",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "pep440"
               }
             ],
             "registryUrls": ["https://nexus.example.com/repository/pypi-group/simple"]
           }
         ]
       }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by wwuck**
## Changes

This change fixes the pypi link extraction to detect when a period in the package name has been replaced with underscore in the wheel filename.

## Context

Closes: #15782

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/datasource/pypi/index.ts [hunk 1]
```diff
@@ -182,10 +182,14 @@ export class PypiDatasource extends Datasource {
     // pep-0427 wheel packages
     //  {distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl.
     const wheelText = text.toLowerCase();
-    const wheelPrefix = packageName.replace(regEx(/[^\w\d.]+/g), '_') + '-';
```
Comment (rarkins) [inline lib/modules/datasource/pypi/index.ts:185]: Did this `/g` make sense if the regex starts with `^`?

Comment (wwuck) [reply lib/modules/datasource/pypi/index.ts:185]: Yes I think so.  The `^` is inside `[]` so it is just negating the character classes `\w`, `\d`, and the character `.`, instead of denoting the start of string if it were before the `[`.  The `\g` is there to not return after the first match.  Otherwise you would end up with `test-package-name` changing into `test_package-name`?

Comment (rarkins) [reply lib/modules/datasource/pypi/index.ts:185]: Thanks

Comment (rarkins) [inline lib/modules/datasource/pypi/index.ts:185]: Next question: was the `.` in this regex correct in the first place? Should it have instead been `/.`?

I think we need to document better here, so that it's clearer to future maintainers. When I look at this code (and some of the old code) I'm not sure what/why it's meant to be doing.

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/modules/datasource/pypi/index.ts (hunk 1 above)
Comment (jonyscathe) [reply lib/modules/datasource/pypi/index.ts:185]: Answering that question as I also need this PR merged in order for some internal packages to be updated correctly by renovate.

Within a character class the only special characters are `^-]\` so a `.` only matches a `.`.
`\.` will still work and possibly be more understandable for most people, however the current regex does match the regex string in the PEP427 example exactly which I think is preferable: https://peps.python.org/pep-0427/#escaping-and-unicode

I do agree that an extra comment or two couldn't hurt. Particularly as this is trying to match both the older specification (PEP427) still being used by most packages as well as the current Python Binary Distribution Format specification which won't be terribly clear to people who aren't familiar with wheel naming conventions.

**Review by rarkins — APPROVED** [review]
