### PR TITLE
fix: support artifact updates with multiple managers per package file

### LINKED ISSUE #26949: Conflict in choosing the manager to process lockfile when multiple managers are using the same package file
### Describe the proposed change(s).

When multiple managers work on the same package file, the lockfile maintenance breaks because all lockfiles dependent on the same package file are updated with only one manager instead of their corresponding managers.

_Related discussion: https://github.com/renovatebot/renovate/discussions/26851_
_Detailed explanation: https://github.com/renovatebot/renovate/discussions/26851#discussioncomment-8264904_

### PR DESCRIPTION
**Pull request by fgreinacher**
## Changes

Changes the update handling so that it supports the scenario when there are multiple managers for a single package file.

## Context

Closes #26949

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

:hammer_and_pick: with :heart: by [Siemens](https://opensource.siemens.com/)

### CODE REVIEW

File: lib/workers/repository/update/branch/get-updated.ts
Comment (fgreinacher) [inline lib/workers/repository/update/branch/get-updated.ts:1]: Wow, the diff here is horrible.

All I did was replace all usages of the manager map:

```typescript
const manager = packageFileManagers[packageFile.path];
const updateArtifacts = get(manager, 'updateArtifacts');
// ...
```

By a loop:

```typescript
const managers = packageFileManagers[packageFile.path];
for (const manager of managers) {
  const updateArtifacts = get(manager, 'updateArtifacts');
  // ...
}
```

File: lib/workers/repository/update/branch/get-updated.ts [hunk 1]
```diff
@@ -57,7 +57,8 @@ export async function getUpdatedPackageFiles(
     const newVersion = upgrade.newVersion!;
     const currentVersion = upgrade.currentVersion!;
     const updateLockedDependency = get(manager, 'updateLockedDependency')!;
-    packageFileManagers[packageFile] = manager;
+    packageFileManagers[packageFile] = packageFileManagers[packageFile] || [];
```
Comment (viceice) [inline lib/workers/repository/update/branch/get-updated.ts:60]:
```suggestion
    packageFileManagers[packageFile] ??= [];
```

Comment (fgreinacher) [reply lib/workers/repository/update/branch/get-updated.ts]: Applied (sorry, force-pushed because it was still on draft 😄)

File: lib/workers/repository/update/branch/get-updated.ts [hunk 2]
```diff
@@ -286,24 +286,28 @@ export async function getUpdatedPackageFiles(
...
-      });
-      if (is.nonEmptyArray(results)) {
-        for (const res of results) {
-          const { file, artifactError } = res;
-          if (file) {
-            updatedArtifacts.push(file);
-          } else if (artifactError) {
-            artifactErrors.push(artifactError);
+    const managers = packageFileManagers[packageFile.path];
+    if (managers !== undefined) {
```
Comment (RahulGautamSingh) [inline lib/workers/repository/update/branch/get-updated.ts:291]: We prefer using `is.undefined` in such cases.
@viceice we use `!== undefined` in some places whereas `is.undefined` at other..
We should be consisitent right?

Comment (fgreinacher) [reply lib/workers/repository/update/branch/get-updated.ts:291]: Good point, thanks! I went for `is.nonEmptyArray` to avoid the negation

File: lib/workers/repository/update/branch/get-updated.ts
Comment (fgreinacher) [reply lib/workers/repository/update/branch/get-updated.ts:1]: With the latest commit it's better, no idea why

**Review by secustor — APPROVED** [review]

**Review by viceice — APPROVED** [review]
