### PR TITLE
fix(manager/flux): extract both tag and digest for OCIRepository

### LINKED ISSUE #29768: Let `flux` manager update tags and digests (`flux` currently ignores tags)
### Describe the proposed change(s).

Renovate's `flux` manager does _not_ support updating tags _and_ digests yet:

https://github.com/renovatebot/renovate/blob/8975c9bda67880fd4c91bdc32534e24f98a90e0e/lib/modules/manager/flux/extract.ts#L214

`@viceice` says Renovate should support updating tags _and_ digests. `@viceice` will look next week if there's an easy way to add support.

Related Discussion:

- #29521

### PR DESCRIPTION
**Pull request by robinschneider**
## Changes

This PR allows using both tag and digest for the Flux manager for `OCIRepository`.
Flux ignores the tag if there is an additional digest, but a digest is not human readable, so it is better to use them simultaneously. Flux does not support tag@digest, is uses separate fields for these.

## Context

Please select one of the following:

- [x] This closes an existing Issue, Closes: #29768
- [ ] This doesn't close an Issue, but I accept the risk that this PR may be closed if maintainers disagree with its opening or implementation

## AI assistance disclosure

Did you use AI tools to create any part of this pull request?

Please select one option and, if yes, briefly describe how AI was used (e.g., code, tests, docs) and which tool(s) you used.

- [ ] No — I did not use AI for this contribution.
- [ ] Yes — minimal assistance (e.g., IDE autocomplete, small code completions, grammar fixes).
- [x] Yes — substantive assistance (AI-generated non‑trivial portions of code, tests, or documentation).
- [ ] Yes — other (please describe):

I used Gemini 3.1 Pro to support for this PR. I have carefully checked and tested the code.
It took many iterations to get it done.
It helped me to understand what parts of renovate need to be modified in order to achieve updating Flux tag and digest.

## Documentation

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests, but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

The public repository: https://github.com/robinschneider/renovate-flux/pull/1

### CODE REVIEW

**Comment by matheuscscp** [comment]
@secustor Looks like this PR is fixing an important bug in the flux manager, can you pls take a look? :pray:

File: lib/modules/manager/flux/extract.ts [hunk 1]
```diff
@@ -292,29 +293,72 @@ function resolveResourceManifest(
...
+            }
+          } else {
+            logger.debug(
+              { file: manifest.file, name: resource.metadata.name },
+              'Could not find exact tag/digest block in content, auto-replace might fail',
+            );
+            // fallback (will likely fail auto-replace if not formatted this way, but avoids breaking tests outright)
+            combinedDep.replaceString = `${resource.spec.ref.tag}@${resource.spec.ref.digest}`;
+            combinedDep.autoReplaceStringTemplate =
+              '{{newValue}}@{{newDigest}}';
```
Comment (secustor) [inline lib/modules/manager/flux/extract.ts]: As I understand this will lead to errors with Flux

File: lib/modules/manager/flux/extract.ts [hunk 2]
```diff
@@ -292,29 +293,72 @@ function resolveResourceManifest(
...
+              // tag came first
+              combinedDep.autoReplaceStringTemplate = match[0]
+                .replace(resource.spec.ref.tag, '{{newValue}}')
+                .replace(resource.spec.ref.digest, '{{newDigest}}');
+            } else {
+              // digest came first
+              combinedDep.autoReplaceStringTemplate = match[0]
+                .replace(resource.spec.ref.digest, '{{newDigest}}')
+                .replace(resource.spec.ref.tag, '{{newValue}}');
+            }
```
Comment (secustor) [inline lib/modules/manager/flux/extract.ts]: In which scenario would the order here matter?

File: lib/modules/manager/flux/extract.ts [hunk 3]
```diff
@@ -292,29 +293,72 @@ function resolveResourceManifest(
...
+          // Set currentValue to the tag so the docker datasource can look up the image's new digest
+          combinedDep.currentValue = resource.spec.ref.tag;
+
+          // Attempt to find the exact block spanning `tag: ...` to `digest: ...` (or vice-versa) in the source content
+          const escapedTag = escapeRegExp(resource.spec.ref.tag);
+          const escapedDigest = escapeRegExp(resource.spec.ref.digest);
+          // Regex handles both ordering: tag before digest, or digest before tag.
+          // Allows optional single or double quotes around the values.
+          const multilineRegEx = regEx(
+            `(tag\\s*:\\s*["']?${escapedTag}["']?[\\s\\S]+?digest\\s*:\\s*["']?${escapedDigest}["']?)|(digest\\s*:\\s*["']?${escapedDigest}["']?[\\s\\S]+?tag\\s*:\\s*["']?${escapedTag}["']?)`,
```
Comment (secustor) [inline lib/modules/manager/flux/extract.ts]: Split this into two to simplify the regex and additionally match `ref:` before to anchor this in the correct object

File: lib/modules/manager/flux/extract.ts
Comment (secustor) [inline lib/modules/manager/flux/extract.ts:475]: Don't duplicate the state instead use another type which combines `manifest` and `content`

File: lib/modules/manager/flux/extract.ts [hunk 4]
```diff
@@ -364,9 +409,13 @@ export async function extractAllPackageFiles(
 ): Promise<PackageFile<FluxManagerData>[] | null> {
   const manifests: FluxManifest[] = [];
   const results: PackageFile<FluxManagerData>[] = [];
+  const fileContents = new Map<string, string>(); // Add a map to cache content
```
Comment (secustor) [inline lib/modules/manager/flux/extract.ts]: Use Record instead of Map

File: lib/modules/manager/flux/extract.ts (hunk 1 above)
Comment (matheuscscp) [reply lib/modules/manager/flux/extract.ts]: Yeah, `OCIRepository.spec.ref.tag` cannot contain the digest

File: lib/modules/manager/flux/extract.ts (hunk 2 above)
Comment (robinschneider) [reply lib/modules/manager/flux/extract.ts]: The order matters because `replace()` only replaces the first occurrence of a string.

If the tag value happens to be a substring of the digest string (e.g. tag `123` and digest `sha256:abcd123`), and we process the tag first even though the digest comes earlier in the file, `.replace()` might accidentally overwrite a part of the digest instead of the actual tag.

By processing the replacements in the order they physically appear in the YAML file (top-to-bottom), we prevent this issue. The first field is safely replaced by its literal placeholder like `'{{newDigest}}'`, which guarantees it won't conflict with the second replacement.

File: lib/modules/manager/flux/extract.ts [hunk 5]
```diff
@@ -367,10 +416,12 @@ export async function extractAllPackageFiles(
 
   for (const file of packageFiles) {
     const content = await readLocalFile(file, 'utf8');
-    // TODO #22198
-    const manifest = readManifest(content!, file);
-    if (manifest) {
-      manifests.push(manifest);
+    if (content) {
+      // TODO #22198
```
Comment (viceice) [inline lib/modules/manager/flux/extract.ts]:
```suggestion
```

File: lib/modules/manager/flux/extract.ts [hunk 6]
```diff
@@ -292,29 +295,74 @@ function resolveResourceManifest(
...
+              // digest came first
+              combinedDep.autoReplaceStringTemplate = match[0]
+                .replace(resource.spec.ref.digest, '{{newDigest}}')
+                .replace(resource.spec.ref.tag, '{{newValue}}');
+            }
+          } else {
+            logger.debug(
+              { file: manifest.file, name: resource.metadata.name },
+              'Could not find exact tag/digest block in content, skipping extraction',
+            );
```
Comment (viceice) [inline lib/modules/manager/flux/extract.ts:390]: so this would skip?

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: valkey
spec:
  interval: 12h
  url: oci://ghcr.io/visualon/bitnamicharts/valkey
  ref:
    digest: sha256:761c3189c482d0f1f0ad3735ca05c4c398cae201d2169f6645280c7b7b2ce6fc
    # tag is for renovate and will be ignored by flux
    tag: 5.4.7
```

🤔 

instead of regex we should use the yaml document parser, then find the nodes, from them we can get start and end, so we can easily substring replace string from content.

see npm for parsing, the nodes have a Range, which tell you the positions in source.

https://github.com/renovatebot/renovate/blob/a4456c139c20fa02d5447705c40a52c4441fb100/lib/modules/manager/npm/update/dependency/pnpm.ts#L45

Comment (robinschneider) [reply lib/modules/manager/flux/extract.ts:390]: This would break the regex.
I adjusted it to use a yaml document parser as you suggested.
I also added more example configurations to the repository that I linked above for testing

**Review by secustor — APPROVED** [review]
LGTM now
