### PR TITLE
fix(github): remove deleted issue from issues cache

### LINKED ISSUE #32267: GitHub: Renovate attempts to reopen deleted Dashboard issue
### Describe the proposed change(s).

Discussion: https://github.com/renovatebot/renovate/discussions/32161

Workaround: change `dependencyDashboardTitle`

It would be good to strongly type Issue state to achieve this, e.g.

```diff
diff --git a/lib/modules/platform/types.ts b/lib/modules/platform/types.ts
index 91575d098..24eb42cba 100644
--- a/lib/modules/platform/types.ts
+++ b/lib/modules/platform/types.ts
@@ -87,13 +87,15 @@ export interface Pr {
   isDraft?: boolean;
 }
 
+export type IssueState = 'open' | 'closed' | 'deleted';
+
 /**
  * TODO: Proper typing
  */
 export interface Issue {
   body?: string;
   number?: number;
-  state?: string;
+  state?: IssueState;
   title?: string;
 }
 export type PlatformPrOptions = {
```

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
1. `getIssue()`:  Detect deleted issues and remove them from the `GithubIssuesCache`
2. `GithubIssuesCache`:  Added a new method `deleteIssue` to the 

## Context
- Closes: https://github.com/renovatebot/renovate/issues/32267

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or https://github.com/Rahul-renovate-testing/repro-32267/issues 
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/platform/github/index.ts [hunk 1]
```diff
@@ -1248,6 +1248,11 @@ export async function getIssue(number: number): Promise<Issue | null> {
     return issue;
   } catch (err) /* istanbul ignore next */ {
     logger.debug({ err, number }, 'Error getting issue');
+    // istanbul ignore if
+    if (err.message === 'Response Code 410(Gone)') {
```
Comment (viceice) [inline lib/modules/platform/github/index.ts:1252]: you should check status code instead

File: lib/modules/platform/github/index.ts [hunk 2]
```diff
@@ -1248,6 +1248,11 @@ export async function getIssue(number: number): Promise<Issue | null> {
     return issue;
   } catch (err) /* istanbul ignore next */ {
```
Comment (viceice) [inline lib/modules/platform/github/index.ts:1249]: we should no longer ignore this

**Comment by rarkins** [comment]
@zharinov can you test this on a real repo?

**Review by zharinov — APPROVED** [review]
Yep, it works for real repo

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
