### PR TITLE
fix: configure signing for each repo

### LINKED ISSUE #8313: Renovate does not always sign commits
**What Renovate type, platform and version are you using?**
Renovate 24.5.1

**Describe the bug**

I have self-hosted renovate handling github repositories with the following config:
```json
{
  "logLevel": "debug",
  "trustLevel": "high",
  "allowedPostUpgradeCommands": ["^\\.\\/gen-lockfile\\.sh$"],
  "autodiscover": true,
  "binarySource": "global"
}
```

I am still figuring out exact conditions but for some repos renovate does gpg sign commits, for some it does not.
I noticed that for repos where renovsate signs commits there are such logs
```

DEBUG: Executing command (repository=org/repo, branch=renovate/rust-app-rust-deps)
--
  | "command": "git config user.signingkey ***"
  | DEBUG: exec completed (repository=org/repo, branch=renovate/rust-app-rust-deps)
  | "cmd": "git config user.signingkey ***",
  | "durationMs": 49,
  | "stdout": "",
  | "stderr": ""
  | DEBUG: Executing command (repository=org/repo, branch=renovate/rust-app-rust-deps)
  | "command": "git config commit.gpgsign true"
  | DEBUG: exec completed (repository=org/repo, branch=renovate/rust-app-rust-deps)
  | "cmd": "git config commit.gpgsign true",
  | "durationMs": 51,
  | "stdout": "",
  | "stderr": ""
```

And there are no such logs for repos in which renovate does not sign commits.
Also I noticed that the repo for which renovate does sign commits it the first one which renovate processes. So I suppose renovate just runs `git config ...` just for the first repo it picks from discovered repos but it should run at least `git config commit.gpgsign` for every repo.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

### PR DESCRIPTION
**Pull request by onsails**
## Context:

fixes #8313

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [x] Unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/git/private-key.ts [hunk 1]
```diff
@@ -29,17 +29,24 @@ async function importKey(): Promise<void> {
...
-export async function writePrivateKey(cwd: string): Promise<void> {
+export async function writePrivateKey(): Promise<void> {
   if (!gitPrivateKey) {
     return;
   }
   logger.debug('Setting git private key');
   try {
     await importKey();
-    await exec(`git config user.signingkey ${keyId}`, { cwd });
-    await exec(`git config commit.gpgsign true`, { cwd });
```
Comment (viceice) [inline lib/util/git/private-key.ts:40]: @rarkins Shouldn't we simply set this with `--global` ? So it's written to user home, as the key is imported to user home too. 🤔

Comment (onsails) [reply lib/util/git/private-key.ts:40]: > @rarkins Shouldn't we simply set this with `--global` ? So it's written to user home, as the key is imported to user home too. 🤔

while `commit.gpgsign` can't do much harm but `user.signingkey` being set to `keyId` provided specifically to renovate can override global `user.signingkey` which may be different.

**Review by rarkins — APPROVED** [review]
