### PR TITLE
fix(npm): fix detecting logic of npmClient

### LINKED ISSUE #4129: When set `npmClient: "npm"` in lerna.json, throw Unsupported URL Type "network:": network:31879
**What Renovate type are you using?**
Renovate CLI and Renovate GitHub App.

**Describe the bug**

Renovatebot misidentify `lernaClient`.

https://github.com/renovatebot/renovate/blob/f334c568a5039f88f72fb99ee25410a19ffbe501/lib/manager/npm/extract/index.js#L134

When set `"npmClient": "npm"` in `lerna.json`, renovatebot identify `lernaClient` as `yarn`.

As as results, renovatebot invoke npm with unknown options like `--mutex network:31879` and throw foolowing errors.

```

lerna ERR! Error: Command failed: npm install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879
lerna ERR! npm ERR! code EUNSUPPORTEDPROTOCOL
lerna ERR! npm ERR! Unsupported URL Type "network:": network:31879
```

**Did you see anything helpful in debug logs?**
```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning jest > jest-cli > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
lerna info version 2.9.0
lerna info Bootstrapping 3 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879
lerna ERR! npm ERR! code EUNSUPPORTEDPROTOCOL
lerna ERR! npm ERR! Unsupported URL Type "network:": network:31879
lerna ERR! 
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /tmp/renovate-cache/others/npm/_logs/2019-07-05T06_56_27_106Z-debug.log
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/home/ubuntu/.npm/lerna@2.9.0/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
{ Error: Command failed: npm install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "network:": network:31879
```

This is example Pull Request.

https://github.com/azu/npm-lerna-renovatebot-test_2/pull/7

**To Reproduce**

Reproduce repository: https://github.com/azu/npm-lerna-renovatebot-test_2

1.  Set `"npmClient": "npm"` in `lerna.json`
2.  Run renovatebot

**Expected behavior**

Identify `lernaClient` as npm.
Install the dependencies npm + lerna.

**Screenshots**

**Additional context**

Workaround:

- Delete `npmClient` from `lerna.json`

Because, `npmClient` is `npm` by default.

### PR DESCRIPTION
**Pull request by azu**
if `lernaClient: "npm"` is defined, `lernaClient` should be `"npm"`.

Closes #4129

### CODE REVIEW

File: lib/manager/npm/extract/index.js [hunk 1]
```diff
@@ -131,7 +131,8 @@ async function extractPackageFile(content, fileName, config) {
   if (lernaJson) {
     lernaDir = path.dirname(fileName);
     lernaPackages = lernaJson.packages;
-    lernaClient = lernaJson.npmClient || lockFiles.yarnLock ? 'yarn' : 'npm';
+    lernaClient =
```
Comment (azu) [inline lib/manager/npm/extract/index.js]: > npmClient: an option to specify a specific client to run commands with (this can also be specified on a per command basis). Change to "yarn" to run all commands with yarn. Defaults to "npm".
> https://github.com/lerna/lerna#lernajson

File: test/manager/npm/extract/__snapshots__/index.spec.js.snap [hunk 2]
```diff
@@ -337,6 +337,200 @@ Object {
...
+    Object {
+      "currentValue": "4.0.0-beta.1",
+      "datasource": "npm",
+      "depName": "@angular/core",
+      "depType": "devDependencies",
+      "prettyDepType": "devDependency",
+    },
+  ],
+  "ignoreNpmrcFile": undefined,
+  "lernaClient": "npm",
```
Comment (azu) [inline test/manager/npm/extract/__snapshots__/index.spec.js.snap]: `{ "npmClient": "npm" }`

File: test/manager/npm/extract/__snapshots__/index.spec.js.snap [hunk 3]
```diff
@@ -337,6 +337,200 @@ Object {
...
+    Object {
+      "currentValue": "4.0.0-beta.1",
+      "datasource": "npm",
+      "depName": "@angular/core",
+      "depType": "devDependencies",
+      "prettyDepType": "devDependency",
+    },
+  ],
+  "ignoreNpmrcFile": undefined,
+  "lernaClient": "yarn",
```
Comment (azu) [inline test/manager/npm/extract/__snapshots__/index.spec.js.snap]: `{ "npmClient": "yarn" }`

**Comment by rarkins** [comment]
Thank you for the fix!
