### PR TITLE
fix: populate isLockFileMaintenance

### LINKED ISSUE #9728: Find the cause why `config.isLockFileMaintenance` is not working as expected
we need to find the cause why  is not working as expected.

Your pr is a workaround and not a fix for the root cause.

_Originally posted by @viceice in https://github.com/renovatebot/renovate/issues/9695#issuecomment-826870270_

### PR DESCRIPTION
**Pull request by msw-kialo**
## Changes:

Lock file maintenance was broken as various managers rely on the
`isLockFileMaintenance` update flag to be set. This was not the
case as its config is generated afterwards (without the is*
auto-propagation).

## Context:

Fixes #9728

It restores the lock file maintenance feature for the `pip-compile` manager (it didn't fail but wouldn't report updates). Verified on a real repository. Based on a code search I suspect that at least the manager `bundler`, `composer`, `jsonnet-bundler`, `pipenv` are affected, too.

It would allow reverting #9695, and maybe refactoring other managers to use `isLockFileMaintenance` instead of `config.updateType === 'lockFileMaintenance'`. I can include that in this PR if wanted.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository (with `pip-compile`)

### CODE REVIEW

File: lib/workers/repository/updates/flatten.ts [hunk 1]
```diff
@@ -140,6 +140,7 @@ export async function flattenUpdates(
           packageFileConfig.lockFileMaintenance
         );
         lockFileConfig.updateType = 'lockFileMaintenance';
+        lockFileConfig.isLockFileMaintenance = true;
```
Comment (viceice) [inline lib/workers/repository/updates/flatten.ts:143]: @rarkins do we like it? It's probably easier for templates, but I like to reduce the computed properties. We really should fix our typings to catch those errors.

Comment (rarkins) [reply lib/workers/repository/updates/flatten.ts:143]: I think is good for now

**Review by rarkins — APPROVED** [review]
