### PR TITLE
fix(gradle): gradle wrapper execution files updates

### LINKED ISSUE #3565: Gradle wrapper upgrade should update more files
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

The upgrade of gradle is incomplete. It only updates the version in gradle/wrapper/gradle-wrapper.properties (see for example https://github.com/Ninja-Squad/globe42/pull/663/files, which upgrades from 5.3.1 to 5.4).
However, if I do the upgrade manually by following the procedure documented in the [Gradle release notes](https://docs.gradle.org/5.4/release-notes.html#upgrade-instructions):

    ./gradlew wrapper --gradle-version=5.4

then not only this URL is changed, but the generated gradlew and gradlew.bat files, and the binary wrapper jar files are being modified. See https://github.com/Ninja-Squad/globe42/pull/665/files for the same upgrade doing it by applying the correct upgrade procedure.

Renovate should apply the correct procedure instead of just changing the version.

**Expected behavior**

I expect renovate to produce the same changes as if I executed

    ./gradlew wrapper --gradle-version=5.4

### PR DESCRIPTION
**Pull request by driver733**
Closes #3565

### CODE REVIEW

**Comment by driver733** [comment]
@viceice The build (`yarn test`) runs fine on my local machine (macOS).
Can you take a look at this strange problem happening with the linux build on CI?
Screenshot 2020-04-01 at 01 06 50

**Comment by driver733** [comment]
@viceice The build (`yarn test`) runs fine on my local machine(macOS Catalina), but fails on `macos-latest` CI. Can you take a look?

**Comment by viceice** [comment]
Java install is skipped on mac, so skip gradle tests or install java

**Comment by driver733** [comment]
@viceice Can you enable the `Set up Java` command in the CI?
Screenshot 2020-04-01 at 11 09 14

File: .gitattributes [hunk 1]
```diff
@@ -1 +1,2 @@
 * text=auto eol=lf
+gradlew.bat text eol=crlf
```
Comment (viceice) [inline .gitattributes:2]:
```suggestion
*.bat text eol=crlf
```

File: .gitignore [hunk 2]
```diff
@@ -15,6 +15,7 @@ renovate-0.0.0-semantic-release.tgz
 junit.xml
 /test-results
 renovate-schema.json
+**/*/.gradle
```
Comment (viceice) [inline .gitignore:18]: Please be more precise

**Review by viceice — CHANGES_REQUESTED** [review]
Please skip gradle test if `process.env.SKIP_JAVA_TESTS==='true'`

https://github.com/renovatebot/renovate/blob/master/lib/manager/gradle/__testutil__/gradle.ts#L10
https://github.com/renovatebot/renovate/blob/master/lib/manager/gradle/gradle-updates-report.spec.ts#L23

File: .gitignore (hunk 2 above)
Comment (driver733) [reply .gitignore:18]: fixed

**Review by viceice — CHANGES_REQUESTED** [review]
Test needs fix

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+  packageFileName,
+  updatedDeps,
+  newPackageFileContent,
+  config,
+}: UpdateArtifact): Promise<UpdateArtifactsResult[] | null> {
+  try {
+    const projectDir = resolve(packageFileName, './../../../');
+    logger.debug(updatedDeps, 'gradle-wrapper.updateArtifacts()');
+    const gradlewPath = resolve(projectDir, `./${gradlewFilename}`);
+    const version = VERSION_REGEX.exec(newPackageFileContent).groups.version;
```
Comment (viceice) [inline lib/manager/gradle-wrapper/artifacts.ts:39]: Isn't the version already available in `updatedDeps`?

Comment (driver733) [reply lib/manager/gradle-wrapper/artifacts.ts:39]: AFAIK, the `updatedDeps` contains only the names of the updated dependencies.

**Review by viceice — CHANGES_REQUESTED** [review]
Soory, forgot to mentions that we need to add docker compatibillity. see below for invoking gradle with docker

https://github.com/renovatebot/renovate/blob/a1c14f02d11d771532e55601bd9d640f1f8a93f5/lib/manager/gradle/index.ts#L34-L100

**Review by viceice — APPROVED** [review]
LGTM, looks like github has some trouble with the macos workers. So wee need to wait and hope it will be resolved tomorrow.

**Comment by driver733** [comment]
@viceice One `macos` build got cancelled due to the timeout. I guess increasing the timeout of the total build time can fix this problem.

**Comment by viceice** [comment]
see #5851

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+}
+
+export async function updateArtifacts({
+  packageFileName,
+  updatedDeps,
+  newPackageFileContent,
+  config,
+}: UpdateArtifact): Promise<UpdateArtifactsResult[] | null> {
+  try {
+    const projectDir = resolve(packageFileName, './../../../');
```
Comment (rarkins) [inline lib/manager/gradle-wrapper/artifacts.ts:35]: How do we know that this is the project directory?

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+      docker: {
+        image: 'renovate/gradle',
+      },
+    };
+    try {
+      await exec(cmd, execOptions);
+    } catch (err) /* istanbul ignore next */ {
+      logger.warn(
+        { err },
+        'Error executing gradle wrapper update command. It can be not a critical one though.'
```
Comment (rarkins) [inline lib/manager/gradle-wrapper/artifacts.ts:60]: Is it better to warn, or to treat this as an "artifacts error" like other managers?

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+  packageFileName,
+  updatedDeps,
+  newPackageFileContent,
+  config,
+}: UpdateArtifact): Promise<UpdateArtifactsResult[] | null> {
+  try {
+    const projectDir = resolve(packageFileName, './../../../');
+    logger.debug(updatedDeps, 'gradle-wrapper.updateArtifacts()');
+    const gradlewPath = resolve(
+      projectDir,
```
Comment (viceice) [inline lib/manager/gradle-wrapper/artifacts.ts:38]:
```suggestion
      config.localDir,
```

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 7]
```diff
@@ -0,0 +1,82 @@
...
+      `./${gradleWrapperFileName(config)}`
+    );
+    const version = VERSION_REGEX.exec(newPackageFileContent).groups.version;
+    prepareGradleCommand(
+      gradleWrapperFileName(config),
+      projectDir,
```
Comment (viceice) [inline lib/manager/gradle-wrapper/artifacts.ts:44]:
```suggestion
      config.localDir,
```

File: lib/manager/gradle-wrapper/artifacts.ts (hunk 4 above)
Comment (viceice) [reply lib/manager/gradle-wrapper/artifacts.ts:35]:
```suggestion
```
`config.localDir` should be used, cause gradle wrapper should only be in project root?

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 8]
```diff
@@ -0,0 +1,82 @@
...
+      await fs.stat(gradlewPath).catch(() => null),
+      null
+    );
+    const cmd = `${gradlewPath} wrapper --gradle-version ${version} --project-dir ${projectDir}`;
```
Comment (viceice) [inline lib/manager/gradle-wrapper/artifacts.ts:48]:
```suggestion
    const cmd = `${gradlewPath} wrapper --gradle-version ${version}`;
```

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+    logger.debug(`Updating gradle wrapper: "${cmd}"`);
+    const execOptions: ExecOptions = {
+      docker: {
```
Comment (viceice) [inline lib/manager/gradle-wrapper/artifacts.ts:51]:
```suggestion
      cwd: config.localDir,
      docker: {
```

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+        image: 'renovate/gradle',
+      },
+    };
+    try {
+      await exec(cmd, execOptions);
+    } catch (err) /* istanbul ignore next */ {
+      logger.warn(
+        { err },
+        'Error executing gradle wrapper update command. It can be not a critical one though.'
+      );
```
Comment (viceice) [inline lib/manager/gradle-wrapper/artifacts.ts:61]:
```suggestion
     return [
      {
        artifactError: {
          lockFile: packageFileName,
          stderr: err.stderr || err.stdout || err.message,
        },
      },
    ];
```

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/manager/gradle-wrapper/artifacts.ts (hunk 4 above)
Comment (driver733) [reply lib/manager/gradle-wrapper/artifacts.ts]: fixed in https://github.com/renovatebot/renovate/pull/5842/commits/d6aab5cafa8a7ab4f6e2226d6fc7cb260854cf7c

File: lib/manager/gradle-wrapper/artifacts.ts (hunk 5 above)
Comment (driver733) [reply lib/manager/gradle-wrapper/artifacts.ts:61]: We should only warn, because sometimes the execution command exits with a non-zero exit code, although everything was ok. (This happens in windows with `gradlew.bat`).

File: lib/manager/gradle-wrapper/artifacts.ts (hunk 7 above)
Comment (driver733) [reply lib/manager/gradle-wrapper/artifacts.ts:44]: fixed in https://github.com/renovatebot/renovate/pull/5842/commits/d6aab5cafa8a7ab4f6e2226d6fc7cb260854cf7c

File: lib/manager/gradle-wrapper/artifacts.ts (hunk 6 above)
Comment (driver733) [reply lib/manager/gradle-wrapper/artifacts.ts:38]: fixed in https://github.com/renovatebot/renovate/pull/5842/commits/d6aab5cafa8a7ab4f6e2226d6fc7cb260854cf7c

File: lib/manager/gradle-wrapper/artifacts.ts (hunk 10 above)
Comment (driver733) [reply lib/manager/gradle-wrapper/artifacts.ts:62]: see my comment [here](https://github.com/renovatebot/renovate/pull/5842#discussion_r402130319)

File: lib/manager/gradle-wrapper/artifacts.ts (hunk 8 above)
Comment (driver733) [reply lib/manager/gradle-wrapper/artifacts.ts:48]: `--project-dir ${projectDir}` must be present. Otherwise, gradle updates (or adds) gradle wrapper execution files to the root git repo folder. Try to remove this parameter locally and you'll see that.

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 11]
```diff
@@ -0,0 +1,83 @@
...
+      `./${gradleWrapperFileName(config)}`
+    );
+    const version = VERSION_REGEX.exec(newPackageFileContent).groups.version;
+    await prepareGradleCommand(
+      gradleWrapperFileName(config),
+      projectDir,
+      await fs.stat(gradlewPath).catch(() => null),
+      null
+    );
+    const cmd = `${gradlewPath} wrapper --gradle-version ${version} --project-dir ${projectDir}`;
```
Comment (rarkins) [inline lib/manager/gradle-wrapper/artifacts.ts:48]: Have you verified that this behaves as expected if the gradle wrapper file has already been updated to the latest version? i.e. if the `updateDependency()` function updates the version already and then this wrapper command is found, does it continue to install/update the additional files, or does it abort because it thinks the file has already been updated?

File: lib/manager/gradle-wrapper/artifacts.ts [hunk 12]
```diff
@@ -0,0 +1,83 @@
...
+        ].map(async filePath => addIfUpdated(status, filePath))
+      )
+    ).filter(e => e != null);
+    logger.debug(
+      `Returning updated gradle-wrapper files: ${updateArtifactsResult}`
+    );
+    return updateArtifactsResult;
+  } catch (err) {
+    logger.debug({ err }, 'Error setting new Gradle Wrapper release value');
+    return null;
```
Comment (rarkins) [inline lib/manager/gradle-wrapper/artifacts.ts:81]: Shouldn't we return artifact errors so they can be displayed in the PR?

File: lib/manager/gradle-wrapper/artifacts.ts (hunk 11 above)
Comment (driver733) [reply lib/manager/gradle-wrapper/artifacts.ts:48]: It works correctly. I have verified that with [tests](https://github.com/renovatebot/renovate/pull/5842/files#diff-b92414beacaefed9b1be945bafddf048R34).

File: lib/manager/gradle-wrapper/artifacts.ts (hunk 12 above)
Comment (driver733) [reply lib/manager/gradle-wrapper/artifacts.ts]: fixed in https://github.com/renovatebot/renovate/pull/5842/commits/bf0ee40e5a50f72e6e586d90ecab0caa9a002e41
