### PR TITLE
fix: bitbucket inactive reviewers

### LINKED ISSUE #10700: Bitbucket Cloud - Updating existing PRs with deactivated reviewers causes HTTP 400
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [x] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: 25.52.1 at time of report (always pulls latest released version)

**Describe the bug**

We have been seeing the below error throughout our `renovate-bot` logs recently.  

We have triaged this down to the following situation:
* Renovate creates the initial branches and PRs, assigning the default reviewers for that repository
* After this, one of the default reviewers Bitbucket Cloud user account has been `deactivated` as part of their employment offboarding
* Any subsequent run of Renovate tries to update the existing branches and PRs
* Renovate errors out with a `mailformed reviewers list` HTTP 400 error as shown in the below excerpt

If I go through and manually remove the deactivated user from the PRs, then renovate will run successfully on its next run.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
         "message": "Response code 400 (Bad Request)",
         "stack": "HTTPError: Response code 400 (Bad Request)\n    at Request.<anonymous> (/root/.npm/_npx/05eeecd92f4e18e0/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/25.52.1 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/json",
             "content-type": "application/json",
             "content-length": "6709",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://api.bitbucket.org/2.0/repositories/{org}/{repo}/pullrequests/18",
           "username": "",
           "password": "",
           "method": "PUT",
           "http2": false
         },
         "response": {
           "statusCode": 400,
           "statusMessage": "Bad Request",
           "body": {
             "type": "error",
             "error": {
               "fields": {"reviewers": ["Malformed reviewers list"]},
               "message": "reviewers: Malformed reviewers list"
             }
           },
```

</details>

**Have you created a minimal reproduction repository?**

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Our shared default configuration (local preset)

<details><summary>Click to see local default config</summary>

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    "schedule:nonOfficeHours",
    "group:definitelyTyped",
    "group:linters",
    "github>whitesource/merge-confidence:beta",
    ":prConcurrentLimit10"
  ],
  "packageRules": [
    {
      "matchUpdateTypes": ["patch", "pin", "digest"],
      "automerge": true
    }
  ],
  "automergeType": "branch",
  "separateMinorPatch": true,
  "separateMultipleMajor": true
}
```

</details>

### PR DESCRIPTION
**Pull request by setchy**
## Changes:

Previously, when updating an existing pull request in Bitbucket Cloud, if any of the reviewers have since been deactivated (offboarded) the PR Update would fail.

Now, the existing PR reviewers are each validated to confirm their account is still `active`

## Context:

Closes #10700

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by setchy** [comment]
@rarkins - any additional feedback on this PR?

File: lib/platform/bitbucket/index.ts [hunk 1]
```diff
@@ -712,16 +712,50 @@ export async function updatePr({
...
+      }
+    );
+  } catch (err) /* istanbul ignore next */ {
+    logger.warn({ err }, 'PR contains inactive reviewer accounts.  Will try setting only active reviewers');
+
+    // Bitbucket returns a 400 if any of the PR reviewer accounts are now inactive (ie: disabled/suspended)
+    let activeReviewers: Array<any> = new Array();
+
+    // Validate that each previous PR reviewer account is still active
+    pr.reviewers.forEach(async (reviewer, index) => {
```
Comment (viceice) [inline lib/platform/bitbucket/index.ts:733]: This won't work, as the forEach won't wait for the async callbacks.

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/platform/bitbucket/index.ts (hunk 1 above)
Comment (setchy) [reply lib/platform/bitbucket/index.ts]: thx - replaced with a for...of Loop

File: lib/platform/bitbucket/index.ts [hunk 2]
```diff
@@ -712,16 +717,50 @@ export async function updatePr({
...
+      }
+    );
+  } catch (err) /* istanbul ignore next */ {
+    logger.warn(
+      { err },
+      'PR contains inactive reviewer accounts.  Will try setting only active reviewers'
+    );
+
+    // Bitbucket returns a 400 if any of the PR reviewer accounts are now inactive (ie: disabled/suspended)
+    let activeReviewers: Array<any> = new Array();
```
Comment (viceice) [inline lib/platform/bitbucket/index.ts:738]:
```suggestion
    const activeReviewers: UserResponse[] = [];
```

File: lib/platform/bitbucket/index.ts [hunk 3]
```diff
@@ -712,16 +717,50 @@ export async function updatePr({
...
+      {
+        body: {
+          title,
+          description: sanitize(description),
+          reviewers: pr.reviewers,
+        },
+      }
+    );
+  } catch (err) /* istanbul ignore next */ {
+    logger.warn(
```
Comment (viceice) [inline lib/platform/bitbucket/index.ts:732]: Can we check the response for the reviewer specific error message? So we only retry if it's because of disabled reviewers?

Comment (setchy) [reply lib/platform/bitbucket/index.ts:732]: We can.  The error response I've observed in our logs is along these lines

```
"response": {
    "statusCode": 400,
    "statusMessage": "Bad Request",
    "body": {
        "type": "error",
        "error": {
            "fields": {"reviewers": ["Malformed reviewers list"]},
            "message": "reviewers: Malformed reviewers list"
        }
    },
    ...
}
```

Comment (setchy) [reply lib/platform/bitbucket/index.ts]: Added a check for the `reviewers: Malformed reviewers list` bitbucket error

File: lib/platform/bitbucket/index.ts [hunk 4]
```diff
@@ -712,16 +717,57 @@ export async function updatePr({
...
+        {
+          body: {
+            title,
+            description: sanitize(description),
+            reviewers: activeReviewers,
+          },
+        }
+      );
+    } else {
+      logger.debug({ err }, 'Unknown error updating Bitbucket pull request');
```
Comment (viceice) [inline lib/platform/bitbucket/index.ts:768]:
```suggestion
      throw err;
```
Simply rethrow the original error.

Can you check what other platforms do on error?

**Comment by setchy** [comment]
@rarkins @viceice - any further feedback - I believe I've addressed all the items (though [this](https://github.com/renovatebot/renovate/pull/11834#discussion_r717480932) is still showing as unresolved, but is 🤷)

File: lib/platform/bitbucket/index.ts [hunk 5]
```diff
@@ -712,16 +717,57 @@ export async function updatePr({
...
+      `/2.0/repositories/${config.repository}/pullrequests/${prNo}`,
+      {
+        body: {
+          title,
+          description: sanitize(description),
+          reviewers: pr.reviewers,
+        },
+      }
+    );
+  } catch (err) /* istanbul ignore next */ {
```
Comment (rarkins) [inline lib/platform/bitbucket/index.ts:731]:
```suggestion
  } catch (err) {
```

This is important functionality, so can it be tested?

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/platform/bitbucket/index.ts (hunk 5 above)
Comment (viceice) [reply lib/platform/bitbucket/index.ts:731]: Yeah, couldn't post my suggestion with app earlier today.

Comment (setchy) [reply lib/platform/bitbucket/index.ts]: Tests added.  @rarkins - would you mind kicking off `2 workflows awaiting approval` as I'm a first time contributor

**Review by viceice — DISMISSED** [review]

**Review by viceice — COMMENTED** [review]
Needs snapshot updates

**Comment by setchy** [comment]
> Needs snapshot updates

apologies - resolved now, i think 😅

File: lib/datasource/artifactory/__snapshots__/index.spec.ts.snap [hunk 6]
```diff
@@ -5,19 +5,19 @@ Object {
   "registryUrl": "https://jfrog.company.com/artifactory",
   "releases": Array [
     Object {
-      "releaseTimestamp": "2021-07-21T20:08:00.000Z",
+      "releaseTimestamp": "2021-07-22T00:08:00.000Z",
```
Comment (viceice) [inline lib/datasource/artifactory/__snapshots__/index.spec.ts.snap:8]: These changes looks wrong to me.

Comment (setchy) [reply lib/datasource/artifactory/__snapshots__/index.spec.ts.snap:8]: That was the result of `npm run jest -- -u`.  I'm happy to revert changes to this file

Comment (rarkins) [reply lib/datasource/artifactory/__snapshots__/index.spec.ts.snap]: Ideally we don't have any timestamps, but if we do then they don't change. Will people running `jest` locally end up with this test failing?

Comment (viceice) [reply lib/datasource/artifactory/__snapshots__/index.spec.ts.snap]: Those shouldn't changes, as they are coming from fixtures. Looks like we have a timezone issue in artifactory

Comment (setchy) [reply lib/datasource/artifactory/__snapshots__/index.spec.ts.snap]: I was able to recreate the above snapshot timestamp discrepancy on `main`

Running `npm run test` works as committed. 

Running `npm run jest` produces an update to the artifactory snapshot.

In either case, I have reverted this change and only updated the bitbucket snapshot associated with my changes

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
