### PR TITLE
fix(platform/github): dryrun skip autoclosed prs reopening

### LINKED ISSUE #15697: Seems like dryRun is ignored for opening autoclosed PRs
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.36.0

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

3.3.5

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

It seems like RENOVATE_DRY_RUN is ignored when determining if an autoclosed PR should be reopened.
I imagine it originates from here.
https://github.com/renovatebot/renovate/blob/ef470f7f923a4c03e4c6204094dd508f0a4eef96/lib/modules/platform/github/index.ts#L668
I would expect that it should have logged something like 
`DRY-RUN: Would reopen autoclosed PR` or some such` but it seems there's no such logic.
So I had a renovate validation run end up opening a bunch of closed PRs in a repo.

And It was indeed running in dry run mode since I had tons of dry-run prints like
`DRY-RUN: Would autoclose PR`
next to it printing this for other PRs `Successfully reopened autoclosed PR` 

We use dry run when updating the renovate version to ensure everything seems to behave correctly. It's not ideal that it makes modifications to the repo when in dry-run.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by Gabriel-Ladzaretti**
- init commit

## Changes
Skip reopening of autoclosed prs when in dry mode

## Context
closes #15697

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/platform/github/index.ts [hunk 1]
```diff
@@ -655,14 +656,20 @@ export async function getBranchPr(branchName: string): Promise<Pr | null> {
     autoclosedPr?.title?.endsWith(' - autoclosed') &&
     autoclosedPr?.closedAt
   ) {
-    const closedMillisAgo = DateTime.fromISO(autoclosedPr.closedAt)
+    const closedMillisAgo = DateTime.fromISO(autoclosedPr.closedAt, {
+      zone: 'utc',
```
Comment (rarkins) [inline lib/modules/platform/github/index.ts:660]: Is this related to the current problem, or just something you fixed at the same time? And is it a fix - i.e. something wasn't working before, including tests - or just more robust code?

Comment (Gabriel-Ladzaretti) [reply lib/modules/platform/github/index.ts:660]: was supposed to be the later one, but actually it is not needed.
`toMillis` is millis since epoch which is already utc. 
ill revert this

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
