### PR TITLE
fix(manager): unify logging

### LINKED ISSUE #19696: [helm-values manager]: YAMLException not showing what file the issue is occuring with
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v34.83.1

### If you're self-hosting Renovate, select which platform you are using.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

There seems to be a bug or a feature? That when a YAMLException is thrown when failing to parse, it will not tell you where it occured, like what file is the issue.

I believe that this is a bug due to it not showing which file it complains about.

Public Action Run: https://github.com/samip5/k8s-cluster/actions/runs/3853014276/jobs/6565613817

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Failed to parse helm-values YAML (repository=samip5/k8s-cluster)
       "err": {
         "name": "YAMLException",
         "reason": "expected a single document in the stream, but found more",
         "message": "expected a single document in the stream, but found more",
         "stack": "YAMLException: expected a single document in the stream, but found more\n    at load (/opt/buildpack/tools/renovate/34.83.1/node_modules/js-yaml/lib/loader.js:1722:9)\n    at Object.extractPackageFile (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/modules/manager/helm-values/extract.ts:66:25)\n    at extractPackageFile (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/modules/manager/index.ts:70:9)\n    at getManagerPackageFiles (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:52:43)\n    at /opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/extract/index.ts:47:28\n    at async Promise.all (index 4)\n    at extractAllDependencies (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/extract/index.ts:45:26)\n    at extract (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/process/extract-update.ts:117:20)\n    at extractDependencies (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/process/index.ts:120:26)\n    at Object.renovateRepository (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/index.ts:49:52)\n    at attributes.repository (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/global/index.ts:181:11)\n    at start (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/global/index.ts:166:7)\n    at /opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/renovate.ts:18:22"
       }
DEBUG: Failed to parse helm-values YAML (repository=samip5/k8s-cluster)
       "err": {
         "name": "YAMLException",
         "reason": "expected a single document in the stream, but found more",
         "message": "expected a single document in the stream, but found more",
         "stack": "YAMLException: expected a single document in the stream, but found more\n    at load (/opt/buildpack/tools/renovate/34.83.1/node_modules/js-yaml/lib/loader.js:1722:9)\n    at Object.extractPackageFile (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/modules/manager/helm-values/extract.ts:66:25)\n    at extractPackageFile (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/modules/manager/index.ts:70:9)\n    at getManagerPackageFiles (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:52:43)\n    at /opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/extract/index.ts:47:28\n    at async Promise.all (index 4)\n    at extractAllDependencies (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/extract/index.ts:45:26)\n    at extract (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/process/extract-update.ts:117:20)\n    at extractDependencies (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/process/index.ts:120:26)\n    at Object.renovateRepository (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/repository/index.ts:49:52)\n    at attributes.repository (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/global/index.ts:181:11)\n    at start (/opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/workers/global/index.ts:166:7)\n    at /opt/buildpack/tools/renovate/34.83.1/node_modules/renovate/lib/renovate.ts:18:22"
       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by viceice**
## Changes
Unify parser error logging for allmost all managers.
- log `packageFile` on errors
- rename `fileName` to `packageFile`
- reduce warning to debug (was inconsistent before), maybe we should change all to warn, so users are more aware of parsing issues?

## Context
- closes #19696

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/ansible-galaxy/extract.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ export function extractPackageFile(
     }
     return { deps };
   } catch (err) /* istanbul ignore next */ {
-    logger.debug({ err }, 'Error extracting ansible-galaxy deps');
+    logger.debug({ err, packageFile }, 'Error extracting ansible-galaxy deps');
```
Comment (viceice) [inline lib/modules/manager/ansible-galaxy/extract.ts:90]: @rarkins @secustor @JamieMagee Should we warn instead to make those errors more visible on dashboard? As those errors are mostly caused by wrong config or invalid files.

Comment (rarkins) [reply lib/modules/manager/ansible-galaxy/extract.ts:90]: There's some cases where it's probably worthwhile, but others where it's probably just noise. No single answer

File: lib/modules/manager/buildkite/extract.ts [hunk 2]
```diff
@@ -5,7 +5,10 @@ import { GithubTagsDatasource } from '../../datasource/github-tags';
 import { isVersion } from '../../versioning/semver';
 import type { PackageDependency, PackageFileContent } from '../types';
 
-export function extractPackageFile(content: string): PackageFileContent | null {
+export function extractPackageFile(
+  content: string,
+  packageFile?: string
```
Comment (rarkins) [inline lib/modules/manager/buildkite/extract.ts:10]:
```suggestion
  packageFile: string
```

Can it really be undefined? Or only in tests?

File: lib/modules/manager/bundler/extract.ts [hunk 3]
```diff
@@ -14,7 +14,7 @@ function formatContent(input: string): string {
 
 export async function extractPackageFile(
   content: string,
-  fileName?: string
+  packageFile?: string
```
Comment (rarkins) [inline lib/modules/manager/bundler/extract.ts:17]: Optional due to tests?

**Review by rarkins — CHANGES_REQUESTED** [review]
Are the optional `packageFile?` params due to tests?

File: lib/modules/manager/ansible-galaxy/extract.ts (hunk 1 above)
Comment (viceice) [reply lib/modules/manager/ansible-galaxy/extract.ts:90]: so I would prefer to always only debug log as I've done it here

File: lib/modules/manager/buildkite/extract.ts (hunk 2 above)
Comment (viceice) [reply lib/modules/manager/buildkite/extract.ts:10]: yes, because of tests. making them not optional will cause a lot more changes in tests. i can fix that in follow up PR's.

File: lib/modules/manager/bundler/extract.ts (hunk 3 above)
Comment (viceice) [reply lib/modules/manager/bundler/extract.ts:17]: yes

File: lib/modules/manager/azure-pipelines/extract.ts [hunk 4]
```diff
@@ -116,12 +116,12 @@ export function parseAzurePipelines(
 
 export function extractPackageFile(
   content: string,
-  filename: string
+  packageFile: string
 ): PackageFileContent | null {
-  logger.trace(`azurePipelines.extractPackageFile(${filename})`);
+  logger.trace(`azurePipelines.extractPackageFile(${packageFile})`);
```
[the remark this answers is not in the document]
Comment (viceice) [reply lib/modules/manager/azure-pipelines/extract.ts:121]: sure, but separate PR

**Comment by viceice** [comment]
fixing the optional package file would cause the  PR to become at least four times more changes and double of changed files.

so I would prefer to do those changes in follow up PR's.

also lifting the trace call at beginning of the extract is a good idea for a separate PR.

**Review by secustor — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
