### PR TITLE
fix: Improve the default User-agent string.

### LINKED ISSUE #5710: Set user agent string based on renovate version
It would be nice if Renovate's http requests could include a user agent string that includes its *own version*. e.g. learning this from `package.json` if it can find it.

### PR DESCRIPTION
**Pull request by nielsbasjes**
## Changes:

Change the default user-agent request header to something that conforms to what this header normally looks like.

## Context:

I'm the author of https://yauaa.basjes.nl/ which is intended to analyze the user-agent string.

The current value of the user-agent request header of Renovate is just the github url of the project which does not conform to common conventions and standards.

This change makes this header conform much better to the conventions and what is described in the RFC  https://datatracker.ietf.org/doc/html/rfc7231#section-5.5.3 

This change proposes to change the default string to: `RenovateBot/25.50.0 (https://github.com/renovatebot/renovate)`

It is still possible to override the value if so desired.

- closes #5710

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

One of the messages in my test run showed:
```json
"user-agent": "RenovateBot/0.0.0-semantic-release (https://github.com/renovatebot/renovate)",
```

### CODE REVIEW

File: lib/util/http/index.ts [hunk 1]
```diff
@@ -54,11 +54,18 @@ function cloneResponse<T>(response: any): HttpResponse<T> {
 
 function applyDefaultHeaders(options: Options): void {
   // eslint-disable-next-line no-param-reassign
```
Comment (viceice) [inline lib/util/http/index.ts:56]:
```suggestion
```

File: lib/util/http/index.ts [hunk 2]
```diff
@@ -54,11 +54,18 @@ function cloneResponse<T>(response: any): HttpResponse<T> {
...
+  let renovateVersion = 'unknown';
+  try {
+    // eslint-disable-next-line @typescript-eslint/no-var-requires
+    renovateVersion = require('../../../package.json').version; // eslint-disable-line global-require
+  } catch (err) /* istanbul ignore next */ {
+    logger.debug({ err }, 'Error getting renovate version');
+  }
   options.headers = {
```
Comment (viceice) [inline lib/util/http/index.ts:64]:
```suggestion
  // eslint-disable-next-line no-param-reassign
  options.headers = {
```

**Review by viceice — CHANGES_REQUESTED** [review]
Needs snapshot updates, run `yarn jest -u`

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
