### PR TITLE
fix(npm): avoid transitive remediation of bundled dependencies

### LINKED ISSUE #13977: Renovate is stuck in a loop making changes to our NPM lockfile
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Renovate is continuously making changes to our NPM lockfile by 1) moving a specific dependency up and then later 2) moving it down the dependency tree again, and then moving it up again and continuing in a loop.

We have now accumulated over 10 of these commits, and I expect there are more to come.

See repository https://github.com/capralifecycle/webapp-deploy-lambda for an example.

### Relevant debug logs

_No response_

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Skips transitive remediation if the dependency is bundled.

## Context:

Fixes #13977

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/manager/npm/update/locked-dependency/package-lock/index.ts [hunk 1]
```diff
@@ -47,6 +47,12 @@ export async function updateLockedDependency(
       depName,
       currentVersion
     );
+    if (lockedDeps.some((dep) => dep.bundled)) {
```
Comment (viceice) [inline lib/manager/npm/update/locked-dependency/package-lock/index.ts:50]: Shouldn't we just filter bundled and update not bundled?

**Review by viceice — COMMENTED** [review]
Otherwise LGTM

File: lib/manager/npm/update/locked-dependency/package-lock/index.ts (hunk 1 above)
Comment (rarkins) [reply lib/manager/npm/update/locked-dependency/package-lock/index.ts:50]: Scenario:
- the vulnerable version is found twice
- one is bundled and the other is unbundled
- per your suggestion, we filter out the bundled version and only remediate the unbundled
- we raise a PR saying we've remediated the vulnerability
- PR is merged.. but vulnerability (including alert) remains

I don't like this edge case, so prefer to just stop trying

**Review by viceice — APPROVED** [review]
