### PR TITLE
fix: set `allowedHeaders` to `GlobalConfig` before `initPlatform` is invoked

### LINKED ISSUE #26983: hostRules.headers cannot be configured in config.js
### Describe the proposed change(s).

Example failure:

```
DEBUG: File config
       "config": {
         "allowedHeaders": ["abc"],
         "hostRules": [{"headers": {"abc": "def"}}]
       }
...
DEBUG: Setting global hostRules
DEBUG: Using default github endpoint: https://api.github.com/
DEBUG: hostRules: authentication already set for api.github.com
ERROR: Disallowed hostRules headers
       "allowedHeaders": undefined,
       "header": "abc"
```

Meanwhile it does work if the same hostRules is in renovate.json instead of config.js

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
Set `allowedHeaders` to `GlobalConfig` and moved this setting before `globalInitialize` in invoked, so that `allowedHeaders` is configured and available before `initPlatform` in invoked and requests are made.

## Context
Closes: https://github.com/renovatebot/renovate/issues/26983

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or (tested locally)
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/global/index.ts [hunk 1]
```diff
@@ -156,15 +156,18 @@ export async function start(): Promise<number> {
           );
         }
       }
-      // initialize all submodules
-      config = await globalInitialize(config);
 
       // Set platform and endpoint in case local presets are used
+      // Set allowedHeaders in case hostRules headers are configured in file config
       GlobalConfig.set({
```
Comment (viceice) [inline lib/workers/global/index.ts:162]: I think we need to set it twice, because endpoint can be changed from platform init. (eg strip api suffix...)

**Review by viceice — APPROVED** [review]

**Comment by lmarschall** [comment]
Still getting the same error at the end, it seems to work better now, but not as I intended I guess, using the newest version here.

<details open>
  <summary>Logs</summary>
```
[0KRunning with gitlab-runner 13.8.0 (775dd39d)
[0;m[0K  on lxrunner docker J7ky3Fid
[0;msection_start:1712316202:prepare_executor
[0K[0K[36;1mPreparing the "docker" executor[0;m
[0;m[0KUsing Docker executor with image renovate/renovate:37.279.2 ...
[0;m[0KPulling docker image renovate/renovate:37.279.2 ...
[0;m[0KUsing docker image sha256:76d47725757e533d42e3e500eab30bf0d778c0827f98abf8226729d88687aa18 for renovate/renovate:37.279.2 with digest renovate/renovate@sha256:cab7ed82d927d968cdff7da22bb6ea9d26bae6eb6a6c9413cabebcd6c41d2730 ...
[0;msection_end:1712316205:prepare_executor
[0Ksection_start:1712316205:prepare_script
[0K[0K[36;1mPreparing environment[0;m
[0;mRunning on runner-j7ky3fid-project-182-concurrent-0 via lxrunner...
section_end:1712316205:prepare_script
[0Ksection_start:1712316205:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m
[0;m[32;1mFetching changes with git depth set to 20...[0;m
Reinitialized existing Git repository in /builds/it/renovate/.git/
[32;1mChecking out 95a6647e as main...[0;m
Removing renovate/

[32;1mSkipping Git submodules setup[0;m
section_end:1712316206:get_sources
[0Ksection_start:1712316206:restore_cache
[0K[0K[36;1mRestoring cache[0;m
[0;m[32;1mChecking cache for main-renovate-2-protected...[0;m
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted.[0;m 
[32;1mSuccessfully extracted cache[0;m
section_end:1712316207:restore_cache
[0Ksection_start:1712316207:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m
[0;m[32;1m$ renovate $RENOVATE_EXTRA_FLAGS[0;m
DEBUG: Using RE2 regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in config.js
DEBUG: File config
       "config": {
         "endpoint": "https://git.docsinclouds.com/api/v4/",
         "platform": "gitlab",
         "persistRepoData": true,
         "logLevel": "debug",
         "hostRules": [
           {
             "allowedHeaders": ["Authorization"],
             "headers": {"Authorization": "Bearer [MASKED]"}
           },
           {"matchHost": "https://auth.docker.io", "headers": {"Authorization": null}}
         ],
         "repositories": ["161"],
         "onboardingConfig": {"extends": ["renovate/renovate-config"]},
         "autodiscover": false
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {
         "hostRules": [],
         "repositoryCache": "true",
         "baseDir": "/builds/it/renovate/renovate",
         "optimizeForDisabled": true,
         "token": "***********",
         "gitAuthor": "Renovate <renovate@docsinclouds.com>"
       }
DEBUG: Combined config
       "config": {
         "endpoint": "https://git.docsinclouds.com/api/v4/",
         "platform": "gitlab",
         "persistRepoData": true,
         "logLevel": "debug",
         "hostRules": [
           {
             "allowedHeaders": ["Authorization"],
             "headers": {"Authorization": "Bearer [MASKED]"}
           },
           {"matchHost": "https://auth.docker.io", "headers": {"Authorization": null}}
         ],
         "repositories": ["161"],
         "onboardingConfig": {"extends": ["renovate/renovate-config"]},
         "autodiscover": false,
         "repositoryCache": "true",
         "baseDir": "/builds/it/renovate/renovate",
         "optimizeForDisabled": true,
         "token": "***********",
         "gitAuthor": "Renovate <renovate@docsinclouds.com>"
       }
DEBUG: Adding trailing slash to endpoint
DEBUG: Enabling forkProcessing while in non-autodiscover mode
DEBUG: Found valid git version: 2.43.2
DEBUG: Setting global hostRules
DEBUG: hostRules: authentication already set for git.docsinclouds.com
ERROR: Disallowed hostRules headers
       "allowedHeaders": ["X-*"],
       "header": "Authorization"
DEBUG: GitLab version is: 16.9.1
DEBUG: Using configured gitAuthor (Renovate <renovate@docsinclouds.com>)
DEBUG: Adding token authentication for git.docsinclouds.com (hostType=gitlab) to hostRules
DEBUG: Using configured baseDir: /builds/it/renovate/renovate
DEBUG: Using cacheDir: /builds/it/renovate/renovate/cache
DEBUG: Using containerbaseDir: /builds/it/renovate/renovate/cache/containerbase
DEBUG: Initializing Renovate internal cache into /builds/it/renovate/renovate/cache/renovate/renovate-cache-v1
DEBUG: Commits limit = null
DEBUG: Setting global hostRules
DEBUG: Adding token authentication for git.docsinclouds.com (hostType=gitlab) to hostRules
DEBUG: validatePresets()
DEBUG: Reinitializing hostRules for repo
DEBUG: Clearing hostRules
DEBUG: Adding token authentication for git.docsinclouds.com (hostType=gitlab) to hostRules
 INFO: Repository started (repository=161)
       "renovateVersion": "37.279.2"
DEBUG: Using localDir: /builds/it/renovate/renovate/repos/gitlab/161 (repository=161)
DEBUG: PackageFiles.clear() - Package files deleted (repository=161)
DEBUG: hostRules: applying Bearer authentication for git.docsinclouds.com (repository=161)
ERROR: Disallowed hostRules headers (repository=161)
       "allowedHeaders": ["X-*"],
       "header": "Authorization"
DEBUG: 161 default branch = main (repository=161)
DEBUG: Enabling Git FS (repository=161)
DEBUG: Using http URL: https://git.docsinclouds.com/it/monitoring.git (repository=161)
 WARN: File contents are invalid JSON but parse using JSON5. Support for this will be removed in a future release so please change to a support .json5 file name or ensure correct JSON syntax. (repository=161)
       "context": "renovate.json"
DEBUG: Resetting npmrc (repository=161)
DEBUG: Resetting npmrc (repository=161)
DEBUG: checkOnboarding() (repository=161)
DEBUG: isOnboarded() (repository=161)
DEBUG: findPr(renovate/configure, Configure Renovate, !open) (repository=161)
DEBUG: findPr(renovate/configure, chore: Configure Renovate, !open) (repository=161)
DEBUG: findFile(renovate.json) (repository=161)
DEBUG: Initializing git repository into /builds/it/renovate/renovate/repos/gitlab/161 (repository=161)
DEBUG: resetToBranch(main) (repository=161)
DEBUG: resetToBranch(main) (repository=161)
DEBUG:  (repository=161)
       "existingBranches": []
 INFO: git fetch completed (repository=161)
       "durationMs": 2305
DEBUG: latest repository commit (repository=161)
       "latestCommit": {
         "hash": "69428871d4f608644cb165fc7e75382efc30c6d0",
         "date": "2024-04-05T09:41:54+00:00",
         "message": "Update renovate.json5",
         "refs": "HEAD -> main, origin/main, origin/HEAD",
         "body": "",
         "author_name": "Lukas Marschall",
         "author_email": "lmarschall@docsinclouds.com"
       }
DEBUG: Config file exists, fileName: renovate.json (repository=161)
DEBUG: ensureIssueClosing() (repository=161)
DEBUG: Repo is onboarded (repository=161)
DEBUG: Found renovate.json config file (repository=161)
 WARN: File contents are invalid JSON but parse using JSON5. Support for this will be removed in a future release so please change to a support .json5 file name or ensure correct JSON syntax. (repository=161)
       "context": "renovate.json"
DEBUG: Repository config (repository=161)
       "fileName": "renovate.json",
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "gitAuthor": "Renovate Bot <renovate-bot@mycompany.com>",
         "extends": ["config:base"],
         "enabledManagers": ["docker-compose"],
         "packageRules": [
           {"managers": ["docker-compose"], "groupName": "Drupal contributed modules"}
         ]
       }
DEBUG: migrateAndValidate() (repository=161)
DEBUG: Config migration necessary (repository=161)
       "oldConfig": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "gitAuthor": "Renovate Bot <renovate-bot@mycompany.com>",
         "extends": ["config:base"],
         "enabledManagers": ["docker-compose"],
         "packageRules": [
           {"managers": ["docker-compose"], "groupName": "Drupal contributed modules"}
         ]
       },
       "newConfig": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "gitAuthor": "Renovate Bot <renovate-bot@mycompany.com>",
         "extends": ["config:recommended"],
         "enabledManagers": ["docker-compose"],
         "packageRules": [
           {
             "matchManagers": ["docker-compose"],
             "groupName": "Drupal contributed modules"
           }
         ]
       }
DEBUG: Post-massage config (repository=161)
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "gitAuthor": "Renovate Bot <renovate-bot@mycompany.com>",
         "extends": ["config:recommended"],
         "enabledManagers": ["docker-compose"],
         "packageRules": [
           {
             "matchManagers": ["docker-compose"],
             "groupName": "Drupal contributed modules"
           }
         ]
       }
DEBUG: Setting hostRules from config (repository=161)
DEBUG: Found repo ignorePaths (repository=161)
       "ignorePaths": [
         "**/node_modules/**",
         "**/bower_components/**",
         "**/vendor/**",
         "**/examples/**",
         "**/__tests__/**",
         "**/test/**",
         "**/tests/**",
         "**/__fixtures__/**"
       ]
DEBUG: No vulnerability alerts found (repository=161)
DEBUG: findIssue(Dependency Dashboard) (repository=161)
DEBUG: No baseBranches (repository=161)
DEBUG: extract() (repository=161)
DEBUG: Setting current branch to main (repository=161)
DEBUG: latest commit (repository=161)
       "branchName": "main",
       "latestCommitDate": "2024-04-05T09:41:54+00:00"
DEBUG: Using file match: (^|/)(?:docker-)?compose[^/]*\.ya?ml$ for manager docker-compose (repository=161)
DEBUG: Matched 10 file(s) for manager docker-compose: deprecated/grafana/docker-compose.yml, deprecated/rancher/docker-compose.yml, deprecated/rustdesk/docker-compose.yml, deprecated/vaultwarden/docker-compose.yml, deprecated/watchtower/docker-compose.yml, node-exporter/docker-compose.yml, portainer-agent/docker-compose.yml, portainer/docker-compose.yml, prometheus/docker-compose.yml, traefik/docker-compose.yml (repository=161)
DEBUG: docker-compose.extractPackageFile(deprecated/grafana/docker-compose.yml) (repository=161)
DEBUG: docker-compose.extractPackageFile(deprecated/rancher/docker-compose.yml) (repository=161)
DEBUG: docker-compose.extractPackageFile(deprecated/rustdesk/docker-compose.yml) (repository=161)
DEBUG: docker-compose.extractPackageFile(deprecated/vaultwarden/docker-compose.yml) (repository=161)
DEBUG: docker-compose.extractPackageFile(deprecated/watchtower/docker-compose.yml) (repository=161)
DEBUG: docker-compose.extractPackageFile(node-exporter/docker-compose.yml) (repository=161)
DEBUG: docker-compose.extractPackageFile(portainer-agent/docker-compose.yml) (repository=161)
DEBUG: docker-compose.extractPackageFile(portainer/docker-compose.yml) (repository=161)
DEBUG: docker-compose.extractPackageFile(prometheus/docker-compose.yml) (repository=161)
DEBUG: docker-compose.extractPackageFile(traefik/docker-compose.yml) (repository=161)
DEBUG: manager extract durations (ms) (repository=161)
       "managers": {"docker-compose": 25}
DEBUG: Found docker-compose package files (repository=161)
DEBUG: Found 10 package file(s) (repository=161)
 INFO: Dependency extraction complete (repository=161, baseBranch=main)
       "stats": {
         "managers": {"docker-compose": {"fileCount": 10, "depCount": 15}},
         "total": {"fileCount": 10, "depCount": 15}
       }
DEBUG: Dependency rancher/server has unsupported/unversioned value latest (versioning=docker) (repository=161)
DEBUG: Skipping rancher/server because no currentDigest or pinDigests (repository=161)
DEBUG: Dependency rustdesk/rustdesk-server has unsupported/unversioned value latest (versioning=docker) (repository=161)
DEBUG: Skipping rustdesk/rustdesk-server because no currentDigest or pinDigests (repository=161)
DEBUG: Dependency rustdesk/rustdesk-server has unsupported/unversioned value latest (versioning=docker) (repository=161)
DEBUG: Skipping rustdesk/rustdesk-server because no currentDigest or pinDigests (repository=161)
DEBUG: GET https://auth.docker.io/token?scope=repository%3Avaultwarden%2Fserver%3Apull&service=registry.docker.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=500 retryCount=2, duration=298) (repository=161)
 WARN: Retry-After: unexpected status code 500 (repository=161)
       "url": "https://auth.docker.io/token?scope=repository%3Avaultwarden%2Fserver%3Apull&service=registry.docker.io"
 WARN: docker registry failure: internal error (repository=161)
       "registryHost": "https://index.docker.io",
       "dockerRepository": "vaultwarden/server",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316221504,
           "socket": 1712316221505,
           "lookup": 1712316221506,
           "connect": 1712316221601,
           "secureConnect": 1712316221703,
           "upload": 1712316221703,
           "response": 1712316221802,
           "end": 1712316221802,
           "phases": {
             "wait": 1,
             "dns": 1,
             "tcp": 95,
             "tls": 102,
             "request": 0,
             "firstByte": 99,
             "download": 0,
             "total": 298
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Avaultwarden%2Fserver%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:41 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
DEBUG: Aggregate error is thrown (repository=161)
       "err": {
         "name": "AggregateError",
         "message": "\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
         "stack": "AggregateError: \n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    at next (/usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:43:14)\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:67:7\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
DEBUG: GET https://auth.docker.io/token?scope=repository%3Aportainer%2Fagent%3Apull&service=registry.docker.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=500 retryCount=2, duration=385) (repository=161)
 WARN: Retry-After: unexpected status code 500 (repository=161)
       "url": "https://auth.docker.io/token?scope=repository%3Aportainer%2Fagent%3Apull&service=registry.docker.io"
 WARN: docker registry failure: internal error (repository=161)
       "registryHost": "https://index.docker.io",
       "dockerRepository": "portainer/agent",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316221521,
           "socket": 1712316221521,
           "lookup": 1712316221522,
           "connect": 1712316221616,
           "secureConnect": 1712316221719,
           "upload": 1712316221719,
           "response": 1712316221905,
           "end": 1712316221906,
           "phases": {
             "wait": 0,
             "dns": 1,
             "tcp": 94,
             "tls": 103,
             "request": 0,
             "firstByte": 186,
             "download": 1,
             "total": 385
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Aportainer%2Fagent%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:41 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
DEBUG: Aggregate error is thrown (repository=161)
       "err": {
         "name": "AggregateError",
         "message": "\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
         "stack": "AggregateError: \n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    at next (/usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:43:14)\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:67:7\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
DEBUG: GET https://auth.docker.io/token?scope=repository%3Agrafana%2Fgrafana%3Apull&service=registry.docker.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=500 retryCount=2, duration=390) (repository=161)
 WARN: Retry-After: unexpected status code 500 (repository=161)
       "url": "https://auth.docker.io/token?scope=repository%3Agrafana%2Fgrafana%3Apull&service=registry.docker.io"
 WARN: docker registry failure: internal error (repository=161)
       "registryHost": "https://index.docker.io",
       "dockerRepository": "grafana/grafana",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316221529,
           "socket": 1712316221529,
           "lookup": 1712316221530,
           "connect": 1712316221624,
           "secureConnect": 1712316221726,
           "upload": 1712316221726,
           "response": 1712316221919,
           "end": 1712316221919,
           "phases": {
             "wait": 0,
             "dns": 1,
             "tcp": 94,
             "tls": 102,
             "request": 0,
             "firstByte": 193,
             "download": 0,
             "total": 390
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Agrafana%2Fgrafana%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:41 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
DEBUG: Aggregate error is thrown (repository=161)
       "err": {
         "name": "AggregateError",
         "message": "\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
         "stack": "AggregateError: \n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    at next (/usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:43:14)\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:67:7\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
DEBUG: GET https://auth.docker.io/token?scope=repository%3Aprom%2Fnode-exporter%3Apull&service=registry.docker.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=500 retryCount=2, duration=376) (repository=161)
 WARN: Retry-After: unexpected status code 500 (repository=161)
       "url": "https://auth.docker.io/token?scope=repository%3Aprom%2Fnode-exporter%3Apull&service=registry.docker.io"
 WARN: docker registry failure: internal error (repository=161)
       "registryHost": "https://index.docker.io",
       "dockerRepository": "prom/node-exporter",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316221548,
           "socket": 1712316221549,
           "lookup": 1712316221550,
           "connect": 1712316221644,
           "secureConnect": 1712316221743,
           "upload": 1712316221743,
           "response": 1712316221924,
           "end": 1712316221924,
           "phases": {
             "wait": 1,
             "dns": 1,
             "tcp": 94,
             "tls": 99,
             "request": 0,
             "firstByte": 181,
             "download": 0,
             "total": 376
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Aprom%2Fnode-exporter%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:41 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
DEBUG: Aggregate error is thrown (repository=161)
       "err": {
         "name": "AggregateError",
         "message": "\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
         "stack": "AggregateError: \n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    at next (/usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:43:14)\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:67:7\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
DEBUG: GET https://auth.docker.io/token?scope=repository%3Aportainer%2Fportainer-ee%3Apull&service=registry.docker.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=500 retryCount=2, duration=325) (repository=161)
 WARN: Retry-After: unexpected status code 500 (repository=161)
       "url": "https://auth.docker.io/token?scope=repository%3Aportainer%2Fportainer-ee%3Apull&service=registry.docker.io"
 WARN: docker registry failure: internal error (repository=161)
       "registryHost": "https://index.docker.io",
       "dockerRepository": "portainer/portainer-ee",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316221904,
           "socket": 1712316221904,
           "lookup": 1712316221929,
           "connect": 1712316222024,
           "secureConnect": 1712316222130,
           "upload": 1712316222130,
           "response": 1712316222228,
           "end": 1712316222229,
           "phases": {
             "wait": 0,
             "dns": 25,
             "tcp": 95,
             "tls": 106,
             "request": 0,
             "firstByte": 98,
             "download": 1,
             "total": 325
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Aportainer%2Fportainer-ee%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:42 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
DEBUG: Aggregate error is thrown (repository=161)
       "err": {
         "name": "AggregateError",
         "message": "\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
         "stack": "AggregateError: \n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    at next (/usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:43:14)\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:67:7\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
DEBUG: GET https://auth.docker.io/token?scope=repository%3Aprom%2Fblackbox-exporter%3Apull&service=registry.docker.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=500 retryCount=2, duration=295) (repository=161)
 WARN: Retry-After: unexpected status code 500 (repository=161)
       "url": "https://auth.docker.io/token?scope=repository%3Aprom%2Fblackbox-exporter%3Apull&service=registry.docker.io"
 WARN: docker registry failure: internal error (repository=161)
       "registryHost": "https://index.docker.io",
       "dockerRepository": "prom/blackbox-exporter",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316225979,
           "socket": 1712316225979,
           "lookup": 1712316225979,
           "connect": 1712316226073,
           "secureConnect": 1712316226176,
           "upload": 1712316226183,
           "response": 1712316226273,
           "end": 1712316226274,
           "phases": {
             "wait": 0,
             "dns": 0,
             "tcp": 94,
             "tls": 103,
             "request": 7,
             "firstByte": 90,
             "download": 1,
             "total": 295
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Aprom%2Fblackbox-exporter%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:46 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
DEBUG: GET https://auth.docker.io/token?scope=repository%3Aprometheuscommunity%2Fjson-exporter%3Apull&service=registry.docker.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=500 retryCount=2, duration=305) (repository=161)
 WARN: Retry-After: unexpected status code 500 (repository=161)
       "url": "https://auth.docker.io/token?scope=repository%3Aprometheuscommunity%2Fjson-exporter%3Apull&service=registry.docker.io"
 WARN: docker registry failure: internal error (repository=161)
       "registryHost": "https://index.docker.io",
       "dockerRepository": "prometheuscommunity/json-exporter",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316225976,
           "socket": 1712316225976,
           "lookup": 1712316225979,
           "connect": 1712316226074,
           "secureConnect": 1712316226183,
           "upload": 1712316226183,
           "response": 1712316226280,
           "end": 1712316226281,
           "phases": {
             "wait": 0,
             "dns": 3,
             "tcp": 95,
             "tls": 109,
             "request": 0,
             "firstByte": 97,
             "download": 1,
             "total": 305
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Aprometheuscommunity%2Fjson-exporter%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:46 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
DEBUG: GET https://auth.docker.io/token?scope=repository%3Aprom%2Fprometheus%3Apull&service=registry.docker.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=500 retryCount=2, duration=291) (repository=161)
 WARN: Retry-After: unexpected status code 500 (repository=161)
       "url": "https://auth.docker.io/token?scope=repository%3Aprom%2Fprometheus%3Apull&service=registry.docker.io"
 WARN: docker registry failure: internal error (repository=161)
       "registryHost": "https://index.docker.io",
       "dockerRepository": "prom/prometheus",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316225995,
           "socket": 1712316225995,
           "lookup": 1712316225995,
           "connect": 1712316226089,
           "secureConnect": 1712316226188,
           "upload": 1712316226192,
           "response": 1712316226286,
           "end": 1712316226286,
           "phases": {
             "wait": 0,
             "dns": 0,
             "tcp": 94,
             "tls": 99,
             "request": 4,
             "firstByte": 94,
             "download": 0,
             "total": 291
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Aprom%2Fprometheus%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:46 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
DEBUG: GET https://auth.docker.io/token?scope=repository%3Alibrary%2Ftraefik%3Apull&service=registry.docker.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=500 retryCount=2, duration=302) (repository=161)
 WARN: Retry-After: unexpected status code 500 (repository=161)
       "url": "https://auth.docker.io/token?scope=repository%3Alibrary%2Ftraefik%3Apull&service=registry.docker.io"
 WARN: docker registry failure: internal error (repository=161)
       "registryHost": "https://index.docker.io",
       "dockerRepository": "library/traefik",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316225990,
           "socket": 1712316225990,
           "lookup": 1712316225995,
           "connect": 1712316226090,
           "secureConnect": 1712316226192,
           "upload": 1712316226192,
           "response": 1712316226292,
           "end": 1712316226292,
           "phases": {
             "wait": 0,
             "dns": 5,
             "tcp": 95,
             "tls": 102,
             "request": 0,
             "firstByte": 100,
             "download": 0,
             "total": 302
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Alibrary%2Ftraefik%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:46 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
DEBUG: Aggregate error is thrown (repository=161)
       "err": {
         "name": "AggregateError",
         "message": "\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
         "stack": "AggregateError: \n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    at next (/usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:43:14)\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:67:7\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
DEBUG: GET https://auth.docker.io/token?scope=repository%3Aprom%2Falertmanager%3Apull&service=registry.docker.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=500 retryCount=2, duration=300) (repository=161)
 WARN: Retry-After: unexpected status code 500 (repository=161)
       "url": "https://auth.docker.io/token?scope=repository%3Aprom%2Falertmanager%3Apull&service=registry.docker.io"
 WARN: docker registry failure: internal error (repository=161)
       "registryHost": "https://index.docker.io",
       "dockerRepository": "prom/alertmanager",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316226054,
           "socket": 1712316226055,
           "lookup": 1712316226055,
           "connect": 1712316226150,
           "secureConnect": 1712316226252,
           "upload": 1712316226252,
           "response": 1712316226353,
           "end": 1712316226354,
           "phases": {
             "wait": 1,
             "dns": 0,
             "tcp": 95,
             "tls": 102,
             "request": 0,
             "firstByte": 101,
             "download": 1,
             "total": 300
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Aprom%2Falertmanager%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:46 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
DEBUG: Aggregate error is thrown (repository=161)
       "err": {
         "name": "AggregateError",
         "message": "\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
         "stack": "AggregateError: \n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    at next (/usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:43:14)\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:67:7\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
DEBUG: Aggregate error is thrown (repository=161)
       "err": {
         "name": "AggregateError",
         "message": "\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
         "stack": "AggregateError: \n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at DockerDatasource.getTags (/usr/local/renovate/lib/modules/datasource/docker/index.ts:749:15)\n        at processTicksAndRejections (node:internal/process/task_queues:95:5)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1007:36)\n        at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n        at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n        at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n        at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:123:56)\n        at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n        at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n        at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n        at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22\n    at next (/usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:43:14)\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:67:7\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
 WARN: Host error (repository=161)
       "hostType": "docker",
       "packageName": "vaultwarden/server",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1712316221504,
           "socket": 1712316221505,
           "lookup": 1712316221506,
           "connect": 1712316221601,
           "secureConnect": 1712316221703,
           "upload": 1712316221703,
           "response": 1712316221802,
           "end": 1712316221802,
           "phases": {
             "wait": 1,
             "dns": 1,
             "tcp": 95,
             "tls": 102,
             "request": 0,
             "firstByte": 99,
             "download": 0,
             "total": 298
           }
         },
         "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.279.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?scope=repository%3Avaultwarden%2Fserver%3Apull&service=registry.docker.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": {"details": "unsupported authentication scheme: Bearer"},
           "headers": {
             "content-type": "application/json",
             "date": "Fri, 05 Apr 2024 11:23:41 GMT",
             "content-length": "56",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
 INFO: External host error causing abort - skipping (repository=161)
DEBUG: Repository result: external-host-error, status: onboarded, enabled: true, onboarded: true (repository=161)
DEBUG: Repository timing splits (milliseconds) (repository=161)
       "splits": {"init": 5083, "extract": 107},
       "total": 14215
DEBUG: Package cache statistics (repository=161)
       "get": {"count": 20, "avgMs": 17, "medianMs": 13, "maxMs": 57, "totalMs": 336},
       "set": {"count": 0, "avgMs": 0, "medianMs": 0, "maxMs": 0, "totalMs": 0}
DEBUG: HTTP statistics (repository=161)
       "urls": {
         "https://auth.docker.io/token": {"GET": {"500": 10}},
         "https://git.docsinclouds.com/api/v4/projects/161": {"GET": {"200": 1}},
         "https://git.docsinclouds.com/api/v4/projects/161/issues": {
           "GET": {"200": 1}
         },
         "https://git.docsinclouds.com/api/v4/projects/161/merge_requests": {
           "GET": {"200": 1}
         },
         "https://git.docsinclouds.com/api/v4/projects/161/repository/files/renovate.json": {
           "GET": {"200": 1}
         },
         "https://index.docker.io/v2/grafana/grafana/tags/list": {"GET": {"401": 1}},
         "https://index.docker.io/v2/library/traefik/tags/list": {"GET": {"401": 1}},
         "https://index.docker.io/v2/portainer/agent/tags/list": {"GET": {"401": 1}},
         "https://index.docker.io/v2/portainer/portainer-ee/tags/list": {
           "GET": {"401": 1}
         },
         "https://index.docker.io/v2/prom/alertmanager/tags/list": {"GET": {"401": 1}},
         "https://index.docker.io/v2/prom/blackbox-exporter/tags/list": {
           "GET": {"401": 1}
         },
         "https://index.docker.io/v2/prom/node-exporter/tags/list": {
           "GET": {"401": 1}
         },
         "https://index.docker.io/v2/prom/prometheus/tags/list": {"GET": {"401": 1}},
         "https://index.docker.io/v2/prometheuscommunity/json-exporter/tags/list": {
           "GET": {"401": 1}
         },
         "https://index.docker.io/v2/vaultwarden/server/tags/list": {"GET": {"401": 1}}
       },
       "hosts": {
         "auth.docker.io": {
           "count": 10,
           "reqAvgMs": 327,
           "reqMedianMs": 305,
           "reqMaxMs": 390,
           "queueAvgMs": 0,
           "queueMedianMs": 0,
           "queueMaxMs": 0
         },
         "git.docsinclouds.com": {
           "count": 4,
           "reqAvgMs": 186,
           "reqMedianMs": 201,
           "reqMaxMs": 228,
           "queueAvgMs": 0,
           "queueMedianMs": 0,
           "queueMaxMs": 0
         },
         "index.docker.io": {
           "count": 10,
           "reqAvgMs": 358,
           "reqMedianMs": 332,
           "reqMaxMs": 646,
           "queueAvgMs": 0,
           "queueMedianMs": 0,
           "queueMaxMs": 1
         }
       },
       "requests": 24
DEBUG: HTTP cache statistics (repository=161)
DEBUG: Lookup statistics (repository=161)
       "docker": {"count": 15, "avgMs": 2988, "medianMs": 4399, "maxMs": 4797, "totalMs": 44813}
DEBUG: dns cache (repository=161)
       "hosts": []
 INFO: Repository finished (repository=161)
       "cloned": true,
       "durationMs": 14215
DEBUG: Checking file package cache for expired items
DEBUG: Deleted 0 of 0 file cached entries in 2ms
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "0TO5evcdqF-CuWc3dvQac",
           "allowedHeaders": ["X-*"],
           "header": "Authorization",
           "msg": "Disallowed hostRules headers"
         },
         {
           "name": "renovate",
           "level": 50,
           "logContext": "0TO5evcdqF-CuWc3dvQac",
           "repository": "161",
           "allowedHeaders": ["X-*"],
           "header": "Authorization",
           "msg": "Disallowed hostRules headers"
         }
       ]
section_end:1712316226:step_script
[0Ksection_start:1712316226:cleanup_file_variables
[0K[0K[36;1mCleaning up file based variables[0;m
[0;msection_end:1712316227:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m
  ```
</details>
