### PR TITLE
fix(bundler): don't log error when Gemfile is invalid

### LINKED ISSUE #6548: Renovate exits with error on invalid Gemfiles
**What Renovate type are you using?**

Self-hosted Renovate/GitLab

**Describe the bug**

Given an invalid Gemfile like this:

```ruby
source 'https://rubygems.org' do
    gem 'mylittlepony'
```
(The `end` is missing)

Renovate exit with messages like these:

```
 ERROR: Undefined sourceLine (repository=abc/def)
        "content": "[content]",
        "fileName": "Gemfile"

  INFO: Renovate is exiting with a non-zero code due to the following logged errors
        "loggerErrors": [
          {
            "name": "renovate",
            "level": 50,
            "logContext": "drHJXxf6V",
            "repository": "abc/def",
            "content": "[content]",
            "fileName": "Gemfile",
            "msg": "Undefined sourceLine"
          }
        ]
```

**Additional context**

This behavior was already mentioned in https://github.com/renovatebot/renovate/issues/5232#issuecomment-578761280.

### PR DESCRIPTION
**Pull request by fgreinacher**
Closes #6548

### CODE REVIEW

File: lib/manager/bundler/extract.ts [hunk 1]
```diff
@@ -116,7 +116,7 @@ export async function extractPackageFile(
           sourceLine = lines[lineNumber];
           // istanbul ignore if
           if (sourceLine === null || sourceLine === undefined) {
-            logger.error({ content, fileName }, 'Undefined sourceLine');
+            logger.info({ content, fileName }, 'Undefined sourceLine');
```
Comment (fgreinacher) [inline lib/manager/bundler/extract.ts:119]: I picked info based on the guidelines in https://github.com/renovatebot/renovate/blob/8e97958dd17b3ec92926af10fc012bea66308d26/docs/development/design-decisions.md#logging-and-error-levels

**Review by viceice — APPROVED** [review]
