### PR TITLE
fix: match source url prefixes compares case insensitive

### LINKED ISSUE #10962: `matchSourceUrlPrefixes` should compare case insensitive
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: ...

**Describe the bug**

Urls are nomally case insensive, so we should compare `matchSourceUrlPrefixes` case insensitive too.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

This can happen, if repos or orgs on github are moved to lowercase only letters, see #10960

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes:

matchSourceUrlPrefixes now compares as case insensitive

## Context:

Fixes #10962 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/package-rules.ts [hunk 1]
```diff
@@ -194,8 +194,9 @@ function matchesRule(
     positiveMatch = true;
   }
   if (matchSourceUrlPrefixes.length) {
+    const lowerCaseSourceUrl = sourceUrl?.toLowerCase();
```
Comment (viceice) [inline lib/util/package-rules.ts:197]: We should use uppercase, as there are symbols without a lowercase char.

**Review by viceice — COMMENTED** [review]
Otherwise LGTM

**Review by viceice — APPROVED** [review]
