### PR TITLE
fix(onboarding): refactor commit message functionality

### LINKED ISSUE #10854: rebase onboarding branch does not respect commitMessagePrefix
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted (official docker image in on premise Kubernetes CronJob)

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [x] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: 25.49.5 (official docker image)

**Describe the bug**
In our enterprise environment, we are required to prefix all commit messages with Jira Issue IDs. To pass this regex check, we use the configuration option `commitMessagePrefix `to add a placeholder issue to all commits.
This works fine for creating onboarding PRs and update PRs. 

But for rebasing onboarding PRs the commitMessagePrefix is ignored and our renovate CronJob fails due to the push being blocked.

To test the behaviour we deactivated the check (which is no longterm solution due to it being a compliance requirement). This created these changes on the onboarding PR:
renovate

A solution should be for `getCommitMessage(config: RenovateConfig)` in `rebase.ts`

https://github.com/renovatebot/renovate/blob/3a4e7428f575eeeec6e38308798563caf34f4bc7/lib/workers/repository/onboarding/branch/rebase.ts#L18-L33

to honour the config `commitMessagePrefix` just like `create.ts` does:
 https://github.com/renovatebot/renovate/blob/73cd3d517bd72bb1797cbb79776f9389d76a0870/lib/workers/repository/onboarding/branch/create.ts#L22-L42
...

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

### PR DESCRIPTION
**Pull request by pret-a-porter**
## Changes:

1. Introduced new entity `CommitMessage`. It is quite abstract entity, so can be widely used in different places. In the same time, if we will operate by specific entity instead of string, we will always be sure, that formatting of commit message will be correct.
2. Introduced `OnboardingCommitMessageFactory` (more [info](https://refactoring.guru/design-patterns/factory-method) about factory pattern)

## Context:

Fixes #10854 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/repository/onboarding/branch/commit-message.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
+import { RenovateConfig } from '../../../../config/types';
+import { CommitMessage } from '../../model/commit-message';
+import { CommitMessageBuilder } from '../../model/commit-message-builder';
+
+export class OnboardingCommitMessageFactory {
+  private readonly config: Partial<RenovateConfig>;
```
Comment (viceice) [inline lib/workers/repository/onboarding/branch/commit-message.ts:6]: No partial.

File: lib/workers/repository/onboarding/branch/commit-message.ts [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+
+  private readonly configFile: string;
+
+  constructor(config: Partial<RenovateConfig>, configFile: string) {
```
Comment (viceice) [inline lib/workers/repository/onboarding/branch/commit-message.ts:10]: No partial

File: lib/workers/repository/model/commit-message.ts [hunk 3]
```diff
@@ -0,0 +1,39 @@
+export class CommitMessage {
```
Comment (viceice) [inline lib/workers/repository/model/commit-message.ts:1]: I don't see much value for this class. Why not build the final message on build command of builder?

**Comment by HonkingGoose** [comment]
There's a spelling error in the PR title:

change `funcionality`- > `functionality`

File: lib/workers/repository/model/commit-message.ts (hunk 3 above)
Comment (pret-a-porter) [reply lib/workers/repository/model/commit-message.ts:1]: Yeah, I agree. I have merged functionality of both classes in `CommitMessage`

File: lib/workers/repository/model/commit-message.spec.ts [hunk 4]
```diff
@@ -0,0 +1,58 @@
+import { getName } from '../../../../test/util';
```
Comment (viceice) [inline lib/workers/repository/model/commit-message.spec.ts:1]: Any special cause for new folder name? `util->model`

File: lib/workers/repository/onboarding/branch/commit-message.ts [hunk 5]
```diff
@@ -0,0 +1,41 @@
+import { RenovateConfig } from '../../../../config/types';
+import { CommitMessage } from '../../model/commit-message';
+
+export class OnboardingCommitMessageFactory {
```
Comment (viceice) [inline lib/workers/repository/onboarding/branch/commit-message.ts:4]: Shouldn't this class be at same folder as commit-message?

File: lib/workers/repository/model/commit-message.spec.ts (hunk 4 above)
Comment (pret-a-porter) [reply lib/workers/repository/model/commit-message.spec.ts:1]: I did not recognize which architecture approach now used in repository, that is why I though about starting introduce hexagonal architecture. From this point of view `CommitMessage` looks like domain level model for `repository` module

File: lib/workers/repository/onboarding/branch/commit-message.ts (hunk 5 above)
Comment (pret-a-porter) [reply lib/workers/repository/onboarding/branch/commit-message.ts:4]: I would prefer to store it inside `onboarding` folder, because this class is specific only for onboarding functionality

**Review by viceice — APPROVED** [review]
