### PR TITLE
fix(platform/azure): improve getPolicyConfigurations latency via mergePolicyGuid filter

### LINKED ISSUE #14438: [Azure DevOps] Renovate hangs after getProjectAndRepo step
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.94.0

### Please select which platform you are using if self-hosting.

Azure DevOps (dev.azure.com)

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When attempting to run renovate with the following simple configuration:

```
module.exports = {
  platform: 'azure',
  endpoint: 'https://dev.azure.com/MY_ORG',
  token: process.env.TOKEN,
  logLevel: 'debug',
  nuget: {
    registryUrls: [
      'https://msazure.pkgs.visualstudio.com/One/_packaging/MY_FEED/nuget/v3/index.json'
    ]
  },
  hostRules: [
    {
      hostType: 'nuget',
      matchHost: 'https://MY_ORG.pkgs.visualstudio.com',
      username: '',
      password: process.env.TOKEN,
    },
  ],
  repositories: [
      'Project/Repo'
  ],
  requireConfig: false,
  printConfig: true,
  persistRepoData: true
};
```

Renovate hangs when determining the default merge strategy to use. I tried debugging and got stuck here: https://github.com/renovatebot/renovate/blob/b8dd3e8493083ea1e4e2e982bf420ba9d685e583/lib/platform/azure/azure-helper.ts#L140. 

It appears that renovate lists all policy configurations with this API: https://ORG.visualstudio.com/PROJECT/_apis/policy/configurations?api-version=6.1-preview.1, without any pagination. I was able to determine that this call does indeed return when using curl after a few minutes. When Renovate uses this API, it simply hangs and times out. I'm assuming that this is because our Azure Devops organization has a large amount of policies.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in C:\Me\Microsoft\Code\Dir/config.js
DEBUG: File config
       "config": {
         "platform": "azure",
         "endpoint": "https://dev.azure.com/MY_ORG",
         "token": "***********",
         "logLevel": "debug",
         "nuget": {
           "registryUrls": [
             "https://MY_ORG.pkgs.visualstudio.com/One/_packaging/MY_FEED/nuget/v3/index.json"
           ]
         },
         "hostRules": [
           {
             "hostType": "nuget",
             "matchHost": "https://MY_ORG.pkgs.visualstudio.com",
             "username": "",
             "password": "***********"
           }
         ],
         "repositories": ["Project/Repo"],
         "requireConfig": false,
         "printConfig": true,
         "persistRepoData": true
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {"hostRules": []}
DEBUG: Combined config
       "config": {
         "platform": "azure",
         "endpoint": "https://dev.azure.com/MY_ORG",
         "token": "***********",
         "logLevel": "debug",
         "nuget": {
           "registryUrls": [
             "https://MY_ORG.pkgs.visualstudio.com/One/_packaging/MY_FEED/nuget/v3/index.json"
           ]
         },
         "hostRules": [
           {
             "hostType": "nuget",
             "matchHost": "https://MY_ORG.pkgs.visualstudio.com",
             "username": "",
             "password": "***********"
           }
         ],
         "repositories": ["Project/Repo"],
         "requireConfig": false,
         "printConfig": true,
         "persistRepoData": true
       }
DEBUG: Adding trailing slash to endpoint
DEBUG: Found valid git version: 2.35.1.windows.2
DEBUG: Adding token authentication for dev.azure.com to hostRules
DEBUG: Using baseDir: C:/Users/NOAMDO~1/AppData/Local/Temp/renovate
DEBUG: Using cacheDir: C:/Users/NOAMDO~1/AppData/Local/Temp/renovate/cache
DEBUG: Initializing Renovate internal cache into C:/Users/NOAMDO~1/AppData/Local/Temp/renovate/cache/renovate/renovate-cache-v1
DEBUG: Commits limit = null
DEBUG: Setting global hostRules
DEBUG: Adding password authentication for https://MY_ORG.pkgs.visualstudio.com to hostRules
DEBUG: Adding token authentication for dev.azure.com to hostRules
DEBUG: validatePresets()
DEBUG: Reinitializing hostRules for repo
DEBUG: Clearing hostRules
DEBUG: Adding password authentication for https://MY_ORG.pkgs.visualstudio.com to hostRules
DEBUG: Adding token authentication for dev.azure.com to hostRules
 INFO: Repository started (repository=Project/Repo)
       "renovateVersion": "31.94.0"
DEBUG: Using localDir: C:/Users/NOAMDO~1/AppData/Local/Temp/renovate/repos/azure/Project/Repo (repository=Project/Repo)
DEBUG: initRepo("Project/Repo") (repository=Project/Repo)
TRACE: getRepoByName(One/ASI-AlertRules) (repository=Project/Repo)
TRACE: getProjectAndRepo(One/ASI-AlertRules) (repository=Project/Repo)
DEBUG: Repository details (repository=Project/Repo)
       "repositoryDetails": {...removed...}
DEBUG: Project/Repo owner = ?owner? (repository=Project/Repo)
DEBUG: Project/Repo default branch = develop (repository=Project/Repo)
TRACE: getProjectAndRepo(Project/Repo)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by NoamTD**
fixes #14438

### CODE REVIEW

File: lib/modules/platform/azure/azure-helper.ts [hunk 1]
```diff
@@ -141,7 +141,9 @@ export async function getMergeMethod(
   };
 
   const policyConfigurations = (
-    await (await azureApi.policyApi()).getPolicyConfigurations(project)
+    await (
+      await azureApi.policyApi()
+    ).getPolicyConfigurations(project, mergePolicyGuid)
   )
     .filter(
```
Comment (JamieMagee) [inline lib/modules/platform/azure/azure-helper.ts:148]: small nit, but is the filter below still required?

Comment (NoamTD) [reply lib/modules/platform/azure/azure-helper.ts]: no, good point - removed.

**Review by JamieMagee — APPROVED** [review]
