### PR TITLE
fix(github): Remove PR cache migrations code

### LINKED ISSUE #17497: Remove cache migrations
### Describe the proposed change(s).

Let's remove all cache migration logic for v33

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

`repoCache.platform.github.prCache` was the root of PR cache data. Here we delete old root and use new one instead.

## Context

- Closes: #17497

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/platform/github/pr.ts [hunk 1]
```diff
@@ -9,42 +9,16 @@ import { ApiCache } from './api-cache';
...
-  repoCache.platform.github.prCache ??= { items: {} };
-  const cache = repoCache.platform.github.prCache;
-  migrateCache(cache);
-  const prCache = new ApiCache<GhPr>(cache as ApiPageCache<GhPr>);
-  return prCache;
+  delete repoCache.platform.github.prCache;
+  repoCache.platform.github.pullRequestsCache ??= { items: {} };
+  const prApiCache = new ApiCache<GhPr>(
+    repoCache.platform.github.pullRequestsCache as ApiPageCache<GhPr>
+  );
```
Comment (rarkins) [inline lib/modules/platform/github/pr.ts:20]: So once deployed this will be a complete reset of all github PR data, right?

Comment (zharinov) [reply lib/modules/platform/github/pr.ts:20]: Right
