### PR TITLE
fix(rubygems): Use cascade of endpoints for unknown servers

### LINKED ISSUE #15459: Support Nexus repository manager for RubyGems
### What would you like Renovate to be able to do?

Nexus repository manager doesn't support the '/api/v1/' pattern for RubyGem discovery, however, `bundler` does support installing Gems when the Nexus URL is used as the `source` in the `Gemfile`.

When Renovate finds a Gemfile with a source of a source of Nexus the logs show:

```shell
DEBUG: Datasource connection error (repository=example)
       "datasource": "rubygems",
       "packageName": "example",
       "url": "https://private/repository/example/api/v1/gems/example.json",
       "errCode": "ERR_NON_2XX_3XX_RESPONSE"
DEBUG: Failed to look up dependency ***
```

The above URL would result in a 400.

### If you have any ideas on how this should be implemented, please tell us here.

The `source` used for `bundler` is just a URL link to the Gem group rather than an API endpoint. Should maybe take that into account.

### Is this a feature you are interested in implementing yourself?

No

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

For registries other than `rubygems.org`, `rubygems.pkg.github.com` or `gitlab.com`, following endpoints are queried:

- First request: `/api/v1/versions/{package}.json`
  - It's useful because it contains date for `releaseTimestamp` field
  - Optionally, metadata such as `homepageUrl` will be queried via `/api/v1/gems/{package}.json`
- Fallback 1: `/info/{package}` endpoint ([example](https://rubygems.org/info/faker))
- Fallback 2: `/api/v1/dependencies` ([obsolete](https://blog.rubygems.org/2023/02/22/dependency-api-deprecation.html) but [still working](https://blog.rubygems.org/2023/04/07/dependency-api-deprecation-delayed.html))

## Context

- Closes #15459

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
- Blocked by #23522

File: lib/modules/datasource/rubygems/metadata-cache.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ import type { Http } from '../../../util/http';
 import { AsyncResult, Result } from '../../../util/result';
 import { parseUrl } from '../../../util/url';
 import type { ReleaseResult } from '../types';
-import { getV1Releases } from './common';
+import { assignMetadata, getV1Metadata, getV1Releases } from './common';
```
Comment (viceice) [inline lib/modules/datasource/rubygems/metadata-cache.ts:7]: unused import?
```suggestion
import { getV1Metadata, getV1Releases } from './common';
```

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
