### PR TITLE
fix(manger/npm): apply config.npmrc during extraction, not in post-update

### LINKED ISSUE #12891: Renovate removing dependencies in "unaffected" package in monorepo
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Describe the bug

Dependencies are purged from `package-lock.json` files which causes package-locks to be corrupted in a lerna monorepo

I tried to setup a minimal reproduction here: this [pull request](https://github.com/donmahallem/renovate-issue/pull/1) where dependencies in **package a** and **b** are updated but purged from **c** too, which causes dependencies to be missing in **package c** on clean install.
For example remark is purged in the pull request above from package **c**.
dudi
In the linked Repo run:
```
npm ci
npx lerna bootstrap --ci
npx lerna run test
```
it will fail on the linked PR above because renovate-validate-config is misisng the remark dependency.

I had this issue with several dependencies: @types/node and ajv too for example.

This has been an issue for me for roughly three weeks now.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Branch is stale and needs rebasing(branch="renovate/remark-monorepo")
DEBUG: Using reuseExistingBranch: false(branch="renovate/remark-monorepo")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/remark-monorepo")
DEBUG: npm.updateDependency(): dependencies.remark = ~14.0.2(branch="renovate/remark-monorepo")
DEBUG: Updating remark in packages/a/package.json(branch="renovate/remark-monorepo")
DEBUG: npm.updateDependency(): dependencies.remark-html = ~15.0.1(branch="renovate/remark-monorepo")
DEBUG: Updating remark-html in packages/a/package.json(branch="renovate/remark-monorepo")
DEBUG: npm.updateDependency(): dependencies.remark-license = ~6.1.0(branch="renovate/remark-monorepo")
DEBUG: Updating remark-license in packages/a/package.json(branch="renovate/remark-monorepo")
DEBUG: npm.updateDependency(): devDependencies.remark-parse = 10.0.1(branch="renovate/remark-monorepo")
DEBUG: Updating remark-parse in packages/b/package.json(branch="renovate/remark-monorepo")
DEBUG: npm.updateDependency(): devDependencies.remark-stringify = 10.0.2(branch="renovate/remark-monorepo")
DEBUG: Updating remark-stringify in packages/b/package.json(branch="renovate/remark-monorepo")
DEBUG: Updated 2 package files(branch="renovate/remark-monorepo")
DEBUG: Getting updated lock files(branch="renovate/remark-monorepo")
DEBUG: packages/a/package.json has lerna lock file(branch="renovate/remark-monorepo")
DEBUG: packages/b/package.json has lerna lock file(branch="renovate/remark-monorepo")
DEBUG: Writing package.json files(branch="renovate/remark-monorepo")
{
  "packageFiles": [
    "package.json",
    "packages/a/package.json",
    "packages/b/package.json",
    "packages/c/package.json"
  ]
}
DEBUG: Writing package-lock.json(branch="renovate/remark-monorepo")
DEBUG: Writing packages/a/package-lock.json(branch="renovate/remark-monorepo")
DEBUG: Massaging npm lock file before writing to disk(branch="renovate/remark-monorepo")
DEBUG: Writing packages/b/package-lock.json(branch="renovate/remark-monorepo")
DEBUG: Massaging npm lock file before writing to disk(branch="renovate/remark-monorepo")
DEBUG: Writing packages/c/package-lock.json(branch="renovate/remark-monorepo")
DEBUG: Massaging npm lock file before writing to disk(branch="renovate/remark-monorepo")
DEBUG: Writing any updated package files(branch="renovate/remark-monorepo")
DEBUG: Writing packages/a/package.json(branch="renovate/remark-monorepo")
DEBUG: Writing packages/b/package.json(branch="renovate/remark-monorepo")
DEBUG: Finding package.json for lerna location "lerna.json"(branch="renovate/remark-monorepo")
DEBUG: No npmrc file found in repository(branch="renovate/remark-monorepo")
DEBUG: Writing updated .npmrc file to /mnt/renovate/gh/donmahallem/renovate-issue/.npmrc(branch="renovate/remark-monorepo")
DEBUG: Spawning lerna with npm to create lock files(branch="renovate/remark-monorepo")
DEBUG: No node constraint found - using latest(branch="renovate/remark-monorepo")
DEBUG: Using lerna version 4.0.0(branch="renovate/remark-monorepo")
DEBUG: Using docker to execute(branch="renovate/remark-monorepo")
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by simon-abbott**
## Changes

This moves the application of the global `npmrc` config option from the `post-update` phase to the `extract` phase.

## Context

Sub-packages in monorepos sometimes have their own `.npmrc` files. These should not be shared between packages. This fixes a particularly nasty bug, reported in #12891.

Here's what is actually happening to cause #12891:

1. Create a monorepo using Lerna
2. Make two sub-packages `foo` and `bar`
3. Add a `.npmrc` file to `foo` with the contents `legacy-peer-deps=true`
4. Have an out-of-date dependency in `foo`
5. Run Renovate

When Renovate runs it will execute `branchifyUpgrades()`, which, in turn, calls `flattenUpdates`, which will return a branch config object with `{ npmrc: "legacy-peer-deps=true" }`. Later on in the process that config is passed to `writeExistingFiles` for each package, which dutifully creates a `.npmrc` file with `legacy-peer-deps=true` _in each subpackage_. This is the real bug, since now `legacy-peer-deps` has been turned on for package `bar`, even though it's only defined in `foo`. Then, when the updates are finished Renovate runs `lerna bootstrap` to update the lockfiles. When Lerna runs with `legacy-peer-deps=true` it regenerates the lock files, likely because the dependency resolution graph is different since it can meet peer requirements more easily.

To fix this issue, we now apple the `npmrc` config when extracting per-package-file configs, and write the result to disk `writeExistingFiles`.

Closes #12891 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by simon-abbott** [comment]
Another approach I thought of to fix this would be to always set the `packageFile.npmrc` setting in `extractPackageFile`, and only use that in `writeExistingFiles`.

**Review by viceice — COMMENTED** [review]
this needs a unit test

**Comment by viceice** [comment]
> Another approach I thought of to fix this would be to always set the `packageFile.npmrc` setting in `extractPackageFile`, and only use that in `writeExistingFiles`.

that would probably the better solution.

**Comment by simon-abbott** [comment]
> that would probably the better solution.

It shall be done.

> this needs a unit test

Agreed, I just wasn't entirely sure how to do that, but doing the other approach would make that easier as well I think.

**Comment by simon-abbott** [comment]
Force-pushed because this is a complete rewrite of the patch.

File: lib/modules/manager/npm/post-update/index.ts [hunk 1]
```diff
@@ -143,7 +143,7 @@ export async function writeExistingFiles(
   for (const packageFile of npmFiles) {
     // TODO #7154
     const basedir = upath.dirname(packageFile.packageFile!);
-    const npmrc: string = packageFile.npmrc ?? config.npmrc;
+    const npmrc = packageFile.npmrc;
```
Comment (simon-abbott) [inline lib/modules/manager/npm/post-update/index.ts:146]: Since we do this application earlier, should the `npmrc` option be moved from the `branch` stage to the `package` stage? I'm still not 100% sure what an option's `stage` semantically means.

Comment (rarkins) [reply lib/modules/manager/npm/post-update/index.ts:146]: This field only affects when Renovate _strips_ the option from config (i.e. to try to reduce the number of fields). Safest to leave it as-is for now

Comment (simon-abbott) [reply lib/modules/manager/npm/post-update/index.ts:146]: So should it be changed or not? The `config`'s `.npmrc` isn't used in here at all anymore, so it makes sense to me that it should be allowed to be stripped out, but also it's not used anymore so it doesn't really matter either way.

Comment (rarkins) [reply lib/modules/manager/npm/post-update/index.ts:146]: Keep it as is, because it doesn't really matter (it's really just for readability of logs and debugging)

**Review by viceice — COMMENTED** [review]
looks good so far. please create some sample repos to do some real tests. this change is risky to break something.

**Comment by simon-abbott** [comment]
> looks good so far. please create some sample repos to do some real tests. this change is risky to break something.

What do you mean by that? I didn't see any repos as part of the test suite, did I miss something?

**Comment by viceice** [comment]
yes, real repo tests was my intention. thanks for confirming.

File: lib/modules/manager/npm/extract/index.spec.ts [hunk 2]
```diff
@@ -153,37 +153,47 @@ describe('modules/manager/npm/extract/index', () => {
       expect(res).toMatchSnapshot({ yarnLock: 'yarn.lock' });
     });
 
-    it('finds and filters .npmrc', async () => {
```
Comment (viceice) [inline lib/modules/manager/npm/extract/index.spec.ts:156]: can you please revert the test order, so the test changes are easier to review

File: lib/modules/manager/npm/post-update/index.spec.ts [hunk 3]
```diff
@@ -219,6 +219,27 @@ describe('modules/manager/npm/post-update/index', () => {
       ]);
     });
 
+    it('writes .npmrc files', async () => {
+      await writeExistingFiles(updateConfig, additionalFiles);
+      expect(fs.writeLocalFile).toHaveBeenCalledOnce();
+      expect(fs.writeLocalFile).toHaveBeenCalledWith(
+        'packages/core/.npmrc',
+        '#dummy\n'
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/index.spec.ts:227]: why does this value comes from? can you make the test more self-contained please?

File: lib/modules/manager/npm/extract/index.spec.ts (hunk 2 above)
Comment (simon-abbott) [reply lib/modules/manager/npm/extract/index.spec.ts:156]: Certainly

File: lib/modules/manager/npm/post-update/index.spec.ts (hunk 3 above)
Comment (simon-abbott) [reply lib/modules/manager/npm/post-update/index.spec.ts:227]: It comes from the definition of `additionalFiles`, but I can definitely make smaller filesets contained within the test itself.

**Review by viceice — APPROVED** [review]
