### PR TITLE
fix(presets): set global host rules before validating presets

### LINKED ISSUE #10893: Presets are read from api.github.com before applying the hostRule for it
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [x] GitLab self-hosted

Renovate version: 25.36.2

**Describe the bug**

My run of Renovate failed, while it attempted to import the https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json file. It failed because our IP address hit the rate limit. I have configured an environment variable `GITHUB_COM_TOKEN`, so the notice `(But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)` should help us. Instead, since the Host Rule for Github.com has not been applied yet, the request (and the job) fails.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
...
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","msg":"Adding trailing slash to endpoint","time":"2021-07-19T13:53:45.696Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","msg":"GitLab version is: 13.8.7","time":"2021-07-19T13:53:46.882Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","msg":"Using configured gitAuthor (Renovate Bot <4520-svc_UBM_astellin@users.noreply.gitlab.otxlab.net>)","time":"2021-07-19T13:53:46.884Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","msg":"Adding token authentication for gitlab.otxlab.net to hostRules","time":"2021-07-19T13:53:46.925Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","msg":"Using configured baseDir: /builds/developer-experience-/ot2-dx-scan/renovate","time":"2021-07-19T13:53:46.926Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","msg":"Using configured cacheDir: /builds/developer-experience-/ot2-dx-scan/renovate/cache/","time":"2021-07-19T13:53:46.927Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","msg":"Initializing Renovate internal cache into /builds/developer-experience-/ot2-dx-scan/renovate/cache/renovate/renovate-cache-v1","time":"2021-07-19T13:53:46.927Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","msg":"Commits limit = null","time":"2021-07-19T13:53:46.928Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","err":{"name":"HTTPError","timings":{"start":1626702827073,"socket":1626702827073,"lookup":1626702827094,"connect":1626702827095,"secureConnect":1626702827135,"upload":1626702827135,"response":1626702827152,"end":1626702827152,"phases":{"wait":0,"dns":21,"tcp":1,"tls":40,"request":0,"firstByte":17,"download":0,"total":79}},"message":"Response code 403 (rate limit exceeded)","stack":"HTTPError: Response code 403 (rate limit exceeded)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","options":{"headers":{"user-agent":"https://github.com/renovatebot/renovate","accept":"application/vnd.github.v3+json","accept-encoding":"gzip, deflate, br"},"url":"https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json","username":"","password":"","method":"GET","http2":false},"response":{"statusCode":403,"statusMessage":"rate limit exceeded","body":{"message":"API rate limit exceeded for 204.90.140.129. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"},"headers":{"date":"Mon, 19 Jul 2021 13:53:47 GMT","server":"Varnish","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-content-type-options":"nosniff","x-frame-options":"deny","x-xss-protection":"1; mode=block","content-security-policy":"default-src 'none'; style-src 'unsafe-inline'","access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset","content-type":"application/json; charset=utf-8","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","x-github-media-type":"github.v3; format=json","x-ratelimit-limit":"60","x-ratelimit-remaining":"0","x-ratelimit-reset":"1626706006","x-ratelimit-resource":"core","x-ratelimit-used":"60","content-length":"280","x-github-request-id":"28A0:4DBB:1B21ACA:3E6BD77:60F583EB","connection":"close"},"httpVersion":"1.1"}},"msg":"GitHub failure: rate limit","time":"2021-07-19T13:53:47.155Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","url":"https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json","msg":"Failed to retrieve beta.json from repo","time":"2021-07-19T13:53:47.155Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","preset":"github>whitesource/merge-confidence:beta","err":{"message":"dep not found","stack":"Error: dep not found\n    at fetchJSONFile (/usr/src/app/node_modules/renovate/lib/config/presets/github/index.ts:33:11)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Object.fetchPreset (/usr/src/app/node_modules/renovate/lib/config/presets/util.ts:45:19)\n    at getPreset (/usr/src/app/node_modules/renovate/lib/config/presets/index.ts:180:22)\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/lib/config/presets/index.ts:255:27)\n    at validatePresets (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:77:5)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:91:5)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"},"msg":"Preset fetch error","time":"2021-07-19T13:53:47.262Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":30,"logContext":"r5lBN0D12","validationError":"Cannot find preset's package (github>whitesource/merge-confidence:beta)","msg":"Throwing preset error","time":"2021-07-19T13:53:47.262Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":60,"logContext":"r5lBN0D12","err":{"message":"config-presets-invalid","stack":"Error: config-presets-invalid\n    at validatePresets (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:79:11)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:91:5)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"},"msg":"Fatal error: config-presets-invalid","time":"2021-07-19T13:53:47.264Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":20,"logContext":"r5lBN0D12","msg":"Renovate exiting","time":"2021-07-19T13:53:47.264Z","v":0}
{"name":"renovate","hostname":"runner-vnmerwc--project-6533-concurrent-1z85d2","pid":22,"level":30,"logContext":"r5lBN0D12","loggerErrors":[{"name":"renovate","level":60,"logContext":"r5lBN0D12","err":{"message":"config-presets-invalid","stack":"Error: config-presets-invalid\n    at validatePresets (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:79:11)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:91:5)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"},"msg":"Fatal error: config-presets-invalid"}],"msg":"Renovate is exiting with a non-zero code due to the following logged errors","time":"2021-07-19T13:53:47.264Z","v":0}

```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Sets any global host rules before validating presets. This ensures that any github-hosted presets use a github.com token if configured.

## Context:

Closes #10893

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/global/index.ts [hunk 1]
```diff
@@ -141,6 +142,7 @@ export async function start(): Promise<number> {
       }
       const repoConfig = await getRepositoryConfig(config, repository);
       if (repoConfig.hostRules) {
```
Comment (astellingwerf) [inline lib/workers/global/index.ts:144]: @rarkins, I've looked at this piece of code multiple times, and was left confused every time. Doesn't this mean that if there are no hostRules, it will lend them from whatever repo last did declare them? Is that a preferable behavior?

Comment (rarkins) [reply lib/workers/global/index.ts:144]: True, we should probably clear them and then reapply. But I think it's impossible to have zero hostRules anyway, because we always add one for the platform

**Review by viceice — APPROVED** [review]
