### PR TITLE
fix(composer): Fix excessive parsing error logging

### LINKED ISSUE #22087: Error parsing composer lock file
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Source

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

To reproduce, run a dry run extract against composer, e.g. `yarn start --dry-run=extract composer/composer`. See errors below

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: Composer: lockfile parsing error (repository=composer/composer)
       "err": {
         "issues": [
           {
             "code": "invalid_type",
             "expected": "string",
             "received": "null",
             "path": ["lockfile"],
             "message": "Expected string, received null"
           }
         ],
         "addIssue": "[function]",
         "addIssues": "[function]",
         "name": "ZodError",
         "message": "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"null\",\n    \"path\": [\n      \"lockfile\"\n    ],\n    \"message\": \"Expected string, received null\"\n  }\n]",
         "stack": "ZodError: [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"null\",\n    \"path\": [\n      \"lockfile\"\n    ],\n    \"message\": \"Expected string, received null\"\n  }\n]\n    at Object.get error [as error] (/Users/rhys/src/github/renovatebot/renovate/node_modules/zod/lib/types.js:2970:40)\n    at Object.catchValue (/Users/rhys/src/github/renovatebot/renovate/lib/modules/manager/composer/schema.ts:216:26)\n    at /Users/rhys/src/github/renovatebot/renovate/node_modules/zod/lib/types.js:2968:37\n    at async /Users/rhys/src/github/renovatebot/renovate/node_modules/zod/lib/types.js:1704:32\n    at async ZodEffects.safeParseAsync (/Users/rhys/src/github/renovatebot/renovate/node_modules/zod/lib/types.js:180:24)\n    at async Object.extractPackageFile (/Users/rhys/src/github/renovatebot/renovate/lib/modules/manager/composer/extract.ts:9:15)\n    at async getManagerPackageFiles (/Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/extract/manager-files.ts:45:19)\n    at async /Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/extract/index.ts:59:28\n    at async Promise.all (index 0)\n    at async extractAllDependencies (/Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/extract/index.ts:56:26)\n    at async extract (/Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/process/extract-update.ts:140:28)\n    at async extractDependencies (/Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/process/index.ts:139:26)\n    at async Object.renovateRepository (/Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/index.ts:61:9)\n    at async attributes.repository (/Users/rhys/src/github/renovatebot/renovate/lib/workers/global/index.ts:184:11)\n    at async start (/Users/rhys/src/github/renovatebot/renovate/lib/workers/global/index.ts:169:7)\n    at async /Users/rhys/src/github/renovatebot/renovate/lib/renovate.ts:18:22"
       }
 WARN: Composer: lockfile parsing error (repository=composer/composer)
       "err": {
         "issues": [
           {
             "code": "invalid_type",
             "expected": "string",
             "received": "null",
             "path": ["lockfile"],
             "message": "Expected string, received null"
           }
         ],
         "addIssue": "[function]",
         "addIssues": "[function]",
         "name": "ZodError",
         "message": "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"null\",\n    \"path\": [\n      \"lockfile\"\n    ],\n    \"message\": \"Expected string, received null\"\n  }\n]",
         "stack": "ZodError: [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"null\",\n    \"path\": [\n      \"lockfile\"\n    ],\n    \"message\": \"Expected string, received null\"\n  }\n]\n    at Object.get error [as error] (/Users/rhys/src/github/renovatebot/renovate/node_modules/zod/lib/types.js:2970:40)\n    at Object.catchValue (/Users/rhys/src/github/renovatebot/renovate/lib/modules/manager/composer/schema.ts:216:26)\n    at /Users/rhys/src/github/renovatebot/renovate/node_modules/zod/lib/types.js:2968:37\n    at async /Users/rhys/src/github/renovatebot/renovate/node_modules/zod/lib/types.js:1704:32\n    at async ZodEffects.safeParseAsync (/Users/rhys/src/github/renovatebot/renovate/node_modules/zod/lib/types.js:180:24)\n    at async Object.extractPackageFile (/Users/rhys/src/github/renovatebot/renovate/lib/modules/manager/composer/extract.ts:9:15)\n    at async getManagerPackageFiles (/Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/extract/manager-files.ts:45:19)\n    at async /Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/extract/index.ts:59:28\n    at async Promise.all (index 0)\n    at async extractAllDependencies (/Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/extract/index.ts:56:26)\n    at async extract (/Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/process/extract-update.ts:140:28)\n    at async extractDependencies (/Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/process/index.ts:139:26)\n    at async Object.renovateRepository (/Users/rhys/src/github/renovatebot/renovate/lib/workers/repository/index.ts:61:9)\n    at async attributes.repository (/Users/rhys/src/github/renovatebot/renovate/lib/workers/global/index.ts:184:11)\n    at async start (/Users/rhys/src/github/renovatebot/renovate/lib/workers/global/index.ts:169:7)\n    at async /Users/rhys/src/github/renovatebot/renovate/lib/renovate.ts:18:22"
       }```

</details>


### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above

### PR DESCRIPTION
**Pull request by zharinov**
## Context

- Fix: #22087

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/composer/schema.ts [hunk 1]
```diff
@@ -26,26 +26,34 @@ export type ComposerRepo = z.infer<typeof ComposerRepo>;
...
 export const PathRepo = z.object({
   type: z.literal('path'),
   url: z.string(),
+  name: z.string().optional(),
 });
 export type PathRepo = z.infer<typeof PathRepo>;
 
+export const PackageRepo = z.object({
+  type: z.literal('package'),
+});
```
Comment (zharinov) [inline lib/modules/manager/composer/schema.ts:42]: We don't actually support it, but seems like we can do it for GitHub-based deps, like we do for Bazel

**Review by viceice — APPROVED** [review]
