### PR TITLE
fix(pin): avoid pinning deprecated version

### LINKED ISSUE #4608: Renovate attempts to pin  deprecated version of dependency
**What Renovate type are you using?**
Hosted app, GitHub.

**Describe the bug**
See this PR raised by Renovate: https://github.com/djcsdy/wildflower-codec/pull/2

Renovate is attempting to pin the crate "bitflags" to "=1.0.5", but that version is "yanked" from Cargo, meaning it is deprecated.

Yanked versions are still available to download, but Cargo will refuse to create a new lockfile that locks a dependency to a yanked version. Since the lockfile is not checked in with this project, pinning the dependency to a yanked version causes the build to fail.

**Did you see anything helpful in debug logs?**
```
        {
            "depName": "bitflags",
            "depType": "dependencies",
            "currentValue": "1.0",
            "managerData": {
              "nestedVersion": false
            },
            "datasource": "cargo",
            "updates": [
              {
                "updateType": "pin",
                "isPin": true,
                "newValue": "=1.0.5",
                "newMajor": 1
              },
              {
                "fromVersion": "1.0.5",
                "toVersion": "1.2.0",
                "newValue": "=1.2.0",
                "newMajor": 1,
                "newMinor": 2,
                "updateType": "minor",
                "isSingleVersion": true,
                "isRange": true,
                "blockedByPin": true
              }
            ],
            "warnings": [],
            "sourceUrl": null
          }
```

**To Reproduce**

1. Create new Rust project with the following dependencies in `Cargo.toml`:
```toml
[dependencies]
bitflags = "1.0"
```

2. Configure Renovate to pin dependencies:
renovate.json
```json
{
  "extends": [
    "config:base",
    ":pinAllExceptPeerDependencies"
  ]
}
```

3. Check in and push `Cargo.toml` and `renovate.json`. **Do not check in `Cargo.lock`.**

4. Activate Renovate on the repository and wait for Renovate to create a PR.

**Expected behavior**
Renovate should pin the dependency to =1.0.4, which is the latest non-yanked version matching the specified dependency range. This is the version that cargo would select if a developer checked out a fresh copy of the repository and ran `cargo install`.

Note that the lockfile (`Cargo.lock`) is not checked into this repository. This is the recommended practice for Rust libraries. If the lockfile were checked in, I would expect Renovate to pin the version to the exact version specified in the lockfile, **even if that version is deprecated**. This would not fail the build since Cargo will allow the existing dependency lock to remain in place.

**Additional context**
I remembered that there was some discussion about handling yanked dependencies when Rust support was first added (#2795), so I took a look at the relevant code: https://github.com/renovatebot/renovate/blob/master/lib/datasource/cargo/index.ts#L84-L86

I compared this implementation with the [bitflags JSON from crates.io](https://raw.githubusercontent.com/rust-lang/crates.io-index/master/bi/tf/bitflags) and it seems to match up. I think renovate is marking the yanked version as deprecated correctly.

The problem seems to be that renovate ignores the `isDeprecated` flag when pinning. I searched the code for `isDeprecated` and the only occurrence I found (other than data sources setting the flag) was here: https://github.com/renovatebot/renovate/blob/master/lib/workers/repository/process/lookup/filter.ts#L40-L52

I am not sure if this code is called at all when pinning dependencies but if it is then it is ineffective.

I want to reiterate that I am pretty sure this problem **can only happen if the lockfile is not committed**.

I am pretty sure this problem can occur for npm/yarn projects too. If it hasn’t come up before then that’s probably because it’s rare for the last release in a release series to be deprecated :-).

### PR DESCRIPTION
**Pull request by djcsdy**
Closes #4608 (I think, not tested yet).

Looks like the problem was that renovate didn't take deprecation into account when determining the current version (`fromVersion`) of a dependency.

### CODE REVIEW

**Comment by rarkins** [comment]
Can you give an example package file so I can understand the before/after ?

**Comment by djcsdy** [comment]
I ran renovate with this change against djcsdy/wildflower-codec and it did the right thing, so I think this is ready for merge.

**Comment by rarkins** [comment]
I thought about this more and for npm, we *should* pin it to the same one as before, even if that one is deprecated. At the same time, I want to avoid any manager-specific code in this worker file because it should ideally be captured within lib/manager/*. Somehow we need a way to behave different for Cargo and npm here.

File: lib/workers/repository/process/lookup/index.ts [hunk 1]
```diff
@@ -379,7 +384,7 @@ function getFromVersion(
   config: LookupUpdateConfig,
   rangeStrategy: string,
   allVersions: string[]
-): string {
+): string | null {
```
Comment (rarkins) [inline lib/workers/repository/process/lookup/index.ts]: Is this change required?

Comment (djcsdy) [reply lib/workers/repository/process/lookup/index.ts]: No, but it’s an unambiguous improvement since the function was already capable of returning `null` and it’s helpful for the type to document that fact.

At the moment `strictNullChecks` is turned off in `tsConfig.json` for compatibility with the parts of renovate that are still written in JavaScript, but as you convert more of the code to TypeScript you probably want to work towards turning this option on to get better static type checking.

Comment (djcsdy) [reply lib/workers/repository/process/lookup/index.ts]: Also I wanted to make it clear from the type of the function that

```typescript
getFromVersion(config, rangeStrategy, nonDeprecatedVersions) ||
      getFromVersion(config, rangeStrategy, allVersions)
```

works because the first function call returns `null` if there are no matching non-deprecated versions.

**Comment by djcsdy** [comment]
> I thought about this more and for npm, we _should_ pin it to the same one as before, even if that one is deprecated. At the same time, I want to avoid any manager-specific code in this worker file because it should ideally be captured within lib/manager/*. Somehow we need a way to behave different for Cargo and npm here.

The behaviour with this change for Cargo *and* npm is:

1. If a lock file is present, pin to the version specified in the lockfile, don’t care if it is deprecated.
2. If there is no lock file, pin to the latest non-deprecated version that satisfies the version range, if possible. **This is the same version that npm or Cargo would resolve in this case**.
3. If there is no matching non-deprecated version, pin to the latest deprecated version that satisfies the version range.

Which part of this behaviour is not what you want for npm?

**Comment by rarkins** [comment]
@djcsdy thanks for the explanation. I hadn't realised about point (1) above.
