### PR TITLE
Use package-lock as shrinkwrap when maintaining shrinkwrap

### LINKED ISSUE #4772: packageLockMaintenance does not work for npm-shrinkwrap.json
**What Renovate type are you using?**

Self-hosted, but repro via GH app

**Describe the bug**

When `packageLockMaintenance` is enabled, a PR to upgrade the `npm-shrinkwrap.json` is not opened.

**Did you see anything helpful in debug logs?**

```
"ENOENT: no such file or directory, open '/mnt/renovate/gh/dominykas/test-things/npm-shrinkwrap.json'"
```

This is because running `npm install --package-lock-only` produces only the `package-lock.json`, not the `npm-shrinkwrap.json` (which got removed earlier).

**To Reproduce**

1. Config: `{ "lockFileMaintenance": { "enabled": true, "schedule": ["at any time"] } }`
2. Have a shrinkwrap
3. Renovate

Test build job: https://app.renovatebot.com/dashboard#github/dominykas/test-things/109551311

**Additional context**

In my testing, it seemed that it is enough to `mv package-lock.json npm-shrinkwrap.json` [before reading the lock file](https://github.com/renovatebot/renovate/blob/master/lib/manager/npm/post-update/npm.ts#L142) (if the `filename === 'npm-shrinkwrap.json'` ofc).

~~I'm happy to try to turn this into a PR.~~ Fix: https://github.com/renovatebot/renovate/pull/4776

### PR DESCRIPTION
**Pull request by dominykas**
Fixes https://github.com/renovatebot/renovate/issues/4772

When running the `lockFileMaintenance`, the lock file is removed before it gets recreated. When the lock file is not present, npm creates a `package-lock.json` by default, so we need to rename it to `npm-shrinkwrap.json` when we want to get an updated version.

---

I chose to move the file, although I can see that it probably does not matter - I could have probably just passed the `package-lock.json` instead of `filename` into `readFile()` for the use case, but I wasn't 100% sure that the file itself is really never used from the filesystem.

The `pathExistsSync(package-lock.json)` check is necessary, because the issue only exhibits itself when in `lockFileMaintenance` mode - when doing a regular dependency update, the `npm-shrinkwrap.json` is not removed, and so npm knows to update it, rather than create a new `package-lock.json`.

### CODE REVIEW

**Comment by rarkins** [comment]
I recalled fixing something like this before in Lerna. Found some code here: https://github.com/renovatebot/renovate/blob/331863d2110ce8858a61783b4b7af544563f29ad/lib/manager/npm/post-update/index.ts#L628-L634

I think either approach is ok, so let's go with the solution you made.

File: lib/manager/npm/post-update/npm.ts [hunk 1]
```diff
@@ -139,6 +139,15 @@ export async function generateLockFile(
     }
     const duration = process.hrtime(startTime);
     const seconds = Math.round(duration[0] + duration[1] / 1e9);
+    if (
+      filename === 'npm-shrinkwrap.json' &&
+      pathExistsSync(join(cwd, 'package-lock.json'))
```
Comment (rarkins) [inline lib/manager/npm/post-update/npm.ts]: Much preferred if we can await an async path exists function here instead of a sync one

Comment (dominykas) [reply lib/manager/npm/post-update/npm.ts]: https://github.com/renovatebot/renovate/pull/4776/commits/582955ad52a38bf733fd6c8e0cd141c7a400892d
