### PR TITLE
fix(pip_requirements): ignore extras in test for hashes

### LINKED ISSUE #16869: pip_requirements fails to update hashes on dependencies with extras
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.135.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab CE 15.1.3

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Given a requirements.txt file with (a.o.) the following entries, `pip_requirements` successfully updates the hashes for all dependencies except for `boto3-stubs`.  It does create a MR with the updated version, but fails to update the hashes as well.

```
boto3==1.24.36 \
    --hash=sha256:8844bbcb69ac0afc68225b58abe105852231cf1b562e6c8c9eb6b2b97fd4757a \
    --hash=sha256:b1855ede59e725b968d6336908ffc864b65985ca441d730625b09c43ccd6413b
    # via secretmanagement (./pyproject.toml)
boto3-stubs[iam]==1.24.36.post1 \
    --hash=sha256:39acbbc8c87a101bdf46e058fbb012d044b773b43f7ed02cc4c24192a564411e \
    --hash=sha256:ca3b3066773fc727fea0dbec252d098098e45fe0def011b22036ef674344def2
    # via secretmanagement (./pyproject.toml)
botocore==1.27.36 \
    --hash=sha256:3119ce186053b9bf6bd0bd0ad19a8cedeb626b205ce6ad26ea0894634f702cd5 \
    --hash=sha256:8109526f55742539d2311d742b40c89e65781ad18966e577dda360cd55c9d047
    # via
    #   boto3
    #   s3transfer
botocore-stubs==1.27.36 \
    --hash=sha256:277b62b74784998dadc23fcb28452bb956fe6e4c6b2499e58430c9260da2fc7e \
    --hash=sha256:f257f39308a56c9e9acf9805f0f282a556c0eed27c7d583c24e4a9884110297b
    # via boto3-stubs
```

I dug into the source code a bit. Just from reading, I think the error is in [line 31 of lib/modules/manager/pip_requirements/artifacts.ts](https://github.com/renovatebot/renovate/blob/b696abb3c2741508fbb4029f39153140a3722e1e/lib/modules/manager/pip_requirements/artifacts.ts#L31): The test for the presence of hashes expects that the dependency name is directly followed by `==`.  However, [line 112 of lib/modules/manager/pip_requirements/extract.ts](https://github.com/renovatebot/renovate/blob/b696abb3c2741508fbb4029f39153140a3722e1e/lib/modules/manager/pip_requirements/extract.ts#L112) stores only the package name (here: `boto3-stubs`) _without_ any extras (here: `[iam]`) in the dependency name. Therefore, the test evaluates to `false` even though there are hashes.

**Minimal repro** is available at [chludwig-haufe/renovate-pip-requirements-extras-repro](https://github.com/chludwig-haufe/renovate-pip-requirements-extras-repro). Therein, renovate created two PRs: chludwig-haufe/renovate-pip-requirements-extras-repro#1 updates the hashes as well, chludwig-haufe/renovate-pip-requirements-extras-repro#2 only updates the version number, not the hashes.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: packageFiles with updates (repository=library/gitlab-templates/secretsmanagement)
       "config": {
        // ..
        "pip_requirements": [
           {
             "packageFile": "build-image/requirements/base.txt",
             "deps": [
               // ...
              {
                 "depName": "boto3",
                 "currentValue": "==1.24.36",
                 "datasource": "pypi",
                 "currentVersion": "1.24.36",
                 "depIndex": 1,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "1.24.41",
                     "newValue": "==1.24.41",
                     "releaseTimestamp": "2022-07-29T19:17:37.000Z",
                     "newMajor": 1,
                     "newMinor": 24,
                     "updateType": "patch",
                     "isRange": true,
                     "branchName": "renovate/boto3-botocore-and-stubs"
                   }
                 ],
                 "warnings": [],
                 "versioning": "pep440",
                 "sourceUrl": "https://github.com/boto/boto3",
                 "isSingleVersion": true,
                 "fixedVersion": "1.24.36"
               },
              {
                 "depName": "boto3-stubs",
                 "currentValue": "==1.24.36.post1",
                 "datasource": "pypi",
                 "currentVersion": "1.24.36.post1",
                 "depIndex": 2,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "1.24.41",
                     "newValue": "==1.24.41",
                     "releaseTimestamp": "2022-07-29T19:24:47.000Z",
                     "newMajor": 1,
                     "newMinor": 24,
                     "updateType": "patch",
                     "isRange": true,
                     "branchName": "renovate/boto3-botocore-and-stubs"
                   }
                 ],
                 "warnings": [],
                 "versioning": "pep440",
                 "sourceUrl": "https://github.com/youtype/mypy_boto3_builder",
                 "isSingleVersion": true,
                 "fixedVersion": "1.24.36.post1"
               },
               // ...
             ]
           }
         ]
       }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by chludwig-haufe**
## Changes

Make the check in the `pip_requirements` manager whether a line contains a dependency with hashes ignore any extras between the dependency name and the equal signs.

## Context

Closes #16869

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/pip_requirements/artifacts.ts [hunk 1]
```diff
@@ -25,10 +28,13 @@ export async function updateArtifacts({
       .split(newlineRegex)
       .map((line) => line.trim());
     for (const dep of updatedDeps) {
+      const depName = dep.depName!;
```
Comment (PhilipAbed) [inline lib/modules/manager/pip_requirements/artifacts.ts:31]:
```suggestion
      if(!dep.Name) {continue;}
      const depName = dep.depName;
```

**Review by PhilipAbed — COMMENTED** [review]
looks good, thanks for the contribution!

File: lib/modules/manager/pip_requirements/artifacts.ts [hunk 2]
```diff
@@ -25,10 +28,13 @@ export async function updateArtifacts({
...
       const hashLine = lines.find(
         (line) =>
           // TODO: types (#7154)
-          line.startsWith(`${dep.depName!}==`) && line.includes('--hash=')
+          line.startsWith(depName) &&
+          extrasAndEqualsRegex.test(line.substring(depName.length)) &&
+          line.includes('--hash=')
```
Comment (PhilipAbed) [inline lib/modules/manager/pip_requirements/artifacts.ts:37]: instead of these 3 lines, can we create 1 regex that supports all lines?

File: lib/modules/manager/pip_requirements/artifacts.ts [hunk 3]
```diff
@@ -25,10 +28,13 @@ export async function updateArtifacts({
...
       );
       if (hashLine) {
         const depConstraint = hashLine.split(' ')[0];
```
Comment (PhilipAbed) [inline lib/modules/manager/pip_requirements/artifacts.ts:40]: then here we wouldnt just split, instead you can have capture naming groups and put the group name here to understand what we are really picking up

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 2 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts:37]: The `line.includes('--hash=')` won't be hard to cover by some regex. The dependency name is more problematic – it's a string we do not control and we either need to be 100% sure it does not contain any special characters or we need to escape it in the regex.

I am everything but a JavaScript or TypeScript expert. AFAIK – which boils down to the [regex chapter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) in the MSDN JavaScript guide – the JavaScript regex engine does not support the `\Q`/`\E` quotation escapes or a function like Python's `re.escape()`.  Is there some helper function in the renovate codebase that escapes a string so it matches exactly the input string and nothing else?

Besides, keeping the test for the dependency name separate means the regular expression needs to be compiled only once, not for every single dependency. I don't expect this will have a huge impact in the end, though.

Regarding `lines.find( (line) => ...`:  I don't think it is needed in a strict sense. We certainly could come up with a regex that also accounts for the whitespace [trimmed from each line](https://github.com/renovatebot/renovate/blob/0b0fbd6ee81965ad652c69b1ff9f80fc759e010f/lib/modules/manager/pip_requirements/artifacts.ts#L29) and make sure the regex matches within single lines only. I am not sure whether the resulting code would be easier to understand, though. (The majority of the developers I know consider regular expressions hard to read.) And, of course, I did not want to make more changes to the codebase than necessary.

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 1 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts:31]: Fine with me. The existing code base used the non-null assertion operator, that's why I kept it.

Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts:31]: Well, almost. Line 31 must read `if(!dep.depName) {continue;}`. :smile:

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 3 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts:40]: Understood. All I need to know is how to proceed with escaping the dependency name inside the regex. Then I can push a change that extracts all the necessary bits during the regex matching.

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 1 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts]: resolved in d540d0cf1fdb3e2621920edc50790f38ad65150e

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 2 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts:40]: resolved in d540d0cf1fdb3e2621920edc50790f38ad65150e

Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts:40]: Ok, I found `util.regex.escapeRegExp()`. I will give the single regex test a try.

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/pip_requirements/artifacts.ts]: There is a function to escape depname its used on depnames all over the code ill check it tomorrow

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 2 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts]: It's in e8eccbf48099da83b0b6cc15b441160e363fc65e. You can decide whether you prefer the previous version or this one that requires the reader to think a bit more about the regexp.

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 3 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts]: I already found the escape function. e8eccbf48099da83b0b6cc15b441160e363fc65e uses a named subgroup to extract the dependency constraint.

Comment (PhilipAbed) [reply lib/modules/manager/pip_requirements/artifacts.ts]: yup that's the one.

File: lib/modules/manager/pip_requirements/artifacts.ts [hunk 4]
```diff
@@ -4,8 +4,34 @@ import { logger } from '../../../logger';
...
+function dependencyAndHashPattern(depName: string): RegExp {
+  const escapedDepName = escapeRegExp(depName);
+
+  // extrasPattern covers any whitespace between the dep name and the optional extras specifier,
+  // but it does not cover any whitespace in front of the equal signs.
+  //
+  // Use a non-greedy wildcard for the range pattern; otherwise, we would
+  // include all but the last hash specifier into depConstraint.
+  return new RegExp(
+    `^\\s*(?<depConstraint>${escapedDepName}${extrasPattern}\\s*==.*?\\S)\\s+--hash=`,
```
Comment (PhilipAbed) [inline lib/modules/manager/pip_requirements/artifacts.ts:31]: we usually use `regex` instead of the actual RegExp all over the code, 
the regex functionality takes 2 types of inputs
either regex('your regex', 'flag')
or regex(`/your regex/flag`) 
maybe more check it out 

i always had trouble with the 'm' flag which means Multiline right? let me know if it works for you
i'm not sure why, but when i do the 'm' flag it will not split lines correctly for me, and will not catch anything, 
so i use the regex on the whole content as one big string, and if i want another row id just add `\n` to the regex

Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts:31]: No problem, it's changed. Should I set the parameter `useCache` to `false`? The expression will be different for every dependency. There might only be a small advantage to caching if the same dependency is used in multiple requirement files. (No idea whether they will then be processed within the same process, though...)

Yes, the flag `m` enables multiline-mode. (According to MDN, at least. :smile:) I updated the unit test so that the expression needs to match in the middle expression actually needs to match in the middle of the new package file content - the test passes. But, of course, I can also start the expression with `(?:^|\\n)` instead if you think it's more portable.

Regarding the test, I saw that the merge conflict will require some changes. I need to take a look at `test.exec-util.mockExecAll` before I can try to resolve the  conflict.

File: lib/modules/manager/pip_requirements/artifacts.spec.ts [hunk 5]
```diff
@@ -1,17 +1,28 @@
...
+import { fs, mockedFunction } from '../../../../test/util';
 import { GlobalConfig } from '../../../config/global';
+import { exec } from '../../../util/exec';
 import type { UpdateArtifactsConfig } from '../types';
 import { updateArtifacts } from '.';
 
 jest.mock('child_process');
 jest.mock('../../../util/exec');
 jest.mock('../../../util/fs');
+const mockedExec = mockedFunction(exec);
```
Comment (viceice) [inline lib/modules/manager/pip_requirements/artifacts.spec.ts:10]: remove, just call mockExecAll in test and match object after artifacts call. checkout

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 4 above)
Comment (PhilipAbed) [reply lib/modules/manager/pip_requirements/artifacts.ts:31]: As long as it works im fine with it xD test it on a real repo just to make sure.. looks good. U are doing great..

Comment (viceice) [reply lib/modules/manager/pip_requirements/artifacts.ts:31]: Use our regEx function and allow to cache (it's in memory only, shouldn't matter much).

- The `m` specifier makes `^`  to match start of line and `$` to match end of line
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags

so `^` is correct

File: lib/modules/manager/pip_requirements/artifacts.spec.ts (hunk 5 above)
Comment (viceice) [reply lib/modules/manager/pip_requirements/artifacts.spec.ts:10]: A good sample for using our exec mock

https://github.com/renovatebot/renovate/blob/1111b322f59aae97e5c54a550e5003946cf8bce9/lib/modules/manager/flux/artifacts.spec.ts#L62-L79

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 4 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts:31]: The unit tests cover both cases (dependency at the beginning of the package file and in the middle) and I ran a successful test on [chrludwig/renovate-pip-requirements-extras-repro](https://github.com/chrludwig/renovate-pip-requirements-extras-repro).

File: lib/modules/manager/pip_requirements/artifacts.spec.ts (hunk 5 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.spec.ts]: Thanks. And after reading the implementation of `mockExecAll` I understood what's happening.

In the end, it was most simple to accept the incoming `artifacts.spec.ts` during the merge "as is" and add my extra test cases in fe9d9161380cdf97c85eb6f7294897741e2dc061 again.

File: lib/modules/manager/pip_requirements/artifacts.ts [hunk 6]
```diff
@@ -21,17 +47,17 @@ export async function updateArtifacts({
...
+      const depAndHashMatch = dependencyAndHashPattern(dep.depName).exec(
+        rewrittenContent
       );
-      if (hashLine) {
-        const depConstraint = hashLine.split(' ')[0];
+      if (depAndHashMatch) {
+        // If there's a match, then the regular expression guarantees
+        // that the named subgroup deepConstraint did match as well.
+        const depConstraint = depAndHashMatch.groups!.depConstraint;
         cmd.push(`hashin ${depConstraint} -r ${packageFileName}`);
```
Comment (viceice) [inline lib/modules/manager/pip_requirements/artifacts.ts:61]:
```suggestion
        cmd.push(`hashin ${quote(depConstraint)} -r ${quote(packageFileName)}`);
```

needs import update
```ts
import { quote } from 'shlex';
```

File: lib/modules/manager/pip_requirements/artifacts.spec.ts [hunk 7]
```diff
@@ -54,53 +65,81 @@ describe('modules/manager/pip_requirements/artifacts', () => {
...
-          path: 'requirements.txt',
-          contents: 'new content',
+  it.each([
+    ['dependency w/o extras', 'atomicwrites', 'atomicwrites==1.4.0'],
+    [
+      'dependency with extras',
+      'boto3-stubs',
+      'boto3-stubs[iam] == 1.24.36.post1',
+    ],
+  ])(
```
Comment (viceice) [inline lib/modules/manager/pip_requirements/artifacts.spec.ts:75]: please use a single test and pass all values as `updatedDeps`. So that `updateArtifacts` should update all hashes , so you get three exec snapshots

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/modules/manager/pip_requirements/artifacts.ts (hunk 6 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.ts]: Done

File: lib/modules/manager/pip_requirements/artifacts.spec.ts (hunk 7 above)
Comment (chludwig-haufe) [reply lib/modules/manager/pip_requirements/artifacts.spec.ts]: Now you say it... Makes sense, of course. Done.

**Review by PhilipAbed — DISMISSED** [review]

**Review by viceice — DISMISSED** [review]

**Comment by chludwig-haufe** [comment]
I added a test that brings the test line coverage back to 100%.

Just as as side note (and maybe you are aware of this): The test `util/git/index › commitFiles({branchName, files, message}) › updates git submodules` kept failing on my machine (with the effect that the test coverage was always reported as < 100%) even though I had not touched any of the related files. In the end, I found the failure was somehow caused by the fact that I had a pre-commit hook [configured in the git init templates](https://pre-commit.com/#pre-commit-init-templatedir). Once I moved the hook template aside, the test succeeded locally as well. I did not look further into it, but maybe it's worth mentioning in your [local development docs](docs/development/local-development.md) that pre-commit templates can interfere with the tests.

**Review by viceice — APPROVED** [review]
