### PR TITLE
fix(manager/terraform): correctly extract oci charts

### LINKED ISSUE #21971: Terraform manager wrongly extracts oci charts
### How are you running Renovate?

Placeholder value, please select the correct response from the dropdown

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

Placeholder value, please select the correct response from the dropdown

### Describe the bug

Registry and repository are wrongly extracted, so renovate add the `v2/` path to wrong place.

```json
     {
        "deps": [
          {
            "currentValue": "8.9.1",
            "depType": "helm_release",
            "depName": "kube-prometheus",
            "datasource": "docker",
            "registryUrls": [
              "https://registry-1.docker.io/bitnamicharts"
            ],
            "updates": [],
            "packageName": "kube-prometheus",
            "warnings": [],
            "versioning": "docker",
            "registryUrl": "https://registry-1.docker.io/bitnamicharts",
            "currentVersion": "8.9.1",
            "fixedVersion": "8.9.1"
          }
        ],
        "packageFile": "terra/modules/devel/modules/core/prometheus.tf"
      },
```

No need for reproduction, can be reproduced with test case

```hcl
resource "helm_release" "prometheus" {
  name       = "kube-prometheus"
  repository = "oci://registry-1.docker.io/bitnamicharts"
  chart      = "kube-prometheus"
  version    = "8.9.1"
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: getLabels(https://registry-1.docker.io/bitnamicharts, kube-prometheus, 8.9.1)
DEBUG: getManifestResponse(https://registry-1.docker.io/bitnamicharts, kube-prometheus, 8.9.1, get)
...
DEBUG: Page Not Found https://registry-1.docker.io/bitnamicharts/v2/
DEBUG: Unknown Error looking up docker manifest
{
  "err": {
    "message": "page-not-found",
    "stack": "Error: page-not-found\n    at getAuthHeaders (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/common.js:47:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DockerDatasource.getManifestResponse (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:53:29)\n    at async DockerDatasource.getConfigDigest (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:124:34)\n    at async DockerDatasource.getLabels (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:226:34)\n    at async /home/ubuntu/renovateapp/node_modules/renovate/dist/util/cache/package/decorator.js:69:24\n    at async DockerDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:527:24)\n    at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n    at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:246:23)"
  },
  "registryHost": "https://registry-1.docker.io/bitnamicharts",
  "dockerRepository": "kube-prometheus",
  "tag": "8.9.1"
}
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

### PR DESCRIPTION
**Pull request by viceice**
## Changes
Currently oci charts are wrongly extracted when the chart repo is configured via `repository`.
The docker datasource will then add the `/v2/` api path to the wrong place. 

## Context
- fixes #21971
- regression of #20237

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/terraform/extractors/resources/helm-release.ts [hunk 1]
```diff
@@ -37,28 +38,31 @@ export class HelmReleaseExtractor extends DependencyExtractor {
...
-            helmRelease.repository.replace('oci://', 'https://'),
-          ];
-          dep.datasource = DockerDatasource.id;
-        } else {
-          dep.registryUrls = [helmRelease.repository];
-        }
-      }
-      if (!helmRelease.chart) {
+
+      dependencies.push(dep);
```
Comment (secustor) [inline lib/modules/manager/terraform/extractors/resources/helm-release.ts:42]: Why do you have moved this around?

**Review by secustor — APPROVED** [review]
