### PR TITLE
fix(terraform): wrong buildin provider lookup

### LINKED ISSUE #7519: terraform-provider: no updates for terraform-provider/docker
**What Renovate type, platform and version are you using?**

any >= 23.52.0

**Describe the bug**

can't update the following provider because of lookup failure:

```hcl
terraform {
  required_providers {
    docker = {
      source  = "terraform-providers/docker"
      version = "2.7.2"
    }
  }
  required_version = ">= 0.13"
}
```

**Relevant debug logs**

```
DEBUG: terraform-provider.getDependencies() (repository=viceice-tests/renovate-terraform)
       "lookupName": "terraform-providers/docker"
DEBUG: terraform-provider.getDependencies() (repository=viceice-tests/renovate-terraform)
       "lookupName": "terraform-providers/docker"
DEBUG: Datasource unknown error (repository=viceice-tests/renovate-terraform)
       "datasource": "terraform-provider",
       "lookupName": "terraform-providers/docker",
       "err": {
         "message": "Cannot read property 'versions' of undefined",
         "stack": "TypeError: Cannot read property 'versions' of undefined\n    at queryReleaseBackend (~\\renovate\\lib\\datasource\\terraform-provider\\index.ts:87:53)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.getReleases (~\\renovate\\lib\\datasource\\terraform-provider\\index.ts:124:11)\n    at async getRegistryReleases (~\\renovate\\lib\\datasource\\index.ts:55:15)\n    at async huntRegistries (~\\renovate\\lib\\datasource\\index.ts:83:13)\n    at async fetchReleases (~\\renovate\\lib\\datasource\\index.ts:189:15)\n    at async getPkgReleases (~\\renovate\\lib\\datasource\\index.ts:248:5)\n    at async lookupUpdates (~\\renovate\\lib\\workers\\repository\\process\\lookup\\index.ts:158:42)\n    at async fetchDepUpdates (~\\renovate\\lib\\workers\\repository\\process\\fetch.ts:44:26)\n    at async ~\\renovate\\node_modules\\p-map\\index.js:57:22"
       }
DEBUG: Failed to look up dependency docker (repository=viceice-tests/renovate-terraform, packageFile=new/versions.tf, dependency=docker)
```

**To Reproduce**

use https://github.com/viceice-tests/renovate-terraform

**Additional context**

I think it's a regression of #7396

### PR DESCRIPTION
**Pull request by viceice**
Fix regression, so buildin terrafrom provider can be updated again

closes #7519 
ref #7396

### CODE REVIEW

File: lib/datasource/terraform-provider/index.ts [hunk 1]
```diff
@@ -60,6 +60,7 @@ async function queryRegistry(
   const currentVersion = dep.releases.find((release) => {
     return res.version === release.version;
   });
+  // istanbul ignore else
```
Comment (rarkins) [inline lib/datasource/terraform-provider/index.ts:63]: I don't see any `else`

**Review by rarkins — APPROVED** [review]

File: lib/datasource/terraform-provider/index.ts (hunk 1 above)
Comment (viceice) [reply lib/datasource/terraform-provider/index.ts:63]: yes, but coverage thinks there is one, because we have no test for a falsy if. I don't think adding one makes an improvement here just to cover the non existing else branch
