### PR TITLE
fix(git): Don't fetch if push has failed

### LINKED ISSUE #13996: Do not git fetch branch after git push fails
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

If a push fails, then it returns null: https://github.com/renovatebot/renovate/blob/fbb0a01f156a8b60828b24f6b7ae3113b34277ff/lib/util/git/error.ts#L123-L128

Therefore this function returns null:
https://github.com/renovatebot/renovate/blob/fbb0a01f156a8b60828b24f6b7ae3113b34277ff/lib/util/git/index.ts#L690-L695

And then this function blindly calls fetch:
https://github.com/renovatebot/renovate/blob/2a013b3c2500140dce11a2136cab48b2576d4ef6/lib/util/git/index.ts#L861-L870

### Relevant debug logs

<details><summary>Logs</summary>

```
{"level":20,"branch":"renovate/google-4.x","msg":"Preparing files for commiting to branch renovate/google-4.x","time":"2022-02-04T07:52:33.105Z"}
{"level":20,"branch":"renovate/google-4.x","deletedFiles":[],"ignoredFiles":[],"result":{"author":null,"branch":"renovate/google-4.x","commit":"0d69417","root":false,"summary":{"changes":1,"insertions":1,"deletions":1}},"msg":"git commit","time":"2022-02-04T07:52:33.417Z"}
{"level":20,"branch":"renovate/google-4.x","msg":"Pushing branch renovate/google-4.x","time":"2022-02-04T07:52:33.462Z"}
{"level":30,"branch":"renovate/google-4.x","msg":"Branch update was rejected because local copy is not up-to-date.","time":"2022-02-04T07:52:33.840Z"}
{"level":20,"branch":"renovate/google-4.x","msg":"Fetching branch renovate/google-4.x","time":"2022-02-04T07:52:33.840Z"}
{"level":20,"branch":"renovate/google-4.x","err":{"task":{"commands":["fetch","origin","refs/heads/renovate/google-4.x:refs/remotes/origin/renovate/google-4.x","--force"],"format":"utf-8","parser":"[function]"},"message":"fatal: couldn't find remote ref refs/heads/renovate/google-4.x\n","stack":"Error: fatal: couldn't find remote ref refs/heads/renovate/google-4.x\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/cjs/index.js:1194:25)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/cjs/index.js:1229:29)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/cjs/index.js:1589:43\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/cjs/index.js:1587:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/cjs/index.js:1571:44)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/cjs/index.js:55:24)"},"msg":"Unknown error committing files","time":"2022-02-04T07:52:34.497Z"}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by zharinov**
## Context:

- Closes: #13996

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/git/index.ts [hunk 1]
```diff
@@ -862,11 +864,13 @@ export async function commitFiles(
   config: CommitFilesConfig
 ): Promise<CommitSha | null> {
   const commitResult = await prepareCommit(config);
-  if (!commitResult) {
-    return null;
+  if (commitResult) {
+    const pushResult = await pushCommit(config);
+    if (pushResult) {
+      return fetchCommit(config);
+    }
```
Comment (zharinov) [inline lib/util/git/index.ts:871]: Isn't as linear, but doesn't break coverage.
I'll try to come up with unit test in further PR.

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
