### PR TITLE
fix(poetry): wrong version parts extraction

### LINKED ISSUE #8740: Invalid Version error running Renovate 24.52.0 against Poetry project
**What Renovate type, platform and version are you using?**

Gitlab configured using template: https://gitlab.com/renovate-bot/renovate-runner

**Describe the bug**

When I run Renovate version 24.52.0 against my Poetry project I get an error like

This does not occur with Renovate version 24.49.9

**Relevant debug logs**
```
ERROR: Repository has unknown error (repository=hunter2.app/hunter2)
       "err": {
         "message": "Invalid Version: 1.9",
         "stack": "TypeError: Invalid Version: 1.9\n    at new SemVer (/usr/src/app/node_modules/semver/classes/semver.js:38:13)\n    at Object.major [as getMajor] (/usr/src/app/node_modules/semver/functions/major.js:2:29)\n    at Object.lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:295:30)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:44:26)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       }
```

I don't see any more in the debug logs than quoted above other than one line indicating the package being looked at:
```
DEBUG: Returning cached datasource response (repository=hunter2.app/hunter2)
       "cacheKey": "pypi https://pypi.org/pypi/ lupa"
ERROR: Repository has unknown error (repository=hunter2.app/hunter2)
       "err": {
         "message": "Invalid Version: 1.9",
         "stack": "TypeError: Invalid Version: 1.9\n    at new SemVer (/usr/src/app/node_modules/semver/classes/semver.js:38:13)\n    at Object.major [as getMajor] (/usr/src/app/node_modules/semver/functions/major.js:2:29)\n    at Object.lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:295:30)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:44:26)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       }
```

**Have you created a minimal reproduction repository?**

I've not managed to create a minimal reproducer. I suspect it needs some specific state in the lockfile which I can't quite produce minimally.

It's exhibited by the repo here:
https://gitlab.com/hunter2.app/hunter2

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

It looks like this might be caused by https://github.com/renovatebot/renovate/pull/8672
It seems like it might be unconditionally expecting version numbers to be semantic versions and tripping over the two-part version of this dependency.

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

Poetry allows invalid semver short versions (eg, falls back to pep440) but renovate will fail to use it.
So this pr allows short versions. `1.9` is now internally padded to `1.9.0`.

test: https://github.com/viceice-tests/hunter2/pull/2

## Context:
fixes #8740

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/versioning/poetry/index.ts [hunk 1]
```diff
@@ -43,13 +66,29 @@ function npm2poetry(input: string): string {
...
+
 const isLessThanRange = (version: string, range: string): boolean =>
   npm.isLessThanRange(version, poetry2npm(range));
 
 export const isValid = (input: string): string | boolean =>
   npm.isValid(poetry2npm(input));
 
-const isVersion = (input: string): string | boolean => npm.isVersion(input);
+const isStable = (version: string): boolean =>
+  version && npm.isStable(padZeroes(version));
```
Comment (rarkins) [inline lib/versioning/poetry/index.ts:88]: pep440 stability is different to npm, so this won't be perfect

**Review by rarkins — APPROVED** [review]
