### PR TITLE
fix(git): convert to config validation errors

### LINKED ISSUE #10729: Catch and warn when GitLab rejects git push with "not a member of team"
```
DEBUG: Converting git error to ExternalHostError (repository=company/map, branch=renovate/pin-dependencies)
       "err": {
         "task": {
           "commands": [
             "push",
             "origin",
             "renovate/pin-dependencies:renovate/pin-dependencies",
             "--force",
             "-u",
             "--no-verify",
             "--verbose",
             "--porcelain"
           ],
           "format": "utf-8"
         },
         "message": "To https://**redacted**@renovateapp.com' is not a member of team\nerror: failed to push some refs to 'https://git.company.com/company/map.git'\n",
         "stack": "Error: To https://**redacted**@renovateapp.com' is not a member of team\nerror: failed to push some refs to 'https://git.company.com/company/map.git'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
       }
```
There is a clear message what happens. Next time trim the logs to at least the failing repo and not the full log.

It seems the renovate user has not enough rights on the `company/map` repo

_Originally posted by @viceice in https://github.com/renovatebot/renovate/discussions/10680#discussioncomment-948027_

### PR DESCRIPTION
**Pull request by viceice**
## Changes:
Converted some git errors to config validation errors, so users have more visibillity for them.

## Context:

fixes #10729

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
Thinking if we should treat this errors as config error too:
https://github.com/renovatebot/renovate/blob/a7d10ac7fcfda2b88e7fa20baf05123b13b26f3d/lib/util/git/index.ts#L68-L68
https://github.com/renovatebot/renovate/blob/a7d10ac7fcfda2b88e7fa20baf05123b13b26f3d/lib/util/git/index.ts#L72-L72

File: lib/util/git/index.ts [hunk 1]
```diff
@@ -96,6 +94,14 @@ function checkForPlatformFailure(err: Error): void {
       'GitLab: Commit message does not follow the pattern',
       "Cannot push because commit message does not follow project's push rules",
     ],
+    [
+      ' is not a member of team',
```
Comment (HonkingGoose) [inline lib/util/git/index.ts:98]:
```suggestion
      ' is not a member of the team',
```

Maybe this would be better? Or are we doing something like this in the final message output:

` userName is not a member of team teamNameVariable`

File: lib/util/git/index.ts [hunk 2]
```diff
@@ -96,6 +94,14 @@ function checkForPlatformFailure(err: Error): void {
...
+      '`Restrict commits to existing GitLab users` rule is blocking renovate push. Check renovate `gitAuthor` setting',
```
Comment (HonkingGoose) [inline lib/util/git/index.ts:99]:
```suggestion
      'The `restrict commits to existing GitLab users` rule is blocking Renovate push. Check the Renovate `gitAuthor` setting',
```

Maybe we should capitalize our branding name. 😉

File: lib/util/git/index.ts [hunk 3]
```diff
@@ -96,6 +94,14 @@ function checkForPlatformFailure(err: Error): void {
...
+    ],
+    [
+      'TF401027:', // You need the Git 'GenericContribute' permission to perform this action
+      'You need the Git `GenericContribute` permission to perform this action',
```
Comment (HonkingGoose) [inline lib/util/git/index.ts:103]:
```suggestion
      'You need the Git `GenericContribute` permission to perform this action, do .... to fix the problem',
```

Maybe we can help users fix this by pointing them to the docs they need to fix this?
It feels a little unhelpful the way it is now. 😄

**Review by HonkingGoose — COMMENTED** [review]
Just some minor things/thoughts.

File: lib/util/git/index.ts (hunk 1 above)
Comment (viceice) [reply lib/util/git/index.ts:98]: Nope, the first line is the matching git error and the second line is the error message to show. so no changes on first array member. 🙃 

I'll refactor to objects, so it's more clear how it works. 😉

File: lib/util/git/index.ts (hunk 2 above)
Comment (viceice) [reply lib/util/git/index.ts:99]:
```suggestion
      'The `Restrict commits to existing GitLab users` rule is blocking Renovate push. Check the Renovate `gitAuthor` setting',
```

Uppercase for the rule, as it's named lie that?

File: lib/util/git/index.ts (hunk 3 above)
Comment (viceice) [reply lib/util/git/index.ts:103]: @JamieMagee  Do you now how to fix the permission issue in azure devops? As this is a server side permission issue.

**Comment by HonkingGoose** [comment]
I like the refactored code! It's easier to understand what each item means now! 😉

**Review by rarkins — APPROVED** [review]
