### PR TITLE
fix(gomod): treat v0 pseudo version updates as digest updates

### LINKED ISSUE #29034: Gomod dependency updates type are now patch (where digest before)
### Discussed in https://github.com/renovatebot/renovate/discussions/29033

<div type='discussions-op-text'>

<sup>Originally posted by **aerialls** May 13, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab with the latest Renovate version

### Please tell us more about your question or problem

Hello,
Not sure this is a bug but I found a change of behavior introduced in 37.327.1 using the `gomod` manager. Updates from the module `google.golang.org/genproto/googleapis/rpc` are found of type `patch` as of before version 37.327.1, the type `digest` was returned. 

A full working repository is available at https://github.com/aerialls/renovate-gomod. I've also attached in the README the log from both versions to highlight the change of `updateType`

## 37.327.0

Check the `updateType`.
```
DEBUG: Branch summary (repository=api-gateway/test)
       "cacheModified": undefined,
       "baseBranches": [{"branchName": "master", "sha": "d3b2a5c7e83004dc75ef21de93d6e95e618e15c4"}],
       "branches": [],
       "defaultBranch": "master",
       "inactiveBranches": ["renovate/google.golang.org-genproto-googleapis-rpc-digest"]
DEBUG: branches info extended (repository=api-gateway/test)
       "branchesInformation": [
         {
           "branchName": "renovate/google.golang.org-genproto-googleapis-rpc-digest",
           "prNo": null,
           "prTitle": "chore(deps): update google.golang.org/genproto/googleapis/rpc digest to 6275950",
           "result": "no-work",
           "upgrades": [
             {
               "datasource": "go",
               "depName": "google.golang.org/genproto/googleapis/rpc",
               "displayPending": "",
               "fixedVersion": "v0.0.0-20240506185236-b8a5c65736ae",
               "currentVersion": "v0.0.0-20240506185236-b8a5c65736ae",
               "currentValue": "v0.0.0-20240506185236-b8a5c65736ae",
               "currentDigest": "b8a5c65736ae",
               "newValue": "v0.0.0-20240506185236-b8a5c65736ae",
               "newDigest": "62759503f4344226051f4e24858a7517e45b4ae6",
               "packageFile": "go.mod",
               "updateType": "digest",
               "packageName": "google.golang.org/genproto/googleapis/rpc"
             }
           ]
         }
       ]
```

## 37.327.1

Check the `updateType`.

```
DEBUG: Branch summary (repository=api-gateway/test)
       "cacheModified": undefined,
       "baseBranches": [{"branchName": "master", "sha": "d3b2a5c7e83004dc75ef21de93d6e95e618e15c4"}],
       "branches": [],
       "defaultBranch": "master",
       "inactiveBranches": ["renovate/google.golang.org-genproto-googleapis-rpc-0.x"]
DEBUG: branches info extended (repository=api-gateway/test)
       "branchesInformation": [
         {
           "branchName": "renovate/google.golang.org-genproto-googleapis-rpc-0.x",
           "prNo": null,
           "prTitle": "chore(deps): update module google.golang.org/genproto/googleapis/rpc to v0.0.0-20240509183442-62759503f434",
           "result": "no-work",
           "upgrades": [
             {
               "datasource": "go",
               "depName": "google.golang.org/genproto/googleapis/rpc",
               "displayPending": "",
               "fixedVersion": "v0.0.0-20240506185236-b8a5c65736ae",
               "currentVersion": "v0.0.0-20240506185236-b8a5c65736ae",
               "currentValue": "v0.0.0-20240506185236-b8a5c65736ae",
               "currentDigest": "b8a5c65736ae",
               "newValue": "v0.0.0-20240509183442-62759503f434",
               "newVersion": "v0.0.0-20240509183442-62759503f434",
               "newDigest": "62759503f434",
               "packageFile": "go.mod",
               "updateType": "patch",
               "packageName": "google.golang.org/genproto/googleapis/rpc"
             }
           ]
         }
       ]
```</div>

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

Based on minor, major and patch changes, detect `digest` update type.

## Context

- Closes: #29034

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

File: lib/workers/repository/process/lookup/generate.ts [hunk 1]
```diff
@@ -68,8 +69,30 @@ export async function generateUpdate(
...
+  }
+
+  const newMinor = versioning.getMinor(newVersion);
+  if (is.number(newMinor)) {
+    update.newMinor = newMinor;
+  }
+
+  const newPatch = versioning.getPatch(newVersion);
+
+  // istanbul ignore next
```
Comment (viceice) [inline lib/workers/repository/process/lookup/generate.ts:85]: we should have a test instead to not break it again in future

**Review by viceice — COMMENTED** [review]
otherwise LGTM

File: lib/workers/repository/process/lookup/generate.ts (hunk 1 above)
Comment (zharinov) [reply lib/workers/repository/process/lookup/generate.ts:85]: Yes, but I can't come up with test that really checks this specific behavior across datasource/lookup mechanism, and not just provides the wrong confidence. The original regression occurred exactly because it's not easy testable.

Comment (rarkins) [reply lib/workers/repository/process/lookup/generate.ts:85]: But can't it be a simple test with two v0.0.0- versions?

Comment (zharinov) [reply lib/workers/repository/process/lookup/generate.ts:85]: I didn't want to make it too specific, e.g. checking for particular datasource or manager. But actually maybe it's the best option in this conditions, because at least we'll know it's related to the `go` ecosystem, which isn't obvious when `updates` array length was checked for emptiness.

Comment (rarkins) [inline lib/workers/repository/process/lookup/generate.ts:85]:
```suggestion
```

**Review by rarkins — CHANGES_REQUESTED** [review]
I think you need to check both versions start with v0.0.0, to be safest

**Review by rarkins — CHANGES_REQUESTED** [review]
Wouldn't it be more logical to locate this in the getBucket() function? I assume it won't happen in practice but in theory you could have both digest and patch updates separately

**Comment by zharinov** [comment]
> Wouldn't it be more logical to locate this in the getBucket() function? I assume it won't happen in practice but in theory you could have both digest and patch updates separately

I saw `getBucket()` function, but it returns strings, so I'm not sure. Seems like there is no solution which isn't ugly, but maybe `generateUpdate()` is the better place. IMO it doesn't matter as far as we make it clear: this `if`-statement is the workaround.

**Comment by rarkins** [comment]
I realized that this would require us changing in both getBucket() and getUpdateType(), and both changes would still be essentially "hardcoded logic for go", so we may as well stick with the proposed solution here

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
