### PR TITLE
fix: error gracefully when .editorconfig parsing fails

### LINKED ISSUE #18540: Onboarding error with .editorconfig present
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.241.4

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab 15.4.2 EE

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Since Renovate 32.241.4, onboarding a project with the following `.editorconfig` fails:

```editorconfig
#
# .editorconfig
#
# http://editorconfig.org
#
# The EditorConfig project consists of a file format for defining coding styles
# and a collection of text editor plugins that enable editors to read the file
# format and adhere to defined styles.
#

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
indent_style = space
indent_size = 4
insert_final_newline = true

# package.json specific rules
[package.json]
indent_size = 2

# .yml specific rules
[*.yml]
indent_size = 2
```

This worked prior to 32.241.4, so it's probably a side-effect of the `editorconfig` dependency update at #18427.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found gitlabci package files (repository=xxx/yyy)
DEBUG: Found npm package files (repository=xxx/yyy)
DEBUG: Found 3 package file(s) (repository=xxx/yyy)
DEBUG: Need to create onboarding PR (repository=xxx/yyy)
DEBUG: createOnboardingBranch() (repository=xxx/yyy)
ERROR: Repository has unknown error (repository=xxx/yyy)
       "err": {
         "message": "unreachable",
         "stack": "RuntimeError: unreachable\n    at null.<anonymous> (wasm://wasm/00051056:1:55953)\n    at null.<anonymous> (wasm://wasm/00051056:1:62171)\n    at null.<anonymous> (wasm://wasm/00051056:1:70209)\n    at null.<anonymous> (wasm://wasm/00051056:1:70338)\n    at null.<anonymous> (wasm://wasm/00051056:1:69214)\n    at null.<anonymous> (wasm://wasm/00051056:1:17561)\n    at null.<anonymous> (wasm://wasm/00051056:1:47453)\n    at null.<anonymous> (wasm://wasm/00051056:1:58421)\n    at null.<anonymous> (wasm://wasm/00051056:1:54915)\n    at module.exports.parse_to_uint32array (/usr/src/app/node_modules/@one-ini/wasm/one_ini.js:235:14)\n    at parseBuffer (/usr/src/app/node_modules/editorconfig/lib/index.js:58:52)\n    at processFileContents (/usr/src/app/node_modules/editorconfig/lib/index.js:234:25)\n    at getConfig (/usr/src/app/node_modules/editorconfig/lib/index.js:272:12)\n    at getAllConfigs (/usr/src/app/node_modules/editorconfig/lib/index.js:310:24)\n    at parse (/usr/src/app/node_modules/editorconfig/lib/index.js:440:21)\n    at Function.getCodeFormat (/usr/src/app/node_modules/renovate/lib/util/json-writer/editor-config.ts:10:24)\n    at getOnboardingConfigContents (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/config.ts:89:22)\n    at createOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/create.ts:21:20)\n    at checkOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/index.ts:65:20)\n    at getRepoConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/config.ts:15:12)"
       }
DEBUG: Unknown res (repository=xxx/yyy)
       "res": "unknown-error"
DEBUG: Repository result: unknown-error, status: unknown, enabled: undefined, onboarded: undefined (repository=xxx/yyy)
```

</details>

Formatted error message with stacktrace:

```
RuntimeError: unreachable
    at null.<anonymous> (wasm://wasm/00051056:1:55953)
    at null.<anonymous> (wasm://wasm/00051056:1:62171)
    at null.<anonymous> (wasm://wasm/00051056:1:70209)
    at null.<anonymous> (wasm://wasm/00051056:1:70338)
    at null.<anonymous> (wasm://wasm/00051056:1:69214)
    at null.<anonymous> (wasm://wasm/00051056:1:17561)
    at null.<anonymous> (wasm://wasm/00051056:1:47453)
    at null.<anonymous> (wasm://wasm/00051056:1:58421)
    at null.<anonymous> (wasm://wasm/00051056:1:54915)
    at module.exports.parse_to_uint32array (/usr/src/app/node_modules/@one-ini/wasm/one_ini.js:235:14)
    at parseBuffer (/usr/src/app/node_modules/editorconfig/lib/index.js:58:52)
    at processFileContents (/usr/src/app/node_modules/editorconfig/lib/index.js:234:25)
    at getConfig (/usr/src/app/node_modules/editorconfig/lib/index.js:272:12)
    at getAllConfigs (/usr/src/app/node_modules/editorconfig/lib/index.js:310:24)
    at parse (/usr/src/app/node_modules/editorconfig/lib/index.js:440:21)
    at Function.getCodeFormat (/usr/src/app/node_modules/renovate/lib/util/json-writer/editor-config.ts:10:24)
    at getOnboardingConfigContents (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/config.ts:89:22)
    at rebaseOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/rebase.ts:31:20)
    at checkOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/index.ts:38:20)
    at getRepoConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/config.ts:15:12)
```

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes

added try catch and a test with customer's file

## Context

- Closes #18540

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/json-writer/editor-config.ts [hunk 1]
```diff
@@ -1,18 +1,27 @@
...
     const { localDir } = GlobalConfig.get();
-    const knownProps = await parse(upath.join(localDir, fileName));
-
-    return {
-      indentationSize: EditorConfig.getIndentationSize(knownProps),
-      indentationType: EditorConfig.getIndentationType(knownProps),
-    };
+    let knownProps = undefined;
+    try {
+      knownProps = await parse(upath.join(localDir, fileName));
```
Comment (viceice) [inline lib/util/json-writer/editor-config.ts:13]:
```suggestion
      const knownProps = await parse(upath.join(localDir, fileName));
```

File: lib/util/json-writer/editor-config.ts [hunk 2]
```diff
@@ -1,18 +1,27 @@
...
 export class EditorConfig {
   public static async getCodeFormat(fileName: string): Promise<CodeFormat> {
     const { localDir } = GlobalConfig.get();
-    const knownProps = await parse(upath.join(localDir, fileName));
-
-    return {
-      indentationSize: EditorConfig.getIndentationSize(knownProps),
-      indentationType: EditorConfig.getIndentationType(knownProps),
-    };
+    let knownProps = undefined;
```
Comment (viceice) [inline lib/util/json-writer/editor-config.ts:11]:
```suggestion
```

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/util/json-writer/editor-config.ts [hunk 3]
```diff
@@ -1,18 +1,27 @@
...
+      return {
+        indentationSize: EditorConfig.getIndentationSize(knownProps),
+        indentationType: EditorConfig.getIndentationType(knownProps),
+      };
+    } catch (err) {
+      logger.warn({ err }, 'Failed to parse editor config');
+      return {
+        indentationSize: undefined,
+        indentationType: undefined,
+      };
```
Comment (viceice) [inline lib/util/json-writer/editor-config.ts:23]:
```suggestion
      return { };
```

look cleaner to me

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
