### PR TITLE
fix(poetry): better getNewValue replace

### LINKED ISSUE #9256: Fails to detect new Python coverage version with invalid version warning
**What Renovate type, platform and version are you using?**

We are using the latest Docker tag for self-hosting Renovate (renovate/renovate:24.93.1) with Gitlab. The issue is also reproducible on Github with the managed app.

**Describe the bug**

https://github.com/languitar/renovate-coverage-reproduction is a reproduction case of the issue. A Python project contains an outdated version of the `coverage` package. Automatic updates fail. The reproduction repo show the error detecting the new version as `WARN: getNewValue error` in the dashboard issue.

**Relevant debug logs**

In the self-hosted case, this warning can be found for repos using coverage:

```
 WARN: getNewValue error (repository=xxx)
       "err": {
         "message": "Invalid Version: 5.5",
         "stack": "TypeError: Invalid Version: 5.5\n    at new SemVer (/usr/src/app/node_modules/semver/classes/semver.js:38:13)\n    at Object.major (/usr/src/app/node_modules/semver/functions/major.js:2:29)\n    at Object.getNewValue (/usr/src/app/node_modules/renovate/lib/versioning/npm/range.ts:104:26)\n    at Object.getNewValue (/usr/src/app/node_modules/renovate/lib/versioning/poetry/index.ts:150:25)\n    at Object.lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:214:38)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:44:13)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       },
       "currentValue": "^5.0.3",
       "rangeStrategy": "replace",
       "currentVersion": "5.3.1",
       "newVersion": "5.5"
```

Looks like SemVer should not be assumed for PyPi dependencies as PEP 440 allows omitting parts: https://www.python.org/dev/peps/pep-0440/#public-version-identifiers

**Have you created a minimal reproduction repository?**

https://github.com/languitar/renovate-coverage-reproduction

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Adds logic to check if a massaged new version satisfies the existing range, and returns the range if so before doing other evaluation.

## Context:

Fixes #9256

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/versioning/poetry/index.ts [hunk 1]
```diff
@@ -130,6 +131,20 @@ function getNewValue({
...
+        npm.isVersion(massagedNewVersion) &&
+        npm.matches(massagedNewVersion, npmCurrentValue)
+      ) {
+        return currentValue;
+      }
+    } catch (err) /* istanbul ignore next */ {
+      logger.info(
+        { err },
+        'Poetry versioning: Error caught checking if newVersion satisfies currentValue'
+      );
```
Comment (viceice) [inline lib/versioning/poetry/index.ts:146]: When will this happen? Shouldn't be better have a test?

Comment (rarkins) [reply lib/versioning/poetry/index.ts:146]: I'm not aware of any case that can trigger it, so it's there purely defensively. I don't want to make it a WARN in case it happens a lot.. in that case I'll check the app logs once deployed for any logs of this and try to fix.

**Review by viceice — APPROVED** [review]
