### PR TITLE
fix(pr): wrong release notes when releases found in URLs

### LINKED ISSUE #4618: Wrong release notes in PR body
**What Renovate type are you using?**
GitHub App

**Describe the bug**
There are two changelogs (v2.0.1 and v2.0.2) in this PR, but both content are same.

> v3.0.2
> Compare Source
> Bug Fixes
> - do not encodeURIComponent the domain (3e5fbec), closes #​53
> 
> v3.0.1
> Compare Source
> Bug Fixes
> - do not encodeURIComponent the domain (3e5fbec), closes #​53
> 
> https://github.com/teppeis/thank-you-stars/pull/152

The original changelog: https://github.com/npm/hosted-git-info/blob/latest/CHANGELOG.md

**Expected behavior**

> v3.0.2
> Compare Source
> Bug Fixes
> - do not encodeURIComponent the domain (3e5fbec), closes #​53
> 
> v3.0.1
> Compare Source
> Bug Fixes
> - update pathmatch for gitlab (e3e3054), closes #52
> - updated pathmatch for gitlab (fa87af7)

**Another example**

https://github.com/teppeis/duck/pull/246

### PR DESCRIPTION
**Pull request by ViralRuparel**
Fixes the issue of wrong release notes in PR body. Issue occurred when the CHANGELOG.md had an url linked with the version, due to which it had matching version two times, one in the actual version `[v3.0.3]` and another was when it had version number in the link url eg. `(https://github.com/npm/hosted-git-info/compare/v3.0.3...v3.0.4)`

Closes #4618

### CODE REVIEW

**Comment by ViralRuparel** [comment]
BEFORE
image
AFTER
image

**Comment by rarkins** [comment]
Needs at least one test added. Should be one that fails on master but passes one this branch.

File: lib/workers/pr/changelog/release-notes.ts [hunk 1]
```diff
@@ -179,14 +179,15 @@ export async function getReleaseNotesMd(
     if (changelogParsed.length >= 2) {
       for (const section of changelogParsed) {
         try {
-          const [heading] = section.split('\n');
+          const [heading] = section.replace(/[[\]()]/g, ' ').split('\n');
```
Comment (rarkins) [inline lib/workers/pr/changelog/release-notes.ts]: We need to make this more understandable for anyone in future reading it. This can be done either with comments, or by breaking it up into multiple steps with meaningful variable names, or a combination of both. Of course, tests help too.

File: lib/workers/pr/changelog/release-notes.ts [hunk 2]
```diff
@@ -179,14 +179,15 @@ export async function getReleaseNotesMd(
...
           const title = heading
             .replace(/^\s*#*\s*/, '')
             .split(' ')
             .filter(Boolean);
           let body = section.replace(/.*?\n(-{3,}\n)?/, '').trim();
           for (const word of title) {
-            if (word.includes(version)) {
+            const isUrl = /^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([-.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/gm;
```
Comment (rarkins) [inline lib/workers/pr/changelog/release-notes.ts]: Is there may be a better way to approach this? e.g. can we simply use URL.parse and see if it succeeds?

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/workers/pr/changelog/release-notes.ts (hunk 1 above)
Comment (ViralRuparel) [reply lib/workers/pr/changelog/release-notes.ts]: Sure, will do that

File: lib/workers/pr/changelog/release-notes.ts (hunk 2 above)
Comment (ViralRuparel) [reply lib/workers/pr/changelog/release-notes.ts]: let me check that, and will correct it.

File: .github/workflows/build.yml [hunk 3]
```diff
@@ -302,4 +303,4 @@ jobs:
           npx semantic-release --dry-run ${{github.ref != 'refs/heads/master'}} --ci ${{github.ref == 'refs/heads/master'}}
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
Comment (rarkins) [inline .github/workflows/build.yml]: @ViralRuparel looks like a bad merge here, you should probably revert your changes to this file

File: lib/workers/pr/changelog/release-notes.ts [hunk 4]
```diff
@@ -179,14 +180,17 @@ export async function getReleaseNotesMd(
...
+          const deParenthesizedSection = section.replace(/[[\]()]/g, ' ');
+          const [heading] = deParenthesizedSection.split('\n');
           const title = heading
             .replace(/^\s*#*\s*/, '')
             .split(' ')
             .filter(Boolean);
           let body = section.replace(/.*?\n(-{3,}\n)?/, '').trim();
           for (const word of title) {
-            if (word.includes(version)) {
+            // const isUrl = /^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([-.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/gm;
```
Comment (rarkins) [inline lib/workers/pr/changelog/release-notes.ts]:
```suggestion
```

Comment (rarkins) [reply lib/workers/pr/changelog/release-notes.ts]: Remove this

File: lib/workers/pr/changelog/release-notes.ts [hunk 5]
```diff
@@ -179,14 +180,17 @@ export async function getReleaseNotesMd(
...
+            if (word.includes(version) && !URL.parse(word).hostname) {
```
Comment (rarkins) [inline lib/workers/pr/changelog/release-notes.ts]: `URL.parse()` can throw - see https://nodejs.org/docs/latest-v12.x/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost

So please make a function `isUrl` that includes try/catch to be safest

**Review by rarkins — CHANGES_REQUESTED** [review]

File: .github/workflows/build.yml (hunk 3 above)
Comment (ViralRuparel) [reply .github/workflows/build.yml]: yes something went wrong while merging, let me fix!

File: lib/workers/pr/changelog/release-notes.ts (hunk 4 above)
Comment (ViralRuparel) [reply lib/workers/pr/changelog/release-notes.ts]: okay

File: lib/workers/pr/changelog/release-notes.ts (hunk 5 above)
Comment (ViralRuparel) [reply lib/workers/pr/changelog/release-notes.ts]: sure

**Comment by ViralRuparel** [comment]
In master branch:
image
In this branch:
image

File: lib/workers/pr/changelog/release-notes.ts [hunk 6]
```diff
@@ -130,6 +131,17 @@ function sectionize(text: string, level: number): string[] {
   return result;
 }
 
+function isUrl(url: string): boolean {
+  try {
+    return !!URL.parse(url).hostname;
+  } catch (err) {
+    // istanbul ignore next
+    logger.warn({ err }, `Error parsing ${url} in URL.parse`);
```
Comment (rarkins) [inline lib/workers/pr/changelog/release-notes.ts]:
```suggestion
    logger.debug({ err }, `Error parsing ${url} in URL.parse`);
```

This is not something people should be concerned about

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/workers/pr/changelog/release-notes.ts (hunk 6 above)
Comment (ViralRuparel) [reply lib/workers/pr/changelog/release-notes.ts]: okay!
