### PR TITLE
fix(manager/go): fix replace block regex 

### LINKED ISSUE #15369: go.sum update fails if go.mod contains a comment with a version
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.33.1

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

The problem occurs if the go.mod file contains a comment line that contains a semver tag.
Pls have a look at [my example repo](https://github.com/brumhard/renovate-issue) to see the issue.

### Relevant debug logs

From https://github.com/brumhard/renovate-issue/pull/4:

<details><summary>Logs</summary>

```
Command failed: go get -d -t ./...
go: errors parsing go.mod:
/tmp/renovate/repos/github/brumhard/renovate-issue/go.mod:15:2: unknown directive: go.uber.org/zap
/tmp/renovate/repos/github/brumhard/renovate-issue/go.mod:16: unknown directive: )
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes

changed the regex so it would support comment lines inside replace block

## Context

- Closes #15369 
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [X] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
needs test and regex is bad, see codeql error

**Comment by PhilipAbed** [comment]
- The Replace is being changed just so we could run the Command `go get -t ./...`, 
i added another replace section in the tests, the tests won't fail anyway because it doesn't change the final result
there's no test i can add that can test  the private function unless we use some reflection which isn't best practice..

- The regex replace\s*\((?:(?:\s*\/\/.*)?(?:[^)])?)+\)
is meant to find replace  keyword+ spaces + `(`  everything that is not `)`+  except (?:\s*\/\/.*)? commented line  `)`
i read some documentation about this issue,  but i'm not that familiar with regex, i'm not sure how to rewrite my regex in a better way, can you help?

File: lib/modules/manager/gomod/artifacts.ts [hunk 1]
```diff
@@ -177,7 +177,10 @@ export async function updateArtifacts({
     // replace (
     //     golang.org/x/net v1.2.3 => example.com/fork/net v1.4.5
     // )
-    const blockReplaceRegEx = regEx(/(\r?\n)replace\s*\([^)]+\s*\)/g);
+    // the regex will ignore commented lines with "//"
+    const blockReplaceRegEx = regEx(
+      /replace\s*\((?:(?:\s*\/\/.*)?(?:[^)])?)+\)/g
```
Comment (viceice) [inline lib/modules/manager/gomod/artifacts.ts:182]:
```suggestion
      /\r?\nreplace\s*\((?:\r?\n\s+\/\/[^\n]+)*[^)]+\)/g
```

what about this?

- https://regex101.com/r/WN0M0H/1

Comment (PhilipAbed) [reply lib/modules/manager/gomod/artifacts.ts:182]: it fails on double comments in different lines
```
replace (
  go.uber.org/zap => go.uber.org/zap v1.21.0
  // TODO: this comment breaks renovatebot (>v0.11.1)
  go.uber.org/zap => go.uber.org/zap v1.21.0
  // TODO: this comment breaks renovatebot (>v0.11.1)
  go.uber.org/zap => go.uber.org/zap v1.21.0
)
```

Comment (PhilipAbed) [reply lib/modules/manager/gomod/artifacts.ts:182]: do you think i should just look for all comments in file and replace them with Spaces for the sake of replace regex? then get it back? instead of doing such complex regex?

Comment (viceice) [reply lib/modules/manager/gomod/artifacts.ts:182]: no.

@zharinov It seems `moo` lexer is a better option here? As the regex will be too complex

Comment (zharinov) [reply lib/modules/manager/gomod/artifacts.ts:182]: Looks like it is

Comment (viceice) [reply lib/modules/manager/gomod/artifacts.ts:182]: Can you do some suggestions?

Comment (zharinov) [reply lib/modules/manager/gomod/artifacts.ts:182]: I think, the best example would be `lib/modules/manager/cake/index.ts`

Comment (PhilipAbed) [reply lib/modules/manager/gomod/artifacts.ts:182]: do you mean this? let url = line.replace(regEx(/^[^:]*:/), '');

where you replace comments with nothing?

Comment (PhilipAbed) [reply lib/modules/manager/gomod/artifacts.ts:182]: you mean when using lexer?
```
export function extractPackageFile(content: string): PackageFile {
  const deps: PackageDependency[] = [];
  lexer.reset(content);
  let token = lexer.next();
  while (token) {
    const { type, value } = token;
    if (type === 'dependency' || type === 'dependencyQuoted') {
      const dep = parseDependencyLine(value);
      if (dep) {
        deps.push(dep);
      }
    }
    token = lexer.next();
  }
  return { deps };
}
```

Comment (rarkins) [reply lib/modules/manager/gomod/artifacts.ts:182]: Can we have a short term solution though? This is not a hugely high priority item for me, so happy with a quick fix

Comment (zharinov) [reply lib/modules/manager/gomod/artifacts.ts:182]: Why the comment removal before any processing isn't option? If I understand correctly, we don't care about offsets info here.

Comment (PhilipAbed) [reply lib/modules/manager/gomod/artifacts.ts:182]: if we remove anything we will have to replace it back since the changes affect the PR in the end

File: lib/modules/manager/gomod/artifacts.ts [hunk 2]
```diff
@@ -159,11 +159,21 @@ export async function updateArtifacts({
   const useVendor = (await readLocalFile(vendorModulesFileName)) !== null;
 
   let massagedGoMod = newGoModContent;
-
   if (!config.postUpdateOptions?.includes('gomodNoMassage')) {
     // Regex match inline replace directive, example:
     // replace golang.org/x/net v1.2.3 => example.com/fork/net v1.4.5
     // https://go.dev/ref/mod#go-mod-file-replace
+
+    massagedGoMod = massagedGoMod
```
Comment (nabeelsaabna) [inline lib/modules/manager/gomod/artifacts.ts:167]: please add comment explaining the need for this block

File: lib/modules/manager/gomod/artifacts.ts (hunk 1 above)
Comment (PhilipAbed) [reply lib/modules/manager/gomod/artifacts.ts]: i'm not 100% familiar with go, so are you sure the Command mod tidy doesn't update anything?
What if the command changes the file?
i think we are doing some changes:
if you look here
```
  if (finalGoModContent !== newGoModContent) {
      logger.debug('Found updated go.mod after go.sum update');
```
apparently we do some changes.

Unless i am fully familiar with the flow i cant say.

**Review by nabeelsaabna — DISMISSED** [review]

File: lib/modules/manager/gomod/artifacts.ts [hunk 3]
```diff
@@ -159,11 +159,23 @@ export async function updateArtifacts({
...
     // replace golang.org/x/net v1.2.3 => example.com/fork/net v1.4.5
     // https://go.dev/ref/mod#go-mod-file-replace
+
+    // replace bracket after comments, so it doesn't break the regex, doing a complex regex causes problems
+    // when there's a comment and ")" after it, the regex will read replace block until comment.. and stop.
+    massagedGoMod = massagedGoMod
+      .split('\n')
+      .map((line) => {
+        if (line.trim().startsWith('//')) {
+          return line.replace(')', 'renovate-replace-bracket');
```
Comment (rarkins) [inline lib/modules/manager/gomod/artifacts.ts:173]: Pretty hacky but I guess it works?

**Review by viceice — COMMENTED** [review]
Did you real run against a test repo with latest changes?

File: lib/modules/manager/gomod/artifacts.ts [hunk 4]
```diff
@@ -188,12 +200,14 @@ export async function updateArtifacts({
       match.replace(/(\r?\n)/g, '$1// renovate-replace ');
 
     // Comment out golang replace directives
-    massagedGoMod = newGoModContent
+    massagedGoMod = massagedGoMod
```
[the remark this answers is not in the document]
Comment (PhilipAbed) [reply lib/modules/manager/gomod/artifacts.ts:203]: no it wasn't used anywhere anyway.

File: lib/modules/manager/gomod/artifacts.ts (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/gomod/artifacts.ts:173]: Yes, that's how its done line by line :D you wanted a fast fix! there you go...
The other way is to do a complex regex but its problematic.

**Comment by PhilipAbed** [comment]
Yes, i ran it on this: https://github.com/StinkyLord/15369-go-get-failed

**Review by rarkins — DISMISSED** [review]

**Review by viceice — DISMISSED** [review]
Very hacky, but i don't have a beter solution. Everyone should prefer to use `gomodNoMassage`

**Review by rarkins — APPROVED** [review]
