### PR TITLE
fix(manager/nuget): don't bump version if already done 

### LINKED ISSUE #23526: Renovate bumps the version in csproj with trailing zeroes i.e. 4.10.000000
### Discussed in https://github.com/renovatebot/renovate/discussions/23418

<div type='discussions-op-text'>

<sup>Originally posted by **bjuraga** July 18, 2023</sup>
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.160.0

### If you're self-hosting Renovate, select which platform you are using.

Azure DevOps (dev.azure.com)

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

This happens on PRs that change a csproj file which has a Version property. We have Renovate configured to bump the version.
So, if we leave a PR open for longer, can be few days to few weeks, Renovate will update the PR nightly (we scheduled the Renovate pipeline to run once a day at night). 

So, say we have a csproj for our internal NuGet package, versioned at 4.7.0. 

The first PR will correctly update the version to 4.8.0, because we set the PR to update the minor part of the version.

Say we get several PRs on the same csproj for various other Renovate PRs. And one goes in to master. 

Next day we get an update to the PR i mention, and it correctly bumps the version from 4.8.0 to 4.9.0. It was rebased on master if that helps.

Same thing next day, some other PR got merged, it incremented the minor part to 4.10.0, so the PR in question will correctly update the Version to 4.10.0. Keep in mind this is the same PR, getting rebased on master and not being merged.

So far, timeline wise all seems perfect.

Next day (4th) no PRs got merged, so the PR in question did not rebase, but it got a change from 4.9.0 to 4.10.00. Do note the last double zeroes!

Since then, every next day the same PR is updated to bump the version with one extra zero at the patch part, to make it visual:
4.9.0 -> 4.10.0
4.9.0 -> 4.10.00
4.9.0 -> 4.10.000
4.9.0 -> 4.10.0000
....
4.9.0 -> 4.10.0000000000

Since this is a PR for a Nuget package csproj, i cant even merge it because it would generate a semver of 4.10.0 and my push to the feed would fail beause the version exists.</div>

### PR DESCRIPTION
**Pull request by bjuraga**
## Changes
Added tests to reproduce issue #23526 
Provided a bugfix for the issue
Changes tested with [this workflow](https://github.com/bjuraga/renovate_add_bumpVersion_to_nuget/actions/runs/5648638535)

## Context
Closes #23526 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/nuget/update.ts [hunk 1]
```diff
@@ -29,23 +27,19 @@ export function bumpPackageVersion(
...
-    const startTagPosition = versionNode.startTagPosition;
-    const versionPosition = content.indexOf(versionNode.val, startTagPosition);
-
     const newProjVersion = semver.inc(currentValue, bumpVersion as ReleaseType);
     if (!newProjVersion) {
       throw new Error('semver inc failed');
     }
 
     logger.debug(`newProjVersion: ${newProjVersion}`);
-    bumpedContent = replaceAt(
```
Comment (viceice) [inline lib/modules/manager/nuget/update.ts:43]: no, `replaceAt` needs to be fixed

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/modules/manager/nuget/update.ts (hunk 1 above)
Comment (bjuraga) [reply lib/modules/manager/nuget/update.ts:43]: Added a check in nuget before even calling `bumpVersion()`. Also, fixed replaceAt, but not checked for performance impact.

File: lib/util/string.ts [hunk 2]
```diff
@@ -14,11 +14,13 @@ export function replaceAt(
...
-    newString +
-    content.substring(index + oldString.length)
-  );
+  const firstPart = content.slice(0, index);
+  const secondPart = content.slice(index);
+  if (secondPart.startsWith(oldString)) {
+    return firstPart + secondPart.replace(oldString, newString);
+  }
+
+  return content;
```
Comment (viceice) [inline lib/util/string.ts:23]: why does the original code doesn't successfully replace, the new code looks more worse.

Comment (bjuraga) [reply lib/util/string.ts:23]: The old implementation was wrong because first it did not check if the string exists and it made assumptions about the length of the string it though it was replacing. 

This code makes sure that the string we are trying to replace actually exists at the index we specified. And replace() only replaces the first instance it finds, so if the string starts with it, it only replaces what was meant to be replaced.

Hope that makes sense.

Comment (bjuraga) [reply lib/util/string.ts:23]: An alternative would be to use the 'old' code and add a check to make sure that the string we want to replace does exist. Would that be more acceptable? 

In any case, the test i added should prevent the reported issue in the future. And also make sure i did not break anything else.

Comment (bjuraga) [reply lib/util/string.ts]: I reverted all the changes in this file. Turns out  i could fix the bug elsewhere.

File: lib/modules/manager/nuget/update.ts [hunk 3]
```diff
@@ -31,27 +31,35 @@ export function bumpPackageVersion(
...
       newProjVersion
     );
 
-    if (bumpedContent === content) {
-      logger.debug('Version was already bumped');
-    } else {
-      logger.debug('project version bumped');
-    }
+    logger.debug('project version bumped');
+    logger.debug(`project after bumpVersion(): ${bumpedContent}`);
```
Comment (rarkins) [inline lib/modules/manager/nuget/update.ts:62]: Better to combine these into one log message

**Comment by bjuraga** [comment]
@viceice sorry to mention you, but the last thing we need to merge this PR is to acknowledge the requested change is done.

File: lib/modules/manager/nuget/update.ts [hunk 4]
```diff
@@ -31,27 +31,37 @@ export function bumpPackageVersion(
...
-    logger.debug(`newProjVersion: ${newProjVersion}`);
+    if (currentProjVersion === newProjVersion) {
+      logger.debug('Version was already bumped');
+      return { bumpedContent };
+    }
+
+    logger.debug(
+      `newProjVersion: ${newProjVersion}, project content before bumpVersion(): ${content}`
+    );
+
```
Comment (viceice) [inline lib/modules/manager/nuget/update.ts:54]: remove, too much debug logs

File: lib/modules/manager/nuget/update.ts [hunk 5]
```diff
@@ -31,27 +31,37 @@ export function bumpPackageVersion(
...
     );
 
-    if (bumpedContent === content) {
-      logger.debug('Version was already bumped');
-    } else {
-      logger.debug('project version bumped');
-    }
+    logger.debug(
+      `project version bumped, project content after bumpVersion(): ${bumpedContent}`
+    );
```
Comment (viceice) [inline lib/modules/manager/nuget/update.ts:64]:
```suggestion
    logger.debug(
      `project version bumped, project content after bumpVersion(): ${bumpedContent}`
    );
```
use original message

**Review by viceice — APPROVED** [review]
