### PR TITLE
fix(html-sanitize): Sanitize HTML comments in PR

### LINKED ISSUE #3715: Sanitize all HTML comments on Bitbucket/Bitbucket Server
e.g. so we don't see this:

image

### PR DESCRIPTION
**Pull request by rakeshtembhurne**
Sanitizes HTML comments inside PR body for BitBucket server.

Closes #3715

### CODE REVIEW

File: lib/platform/bitbucket-server/index.ts [hunk 1]
```diff
@@ -964,6 +964,7 @@ export function getPrBody(input: string) {
     .replace(/<\/?summary>/g, '**')
     .replace(/<\/?details>/g, '')
     .replace(new RegExp(`\n---\n\n.*?<!-- .*?-rebase -->.*?(\n|$)`), '')
+    .replace(new RegExp('<!--.*-->', 'g'), '')
```
Comment (ViceIce) [inline lib/platform/bitbucket-server/index.ts]: Shouldn't we be non greedy here `'<!--.*?-->'` ?

otherwise we would replace all:
```html
<!-- comment -->
Text
<!-- other comment -->
```

Comment (rakeshtembhurne) [reply lib/platform/bitbucket-server/index.ts]: Yeah, you're right. I will make sure that it works well with such scenarios as well.

Comment (ViceIce) [reply lib/platform/bitbucket-server/index.ts]: I've added the suggestion. if you like you can take it 😄

Comment (rakeshtembhurne) [reply lib/platform/bitbucket-server/index.ts]: It's a good suggestion. Happy to use it.

Comment (rakeshtembhurne) [reply lib/platform/bitbucket-server/index.ts]: It's a good suggestion. At least I can add
