### PR TITLE
fix(pr): ensure PR update after branch commit

### LINKED ISSUE #17388: PR title and description not updated until subsequent run when prCreation != immediate
## How are you running Renovate?
Self-hosted

## If you're self-hosting Renovate, tell us what version of Renovate you run.
32.169.1

## Please select which platform you are using if self-hosting.
Bitbucket Cloud

## If you're self-hosting Renovate, tell us what version of the platform you run.
No response

## Was this something which used to work for you, and then stopped?
No

## Describe the bug
1. An existing PR for package updates has been opened by Renovate but hasn't been touched
2. New package updates are published
3. Renovate runs and detects new packages and updates the existing branch with a proper commit but does not update the PR title and description with the new package version numbers.
4. Renovate runs an hour later and updates the PR title and descriptions to match the correct versions.

## Here's the relevant logs:

```
 INFO: Branch updated (repository=company/poc-repo, baseBranch=develop, branch=renovate/all-company-nuget-packages)
       "commitSha": "76dd00b1f324aabf722e5b2111b4c36611e8e983"
DEBUG: Branch status pending (repository=company/poc-repo, baseBranch=develop, branch=renovate/all-company-nuget-packages)
       "commitSha": "76dd00b1f324aabf722e5b2111b4c36611e8e983"
DEBUG: getBranchPr(renovate/all-company-nuget-packages) (repository=company/poc-repo)
DEBUG: findPr(renovate/all-company-nuget-packages, undefined, open) (repository=company/poc-repo)
DEBUG: getPrList() (repository=company/poc-repo)
DEBUG: Found PR #1 (repository=company/poc-repo)
DEBUG: Closing Dependency Dashboard (repository=company/poc-repo)
```

It looks like it found the relevant PR although there's no log messages after that. Doing some code inspection I think this block is causing it to return too early: https://github.com/renovatebot/renovate/blob/78e20c9e1ac4c0085453acc4e1e863ea53e15e32/lib/workers/repository/update/branch/index.ts#L548-L563

IIRC this block was to prevent accidental race conditions on automerge which follows after it.

Please go ahead and create a bug report issue and you can copy/paste what I wrote above.

_Originally posted by @rarkins in https://github.com/renovatebot/renovate/discussions/17343#discussioncomment-3466111_

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes

i stopped going inside the IF case, if we have a PR created already, 
the code was getting inside the IF case also when there's a branch update, but that doesn't make sense to me.

@rarkins @viceice this solution works, but i'm not sure if i impact any other flow that i dont know about,
it seems logical to me, 
but you know better.

## Context

Closes #17388

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
We need to be careful about unintended side effects.

Here's the `if` which now won't be entered: https://github.com/PhilipAbed/renovate/blob/8ddc944b9e76edcecc8f0f3f2c01667f000daf7c/lib/workers/repository/update/branch/index.ts#L556

Here's the next `if` which now might be entered: https://github.com/PhilipAbed/renovate/blob/8ddc944b9e76edcecc8f0f3f2c01667f000daf7c/lib/workers/repository/update/branch/index.ts#L574

So we might want to skip that second one if `commitSha` exists?

We also need to consider what the `return {}` value will be

**Review by viceice — CHANGES_REQUESTED** [review]
this will cause early automerge again, check the comment above the if condition.

we added this to suppress automerge, because status checks can be missing and renovate has probably at green stability check.

on some platforms you can workaround with required status checks, but not always.

**Comment by PhilipAbed** [comment]
@rarkins yes i dont want to enter in case there's no PR for that branch on, this is supposed to take care of PR CREATION only https://github.com/PhilipAbed/renovate/blob/8ddc944b9e76edcecc8f0f3f2c01667f000daf7c/lib/workers/repository/update/branch/index.ts#L556

that leaves the PR UPDATE flow that i don't want it to enter there,
this should pass the above IF statement, since its not PR creation, but it is a new commit, a new update on the branch.

@viceice let's say we have Automerge, and we did an Update flow, why do u step into an IF statement that belongs to the PR Creation?

shouldn't the check for automerge be after it? at 
https://github.com/PhilipAbed/renovate/blob/8ddc944b9e76edcecc8f0f3f2c01667f000daf7c/lib/workers/repository/update/branch/index.ts#L574

i see `if (branchExists || config.ignoreTests) {` 
but i can see that this is not enough, 
what if we change it?
shouldn't we check status of branch before ?

**Comment by viceice** [comment]
@rarkins yes, i think we need to check commitSha and skip trying automerge then

@PhilipAbed #5594 is the original introduction of that condition. it was added to supress automerge when a new commit was made. The code was very different than now and it was easiest solution. You can now try to refactor but you need to make sure automerge is skipped when a new commit was made. The skipped PR update was a trade of not doing automerge.

**Comment by PhilipAbed** [comment]
there are too many flows going on 
1) artifact error flow
2) pr creation immediate
3) pr creation not immediate
4) pr update immediate
5) pr update not immediate
6) automerge immediate
7) automerge not immediate

There's no way to do this without a refactor, ill see what i can do

**Comment by PhilipAbed** [comment]
@rarkins @viceice  i believe we should split the Immediate flow from the non-immediate flow 
the functionalities of branch update/ Auto merge / ensuring pr  should be in functions but i can't refactor there are over 30 returns in the middle of the code, it's not that easy 

i just added double condition 
now 
what changed:

before:
pr update not immediate flow - exit early skip auto merge and ensure PR

after:
pr update not immediate flow - will now ensure PR but skip automerge

i check if `branchPr` exists, and that is how i acknowledge if its an update flow or a creation flow.

p.s. i was unable to add `commitSha` to the `skipCondition` i created, lint screams that `commitSha` can be `null` even though it's part of the `skipCondition`, so i got it out of the condition and it looks uglier than expected

File: lib/workers/repository/update/branch/index.ts [hunk 1]
```diff
@@ -553,26 +553,29 @@ export async function processBranch(
     await setStability(config);
     await setConfidence(config);
 
-    // break if we pushed a new commit because status check are pretty sure pending but maybe not reported yet
-    // but do not break when there are artifact errors
-    if (
+    const skipCondition =
+      commitSha &&
       !config.artifactErrors?.length &&
       !userRebaseRequested &&
```
Comment (viceice) [inline lib/workers/repository/update/branch/index.ts:559]: those should stay at original condition, as we should skip automerge on artifact errors and user rebase.

Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts:559]: the message in the above comment indicates the opposite 
`// but do not break when there are artifact errors` 
which means we do the Try auto merge flow

Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts:559]: what you say makes more sense though,

**Comment by PhilipAbed** [comment]
it's working according to my test at:
https://github.com/StinkyLord/prcreationimmediate/pull/6

**Comment by PhilipAbed** [comment]
@rarkins a question that has been bothering me, 
why is Automerge before ensuring PR?

doesn't make sense to me, 
so you are saying some branch could change, the title/content aren't updated, yet we merge it?

File: lib/workers/repository/update/branch/index.ts [hunk 2]
```diff
@@ -553,26 +553,35 @@ export async function processBranch(
...
         commitSha,
       };
     }
 
     // Try to automerge branch and finish if successful, but only if branch already existed before this run
-    if (branchExists || config.ignoreTests) {
+    // skip if we have a non-immediate pr and there is an existing PR,
+    // we want to update the PR and skip the Auto merge since status checks aren't done yet
+    if (
+      !notImmediate &&
```
Comment (PhilipAbed) [inline lib/workers/repository/update/branch/index.ts:580]: does the ignoreTests relate to the commitSha && config.prCreation !== 'immediate';?
if i keep same funcitonality in a flow where
prCreation !== immediate and ignoreTests=true and there's a new commit, 
the code used to break.
but if we are ignoring tests, then why should we break and skip automerge? we are ignoring tests anyway

i'm doubting this flow

Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts:580]: or does prCreation relate to ALL checks including tests?

**Comment by rarkins** [comment]
It's branch automerge

File: lib/workers/repository/update/branch/index.ts (hunk 2 above)
Comment (viceice) [reply lib/workers/repository/update/branch/index.ts:580]: no, we should never try to automerge when we've done a fresh commit

btw: here's another automerge condition (pr-automerge)

https://github.com/renovatebot/renovate/blob/76b536e23a1b25999c2ffcf029bcb4e786dd4753/lib/workers/repository/update/branch/index.ts#L812-L821

**Comment by rarkins** [comment]
We need to make sure that we don't branch or PR automerge after a fresh commit unless ignoreTests=true

**Comment by PhilipAbed** [comment]
you say we should not even try to auto merge branch when there's a fresh commit
but if you look at the current code without any changes:

https://github.com/renovatebot/renovate/blob/6f051f3ae7e8f63dfe7481dc5f82d30a5b09ab55/lib/workers/repository/update/branch/index.ts#L558-L563

this IF condition only quits if `prCreation !== immediate`

so in case  the prCreation flag is not used, it would just skip to the automerge where 
https://github.com/renovatebot/renovate/blob/6f051f3ae7e8f63dfe7481dc5f82d30a5b09ab55/lib/workers/repository/update/branch/index.ts#L575
and enter the loop in case we have an update on the branch..
the update is a Fresh commit, where `commitSha` is not null. but it is not checked.

so if i add another check to it to make sure i dont do auto merge that would change logic right?  is that ok?

**Comment by PhilipAbed** [comment]
i will test and see

**Comment by viceice** [comment]
That's why i've doen it that way long ago. the early return was the easiest solution to not automerge 😉

**Comment by PhilipAbed** [comment]
it actually reaches the condition even if i dont use the `config.automerge` flag
it doesn't return early as you mentioned
but inside the function `tryBranchAutomerge(config)` it would `return 'no automerge';`

so i'm not sure what you mean by the early return as it reaches that line in the branch update case,
i believe if i add automergeType='branch' it should work normally

File: lib/workers/repository/update/branch/index.ts (hunk 2 above)
Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts:580]: i dont think i need to change anything here since inside the check auto merge there's always a check for branch status, so a new commit or not a new commit, the branch status check will give the indication if we should continue or not

Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts:580]: so you want to skip both in case pr !== immediate? hmmmm this is more complicated than i thought

Comment (viceice) [reply lib/workers/repository/update/branch/index.ts:580]: no, the status checks can be missing and renovate can have added a successful stabillity check, so renovate would strait automerge. so we should never try to automerge when we've done a new commit.

Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts:580]: image
its not defined in there :D

**Comment by PhilipAbed** [comment]
Thanks a lot @rarkins @viceice i learned a lot from this, there are certainly lots of flows and cases

I tried to refactor, but i see more than 30 exits to `processBranch` function with 700+ rows .
the impact is too large so i will not do that unless its necessary.

hope i covered everything in my changes

**Comment by PhilipAbed** [comment]
https://github.com/renovatebot/renovate/blob/6f051f3ae7e8f63dfe7481dc5f82d30a5b09ab55/lib/workers/repository/update/branch/index.spec.ts#L511-L528

this test is failing because i added the `!commitSha` on the automerge branch, so it's skipping the call to `tryBranchAutomerge`, 
and failing on row ` expect(automerge.tryBranchAutomerge).toHaveBeenCalledTimes(1);`

in this test: 
Branch Exists = false
IgnoreTests = true
commitSha = 123test

i still don't understand which cases have BranchExists=false? how can we process a branch that doesn't exist?
because of this missing knowledge i'm not sure what to do with this test 
please advise

File: lib/workers/repository/update/branch/index.ts (hunk 2 above)
Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts]: ah, ok, i've done it but now i have a problem in 1 of the tests see my comment blow
https://github.com/renovatebot/renovate/pull/18839#issuecomment-1310425195

File: lib/workers/repository/update/branch/index.ts [hunk 3]
```diff
@@ -553,26 +553,34 @@ export async function processBranch(
...
     // Try to automerge branch and finish if successful, but only if branch already existed before this run
-    if (branchExists || config.ignoreTests) {
+    // skip if we have a non-immediate pr and there is an existing PR,
+    // we want to update the PR and skip the Auto merge since status checks aren't done yet
+    if (
+      !commitSha &&
+      !config.artifactErrors?.length &&
+      !userRebaseRequested &&
+      (branchExists || config.ignoreTests)
+    ) {
```
Comment (viceice) [inline lib/workers/repository/update/branch/index.ts:583]: we can automerge when new commit and config.ignoreTests.

branchExists only means branch was there or new created.

File: lib/workers/repository/update/branch/index.ts [hunk 4]
```diff
@@ -811,13 +819,21 @@ export async function processBranch(
...
-        if (prAutomergeResult?.automerged) {
-          return {
-            branchExists,
-            result: BranchResult.Automerged,
-            commitSha,
-          };
+        if (
+          !commitSha &&
+          !config.artifactErrors?.length &&
+          !userRebaseRequested
```
Comment (viceice) [inline lib/workers/repository/update/branch/index.ts:825]: i think commitSha is already set when userRebaseRequested was true, so this would probyböy enough
```suggestion
          !commitSha &&
          !config.artifactErrors?.length
```

File: lib/workers/repository/update/branch/index.ts (hunk 3 above)
Comment (viceice) [reply lib/workers/repository/update/branch/index.ts:583]:
```suggestion
    // skip if we have a non-immediate pr and there is an existing PR,
    // we want to update the PR and skip the Auto merge since status checks aren't done yet
    if (
      (!commitSha &&
      !config.artifactErrors?.length) ||
      config.ignoreTests
    ) {
```

maybe this is the right condition?

Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts]: what about a flow with Artifact Errors + ignoreTests=true ? is it ok to merge with artifact errors?

Comment (viceice) [reply lib/workers/repository/update/branch/index.ts]: good catch, we shouldn't.

Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts]: if u look up a bit on the same IF statement before automerge check there's:
` if (config.artifactErrors?.length) {`
so basically we dont need to check for artifact errors in there.

ignoreTests is not needed as a check here neither since it's being checked in the branch status
```
 const branchStatus = await resolveBranchStatus(
    config.branchName!,
    config.ignoreTests
  );
```

!commitSha i'm not sure since it's part of the return
```
  const prAutomergeResult = await checkAutoMerge(pr, config);
          if (prAutomergeResult?.automerged) {
            return {
              branchExists,
              result: BranchResult.Automerged,
              commitSha,
            };
          }
```

so the first branch auto merge condition should be 
`    if (!config.artifactErrors?.length && (!commitSha || (commitSha && config.ignoreTests))) {`

either there's no new commit, or there's a commit with ignoreTests

otherwise the ignoreTests shouldnt even exist in this condition. like :
`    if (!config.artifactErrors?.length && !commitSha) {`

WDYT?

**Comment by PhilipAbed** [comment]
@rarkins @viceice 

Too many flows caused this to be complicated, let's ignore all other comments and summarize.

Summary of what i did and open questions

1. When there are artifact errors, We don't wanna merge neither branch nor PR but we will add the Artifact error notes to the PR! 
    -  should we auto-merge branch with artifact errors? 

2. When there's a new commit(update or create), according to @viceice we don't want to auto merge directly cause of checks, unless the `config.ignoreTests=true` then according to docs: `Setting this option to true means that Renovate will ignore all status checks.`

   - i believe that includes the Stability check case right?
   
3. on the PR Merge, before we go to the auto-merge, there's a check for Artifact Errors, where it adds the errors to the PR content to display it, so it's already checked, 
instead, i added a check for a Commit, if there's a `commitSha` then do not auto merge. but it leaves the inconsistency with these :
    - it's **OK** to auto merge **BRANCH** with a new commit when we are in `config.ignoreTests`
    - it's **NOT OK** to auto merge **PR** with a new commit even if we are in `config.ignoreTests` 

does that make sense?

**Comment by viceice** [comment]
1. never auto merge on artifact errors

**Comment by viceice** [comment]
2. yes all checks are ignored

**Comment by viceice** [comment]
3. only automerge with new commit when tests are ignored.

**Comment by PhilipAbed** [comment]
@viceice Thanks, i followed your instructions, hopefully this is the last commit :D

**Review by viceice — COMMENTED** [review]
looks good so far, we should add new tests for that?

File: lib/workers/repository/update/branch/index.ts [hunk 5]
```diff
@@ -553,26 +553,29 @@ export async function processBranch(
...
     // but do not break when there are artifact errors
     if (
-      !config.artifactErrors?.length &&
-      !userRebaseRequested &&
       commitSha &&
-      config.prCreation !== 'immediate'
+      config.prCreation !== 'immediate' &&
+      !branchPr &&
+      !config.artifactErrors?.length &&
+      !userRebaseRequested
```
[the remark this answers is not in the document]
Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts:564]: the check here is for `!userRebaseRequested` with `commitSha` though.
it could be a commitSha for update or create, it doesn't have to be rebase.

but the good question is, why is it in here?
so i think it's there because it's with `config.prCreation !== 'immediate'` 
so if there's a pr creation that should wait, and there's a rebase request, then we shouldnt wait, we should just continue, 
so i think the check is OK, do u agree with me? or you still think we should remove it?

**Comment by PhilipAbed** [comment]
@viceice there are 63 tests already that cover almost all cases, ill check if there are flows to ad

**Comment by PhilipAbed** [comment]
@viceice @rarkins  something is bothering me,

after reproducing again and debugging to create a suitable test `IsBranchModified` is returning `false`,
but the branch was modified.

i checked where it goes exactly, and i reached these lines.

https://github.com/renovatebot/renovate/blob/e4e34ff73f046029735a6482154feeb43afb240d/lib/util/git/index.ts#L650-L659

why are these lines a consideration for if the branch is modified or not?

could it be i approached this wrongly? we needed to fix the `isBranchModified` before i started all these changes?

**Comment by viceice** [comment]
the is branch modified means a user made a change on top of renovate. can't happen when we've done a new commit.

File: lib/workers/repository/update/branch/index.spec.ts [hunk 6]
```diff
@@ -1956,5 +1956,59 @@ describe('workers/repository/update/branch/index', () => {
...
+    it('continues branch, skips automerge if there are artifact errors', async () => {
+      jest.spyOn(getUpdated, 'getUpdatedPackageFiles').mockResolvedValueOnce({
+        updatedPackageFiles: [{}],
+        artifactErrors: [{}],
+      } as PackageFilesResult);
+      npmPostExtract.getAdditionalFiles.mockResolvedValueOnce({
+        artifactErrors: [],
+        updatedArtifacts: [],
+      });
+      git.branchExists.mockReturnValue(true);
```
Comment (viceice) [inline lib/workers/repository/update/branch/index.spec.ts:1969]: why not once here? not using once can cause side effects to other tests.

File: lib/workers/repository/update/branch/index.spec.ts [hunk 7]
```diff
@@ -1956,5 +1956,59 @@ describe('workers/repository/update/branch/index', () => {
...
+      git.isBranchModified.mockResolvedValueOnce(true);
+      git.getBranchCommit.mockReturnValue('123test');
```
Comment (viceice) [inline lib/workers/repository/update/branch/index.spec.ts:1971]: same

**Review by viceice — COMMENTED** [review]
otherwise LGTM

File: lib/workers/repository/update/branch/index.spec.ts (hunk 6 above)
Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.spec.ts:1969]: just copy paste mistake xD

**Comment by PhilipAbed** [comment]
weird exception happened after i updated branch from main

File: lib/workers/repository/update/branch/index.ts [hunk 8]
```diff
@@ -553,9 +553,11 @@ export async function processBranch(
     await setStability(config);
     await setConfidence(config);
 
-    // break if we pushed a new commit because status check are pretty sure pending but maybe not reported yet
+    // new commit means status check are pretty sure pending but maybe not reported yet
+    // if PR has not been created + new commit + prCreation !== immediate skip
     // but do not break when there are artifact errors
     if (
+      !branchPr &&
```
Comment (rarkins) [inline lib/workers/repository/update/branch/index.ts:560]: @viceice @PhilipAbed I edited this file to restore the original ordering to make it clearer that only `!branchPr` has been added here. Unfortunately previous discussion got buried after this change

File: lib/workers/repository/update/branch/index.ts [hunk 9]
```diff
@@ -811,13 +814,16 @@ export async function processBranch(
...
       } else if (config.automerge) {
         logger.debug('PR is configured for automerge');
-        const prAutomergeResult = await checkAutoMerge(pr, config);
-        if (prAutomergeResult?.automerged) {
-          return {
-            branchExists,
-            result: BranchResult.Automerged,
-            commitSha,
-          };
+        if (!commitSha || config.ignoreTests) {
```
Comment (viceice) [inline lib/workers/repository/update/branch/index.ts:817]:
```suggestion
        // skip automerge if there is a new commit since status checks aren't done yet
        if (!config.artifactErrors?.length && (!commitSha || config.ignoreTests)) {
```

i think we don't like to automerge on artifact errors?

Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts]: the code doesn't reach here with artifact errors

File: lib/workers/repository/update/branch/index.ts (hunk 8 above)
Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts:560]: makes sense, ill just lint fix it xD

File: lib/workers/repository/update/branch/index.ts (hunk 9 above)
Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts]: im rolling this back

Comment (PhilipAbed) [reply lib/workers/repository/update/branch/index.ts:818]: @viceice after checking that the code goes into this section in case of artifact errors, i removed the check
https://github.com/renovatebot/renovate/blob/9562cf400928fd5756febf0a42105da03c362ade/lib/workers/repository/update/branch/index.ts#L767-L812

**Review by viceice — APPROVED** [review]

**Comment by PhilipAbed** [comment]
@viceice @rarkins  looks great now :D can we merge? or are we waiting for anything?

**Review by rarkins — APPROVED** [review]
