### PR TITLE
fix(config): apply secrets to global config

### LINKED ISSUE #35254: Regression in parsing of customEnvVariables
### Discussed in https://github.com/renovatebot/renovate/discussions/35242

<div type='discussions-op-text'>

<sup>Originally posted by **aerialls** April  8, 2025</sup>
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab (working in 39.222.1, not working in 39.227.2)

### Please tell us more about your question or problem

Hello,
We noticed a regression with the parameters `--secrets`  and `--custom-env-variables` used in postUpgradeTasks. We are currently using the following configuration.

```
{
  secrets: {
    SECRET_TOKEN: "whatever",
  },
  customEnvVariables: {
    SECRET_TOKEN: '{{ secrets.SECRET_TOKEN }}',
  }
}
```

With a postUpgradeTasks,

```
"postUpgradeTasks": {
  "commands": [
    "echo \"{{ env.SECRET_TOKEN }}\""
  ]
}
```

The workflow is working in version `39.222.1` but not working in version `39.227.2`. I haven’t tested intermediate versions to pinpoint a specific release.

A working reproduction is available at https://github.com/aerialls/renovate-secret. Renovate is launched with the following parameters.

Thanks a lot!

### Logs (if relevant)

# Working in 39.222.1

```
DEBUG: Executing command (repository=aerialls/renovate-secret, branch=renovate/google.golang.org-grpc-1.x)
       "dep": "google.golang.org/grpc",
       "command": "echo \"**redacted**\""
DEBUG: exec completed (repository=aerialls/renovate-secret, branch=renovate/google.golang.org-grpc-1.x)
       "dep": "google.golang.org/grpc",
       "durationMs": 6,
       "stdout": "**redacted**\n",
       "stderr": ""
DEBUG: Executed post-upgrade task (repository=aerialls/renovate-secret, branch=renovate/google.golang.org-grpc-1.x)
       "dep": "google.golang.org/grpc",
       "cmd": "echo \"**redacted**\"",
       "stderr": "",
       "stdout": "**redacted**\n"
DEBUG: git status counts after post-upgrade tasks (repository=aerialls/renovate-secret, branch=renovate/google.golang.org-grpc-1.x)
       "dep": "google.golang.org/grpc",
       "addedCount": 0,
       "modifiedCount": 2,
       "deletedCount": 0
DEBUG: Checking 2 added or modified files for post-upgrade changes (repository=aerialls/renovate-secret, branch=renovate/google.golang.org-grpc-1.x)
       "dep": "google.golang.org/grpc"
```

# Not working in 39.227.2

```
DEBUG: Executing command (repository=aerialls/renovate-secret, branch=renovate/google.golang.org-grpc-1.x)
       "dep": "google.golang.org/grpc",
       "command": "echo \"{{ secrets.SECRET_TOKEN }}\""
DEBUG: exec completed (repository=aerialls/renovate-secret, branch=renovate/google.golang.org-grpc-1.x)
       "dep": "google.golang.org/grpc",
       "durationMs": 5,
       "stdout": "{{ secrets.SECRET_TOKEN }}\n",
       "stderr": ""
DEBUG: Executed post-upgrade task (repository=aerialls/renovate-secret, branch=renovate/google.golang.org-grpc-1.x)
       "dep": "google.golang.org/grpc",
       "cmd": "echo \"{{ secrets.SECRET_TOKEN }}\"",
       "stderr": "",
       "stdout": "{{ secrets.SECRET_TOKEN }}\n"
DEBUG: git status counts after post-upgrade tasks (repository=aerialls/renovate-secret, branch=renovate/google.golang.org-grpc-1.x)
       "dep": "google.golang.org/grpc",
       "addedCount": 0,
       "modifiedCount": 2,
       "deletedCount": 0
DEBUG: Checking 2 added or modified files for post-upgrade changes (repository=aerialls/renovate-secret, branch=renovate/google.golang.org-grpc-1.x)
       "dep": "google.golang.org/grpc"
```</div>

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- Apply secrets to global config 
- Make sure the secrets are added for sanitizing 

## Context
 - Closes: #35254 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or (verified on [user provided reproduction](https://github.com/Rahul-renovate-testing/renovate-secret))
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Were there two problems?
1. Secrets not applied to customEnvVariables
2. Secrets not added to sanitization?

I expected the first but not the second

**Comment by RahulGautamSingh** [comment]
Encountered the second one while doing test runs. Hence, added a fix for it.

File: lib/workers/global/config/parse/index.ts [hunk 1]
```diff
@@ -109,6 +110,16 @@ export async function parseConfigs(
     config.onboardingNoDeps = 'enabled';
   }
 
+  // do not add these secrets to repoSecrets and,
+  //  do not delete the secrets object after applying on global config as it needs to be re-used for repo config
+  if (is.nonEmptyObject(config.secrets)) {
+    config = applySecretsToConfig(config, undefined, false);
```
Comment (rarkins) [inline lib/workers/global/config/parse/index.ts:116]: If this is applied, is https://github.com/renovatebot/renovate/blob/68a66a05a98ae2ed77ec2f1e203fac553383b081/lib/workers/global/initialize.ts#L64 also still required?

File: lib/workers/global/config/parse/index.ts [hunk 2]
```diff
@@ -109,6 +110,16 @@ export async function parseConfigs(
...
+    // adding these secrets to the globalSecrets set so that they can be redacted from logs
+    for (const secret of Object.values(config.secrets!)) {
+      addSecretForSanitizing(secret, 'global');
```
Comment (rarkins) [inline lib/workers/global/config/parse/index.ts:119]: Isn't this already done in https://github.com/renovatebot/renovate/blob/ad5c45f43770e8d422c3e93b1c7e805848aa8dc9/lib/config/secrets.ts#L127 ?

Comment (RahulGautamSingh) [reply lib/workers/global/config/parse/index.ts:119]: This adds it to the `repoSecrets` set in the same file, which gets cleared before repo processing begins. That's why I passed the `global` argument

File: lib/workers/global/config/parse/index.ts (hunk 1 above)
Comment (RahulGautamSingh) [reply lib/workers/global/config/parse/index.ts:116]: It should not be. But, even in the `globalInitialize` function `setGlobalHostRules` has been called twice, which mean that some host rules could get added during `initPlatform` call. Hence, better to leave it there,

**Comment by aerialls** [comment]
👋 Do you need help on this PR? Thanks a lot!

**Comment by RahulGautamSingh** [comment]
> 👋 Do you need help on this PR? Thanks a lot!

Needs review for the discussions.

**Review by viceice — APPROVED** [review]

**Review by secustor — APPROVED** [review]
