### PR TITLE
fix(nuget): add simple check to skip non-xml files

### LINKED ISSUE #19220: Nuget manager should not parse any .props file strictly as xml
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

self-built

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Nuget mgr could catch the parse exception, log a frienly info that this can't be a nuget file and silently move on...

In our case it conflicts with a new `versions.props` file that gradle understands, see #8017 

Repro repo: https://github.com/janhoy/gradle-consistent

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Matched 2 file(s) for manager nuget: subproject/versions.props, versions.props (repository=janhoy/gradle-consistent)
DEBUG: Failed to parse subproject/versions.props (repository=janhoy/gradle-consistent)
       "err": {
         "message": "Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: #",
         "stack": "Error: Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: #\n    at error (/Users/janhoy/git/renovate/node_modules/sax/lib/sax.js:651:10)\n    at strictFail (/Users/janhoy/git/renovate/node_modules/sax/lib/sax.js:677:7)\n    at beginWhiteSpace (/Users/janhoy/git/renovate/node_modules/sax/lib/sax.js:951:7)\n    at SAXParser.write (/Users/janhoy/git/renovate/node_modules/sax/lib/sax.js:1006:11)\n    at new XmlDocument (/Users/janhoy/git/renovate/node_modules/xmldoc/lib/xmldoc.js:295:17)\n    at Object.extractPackageFile (/Users/janhoy/git/renovate/lib/modules/manager/nuget/extract.ts:124:23)\n    at async getManagerPackageFiles (/Users/janhoy/git/renovate/lib/workers/repository/extract/manager-files.ts:52:19)\n    at async /Users/janhoy/git/renovate/lib/workers/repository/extract/index.ts:47:28\n    at async Promise.all (index 2)\n    at async extractAllDependencies (/Users/janhoy/git/renovate/lib/workers/repository/extract/index.ts:45:26)\n    at async extract (/Users/janhoy/git/renovate/lib/workers/repository/process/extract-update.ts:100:20)\n    at async extractDependencies (/Users/janhoy/git/renovate/lib/workers/repository/process/index.ts:120:26)\n    at async Object.renovateRepository (/Users/janhoy/git/renovate/lib/workers/repository/index.ts:48:52)\n    at async attributes.repository (/Users/janhoy/git/renovate/lib/workers/global/index.ts:173:11)\n    at async Object.start (/Users/janhoy/git/renovate/lib/workers/global/index.ts:158:7)\n    at async /Users/janhoy/git/renovate/lib/renovate.ts:17:22"
       }
DEBUG: Failed to parse versions.props (repository=janhoy/gradle-consistent)
       "err": {
         "message": "Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: o",
         "stack": "Error: Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: o\n    at error (/Users/janhoy/git/renovate/node_modules/sax/lib/sax.js:651:10)\n    at strictFail (/Users/janhoy/git/renovate/node_modules/sax/lib/sax.js:677:7)\n    at beginWhiteSpace (/Users/janhoy/git/renovate/node_modules/sax/lib/sax.js:951:7)\n    at SAXParser.write (/Users/janhoy/git/renovate/node_modules/sax/lib/sax.js:1006:11)\n    at new XmlDocument (/Users/janhoy/git/renovate/node_modules/xmldoc/lib/xmldoc.js:295:17)\n    at Object.extractPackageFile (/Users/janhoy/git/renovate/lib/modules/manager/nuget/extract.ts:124:23)\n    at async getManagerPackageFiles (/Users/janhoy/git/renovate/lib/workers/repository/extract/manager-files.ts:52:19)\n    at async /Users/janhoy/git/renovate/lib/workers/repository/extract/index.ts:47:28\n    at async Promise.all (index 2)\n    at async extractAllDependencies (/Users/janhoy/git/renovate/lib/workers/repository/extract/index.ts:45:26)\n    at async extract (/Users/janhoy/git/renovate/lib/workers/repository/process/extract-update.ts:100:20)\n    at async extractDependencies (/Users/janhoy/git/renovate/lib/workers/repository/process/index.ts:120:26)\n    at async Object.renovateRepository (/Users/janhoy/git/renovate/lib/workers/repository/index.ts:48:52)\n    at async attributes.repository (/Users/janhoy/git/renovate/lib/workers/global/index.ts:173:11)\n    at async Object.start (/Users/janhoy/git/renovate/lib/workers/global/index.ts:158:7)\n    at async /Users/janhoy/git/renovate/lib/renovate.ts:17:22"
       }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by viceice**
## Changes
Simply check if xml file starts and ends with proper xml chars after trimming whitespace.

## Context
- closes #19220

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/nuget/extract.ts [hunk 1]
```diff
@@ -198,6 +199,13 @@ export async function extractPackageFile(
     return extractMsbuildGlobalManifest(content, packageFile, registries);
   }
 
+  // Simple xml validation.
+  // Should start with `<` and end with `>` after trimming all whitespace
+  if (!regEx(/^\s*<.+>$/m).test(content.trim())) {
+    logger.debug(`Skipping ${packageFile} as it is not XML`);
```
Comment (rarkins) [inline lib/modules/manager/nuget/extract.ts]:
```suggestion
    logger.debug(`NuGet: Skipping ${packageFile} as it is not XML`);
```

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/modules/manager/nuget/extract.spec.ts [hunk 2]
```diff
@@ -26,8 +26,34 @@ describe('modules/manager/nuget/extract', () => {
...
+          org.apache.curator:* =4.3.0
+          org.apache.hadoop:*=3.1.4
+          org.apache.hadoop.thirdparty:* =   1.1.0
+          `,
+          'versions.props',
+          config,
+        ),
+      ).toBeNull();
+      expect(logger.logger.debug).toHaveBeenCalledWith(
+        'Skipping versions.props as it is not XML',
```
Comment (viceice) [inline lib/modules/manager/nuget/extract.spec.ts]:
```suggestion
        'NuGet: Skipping versions.props as it is not XML',
```

**Review by rarkins — APPROVED** [review]
