### PR TITLE
fix(cache): log cache errors as trace

### LINKED ISSUE #10445: Cache decorator noisily logs lookup errors
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

**Describe the bug**

The new cache decorator logs lookup errors which were previously ignored quietly.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

Here is one example:

```
{
code: ENOTFOUND, 
message: getaddrinfo ENOTFOUND charts.truecharts.com, 
name: RequestError, 
options: {
headers: [Object], 
http2: False, 
method: GET, 
password: , 
url: https://charts.truecharts.com/index.yaml, 
username: 
}, 
stack: 
RequestError: getaddrinfo ENOTFOUND charts.truecharts.com
    at ClientRequest.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.origin.emit (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
, 
timings: {
error: 1623766414905, 
lookup: 1623766414905, 
phases: [Object], 
socket: 1623766414760, 
start: 1623766414760
}
}
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I think we should only log errors in the cache's own logic and not ones returned from datasources.

### PR DESCRIPTION
**Pull request by JamieMagee**
## Changes:

Log errors caught by the cache decorator as trace. 

This matches what's done further up the stack in `datasource/index.ts`: [[1]](https://github.com/renovatebot/renovate/blob/d3bce1b01a7d3d4e3180b4df7fab02839b04f58d/lib/datasource/index.ts#L116), [[2]](https://github.com/renovatebot/renovate/blob/d3bce1b01a7d3d4e3180b4df7fab02839b04f58d/lib/datasource/index.ts#L159). The error will eventually bubble up to `logError`, where selective details from it are logged at the debug level, instead of the entire error:

https://github.com/renovatebot/renovate/blob/d3bce1b01a7d3d4e3180b4df7fab02839b04f58d/lib/datasource/index.ts#L36-L50

While I could split this into 3 different try/catch blocks (for the cache get, the method call, and the cache set) I think these parts are less likely to throw an error.

## Context:

Fixed #10445

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/cache/package/decorator.ts [hunk 1]
```diff
@@ -119,7 +119,7 @@ export function cache<T>({
       await packageCache.set(finalNamespace, finalKey, result, ttlMinutes);
       return result;
     } catch (err) /* istanbul ignore next */ {
-      logger.error({ err }, 'cache decorate error');
+      logger.trace({ err }, 'cache decorate error');
```
Comment (viceice) [inline lib/util/cache/package/decorator.ts:122]: 🤔 I think we can drop this catch block. It has no value for me as errors are logged later anyways.

@rarkins WDYT?

Comment (JamieMagee) [reply lib/util/cache/package/decorator.ts:122]: I'll take that 👍 as agreement. I'll update this PR to just drop the whole try/catch block.

Comment (JamieMagee) [reply lib/util/cache/package/decorator.ts]: Done! We may need to revisit this if we start to use the cache decorator outside of datasources.

**Review by viceice — DISMISSED** [review]

**Review by viceice — APPROVED** [review]
