### PR TITLE
fix(repo/update): dry run - skip PR update when branch is modified

### LINKED ISSUE #17109: PR is being updated in dry mode when branch was modified
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate will update a existing PR even when in dry run mode.
This happens when the renovate branch was modified.

Steps to reproduce:
 - Commit to any renovate feature branch with a non bot git account 
 - ~~Edit the PR body corresponding to the above branch~~ 
 - Run renovate in dry mode

Any repro will do, i for one used [this](https://github.com/ladzaretti/alpine-node) 

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: File config
       "config": {
         "platform": "github",
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "token": "***********",
     ...
         "dryRun": "full"
       }



...
DEBUG: Found existing branch PR (repository=ladzaretti/alpine-node, branch=renovate/node-18.x)
DEBUG: PR has been edited (repository=ladzaretti/alpine-node, branch=renovate/node-18.x)
       "prNo": 2
DEBUG: Updating existing PR to indicate that rebasing is not possible (repository=ladzaretti/alpine-node, branch=renovate/node-18.x)
DEBUG: updatePr(2, Update dependency node to v18, body) (repository=ladzaretti/alpine-node, branch=renovate/node-18.x)
DEBUG: PR updated (repository=ladzaretti/alpine-node, branch=renovate/node-18.x)
       "pr": 2


```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by Gabriel-Ladzaretti**
## Changes
 skip PR update when branch is modified in dry run mode

## Context
Closes #17109

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/repository/update/branch/index.ts [hunk 1]
```diff
@@ -198,15 +198,21 @@ export async function processBranch(
             });
             const newBodyHash = hashBody(newBody);
             if (newBodyHash !== branchPr.bodyStruct?.hash) {
```
Comment (Gabriel-Ladzaretti) [inline lib/workers/repository/update/branch/index.ts:200]: `newBodyHash !== branchPr.bodyStruct?.hash` will be true on the first dry run when the branch is modified because we adding a `rebasingNotice`. therefore the PR gets updated.

Comment (Gabriel-Ladzaretti) [inline lib/workers/repository/update/branch/index.ts:200]: `newBodyHash !== branchPr.bodyStruct?.hash` will be true on the first dry run when the branch is modified because we adding a `rebasingNotice`. therefore the PR gets updated.

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
