### PR TITLE
fix(manager/npm): workspaces npmrc

### LINKED ISSUE #20324: Support npm workspaces
Dear renovate maintainers,
we tried to update dependencies via renovate in two of our internal repositories which is using **npm workspaces** and unfortunately it doesn't work as expected. 

Current issues is that it starts to complain after  2 or 3 packages that packages can not being found -> "Failed to look up npm dependency...." also reported via the dependency dashboard. I checked the logs in debug mode and it seems that it isn't loading the npmrc from the project root where we configured to use our internal npm registry and then it tries to fetch it from the https://registry.npmjs.org.

I also gave it a try with yarn workspaces and that works like a charm. 

I found that post below and maybe it was just forgotten 🤷🏻 

     I think we're missing workspaces, but let's handle that in a separate issue and get a reproduction for it

_Originally posted by @rarkins in https://github.com/renovatebot/renovate/issues/7474#issuecomment-776224617_

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Supports `workspaces` in `package.json` for npm and not just Yarn

## Context

Closes #20324

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/npm/extract/monorepo.ts [hunk 1]
```diff
@@ -54,10 +54,8 @@ export async function detectMonorepos(
         subPackage.yarnLock = subPackage.yarnLock ?? yarnLock;
         subPackage.npmLock = subPackage.npmLock ?? npmLock;
         subPackage.skipInstalls = skipInstalls && subPackage.skipInstalls; // skip if both are true
-        if (subPackage.yarnLock) {
-          subPackage.hasYarnWorkspaces = !!yarnWorkspacesPackages;
-          subPackage.npmrc = subPackage.npmrc ?? npmrc;
-        }
+        subPackage.hasWorkspaces = !!workspacesPackages;
+        subPackage.npmrc = subPackage.npmrc ?? npmrc;
```
Comment (viceice) [inline lib/modules/manager/npm/extract/monorepo.ts:58]:
```suggestion
        subPackage.npmrc ??= npmrc;
```
that's shorter 😉

**Review by viceice — COMMENTED** [review]
just some small stuff

**Review by viceice — APPROVED** [review]
