### PR TITLE
fix(manager/mix): Support umbrella projects

### LINKED ISSUE #11851: mix.lock not updated when using an Elixir umbrella app
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Describe the bug

When using an Elixir/Mix umbrella application, Renovate is not updating the `mix.lock` file when updating dependencies in the `mix.exs` file of any of the apps within the umbrella, only when it changes the root `mix.exs` file. I believe the issue originated here: https://github.com/renovatebot/renovate/pull/10689. 

Minimal reproduction repo here:
https://github.com/tpbowden/renovate-umbrella-reproduction

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: mix.getArtifacts(apps/demo_app/mix.exs)(branch="renovate/plug-1.x")
DEBUG: No mix.lock found(branch="renovate/plug-1.x")
DEBUG: Updated 1 package files(branch="renovate/plug-1.x")
DEBUG: No updated lock files in branch(branch="renovate/plug-1.x")
DEBUG: 1 file(s) to commit(branch="renovate/plug-1.x")
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by tpbowden**
## Changes:

Currently, renovate only looks for `mix.lock` in the same directory as `mix.exs`, but in umbrella apps there is only one `mix.lock` file at the top level of the repository. This change means we recursively look in parent directories until finding a `mix.lock` file.

Output from the fork can be seen here: https://github.com/tpbowden/renovate-umbrella-reproduction/pull/5

## Context:

Closes https://github.com/renovatebot/renovate/issues/11851

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

File: lib/manager/mix/extract.ts [hunk 1]
```diff
@@ -67,7 +67,8 @@ export async function extractPackageFile(
     }
   }
   const res: PackageFile = { deps };
-  const lockFileName = getSiblingFileName(fileName, 'mix.lock');
+  const lockFileName =
+    (await findLocalSiblingOrParent(fileName, 'mix.lock')) || 'mix.lock';
```
Comment (viceice) [inline lib/manager/mix/extract.ts:71]: Why the fallback

Comment (tpbowden) [reply lib/manager/mix/extract.ts:71]: It needs to be a string, otherwise it causes an exception if there is no lockfile at all. There is a test case covering this which failed on my first commit

**Review by viceice — APPROVED** [review]
