### PR TITLE
fix(autoreplace): avoid mistaken duplicate replace

### LINKED ISSUE #19174: sbt: unrelated dependencies in same PR
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

33.2.0 / 34.42.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When same version is used for different dependencies, it happens that a single MR is created for the dependencies even though they are totally unrelated.

Example:
```scala
lazy val root = (project in file("."))

val slf4jVersion = "2.0.4"

libraryDependencies ++= Seq(
    "dev.zio" %% "zio" % "2.0.4"
)

dependencyOverrides ++= Seq(
  // Enforce SLF4J consistency
  "org.slf4j" % "slf4j-api" % slf4jVersion,
  "org.slf4j" % "jcl-over-slf4j" % slf4jVersion,
  "org.slf4j" % "jul-to-slf4j" % slf4jVersion,
)
```

With this very example, we got a single PR opened trying to update both versions to 2.0.5 even though only SLF4J dependency has a 2.0.5 available and anyway these two dependencies are absolutely not related.

My feeling is that it's related to the usage of a variable in one of the dependency (`val slf4jVersion`).

EDIT: it seems it's also related to the `dependencyOverrides` presence, if `slf4j-api` is present in `libraryDependencies` only, the issue does not appear.

### Relevant debug logs

_No response_

### Have you created a minimal reproduction repository?

https://github.com/gaeljw/bug_renovate_19174

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Performs an already-updated check before performing update

## Context

Closes #19174

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

File: lib/workers/repository/update/branch/auto-replace.ts [hunk 1]
```diff
@@ -65,7 +65,7 @@ export async function confirmIfDepUpdated(
         expectedValue: newValue,
         foundValue: newUpgrade.currentValue,
       },
-      'Value mismatch'
+      'Value is not updated'
```
Comment (rarkins) [inline lib/workers/repository/update/branch/auto-replace.ts:68]: I adjusted this so that it does not "alarm" users so much

File: lib/workers/repository/update/branch/auto-replace.ts [hunk 2]
```diff
@@ -133,7 +133,8 @@ async function checkExistingBranch(
 export async function doAutoReplace(
   upgrade: BranchUpgradeConfig,
   existingContent: string,
-  reuseExistingBranch: boolean
+  reuseExistingBranch: boolean,
+  firstUpdate = true
```
Comment (rarkins) [inline lib/workers/repository/update/branch/auto-replace.ts:137]: Small optimization to not preemptively check if it's the first autoreplace on the branch

**Review by viceice — DISMISSED** [review]
