### PR TITLE
fix(datasource/go): use @latest to determine pseudo version

### LINKED ISSUE #28707: GOPROXY + pseudoversions: skip direct lookup fallback when @latest is known
### Describe the proposed change(s).

If GOPROXY is used, and `@v/list` returns empty for a pseudo version while `@latest` returns a version, then use that version as the only version in order to skip the fallback to github.com lookups.

Example dependency: 

```
require (
	k8s.io/utils v0.0.0-20230220204549-a5ecb0141aa5
)
```

https://proxy.golang.org/k8s.io/utils/@latest returns:

```
{"Version":"v0.0.0-20240423183400-0849a56e8f22","Time":"2024-04-23T18:34:00Z","Origin":{"VCS":"git","URL":"https://github.com/kubernetes/utils","Hash":"0849a56e8f2216ce029590a538a9b50f301a90ae"}}
```

In such a case there's no need to fall back to looking it up from github.com, instead we can use `v0.0.0-20240423183400-0849a56e8f22` as the result.

### PR DESCRIPTION
**Pull request by rarkins**
## Context

Fixes #28707

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Reproduction: https://github.com/renovate-reproductions/argo-cd/pull/4/files

File: lib/modules/datasource/go/releases-goproxy.ts [hunk 1]
```diff
@@ -119,29 +134,13 @@ export class GoProxyDatasource extends Datasource {
...
-        const pseudoVersionReleaseTimestamp = DateTime.fromFormat(
-          timestamp,
-          'yyyyMMddHHmmss',
-          { zone: 'UTC' },
-        ).toISO({ suppressMilliseconds: true });
-        if (pseudoVersionReleaseTimestamp) {
-          release.releaseTimestamp = pseudoVersionReleaseTimestamp;
-        }
-      }
+      release = pseudoVersionToRelease(version) ?? release;
```
Comment (secustor) [inline lib/modules/datasource/go/releases-goproxy.ts:143]:
```suggestion
```

File: lib/modules/datasource/go/releases-goproxy.ts [hunk 2]
```diff
@@ -119,29 +134,13 @@ export class GoProxyDatasource extends Datasource {
       }
 
       const [version, releaseTimestamp] = str.trim().split(regEx(/\s+/));
-      const release: Release = { version };
+      let release: Release = { version };
```
Comment (secustor) [inline lib/modules/datasource/go/releases-goproxy.ts:137]:
```suggestion
      const release: Release = pseudoVersionToRelease(version) ?? { version };
```

**Review by viceice — APPROVED** [review]
