### PR TITLE
fix(bitbucket-server): PR update with invalid reviewers

### LINKED ISSUE #7696: Bitbucket Server fails to update PR and aborts if containing invalid reviewer
**What Renovate type, platform and version are you using?**
self-hosted with BitBucket Server
v23.77.0

**Describe the bug**

Some of our repositories "hang", in the debug log I cannot really figure out what is wrong. The repository definitely does not change during renovation.

It also happens on every run not just sometimes.

The branch in question is up2date with master, so the rebasing works. The PR was created because automerge check failed and the checks still fail for the PR.

**Relevant debug logs**

```
DEBUG: 3 PRs are currently open (repository=INFRASTRUCTURE/launchpad)
DEBUG: PR concurrent limit remaining: 17 (repository=INFRASTRUCTURE/launchpad)
DEBUG: Calculated maximum PRs remaining this run (repository=INFRASTRUCTURE/launchpad)
       "prsRemaining": 2
DEBUG: getBranchPr(renovate/spire-monorepo) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: findPr(renovate/spire-monorepo, "undefined", "open") (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPrList() (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: returning cached PR list (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Found PR #85 (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPr(85) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: processBranch with 2 upgrades (repository=INFRASTRUCTURE/launchpad, dependencies=@researchgate/spire-config,spire, branch=renovate/spire-monorepo)
DEBUG: Setting current branch to master (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: latest commit (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
       "branchName": "master",
       "latestCommitDate": "2020-10-08T17:06:30+00:00"
DEBUG: getBranchPr(renovate/spire-monorepo) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: findPr(renovate/spire-monorepo, "undefined", "open") (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPrList() (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: returning cached PR list (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Found PR #85 (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPr(85) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: branchExists=true (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Branch pr rebase requested: false (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Branch has 2 upgrade(s) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Checking if PR has been edited (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Found existing branch PR (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Checking schedule(at any time, Europe/Berlin) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: No schedule defined (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Branch already exists (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getBranchPr(renovate/spire-monorepo) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: findPr(renovate/spire-monorepo, "undefined", "open") (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPrList() (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: returning cached PR list (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Found PR #85 (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPr(85) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getRepoForceRebase() (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Branch does not need rebasing (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Using reuseExistingBranch: true (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: manager.getUpdatedPackageFiles() (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
       "reuseExistingBranch": true,
       "branchName": "renovate/spire-monorepo"
DEBUG: npm.updateDependency(): devDependencies.@researchgate/spire-config = 4.1.1 (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: npm.updateDependency(): devDependencies.spire = 2.2.1 (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: No package files need updating (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Getting updated lock files (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: lock file dirs (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
       "dirs": {
         "yarnLockDirs": [],
         "npmLockDirs": [],
         "pnpmShrinkwrapDirs": [],
         "lernaDirs": []
       }
DEBUG: Writing repo .npmrc (/tmp/renovate/repos/bitbucket-server/INFRASTRUCTURE/launchpad) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Writing repo .yarnrc (/tmp/renovate/repos/bitbucket-server/INFRASTRUCTURE/launchpad) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Writing package.json files (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
       "packageFiles": ["package.json"]
DEBUG: Writing .yarnrc to /tmp/renovate/repos/bitbucket-server/INFRASTRUCTURE/launchpad (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Writing any updated package files (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: No updated lock files in branch (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: No files to commit (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPr(85) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Checking if we can automerge branch (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getBranchPr(renovate/spire-monorepo) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: findPr(renovate/spire-monorepo, "undefined", "open") (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPrList() (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: returning cached PR list (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Found PR #85 (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPr(85) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: mergeStatus=automerge aborted - PR exists (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Branch automerge not possible (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
       "mergeStatus": "automerge aborted - PR exists"
DEBUG: Ensuring PR (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: There are 0 errors and 0 warnings (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getBranchPr(renovate/spire-monorepo) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: findPr(renovate/spire-monorepo, "undefined", "open") (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPrList() (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: returning cached PR list (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Found PR #85 (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPr(85) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Found existing PR (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getBranchStatus(renovate/spire-monorepo, requiredStatusChecks=true) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: branch status check result (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
       "commitStatus": {"successful": 0, "inProgress": 0, "failed": 2}
DEBUG: getPrBody(This PR contains the following updates:) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Processing existing PR (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: PR body changed (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
       "prTitle": "chore(deps): update spire monorepo"
DEBUG: updatePr(85, title=chore(deps): update spire monorepo) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: getPr(85) (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Passing error up (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
DEBUG: Passing PR error up (repository=INFRASTRUCTURE/launchpad, branch=renovate/spire-monorepo)
 INFO: Repository has changed during renovation - aborting (repository=INFRASTRUCTURE/launchpad)
DEBUG: Repository timing splits (milliseconds) (repository=INFRASTRUCTURE/launchpad)
       "splits": {"init": 3383, "extract": 3655, "lookup": 3584},
       "total": 14158
DEBUG: http statistics (repository=INFRASTRUCTURE/launchpad)
       "hostStats": [
         "api.github.com, 18 requests, 303ms request average, 0ms queue average",
         "git.rgoffice.net, 13 requests, 166ms request average, 0ms queue average",
         "nexus3.rgoffice.net, 8 requests, 340ms request average, 0ms queue average"
       ],
       "totalRequests": 39
```

**To Reproduce**

Nothing to reproduce as these are all private repos.

**Additional context**

### PR DESCRIPTION
**Pull request by danez**
Also always log the error in any case for better visibility

## Changes:

Check the body in the 409 response case if the errors returned are only about invalid reviewers and if this is the case do not throw REPOSITORY_CHANGED. There are more cases that could be handled gracefully besides invalid reviewers, but I don't have example responses to add this.

Also in any case I added logging the actual HTTP error with `logger.fatal`. I think it is good to see the error in the log even if afterwards we throw `REPOSITORY_CHANGED`.

## Context:

Fixes #7696 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

File: lib/platform/bitbucket-server/index.ts [hunk 1]
```diff
@@ -577,15 +580,24 @@ export async function addReviewers(
     );
     await getPr(prNo, true);
   } catch (err) {
+    logger.fatal(
+      { err },
+      `Failed to add reviewers '${reviewers.join(', ')}' to #${prNo}`
+    );
```
Comment (rarkins) [inline lib/platform/bitbucket-server/index.ts:586]:
```suggestion
    logger.warn({ err, reviewers, prNo }, 'Failed to add reviewers');
```

File: lib/platform/bitbucket-server/index.ts [hunk 2]
```diff
@@ -577,15 +580,24 @@ export async function addReviewers(
...
+        errors.every(
+          (error) => error?.exceptionName === BITBUCKET_INVALID_REVIEWERS
+        )
+      ) {
+        // If the errors are only about invalid reviewers do not throw REPOSITORY_CHANGED
+        throw err;
+      }
       throw new Error(REPOSITORY_CHANGED);
     } else {
-      logger.fatal(
```
Comment (rarkins) [inline lib/platform/bitbucket-server/index.ts:585]: Weird, we should never have had a fatal error!

File: lib/platform/bitbucket-server/index.ts [hunk 3]
```diff
@@ -891,12 +903,21 @@ export async function updatePr({
...
+    logger.fatal({ err }, `Failed to update PR`);
     if (err.statusCode === 404) {
       throw new Error(REPOSITORY_NOT_FOUND);
     } else if (err.statusCode === 409) {
+      const errors = err?.response?.body?.errors || [];
+      if (
+        errors.every(
+          (error) => error?.exceptionName === BITBUCKET_INVALID_REVIEWERS
+        )
+      ) {
```
Comment (rarkins) [inline lib/platform/bitbucket-server/index.ts:915]: We shouldn't duplicate this logic. Maybe better to introduce a new error code and throw it from below. Also, should we try re-submitting or re-updating the PR *without* reviewers?

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/platform/bitbucket-server/index.ts (hunk 1 above)
Comment (danez) [reply lib/platform/bitbucket-server/index.ts]: Done

File: lib/platform/bitbucket-server/index.ts (hunk 3 above)
Comment (danez) [reply lib/platform/bitbucket-server/index.ts]: I extracted the logic into a separate function.

I also added the retry logic for `updatePR()`. I did sneak in an "internal" property in the object which is supplied to `updatePR`, so I can simply use recursion. Not sure if you are okay with doing this?

I did not add the retry logic to `addReviewers` yet, because of two things:

- The logic is different because imho it should not retry if the supplied username is invalid, but only if the username is one that is coming from the bb API. Unless you disagree I think it would be weird calling `addReviewers(5, ['name'])` whereas `name` is invalid and gets simply ignored.
- `addReviewers` has two fixed arguments so I'm not sure if it would be okay here to do the recursion by adding a 3rd optional argument like `invalidReviewers = null`. I guess that is somehow not okay as all the exported methods somehow follow some internal API for platforms?

**Review by viceice — CHANGES_REQUESTED** [review]
Update pr can cause this exception when an assigned reviewer becomes invalid? How does the bitbucket ui handle this?

**Comment by danez** [comment]
> Update pr can cause this exception when an assigned reviewer becomes invalid? How does the bitbucket ui handle this?

In the UI the user is shown but with the default avatar and the only thing you can do is remove the user.

The problem here is that the API returns inactive users when requesting the PR, but it does not accept when the user is sent back.

File: lib/platform/bitbucket-server/index.ts [hunk 4]
```diff
@@ -549,6 +552,30 @@ export function addAssignees(iid: number, assignees: string[]): Promise<void> {
   return Promise.resolve();
 }
 
+function isInvalidReviewersResponse(err: any): string[] {
```
[the remark this answers is not in the document]
Comment (danez) [reply lib/platform/bitbucket-server/index.ts:555]: Copy&Paste 🙄 
Interesting though that ts does not throw

File: lib/platform/bitbucket-server/index.ts [hunk 5]
```diff
@@ -843,7 +867,10 @@ export async function updatePr({
   prTitle: title,
   prBody: rawDescription,
   state,
-}: UpdatePrConfig): Promise<void> {
+  bitbucketInvalidReviewers,
```
[the remark this answers is not in the document]
Comment (danez) [reply lib/platform/bitbucket-server/index.ts:870]: This is on purpose so the check in catch works. The code is only retrying the call if `bitbucketInvalidReviewers ` is undefined. This ensures we retry only once.

File: lib/platform/bitbucket-server/index.ts [hunk 6]
```diff
@@ -549,6 +552,30 @@ export function addAssignees(iid: number, assignees: string[]): Promise<void> {
...
+      (error) => error?.exceptionName === BITBUCKET_INVALID_REVIEWERS
+    )
+  );
+}
+
+function getInvalidReviewers(err: any): string[] {
+  const errors = err?.response?.body?.errors || [];
+  let invalidReviewers = [];
+  for (const error of errors) {
+    if (error?.exceptionName === BITBUCKET_INVALID_REVIEWERS) {
```
[the remark this answers is not in the document]
Comment (danez) [reply lib/platform/bitbucket-server/index.ts]: In general the code is written very defensively, because errors are not documented, and I simply reverse engineered what the API returns. But here it's probably safe it will never be null.

File: lib/platform/bitbucket-server/index.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (rarkins) [reply lib/platform/bitbucket-server/index.ts:870]: I guess checking for non-zero length would also work? @viceice do you have a preference either way?

[the remark this answers is not in the document]
Comment (viceice) [reply lib/platform/bitbucket-server/index.ts:870]: Sure, we can leave it as is. I've no preference here.

**Review by viceice — DISMISSED** [review]

File: lib/platform/bitbucket-server/index.ts [hunk 7]
```diff
@@ -549,6 +552,30 @@ export function addAssignees(iid: number, assignees: string[]): Promise<void> {
...
+    if (error.exceptionName === BITBUCKET_INVALID_REVIEWERS) {
+      invalidReviewers = invalidReviewers.concat(
+        error.reviewerErrors?.map(({ context }) => context) || []
+      );
+    }
+  }
+
+  return invalidReviewers;
+}
+
```
Comment (viceice) [inline lib/platform/bitbucket-server/index.ts:578]: Lets move this helper to a seperate file (eg `utils.ts` or `re), as this file is already very big.

**Review by viceice — COMMENTED** [review]
Just a small change

File: lib/platform/bitbucket-server/index.ts (hunk 7 above)
Comment (danez) [reply lib/platform/bitbucket-server/index.ts:578]: Will do

Comment (danez) [reply lib/platform/bitbucket-server/index.ts]: I moved them and also added proper types for the Error.

File: lib/platform/bitbucket-server/utils.ts [hunk 8]
```diff
@@ -118,3 +122,38 @@ export interface BitbucketStatus {
   key: string;
   state: BitbucketBranchState;
 }
+
+interface BitbucketErrorResponse {
+  errors?: Array<{
+    exceptionName?: string;
+    reviewerErrors?: Array<{ context?: string }>;
+  }>;
```
Comment (viceice) [inline lib/platform/bitbucket-server/utils.ts:130]:
```suggestion
  errors?: {
    exceptionName?: string;
    reviewerErrors?: { context?: string }[];
  }[];
```
uses short array type to be more consistent

**Review by viceice — COMMENTED** [review]
some small changes

File: lib/platform/bitbucket-server/utils.ts (hunk 8 above)
Comment (danez) [reply lib/platform/bitbucket-server/utils.ts]: 👍

**Review by viceice — APPROVED** [review]

**Comment by danez** [comment]
Thanks
