### PR TITLE
fix(manager/gomod): GitLab Private Authentication

### LINKED ISSUE #12912: Gitlab git host rule for gomod does not work
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

https://gitlab.com/renovate-bot/renovate-runner/

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Describe the bug

The url created for git authentication for gomod for private gitlab repositories creates an invalid url.

The following config.js

```js
module.exports = {
  hostRules: [
    {
      matchHost: 'gitlab.com',
      token: process.env.CI_JOB_TOKEN,
      hostType: 'gitlab',
    },
  ]
};
```

leds to this error message `exit status 128:\n\tfatal: could not read Password for 'https://[MASKED]@gitlab.com': terminal prompts disabled\n"`

According to [this](https://stackoverflow.com/questions/25409700/using-gitlab-token-to-clone-without-authentication?rq=1) Post on Stackoverflow, Gitlab does not support token only authentication.

Looking at https://github.com/renovatebot/renovate/blob/main/lib/manager/gomod/artifacts.ts, it appears that a username cannot be set. Trying to cheat the system by prepending the username with a colon `token: 'gitlab-ci-token:'.concat(process.env.CI_JOB_TOKEN),` does not appear to work.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by 56KBs**
## Changes:

When authenticating with GitLab for https Git commands using an access token, you must provide a username with the token - Otherwise authentication fails.

CI tokens generated by GitLab should use the username `gitlab-ci-token`, see https://docs.gitlab.com/14.5/ee/ci/jobs/ci_job_token.html for an example.

Personal Access Tokens also require a username to be associated for HTTPS Git commands, however this does not have to match the username associated with the token, see https://docs.gitlab.com/14.5/ee/user/profile/personal_access_tokens.html. Meaning in this scenario, it is safe to also use `gitlab-ci-token` as the username for the token for HTTPS Git commands.

## Context:

Closes #12912

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/git/auth.ts [hunk 1]
```diff
@@ -1,4 +1,6 @@
+import { PlatformId } from '../../constants';
 import { logger } from '../../logger';
+import { HostRule } from '../../types';
```
Comment (viceice) [inline lib/util/git/auth.ts:3]:
```suggestion
import type { HostRule } from '../../types';
```

**Review by viceice — APPROVED** [review]
