### PR TITLE
fix(manager:regex): allow no match in combination

### LINKED ISSUE #11385: [ Regex manager ] Reduce of empty array with no initial value
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

26.4.2

### Describe the bug

After upgrading renovate from 25.76.1 to 26.4.2 our pipeline has started to crash.

Minimal reproduction repository :
- This preset with regexManagers seems to be the root cause : https://gitlab.com/ajoux.accor/renovate/-/blob/v26/typeError/config-presets/helm-only-regex.json 
- Full logs can be found here : https://gitlab.com/ajoux.accor/renovate/-/jobs/1526170501 
- We have no errors with 25.76.1 : https://gitlab.com/ajoux.accor/renovate/-/jobs/1526252311 ( https://gitlab.com/ajoux.accor/renovate/-/compare/v26%2FtypeError...v25%2Fno-typeError?from_project_id=29062157 ) 

### Relevant debug logs

<details><summary>Logs</summary>

```
 "err": {
         "message": "Reduce of empty array with no initial value",
         "stack": "TypeError: Reduce of empty array with no initial value\n    at Array.reduce (<anonymous>)\n    at handleCombination (/usr/src/app/node_modules/renovate/lib/manager/regex/index.ts:152:6)\n    at Object.extractPackageFile (/usr/src/app/node_modules/renovate/lib/manager/regex/index.ts:199:14)\n    at Object.extractPackageFile (/usr/src/app/node_modules/renovate/lib/manager/index.ts:81:9)\n    at Object.getManagerPackageFiles (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:51:25)\n    at /usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:45:28\n    at async Promise.all (index 2)\n    at Object.extractAllDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:43:26)\n    at Object.extract (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:82:20)\n    at Object.extractDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/process/index.ts:58:26)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:46:52)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:111:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"
       }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by viceice**
## Changes:
 Check for empty combination matches and return early.

## Context:

fixes #11385

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/manager/regex/index.ts [hunk 1]
```diff
@@ -147,12 +147,17 @@ function handleCombination(
...
+    return [];
+  }
+
   const combinedGroup = matches
     .map((match) => match.groups)
     .reduce((mergedGroup, currentGroup) =>
       mergeGroups(mergedGroup, currentGroup)
     );
 
+  // TODO: this seems to be buggy behavior, needs to be checked
```
Comment (rarkins) [inline lib/manager/regex/index.ts:160]: Can you create an issue for this and include it in the TODO?

**Review by rarkins — DISMISSED** [review]

File: lib/manager/regex/index.ts (hunk 1 above)
Comment (viceice) [reply lib/manager/regex/index.ts:160]: sure

**Review by rarkins — APPROVED** [review]
