### PR TITLE
fix(presets): Spring Boot group includes Gradle plugin

### LINKED ISSUE #11950: Group preset group:springBoot does not match Spring Boot Gradle plugin
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of Renovate you run.

27.4.0

### Describe the bug

Hello,

I have a Renovate Bot job on a Spring Boot project built using Gradle. The configuration includes `group:recommended` hence `group:springBoot`.

The project has a `build.gradle` (extract):

```
plugins {
  id 'java'
  id 'jacoco'
  id 'eclipse'
  id 'maven-publish'
  id 'distribution'
  id 'org.springframework.boot'
}

[...]

dependencies {
  implementation platform('org.springframework.boot:spring-boot-dependencies:2.5.4')
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-freemarker'
  implementation 'org.springframework.boot:spring-boot-starter-validation'
  implementation 'org.springframework.boot:spring-boot-starter-cache'
  implementation 'org.springframework.boot:spring-boot-configuration-processor'
  // ...
}
```

And a `settings.gradle`:

```
pluginManagement {
    plugins {
        id 'org.springframework.boot' version '2.5.4'
    }
}

rootProject.name = 'my-project'
```

When Renovate runs, it will create 2 PRs:

* Update plugin org.springframework.boot to v2.5.5 -> Updates the Gradle plugin version
* Update spring boot to v2.5.5 -> Updates Gradle dependencies

I suppose this is due to the [preset definition](https://github.com/renovatebot/renovate/blob/main/lib/config/presets/internal/group.ts#L268), asking for a comma after the groupId:

```
{
  "packageRules": [
    {
      "groupName": "spring boot",
      "matchPackagePrefixes": [
        "org.springframework.boot:"
      ]
    }
  ]
}
```

Should we group the plugin with the dependencies? I would say yes, as I suppose the rule would group the Maven plugins.
If yes, I guess this would do the trick:

```
{
  "packageRules": [
    {
      "groupName": "spring boot",
      "matchPackagePrefixes": [
        "org.springframework.boot",
        "org.springframework.boot:"
      ]
    }
  ]
}
```
Hoping the first entry would be an exact match, so it would match only the Gradle plugin?
I can open a PR as it shoudl be easy :)

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Using group branchName template (repository=CAPI/my-project)
DEBUG: Dependency org.springframework.boot:spring-boot-dependencies is part of group spring boot (repository=CAPI/my-project)
DEBUG: Using group branchName template (repository=CAPI/my-project)
DEBUG: Dependency org.springframework.boot:spring-boot-devtools is part of group spring boot (repository=CAPI/my-project)
DEBUG: Using group branchName template (repository=CAPI/my-project)
DEBUG: Dependency org.springframework.boot:spring-boot-dependencies is part of group spring boot (repository=CAPI/my-project)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by Xendar**
## Changes:

Including a `matchPackagePrefixes` for the Spring Boot Gradle plugin for the `group:springBoot` preset.

## Context:

Closes #11950 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

N.B.: I think no update of [documentation](https://docs.renovatebot.com/presets-group/#groupspringboot) is required as it should be updated automatically, let me know if I'm wrong!

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

N.B.: Tested on my self-hosted Renovate, the grouping was successful

### CODE REVIEW

File: lib/config/presets/internal/group.ts [hunk 1]
```diff
@@ -265,7 +265,7 @@ const staticGroups = {
     packageRules: [
       {
         groupName: 'spring boot',
-        matchPackagePrefixes: ['org.springframework.boot:'],
+        matchPackagePrefixes: ['org.springframework.boot:', 'org.springframework.boot'],
```
Comment (viceice) [inline lib/config/presets/internal/group.ts:268]: This won't work as you intended. All prefixes are matched with `startsWith`

**Review by viceice — CHANGES_REQUESTED** [review]
Fix git author and do a force push

File: lib/config/presets/internal/group.ts (hunk 1 above)
Comment (Xendar) [reply lib/config/presets/internal/group.ts:268]: Thanks @viceice for the information.
So, it's not considering a pattern as well, something like `'^org.springframework.boot$'` won't work then.
Would a mix of `matchPackagePrefixes` and  `matchPackageNames` work? Like:

```
"packageRules": [
    {
      "groupName": "spring boot",
      "matchPackagePrefixes": [
        "org.springframework.boot:"
      ],
      "matchPackageNames": [
        "org.springframework.boot"
      ]
    }
  ]
```

**Comment by Xendar** [comment]
> Fix git author and do a force push

Apologies, I misconfigured my repository. It has been fixed

**Review by viceice — APPROVED** [review]
I think this should work as expected

File: lib/config/presets/internal/group.ts (hunk 1 above)
Comment (Xendar) [reply lib/config/presets/internal/group.ts]: It does the trick it seems!

```
DEBUG: Using group branchName template (repository=CAPI/my-project)
DEBUG: Dependency org.springframework.boot:spring-boot-dependencies is part of group spring boot (repository=CAPI/my-project)
DEBUG: Using group branchName template (repository=CAPI/my-project)
DEBUG: Dependency org.springframework.boot:spring-boot-devtools is part of group spring boot (repository=CAPI/my-project)
DEBUG: Using group branchName template (repository=CAPI/my-project)
DEBUG: Dependency org.springframework.boot:spring-boot-dependencies is part of group spring boot (repository=CAPI/my-project)
DEBUG: Using group branchName template (repository=CAPI/my-project)
DEBUG: Dependency org.springframework.boot is part of group spring boot (repository=CAPI/my-project)
```

**Review by viceice — APPROVED** [review]
