### PR TITLE
fix(template): Use proxy instead of deep clone

### LINKED ISSUE #17072: Instead of filter and clone handlebar template data we should use `Proxy` class
### Describe the proposed change(s).

Currently we filter the input object on each template compile, this is expensive (especially when we have huge change logs attached)

https://github.com/renovatebot/renovate/blob/5069b6010933e3aab044e703ec49e4a2d7d8a9ac/lib/util/template/index.ts#L197

we should use `Proxy` class instead on filter at calling time. We do something similar at platform

https://github.com/renovatebot/renovate/blob/5069b6010933e3aab044e703ec49e4a2d7d8a9ac/lib/modules/platform/index.ts#L16-L27

- #17063

### PR DESCRIPTION
**Pull request by zharinov**
## Context

- Closes: #17072

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/template/index.ts [hunk 1]
```diff
@@ -162,28 +161,35 @@ const allowedFieldsList = Object.keys(allowedFields)
...
+
+    if (is.plainObject(value)) {
+      return proxyCompileInput(value);
+    }
+
+    return value;
+  },
+};
+
+export function proxyCompileInput(input: CompileInput): CompileInput {
```
Comment (viceice) [inline lib/util/template/index.ts:191]: do we really need to make this public?

File: lib/util/template/index.ts [hunk 2]
```diff
@@ -162,28 +161,35 @@ const allowedFieldsList = Object.keys(allowedFields)
...
-    const value = obj[field];
+const allowedTemplateFields = new Set([
+  ...Object.keys(allowedFields),
+  ...exposedConfigOptions,
+]);
+
+const compileInputProxyHandler: ProxyHandler<CompileInput> = {
+  get(target: CompileInput, prop: keyof CompileInput): unknown {
+    if (!allowedTemplateFields.has(prop)) {
+      return undefined;
```
Comment (viceice) [inline lib/util/template/index.ts:172]: @rarkins  should we warn here?, so users know  they have errors in templates?

with this we can remove the manual template check with regex.

**Review by viceice — COMMENTED** [review]
otherwise LGTM

File: lib/util/template/index.ts (hunk 1 above)
Comment (zharinov) [reply lib/util/template/index.ts:191]: I think filtering should be tested as separate function, because it's quite important

File: lib/util/template/index.ts (hunk 2 above)
Comment (zharinov) [reply lib/util/template/index.ts:172]: If so, let's do this in separate PR maybe?

**Review by viceice — APPROVED** [review]
