### PR TITLE
fix: auto-replace for pinDigest without currentDigest or shortDigest

### LINKED ISSUE #20128: Docker Replacement Rules: Not working as expected
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I have had [this demonstration repository](https://github.com/setchy/renovate-replacements-docker) for a while in eager anticipation of the recently released support for [Docker replacement rules](https://github.com/renovatebot/renovate/pull/17883) 

I have a single `Dockerfile` with two images and two replacement rules.

My expected behavior is

- `FROM java:8` replaced with `FROM eclipse-temurin:8`
- `FROM bitnami/redis:6.2` replaced with `FROM mcr.microsoft.com/oss/bitnami/redis:6.0.8`

However, observed behavior is

- No replacement PR for `java`
- `bitnami/redis` PR only updates version number, doesn't update dependency name - see [PR](https://github.com/setchy/renovate-replacements-docker/pull/5)

Logs excerpt

```
{
  "baseBranch": "main",
  "config": {
    "dockerfile": [
      {
        "deps": [
          {
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "currentValue": "8",
            "currentVersion": "8",
            "datasource": "docker",
            "depIndex": 0,
            "depName": "java",
            "depType": "stage",
            "fixedVersion": "8",
            "registryUrl": "https://index.docker.io",
            "replaceString": "java:8",
            "versioning": "regex:^(?<major>\\d+)?(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))?([\\._+](?<build>\\d+))?(-(?<compatibility>.*))?$",
            "warnings": [],
            "updates": []
          },
          {
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "currentValue": "6.2",
            "currentVersion": "6.2",
            "datasource": "docker",
            "depIndex": 1,
            "depName": "bitnami/redis",
            "depType": "final",
            "fixedVersion": "6.2",
            "isSingleVersion": true,
            "registryUrl": "https://index.docker.io",
            "replaceString": "bitnami/redis:6.2",
            "sourceDirectory": "bitnami/redis",
            "sourceUrl": "https://github.com/bitnami/containers",
            "versioning": "docker",
            "warnings": [],
            "updates": [
              {
                "updateType": "replacement",
                "newName": "mcr.microsoft.com/oss/bitnami/redis",
                "newValue": "6.0.8",
                "branchName": "renovate/bitnami-redis-replacement"
              },
              {
                "bucket": "major-7",
                "newVersion": "7.0",
                "newValue": "7.0",
                "newMajor": 7,
                "newMinor": 0,
                "updateType": "major",
                "branchName": "renovate/bitnami-redis-7.x"
              }
            ]
          }
        ],
        "packageFile": "Dockerfile"
      }
    ]
  }
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by setchy**
## Changes

This PR handles two new scenarios when using auto-replacement rules

**Scenario 1**
- `pinDigests` are enabled
-  dependency targeted for replacement does not have a `currentDigest`
  
 **Scenario 2**
- `digestShort` SHAs are being used
 
In both scnearios, the [verification logic](https://github.com/renovatebot/renovate/blob/main/lib/workers/repository/update/branch/auto-replace.ts#L82) deems these as invalid and therefore no branches are created/updated.

I have validated these changes locally running about our Bitbucket Cloud test repository

## Context

Resolves https://github.com/renovatebot/renovate/issues/20128

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/repository/update/branch/auto-replace.ts [hunk 1]
```diff
@@ -198,11 +199,15 @@ export async function doAutoReplace(
...
-          newDigest
-        );
+      if (newDigest) {
+        if (currentDigest) {
+          newString = newString.replace(
+            regEx(escapeRegExp(currentDigest), 'g'),
+            newDigest
+          );
+        } else if (pinDigests) {
+          newString = `${newString}@${newDigest}`;
```
Comment (viceice) [inline lib/workers/repository/update/branch/auto-replace.ts:209]: this only works for docker images and will break all other managers with different dep types.

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/workers/repository/update/branch/auto-replace.ts (hunk 1 above)
Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.ts:209]: @viceice - good feedback.  

do you have a suggestion on how to best proceed... would an additional guard make sense to check if it's a docker update?  

alternatively, perhaps `confirmIfDepUpdated` function could be updated to better handle this edge-case

Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.ts]: I've pivoted to a different solution to handle this edge-case.  explanation added as a comment below

**Comment by setchy** [comment]
I've pivoted to a different solution thanks to @viceice initial feedback.

In this new method, replacements without a `currentDigest` will not attempt to add a `newDigest` in the same branch/PR, while replacements with a `currentDigest` will ensure its updated tothe `newDigest` value

**Review by viceice — COMMENTED** [review]
looks good so far, can you make a more complex non-docker regex manager sample?

**Comment by setchy** [comment]
I've added two `regex manager` tests.



_An observation I had while doing so....  I had some "fun" due to the test data I originally selected and the way in which the existing implementation of [version replacement ](https://github.com/renovatebot/renovate/blob/main/lib/workers/repository/update/branch/auto-replace.ts#L189) and [digest replacement](https://github.com/renovatebot/renovate/blob/main/lib/workers/repository/update/branch/auto-replace.ts#L201) is handled._

_For example, I began with a test case to replace `image:1@sha256:1a2b` with `new-image:3.14@sha256:9p8o`.  What ended up happening after the version replacement step is a string of `image:3.14@sha256:3.14a2b" which then skips the digest replacement step, which ultimately gets caught in the final `confirmIfDepUpdated` check.  I think fixing this interesting edge-case (if at all) should be in a separate issue/PR_

File: lib/workers/repository/update/branch/auto-replace.spec.ts [hunk 2]
```diff
@@ -909,7 +909,7 @@ describe('workers/repository/update/branch/auto-replace', () => {
       const tf = codeBlock`
         module "vpc" {
           source  = "terraform-aws-modules/vpc/aws"
-         version = "3.14.2"
+          version = "3.14.2"
```
Comment (viceice) [inline lib/workers/repository/update/branch/auto-replace.spec.ts:912]: ?

**Review by viceice — COMMENTED** [review]
please add a GitHub actions test. there we've digest pinning too.

File: lib/workers/repository/update/branch/auto-replace.spec.ts (hunk 2 above)
Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.spec.ts:912]: The indentation was off

**Comment by setchy** [comment]
> please add a GitHub actions test. there we've digest pinning too.

github actions / github-tags tests added

File: lib/workers/repository/update/branch/auto-replace.spec.ts [hunk 3]
```diff
@@ -1038,5 +1038,191 @@ describe('workers/repository/update/branch/auto-replace', () => {
...
+      `;
+      upgrade.manager = 'github-actions';
+      upgrade.datasource = 'github-tags';
+      upgrade.depName = 'actions/checkout';
+      upgrade.currentValue = 'v1.0.0';
+      upgrade.currentDigest = undefined;
+      upgrade.depIndex = 0;
+      upgrade.pinDigests = true;
+      upgrade.updateType = 'replacement';
+      upgrade.replaceString = 'actions/checkout@v1.0.0';
```
Comment (viceice) [inline lib/workers/repository/update/branch/auto-replace.spec.ts:1154]: i think you need the auto-replace template which is normally set by the github actions manager 🤔

Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.spec.ts:1154]: Added to the two github-actions replacement tests, although it won't be used due to [this conditional check](https://github.com/renovatebot/renovate/blob/51107e31608f81111774cf6aee77a1d2074fe7a3/lib/workers/repository/update/branch/auto-replace.ts#L185)

Furthermore, added two other github-actions tests to cover scenarios where we're not changing the action name

File: lib/workers/repository/update/branch/auto-replace.spec.ts [hunk 4]
```diff
@@ -1038,5 +1038,284 @@ describe('workers/repository/update/branch/auto-replace', () => {
...
+        'image: "some.other.url.com/some-new-repo:3.16@sha256:p0o9i8u7z6t5r4e3w2q1"'
+      );
+    });
+
+    it('github-actions: update with newValue only', async () => {
+      const githubaction = codeBlock`
+        name: build
+
+        on: [push]
+
```
Comment (viceice) [inline lib/workers/repository/update/branch/auto-replace.spec.ts:1139]: i think you can remove this, not relevant for test. so test is a little bit less verbose and big

File: lib/workers/repository/update/branch/auto-replace.spec.ts [hunk 5]
```diff
@@ -1038,5 +1038,284 @@ describe('workers/repository/update/branch/auto-replace', () => {
...
+        jobs:
+          build:
+            runs-on: ubuntu-latest
+            steps:
+              - uses: actions/checkout@2485f4d55aae6c5b073114bc4c4b1907c0abae14166281beee7d93f76ebf41fc # tag=v1.0.0
```
Comment (viceice) [inline lib/workers/repository/update/branch/auto-replace.spec.ts:1282]: why are the git sha so long? can we shorten them for better readability?

File: lib/workers/repository/update/branch/auto-replace.spec.ts (hunk 4 above)
Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.spec.ts:1139]: Done ✅

File: lib/workers/repository/update/branch/auto-replace.spec.ts (hunk 5 above)
Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.spec.ts:1262]: Because the github-actions manager validates either [sha](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/github-actions/extract.ts#L17) or [shaShort](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/github-actions/extract.ts#L18)

Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.spec.ts]: Done.  In doing so, I uncovered that the auto-replace didn't currently support digestShort updates.  This is now resolved too

**Comment by setchy** [comment]
As part of updating the github-actions tests to use shortDigest formats (for readability), it was discovered that this scenario was also not handled by the auto-replace logic.  As such, I've updated the tests and added the necessary replacement step for shortDigests.  PR title has been renamed to represent the work

File: lib/workers/repository/update/branch/auto-replace.ts [hunk 6]
```diff
@@ -204,6 +213,12 @@ export async function doAutoReplace(
           newDigest
         );
       }
+      if (currentDigestShort && newDigest) {
```
Comment (viceice) [inline lib/workers/repository/update/branch/auto-replace.ts:216]:
```suggestion
      else if (currentDigestShort && newDigest) {
```

Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.ts]: Good suggestion 👍

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
needs some more 👀👀👀

File: lib/workers/repository/update/branch/auto-replace.spec.ts [hunk 7]
```diff
@@ -1038,5 +1038,250 @@ describe('workers/repository/update/branch/auto-replace', () => {
...
+      upgrade.updateType = 'replacement';
+      upgrade.replaceString = 'ubuntu:18.04';
+      upgrade.newName = 'alpine';
+      upgrade.newValue = '3.16';
+      upgrade.newDigest = 'sha256:p0o9i8u7z6t5r4e3w2q1';
+      upgrade.packageFile = 'Dockerfile';
+      const res = await doAutoReplace(upgrade, dockerfile, reuseExistingBranch);
+      expect(res).toBe(
+        codeBlock`
+          FROM alpine:3.16
```
Comment (secustor) [inline lib/workers/repository/update/branch/auto-replace.spec.ts:1061]: Shouldn't `pinDigests: true` lead to a digest even if there not one currently applied?
```suggestion
          FROM alpine:3.16@sha256:p0o9i8u7z6t5r4e3w2q1
```

File: lib/workers/repository/update/branch/auto-replace.spec.ts [hunk 8]
```diff
@@ -1038,5 +1038,250 @@ describe('workers/repository/update/branch/auto-replace', () => {
...
+      upgrade.replaceString = 'image: "some.url.com/my-repository:1.0"';
+      upgrade.packageFile = 'k8s/base/defaults.yaml';
+      upgrade.newName = 'some.other.url.com/some-new-repo';
+      upgrade.newValue = '3.16';
+      upgrade.newDigest = 'sha256:p0o9i8u7z6t5r4e3w2q1';
+      upgrade.matchStrings = [
+        'image:\\s*?\\\'?\\"?(?<depName>[^:\\\'\\"]+):(?<currentValue>[^@\\\'\\"]+)@?(?<currentDigest>[^\\s\\\'\\"]+)?\\"?\\\'?\\s*',
+      ];
+      const res = await doAutoReplace(upgrade, yml, reuseExistingBranch);
+      expect(res).toBe('image: "some.other.url.com/some-new-repo:3.16"');
```
Comment (secustor) [inline lib/workers/repository/update/branch/auto-replace.spec.ts:1107]: Same here

File: lib/workers/repository/update/branch/auto-replace.spec.ts [hunk 9]
```diff
@@ -1038,5 +1038,250 @@ describe('workers/repository/update/branch/auto-replace', () => {
...
+        githubAction,
+        reuseExistingBranch
+      );
+      expect(res).toBe(
+        codeBlock`
+          jobs:
+            build:
+              runs-on: ubuntu-latest
+              steps:
+                - uses: some-other-action/checkout@v2.0.0
```
Comment (secustor) [inline lib/workers/repository/update/branch/auto-replace.spec.ts:1244]: Here too ☝️

File: lib/workers/repository/update/branch/auto-replace.spec.ts (hunk 7 above)
Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.spec.ts:1061]: @secustor - thanks for the PR review.

I called out this behavior in this [comment above](https://github.com/renovatebot/renovate/pull/20317#issuecomment-1425112361) after feedback from @viceice [here](https://github.com/renovatebot/renovate/pull/20317#discussion_r1101824798)

Comment (secustor) [reply lib/workers/repository/update/branch/auto-replace.spec.ts:1061]: The missing `autoReplaceStringTemplate` which is added by the Dockerfile manager is the reason why . 
https://github.com/renovatebot/renovate/blob/90694bf398fea2f20c4892db48f61a6f420f8610/lib/modules/manager/dockerfile/extract.ts#L33

File: lib/workers/repository/update/branch/auto-replace.spec.ts (hunk 8 above)
Comment (secustor) [reply lib/workers/repository/update/branch/auto-replace.spec.ts:1107]: Please also add an example with a set `autoReplaceStringTemplate` where the digest is added.

**Review by JamieMagee — APPROVED** [review]
This looks great 🎉

File: lib/workers/repository/update/branch/auto-replace.spec.ts (hunk 7 above)
Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.spec.ts:1061]: Thanks @secustor - will update the test cases later today

Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.spec.ts:1061]: Ok, I've double confirmed what I mentioned above , adding `upgrade.autoReplaceStringTemplate=
        '{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}';` has no bearing with replacements because of how the [logic is inside doAutoReplace](https://github.com/renovatebot/renovate/blob/8af82990ee38f4e35071af01c8d124f401fa2bc1/lib/workers/repository/update/branch/auto-replace.ts#L196)

File: lib/workers/repository/update/branch/auto-replace.spec.ts (hunk 8 above)
Comment (setchy) [reply lib/workers/repository/update/branch/auto-replace.spec.ts:1107]: As above

**Comment by chezsmithy** [comment]
This should resolve #19999 as well.

**Review by secustor — APPROVED** [review]
