### PR TITLE
fix(github): fully support ghe for releases and tags datasource

### LINKED ISSUE #7751: registryStrategy isn't set in github-releases datasource
**What Renovate type, platform and version are you using?**

* self-hosted renovate (v 23.84.3)
* github-enterprise

**Describe the bug**

Custom registryUrl support for the _github-releases_ datasource has been recently introduced with #7657, but is actually not working in combination with the `regex` manager. As far as I can see the implementation of [`getReleases`](https://github.com/renovatebot/renovate/blob/master/lib/datasource/github-releases/index.ts#L40-L43) in the datasource is only able to handle a string as registryUrl. But as there is no `registryStrategy` set, it get's an array of strings right here.

https://github.com/renovatebot/renovate/blob/16e2b8ae904cc0d4566432bd8ba898b29fa1e7c3/lib/datasource/index.ts#L177-L197

My proposal would be to set it to 'first', like it is implemented in the [gitlab-tags](https://github.com/renovatebot/renovate/blob/16e2b8ae904cc0d4566432bd8ba898b29fa1e7c3/lib/datasource/gitlab-tags/index.ts#L10) datasource.

**Relevant debug logs**

```
11:20:26  DEBUG: GitHub 404 (repository=ghorg/renovate)
11:20:26         "url": "https://api.github.com/repos/ghorg/jenkins-lib-repo/releases?per_page=100"
11:20:26  DEBUG: Datasource 404 (repository=ghorg/renovate)
11:20:26         "datasource": "github-releases",
11:20:26         "lookupName": "ghorg/jenkins-lib-repo",
11:20:26         "url": "https://api.github.com/repos/ghorg/jenkins-lib-repo/releases?per_page=100"
```

**To Reproduce**

This is more or less the config I've tried to use. It simply tries to find some internal jenkins libraries (hosted in our internal github), to keep them up to date. Detection works like a charm, but the resolution of available version does not.

```
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "regex": {
        "enabled": true
    },
    "regexManagers": [
        {
            "fileMatch": ["(^|/)Jenkinsfile.*$"],
            "matchStrings": ["(?<depName>jenkins-lib)@(?<currentValue>v?[-_\\d\\.]+)"],
            "datasourceTemplate": "github-releases",
            "lookupNameTemplate": "ghorg/jenkins-lib-repo"
        }   
    ],
    "packageRules": [
        {
            "datasources": ["github-releases"],
            "registryUrls": ["https://<github.enterprise.corp>/"]
        }
    ]
}
```

This is how a Jenkinsfile looks like. 
```
@Library( 'jenkins-lib@1.2.3')

...
```

**Additional context**

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

Fully support GHE for `github-tags` and `github-releases` datasources.

* Set `registryStrategy = 'first'` for `github-tags` and `github-releases` datasources
* Add `defaultRegistryUrls` urls to both
* Add `registryUrl` to cache key
* Fix `github-tags.getDigest` to support registryUrl
  

## Context:

closes #7751

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

File: lib/datasource/github-releases/index.ts [hunk 1]
```diff
@@ -38,6 +40,11 @@ export async function getReleases({
   if (cachedResult) {
     return cachedResult;
   }
+  let depHost = registryUrl;
+  if (ensureTrailingSlash(depHost) === 'https://github.com/') {
+    depHost = null;
```
Comment (rarkins) [inline lib/datasource/github-releases/index.ts:45]: I don't understand this. Isn't it written back again in the subsequent code block?

Comment (volkc) [reply lib/datasource/github-releases/index.ts:45]: I think the only reason for this is to let `apiBaseUrl` point to _api.github.com_ in case github is passed as `registryUrl`, isn't it?

Comment (viceice) [reply lib/datasource/github-releases/index.ts:45]: yes, thats the cause. Maybe i can optimize /cleanup it some more, but first need to check, why some tests are failing now.

Any hints are helpful. 🙃

Comment (volkc) [reply lib/datasource/github-releases/index.ts:45]: Maybe an issue with the cache? It doesn't care about the `registryUrl` at all, the namespace is always set to **datasource-github-releases**.

https://github.com/renovatebot/renovate/blob/eca09cb1fd6bf17ddfc27d4c79c65191155e6968/lib/datasource/github-releases/index.ts#L35-L42

Comment (volkc) [reply lib/datasource/github-releases/index.ts:45]: I would just turn it off for a second and run the tests again to see if it helps.

Comment (viceice) [reply lib/datasource/github-releases/index.ts:50]: caching is turned of by default on tests, but iv'e fixed the cache keys now

**Comment by volkc** [comment]
I just figured out why the tests are failing. Let's have a look on this one:

https://github.com/renovatebot/renovate/blob/e9d3219dcf87dfcb6974abed3b619c7f998453aa/lib/workers/repository/process/lookup/index.spec.ts#L645-L664

As you can see there is no default registry set, thus `fetchReleases` returns null and doesn't even call the mock service.

https://github.com/renovatebot/renovate/blob/e9d3219dcf87dfcb6974abed3b619c7f998453aa/lib/datasource/index.ts#L177-L185

You can simply turn the test green by setting a default registry like this

```node
 it('should ignore unstable versions from datasource', async () => { 
   config.currentValue = '1.4.4'; 
   config.depName = 'some/action'; 
   config.datasource = datasourceGithubReleases.id; 
   config.registryUrls = ['https://github.com/'];
   githubReleases.getReleases.mockResolvedValueOnce({ 
     releases: [ 
       { 
         version: '1.4.4', 
       }, 
       { 
         version: '2.0.0', 
       }, 
       { 
         version: '2.1.0', 
         isStable: false, 
       }, 
     ], 
   }); 
   expect((await lookup.lookupUpdates(config)).updates).toMatchSnapshot(); 
 }); 
```

**Comment by volkc** [comment]
And if you would revert your changes for github-tags datasource then we could get all the tests green and follow up on these issues in a different Issue/PR. This is sufficient to solve #7751

**Comment by volkc** [comment]
I think this is the place that needs to be fixed in order to get the go datasource working again. The `registryUrl` needs to be extracted from the `goModule` and returned in lines [26](https://github.com/renovatebot/renovate/blob/e9d3219dcf87dfcb6974abed3b619c7f998453aa/lib/datasource/go/index.ts#L26-L29) and [34](https://github.com/renovatebot/renovate/blob/e9d3219dcf87dfcb6974abed3b619c7f998453aa/lib/datasource/go/index.ts#L34-L37). 

https://github.com/renovatebot/renovate/blob/e9d3219dcf87dfcb6974abed3b619c7f998453aa/lib/datasource/go/index.ts#L20-L38

**Comment by viceice** [comment]
Fixed all issues, succeeds locally. needs read runs. do we have any public ghe repo to test agains it?

@volkc can you test this branch?

File: lib/workers/repository/process/lookup/index.spec.ts [hunk 2]
```diff
@@ -35,6 +35,8 @@ docker.defaultRegistryUrls = ['https://index.docker.io'];
 const gitSubmodules = mocked(datasourceGitSubmodules);
 const githubReleases = mocked(datasourceGithubReleases);
 
+Object.assign(githubReleases, { defaultRegistryUrls: ['https://github.com'] });
```
Comment (viceice) [inline lib/workers/repository/process/lookup/index.spec.ts:38]: Required because we mock `github-releases`

File: lib/datasource/github-tags/index.ts [hunk 3]
```diff
@@ -164,25 +187,23 @@ export async function getReleases(
   const tagsResult = await getTags(config);
 
   try {
-    if (tagsResult?.releases) {
```
Comment (viceice) [inline lib/datasource/github-tags/index.ts:167]: This is always true.

File: lib/datasource/github-releases/index.ts [hunk 4]
```diff
@@ -27,27 +34,32 @@ type GithubRelease = {
...
-    : `https://api.github.com/`;
-  const url = URL.resolve(apiBaseUrl, `repos/${repo}/releases?per_page=100`);
+  // default to GitHub.com if no GHE host is specified.
+  const sourceUrlBase = ensureTrailingSlash(
+    registryUrl ?? 'https://github.com/'
+  );
+  const apiBaseUrl =
+    sourceUrlBase !== 'https://github.com/'
+      ? `${sourceUrlBase}api/v3/`
+      : `https://api.github.com/`;
```
Comment (viceice) [inline lib/datasource/github-releases/index.ts:54]: Maybe we should move this to a helper function at `util/http/github` ?

**Review by viceice — COMMENTED** [review]
Use `hide whitespace changes` to review 😉

**Comment by volkc** [comment]
> @volkc can you test this branch?

Yes, no problem. I'll do it morning.

File: lib/datasource/github-releases/index.ts [hunk 5]
```diff
@@ -1,14 +1,21 @@
-import URL from 'url';
 import * as packageCache from '../../util/cache/package';
 import { GithubHttp } from '../../util/http/github';
+import { ensureTrailingSlash } from '../../util/url';
 import { GetReleasesConfig, ReleaseResult } from '../common';
 
 export const id = 'github-releases';
+export const defaultRegistryUrls = ['https://github.com'];
```
Comment (volkc) [inline lib/datasource/github-releases/index.ts:7]: Where is this used?

Comment (viceice) [reply lib/datasource/github-releases/index.ts:7]: on line L154 🙃 Is used if extracted urls is empty
https://github.com/renovatebot/renovate/blob/5896d9cb37447151f2e13d0b8570bc1618dfbca4/lib%2Fdatasource%2Findex.ts#L150-L163

Comment (viceice) [reply lib/datasource/github-releases/index.ts:7]: is hidden behind interface
https://github.com/renovatebot/renovate/blob/40ae43817a6713423a9e968296806614740bef01/lib%2Fdatasource%2Fcommon.ts#L73-L81

**Comment by volkc** [comment]
Good morning everyone,

I can confirm, it works! @viceice thank you a lot for your help!

Christian

**Comment by volkc** [comment]
Ok it turned out I was a bit too optimistic. It now works for the internal libraries, but not anymore for external libraries hosted on github. For whatever reasons it tries looking them up in our internal GHE instance.

**Review by rarkins — APPROVED** [review]
