### PR TITLE
fix(git): clone submodules after repo config

### LINKED ISSUE #17911: Renovate won't download submodules
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate doesn't seem to be picking up my projects root Cargo.toml and isn't downloading the submodule that's required. I've tried everything I can think of to get this working...

I have cloneSubmodules set to true in the renovate.json, and it doesn't seem to be doing anything.

renovate.json
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "cloneSubmodules": true
}
```

.gitmodules
```
[submodule "test-repo-a"]
	path = test-repo-a
	url = https://github.com/briancorbin/renovate-test-repo-a.git

```

### Relevant debug logs

<details><summary>Logs</summary>

https://github.com/mobilecoinofficial/full-service/pull/455

```
DEBUG: No dangling containers to remove
INFO: Repository started
{
  "renovateVersion": "32.208.0"
}
DEBUG: Using localDir: /mnt/renovate/gh/briancorbin/renovate-test-repo-b
DEBUG: PackageFiles.clear() - Package files deleted
{
  "baseBranches": []
}
DEBUG: initRepo("briancorbin/renovate-test-repo-b")
DEBUG: Using queue
{
  "concurrency": 10,
  "host": "api.github.com"
}
DEBUG: briancorbin/renovate-test-repo-b default branch = main
DEBUG: Using app token for git init
DEBUG: Resetting npmrc
DEBUG: detectSemanticCommits()
DEBUG: Initializing git repository into /mnt/renovate/gh/briancorbin/renovate-test-repo-b
DEBUG: Performing blobless clone
DEBUG: git clone completed
{
  "durationMs": 880
}
DEBUG: latest repository commit
{
  "latestCommit": {
    "hash": "eb06ad60bfe47dd3424408a69681e92abe3a0de2",
    "date": "2022-09-27T17:34:38-07:00",
    "message": "adding outdated packages",
    "refs": "HEAD -> main, origin/main, origin/HEAD",
    "body": "",
    "author_name": "Brian Corbin",
    "author_email": "brian.william.corbin@gmail.com"
  }
}
DEBUG: getCommitMessages
DEBUG: Semantic commits detection: unknown
DEBUG: No semantic commits detected
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: findFile(renovate.json5)
DEBUG: findFile(.github/renovate.json)
DEBUG: findFile(.github/renovate.json5)
DEBUG: findFile(.gitlab/renovate.json)
DEBUG: findFile(.gitlab/renovate.json5)
DEBUG: findFile(.renovaterc)
DEBUG: findFile(.renovaterc.json)
DEBUG: config file not found
DEBUG: findPr(renovate/configure, Configure Renovate, !open)
DEBUG: getPrList success
{
  "pullsTotal": 3,
  "requestsTotal": 1,
  "apiQuotaAffected": true
}
DEBUG: Found no closed onboarding PR
DEBUG: Repo is not onboarded
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, undefined, open)
DEBUG: Found PR #3
DEBUG: Onboarding PR already exists
DEBUG: Checking if onboarding branch needs rebasing
DEBUG: Last commit author does not match git author email - branch has been modified
{
  "branchName": "renovate/configure",
  "lastAuthor": "brian.william.corbin@gmail.com",
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: Branch cache not present for renovate/configure
DEBUG: Onboarding branch has been edited and cannot be rebased
DEBUG: Checkout onboarding branch.
DEBUG: Setting current branch to renovate/configure
DEBUG: latest commit
{
  "branchName": "renovate/configure",
  "latestCommitDate": "2022-09-27T17:38:18-07:00"
}
DEBUG: Found renovate.json config file
DEBUG: Repository config
{
  "fileName": "renovate.json",
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "config:base"
    ],
    "cloneSubmodules": true
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ],
    "cloneSubmodules": true
  }
}
DEBUG: migrated config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ],
    "cloneSubmodules": true
  }
}
DEBUG: Setting hostRules from config
DEBUG: Found repo ignorePaths
{
  "ignorePaths": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/examples/**",
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**",
    "**/__fixtures__/**"
  ]
}
DEBUG: Using queue
{
  "concurrency": 10,
  "host": "api.github.com"
}
DEBUG: No vulnerability alerts found
DEBUG: No vulnerability alerts found
DEBUG: findIssue(Dependency Dashboard)
DEBUG: Retrieving issueList
DEBUG: Retrieved 0 issues
DEBUG: No baseBranches
DEBUG: extract()
DEBUG: Setting current branch to main
DEBUG: latest commit
{
  "branchName": "main",
  "latestCommitDate": "2022-09-27T17:34:38-07:00"
}
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible
DEBUG: Using file match: (^|/)requirements\.ya?ml$ for manager ansible-galaxy
DEBUG: Using file match: (^|/)galaxy\.ya?ml$ for manager ansible-galaxy
DEBUG: Using file match: (^|/)\.tool-versions$ for manager asdf
DEBUG: Using file match: azure.*pipelines?.*\.ya?ml$ for manager azure-pipelines
DEBUG: Using file match: (^|/)batect(-bundle)?\.yml$ for manager batect
DEBUG: Using file match: (^|/)batect$ for manager batect-wrapper
DEBUG: Using file match: (^|/)WORKSPACE(|\.bazel)$ for manager bazel
DEBUG: Using file match: \.bzl$ for manager bazel
DEBUG: Using file match: (^|\/)\.bazelversion$ for manager bazelisk
DEBUG: Using file match: (^|/)\.?bitbucket-pipelines\.ya?ml$ for manager bitbucket-pipelines
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite
DEBUG: Using file match: (^|/)Gemfile$ for manager bundler
DEBUG: Using file match: \.cake$ for manager cake
DEBUG: Using file match: (^|/)Cargo\.toml$ for manager cargo
DEBUG: Using file match: (^|/)\.circleci/config\.yml$ for manager circleci
DEBUG: Using file match: (^|/)cloudbuild\.ya?ml for manager cloudbuild
DEBUG: Using file match: (^|/)Podfile$ for manager cocoapods
DEBUG: Using file match: (^|/)([\w-]*)composer\.json$ for manager composer
DEBUG: Using file match: (^|/)conanfile\.(txt|py)$ for manager conan
DEBUG: Using file match: (^|/)(?:deps|bb)\.edn$ for manager deps-edn
DEBUG: Using file match: (^|/)(?:docker-)?compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: Using file match: (^|/|\.)Dockerfile$ for manager dockerfile
DEBUG: Using file match: (^|/)Dockerfile[^/]*$ for manager dockerfile
DEBUG: Using file match: (^|/)\.drone\.yml$ for manager droneci
DEBUG: Using file match: (^|/)fleet\.ya?ml for manager fleet
DEBUG: Using file match: (^|/)flux-system/gotk-components\.yaml$ for manager flux
DEBUG: Using file match: (^|\/)\.fvm\/fvm_config\.json$ for manager fvm
DEBUG: Using file match: (^|/)\.gitmodules$ for manager git-submodules
DEBUG: Using file match: ^(workflow-templates|\.github\/workflows)\/[^/]+\.ya?ml$ for manager github-actions
DEBUG: Using file match: (^|\/)action\.ya?ml$ for manager github-actions
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci-include
DEBUG: Using file match: (^|/)go\.mod$ for manager gomod
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle
DEBUG: Using file match: (^|\/)gradle\.properties$ for manager gradle
DEBUG: Using file match: (^|\/)gradle\/.+\.toml$ for manager gradle
DEBUG: Using file match: \.versions\.toml$ for manager gradle
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper\.properties$ for manager gradle-wrapper
DEBUG: Using file match: (^|/)requirements\.yaml$ for manager helm-requirements
DEBUG: Using file match: (^|/)values\.yaml$ for manager helm-values
DEBUG: Using file match: (^|/)helmfile\.yaml$ for manager helmfile
DEBUG: Using file match: (^|/)Chart\.yaml$ for manager helmv3
DEBUG: Using file match: (^|/)bin/hermit$ for manager hermit
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew
DEBUG: Using file match: \.html?$ for manager html
DEBUG: Using file match: (^|/)plugins\.(txt|ya?ml)$ for manager jenkins
DEBUG: Using file match: (^|/)jsonnetfile\.json$ for manager jsonnet-bundler
DEBUG: Using file match: ^.+\.main\.kts$ for manager kotlin-script
DEBUG: Using file match: (^|/)kustomization\.ya?ml$ for manager kustomize
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen
DEBUG: Using file match: (^|/|\.)pom\.xml$ for manager maven
DEBUG: Using file match: ^(((\.mvn)|(\.m2))/)?settings\.xml$ for manager maven
DEBUG: Using file match: (^|/)package\.js$ for manager meteor
DEBUG: Using file match: (^|\/)Mintfile$ for manager mint
DEBUG: Using file match: (^|/)mix\.exs$ for manager mix
DEBUG: Using file match: (^|/)\.node-version$ for manager nodenv
DEBUG: Using file match: (^|/)package\.json$ for manager npm
DEBUG: Using file match: \.(?:cs|fs|vb)proj$ for manager nuget
DEBUG: Using file match: \.(?:props|targets)$ for manager nuget
DEBUG: Using file match: (^|\/)dotnet-tools\.json$ for manager nuget
DEBUG: Using file match: (^|\/)global\.json$ for manager nuget
DEBUG: Using file match: (^|/)\.nvmrc$ for manager nvm
DEBUG: Using file match: (^|/)([\w-]*)requirements\.(txt|pip)$ for manager pip_requirements
DEBUG: Using file match: (^|/)setup\.py$ for manager pip_setup
DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry
DEBUG: Using file match: (^|/)\.pre-commit-config\.yaml$ for manager pre-commit
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub
DEBUG: Using file match: (^|\/)Puppetfile$ for manager puppet
DEBUG: Using file match: (^|/)\.python-version$ for manager pyenv
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version
DEBUG: Using file match: \.sbt$ for manager sbt
DEBUG: Using file match: project/[^/]*.scala$ for manager sbt
DEBUG: Using file match: (^|/)setup\.cfg$ for manager setup-cfg
DEBUG: Using file match: (^|/)Package\.swift for manager swift
DEBUG: Using file match: \.tf$ for manager terraform
DEBUG: Using file match: (^|/)\.terraform-version$ for manager terraform-version
DEBUG: Using file match: (^|/)terragrunt\.hcl$ for manager terragrunt
DEBUG: Using file match: (^|/)\.terragrunt-version$ for manager terragrunt-version
DEBUG: Using file match: ^\.travis\.yml$ for manager travis
DEBUG: Using file match: (^|/)\.vela\.ya?ml$ for manager velaci
DEBUG: Using file match: (^|\/)\.woodpecker[^/]*\.ya?ml$ for manager woodpecker
DEBUG: Matched 2 file(s) for manager cargo: Cargo.toml, test-b/Cargo.toml
DEBUG: git-submodules is disabled
DEBUG: Neither .cargo/config nor .cargo/config.toml found
DEBUG: Neither .cargo/config nor .cargo/config.toml found
DEBUG: Found cargo package files
DEBUG: Found 1 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "main",
  "stats": {
    "managers": {
      "cargo": {
        "fileCount": 1,
        "depCount": 4
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 4
    }
  }
}
DEBUG: PackageFiles.add() - Package file saved for branch
{
  "baseBranch": "main"
}
DEBUG: Package releases lookups complete
{
  "baseBranch": "main"
}
DEBUG: branchifyUpgrades
DEBUG: 2 flattened updates found: dotenv, retry
DEBUG: Returning 2 branch(es)
DEBUG: config.repoIsOnboarded=false
DEBUG: packageFiles with updates
{
  "baseBranch": "main",
  "config": {
    "cargo": [
      {
        "packageFile": "test-b/Cargo.toml",
        "deps": [
          {
            "depName": "member-a",
            "depType": "dependencies",
            "currentValue": "",
            "managerData": {
              "nestedVersion": false
            },
            "datasource": "crate",
            "skipReason": "path-dependency",
            "depIndex": 0,
            "updates": []
          },
          {
            "depName": "member-b",
            "depType": "dependencies",
            "currentValue": "",
            "managerData": {
              "nestedVersion": false
            },
            "datasource": "crate",
            "skipReason": "path-dependency",
            "depIndex": 1,
            "updates": []
          },
          {
            "depName": "dotenv",
            "depType": "dependencies",
            "currentValue": "0.14.0",
            "managerData": {
              "nestedVersion": false
            },
            "datasource": "crate",
            "depIndex": 2,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "0.15.0",
                "newValue": "0.15.0",
                "newMajor": 0,
                "newMinor": 15,
                "updateType": "minor",
                "branchName": "renovate/dotenv-0.x"
              }
            ],
            "warnings": [],
            "versioning": "cargo",
            "sourceUrl": "https://github.com/dotenv-rs/dotenv",
            "dependencyUrl": "https://crates.io/crates/dotenv",
            "currentVersion": "0.14.0",
            "isSingleVersion": false
          },
          {
            "depName": "retry",
            "depType": "dependencies",
            "currentValue": "1.3",
            "managerData": {
              "nestedVersion": false
            },
            "datasource": "crate",
            "depIndex": 3,
            "updates": [
              {
                "bucket": "major",
                "newVersion": "2.0.0",
                "newValue": "2.0",
                "newMajor": 2,
                "newMinor": 0,
                "updateType": "major",
                "isRange": true,
                "branchName": "renovate/retry-2.x"
              }
            ],
            "warnings": [],
            "versioning": "cargo",
            "sourceUrl": "https://github.com/jimmycuadra/retry",
            "dependencyUrl": "https://crates.io/crates/retry",
            "currentVersion": "1.3.0",
            "isSingleVersion": false
          }
        ],
        "lockFiles": [
          "Cargo.lock"
        ]
      }
    ]
  }
}
DEBUG: ensureOnboardingPr()
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, undefined, open)
DEBUG: Found PR #3
DEBUG: Filling in onboarding PR template
DEBUG: isBranchConflicted(main, renovate/configure)
DEBUG: Setting git author name
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: getPrList()
DEBUG: Found open onboarding PR
DEBUG: updatePr(3, Configure Renovate, body)
DEBUG: PR updated
{
  "pr": 3
}
INFO: Onboarding PR updated
{
  "pr": 3
}
DEBUG: processRepo()
DEBUG: Repo is onboarding - skipping dependency dashboard
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=false
DEBUG: Branch lists
{
  "branchList": [
    "renovate/configure"
  ],
  "renovateBranches": [
    "renovate/configure"
  ]
}
DEBUG: remainingBranches=
DEBUG: No branches to clean up
DEBUG: PackageFiles.clear() - Package files deleted
{
  "baseBranches": [
    "main"
  ]
}
DEBUG: Renovate repository PR statistics
{
  "stats": {
    "total": 2,
    "open": 0,
    "closed": 2,
    "merged": 0
  }
}
DEBUG: Repository result: undefined, status: onboarding, enabled: true, onboarded: false
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {
    "init": 4628,
    "extract": 1066,
    "lookup": 226,
    "onboarding": 1194,
    "update": 0
  },
  "total": 7159
}
DEBUG: http statistics
{
  "urls": {
    "https://api.github.com/graphql (POST,200)": 2,
    "https://api.github.com/repos/briancorbin/renovate-test-repo-b/pulls (GET,200)": 1,
    "https://api.github.com/repos/briancorbin/renovate-test-repo-b/pulls/3 (PATCH,200)": 1,
    "https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json (GET,200)": 1
  },
  "hostStats": {
    "api.github.com": {
      "requestCount": 5,
      "requestAvgMs": 292,
      "queueAvgMs": 0
    }
  },
  "totalRequests": 5
}
DEBUG: dns cache
{
  "hosts": [
    "api.github.com"
  ]
}
INFO: Repository finished
{
  "durationMs": 7159
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Ensures submodules sync is tried again after reading repo config

## Context

Closes #17911

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/git/index.ts [hunk 1]
```diff
@@ -415,20 +437,8 @@ export async function syncGit(): Promise<void> {
...
-      } catch (err) {
-        logger.warn(
-          { err },
-          `Unable to initialise git submodule at ${submodule}`
-        );
-      }
-    }
-  }
+  // This will only happen now if set in global config
+  await cloneSubmodules(!!config.cloneSubmodules);
```
Comment (rarkins) [inline lib/util/git/index.ts:441]: I think this could possibly be removed, but it's kept for backwards compatibility. The only use I can think of is if someone somehow has a symbolic link for their config file, pointing to a file within a submodule.

File: lib/workers/repository/init/index.ts [hunk 2]
```diff
@@ -48,5 +48,6 @@ export async function initRepo(
       'Full resolved config and hostRules including presets'
     );
   }
+  await cloneSubmodules(!!config.cloneSubmodules);
```
Comment (rarkins) [inline lib/workers/repository/init/index.ts:51]: This means that repos with cloneSubmodules will have 100% git cloning (even if no work needs to be done), but we can live with that edge case.

**Review by viceice — APPROVED** [review]

**Review by sleepynano — APPROVED** [review]
