### PR TITLE
fix(helmv3): set helm repositories from aliases to update Chart.lock

### LINKED ISSUE #8542: Helm repo @stable not found, "helm repo add" required (but unable to)
**What Renovate type, platform and version are you using?**

Hosted GitHub app.

**Describe the bug**

Renovate commented on my PR with the following failure:

Skärmavbild 2021-02-04 kl  13 51 53

Here's the entire error message:

`Command failed: docker run --rm --name=renovate_helm --label=renovate_child -v "/mnt/renovate/gh/myorg/myrepo":"/mnt/renovate/gh/myorg/cluster-monitoring" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -w "/mnt/renovate/gh/myorg/cluster-monitoring" docker.io/renovate/helm bash -l -c "helm dependency update cluster-monitoring"
Error: no repository definition for @stable, @stable, @stable. Please add them via 'helm repo add'`

Here's the `Chart.yaml` file it fails on:

```yaml
apiVersion: v2
appVersion: "1.0"
description: Cluster-wide monitoring
name: cluster-monitoring
version: 0.1.0
home: https://github.com/helm/charts/tree/master/stable/prometheus-operator
dependencies:
  - name: prometheus-operator
    version: 8.16.1
    repository: "@stable"
  - name: nginx-ingress
    version: 1.36.3
    repository: "@stable"
    condition: nginxIngressEnabled
  - name: prometheus-adapter
    version: 2.0.1
    repository: "@stable"
```

Here is my `renovate.json` config for this repo:

```json
{
  "extends": [
    "config:base"
  ],
  "aliases": {
    "stable": "https://charts.helm.sh/stable",
    "hashicorp": "https://helm.releases.hashicorp.com",
    "jetstack": "https://charts.jetstack.io"
  },
  "helmv3": {
    "lockFileMaintenance": { "enabled": true }
  }
}
```

**Relevant debug logs**

I have found the Renovate job matching this PR, but I don't see anything relevant to this error in those Renovate App logs.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

### PR DESCRIPTION
**Pull request by jgarec**
## Changes:

Execute `helm repo add <alias> <url>` for all aliases.
Required for helm to update Chart.lock files

## Context:

Closes #8542

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository (https://gitlab.com/jgarec/renovate-helmv3/-/merge_requests)

### CODE REVIEW

File: lib/manager/helmv3/artifacts.ts [hunk 1]
```diff
@@ -10,6 +10,20 @@ import {
 } from '../../util/fs';
 import type { UpdateArtifact, UpdateArtifactsResult } from '../types';
 
+async function helmRepoAdd(alias: string, url: string): Promise<void> {
+  const cmd = `helm repo add ${alias} ${url}`;
```
Comment (rarkins) [inline lib/manager/helmv3/artifacts.ts:14]: Please use `quote()` from package `shlex` to wrap these if there's the possibility that they contain spaces or special characters

File: lib/manager/helmv3/artifacts.ts [hunk 2]
```diff
@@ -10,6 +10,20 @@ import {
...
+
+  const execOptions: ExecOptions = {
+    docker: {
+      image: 'helm',
+    },
+    extraEnv: {
+      HELM_EXPERIMENTAL_OCI: '1',
+    },
+  };
+  await exec(cmd, execOptions);
```
Comment (rarkins) [inline lib/manager/helmv3/artifacts.ts:24]: These commands should instead be added to the existing `cmd` (using an array instead of string) so that they are executed sequentially within the same container.

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/manager/helmv3/artifacts.ts [hunk 3]
```diff
@@ -21,6 +22,15 @@ async function helmUpdate(manifestPath: string): Promise<void> {
       HELM_EXPERIMENTAL_OCI: '1',
     },
   };
+  const cmd = [
+    `helm dependency update ${quote(getSubDirectory(manifestPath))}`,
+  ];
+
+  if (aliases) {
+    Object.entries(aliases).forEach(([alias, url]) =>
+      cmd.push(`helm repo add ${quote(alias)} ${quote(url)}`)
```
Comment (rarkins) [inline lib/manager/helmv3/artifacts.ts:31]: Don't you need these added before the `helm dependency update` command is run? Your snapshot now is `helm dependency update '' && helm repo add stable the_stable_url && helm repo add repo1 the_repo1_url`

Comment (jgarec) [reply lib/manager/helmv3/artifacts.ts:31]: you're right... it's almost the purpose of this PR ...

**Review by rarkins — APPROVED** [review]

**Comment by rarkins** [comment]
Thanks for the PR!
