### PR TITLE
fix(bazel): pass registry for container_pull

### LINKED ISSUE #6412: container_pull loses registry information
**What Renovate type are you using?**

GitHub App

**Describe the bug**

When renovate evaluates `container_pull` Docker dependencies in a Bazel `WORKSPACE` file, it fails to extract the registry. In the renovate logs, I see a def like this:

```
{
  "def": "container_pull(\n    name = \"py3_image_base\",\n    digest = \"sha256:d5a717649fd93ea5b9c430d7f84e4c37ba219eb53bd73ed1d4a5a98e9edd84a7\",\n    registry = \"gcr.io\",\n    repository = \"distroless/python3-debian10\",\n    tag = \"latest\",\n)"
}
```

But then:

```
DEBUG: Unauthorized docker lookup
{
  "registry": "https://index.docker.io",
  "dockerRepository": "distroless/python3-debian10"
}
```

The lookup fails because renovate is using the wrong registry (docker.io), even though the right one (gcr.io) is specified in the `def`. And it's using the wrong one because the `registry` value gets dropped here:

https://github.com/renovatebot/renovate/blob/6c798e5fcdfd7958a1fe2e7a519e9dbd222e96af/lib/manager/bazel/extract.ts#L235-L247

**Did you see anything helpful in debug logs?**

See eg job ID 184347310.

**To Reproduce**

See above for a `container_pull` that reproduces the problem.

**Additional context**

Thank you!

### PR DESCRIPTION
**Pull request by viceice**
Simply pass extracted `registry` to `dep.registryUrls`

Closes #6412

### CODE REVIEW

File: lib/manager/bazel/extract.ts [hunk 1]
```diff
@@ -244,6 +244,7 @@ export function extractPackageFile(content: string): PackageFile | null {
       dep.versioning = dockerVersioning.id;
       dep.datasource = datasourceDocker.id;
       dep.lookupName = repository;
+      dep.registryUrls = [registry];
```
Comment (rarkins) [inline lib/manager/bazel/extract.ts:247]: Is it a mandatory field?

Comment (rarkins) [reply lib/manager/bazel/extract.ts:247]: Wondering if it should be `if(registry) dep.registryUrls = registry`

Comment (viceice) [reply lib/manager/bazel/extract.ts:247]: yes, it's mandatory, see condition above.
