### PR TITLE
fix(versioning/hashicorp): check valid before matches

### LINKED ISSUE #19739: "invalid hashicorp constraint" for Terraform provider upgrades
### Discussed in https://github.com/renovatebot/renovate/discussions/19735

<div type='discussions-op-text'>

<sup>Originally posted by **lauraseidler** January  9, 2023</sup>
When running on a repository with Terraform code with a variety of providers, we're seeing an "invalid hashicorp constraint" error - that's all the information I have, unfortunately. There's a couple of providers installed in this repository, but I have no clue which one is the problematic one. 

<details><summary>Logs</summary>

```
    Error: invalid hashicorp constraint
        at /usr/src/app/node_modules/renovate/lib/modules/versioning/hashicorp/convertor.ts:19:15
        at Array.map (<anonymous>)
        at hashicorp2npm (/usr/src/app/node_modules/renovate/lib/modules/versioning/hashicorp/convertor.ts:14:6)
        at Object.matches (/usr/src/app/node_modules/renovate/lib/modules/versioning/hashicorp/index.ts:35:44)
        at CurrentVersionMatcher.matches (/usr/src/app/node_modules/renovate/lib/util/package-rules/current-version.ts:57:22)
        at matcherOR (/usr/src/app/node_modules/renovate/lib/util/package-rules/utils.ts:20:27)
        at matchesRule (/usr/src/app/node_modules/renovate/lib/util/package-rules/index.ts:17:30)
        at applyPackageRules (/usr/src/app/node_modules/renovate/lib/util/package-rules/index.ts:79:9)
        at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:46:32)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at /usr/src/app/node_modules/p-map/index.js:57:22
 ```

</details>

I believe this was introduced by https://github.com/renovatebot/renovate/pull/19652 - maybe there's a way to at least add some more info to where this error is thrown, so that the offending provider/version can be identified?
 </div>

### PR DESCRIPTION
**Pull request by rarkins**
## Context

Closes #19739

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]

File: lib/modules/versioning/hashicorp/index.ts [hunk 1]
```diff
@@ -25,14 +26,15 @@ export function isValid(input: string): boolean {
...
+      logger.debug({ value: input }, 'Unsupported hashicorp versioning value');
       return false;
     }
   }
   return false;
 }
 
 function matches(version: string, range: string): boolean {
-  return npm.matches(version, hashicorp2npm(range));
+  return isValid(range) && npm.matches(version, hashicorp2npm(range));
```
Comment (viceice) [inline lib/modules/versioning/hashicorp/index.ts:37]: are we doing this at other versionings too? 🤔

Comment (rarkins) [reply lib/modules/versioning/hashicorp/index.ts:37]: we don't seem to have the same problem with others, maybe because they don't throw

Comment (mcfedr) [reply lib/modules/versioning/hashicorp/index.ts:37]: I nearly added this here, but thought, its probably called before `matches` is called, as none of the other versioning do this
