### PR TITLE
fix: perform pr-update when requested regardless of pr-cache state

### LINKED ISSUE #21144: PR rebase checkbox is not reset if cache in use and PR was unchanged for 24 hours prior
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

If PR cache is in use, and PR hasn't changed in >24 hours, and you check the rebase checkbox, then the checkbox won't be unchecked after the run.

Example from https://github.com/renovatebot/renovate/pull/21116

It would take 24hrs+ to reproduce this

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found existing PR(branch="renovate/yarn-monorepo")
DEBUG: PR cache matches and no PR changes in last 24hrs, so skipping PR body check(branch="renovate/yarn-monorepo")```

</details>


### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- also changed the returned value when pr is udpated as we were returning the outdated data

## Context
- Closes: https://github.com/renovatebot/renovate/issues/21144

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

File: lib/workers/repository/update/pr/index.ts [hunk 1]
```diff
@@ -364,7 +369,14 @@ export async function ensurePr(
         logger.info({ pr: existingPr.number, prTitle }, `PR updated`);
         setPrCache(branchName, prFingerprint, true);
       }
-      return { type: 'with-pr', pr: existingPr };
+      return {
+        type: 'with-pr',
+        pr: {
+          ...existingPr,
+          bodyStruct: getPrBodyStruct(prBody),
+          title: prTitle,
```
Comment (rarkins) [inline lib/workers/repository/update/pr/index.ts:377]: are you sure you want to do these even if dryRun?

**Review by hleannhot — DISMISSED** [review]

File: lib/workers/repository/update/pr/index.ts (hunk 1 above)
Comment (RahulGautamSingh) [reply lib/workers/repository/update/pr/index.ts:377]: Shouldn't matter I think

We don't use the returned info except `pr.number`
And the `prBody` & `prTitle` are generated anyways so better use correct the data

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
