### PR TITLE
fix: force commit if requested or conflicted

### LINKED ISSUE #6264: Rebase failed to update branch, skipped due to no file changed
**What Renovate type are you using?**

GitHub marketplace app. 

**Describe the bug**

GitHub thinks the PR is conflicted, but Renovate does not force push a change after checking the rebase checkbox. Renovate simply uncheck the checkbox and leave the PR conflicted. 

Closing the PR and let Renovate create a new one resolved the conflict. 

The PR: https://github.com/NanoMeow/MirrorEngine/pull/76

**Did you see anything helpful in debug logs?**

```
DEBUG: Manual rebase requested via PR checkbox for #76
[...]
DEBUG: No file changes detected. Skipping commit
```

**To Reproduce**

I'm not too sure how to easily reproduce this issue, but this is what I think is happening: 

- Renovate creates 2 PRs to update `fs-extra` (as instructed by the `:separateMultipleMajorReleases` config): 
  - From `8.1.0` to `8.1.1`: https://github.com/NanoMeow/MirrorEngine/pull/75
  - From `8.1.1` to `9.0.0`: https://github.com/NanoMeow/MirrorEngine/pull/76
- The first PR is automerged via squash merge
- GitHub thinks the second PR is conflicted, but Renovate failed to rebase it

**Additional context**

I think squash merge might have something to do with this. Maybe have Renovate to force an update when requested manually even if no file has changed?

### PR DESCRIPTION
**Pull request by rarkins**
Closes #6264

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

File: lib/workers/branch/index.ts [hunk 1]
```diff
@@ -441,7 +441,8 @@ export async function processBranch(
         logger.debug('PR has no releaseTimestamp');
       }
     }
-
+    config.forceCommit =
+      masterIssueCheck || config.rebaseRequested || branchPr.isConflicted;
```
Comment (viceice) [inline lib/workers/branch/index.ts:445]: haha, one of the types is `unknown`

**Review by viceice — APPROVED** [review]
