### PR TITLE
fix(logging): Added check for log level value

### LINKED ISSUE #9526: renovate fails to run due to fatal error in bunyan setup
**What Renovate type, platform and version are you using?**
Running version 24.114.1-slim "self-hosted" on a Gitlab.com runner using job configuration from https://gitlab.com/renovate-bot/renovate-runner 

**Describe the bug**

Renovate fails to run as the logging framework (bunyan) throws a fatal error upon start. Even with LOG_LEVEL="debug" nothing but the bunyan error is logged.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Running with gitlab-runner 13.10.0-rc1 (ecc4c590)
  on gitlab-org-docker D4kd9MvC
  feature flags: FF_GITLAB_REGISTRY_HELPER_IMAGE:true
Resolving secrets 00:00
Preparing the "docker+machine" executor 00:24
Using Docker executor with image renovate/renovate:24.114.1-slim@sha256:b5cbb6fb0c1df577b10c46d0312fb5266e1c2bd8df25e91e354b6b8d0483cf71 ...
Starting service docker:20.10.6-dind ...
Pulling docker image docker:20.10.6-dind@sha256:2636ec38c4567671b24f35683a66d1204bbeed208873a2a11c64dd592742b97a ...
Using docker image sha256:c9b83b687d756362c574f75cfba587172af6cbcdd4d009ecb6d891da9522298c for docker:20.10.6-dind@sha256:2636ec38c4567671b24f35683a66d1204bbeed208873a2a11c64dd592742b97a with digest docker@sha256:2636ec38c4567671b24f35683a66d1204bbeed208873a2a11c64dd592742b97a ...
Waiting for services to be up and running...
Pulling docker image renovate/renovate:24.114.1-slim@sha256:b5cbb6fb0c1df577b10c46d0312fb5266e1c2bd8df25e91e354b6b8d0483cf71 ...
Using docker image sha256:f6496b5d70ff0ca585fbf2358d387e71c287f35be804398b5aa17c0a0e5aa72a for renovate/renovate:24.114.1-slim@sha256:b5cbb6fb0c1df577b10c46d0312fb5266e1c2bd8df25e91e354b6b8d0483cf71 with digest renovate/renovate@sha256:b5cbb6fb0c1df577b10c46d0312fb5266e1c2bd8df25e91e354b6b8d0483cf71 ...
Preparing environment 00:02
Running on runner-d4kd9mvc-project-9680743-concurrent-0 via runner-d4kd9mvc-org-ci-1618304718-18081f50...
Getting source from Git repository 00:01
$ eval "$CI_PRE_CLONE_SCRIPT"
Fetching changes...
Initialized empty Git repository in /builds/openstapps/projectmanagement/.git/
Created fresh repository.
Checking out c92bba1e as master...
Skipping Git submodules setup
Restoring cache 00:01
Checking cache for master-renovate-5...
FATAL: file does not exist                         
Failed to extract cache
Downloading artifacts 00:01
Downloading artifacts for npm build (1175350605)...
Executing "step_script" stage of the job script 00:00
Using docker image sha256:f6496b5d70ff0ca585fbf2358d387e71c287f35be804398b5aa17c0a0e5aa72a for renovate/renovate:24.114.1-slim@sha256:b5cbb6fb0c1df577b10c46d0312fb5266e1c2bd8df25e91e354b6b8d0483cf71 with digest renovate/renovate@sha256:b5cbb6fb0c1df577b10c46d0312fb5266e1c2bd8df25e91e354b6b8d0483cf71 ...
$ renovate $RENOVATE_EXTRA_FLAGS
/usr/src/app/node_modules/bunyan/lib/bunyan.js:293
            throw new Error(format('unknown level name: "%s"', nameOrNum));
                  ^
Error: unknown level name: "warning"
    at resolveLevel (/usr/src/app/node_modules/bunyan/lib/bunyan.js:293:19)
    at Logger.addStream (/usr/src/app/node_modules/bunyan/lib/bunyan.js:570:19)
    at /usr/src/app/node_modules/bunyan/lib/bunyan.js:470:18
    at Array.forEach (<anonymous>)
    at new Logger (/usr/src/app/node_modules/bunyan/lib/bunyan.js:469:25)
    at Object.createLogger (/usr/src/app/node_modules/bunyan/lib/bunyan.js:1620:12)
    at Object.<anonymous> (/usr/src/app/node_modules/renovate/lib/logger/index.ts:39:29)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/src/app/src/renovate.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Uploading artifacts for failed job 00:00
Uploading artifacts...
WARNING: renovate-log.ndjson: no matching files    
ERROR: No files to upload                          
Cleaning up file based variables 00:01
ERROR: Job failed: exit code 1
```

</details>

GitLab Project:
https://gitlab.com/openstapps/projectmanagement/

- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**
For GitLab pipeline job config see https://gitlab.com/openstapps/projectmanagement/-/blob/master/.gitlab-ci.yml#L133
Additional changes made via $RENOVATE_EXTRA_FLAGS only define on which projects the renovate task should be executed.

### PR DESCRIPTION
**Pull request by hasanwhitesource**
## Changes:

Renovate will now check if the log level from the config is a valid bunyan logLevel value and will log error and then stops running.

## Context:

- Closes #9526

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/config/validation.ts [hunk 1]
```diff
@@ -570,3 +571,41 @@ export async function validateConfig(
   warnings.sort(sortAll);
   return { errors, warnings };
 }
+
+export function isValidLogLevel(
```
Comment (viceice) [inline lib/config/validation.ts:575]: Move this to `lib/logger/utils.ts` otherwise we get circular dependencies.

**Review by viceice — DISMISSED** [review]

File: lib/config/validation.ts (hunk 1 above)
Comment (hasanwhitesource) [reply lib/config/validation.ts:575]: Where do you recommend the test to be put in `lib/logger/index.spec.ts` ?

Comment (viceice) [reply lib/config/validation.ts:575]: yes

File: lib/logger/index.ts [hunk 2]
```diff
@@ -6,13 +6,17 @@ import configSerializer from './config-serializer';
...
 import type { BunyanRecord, Logger } from './types';
-import { ProblemStream, withSanitizer } from './utils';
+import { ProblemStream, isValidLogLevel, withSanitizer } from './utils';
 
 let logContext: string = process.env.LOG_CONTEXT ?? nanoid();
 let curMeta: Record<string, unknown> = {};
 
 const problems = new ProblemStream();
 
+process.env.LOG_LEVEL.toLocaleLowerCase();
```
Comment (rarkins) [inline lib/logger/index.ts:16]: This line achieves nothing as it is. It returns a lower-cased value, but you're not saving it into any variable, so it is lost.

Comment (rarkins) [reply lib/logger/index.ts:16]: Also, can't it be undefined?

File: lib/logger/index.ts [hunk 3]
```diff
@@ -6,13 +6,17 @@ import configSerializer from './config-serializer';
...
+if (!isValidLogLevel(process.env.LOG_LEVEL as bunyan.LogLevel)) {
```
Comment (rarkins) [inline lib/logger/index.ts:17]:
```suggestion
if (!isValidLogLevel(process.env.LOG_LEVEL as bunyan.LogLevel)) {
```

This is not a good idea. `as` is like casting. The whole reason for calling this code is to see if it's a valid log level. But by saying `as bunyan.LogLevel` you are telling the typescript compiler "don't bother checking this, I know it's a valid log level".

File: lib/logger/index.ts [hunk 4]
```diff
@@ -6,13 +6,17 @@ import configSerializer from './config-serializer';
...
+  process.exit(1);
```
Comment (rarkins) [inline lib/logger/index.ts:18]: We need to fatally log before exiting instead of exiting silently like this. I suggest that you should create the logger (skipping LOG_LEVEL) and then log a fatal error and exit after that.

File: lib/logger/utils.ts [hunk 5]
```diff
@@ -206,3 +206,41 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
 
   throw new Error("Missing 'stream' or 'path' for bunyan stream");
 }
+
+export function isValidLogLevel(
+  logLevelToCheck: bunyan.LogLevel
```
Comment (rarkins) [inline lib/logger/utils.ts:211]:
```suggestion
  logLevelToCheck: string
```

File: lib/logger/utils.ts [hunk 6]
```diff
@@ -206,3 +206,41 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+    'info',
+    'warn',
+    'error',
+    'fatal',
+    bunyan.TRACE,
+    bunyan.DEBUG,
+    bunyan.INFO,
+    bunyan.WARN,
+    bunyan.ERROR,
+    bunyan.FATAL,
```
Comment (rarkins) [inline lib/logger/utils.ts:225]: Aren't these duplicated?

File: lib/logger/utils.ts [hunk 7]
```diff
@@ -206,3 +206,41 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+  ];
+  const result: boolean =
+    allowedValues.indexOf(logLevelToCheck) !== -1 ||
+    (typeof logLevelToCheck === 'string' &&
+      logLevelToCheck.trim().length === 0);
```
Comment (rarkins) [inline lib/logger/utils.ts:230]: I don't think these lines are necessary

File: lib/logger/utils.ts [hunk 8]
```diff
@@ -206,3 +206,41 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+
+  if (!result) {
+    const Logger = bunyan.createLogger({
+      name: 'log level error log',
```
Comment (rarkins) [inline lib/logger/utils.ts:234]: This should instead be the same name as Renovate has, in case the user is filtering by log stream name

File: lib/logger/utils.ts [hunk 9]
```diff
@@ -206,3 +206,41 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+    bunyan.ERROR,
+    bunyan.FATAL,
+  ];
+  const result: boolean =
+    allowedValues.indexOf(logLevelToCheck) !== -1 ||
+    (typeof logLevelToCheck === 'string' &&
+      logLevelToCheck.trim().length === 0);
+
+  if (!result) {
+    const Logger = bunyan.createLogger({
```
Comment (rarkins) [inline lib/logger/utils.ts:233]:
```suggestion
    const logger = bunyan.createLogger({
```

No upper case variable names

File: lib/logger/utils.ts [hunk 10]
```diff
@@ -206,3 +206,41 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+        {
+          level: 'fatal',
+          stream: process.stdout,
+        },
+      ],
+    });
+    Logger.fatal(`${logLevelToCheck} is not a valid log level. terminating...`);
+  }
+
+  return result;
```
Comment (rarkins) [inline lib/logger/utils.ts:245]: I think just process.exit(1) here instead

**Review by rarkins — CHANGES_REQUESTED** [review]
Call `validateLogLevel()` from the main code, and let that function log and exit if the value is invalid. Otherwise continue

File: lib/config/migration.spec.ts [hunk 11]
```diff
@@ -1,3 +1,4 @@
+import { expect } from '@jest/globals';
```
Comment (viceice) [inline lib/config/migration.spec.ts:1]: ??

File: lib/logger/index.spec.ts [hunk 12]
```diff
@@ -182,4 +184,15 @@ describe('logger/index', () => {
     expect(logged.someFn).toBe('[function]');
     expect(logged.someObject.field).toBe('**redacted**');
   });
+
+  it('checks for valid log level', () => {
+    expect(isValidLogLevel('warning' as bunyan.LogLevel)).toBeFalsy();
+    expect(isValidLogLevel('warn' as bunyan.LogLevel)).toBeTruthy();
+    expect(isValidLogLevel('trace' as bunyan.LogLevel)).toBeTruthy();
+    expect(isValidLogLevel(' ' as bunyan.LogLevel)).toBeTruthy();
+    expect(isValidLogLevel('' as bunyan.LogLevel)).toBeTruthy();
```
Comment (viceice) [inline lib/logger/index.spec.ts:193]:
```suggestion
    expect(isValidLogLevel(undefined)).toBeTruthy();
```

File: lib/logger/index.ts (hunk 2 above)
Comment (viceice) [reply lib/logger/index.ts:16]:
```suggestion
```

File: lib/logger/index.ts (hunk 3 above)
Comment (viceice) [reply lib/logger/index.ts:17]:
```suggestion
if (!isValidLogLevel(process.env.LOG_LEVEL)) {
```

File: lib/logger/utils.ts (hunk 5 above)
Comment (viceice) [reply lib/logger/utils.ts:211]:
```suggestion
  logLevelToCheck: string | undefined | bunyan.LogLevel
```

File: lib/logger/utils.ts [hunk 13]
```diff
@@ -206,3 +206,45 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+    bunyan.ERROR,
+    bunyan.FATAL,
+  ];
+  if (
+    typeof logLevelToCheck === 'string' &&
+    logLevelToCheck.trim().length === 0
+  ) {
+    // if the log level is empty string then return true
+    return true;
+  }
```
Comment (viceice) [inline lib/logger/utils.ts:233]:
```suggestion
  if (
    !logLevelToCheck ||
    (typeof logLevelToCheck === 'string' &&
    logLevelToCheck.trim().length === 0)
  ) {
    // if the log level is empty string then return true
    return true;
  }
```

allow undefined

File: tsconfig.json [hunk 14]
```diff
@@ -22,7 +22,6 @@
     "checkJs": true
   },
   "exclude": [
-    "node_modules",
```
Comment (viceice) [inline tsconfig.json:25]: revert

File: tsconfig.spec.json [hunk 15]
```diff
@@ -1,7 +1,8 @@
 {
   "extends": "./tsconfig",
   "compilerOptions": {
-    "allowJs": false,
-    "checkJs": false
+    "allowJs": true,
+    "checkJs": true,
+    "types": ["node", "jest", "jest-extended", "expect-more-jest"]
```
Comment (viceice) [inline tsconfig.spec.json:6]: revert

Comment (hasanwhitesource) [reply tsconfig.spec.json:6]: Yes by mistake. Will order things now

File: lib/logger/utils.ts (hunk 6 above)
Comment (hasanwhitesource) [reply lib/logger/utils.ts:225]: I added these to check if the user has inserted a number instead of a string.
For example `bunyan.TRACE = 10`

**Comment by hasanwhitesource** [comment]
@rarkins @viceice I will create a new branch with clean changes.

**Comment by rarkins** [comment]
@hasanwhitesource in future it's preferred that you keep the same PR, so that you create less noise for everyone else. Now, every comment made before will be lost and not transferred to your new PR.

File: lib/logger/utils.ts (hunk 13 above)
Comment (hasanwhitesource) [reply lib/logger/utils.ts]: I've added the case

File: tsconfig.spec.json (hunk 15 above)
Comment (hasanwhitesource) [reply tsconfig.spec.json]: reverted

File: tsconfig.json (hunk 14 above)
Comment (hasanwhitesource) [reply tsconfig.json]: reverted

File: lib/config/migration.spec.ts (hunk 11 above)
Comment (hasanwhitesource) [reply lib/config/migration.spec.ts]: Reverted

File: lib/logger/utils.ts (hunk 10 above)
Comment (hasanwhitesource) [reply lib/logger/utils.ts]: Made the process exit in the function and added a log before it

File: lib/logger/utils.ts (hunk 9 above)
Comment (hasanwhitesource) [reply lib/logger/utils.ts]: Changed it

File: lib/logger/index.ts (hunk 2 above)
Comment (hasanwhitesource) [reply lib/logger/index.ts]: Wont worry about converting to lower case

File: lib/logger/index.ts (hunk 3 above)
Comment (hasanwhitesource) [reply lib/logger/index.ts]: Fixed

File: lib/logger/utils.ts (hunk 7 above)
Comment (hasanwhitesource) [reply lib/logger/utils.ts]: Just worrying about the case when it empty. I can remove from test if not needed.

File: tsconfig.spec.json (hunk 15 above)
Comment (viceice) [reply tsconfig.spec.json]: https://github.com/renovatebot/renovate/blob/main/.github/contributing.md#resolve-review-comments-instead-of-commenting 🤗

File: lib/logger/index.spec.ts [hunk 16]
```diff
@@ -182,4 +184,37 @@ describe('logger/index', () => {
...
+    expect(validateLogLevel('debug')).toBeTruthy();
+    expect(validateLogLevel('trace')).toBeTruthy();
+    expect(validateLogLevel('info' as bunyan.LogLevel)).toBeTruthy();
+    expect(validateLogLevel(10)).toBeTruthy();
+    // Mock when the function exits
+    const mockExit = jest
+      .spyOn(process, 'exit')
+      .mockImplementation((number) => {
+        throw new Error('process.exit: ' + number);
+      });
```
Comment (viceice) [inline lib/logger/index.spec.ts:202]:
```suggestion
    const mockExit = jest.spyOn(process, 'exit');
    mockExit.mockImplementationOnce((number) => {
        throw new Error(`process.exit: ${number}`);
      });
```

File: lib/logger/index.spec.ts [hunk 17]
```diff
@@ -182,4 +184,37 @@ describe('logger/index', () => {
...
+    expect(() => {
+      validateLogLevel('warning');
+    }).toThrow();
+    expect(mockExit).toHaveBeenCalledWith(1);
+    mockExit.mockRestore();
```
Comment (viceice) [inline lib/logger/index.spec.ts:207]:
```suggestion
    mockExit.mockClear();
```

File: lib/logger/index.spec.ts [hunk 18]
```diff
@@ -182,4 +184,37 @@ describe('logger/index', () => {
...
+    const mockExit2 = jest
+      .spyOn(process, 'exit')
+      .mockImplementation((number) => {
+        throw new Error('process.exit: ' + number);
+      });
+    expect(() => {
+      validateLogLevel('100');
+    }).toThrow();
+    expect(mockExit2).toHaveBeenCalledWith(1);
+    mockExit2.mockRestore();
```
Comment (viceice) [inline lib/logger/index.spec.ts:218]:
```suggestion
```

File: lib/logger/index.spec.ts [hunk 19]
```diff
@@ -182,4 +184,37 @@ describe('logger/index', () => {
...
+
+    const mockExit2 = jest
+      .spyOn(process, 'exit')
+      .mockImplementation((number) => {
+        throw new Error('process.exit: ' + number);
+      });
+    expect(() => {
+      validateLogLevel('100');
+    }).toThrow();
+    expect(mockExit2).toHaveBeenCalledWith(1);
```
Comment (viceice) [inline lib/logger/index.spec.ts:217]:
```suggestion
    expect(mockExit).toHaveBeenCalledWith(1);
```

File: lib/logger/index.spec.ts [hunk 20]
```diff
@@ -182,4 +184,37 @@ describe('logger/index', () => {
...
+      validateLogLevel('warning');
+    }).toThrow();
+    expect(mockExit).toHaveBeenCalledWith(1);
+    mockExit.mockRestore();
+
+    const mockExit2 = jest
+      .spyOn(process, 'exit')
+      .mockImplementation((number) => {
+        throw new Error('process.exit: ' + number);
+      });
```
Comment (viceice) [inline lib/logger/index.spec.ts:213]:
```suggestion
    mockExit.mockImplementationOnce((number) => {
        throw new Error(`process.exit: ${number}`);
      });
```

File: lib/logger/index.spec.ts [hunk 21]
```diff
@@ -182,4 +184,37 @@ describe('logger/index', () => {
     expect(logged.someFn).toBe('[function]');
     expect(logged.someObject.field).toBe('**redacted**');
   });
+
+  it('checks for valid log level', () => {
```
[the remark this answers is not in the document]
Comment (hasanwhitesource) [reply lib/logger/index.spec.ts:188]: Is it sufficient if I do restoreAllMocks at the end of my test and doing mockClear for each expect ?

[the remark this answers is not in the document]
Comment (viceice) [reply lib/logger/index.spec.ts:188]: No, when the test fails before, the restore is never called and other tests will fail too

File: lib/logger/utils.ts [hunk 22]
```diff
@@ -206,3 +206,49 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+    bunyan.INFO,
+    bunyan.WARN,
+    bunyan.ERROR,
+    bunyan.FATAL,
+  ];
+  if (
+    !logLevelToCheck ||
+    (typeof logLevelToCheck === 'string' &&
+      logLevelToCheck.trim().length === 0) ||
+    allowedValues.indexOf(logLevelToCheck as bunyan.LogLevel) !== -1
```
Comment (viceice) [inline lib/logger/utils.ts:237]:
```suggestion
    !allowedValues.includes(logLevelToCheck as bunyan.LogLevel)
```

File: lib/logger/utils.spec.ts [hunk 23]
```diff
@@ -0,0 +1,40 @@
...
+    mockExit.mockClear();
+
+    mockExit.mockImplementationOnce((number) => {
+      throw new Error(`process.exit: ${number}`);
+    });
+    expect(() => {
+      validateLogLevel('100');
+    }).toThrow();
+    expect(mockExit).toHaveBeenCalledWith(1);
+  });
```
Comment (viceice) [inline lib/logger/utils.spec.ts:39]:
```suggestion
  it.each`
    input
    ${'warning'}
    ${'100'}
  `('checks for invalid log level: $input', (input) => {
    // Mock when the function exits
    const mockExit = jest.spyOn(process, 'exit');
    mockExit.mockImplementationOnce((number) => {
      throw new Error(`process.exit: ${number}`);
    });
    expect(() => {
      validateLogLevel(input);
    }).toThrow();
    expect(mockExit).toHaveBeenCalledWith(1);
  });
```

use ìt.each` for multi value tests 😉

File: lib/logger/utils.ts (hunk 6 above)
Comment (rarkins) [reply lib/logger/utils.ts:231]: I think that process.env values are always strings

**Review by rarkins — CHANGES_REQUESTED** [review]
Does Bunyan accept both upper and lower case? If not, are you doing any massaging of the string?

**Comment by hasanwhitesource** [comment]
> Does Bunyan accept both upper and lower case? If not, are you doing any massaging of the string?

Yes it works with all lower case or all uppercase characters

File: lib/logger/utils.ts (hunk 6 above)
Comment (hasanwhitesource) [reply lib/logger/utils.ts]: Removed these checks. I also think the user wont enter numbers.

File: lib/logger/utils.spec.ts [hunk 24]
```diff
@@ -0,0 +1,35 @@
...
+
+  it('checks for valid log levels', () => {
+    expect(validateLogLevel(undefined)).toBeUndefined();
+    expect(validateLogLevel('')).toBeUndefined();
+    expect(validateLogLevel(' ')).toBeUndefined();
+    expect(validateLogLevel('warn')).toBeUndefined();
+    expect(validateLogLevel('debug')).toBeUndefined();
+    expect(validateLogLevel('trace')).toBeUndefined();
+    expect(validateLogLevel('TRACE')).toBeUndefined();
+    expect(validateLogLevel('info' as bunyan.LogLevel)).toBeUndefined();
```
Comment (viceice) [inline lib/logger/utils.spec.ts:17]:
```suggestion
  it.each`
    input
    ${undefined}
    ${''}
    ${'warn'}
    ${'debug'}
    ${'trace'}
    ${'TRACE'}
    ${'info'}
  `('checks for valid log level: $input', (input) =>{
    expect(validateLogLevel(input)).toBeUndefined();
```

File: lib/logger/utils.ts [hunk 25]
```diff
@@ -206,3 +206,46 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+    'fatal',
+  ];
+  if (!logLevelToCheck) {
+    return;
+  }
+  if (typeof logLevelToCheck === 'string') {
+    logLevelToCheck = logLevelToCheck.toLocaleLowerCase();
+    if (
+      allowedValues.includes(logLevelToCheck as bunyan.LogLevel) ||
+      logLevelToCheck.trim().length === 0
```
Comment (viceice) [inline lib/logger/utils.ts:234]:
```suggestion
      allowedValues.includes(logLevelToCheck as bunyan.LogLevel)
```
This would fail later, as i think bunyan don't accept ` ` or ` debug`. 

So we should always trim or never accept those values. I prefer to not accept.

Comment (hasanwhitesource) [reply lib/logger/utils.ts:234]: Yes but after the function call I see we are taking care of the case when `process.env=''`. Should we ignore the case when that field only has white spaces ?

File: lib/logger/utils.spec.ts (hunk 24 above)
Comment (hasanwhitesource) [reply lib/logger/utils.spec.ts]: For some reason the undefined is being passed as an object and the test is failing with this change. Lets keep it simple as it is ?

File: lib/logger/utils.ts [hunk 26]
```diff
@@ -206,3 +206,46 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+    'warn',
+    'error',
+    'fatal',
+  ];
+  if (!logLevelToCheck) {
+    // when logLevel is undefined
+    return;
+  }
+  if (typeof logLevelToCheck === 'string') {
+    logLevelToCheck = logLevelToCheck.trim();
```
Comment (hasanwhitesource) [inline lib/logger/utils.ts:232]: @viceice Should I change to ?
```suggestion
        // eslint-disable-next-line no-param-reassign
    logLevelToCheck = logLevelToCheck.trim();
    // eslint-disable-next-line no-param-reassign
```

File: lib/logger/utils.ts [hunk 27]
```diff
@@ -206,3 +206,46 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+    'debug',
+    'info',
+    'warn',
+    'error',
+    'fatal',
+  ];
+  if (!logLevelToCheck) {
+    // when logLevel is undefined
+    return;
+  }
```
Comment (rarkins) [inline lib/logger/utils.ts:230]: This `!` check would return if the value is "falsy", which in JS means things like `0`, `false`, and empty string `''`. However because we know the input is string or undefined, then the only one applicable is `''`, and I *think* that's not possible when using `process.env`.

```suggestion
  if (is.undefined(logLevelToCheck)) {
    // when logLevel is undefined
    return;
  }
```

File: lib/logger/utils.ts [hunk 28]
```diff
@@ -206,3 +206,46 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+  if (typeof logLevelToCheck === 'string') {
```
Comment (rarkins) [inline lib/logger/utils.ts:231]:
```suggestion
  if (is.string(logLevelToCheck)) {
```

Also import `@sindresorhus/is`.

File: lib/logger/utils.ts [hunk 29]
```diff
@@ -206,3 +206,46 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
...
+    logLevelToCheck = logLevelToCheck.trim();
+    logLevelToCheck = logLevelToCheck.toLocaleLowerCase();
```
Comment (rarkins) [inline lib/logger/utils.ts:233]: It's a mistake to do this logic because you are not doing the equivalent logic back in the index file when you start the bunyan logger. So for example you would validate ` 
 INFO  ` as OK, and then still get a crash from Bunyan.

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/logger/utils.ts (hunk 29 above)
Comment (hasanwhitesource) [reply lib/logger/utils.ts]: I will trim and convert to lower case as we originally agreed in the issue in case the process.env is a string

File: lib/logger/utils.ts [hunk 30]
```diff
@@ -206,3 +206,42 @@ export function withSanitizer(streamConfig: bunyan.Stream): bunyan.Stream {
 
   throw new Error("Missing 'stream' or 'path' for bunyan stream");
 }
+
+/**
+ * A function that terminates exeution if the log level that was entered is
+ *  not a valid value for the bunyan logger.
```
Comment (HonkingGoose) [inline lib/logger/utils.ts:212]:
```suggestion
 *  not a valid value for the Bunyan logger.
```

Bunyan is a proper noun, so should be capitalized.

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by rarkins — APPROVED** [review]

**Comment by hasanwhitesource** [comment]
@viceice Are there anymore changes that need to be done you think?
