### PR TITLE
fix: avoid error if no currentVersion found

### LINKED ISSUE #9097: Internal error with composer minimum-stability "dev"
**What Renovate type, platform and version are you using?**

Self hosted 24.78.4 as well as GitHub app.

**Describe the bug**

Internal error when these conditions are met:
- composer.json `minimum-stability` is "dev"
- range in composer.json is ^2.0
- installed version in composer.lock is 2.0.0@beta16
- there are no non-beta 2.x versions of the package available
- `rangeStrategy` is "update-lockfile"

**Relevant debug logs**

```ERROR: Repository has unknown error
{
  "err": {
    "message": "Cannot read property 'replace' of null",
    "stack": "TypeError: Cannot read property 'replace' of null
    at normalizeVersion (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/composer/index.js:46:21)
    at composer2npm (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/composer/index.js:50:24)
    at Object.getMajor (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/composer/index.js:66:66)
    at Object.getBucket (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/bucket.js:9:34)
    at Object.lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:156:37)
    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:39:32)
    at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22"
  }
}
```

**Have you created a minimal reproduction repository?**

Yes, I have set up a repro repo for this issue: https://github.com/JorisVanEijden/renovate-repro
I used the drupal/private_message package because this is what triggered the bug for me.

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

When checking for updates renovate does not take the minimum-stability parameter into account when filtering the availbale releases against the range from the requirement.
This can lead to a null "current version".

As a workaround you can specify the range more specifically, like `^2.0@beta` in the composer.json.

Apparent composer behaviour:
- 2.0.0@beta16 does not satisfy the range ^2.0 with the default `minimum-stability` "stable".
- 2.0.0@beta16 _does_ satisfy the range ^2.0 with a `minimum-stability` of "dev", "alpha" or "beta".

Related feasture rquest that would prevent this bug: https://github.com/renovatebot/renovate/issues/4542

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Aborts process lookup if no currentVersion is found.

## Context:

Closes #9097

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [x] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/repository/process/lookup/index.ts [hunk 1]
```diff
@@ -153,6 +153,10 @@ export async function lookupUpdates(
         latestVersion,
         allVersions.map((v) => v.version)
       );
+    // istanbul ignore if
+    if (!currentVersion) {
```
Comment (rarkins) [inline lib/workers/repository/process/lookup/index.ts:157]: I don't have time to work out a test for this. It only occurs because of a versioning problem which is even harder to fix.

Comment (viceice) [reply lib/workers/repository/process/lookup/index.ts:157]: Does it work with docker digest updates? Current version can be undefined when no tag is used, so only image name and digest is found.

**Review by viceice — APPROVED** [review]
