### PR TITLE
fix(gitlab): properly massage config migration MR links

### LINKED ISSUE #32178: GitLab Dependency dashboard does not link to Config Migration MR
### Discussed in https://github.com/renovatebot/renovate/discussions/32077

<div type='discussions-op-text'>

<sup>Originally posted by **astellingwerf** October 22, 2024</sup>
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

38.128.6

### Please tell us more about your question or problem

On my GitLab instance, the Dependency Dashboard does mention the Configuration Migration MR, but it's not clickable. On GL, MRs are referenced using `!42`, not `#42`.

image

### PR DESCRIPTION
**Pull request by kylesferrazza**
## Changes

Fixes GitLab MR links for Config Migration.

## Context

Please select one of the following:

- [x] This closes an existing Issue, Closes: #32178 
- [ ] This doesn't close an Issue, but I accept the risk that this PR may be closed if maintainers disagree with its opening or implementation

## AI assistance disclosure

Did you use AI tools to create any part of this pull request?

Please select one option and, if yes, briefly describe how AI was used (e.g., code, tests, docs) and which tool(s) you used.

- [x] No — I did not use AI for this contribution.
- [ ] Yes — minimal assistance (e.g., IDE autocomplete, small code completions, grammar fixes).
- [ ] Yes — substantive assistance (AI-generated non‑trivial portions of code, tests, or documentation).
- [ ] Yes — other (please describe):

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests, but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

The public repository: https://gitlab.com/kylesferrazza/nix-configs

### CODE REVIEW

**Review by RahulGautamSingh — APPROVED** [review]

File: lib/modules/platform/gitlab/index.ts [hunk 1]
```diff
@@ -825,6 +825,7 @@ export async function mergePr({ id }: MergePRConfig): Promise<boolean> {
 export function massageMarkdown(input: string): string {
   const desc = input
     .replace(regEx(/Pull Request/g), 'Merge Request')
+    .replace(regEx(/\bPR: #/g), 'MR: !')
```
Comment (astellingwerf) [inline lib/modules/platform/gitlab/index.ts:828]: I believe we should instead format the input message (from https://github.com/renovatebot/renovate/blob/76f911041a1808555e798f36731052a09a3109e7/lib/workers/repository/dependency-dashboard.ts#L404) in such a way that line 831 catches it.

Comment (RahulGautamSingh) [reply lib/modules/platform/gitlab/index.ts:828]: Line 831 specifically catches the texts with links and not direct references, so that would not work

**Review by viceice — APPROVED** [review]
