### PR TITLE
fix(github): Remote branch existence check

### LINKED ISSUE #11481: GitHub PR creation fails silently with 422
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Describe the bug

Renovate sonmetimes isn't able to create a pr on github and get' a 422, which is only debug logged. I think this should be logged as warning to be visible on dependency dashboard.

https://github.com/renovatebot/renovate/discussions/11479#discussioncomment-1253954

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Setting current branch to master(branch="renovate/lock-file-maintenance")
DEBUG: latest commit(branch="renovate/lock-file-maintenance")
{
  "branchName": "master",
  "latestCommitDate": "2021-08-27T11:31:07+02:00"
}
DEBUG: getBranchPr(renovate/lock-file-maintenance)(branch="renovate/lock-file-maintenance")
DEBUG: findPr(renovate/lock-file-maintenance, undefined, open)(branch="renovate/lock-file-maintenance")
DEBUG: findPr(renovate/lock-file-maintenance, undefined, closed)(branch="renovate/lock-file-maintenance")
DEBUG: branchExists=true(branch="renovate/lock-file-maintenance")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/lock-file-maintenance")
DEBUG: recreateClosed is true(branch="renovate/lock-file-maintenance")
DEBUG: Checking if PR has been edited(branch="renovate/lock-file-maintenance")
DEBUG: Last commit author does not match git author email - branch has been modified(branch="renovate/lock-file-maintenance")
{
  "branchName": "renovate/lock-file-maintenance",
  "lastAuthor": "dawid.janczak@gmail.com",
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: findPr(renovate/lock-file-maintenance, undefined, !open)(branch="renovate/lock-file-maintenance")
DEBUG: Found PR #552(branch="renovate/lock-file-maintenance")
DEBUG: Found old PR matching this branch - will override it(branch="renovate/lock-file-maintenance")
{
  "oldPrNumber": 552,
  "oldPrSha": "e751d48839faa74d2b571fbec204527119886aef",
  "branchSha": "e751d48839faa74d2b571fbec204527119886aef"
}
DEBUG: Checking schedule(before 5am on monday, null)(branch="renovate/lock-file-maintenance")
DEBUG: Checking 1 schedule(s)(branch="renovate/lock-file-maintenance")
DEBUG: Checking schedule "before 5am on monday"(branch="renovate/lock-file-maintenance")
{
  "parsedSchedule": {
    "schedules": [
      {
        "t_b": [
          18000
        ],
        "d": [
          2
        ]
      }
    ],
    "exceptions": [],
    "error": -1
  }
}
DEBUG: Matches schedule before 5am on monday(branch="renovate/lock-file-maintenance")
DEBUG: Branch already exists(branch="renovate/lock-file-maintenance")
DEBUG: getBranchPr(renovate/lock-file-maintenance)(branch="renovate/lock-file-maintenance")
DEBUG: findPr(renovate/lock-file-maintenance, undefined, open)(branch="renovate/lock-file-maintenance")
DEBUG: findPr(renovate/lock-file-maintenance, undefined, closed)(branch="renovate/lock-file-maintenance")
DEBUG: Found branch protection(branch="renovate/lock-file-maintenance")
DEBUG: Branch protection: PRs must be up-to-date before merging(branch="renovate/lock-file-maintenance")
DEBUG: IsBranchStale=true(branch="renovate/lock-file-maintenance")
{
  "isStale": true,
  "branches": {
    "all": [
      "origin/master",
      "origin/renovate/all"
    ],
    "branches": {
      "origin/master": {
        "current": false,
        "name": "origin/master",
        "commit": "1f72e3f",
        "label": "Merge pull request #569 from ygt/refactor-order-presenter"
      },
      "origin/renovate/all": {
        "current": false,
        "name": "origin/renovate/all",
        "commit": "8eb3df2",
        "label": "Update all dependencies"
      }
    },
    "current": "",
    "detached": false
  },
  "currentBranch": "master",
  "currentBranchSha": "1f72e3f55377ae9211994d0623c9c4dc56597e87"
}
DEBUG: Branch is stale and needs rebasing(branch="renovate/lock-file-maintenance")
DEBUG: Cannot rebase branch as it has been modified(branch="renovate/lock-file-maintenance")
DEBUG: Using reuseExistingBranch: true(branch="renovate/lock-file-maintenance")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=true(branch="renovate/lock-file-maintenance")
DEBUG: No package files need updating(branch="renovate/lock-file-maintenance")
DEBUG: Getting updated lock files(branch="renovate/lock-file-maintenance")
DEBUG: Skipping lockFileMaintenance update(branch="renovate/lock-file-maintenance")
DEBUG: No updated lock files in branch(branch="renovate/lock-file-maintenance")
DEBUG: No files to commit(branch="renovate/lock-file-maintenance")
DEBUG: Checking if we can automerge branch(branch="renovate/lock-file-maintenance")
DEBUG: mergeStatus=no automerge(branch="renovate/lock-file-maintenance")
DEBUG: Ensuring PR(branch="renovate/lock-file-maintenance")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/lock-file-maintenance")
DEBUG: getBranchPr(renovate/lock-file-maintenance)(branch="renovate/lock-file-maintenance")
DEBUG: findPr(renovate/lock-file-maintenance, undefined, open)(branch="renovate/lock-file-maintenance")
DEBUG: findPr(renovate/lock-file-maintenance, undefined, closed)(branch="renovate/lock-file-maintenance")
DEBUG: Creating PR(branch="renovate/lock-file-maintenance")
{
  "prTitle": "Lock file maintenance"
}
DEBUG: Creating PR(branch="renovate/lock-file-maintenance")
{
  "title": "Lock file maintenance",
  "head": "ygt:renovate/lock-file-maintenance",
  "base": "master",
  "draft": false
}
DEBUG: 422 Error thrown from GitHub(branch="renovate/lock-file-maintenance")
{
  "err": {
    "name": "HTTPError",
    "timings": {
      "start": 1630282618966,
      "socket": 1630282618966,
      "lookup": 1630282618967,
      "connect": 1630282618976,
      "secureConnect": 1630282618988,
      "upload": 1630282618988,
      "response": 1630282619305,
      "end": 1630282619305,
      "phases": {
        "wait": 0,
        "dns": 1,
        "tcp": 9,
        "tls": 12,
        "request": 0,
        "firstByte": 317,
        "download": 0,
        "total": 339
      }
    },
    "message": "Response code 422 (Unprocessable Entity)",
    "stack": "HTTPError: Response code 422 (Unprocessable Entity)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
    "options": {
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "accept": "application/vnd.github.machine-man-preview+json",
        "authorization": "***********",
        "content-type": "application/json",
        "content-length": "1200",
        "accept-encoding": "gzip, deflate, br"
      },
      "url": "https://api.github.com/repos/ygt/sb-voucher-redemptions/pulls",
      "username": "",
      "password": "",
      "method": "POST",
      "http2": false
    },
    "response": {
      "statusCode": 422,
      "statusMessage": "Unprocessable Entity",
      "body": {
        "message": "Validation Failed",
        "errors": [
          {
            "resource": "PullRequest",
            "code": "custom",
            "message": "No commits between master and renovate/lock-file-maintenance"
          }
        ],
        "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"
      },
      "headers": {
        "server": "GitHub.com",
        "date": "Mon, 30 Aug 2021 00:16:59 GMT",
        "content-type": "application/json; charset=utf-8",
        "content-length": "247",
        "x-github-media-type": "github.v3; param=machine-man-preview; format=json",
        "x-ratelimit-limit": "5950",
        "x-ratelimit-remaining": "5916",
        "x-ratelimit-reset": "1630283251",
        "x-ratelimit-used": "34",
        "x-ratelimit-resource": "core",
        "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
        "access-control-allow-origin": "*",
        "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
        "x-frame-options": "deny",
        "x-content-type-options": "nosniff",
        "x-xss-protection": "0",
        "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
        "content-security-policy": "default-src 'none'",
        "vary": "Accept-Encoding, Accept, X-Requested-With",
        "x-github-request-id": "9F72:4C7C:2269A70:247D070:612C237A",
        "connection": "close"
      },
      "httpVersion": "1.1"
    }
  }
}
DEBUG: Pull request creation error(branch="renovate/lock-file-maintenance")
{
  "err": {
    "hostType": "github",
    "err": {
      "name": "HTTPError",
      "timings": {
        "start": 1630282618966,
        "socket": 1630282618966,
        "lookup": 1630282618967,
        "connect": 1630282618976,
        "secureConnect": 1630282618988,
        "upload": 1630282618988,
        "response": 1630282619305,
        "end": 1630282619305,
        "phases": {
          "wait": 0,
          "dns": 1,
          "tcp": 9,
          "tls": 12,
          "request": 0,
          "firstByte": 317,
          "download": 0,
          "total": 339
        }
      },
      "message": "Response code 422 (Unprocessable Entity)",
      "stack": "HTTPError: Response code 422 (Unprocessable Entity)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
      "options": {
        "headers": {
          "user-agent": "Renovate Bot (GitHub App 2740)",
          "accept": "application/vnd.github.machine-man-preview+json",
          "authorization": "***********",
          "content-type": "application/json",
          "content-length": "1200",
          "accept-encoding": "gzip, deflate, br"
        },
        "url": "https://api.github.com/repos/ygt/sb-voucher-redemptions/pulls",
        "username": "",
        "password": "",
        "method": "POST",
        "http2": false
      },
      "response": {
        "statusCode": 422,
        "statusMessage": "Unprocessable Entity",
        "body": {
          "message": "Validation Failed",
          "errors": [
            {
              "resource": "PullRequest",
              "code": "custom",
              "message": "No commits between master and renovate/lock-file-maintenance"
            }
          ],
          "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"
        },
        "headers": {
          "server": "GitHub.com",
          "date": "Mon, 30 Aug 2021 00:16:59 GMT",
          "content-type": "application/json; charset=utf-8",
          "content-length": "247",
          "x-github-media-type": "github.v3; param=machine-man-preview; format=json",
          "x-ratelimit-limit": "5950",
          "x-ratelimit-remaining": "5916",
          "x-ratelimit-reset": "1630283251",
          "x-ratelimit-used": "34",
          "x-ratelimit-resource": "core",
          "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
          "access-control-allow-origin": "*",
          "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
          "x-frame-options": "deny",
          "x-content-type-options": "nosniff",
          "x-xss-protection": "0",
          "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
          "content-security-policy": "default-src 'none'",
          "vary": "Accept-Encoding, Accept, X-Requested-With",
          "x-github-request-id": "9F72:4C7C:2269A70:247D070:612C237A",
          "connection": "close"
        },
        "httpVersion": "1.1"
      }
    },
    "message": "external-host-error",
    "stack": "Error: external-host-error\n    at handleGotError (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/github.js:85:15)\n    at GithubHttp.request (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/github.js:161:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async GithubHttp.requestJson (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/index.js:151:21)\n    at async Proxy.createPr (/home/ubuntu/renovateapp/node_modules/renovate/dist/platform/github/index.js:1156:17)\n    at async Object.ensurePr (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/pr/index.js:347:22)\n    at async Object.processBranch (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/branch/index.js:480:37)\n    at async Object.writeUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/write.js:25:21)\n    at async Object.update (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/extract-update.js:110:15)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:68:21)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:422:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:660:5"
  }
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

The problem is when we have branch `foo/bar`, HEAD request for `foo` will return 200.

To fix this, we first make another HEAD request with `/` suffix, and make sure it doesn't return 200 (otherwise, it means, nested refs exist).

## Context

- Closes: #11481

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/platform/github/index.ts [hunk 1]
```diff
@@ -759,26 +762,57 @@ export async function findPr({
 
 const REOPEN_THRESHOLD_MILLIS = 1000 * 60 * 60 * 24 * 7;
 
+async function remoteBranchExists(
```
Comment (viceice) [inline lib/modules/platform/github/index.ts:765]: can we move this to a separate file because this file is already really big. then this function would be easier to test.

File: lib/modules/platform/github/index.ts [hunk 2]
```diff
@@ -759,26 +762,57 @@ export async function findPr({
...
+  branchName: string
+): Promise<boolean> {
+  const RefSchema = z
+    .object({
+      ref: z.string().transform((val) => val.replace(/^refs\/heads\//, '')),
+    })
+    .transform(({ ref }) => ref);
+
+  const { val, err } = await githubApi
+    .getJsonSafe(
```
Comment (viceice) [inline lib/modules/platform/github/index.ts:776]: there is no other way to get this info with a head request? 😕 (asking because of rate limits, head requests don't count)

**Review by viceice — COMMENTED** [review]
otherwise LGTM

File: lib/modules/platform/github/index.ts (hunk 2 above)
Comment (zharinov) [reply lib/modules/platform/github/index.ts]: Ha, I think I've found the way

Comment (zharinov) [reply lib/modules/platform/github/index.ts]:
```
❯ xh head https://api.github.com/repos/zharinov/renovate/git/refs/heads/foo                
HTTP/2.0 200 OK
...

❯ xh head https://api.github.com/repos/zharinov/renovate/git/refs/heads/foo/
HTTP/2.0 200 OK
...

❯ xh head https://api.github.com/repos/zharinov/renovate/git/refs/heads/foo/bar
HTTP/2.0 200 OK
...

❯ xh head https://api.github.com/repos/zharinov/renovate/git/refs/heads/foo/bar/
HTTP/2.0 404 Not Found
...
```

File: lib/modules/platform/github/branch.ts [hunk 3]
```diff
@@ -0,0 +1,38 @@
+import { Http, HttpError } from '../../../util/http';
+import { Result } from '../../../util/result';
+
+function headRef(
+  http: Http,
```
Comment (viceice) [inline lib/modules/platform/github/branch.ts:5]: we probably should move the http instance to common, like other platforms, so we don't need to pass it through. 🤔

**Review by viceice — COMMENTED** [review]
please update PR body to match new behavior

**Review by viceice — DISMISSED** [review]
ups, already done 👍

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
you need to find the unresolved conversations 🙃
