### PR TITLE
fix(maven): Check each release for corresponding jar

### LINKED ISSUE #4471: Renovate updates gradle dependency version that does not exist
**What Renovate type are you using?**
GitHub App

**Describe the bug**
Renovate creates a PR offering to upgrade the following dendency: 

`runtime "org.glassfish.web:el-impl:2.2"`
 
To `2.2.1`. None of the repositories in my build.gradle file contain that version, and in fact, I can't seem to find it in any repository. They *do* contain a `2.2.1.b01`, `2.2.1.b02`, etc. So it appears Renovate is not detecting the beta semantics on the versioning string and actually just chopping it off, which then breaks the version definition. Renovate attempts to use the Grails Core repo, which [you can see here](https://repo.grails.org/grails/core/org/glassfish/web/el-impl/) does not contain the version that it calculates is available. 

**Did you see anything helpful in debug logs?**
```
DEBUG: Found 2 repositories for org.glassfish.web:el-impl
DEBUG: Looking up org.glassfish.web:el-impl in repository #0 - https://jcenter.bintray.com/
...
DEBUG: Found 15 new versions for org.glassfish.web:el-impl in repository https://jcenter.bintray.com/
DEBUG: Looking up org.glassfish.web:el-impl in repository #1 - https://repo.grails.org/grails/core/
...
DEBUG: Found 1 new versions for org.glassfish.web:el-impl in repository https://repo.grails.org/grails/core/
DEBUG: Found 16 versions for org.glassfish.web:el-impl
DEBUG: Url not found https://repo.grails.org/grails/core/org/glassfish/web/el-impl/2.2.1/el-impl-2.2.1.pom
DEBUG: org.glassfish.web:el-impl not found in repository https://repo.grails.org/grails/core/
```
...followed by this in the updates json: 
```
{
    "name": "el-impl",
    "depGroup": "org.glassfish.web",
    "depName": "org.glassfish.web:el-impl",
    "currentValue": "2.2",
    "registryUrls": [
        "https://jcenter.bintray.com/",
        "https://repo.grails.org/grails/core"
    ],
    "updates": [
        {
        "fromVersion": "2.2",
        "toVersion": "2.2.1",
        "newValue": "2.2.1",
        "newMajor": 2,
        "newMinor": 2,
        "updateType": "minor",
        "isSingleVersion": true
        }
    ],
    "warnings": [],
    "sourceUrl": null
},
```
**To Reproduce**

1.  Create repository with with a build.gradle file containing...

```
dependencies {
  runtime "org.glassfish.web:el-impl:2.2"
}
```
2.  Let Renovate do it's thing, and you'll see a PR to upgrade it to 2.2.1

**Expected behavior**
"org.glassfish.web:el-impl:2.2" is the latest non-beta release available. Has been for years now.  It should remain as is. If Renovate were to upgrade to the latest version regardless of beta/alpha versioning semantics (which it probably shouldn't do by default) then it should obviously respect those versioning semantics. 

**Screenshots**
N/A

**Additional context**

### PR DESCRIPTION
**Pull request by zharinov**
Rel #5538
Closes #4471

### CODE REVIEW

**Comment by zharinov** [comment]
Do we still need cache entire results by `lookupName` key?

**Comment by zharinov** [comment]
Still leaves room for bugs if directory with `jar` exists, but `metadata.xml` doesn't list this version.

**Comment by rarkins** [comment]
As per https://github.com/renovatebot/renovate/issues/5538#issuecomment-589588005 there is a need for two levels of caching:

1. Similar as done to day, cache the *end result* based on lookupName / url for a limited time (after which the cache expires/disappears)
2. New: cache the list of JAR files and exists/not-exists results, also based on lookupName / url but storing the result for much longer (hours, perhaps a day)

The goal is: if the list of releases in the XML doesn't change, then we shouldn't query the JAR files again unless a long time has elapsed. We don't want to be requerying every JAR file once every 10 minutes, for example.

**Comment by zharinov** [comment]
What logger messages to add?

**Comment by zharinov** [comment]
Test on real repo is okay

**Review by rarkins — COMMENTED** [review]
Do we have any public examples that I can test/debug against? e.g. can you give me `pom.xml` that will demonstrate this filtering behaviour?

**Review by rarkins — COMMENTED** [review]
Do we have any public examples that I can test/debug against? e.g. can you give me `pom.xml` that will demonstrate this filtering behaviour?

File: lib/datasource/maven/index.ts [hunk 1]
```diff
@@ -136,6 +138,85 @@ function extractVersions(metadata: XmlDocument): string[] {
...
+        const proto = artifactUrl.protocol;
+        if (proto === 'http:' || proto === 'https:') {
+          artifactsInfo[version] = await isHttpResourceExists(artifactUrl);
+        } else {
+          artifactsInfo[version] = true;
+        }
+      }
+    }
+
+    // Retry earlier for status other than 404
```
Comment (rarkins) [inline lib/datasource/maven/index.ts]: This is a good idea.. wondering if 6 hours is too long though. We should only attempt these URLs if the XML returns a 200 OK, so what would be the chances of a non-404 in such cases?

File: lib/datasource/maven/index.ts [hunk 2]
```diff
@@ -136,6 +138,85 @@ function extractVersions(metadata: XmlDocument): string[] {
...
+): Promise<string[]> {
+  const cacheNamespace = 'datasource-maven-metadata';
+  const cacheKey = dependency.dependencyUrl;
+  let artifactsInfo: ArtifactsInfo | null = await renovateCache.get<
+    ArtifactsInfo
+  >(cacheNamespace, cacheKey);
+
+  if (!isValidArtifactsInfo(artifactsInfo, versions)) {
+    artifactsInfo = {};
+    for (const version of versions) {
```
Comment (rarkins) [inline lib/datasource/maven/index.ts]: Wondering if doing this in series is too slow

File: lib/datasource/maven/index.ts (hunk 1 above)
Comment (zharinov) [reply lib/datasource/maven/index.ts]: For Maven, it looks like something extraordinary to get 50x errors, but for other repositories it can be produced more frequently. Does one hour seem optimal?

Comment (rarkins) [reply lib/datasource/maven/index.ts]: Sure. It’s hopefully unlikely to get anything other than a 200 or 404 for jars if got a 200 for the index.

File: lib/datasource/maven/index.ts (hunk 2 above)
Comment (zharinov) [reply lib/datasource/maven/index.ts]: Good point, already made it concurrent

File: lib/datasource/maven/index.spec.ts [hunk 3]
```diff
@@ -12,8 +12,8 @@ const MYSQL_VERSIONS = [
   '8.0.7',
   '8.0.8',
   '8.0.9',
-  '8.0.11',
-  '8.0.12',
+  // '8.0.11',
+  // '8.0.12',
```
[the remark this answers is not in the document]
Comment (zharinov) [reply lib/datasource/maven/index.spec.ts]: Let's leave it to inform they're still in use later?

[the remark this answers is not in the document]
Comment (zharinov) [reply lib/datasource/maven/index.spec.ts]: Maybe, it would be nice to refactor this file

**Comment by zharinov** [comment]
> Do we have any public examples that I can test/debug against? e.g. can you give me pom.xml that will demonstrate this filtering behaviour?

I have [this example](https://github.com/zharinov/renovate-test-maven2/pull/4) from the [original issue](https://github.com/renovatebot/renovate/issues/4471), which upgrades to `2.2.1` in `master` and to `2.2` with this branch (according to [the repo structure](https://repo.grails.org/grails/core/org/glassfish/web/el-impl/)).

**Comment by rarkins** [comment]
@zharinov needs refactoring to use util/http

File: lib/datasource/maven/index.ts [hunk 4]
```diff
@@ -143,6 +145,113 @@ function extractVersions(metadata: XmlDocument): string[] {
...
+type ArtifactInfoResult = [string, boolean | null];
+
+async function getArtifactInfo(
+  version: string,
+  artifactUrl: url.URL
+): Promise<ArtifactInfoResult> {
+  const proto = artifactUrl.protocol;
+  if (proto === 'http:' || proto === 'https:') {
+    const result = await isHttpResourceExists(artifactUrl);
+    debugger;
```
Comment (rarkins) [inline lib/datasource/maven/index.ts:199]:
```suggestion
```
