### PR TITLE
fix(manager/kubernetes): don't extract unknown kubernetes objects

### LINKED ISSUE #18299: Renovate fails lookup dependencies related to Helm charts/Kubernetes manifests
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.213.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab CE

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When analyzing dependencies this errors has popped up with Helm charts specifically:

`Renovate failed to look up the following dependencies: `ConfigMap`, `ServiceAccount`, `Service`, `Namespace`, `Issuer`, `Certificate`, `Pod`.`

There is nothing unique in any of the templates it says are affected.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by viceice**
## Changes
Only extract kubernetes objects that we know will return results from the `kubernetes-api` datasource

## Context
- #17420
- #18222
- closes https://github.com/renovatebot/renovate/issues/18299

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
this will again return null and trigger the warning:
https://github.com/renovatebot/renovate/blob/ef11204bfc6a0d4d8a109d6bd34d1ba70a2c3223/lib/modules/datasource/index.ts#L311

**Comment by viceice** [comment]
we probably need to filter here for known vs unknown apis
https://github.com/renovatebot/renovate/blob/ef11204bfc6a0d4d8a109d6bd34d1ba70a2c3223/lib/modules/manager/kubernetes/extract.ts#L69-L81

**Comment by JamieMagee** [comment]
I've changed the approach of this PR to only have the manager extract known kubernetes objects. That way, by the time it makes it to the datasource, we can guarantee that we have results available.

File: lib/modules/manager/kubernetes/extract.ts [hunk 1]
```diff
@@ -73,6 +79,7 @@ function extractApis(content: string, fileName: string): PackageDependency[] {
         is.nonEmptyStringAndNotWhitespace(m.kind) &&
         is.nonEmptyStringAndNotWhitespace(m.apiVersion)
     )
+    .filter((m) => Object.keys(kubernetesApiVersions).includes(m.kind))
```
Comment (rarkins) [inline lib/modules/manager/kubernetes/extract.ts:82]: Maybe push this Object.keys() up into the top scope so that it's not recalculated every time?

File: lib/modules/manager/kubernetes/extract.ts [hunk 2]
```diff
@@ -8,6 +10,10 @@ import { getDep } from '../dockerfile/extract';
 import type { ExtractConfig, PackageDependency, PackageFile } from '../types';
 import type { KubernetesConfiguration } from './types';
 
+const kubernetesApiVersions: Record<string, string[]> = JSON5.parse(
+  dataFiles.get('data/kubernetes-api.json5')!
+);
```
Comment (viceice) [inline lib/modules/manager/kubernetes/extract.ts:15]: we should share this, otherwise we need twice in memory. (perf)

File: lib/modules/manager/kubernetes/extract.ts (hunk 1 above)
Comment (viceice) [reply lib/modules/manager/kubernetes/extract.ts:82]: yes, should be stored as Set for perf

File: lib/modules/manager/kubernetes/extract.ts (hunk 2 above)
Comment (JamieMagee) [reply lib/modules/manager/kubernetes/extract.ts]: You mean between manager and datasource?

Comment (viceice) [reply lib/modules/manager/kubernetes/extract.ts]: yes

Comment (viceice) [reply lib/modules/manager/kubernetes/extract.ts]: manager does access datasource anyways

**Review by rarkins — DISMISSED** [review]

**Comment by lauraseidler** [comment]
@viceice @JamieMagee this issue is affecting us as well - any way to help moving this out of Draft and getting it released?

**Comment by viceice** [comment]
sure, we just need to.chsngevthe double JSON parse to reuse from datasource in manager as mentioned.

**Comment by viceice** [comment]
i can maybe make it tomorrow

**Review by rarkins — APPROVED** [review]
