### PR TITLE
fix(maven): Correct incrementing of right-open ranges

### LINKED ISSUE #10168: Bad version for spring
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

**Describe the bug**

...

**Relevant debug logs**

The last version of `spring-boot` is **2.4.6** for `renovate`
https://app.renovatebot.com/dashboard#github/the-benchmarker/web-frameworks/363023759

However, the last release is **2.5.0**
https://search.maven.org/artifact/org.springframework.boot/spring-boot-starter-parent

<details><summary>Click me to see logs</summary>

```
{
        "datasource": "maven",
        "packageFile": "java/spring/pom.xml",
        "deps": [
          {
            "datasource": "maven",
            "depName": "org.springframework.boot:spring-boot-starter-parent",
            "currentValue": "[2.4,2.5)",
            "fileReplacePosition": 403,
            "registryUrls": [
              "https://repo.maven.apache.org/maven2"
            ],
            "depIndex": 0,
            "warnings": [],
            "sourceUrl": "https://github.com/spring-projects/spring-boot",
            "homepage": "https://spring.io/projects/spring-boot",
            "currentVersion": "2.4.6",
            "updates": []
          }
        ],
        "parent": "java/pom.xml"
      },
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Related to https://github.com/the-benchmarker/web-frameworks/issues/4335

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

Distinguish right-open/right-closed ranges when searching which one should be extended.

## Context:

Closes #10168 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

Example: https://github.com/renovate-testing/test-10168-bad-spring-version

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

File: lib/versioning/maven/compare.ts [hunk 1]
```diff
@@ -545,13 +541,15 @@ function autoExtendMavenRange(
     interval.leftValue = coerceRangeValue(leftValue, newValue);
   }
 
-  if (interval.leftValue && interval.rightValue) {
-    const correctRepresentation =
-      compare(interval.leftValue, interval.rightValue) === 1
-        ? null
-        : rangeToStr(range);
-    return correctRepresentation || currentRepresentation;
+  // istanbul ignore if
```
Comment (viceice) [inline lib/versioning/maven/compare.ts:544]: No test for this?

Comment (zharinov) [reply lib/versioning/maven/compare.ts:544]: Seems like we don't need this check anymore. But I'm not sure , so let it will be kind of *soft assert*. Log a warning, maybe?

Comment (viceice) [reply lib/versioning/maven/compare.ts:544]: sure, can you create a synthetic test for it? if not possible we should remove that code if it's not possible to get there.

Comment (zharinov) [reply lib/versioning/maven/compare.ts]: Okay, I can't create test, guess we've fixed it 😎

**Review by viceice — APPROVED** [review]
