### PR TITLE
fix(terraform): extend module provider git url parsing

### LINKED ISSUE #15467: Terraform-module provider unable to parse some git url
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.41.2

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.9.4

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Hello,

I'm trying to make terraform module updates using renovate on our self hosted gitlab instance. Actually, renovate reports 'invalid-version' for this kind of git url: 

    module "test" {
      source   = "git@my-gitlab-instance.local:devops/terraform/instance.git?ref=v5.0.0"
    ...
    }

If I switch to `https://my-gitlab-instance.local/devops/terraform/instance.git?ref=v5.0.0` it works but renovate cannot authenticate properly.

This is already working for instance for the ansible-galaxy so I think that this should also be supported here.

The problem is the regex [here](https://github.com/renovatebot/renovate/blob/04333d44ab2be145db46026f29df8014a8fce7c5/lib/modules/manager/terraform/modules.ts#L19).

Best,
Jerome

### Relevant debug logs

<details><summary>Logs</summary>

```
{"packageFile":"main.tf","deps":[{"depType":"module","depName":"git@my-gitlab-instance.local:devops/terraform/instance.git?ref=v5.0.0","datasource":"terraform-module","depIndex":0,"updates":[],"warnings":[],"versioning":"hashicorp","skipReason":"invalid-value"},{"depType":"module","depName":"git@my-gitlab-instance.local:devops/terraform/instance.git?ref=v5.0.0","datasource":"terraform-module","depIndex":1,"updates":[],"warnings":[],"versioning":"hashicorp","skipReason":"invalid-value"}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by MaronHatoum**
## Changes
fix gitTagsRefMatchRegex regex

## Context
Closes https://github.com/renovatebot/renovate/issues/15467

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [X] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/terraform/modules.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ export const bitbucketRefMatchRegex = regEx(
   /(?:git::)?(?<url>(?:http|https|ssh)?(?::\/\/)?(?:.*@)?(?<path>bitbucket\.org\/(?<workspace>.*)\/(?<project>.*).git\/?(?<subfolder>.*)))\?ref=(?<tag>.*)$/
 );
 export const gitTagsRefMatchRegex = regEx(
-  /(?:git::)?(?<url>(?:http|https|ssh):\/\/(?:.*@)?(?<path>.*.*\/(?<project>.*\/.*)))\?ref=(?<tag>.*)$/
+  /(?:git::)?(?<url>(?:(?:http|https|ssh)(:\/\/))?(?:.*@)?(?<path>.*.*\/(?<project>.*\/.*)))\?ref=(?<tag>.*)$/
```
Comment (Gabriel-Ladzaretti) [inline lib/modules/manager/terraform/modules.ts:19]:
```suggestion
  /(?:git::)?(?<url>(?:(?:http|https|ssh):\/\/)?(?:.*@)?(?<path>.*.*\/(?<project>.*\/.*)))\?ref=(?<tag>.*)$/
```
I think that this capturing group can be dropped 😀

Comment (viceice) [reply lib/modules/manager/terraform/modules.ts:19]: also `.*.*` should be one `.*` for `path` group

File: lib/modules/manager/terraform/modules.ts [hunk 2]
```diff
@@ -64,7 +64,10 @@ export function analyseTerraformModule(dep: PackageDependency): void {
     dep.datasource = BitBucketTagsDatasource.id;
   } else if (gitTagsRefMatch?.groups) {
     dep.depType = 'module';
-    if (gitTagsRefMatch.groups.path.includes('//')) {
+    if (azureDevOpsSshRefMatch?.groups) {
+      dep.depName = `${azureDevOpsSshRefMatch.groups.organization}/${azureDevOpsSshRefMatch.groups.project}/${azureDevOpsSshRefMatch.groups.repository}${azureDevOpsSshRefMatch.groups.modulepath}`;
+      dep.packageName = azureDevOpsSshRefMatch.groups.url;
+    } else if (gitTagsRefMatch.groups.path.includes('//')) {
```
Comment (Gabriel-Ladzaretti) [inline lib/modules/manager/terraform/modules.ts:70]: In this case we are defaulting to `dep.currentValue = gitTagsRefMatch.groups.tag` as per:
https://github.com/renovatebot/renovate/blob/b34c58c3ee2e094c4d5b96f51054f04e919451d7/lib/modules/manager/terraform/modules.ts#L79
are we ok with that as opposed to  `dep.currentValue = azureDevOpsSshRefMatch.groups.tag;`?

Comment (PhilipAbed) [reply lib/modules/manager/terraform/modules.ts:70]: they both catch the same tag, i actually reviewed the code with maron on this

Comment (Gabriel-Ladzaretti) [reply lib/modules/manager/terraform/modules.ts:70]: than wont `dep.currentValue = azureDevOpsSshRefMatch.groups.tag;` in the given block would be cleaner and more future proof? 😅

Comment (MaronHatoum) [reply lib/modules/manager/terraform/modules.ts:70]: ok I changed it just in case we have different cases.

Comment (PhilipAbed) [reply lib/modules/manager/terraform/modules.ts]: azure works with git tags, so it just has a different domain/host
tags will never be different i believe, 
but if it's clearer to the eyes we can do that

**Review by Gabriel-Ladzaretti — DISMISSED** [review]

File: lib/modules/manager/terraform/modules.ts [hunk 3]
```diff
@@ -64,7 +64,13 @@ export function analyseTerraformModule(dep: PackageDependency): void {
     dep.datasource = BitBucketTagsDatasource.id;
   } else if (gitTagsRefMatch?.groups) {
     dep.depType = 'module';
-    if (gitTagsRefMatch.groups.path.includes('//')) {
+    dep.currentValue = gitTagsRefMatch.groups.tag;
+    dep.datasource = GitTagsDatasource.id;
+    if (azureDevOpsSshRefMatch?.groups) {
```
Comment (viceice) [inline lib/modules/manager/terraform/modules.ts:69]: shouldn't we lift this before normal tags match? like we do for GitHub and bitbucket ...

Comment (MaronHatoum) [reply lib/modules/manager/terraform/modules.ts:69]: I think it doesn't matter because now we will set `currentValue` to `gitTagsRefMatch.groups.tag` and if the URL is `azure` URL we will change the value.

Comment (viceice) [reply lib/modules/manager/terraform/modules.ts:69]: sure, but code seems to look cleaner and less nested then

Comment (MaronHatoum) [reply lib/modules/manager/terraform/modules.ts:69]: sure, so do you want me to revert the last changes? to return these two lines above after normal tags?

Comment (viceice) [reply lib/modules/manager/terraform/modules.ts:69]: yes, i think best place it between bitbucket tags and git tags conditions.

**Comment by MaronHatoum** [comment]
can you please tell me if are any more changes needed here?

**Review by viceice — APPROVED** [review]
