### PR TITLE
fix(datasource): rename `adoptium-java` to `java-version`

### LINKED ISSUE #20234: Rename `adoptium-java` datasource to `java-version`
### What would you like Renovate to be able to do?

We should do this to be in line with our other datasources.
- #20233

### If you have any ideas on how this should be implemented, please tell us here.

just rename and migrate

### Is this a feature you are interested in implementing yourself?

Maybe

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- rename and migrate datasource `adoptium-java` to `java-version`

## Context
- Closes: #20234 

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by RahulGautamSingh** [comment]
Blocked by : #20244
Duplicated fns so merging one will cause conflict in other. Hence waiting.

File: lib/modules/datasource/java-version/index.ts [hunk 1]
```diff
@@ -55,8 +55,7 @@ export class AdoptiumJavaDatasource extends Datasource {
     namespace: `datasource-${datasource}`,
     key: ({ registryUrl, packageName }: GetReleasesConfig) =>
       // TODO: types (#7154)
-      // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
```
Comment (viceice) [inline lib/modules/datasource/java-version/index.ts:58]: please make those changes in separate PR next time

**Review by viceice — APPROVED** [review]
