### PR TITLE
fix(datasource/azure-bicep-resource): accomodate changes to response schema

### LINKED ISSUE #27575: Error in 'azure-bicep-resource' data source due to updates JSON schema
### Discussed in https://github.com/renovatebot/renovate/discussions/27556

<div type='discussions-op-text'>

<sup>Originally posted by **NicolasBissig** February 26, 2024</sup>
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:37-slim

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

## Description

Currently, the `azure-bicep-resource` data source on the self-hosted docker version always fails and thus dependencies are not updated.

## Cause

It seems that the bicep `index.json` got a new format between these two commits:

https://github.com/Azure/bicep-types-az/blob/326b3589f201db73cbd08e3060f952eb931b487f/generated/index.json
https://github.com/Azure/bicep-types-az/blob/6b9843ae1ff0c3aa642e24411e50c467d1fbb697/generated/index.json

Here the field `Resources` got renamed to `resources`, and the field `Functions` to `resourceFunctions`
Also, the `$ref` elements got introduced.

## Reproduce

I tried to reproduce the issue [here](https://github.com/NicolasBissig/renovate-bicep-reproduce) but with the GitHub version it seems to work.
I cannot publicly share a repository of our GitLab Instance.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Datasource unknown error (repository=[REDACTED])
       "datasource": "azure-bicep-resource",
       "packageName": "Microsoft.Web/sites",
       "err": {
         "message": "Schema error",
         "stack": "ZodError: Schema error\n    at Object.get error [as error] (/usr/local/renovate/node_modules/.pnpm/zod@3.22.4/node_modules/zod/lib/types.js:43:31)\n    at ZodEffects.parseAsync (/usr/local/renovate/node_modules/.pnpm/zod@3.22.4/node_modules/zod/lib/types.js:166:22)\n    at Http.requestJson (/usr/local/renovate/lib/util/http/index.ts:369:18)\n    at AzureBicepResourceDatasource.getResourceVersionIndex (/usr/local/renovate/lib/modules/datasource/azure-bicep-resource/index.ts:63:22)\n    at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n    at AzureBicepResourceDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/azure-bicep-resource/index.ts:42:34)\n    at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n    at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:296:13)\n    at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:116:56)\n    at withLookupStats (/usr/local/renovate/lib/workers/repository/process/fetch.ts:28:18)\n    at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:72:42)\n    at /usr/local/renovate/lib/workers/repository/process/fetch.ts:118:23\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
         "issues": {"Resources": "Required", "Functions": "Required"}
       }
DEBUG: Failed to look up azure-bicep-resource package Microsoft.Web/sites (repository=[REDACTED], packageFile=bicep/functionApp.bicep, dependency=Microsoft.Web/sites)
```

</details>

### Have you created a minimal reproduction repository?

https://github.com/renovate-reproductions/27556

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
In the ZodSchema replace 
- `Resources` -> `resources`
- `Functions` -> `resourceFunctions`
- `{ RelativePath, Index }` -> `{ $ref }`

## Context
Closes: https://github.com/renovatebot/renovate/issues/27575

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository https://github.com/RahulGautamSingh-testing/renovate-bicep-reproduce/pulls

### CODE REVIEW

File: lib/modules/datasource/azure-bicep-resource/schema.ts [hunk 1]
```diff
@@ -2,37 +2,35 @@ import { z } from 'zod';
...
 export const BicepResourceVersionIndex = z
   .object({
-    Resources: z.record(
+    resources: z.record(
       z.string(),
       z.object({
-        RelativePath: z.string(),
-        Index: z.number(),
+        $ref: z.string(),
       }),
```
Comment (zharinov) [inline lib/modules/datasource/azure-bicep-resource/schema.ts:9]: As far as we're only concerned with `resources` keys, its scheme should be `z.record(z.string(), z.unknown())`

File: lib/modules/datasource/azure-bicep-resource/schema.ts [hunk 2]
```diff
@@ -2,37 +2,35 @@ import { z } from 'zod';
...
     ),
-    Functions: z.record(
+    resourceFunctions: z.record(
       z.string(),
       z.record(
         z.string(),
         z.array(
```
Comment (zharinov) [inline lib/modules/datasource/azure-bicep-resource/schema.ts:15]: This array should be replaced with `z.unknown()`, if we're going to ignore it and only use the keys from upper-level record.

**Review by zharinov — CHANGES_REQUESTED** [review]

**Review by zharinov — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
