### PR TITLE
fix(kustomize): accept kustomization files without header

### LINKED ISSUE #14524: Renovate ignores Kustomization files without header
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.94.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.8.2

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate currently ignores Kustomization files that don't specify the resource type `Kustomization` or `Component`.

The type might have been required in early Kustomize versions, but nowadays it's usually left out (see e.g. [official Kubernetes documentation](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/)):

A `kustomization.yaml` such as below is totally valid and should be accepted by Renovate:

```yaml
resources:
- deployment.yaml
- ...
```

I suggest to just get rid of the check:

https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/kustomize/extract.ts#L136-L138

### Relevant debug logs

n/a

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by fgreinacher**
## Changes

Changes the behavior of the kustomize manager to accept a missing header and assume the default resource kind `Kustomization`.

## Context

Fixes #14524

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

🛠 with ❤️ by [Siemens](https://opensource.siemens.com/)

### CODE REVIEW

File: lib/modules/manager/kustomize/extract.ts [hunk 1]
```diff
@@ -133,7 +133,12 @@ export function parseKustomize(content: string): Kustomize | null {
     return null;
   }
 
-  if (!['Kustomization', 'Component'].includes(pkg.kind)) {
+  const pkgKindKustomization = 'Kustomization';
+  const pkgKindComponent = 'Component';
+
+  pkg.kind = pkg.kind || pkgKindKustomization;
+
+  if (![pkgKindKustomization, pkgKindComponent].includes(pkg.kind)) {
```
Comment (viceice) [inline lib/modules/manager/kustomize/extract.ts:141]:
```suggestion
  if (is.string(pkg.kind) && !['Kustomization', 'Component'].includes(pkg.kind)) {
```

Simplify

Comment (fgreinacher) [reply lib/modules/manager/kustomize/extract.ts:141]: I guess this would break the fallback logic right? We want the correct `depType`.

Comment (fgreinacher) [reply lib/modules/manager/kustomize/extract.ts]: @viceice OK, done!

**Review by rarkins — APPROVED** [review]
