### PR TITLE
fix(renovate-config-validator): add validate presets to the validator

### LINKED ISSUE #15999: Configuration Validator does not detect errors when bad presets used
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.65 + latest

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.9.3

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Using the following sample configuration
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    "foo"
  ]
}
```

Renovate parser correctly *FAILS* when processing the Renovate configuration file as `foo` is not a valid preset value.
However the configuration validator tool passes with the same configuration.

## Fails as intended
During procesing it fails correctly with validation error: `Cannot find preset's package (foo)`
```sh
docker run --rm -v $PWD/renovate.json5:/usr/src/app/renovate.json5 -e RENOVATE_TOKEN=token -e RENOVATE_REPOSITORIES=repo-path -it renovate/renovate
```

## Passes using the validator
The config validator tool does not detect the bad configuration but it
```sh
docker run --rm -v $PWD/renovate.json5:/usr/src/app/renovate.json5 -e RENOVATE_TOKEN=token -e RENOVATE_REPOSITORIES=repo-path -it renovate/renovate renovate-config-validator
```

> Bad configuration fields not added to the `extends` preset section seem to be detected correctly.

## Reproduction 
[Reproduction Repo](https://github.com/Nithos/renovate-bug.git)

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes

added validate presets to the config-validator class where we can validate if all presets in the extends actually exist.

## Context

Closes #15999

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/config/validation.ts [hunk 1]
```diff
@@ -269,6 +269,14 @@ export async function validateConfig(
             if (key === 'extends') {
               for (const subval of val) {
                 if (is.string(subval)) {
+                  try {
+                    await getPreset(subval, config);
+                  } catch (e) {
```
Comment (viceice) [inline lib/config/validation.ts:274]: we need to differenciate the error. it should be at least logged as warning

File: lib/config/validation.ts [hunk 2]
```diff
@@ -269,6 +269,14 @@ export async function validateConfig(
             if (key === 'extends') {
               for (const subval of val) {
                 if (is.string(subval)) {
```
Comment (viceice) [inline lib/config/validation.ts:271]: do we issue an error for non string presets?

Comment (PhilipAbed) [reply lib/config/validation.ts:271]: yes we give an error in case its an int or something else. it must be a string!

File: lib/config/validation.ts (hunk 1 above)
Comment (PhilipAbed) [reply lib/config/validation.ts:274]: you can see examples in the issue https://github.com/renovatebot/renovate/issues/15999

Comment (PhilipAbed) [reply lib/config/validation.ts:274]: @viceice what do you mean Differentiate the error? if we catch the error it will show as Preset not found error,
it gets logged anyway because im pushing it into `errors`

Comment (viceice) [reply lib/config/validation.ts:274]: yes, log it. as it can be a 404 or invalid json or any other error. so a user should be able to dig and fix the cause

**Review by viceice — COMMENTED** [review]
see comment

**Comment by PhilipAbed** [comment]
@viceice what comment? i solved them all

File: lib/config/validation.ts [hunk 3]
```diff
@@ -269,6 +270,18 @@ export async function validateConfig(
...
+                  try {
+                    await getPreset(subval, config);
+                  } catch (err) {
+                    logger.warn(
+                      { err },
+                      `Preset Error while validating ${subval}`
```
Comment (rarkins) [inline lib/config/validation.ts:278]: Avoid using templates within a warning log message. Otherwise it's not easy to group/aggregate these warnings together on the backend. Put it in metadata instead.

```suggestion
                      `Could not resolve preset during config validation`
```

**Review by rarkins — CHANGES_REQUESTED** [review]

**Comment by rarkins** [comment]
Do we know if there was a reason we *didn't* do preset resolution during config validation before?

Two possible risks:
- Maybe private presets fail at this point?
- Do we have adequate caching so that this doesn't slow us down with duplicate resolution calls?

File: lib/config/validation.ts [hunk 4]
```diff
@@ -269,6 +270,18 @@ export async function validateConfig(
             if (key === 'extends') {
               for (const subval of val) {
                 if (is.string(subval)) {
+                  try {
+                    await getPreset(subval, config);
+                  } catch (err) {
+                    logger.warn(
+                      { err },
```
Comment (viceice) [inline lib/config/validation.ts:277]:
```suggestion
                      { err, preset: subval },
```

**Comment by viceice** [comment]
> Do we know if there was a reason we _didn't_ do preset resolution during config validation before?
> 
> Two possible risks:
> 
> * Maybe private presets fail at this point?
> * Do we have adequate caching so that this doesn't slow us down with duplicate resolution calls?

Yes, private presets will fail. But we officially don't support private presets? Because it's very complicated to get hostrules before preset validation?

On config validator there is currently no options to configure any hostrules, so any private access fails.
So at least the catch block needs to differentiate bewteen not found and access denied. I'm not sure if the `getPreset` is throwing any of those error and instead always throws a generic `preset-not-found` error.

**Comment by PhilipAbed** [comment]
@rarkins i'm not sure about caching, imo i dont think its necessary if its just a preset check, 
and lets  say i want to add extra caching, how do i do it in this case im not sure

**Comment by rarkins** [comment]
We already resolve presets later on. Now you resolve them during validation too. If uncached then it would be inefficient, so we can't merge this without thinking about that. 

Another possibility would be making changes to the validation CLI only? Eg keep as is but then resolve the config once it passes validation?

**Comment by PhilipAbed** [comment]
@rarkins we dont resolve them twice, 
we do it once, when failed, it goes to throw an exception, we handle that exception by creating an issue of `Fix Configuration`
the same one i screenshotted in the issue itself.

**Comment by rarkins** [comment]
And what if it doesn't fail? Then it will resolve twice for the 99.99% which pass validation

**Comment by PhilipAbed** [comment]
makes sense, should i create an app cache, like some Static variable that holds a map of presets and if they succeeded or not?

**Comment by PhilipAbed** [comment]
how do u suggest the best way to do it?

**Comment by PhilipAbed** [comment]
@rarkins 
https://github.com/renovatebot/renovate/blob/3c8d1d6076e2e776ebc366274e97198d9e69bce4/lib/config/presets/index.ts#L222-L232
its already there. nothing needs to be done

**Comment by PhilipAbed** [comment]
@viceice  

presets already throw all kinds of errors, do you think there's some other type of error that we are missing? 

https://github.com/renovatebot/renovate/blob/1b36708c640da6e4648cc6142f8f6f3fefdc834b/lib/config/presets/index.ts#L367-L395

any more changes needed here?

**Comment by nabeelsaabna** [comment]
@PhilipAbed can you please list all test you did ?
any mistake in this PR will cause thousands of issues to be created..

**Comment by PhilipAbed** [comment]
is there any reason you would think that?

i have added only 1 unit test `validates if presets exist`

and i tried this on 2 real repositories one that failed and one that didn't fail 

all seemed fine.

**Comment by rarkins** [comment]
Needs testing with private presets which *works* too

**Comment by PhilipAbed** [comment]
@rarkins does `github> merge-confidence/beta` considered private?

**Comment by rarkins** [comment]
No, I meant a private repo depending on another private repo preset

File: lib/config/validation.ts [hunk 5]
```diff
@@ -269,6 +270,18 @@ export async function validateConfig(
             if (key === 'extends') {
               for (const subval of val) {
                 if (is.string(subval)) {
+                  try {
+                    await getPreset(subval, config);
+                  } catch (err) {
+                    logger.warn(
+                      { err, preset: subval },
+                      `Could not resolve preset during config validation`
+                    );
```
Comment (viceice) [inline lib/config/validation.ts:279]:
```suggestion
                    logger.debug(
                      { err, preset: subval },
                      `Could not resolve preset during config validation`
                    );
```

i think we don't need to warn here if we pass an error below?

**Comment by PhilipAbed** [comment]
@rarkins i did 2 private repos on my account,

one of them i copied the merge-confidence but changed names, i extended it in the renovate.json like this:
```
{
"extends": [
    "github>StinkyLord/mergeconfidence:ren"
  ]
}
```

and it worked fine no issues at all

what were you expecting could happen?
or did i do a wrong test?

**Review by viceice — APPROVED** [review]
🤷‍♂️

**Review by rarkins — APPROVED** [review]
