### PR TITLE
fix(repology): Properly handle of response with multiple package versions

### LINKED ISSUE #8482: Repology datasource fails to retrieve version info in case of multiple versions
**What Renovate type, platform and version are you using?**

Self hosted, based on renovate cli packages as docker image

**Describe the bug**

Right now repology datasource supports only scenarious when single version for package is returned (see [code for details](https://github.com/renovatebot/renovate/blob/master/lib/datasource/repology/index.ts#L212)). While this does makes sense overal (as os repos does not usually keep old versions), this leads to failures in resolution when repology still contains information about more than one package version (see debug logs)

**Relevant debug logs**

```
WARN: Repology lookup returned ambiguous results, ignoring... (repository=.....)
      "repoName": "centos_8",
      "pkgName": "java-11-openjdk",
      "packageTypes": ["binname", "srcname"],
      "pkgs": [
        {
          "repo": "centos_8",
          "subrepo": "AppStream",
          "srcname": "java-11-openjdk",
          "visiblename": "java-11-openjdk",
          "version": "11.0.7.10",
          "maintainers": ["bugs@centos.org"],
          "licenses": [
            "ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib and ISC and FTL and RSA"
          ],
          "www": ["http://openjdk.java.net/"],
          "summary": "OpenJDK Runtime Environment 11",
          "categories": ["Development/Languages"],
          "status": "noscheme",
          "origversion": "1:11.0.7.10-1.el8_1"
        },
        {
          "repo": "centos_8",
          "subrepo": "AppStream",
          "srcname": "java-11-openjdk",
          "visiblename": "java-11-openjdk",
          "version": "11.0.8.10",
          "maintainers": ["bugs@centos.org"],
          "licenses": [
            "ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib and ISC and FTL and RSA"
          ],
          "www": ["http://openjdk.java.net/"],
          "summary": "OpenJDK Runtime Environment 11",
          "categories": ["Development/Languages"],
          "status": "noscheme",
          "origversion": "1:11.0.8.10-0.el8_2"
        },
        {
          "repo": "centos_8",
          "subrepo": "AppStream",
          "srcname": "java-11-openjdk",
          "visiblename": "java-11-openjdk",
          "version": "11.0.8.10",
          "maintainers": ["bugs@centos.org"],
          "licenses": [
            "ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib and ISC and FTL and RSA"
          ],
          "www": ["http://openjdk.java.net/"],
          "summary": "OpenJDK Runtime Environment 11",
          "categories": ["Development/Languages"],
          "status": "noscheme",
          "origversion": "1:11.0.8.10-6.el8"
        },
        {
          "repo": "centos_8",
          "subrepo": "AppStream",
          "srcname": "java-11-openjdk",
          "visiblename": "java-11-openjdk",
          "version": "11.0.9.11",
          "maintainers": ["bugs@centos.org"],
          "licenses": [
            "ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib and ISC and FTL and RSA"
          ],
          "www": ["http://openjdk.java.net/"],
          "summary": "OpenJDK Runtime Environment 11",
          "categories": ["Development/Languages"],
          "status": "noscheme",
          "origversion": "1:11.0.9.11-0.el8_2"
        },
        {
          "repo": "centos_8",
          "subrepo": "AppStream",
          "srcname": "java-11-openjdk",
          "visiblename": "java-11-openjdk",
          "version": "11.0.9.11",
          "maintainers": ["bugs@centos.org"],
          "licenses": [
            "ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib and ISC and FTL and RSA"
          ],
          "www": ["http://openjdk.java.net/"],
          "summary": "OpenJDK Runtime Environment 11",
          "categories": ["Development/Languages"],
          "status": "noscheme",
          "origversion": "1:11.0.9.11-2.el8_3"
        },
        {
          "repo": "centos_8",
          "subrepo": "AppStream",
          "srcname": "java-11-openjdk",
          "visiblename": "java-11-openjdk",
          "version": "11.0.9.11",
          "maintainers": ["bugs@centos.org"],
          "licenses": [
            "ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib and ISC and FTL and RSA"
          ],
          "www": ["http://openjdk.java.net/"],
          "summary": "OpenJDK Runtime Environment 11",
          "categories": ["Development/Languages"],
          "status": "noscheme",
          "origversion": "1:11.0.9.11-3.el8_3"
        }
      ]
renovate_1  | DEBUG: Repository or package not found on Repology (repository=.....)
      "repoName": "centos_8",
      "pkgName": "java-11-openjdk"
renovate_1  | DEBUG: Failed to look up dependency centos_8/java-11-openjdk (repository=....., packageFile=buildsystem/prepare.yml, dependency=centos_8/java-11-openjdk)
```

**Have you created a minimal reproduction repository?**

Not yet, but if it will help -- I can do it.

**Additional context**

I think that it makes sense to allow retrieving all found versions, but also don't mind to have some config option for alternative behavior, e.g. "return-latest-if-found-more-than-one".

### PR DESCRIPTION
**Pull request by zeldigas**
## Changes:

Some repos available in repology api produce multiple versions, and while not all of them can be downloaded, it should not result in invalid result at all. Instead all found versions that match criteria should be returned from data source just like in more regular one like npm or maven.

This change adjust handling of multiple returned versions and produce all of them as result after filtering by repo and package types

## Context:

Closes #8482 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
@danez could you also add your review?

File: lib/datasource/repology/index.ts [hunk 1]
```diff
@@ -209,8 +210,10 @@ export async function getReleases({
 
     // Always prefer origversion if available, otherwise default to version
     // This is required as source packages usually have no origversion
-    const version = pkg.origversion ?? pkg.version;
-    return { releases: [{ version }] };
+    const version = pkg.map((item) => ({
+      version: item.origversion ?? item.version,
+    }));
+    return { releases: version };
```
Comment (danez) [inline lib/datasource/repology/index.ts:216]:
```suggestion
    const releases = pkg.map((item) => ({
      version: item.origversion ?? item.version,
    }));
    return { releases };
```

File: lib/datasource/repology/index.ts [hunk 2]
```diff
@@ -163,10 +164,10 @@ async function queryPackage(
 async function getCachedPackage(
   repoName: string,
   pkgName: string
-): Promise<RepologyPackage> {
+): Promise<RepologyPackage[]> {
   // Fetch previous result from cache if available
   const cacheKey = `${repoName}/${pkgName}`;
-  const cachedResult = await packageCache.get<RepologyPackage>(
+  const cachedResult = await packageCache.get<RepologyPackage[]>(
```
Comment (danez) [inline lib/datasource/repology/index.ts:170]: Is it okay to change the data type in the cache? Or does it need to have some migration code to handle the old cache? I'm not sure about this so this is a question for the maintainers, but I think this might break if someone has an old cache. Or is the cache invalidated on every reonvate update?

**Review by danez — COMMENTED** [review]
I checked the API and it indeed returns multiple versions for the same exact package. So overall this sounds good. Added one minor comment and another question about the caching which I'm not sure it will work.

File: lib/datasource/repology/index.ts (hunk 2 above)
Comment (rarkins) [reply lib/datasource/repology/index.ts:170]: Yes, it would be best to change the `cacheKey` contents so that old formats are not returned. Either that or detecting if the returned value isn't an array and converting it.

Comment (zeldigas) [reply lib/datasource/repology/index.ts:170]: Do you have any preference? Changing cache key is of course simplest approach, but if you feel it's worth keeping it and handle non-array values I'm fine to try to do it.

Comment (zeldigas) [reply lib/datasource/repology/index.ts:170]: Ok, I decided to be on a safe side for version rollbacks and change cache key

**Comment by rarkins** [comment]
Can someone test this on a real repo first before we merge?

**Comment by zeldigas** [comment]
@rarkins  are you looking for real project or test repository showing that it change works properly will do?

**Comment by rarkins** [comment]
Test repository is fine, as long as it validates both list and non-list return types

**Comment by zeldigas** [comment]
@rarkins test repository - https://github.com/zeldigas/renovate-repology

It has 2 packages to update - version of jdk in alpine (worked prior to PR as repology returns one version) and version of jdk for centos_8 (does not work without PR). 

Right now it works (see associated PRs). Log can be found here: https://pastebin.com/FMTLW4JZ

**Comment by rarkins** [comment]
Thanks, @zeldigas
