### PR TITLE
fix: requirements.txt extras

### LINKED ISSUE #2720: Support pip extras
Ref: https://github.com/renovatebot/config-help/issues/120

### PR DESCRIPTION
**Pull request by kayoub5**
Closes  #2720

### CODE REVIEW

File: lib/manager/pip_requirements/update.js [hunk 1]
```diff
@@ -7,10 +7,7 @@ function updateDependency(fileContent, upgrade) {
     logger.debug(`pip_requirements.updateDependency(): ${upgrade.newValue}`);
     const lines = fileContent.split('\n');
     const oldValue = lines[upgrade.lineNumber];
-    const newValue = oldValue.replace(
-      /^.+?(\s.*)?$/,
-      `${upgrade.depName}${upgrade.newValue}$1`
-    );
+    const newValue = oldValue.replace(upgrade.currentValue, upgrade.newValue);
```
Comment (rarkins) [inline lib/manager/pip_requirements/update.js]: This will fail in some circumstances. e.g. let's say currentValue is `==1.0.0` and there is an open PR to upgrade to `==1.0.1`. Next, `1.1.0` is released. The above substitution will fail because it will try to replace `1.0.0` with `1.1.0` but actually the branch's `requirements.txt` will contain `1.0.1`.

Comment (rarkins) [reply lib/manager/pip_requirements/update.js]: We instead need to replace "whatever the current value is in this line";

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/manager/pip_requirements/update.js (hunk 1 above)
Comment (kayoub5) [reply lib/manager/pip_requirements/update.js]: Isn't extract and update ran on the same file content?

**Comment by kayoub5** [comment]
@rarkins done
