### PR TITLE
fix(git): Trim whitespace around private key data

### LINKED ISSUE #9855: Git GPG private keys with trailing whitespace result in obscure GPG error
**What Renovate type, platform and version are you using?**

Renovate on self hosted GitLab, using version 1.6.0 of the `renovate-runner` repository.

**Describe the bug**

When adding a GPG private key for signing Git commits, if one includes a trailing newline in the private key, importing the GPG key fails with an obscure error.

**Relevant logs**

<details><summary>Click me to see logs</summary>

```
"err": {
         "killed": false,
         "code": 2,
         "signal": null,
         "cmd": "gpg --import /tmp/git-private.key",
         "stdout": "",
         "stderr": "gpg: directory '/home/ubuntu/.gnupg' created\ngpg: keybox '/home/ubuntu/.gnupg/pubring.kbx' created\ngpg: /home/ubuntu/.gnupg/trustdb.gpg: trustdb created\ngpg: key <some pubkey ID>: public key \"Redacted\" imported\ngpg: key <some pubkey ID>: error sending to agent: Inappropriate ioctl for device\ngpg: error building skey array: Inappropriate ioctl for device\ngpg: error reading '/tmp/git-private.key': Inappropriate ioctl for device\ngpg: import from '/tmp/git-private.key' failed: Inappropriate ioctl for device\ngpg: Total number processed: 0\ngpg:               imported: 1\ngpg:       secret keys read: 1\n",
         "message": "Command failed: gpg --import /tmp/git-private.key\ngpg: directory '/home/ubuntu/.gnupg' created\ngpg: keybox '/home/ubuntu/.gnupg/pubring.kbx' created\ngpg: /home/ubuntu/.gnupg/trustdb.gpg: trustdb created\ngpg: key DAAE4652066BB029: public key \"Redacted\" imported\ngpg: key <some pubkey ID>: error sending to agent: Inappropriate ioctl for device\ngpg: error building skey array: Inappropriate ioctl for device\ngpg: error reading '/tmp/git-private.key': Inappropriate ioctl for device\ngpg: import from '/tmp/git-private.key' failed: Inappropriate ioctl for device\ngpg: Total number processed: 0\ngpg:               imported: 1\ngpg:       secret keys read: 1\n",
         "stack": "Error: Command failed: gpg --import /tmp/git-private.key\ngpg: directory '/home/ubuntu/.gnupg' created\ngpg: keybox '/home/ubuntu/.gnupg/pubring.kbx' created\ngpg: /home/ubuntu/.gnupg/trustdb.gpg: trustdb created\ngpg: key DAAE4652066BB029: public key \"Redacted\" imported\ngpg: key <some pubkey ID>: error sending to agent: Inappropriate ioctl for device\ngpg: error building skey array: Inappropriate ioctl for device\ngpg: error reading '/tmp/git-private.key': Inappropriate ioctl for device\ngpg: import from '/tmp/git-private.key' failed: Inappropriate ioctl for device\ngpg: Total number processed: 0\ngpg:               imported: 1\ngpg:       secret keys read: 1\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:467:12)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
       }
```

</details>

**Have you created a minimal reproduction repository?**

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I have a PR ready that trims the string before parsing. I'm opening this issue to provide the context for that one.

### PR DESCRIPTION
**Pull request by DCKcode**
## Changes:

When parsing a Git private key, remove any leading and trailing whitespace that may be present.

## Context:

Fixes #9855 .

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by DCKcode** [comment]
If you need test cases for this, I'd be happy to looking into providing those. Before I do, let me know if this solution would be acceptable.

**Review by rarkins — DISMISSED** [review]

File: lib/util/git/private-key.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ let gitPrivateKey: string;
 let keyId: string;
 
 export function setPrivateKey(key: string): void {
-  gitPrivateKey = key;
+  gitPrivateKey = key.trim();
```
Comment (viceice) [inline lib/util/git/private-key.ts:12]:
```suggestion
  gitPrivateKey = key?.trim();
```

**Review by viceice — CHANGES_REQUESTED** [review]

**Review by viceice — APPROVED** [review]

**Comment by DCKcode** [comment]
Thanks all for fixing my crappy code 😄
