### PR TITLE
fix(github): skip forked repos when in fork mode

### LINKED ISSUE #27683: Skip repo when running in fork mode if the repo itself is a fork
### Describe the proposed change(s).

The problem is that each account/org in GitHub can have only one fork of a repo. e.g. let's say repo A exists and is forked to repo B. If both A and B are installed into Renovate when in forking mode, they'll "share" a single forked repo C, and it won't work.

Renovate should abort early if forkToken is in use and repo.isFork=true.

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Adds logic to ensure that forked repos are always skipped when Renovate is running in forking mode. 

## Context

Closes #27683

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/git/index.ts [hunk 1]
```diff
@@ -585,7 +585,7 @@ export async function getFileList(): Promise<string[]> {
 }
 
 export function getBranchList(): string[] {
-  return Object.keys(config.branchCommits);
+  return Object.keys(config.branchCommits ?? /* istanbul ignore next */ {});
```
Comment (rarkins) [inline lib/util/git/index.ts:588]: I discovered this bug while using an invalid forkToken, it threw a fatal error so fixing it here

**Comment by rarkins** [comment]
@nabeelsaabna this will mean that the hosted app no longer needs to set includeForks=false

**Review by viceice — APPROVED** [review]
