### PR TITLE
fix(manager/regex): depName requirement if using the recursive strategy

### LINKED ISSUE #16213: Regex manager requires depName group when using recursive matching strategy
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v32.94.0

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When using regex manager with recursive matching strategy, it does not behave the way described in the [documentation](https://docs.renovatebot.com/modules/manager/regex/#required-fields). The documentation suggests it should be enough to specify `currentValue` capture group and add the `depNameTemplate` field, but that does not work when trying to match 

```
jacoco {
    toolVersion = "0.8.7"
}
```

with

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:base"],
  "regexManagers": [
    {
      "fileMatch": ["build\\.gradle\\.kts$"],
      "matchStringsStrategy": "recursive",
      "matchStrings": [
        "jacoco\\s*{[^}]*}",
        "toolVersion\\s*=\\s*\"(?<currentValue>\\S*)\"\\s*"
      ],
      "depNameTemplate": "org.jacoco:jacoco",
      "datasourceTemplate": "maven"
    }
  ]
}
```

It works when a dummy `depName` capture group is specified and overriden with `depNameTemplate`. 

Looking at the code of regex manager, [this condition](https://github.com/renovatebot/renovate/blob/84228b1b12a9926e1019b6030519c02665c09b61/lib/modules/manager/regex/strategies.ts#L67) seems to be redundant. It requires `depName` goup to be specified, and short-circuits the further processing when `currentValue` is found. I would expect the code to run through all the match strings and then to call `createDependency` with all the groups found.

The reproduction repository: https://github.com/Xrixcis/renovate-regex-recursive-issue

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by secustor**
## Changes
Workthrough all `matchStrings` and then create the dependency.     
To keep the current behaviour dependencies are filtered if they have no `depName` or `currentValue` after the template fields are processed. 
 

## Context
- Closes #16213

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

https://github.com/secustor/renovate-16213

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
still having issues with android app review 😕

File: lib/modules/manager/regex/strategies.ts [hunk 1]
```diff
@@ -22,7 +23,8 @@ export function handleAny(
         config
       )
     )
-    .filter(is.truthy);
+    .filter(is.truthy)
+    .filter(isValidDependency);
```
[the remark this answers is not in the document]
Comment (secustor) [reply lib/modules/manager/regex/strategies.ts:27]: This way the test result have not to be adapted in the same step.     
But yes, I agree it would be better to add a `skipReason` for debugging purposes. IMO this should be then changed in a second PR.

File: lib/modules/manager/regex/utils.ts [hunk 2]
```diff
@@ -97,3 +97,10 @@ export function mergeExtractionTemplate(
     replaceString: addition.replaceString ?? base.replaceString,
   };
 }
+
+export function isValidDependency(dep: PackageDependency): boolean {
+  // check if all the fields are set
+  return !['depName', 'currentValue'].some(
+    (value) => !dep[value as keyof PackageDependency]
+  );
```
Comment (viceice) [inline lib/modules/manager/regex/utils.ts:105]: can't we directly check the two fields, that code looks too ugly and hides type checks.

Comment (secustor) [reply lib/modules/manager/regex/utils.ts]: I have changed it to direct checks, but my thought has been that at some point there will be a list of minimal values which could then replace the static array.

File: lib/modules/manager/regex/strategies.ts [hunk 3]
```diff
@@ -59,21 +63,17 @@ export function handleRecursive(
...
   if (!regexes[index]) {
-    return [];
+    const result = createDependency(
+      {
+        groups: combinedGroups,
+        replaceString: content,
+      },
+      config
+    );
+    return result ? [result] : [];
```
Comment (viceice) [inline lib/modules/manager/regex/strategies.ts:73]: doesn't need this validated as dep too?

File: lib/modules/manager/regex/utils.ts [hunk 4]
```diff
@@ -97,3 +97,11 @@ export function mergeExtractionTemplate(
     replaceString: addition.replaceString ?? base.replaceString,
   };
 }
+
+export function isValidDependency({
+  depName,
+  currentValue,
+}: PackageDependency): boolean {
+  // check if all the fields are set
+  return Boolean(depName) && Boolean(currentValue);
```
Comment (viceice) [inline lib/modules/manager/regex/utils.ts:106]: use `is.string` instead, probably `isNonEmptyOrWhitespaveString`

@HonkingGoose we should add a best practices to not use `Boolean` ans use `is` functions instead

Comment (HonkingGoose) [reply lib/modules/manager/regex/utils.ts:106]: See PR:

- https://github.com/renovatebot/renovate/pull/16573

File: lib/modules/manager/regex/utils.ts [hunk 5]
```diff
@@ -97,3 +98,14 @@ export function mergeExtractionTemplate(
...
 }
+
+export function isValidDependency({
+  depName,
+  currentValue,
+}: PackageDependency): boolean {
+  // check if all the fields are set
+  return (
+    is.nonEmptyStringAndNotWhitespace(depName) &&
+    is.nonEmptyStringAndNotWhitespace(currentValue)
```
Comment (viceice) [inline lib/modules/manager/regex/utils.ts:109]: i think we should check for `currentValue` or `currentDigest`. for some datasource the current value is optional.

File: lib/modules/manager/regex/index.spec.ts [hunk 6]
```diff
@@ -323,6 +323,19 @@ describe('modules/manager/regex/index', () => {
     expect(res).toBeNull();
   });
 
+  it('return null with recursive strategy if matchStrings is empty', async () => {
+    const config: CustomExtractConfig = {
+      matchStrings: [],
```
[the remark this answers is not in the document]
Comment (secustor) [reply lib/modules/manager/regex/index.spec.ts]: This is already tested in validation https://github.com/renovatebot/renovate/blob/main/lib/config/validation.spec.ts#L332

[the remark this answers is not in the document]
Comment (viceice) [reply lib/modules/manager/regex/index.spec.ts]: so this test should never happen on runtime

File: lib/modules/manager/regex/utils.ts [hunk 7]
```diff
@@ -97,3 +98,16 @@ export function mergeExtractionTemplate(
...
+export function isValidDependency({
+  depName,
+  currentValue,
+  currentDigest,
+}: PackageDependency): boolean {
+  // check if all the fields are set
+  return (
+    (is.nonEmptyStringAndNotWhitespace(depName) ||
+      is.nonEmptyStringAndNotWhitespace(currentDigest)) &&
+    is.nonEmptyStringAndNotWhitespace(currentValue)
```
Comment (viceice) [inline lib/modules/manager/regex/utils.ts:111]:
```suggestion
    is.nonEmptyStringAndNotWhitespace(depName) &&
    (is.nonEmptyStringAndNotWhitespace(currentDigest) ||
    is.nonEmptyStringAndNotWhitespace(currentValue))
```
Seems to more logical to me

Comment (secustor) [reply lib/modules/manager/regex/utils.ts]: :man_facepalming:

**Review by viceice — APPROVED** [review]
