### PR TITLE
fix: set conflict status on commit

### LINKED ISSUE #17320: Cached isBranchConflicted result is not set after new git push
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

source

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When a branch becomes conflicted, the cached `getCachedConflictResult()` correctly returns `null`. Renovate then uses `git` to determine that the branch is indeed conflicted, and updates the cached conflicted status to be `true` with the new SHA by calling `setCachedConflictResult()`.

However if on that run Renovate deconflicts the same branch, the cached value is not updated.

The easiest fix seems to be that Renovate should call `setCachedConflictResult()` after any commit, updating SHAs and setting conflicted to false.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- set branch confllict status on commit

## Context
- Closes: #17320 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/git/conflicts-cache.ts [hunk 1]
```diff
@@ -33,11 +33,13 @@ export function setCachedConflictResult(
   isConflicted: boolean
 ): void {
   const cache = getCache();
-  cache.gitConflicts ??= {};
-  const { gitConflicts } = cache;
+  const { gitConflicts = {} } = cache;
```
Comment (zharinov) [inline lib/util/git/conflicts-cache.ts:36]: If cache object is empty, we'll never store `gitConflicts` in it, isn't it?

**Review by zharinov — CHANGES_REQUESTED** [review]

File: lib/util/git/conflicts-cache.ts (hunk 1 above)
Comment (RahulGautamSingh) [reply lib/util/git/conflicts-cache.ts:36]: Not sure. The cache will be empty first time when branch is created but we will want to store isConflicted -> false .

**Review by rarkins — APPROVED** [review]
