### PR TITLE
fix(manager/github-actions): renovate propose to delete YAML inline comments

### LINKED ISSUE #12260: Renovate's GH Actions updates propose to delete YAML inline comments
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Describe the bug

I think this diff provides a good idea of the bug:

https://github.com/DanySK/Tutorial-GitHub-Actions-Minimal/pull/4/files

Basically, if the version is followed by a comment, Renovate proposes to remove it.`

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: No dangling containers to remove
INFO: Repository started
{
  "renovateVersion": "28.8.2"
}
DEBUG: Using localDir: /mnt/renovate/gh/DanySK/Tutorial-GitHub-Actions-Minimal
DEBUG: Repository cache is valid
DEBUG: initRepo("DanySK/Tutorial-GitHub-Actions-Minimal")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: DanySK/Tutorial-GitHub-Actions-Minimal default branch = master
DEBUG: Using app token for git init
DEBUG: resetMemCache()
DEBUG: Resetting npmrc
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: Checking cached config file name
DEBUG: Existing config file confirmed
DEBUG: Repo is onboarded
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "local>DanySK/renovate-config"
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "local>DanySK/renovate-config"
    ]
  }
}
DEBUG: Setting hostRules from config
DEBUG: Found repo ignorePaths
{
  "ignorePaths": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/examples/**",
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**",
    "**/__fixtures__/**"
  ]
}
DEBUG: detectSemanticCommits()
DEBUG: No vulnerability alerts found
DEBUG: No vulnerability alerts found
DEBUG: findIssue(Dependency Dashboard)
DEBUG: Retrieving issueList
DEBUG: Retrieved 2 issues
DEBUG: Found issue 2
DEBUG: No baseBranches
DEBUG: extract()
DEBUG: Setting current branch to master
DEBUG: Initializing git repository into /mnt/renovate/gh/DanySK/Tutorial-GitHub-Actions-Minimal
DEBUG: git clone completed
{
  "durationMs": 903
}
DEBUG: latest repository commit
{
  "latestCommit": {
    "hash": "b58239cd93281dabf9eebf1cde9797d48e60cef4",
    "date": "2021-10-21T17:41:48+02:00",
    "message": "Update workflow-example.yml",
    "refs": "HEAD -> master, origin/master, origin/HEAD",
    "body": "",
    "author_name": "Danilo Pianini",
    "author_email": "danilo.pianini@unibo.it"
  }
}
DEBUG: latest commit
{
  "branchName": "master",
  "latestCommitDate": "2021-10-21T17:41:48+02:00"
}
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible
DEBUG: Using file match: (^|/)requirements\.ya?ml$ for manager ansible-galaxy
DEBUG: Using file match: (^|/)galaxy\.ya?ml$ for manager ansible-galaxy
DEBUG: Using file match: azure.*pipelines?.*\.ya?ml$ for manager azure-pipelines
DEBUG: Using file match: (^|/)batect(-bundle)?\.yml$ for manager batect
DEBUG: Using file match: (^|/)batect$ for manager batect-wrapper
DEBUG: Using file match: (^|/)WORKSPACE(|\.bazel)$ for manager bazel
DEBUG: Using file match: \.bzl$ for manager bazel
DEBUG: Using file match: (^|/)\.?bitbucket-pipelines\.ya?ml$ for manager bitbucket-pipelines
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite
DEBUG: Using file match: (^|/)Gemfile$ for manager bundler
DEBUG: Using file match: \.cake$ for manager cake
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci
DEBUG: Using file match: (^|/)cloudbuild.ya?ml for manager cloudbuild
DEBUG: Using file match: (^|/)Podfile$ for manager cocoapods
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: Using file match: (^|/|\.)Dockerfile$ for manager dockerfile
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci
DEBUG: Using file match: (^|/).gitmodules$ for manager git-submodules
DEBUG: Using file match: ^(workflow-templates|\.github\/workflows)\/[^/]+\.ya?ml$ for manager github-actions
DEBUG: Using file match: (^|\/)action\.ya?ml$ for manager github-actions
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci-include
DEBUG: Using file match: (^|/)go.mod$ for manager gomod
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle
DEBUG: Using file match: (^|\/)gradle\.properties$ for manager gradle
DEBUG: Using file match: (^|\/)gradle\/.+\.toml$ for manager gradle
DEBUG: Using file match: \.versions\.toml$ for manager gradle
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper
DEBUG: Using file match: (^|/)requirements\.yaml$ for manager helm-requirements
DEBUG: Using file match: (^|/)values.yaml$ for manager helm-values
DEBUG: Using file match: (^|/)helmfile.yaml$ for manager helmfile
DEBUG: Using file match: (^|/)Chart.yaml$ for manager helmv3
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew
DEBUG: Using file match: \.html?$ for manager html
DEBUG: Using file match: (^|/)plugins\.(txt|ya?ml)$ for manager jenkins
DEBUG: Using file match: (^|/)kustomization\.yaml for manager kustomize
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen
DEBUG: Using file match: \.pom\.xml$ for manager maven
DEBUG: Using file match: (^|/)pom\.xml$ for manager maven
DEBUG: Using file match: (^|/)package.js$ for manager meteor
DEBUG: Using file match: (^|/)mix\.exs$ for manager mix
DEBUG: Using file match: (^|/).node-version$ for manager nodenv
DEBUG: Using file match: (^|/)package.json$ for manager npm
DEBUG: Using file match: \.(?:cs|fs|vb)proj$ for manager nuget
DEBUG: Using file match: \.(?:props|targets)$ for manager nuget
DEBUG: Using file match: \.config\/dotnet-tools\.json$ for manager nuget
DEBUG: Using file match: (^|//)global\.json$ for manager nuget
DEBUG: Using file match: (^|/)\.nvmrc$ for manager nvm
DEBUG: Using file match: (^|/)([\w-]*)requirements\.(txt|pip)$ for manager pip_requirements
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup
DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry
DEBUG: Using file match: (^|/)\.pre-commit-config\.yaml$ for manager pre-commit
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub
DEBUG: Using file match: (^|/).python-version$ for manager pyenv
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version
DEBUG: Using file match: \.sbt$ for manager sbt
DEBUG: Using file match: project/[^/]*.scala$ for manager sbt
DEBUG: Using file match: (^|/)setup\.cfg$ for manager setup-cfg
DEBUG: Using file match: (^|/)Package\.swift for manager swift
DEBUG: Using file match: \.tf$ for manager terraform
DEBUG: Using file match: (^|/)\.terraform-version$ for manager terraform-version
DEBUG: Using file match: (^|/)terragrunt\.hcl$ for manager terragrunt
DEBUG: Using file match: (^|/)\.terragrunt-version$ for manager terragrunt-version
DEBUG: Using file match: ^.travis.yml$ for manager travis
DEBUG: Matched 3 file(s) for manager github-actions: .github/workflows/use-step-outputs.yml, .github/workflows/workflow-example.yml, .github/workflows/workflow-matrix.yml
DEBUG: Found github-actions package files
DEBUG: Found 3 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "master",
  "stats": {
    "managers": {
      "github-actions": {
        "fileCount": 3,
        "depCount": 7
      }
    },
    "total": {
      "fileCount": 3,
      "depCount": 7
    }
  }
}
DEBUG: Package releases lookups complete
{
  "baseBranch": "master"
}
DEBUG: branchifyUpgrades
DEBUG: 1 flattened updates found: tj-actions/branch-names
DEBUG: Returning 1 branch(es)
DEBUG: Fetching changelog: https://github.com/tj-actions/branch-names (v5 # An action that has some outputs -> v5)
DEBUG: Not enough valid releases for dep tj-actions/branch-names
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "github-actions": [
      {
        "packageFile": ".github/workflows/use-step-outputs.yml",
        "deps": [
          {
            "depName": "danysk/action-checkout",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "danysk/action-checkout@0.1.0",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # renovate: tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "0.1.0",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/danysk/action-checkout",
            "currentVersion": "0.1.0",
            "fixedVersion": "0.1.0"
          },
          {
            "depName": "tj-actions/branch-names",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "tj-actions/branch-names@v5 # An action that has some outputs",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # renovate: tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v5 # An action that has some outputs",
            "depIndex": 1,
            "updates": [
              {
                "bucket": "patch",
                "newVersion": "v5",
                "newValue": "v5",
                "releaseTimestamp": "2021-09-14T17:47:01.000Z",
                "newMajor": 5,
                "newMinor": null,
                "updateType": "patch",
                "branchName": "renovate/tj-actions-branch-names-5.x"
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/tj-actions/branch-names",
            "currentVersion": "v5 # An action that has some outputs",
            "isSingleVersion": true,
            "fixedVersion": "v5 # An action that has some outputs"
          }
        ]
      },
      {
        "packageFile": ".github/workflows/workflow-example.yml",
        "deps": [
          {
            "depName": "actions/checkout",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "actions/checkout@v2",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # renovate: tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v2",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/actions/checkout",
            "currentVersion": "v2",
            "fixedVersion": "v2"
          },
          {
            "depName": "actions/checkout",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "actions/checkout@v2",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # renovate: tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v2",
            "depIndex": 1,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/actions/checkout",
            "currentVersion": "v2",
            "fixedVersion": "v2"
          }
        ]
      },
      {
        "packageFile": ".github/workflows/workflow-matrix.yml",
        "deps": [
          {
            "depName": "actions/setup-java",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "actions/setup-java@v2",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # renovate: tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v2",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/actions/setup-java",
            "currentVersion": "v2",
            "fixedVersion": "v2"
          },
          {
            "depName": "actions/setup-python",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "actions/setup-python@v2",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # renovate: tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v2",
            "depIndex": 1,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/actions/setup-python",
            "currentVersion": "v2",
            "fixedVersion": "v2"
          },
          {
            "depName": "ruby/setup-ruby",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "ruby/setup-ruby@v1",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # renovate: tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v1",
            "depIndex": 2,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/ruby/setup-ruby",
            "currentVersion": "v1",
            "fixedVersion": "v1"
          }
        ]
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 1 branch: renovate/tj-actions-branch-names-5.x
DEBUG: Calculating prConcurrentLimit (25)
DEBUG: getBranchPr(renovate/tj-actions-branch-names-5.x)
DEBUG: findPr(renovate/tj-actions-branch-names-5.x, undefined, open)
DEBUG: Retrieving PR list
DEBUG: Retrieved 1 Pull Requests
DEBUG: findPr(renovate/tj-actions-branch-names-5.x, undefined, closed)
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 25
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 25
}
DEBUG: PullRequests limit = 25
DEBUG: Calculating branchConcurrentLimit (25)
DEBUG: 0 already existing branches found:
DEBUG: Branch concurrent limit remaining: 25
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 25
}
DEBUG: Branches limit = 25
DEBUG: Setting current branch to master(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: latest commit(branch="renovate/tj-actions-branch-names-5.x")
{
  "branchName": "master",
  "latestCommitDate": "2021-10-21T17:41:48+02:00"
}
DEBUG: getBranchPr(renovate/tj-actions-branch-names-5.x)(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: findPr(renovate/tj-actions-branch-names-5.x, undefined, open)(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: findPr(renovate/tj-actions-branch-names-5.x, undefined, closed)(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: branchExists=false(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: recreateClosed is false(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: findPr(renovate/tj-actions-branch-names-5.x, Update tj-actions/branch-names action to v5, !open)(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: prAlreadyExisted=false(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: No schedule defined(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: Branch needs creating(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: Using reuseExistingBranch: false(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: Starting search at index 232(packageFile=".github/workflows/use-step-outputs.yml", branch="renovate/tj-actions-branch-names-5.x")
{
  "depName": "tj-actions/branch-names"
}
DEBUG: Found match at index 232(packageFile=".github/workflows/use-step-outputs.yml", branch="renovate/tj-actions-branch-names-5.x")
{
  "depName": "tj-actions/branch-names"
}
DEBUG: Contents updated(packageFile=".github/workflows/use-step-outputs.yml", branch="renovate/tj-actions-branch-names-5.x")
{
  "depName": "tj-actions/branch-names"
}
DEBUG: Updated 1 package files(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: No updated lock files in branch(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: 1 file(s) to commit(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: Committing files to branch renovate/tj-actions-branch-names-5.x(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: Setting git author name(branch="renovate/tj-actions-branch-names-5.x")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/tj-actions-branch-names-5.x")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: git commit(branch="renovate/tj-actions-branch-names-5.x")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/tj-actions-branch-names-5.x",
    "commit": "25f4295",
    "root": false,
    "summary": {
      "changes": 1,
      "insertions": 1,
      "deletions": 1
    }
  }
}
DEBUG: git push(branch="renovate/tj-actions-branch-names-5.x")
{
  "result": {
    "pushed": [
      {
        "deleted": false,
        "tag": false,
        "branch": true,
        "new": true,
        "alreadyUpdated": false,
        "local": "refs/heads/renovate/tj-actions-branch-names-5.x",
        "remote": "refs/heads/renovate/tj-actions-branch-names-5.x"
      }
    ],
    "branch": {
      "local": "renovate/tj-actions-branch-names-5.x",
      "remote": "renovate/tj-actions-branch-names-5.x",
      "remoteName": "origin"
    },
    "ref": {
      "local": "refs/remotes/origin/renovate/tj-actions-branch-names-5.x"
    },
    "remoteMessages": {
      "all": [
        "Create a pull request for 'renovate/tj-actions-branch-names-5.x' on GitHub by visiting:",
        "https://github.com/DanySK/Tutorial-GitHub-Actions-Minimal/pull/new/renovate/tj-actions-branch-names-5.x"
      ],
      "pullRequestUrl": "https://github.com/DanySK/Tutorial-GitHub-Actions-Minimal/pull/new/renovate/tj-actions-branch-names-5.x"
    }
  }
}
INFO: Branch created(branch="renovate/tj-actions-branch-names-5.x")
{
  "commitSha": "25f4295"
}
DEBUG: Ensuring PR(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: getBranchPr(renovate/tj-actions-branch-names-5.x)(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: findPr(renovate/tj-actions-branch-names-5.x, undefined, open)(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: findPr(renovate/tj-actions-branch-names-5.x, undefined, closed)(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: resolveBranchStatus(branchName=renovate/tj-actions-branch-names-5.x, ignoreTests=false)(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: getBranchStatus(renovate/tj-actions-branch-names-5.x)(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: branch status check result(branch="renovate/tj-actions-branch-names-5.x")
{
  "state": "pending",
  "statuses": []
}
DEBUG: No check runs found(branch="renovate/tj-actions-branch-names-5.x")
{
  "result": {
    "total_count": 0,
    "check_runs": []
  }
}
DEBUG: Branch status yellow(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: Creating PR(branch="renovate/tj-actions-branch-names-5.x")
{
  "prTitle": "Update tj-actions/branch-names action to v5"
}
DEBUG: Creating PR(branch="renovate/tj-actions-branch-names-5.x")
{
  "title": "Update tj-actions/branch-names action to v5",
  "head": "DanySK:renovate/tj-actions-branch-names-5.x",
  "base": "master",
  "draft": false
}
DEBUG: PR created(branch="renovate/tj-actions-branch-names-5.x")
{
  "pr": 4,
  "draft": false
}
DEBUG: Adding labels '' to #4(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: GitHub automerge is not enabled for this repository(branch="renovate/tj-actions-branch-names-5.x")
{
  "prNumber": 4
}
INFO: PR created(branch="renovate/tj-actions-branch-names-5.x")
{
  "pr": 4,
  "prTitle": "Update tj-actions/branch-names action to v5"
}
DEBUG: Skipping assignees and reviewers as automerge=true(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: Created Pull Request #4(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: PR is configured for automerge(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: PR is not ready for merge(branch="renovate/tj-actions-branch-names-5.x")
DEBUG: getBranchPr(renovate/tj-actions-branch-names-5.x)
DEBUG: findPr(renovate/tj-actions-branch-names-5.x, undefined, open)
DEBUG: Found PR #4
DEBUG: Returning from graphql open PR list
DEBUG: Ensuring Dependency Dashboard
DEBUG: ensureIssue(Dependency Dashboard)
DEBUG: Patching issue
DEBUG: Issue updated
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/tj-actions-branch-names-5.x"
  ],
  "renovateBranches": [
    "renovate/tj-actions-branch-names-5.x"
  ]
}
DEBUG: remainingBranches=
DEBUG: No branches to clean up
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {
    "init": 2502,
    "extract": 2207,
    "lookup": 724,
    "update": 5579
  },
  "total": 12218
}
DEBUG: http statistics
{
  "urls": {
    "https://api.github.com/graphql (POST)": 5,
    "https://api.github.com/repos/DanySK/Tutorial-GitHub-Actions-Minimal/commits/renovate/tj-actions-branch-names-5.x/check-runs (GET)": 1,
    "https://api.github.com/repos/DanySK/Tutorial-GitHub-Actions-Minimal/commits/renovate/tj-actions-branch-names-5.x/status (GET)": 1,
    "https://api.github.com/repos/DanySK/Tutorial-GitHub-Actions-Minimal/contents/renovate.json (GET)": 1,
    "https://api.github.com/repos/DanySK/Tutorial-GitHub-Actions-Minimal/issues/2 (GET)": 2,
    "https://api.github.com/repos/DanySK/Tutorial-GitHub-Actions-Minimal/issues/2 (PATCH)": 1,
    "https://api.github.com/repos/DanySK/Tutorial-GitHub-Actions-Minimal/pulls (GET)": 1,
    "https://api.github.com/repos/DanySK/Tutorial-GitHub-Actions-Minimal/pulls (POST)": 1,
    "https://api.github.com/repos/DanySK/renovate-config/contents/default.json (GET)": 1,
    "https://api.github.com/repos/tj-actions/branch-names/releases (GET)": 1,
    "https://api.github.com/repos/tj-actions/branch-names/tags (GET)": 1,
    "https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json (GET)": 1
  },
  "hostStats": {
    "api.github.com": {
      "requestCount": 17,
      "requestAvgMs": 291,
      "queueAvgMs": 0
    }
  },
  "totalRequests": 17
}
INFO: Repository finished
{
  "durationMs": 12218
}

```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by Gabriel-Ladzaretti**
## Changes
Modified extraction regex to be more precise.

## Context
closes #12260 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by Gabriel-Ladzaretti** [comment]
https://github.com/ladzaretti/12260-2/pull/4/files

https://github.com/ladzaretti/12260-2/pull/1/files

File: lib/modules/manager/github-actions/extract.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ import type { PackageDependency, PackageFile } from '../types';
 
 const dockerRe = regEx(/^\s+uses: docker:\/\/([^"]+)\s*$/);
 const actionRe = regEx(
-  /^\s+-?\s+?uses: (?<replaceString>['"]?(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>.+?)\s*['"]?(?:#\s+(?:renovate:\s+)?tag=(?<tag>.+?))?)\s*?$/
+  /^[^\S\r\n]+-?\s+?uses: (:?(?<replaceString>['"]?(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>[\w.]+)?[^\S\r\n]*['"]?[^\S\r\n]*(:?#\s*(?:renovate:\s+)?tag=(?<tag>[v?\d+.]+))?)(:?.*)?)$/
```
Comment (viceice) [inline lib/modules/manager/github-actions/extract.ts:10]: There are never newlines, as we split the file and work line-by-line, see L19

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/modules/manager/github-actions/extract.ts (hunk 1 above)
Comment (Gabriel-Ladzaretti) [reply lib/modules/manager/github-actions/extract.ts]: thanks for the heads up, 
those are left overs from working on a regex sim and multiline input.
fixed.

**Comment by Gabriel-Ladzaretti** [comment]
https://github.com/Gabriel-Ladzaretti/renovate/blob/c28d0448c60c4ed437eadd58cdbfc6fd940f9153/lib/modules/manager/github-actions/extract.ts#L49

im using trim as the original solution to the problem @viceice mentioned (replaceString captures whitespace when there is no `tag`/`renovate`) used lookaheads. but it turns out RE2 does not supports that :{}

File: lib/modules/manager/github-actions/extract.ts [hunk 2]
```diff
@@ -7,7 +7,7 @@ import type { PackageDependency, PackageFile } from '../types';
 
 const dockerRe = regEx(/^\s+uses: docker:\/\/([^"]+)\s*$/);
 const actionRe = regEx(
-  /^\s+-?\s+?uses: (?<replaceString>['"]?(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>.+?)\s*['"]?(?:#\s+(?:renovate:\s+)?tag=(?<tag>.+?))?)\s*?$/
+  /^\s+-?\s+?uses: (:?(?<replaceString>['"]?(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>[\w.]+)?\s*['"]?\s*(:?#\s*(?:renovate:\s+)?tag=(?<tag>[v?\d+.]+))?)(:?.*)?)$/
```
Comment (viceice) [inline lib/modules/manager/github-actions/extract.ts:10]: This looks really wrong now.
- Why there can be an addional `:` infront of the `replaceString`?
- Why is `currentValue` now optional? It's required.

I think this is what we need
```suggestion
  /^\s+-?\s+?uses: (?<replaceString>['"]?(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>\S+)['"]?(?:\s+#\s+(?:renovate:\s+)?tag=(?<tag>\S+))?)/
```
https://regex101.com/r/mKGVLK/1

File: lib/modules/manager/github-actions/extract.ts [hunk 3]
```diff
@@ -46,7 +46,7 @@ export function extractPackageFile(content: string): PackageFile | null {
         datasource: GithubTagsDatasource.id,
         versioning: dockerVersioning.id,
         depType: 'action',
-        replaceString,
+        replaceString: replaceString.trim(),
```
Comment (viceice) [inline lib/modules/manager/github-actions/extract.ts:49]: this is not needed with my regex

**Review by astellingwerf — CHANGES_REQUESTED** [review]
Is there a test that proves the issue and the corresponding fix?

**Comment by Gabriel-Ladzaretti** [comment]
@astellingwerf 
> Is there a test that proves the issue and the corresponding fix?

https://github.com/renovatebot/renovate/pull/14757#issuecomment-1075002005

File: lib/modules/manager/github-actions/extract.ts [hunk 4]
```diff
@@ -7,7 +7,7 @@ import type { PackageDependency, PackageFile } from '../types';
 
 const dockerRe = regEx(/^\s+uses: docker:\/\/([^"]+)\s*$/);
 const actionRe = regEx(
-  /^\s+-?\s+?uses: (?<replaceString>['"]?(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>.+?)\s*['"]?(?:#\s+(?:renovate:\s+)?tag=(?<tag>.+?))?)\s*?$/
+  /^\s+-?\s+?uses: (?<replaceString>['"]?(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>\S+)['"]?(?:\s+#\s+(?:renovate:\s+)?tag=(?<tag>\S+))?)/
```
Comment (viceice) [inline lib/modules/manager/github-actions/extract.ts:10]:
```suggestion
  /^\s+-?\s+?uses: (?<replaceString>['"]?(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>[^\s'"]+)['"]?(?:\s+#\s+(?:renovate:\s+)?tag=(?<tag>\S+))?)/
```

need one more update because of failed test: https://regex101.com/r/mKGVLK/2

**Review by viceice — COMMENTED** [review]
Also please add at least one comment sample to the fixtures files

**Comment by astellingwerf** [comment]
> @astellingwerf
> 
> > Is there a test that proves the issue and the corresponding fix?
> 
> [#14757 (comment)](https://github.com/renovatebot/renovate/pull/14757#issuecomment-1075002005)

Well, those reside in another repo, so wouldn't be an integral part of the test suite for this code. I'd wanna see tests added (or updated) to the Renovate repo.

**Comment by Gabriel-Ladzaretti** [comment]
> > @astellingwerf
> > > Is there a test that proves the issue and the corresponding fix?
> > 
> > 
> > [#14757 (comment)](https://github.com/renovatebot/renovate/pull/14757#issuecomment-1075002005)
> 
> Well, those reside in another repo, so wouldn't be an integral part of the test suite for this code. I'd wanna see tests added (or updated) to the Renovate repo.

misunderstood 😅, anyhow ive added some

**Review by rarkins — DISMISSED** [review]

File: lib/modules/manager/github-actions/__fixtures__/workflow_4.yml [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+    branches: [ main ]
+
+  workflow_dispatch:
+
+jobs:
+  build:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5 # Comment that Renovate bot has moved Comment that Renovate bot will remove later on
```
Comment (viceice) [inline lib/modules/manager/github-actions/__fixtures__/workflow_4.yml:16]: Please add testcases to existing fixtures instead of adding new fixtures

Comment (Gabriel-Ladzaretti) [reply lib/modules/manager/github-actions/__fixtures__/workflow_4.yml]: done

**Review by rarkins — DISMISSED** [review]

**Review by viceice — DISMISSED** [review]

**Comment by viceice** [comment]
needs snapshot update

**Review by rarkins — APPROVED** [review]
