### PR TITLE
fix(manager/docker-compose): update images used as anchors

### LINKED ISSUE #34369: Renovate doesn't update docker-compose with yaml anchors anymore
### Discussed in https://github.com/renovatebot/renovate/discussions/32918

<div type='discussions-op-text'>

<sup>Originally posted by **mueller-ma** December  5, 2024</sup>
### How are you running Renovate?

A Mend.io-hosted app

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

_No response_

### Please tell us more about your question or problem

In the past Renovate had no problems when a Docker compose file had yaml anchors. Now it doesn't extract the image anymore:
- https://github.com/mueller-ma/renovate-reproduce/blob/main/docker-compose.yml
- https://github.com/mueller-ma/renovate-reproduce/issues/2

`docker compose` can use and parse this docker-compose file. You can see that docker includes the `image` in both services:

````
$ docker compose -f docker-compose.yml config
name: tmp
services:
  service-a:
    environment:
      SERVICE: a
    image: debian:11
    networks:
      default: null
  service-b:
    environment:
      SERVICE: b
    image: debian:11
    networks:
      default: null
networks:
  default:
    name: tmp_default
x-shared_setting:
  image: debian:11
````

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: packageFiles with updates
{
  "baseBranch": "main"
  "config": {
    "docker-compose": [
      {
        "deps": [],
        "packageFile": "docker-compose.yml"
      }
    ]
  }
}

```

</details>
</div>

Reproduction: renovate-reproductions/32918

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- Extract the images which are used as anchors from the `extensions`

## Context
- Closes: https://github.com/renovatebot/renovate/issues/34369

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository https://github.com/Rahul-renovate-testing/repro-34369/pulls

### CODE REVIEW

File: lib/modules/manager/docker-compose/schema.ts [hunk 1]
```diff
@@ -14,13 +15,48 @@ const DockerComposeService = z.object({
...
 const DockerComposeFileV1 = z.record(DockerComposeService);
-const DockerComposeFileModern = z.object({
-  // compose does not use this strictly, so we shouldn't be either
-  // https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element
-  version: z.string().optional(),
-  services: z.record(DockerComposeService),
-});
+const DockerComposeFileModern = z
+  .object({
+    // compose does not use this strictly, so we shouldn't be either
```
Comment (viceice) [inline lib/modules/manager/docker-compose/schema.ts:20]: use tsdoc style comment

File: lib/modules/manager/docker-compose/schema.ts [hunk 2]
```diff
@@ -14,13 +15,48 @@ const DockerComposeService = z.object({
...
+    // https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element
+    version: z.string().optional(),
+    services: z.record(DockerComposeService),
+  })
+  .catchall(z.unknown()) // allow unknown fields
```
Comment (viceice) [inline lib/modules/manager/docker-compose/schema.ts:25]: i don't like that. why not simply add extensions to the root schema?

Comment (RahulGautamSingh) [reply lib/modules/manager/docker-compose/schema.ts:25]: `extensions` is a name I have given to collect all of them in one object
They can have any name as long as they `begin` with `x-` prefix hence we cannot use them directly as field.

Comment (viceice) [reply lib/modules/manager/docker-compose/schema.ts:27]: can we define the root schema like:
```ts
type DExtensionKey = `x-${string}`
const isValidDKey = (key: string): key is DExtensionKey => key.startsWith("x-")
const DCFile = z.record(z.string().refine(isValidDKey)).extend(
  z.object({
    version: z.string().optional(),
    services: z.record(DockerComposeService),
  })
);
```

Comment (viceice) [reply lib/modules/manager/docker-compose/schema.ts:27]: - https://github.com/colinhacks/zod/issues/2195

Comment (viceice) [reply lib/modules/manager/docker-compose/schema.ts:27]: ☝️

**Review by viceice — COMMENTED** [review]
see open conversation

File: lib/modules/manager/docker-compose/schema.ts (hunk 2 above)
Comment (RahulGautamSingh) [reply lib/modules/manager/docker-compose/schema.ts:27]: It asks to use `extend` with `record` which is not correct as per the Zod documentation. And, the suggested approach as per their AI is to use `catchall` as well

Comment (viceice) [reply lib/modules/manager/docker-compose/schema.ts]: maybe simply add a filter to only allow keys with `x-` 🤔 .

if not possible add a comment to the code that we need a newer (v4?) zod to make this better.

**Review by viceice — COMMENTED** [review]
see comment

File: lib/modules/manager/docker-compose/schema.ts (hunk 2 above)
Comment (secustor) [reply lib/modules/manager/docker-compose/schema.ts]: Could we passthrough the on the root level and then simply loop over they object keys?

Comment (RahulGautamSingh) [reply lib/modules/manager/docker-compose/schema.ts]: Kinda doing something with the `catchall` in the current implemenation

File: lib/modules/manager/docker-compose/schema.ts [hunk 3]
```diff
@@ -14,13 +15,52 @@ const DockerComposeService = z.object({
...
+  .object({
+    /**
+     *  compose does not use this strictly, so we shouldn't be either
+     *  https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element
+     */
+    version: z.string().optional(),
+    services: z.record(DockerComposeService),
+  })
+  // using catchall to capture fields starting with `x-` and collecting them in `extensions` field
+  // might need to replace this with something better once zodv4 is stable
```
Comment (viceice) [inline lib/modules/manager/docker-compose/schema.ts]:
```suggestion
  // might need to replace this with something better once zod v4 is stable
```

**Review by viceice — APPROVED** [review]
