### PR TITLE
fix: Use auto-discovered organisational preset configuration during on-boarding

### LINKED ISSUE #9851: Auto-discovered organisational presets not applied during on-boarding
**What Renovate type, platform and version are you using?**

Renovate Self-hosted

**Describe the bug**

When using organisational presets for configuration, the preset is not applied during the on-boarding MR - This can result in repositories not being on-boarded when they should be, based on the presets configuration.

e.g 

```
org/renovate-config
org/repository1
```

When `organisation/repository1` is on-boarded it should use the configuration from the `org/renovate-config` to identify any 

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: Found 0 package file(s)
INFO: Repository has no package files - skipping
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

https://github.com/56KBs/renovate-reproduction-repo
https://github.com/56KBs/renovate-config

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Discussion #9781

### PR DESCRIPTION
**Pull request by 56KBs**
## Changes:

When deciding whether to on-board, the global configuration was the only configuration loaded.
This can result in repositories not being on-boarded when the organisational presets being loaded would have resulted in dependencies being identified.

## Context:

Closes #9851

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/repository/init/merge.ts [hunk 1]
```diff
@@ -169,9 +169,10 @@ export async function mergeRenovateConfig(
     throw error;
   }
   if (migratedConfig.warnings) {
-    returnConfig.warnings = returnConfig.warnings.concat(
-      migratedConfig.warnings
-    );
+    returnConfig.warnings = [
+      ...(returnConfig.warnings || []),
+      ...migratedConfig.warnings,
+    ];
```
Comment (viceice) [inline lib/workers/repository/init/merge.ts:175]: unrelated but ok.

File: lib/workers/repository/onboarding/branch/config.spec.ts [hunk 2]
```diff
@@ -1,29 +1,46 @@
 import { RenovateConfig, getConfig, getName } from '../../../../../test/util';
 import * as presets from '../../../../config/presets/local';
 import { PRESET_DEP_NOT_FOUND } from '../../../../config/presets/util';
-import { getOnboardingConfig } from './config';
+import { RenovateSharedConfig } from '../../../../config/types';
```
Comment (viceice) [inline lib/workers/repository/onboarding/branch/config.spec.ts:4]:
```suggestion
import type { RenovateSharedConfig } from '../../../../config/types';
```

File: lib/workers/repository/onboarding/branch/config.spec.ts [hunk 3]
```diff
@@ -1,29 +1,46 @@
...
+import { getOnboardingConfig, getOnboardingConfigContents } from './config';
 
 jest.mock('../../../../config/presets/local');
 
 const mockedPresets = presets as jest.Mocked<typeof presets>;
 
 describe(getName(), () => {
   let config: RenovateConfig;
-  let onboardingConfig: string;
+  let onboardingConfig: RenovateSharedConfig;
```
Comment (viceice) [inline lib/workers/repository/onboarding/branch/config.spec.ts:13]: i think we should remove this and use test local const / let ?

File: lib/workers/repository/onboarding/branch/index.spec.ts [hunk 4]
```diff
@@ -7,81 +7,123 @@ import {
...
+  REPOSITORY_NO_PACKAGE_FILES,
+} from '../../../../constants/error-messages';
 import { Pr } from '../../../../platform';
 import { PrState } from '../../../../types';
+import * as _config from './config';
 import * as _rebase from './rebase';
 import { checkOnboardingBranch } from '.';
 
 const rebase: any = _rebase;
+const config: any = _config;
```
Comment (viceice) [inline lib/workers/repository/onboarding/branch/index.spec.ts:21]: Better rename this, to have less changes?

File: lib/workers/repository/init/merge.ts (hunk 1 above)
Comment (viceice) [reply lib/workers/repository/init/merge.ts:175]: Probably only occur in tests.

**Review by viceice — APPROVED** [review]
