### PR TITLE
fix(gomod): go.mod directive should not bump by default

### LINKED ISSUE #28474: go.mod directive incorrectly bumped
### Discussed in https://github.com/renovatebot/renovate/discussions/28468

<div type='discussions-op-text'>

<sup>Originally posted by **database64128** April 17, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

_No response_

### Please tell us more about your question or problem

Renovate ignores the `toolchain` line in `go.mod` and always updates the `go` line to the latest Go version. This is likely a regression of #16715. #27279 does not seem to work.

Minimum reproduction repo: https://github.com/database64128/renovate-bug-reproduction

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Avoids bumping go.mod directive if new version is compatible

## Context

Fixes #28474

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/versioning/go-mod-directive/index.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import { logger } from '../../../logger';
```
Comment (rarkins) [inline lib/modules/versioning/go-mod-directive/index.ts:1]:
```suggestion
```

**Review by viceice — APPROVED** [review]
So `replace` should only replace if new value is not matching current range?

**Review by secustor — APPROVED** [review]
