### PR TITLE
fix(go): Improve go-import content parsing

### LINKED ISSUE #7663: Some go dependencies can't be resolved
**What Renovate type, platform and version are you using?**
selfhosted, v23.72 in docker, accessing a Gitea instance.

**Describe the bug**
The go dependency `fyne.io/fyne` (and probably others) can not be resolved.

**Relevant debug logs**
```
DEBUG: Go lookup import url (repository=abc/xyz)                                                                                                                                                
       "goModule": "fyne.io/fyne",                                                                                                                                                                                   
       "goImportURL": "https://github.com/fyne-io/fyne"                                                                                                                                                              
DEBUG: GitHub 404 (repository=abc/xyz)                                                                                                                                                          
       "url": "https://github.com/api/v3/repos/fyne/undefined/tags?per_page=100"                                                                                                                                     
DEBUG: Datasource 404 (repository=abc/xyz)                                                                                                                                                      
       "datasource": "go",                                                                                                                                                                                           
       "lookupName": "fyne.io/fyne",                                                                                                                                                                                 
       "url": "https://github.com/api/v3/repos/fyne/undefined/tags?per_page=100"                                                                                                                                     
DEBUG: Failed to look up dependency fyne.io/fyne (repository=abc/xyz, packageFile=go.mod, dependency=fyne.io/fyne) 
```

**To Reproduce**
Here is a minimal reproduction repo: https://git.nroo.de/norwin/renovate-fyne-repro

**Additional context**
Note that the github fetch URL uses an incorrectly extracted repo slug (`fyne/undefined` instead of `fyne-io/fyne`).

Even if the repo slug was correct, this URL gives me a 404, shouldnt it be `https://api.github.com/repos/...`?

```
$ curl https://fyne.io/fyne/?go-get=1
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="go-import" content="fyne.io/fyne git https://github.com/fyne-io/fyne">
        <meta http-equiv="refresh" content="0; url=http://github.com/fyne-io/fyne">
    </head>
    <body>
        The Fyne API - read the <a href="http://godoc.org/fyne.io/fyne">documentation</a>.
    </body>
</html>

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

Given that we already assume `github` datasource in the conditional branch, let's rely on `goImportUrl` string instead of `goModule` argument.

## Context:

Closes #7663
Example: https://github.com/renovate-testing/test-7663-gomod-deps-404/pulls

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/datasource/go/index.ts [hunk 1]
```diff
@@ -115,8 +115,12 @@ async function getDatasource(goModule: string): Promise<DataSource | null> {
       const parsedUrl = URL.parse(goImportURL);
 
       // split the go module from the URL: host/go/module -> go/module
-      const split = goModule.split('/');
-      const lookupName = split[1] + '/' + split[2];
+      const lookupName = parsedUrl.pathname
+        .replace(/\.git$/, '')
+        .replace(/\/$/, '')
```
Comment (viceice) [inline lib/datasource/go/index.ts:120]: Use `trimTrailingSlash` from url utils

**Review by rarkins — APPROVED** [review]
