### PR TITLE
fix(manager/fleet): do not merge version into customization objects

### LINKED ISSUE #20157: Rancher Fleet Multiple PRs when version is the same
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.119.3 (we pull the latest on cron)

### If you're self-hosting Renovate, select which platform you are using.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

While using the Rancher Fleet module, Renovate will generate PRs for each `targetCustomization` target even if there is not a version specified for each `targetCustomization` in addition the the "root" level `helm.version` PR. The behavior of Fleet would be to take the "default" version under `helm.version` if a `helm.version` is not specified under `targetCustomization`.

Therefore it is redundant to create multiple PRs for each item under `targetCustomization` when the change is the same as the "root" `helm.version`'. Perhaps it is a configuration change on our end?

Here is a `fleet.yaml` for reproduction purposes

``` yaml
defaultNamespace: kube-system
name: cluster-autoscaler
helm:
  releaseName: rancher-cluster-autoscaler
  chart: cluster-autoscaler
  version: 9.23.0
  repo: https://kubernetes.github.io/autoscaler
  values:
    foo: yay

targetCustomizations:
- name: a
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: usw1-a
  helm:
    values:
      foo: daz
- name: b
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: usw1-b
  helm:
    values:
      foo: caz
- name: c
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: aws-usw2-c
  helm:
    values:
      foo: dar
- name: d
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: aws-usw2-d
  helm:
    values:
      foo: car
- name: e
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: aws-usw2-e
  helm:
    values:
      foo: baz
- name: f
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: aws-usw2-f
  helm:
    values:
      foo: bar
```

Here is the renovate configuration
``` json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "labels": ["dependencies"],
  "enabledManagers": ["fleet"]
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by secustor**
## Changes
Do not merge version from the global fleet helm definition into deps which are created for each target customization.     
This results in deps with `skipReason` `no-version`, if the version not overwritten by the customization. 

## Context
Closes https://github.com/renovatebot/renovate/issues/20157

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/fleet/extract.ts [hunk 1]
```diff
@@ -87,10 +87,14 @@ function extractFleetFile(doc: FleetFile): PackageDependency[] {
   result.push(extractFleetHelmBlock(doc.helm));
 
   if (!is.undefined(doc.targetCustomizations)) {
+    // remove version from helm block to allow usage of variables defined in the global block, but do not create PRs
+    // if there is no version defined in the customization.
+    const helmBlockContext = { ...doc.helm, version: undefined };
```
Comment (viceice) [inline lib/modules/manager/fleet/extract.ts:92]: can we completely delete the property instead please

**Review by viceice — COMMENTED** [review]
otherwise LGTM

**Review by viceice — APPROVED** [review]
