### PR TITLE
fix(git): unset all remotes before fetching

### LINKED ISSUE #10261: git fetch error after automerge recursion
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: ...

**Describe the bug**

Renovate warns about "git fetch error" after automerging.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
{"level":20,"branch":"renovate/all-dev","pr":272,"msg":"PR merged","time":"2021-06-01T13:01:10.157Z"}
{"level":20,"branch":"renovate/all-dev","branchName":"renovate/all-dev","msg":"Deleted remote branch","time":"2021-06-01T13:01:12.464Z"}
{"level":20,"branch":"renovate/all-dev","branchName":"renovate/all-dev","msg":"No local branch to delete","time":"2021-06-01T13:01:12.515Z"}
{"level":30,"branch":"renovate/all-dev","pr":272,"prTitle":"chore(deps): update dependency @webundsoehne/nestjs-util to ^3.0.2 [skip ci]","msg":"PR automerged","time":"2021-06-01T13:01:12.515Z"}
{"level":20,"branch":"renovate/all-dev","branchName":"renovate/all-dev","msg":"No remote branch to delete","time":"2021-06-01T13:01:12.935Z"}
{"level":20,"branch":"renovate/all-dev","branchName":"renovate/all-dev","msg":"No local branch to delete","time":"2021-06-01T13:01:12.990Z"}
{"level":30,"branch":"renovate/all-dev","msg":"Renovating repository again after automerge result","time":"2021-06-01T13:01:12.991Z"}
{"level":30,"renovateVersion":"25.34.2","msg":"Repository started","time":"2021-06-01T13:01:12.992Z"}
{"level":20,"msg":"Using localDir: /mnt/renovate/gh/cenk1cenk2/nestjs-tools","time":"2021-06-01T13:01:12.992Z"}
{"level":20,"msg":"Repository cache is valid","time":"2021-06-01T13:01:12.995Z"}
{"level":20,"msg":"initRepo(\"cenk1cenk2/nestjs-tools\")","time":"2021-06-01T13:01:13.004Z"}
{"level":20,"endpoint":"https://api.github.com/","msg":"Overriding default GitHub endpoint","time":"2021-06-01T13:01:13.004Z"}
{"level":20,"msg":"cenk1cenk2/nestjs-tools default branch = master","time":"2021-06-01T13:01:13.207Z"}
{"level":20,"msg":"Using app token for git init","time":"2021-06-01T13:01:13.207Z"}
{"level":20,"msg":"resetMemCache()","time":"2021-06-01T13:01:13.604Z"}
{"level":20,"msg":"Resetting npmrc","time":"2021-06-01T13:01:13.605Z"}
{"level":20,"msg":"checkOnboarding()","time":"2021-06-01T13:01:13.605Z"}
{"level":20,"msg":"isOnboarded()","time":"2021-06-01T13:01:13.605Z"}
{"level":20,"msg":"Checking cached config file name","time":"2021-06-01T13:01:13.605Z"}
{"level":20,"msg":"Existing config file confirmed","time":"2021-06-01T13:01:13.798Z"}
{"level":20,"msg":"Repo is onboarded","time":"2021-06-01T13:01:13.799Z"}
{"level":20,"msg":"migrateAndValidate()","time":"2021-06-01T13:01:13.800Z"}
{"level":20,"msg":"No config migration necessary","time":"2021-06-01T13:01:13.800Z"}
{"level":20,"config":{"$schema":"https://docs.renovatebot.com/renovate-schema.json","extends":["github>whitesource/merge-confidence:beta","@cenk1cenk2"]},"msg":"massaged config","time":"2021-06-01T13:01:13.800Z"}
{"level":20,"config":{"$schema":"https://docs.renovatebot.com/renovate-schema.json","extends":["github>whitesource/merge-confidence:beta","@cenk1cenk2"]},"msg":"migrated config","time":"2021-06-01T13:01:13.801Z"}
{"level":20,"msg":"Setting hostRules from config","time":"2021-06-01T13:01:14.553Z"}
{"level":20,"ignorePaths":["**/node_modules/**","**/bower_components/**","**/vendor/**","**/examples/**","**/__tests__/**","**/test/**","**/tests/**","**/__fixtures__/**"],"msg":"Found repo ignorePaths","time":"2021-06-01T13:01:14.563Z"}
{"level":20,"msg":"No vulnerability alerts found","time":"2021-06-01T13:01:14.765Z"}
{"level":20,"msg":"No vulnerability alerts found","time":"2021-06-01T13:01:14.765Z"}
{"level":20,"msg":"processRepo()","time":"2021-06-01T13:01:14.765Z"}
{"level":20,"msg":"findIssue(Dependency Dashboard)","time":"2021-06-01T13:01:14.766Z"}
{"level":20,"msg":"Retrieving issueList","time":"2021-06-01T13:01:14.766Z"}
{"level":20,"msg":"Retrieved 2 issues","time":"2021-06-01T13:01:14.973Z"}
{"level":20,"msg":"Found issue 1","time":"2021-06-01T13:01:14.973Z"}
{"level":20,"msg":"No baseBranches","time":"2021-06-01T13:01:15.151Z"}
{"level":20,"msg":"extract()","time":"2021-06-01T13:01:15.152Z"}
{"level":20,"msg":"Setting current branch to master","time":"2021-06-01T13:01:15.152Z"}
{"level":20,"msg":"Initializing git repository into /mnt/renovate/gh/cenk1cenk2/nestjs-tools","time":"2021-06-01T13:01:15.152Z"}
{"level":40,"err":{"task":{"commands":["fetch","--depth=10"],"format":"utf-8"},"message":"fatal: couldn't find remote ref refs/heads/origin/renovate/all-dev\n","stack":"Error: fatal: couldn't find remote ref refs/heads/origin/renovate/all-dev\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"},"msg":"git fetch error","time":"2021-06-01T13:01:15.590Z"}
{"level":20,"durationMs":710,"msg":"git clone completed","time":"2021-06-01T13:01:16.362Z"}
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to: https://github.com/cenk1cenk2/nestjs-tools
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I'm seeing this happen hundreds of times in the app.

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Unsets all remotes before doing a git fetch.

## Context:

Closes #10261

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/git/index.ts [hunk 1]
```diff
@@ -266,6 +266,10 @@ export async function syncGit(): Promise<void> {
     try {
       await git.raw(['remote', 'set-url', 'origin', config.url]);
       await resetToBranch(await getDefaultBranch(git));
+      // istanbul ignore if
+      if (process.env.NODE_ENV !== 'test') {
+        await git.raw(['config', '--unset-all', 'remote.origin.fetch']);
```
Comment (viceice) [inline lib/util/git/index.ts:271]:
```suggestion
        await git.raw(['config', '--unset-all', 'remote.origin.fetch']);
```

Why not using `git.config` function? I'm not sure if this solves the issue. Could you reproduce it with local real run? It's a little complicated i think.

Comment (rarkins) [reply lib/util/git/index.ts:271]: image
Seems it's not supported?

We use `git.raw` here too:
image

I can't reproduce this locally but it keeps happening in the app. I don't see much downside in trying this.

Comment (viceice) [reply lib/util/git/index.ts:271]: It's `addConfig` function 🙈
