### PR TITLE
fix(platform/bitbucket): use debug logs if issues unavailable/disabled

### LINKED ISSUE #34180: Gracefully ignore missing issues in Bitbucket Cloud
### Describe the proposed change(s).

Example of what you see in a Bitbucket Cloud repo in the Mend app:

Image

Atlassian have basically deprecated issues in Bitbucket Cloud now, for any new workspaces.

We should:
- Detect when issues are unavailable (is it has_issues?)
- Do not warn about ensureIssue() if issues are unavailable

In other words 2/3 of the warnings in the screenshot should disappear, and be replaced with a debug message noting that issues aren't available.

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- Replace warn with debug logs if issues are unavailable/disabled

## Context
- Closes: #34180 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/platform/bitbucket/schema.ts [hunk 1]
```diff
@@ -30,7 +30,9 @@ export const RepoInfo = z
       name: z.string(),
     }),
     has_issues: z.boolean().catch(() => {
-      logger.once.warn('Bitbucket: "has_issues" field missing from repo info');
+      logger.once.debug(
+        'Bitbucket: "has_issues" field missing from repo info. Issues are not available for this repository.',
+      );
```
Comment (rarkins) [inline lib/modules/platform/bitbucket/schema.ts:35]:
```suggestion
```

Let's actually drop this altogether, as we expect it to happen a lot from now on

**Review by rarkins — APPROVED** [review]
