### PR TITLE
fix(gitlab): encode namespaced project paths in /api/v4/projects call

### LINKED ISSUE #14268: Gitlab v4 API needs encoded namespaced repo paths
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.84.3

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.6.4-ee

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

The issue is currently Gitlab's API will return a 404 when getting the renovate.json file in the function `getRawFile` from `lib/platform/gitlab/index.ts`.  This occurs when the repo path is a namespaced path with a forward slash in it.

Gitlab's REST APIs require url encoded namespaced paths for the repo when making a GET call to get a file.  For example, let's say the the namespaced path is `dev/some-project`

Then, the following would work:

```
curl -H "PRIVATE-TOKEN:<insert your access token>" https://gitlab.example.com/api/v4/projects/dev%2Fsome-project/repository/files/renovate.json?ref=next
```

Please notice the namespaced path for the repo was url encoded to ensure the forward slash is `%2F`.  This would align with Gitlab's docs: https://docs.gitlab.com/ee/api/index.html#namespaced-path-encoding

However, currently, Renovate doesn't encode this, so the forward slash is left as is `(dev/some-project)`, causing the request to fail.  There is a very easy fix in the `getRawFile` function I mentioned:

```
const repo = urlEscape(repoName || config.repository);
```

If you don't mind, I'd like to put up a quick PR to fix this.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by karen-kua**
## Changes

When making a GET call to Gitlab's `/api/v4/projects/:repo` endpoint, the `repo` now has forward slashes url encoded (`%2F%`) when using namespaced paths.  This aligns with Gitlab's [specifications](https://docs.gitlab.com/ee/api/index.html#namespaced-path-encoding) for namespaced project paths.  If they are not encoded, then Gitlab will respond with a 404.  

## Context

Closes #14268

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/platform/gitlab/index.ts [hunk 1]
```diff
@@ -161,7 +161,7 @@ export async function getRawFile(
   branchOrTag?: string
 ): Promise<string | null> {
   const escapedFileName = urlEscape(fileName);
-  const repo = repoName ?? config.repository;
+  const repo = urlEscape(repoName || config.repository);
```
Comment (viceice) [inline lib/platform/gitlab/index.ts:164]:
```suggestion
  const repo = urlEscape(repoName ?? config.repository);
```

Comment (rarkins) [reply lib/platform/gitlab/index.ts:164]: I'm curious though, what "falsely" value would you want to preserve here?

Comment (azukimochi) [reply lib/platform/gitlab/index.ts:164]: Thanks for looking at this PR!  Personally, I wouldn't use nullish coalescing here, as there are no falsey values that I think the app would benefit from.  It would cause more errors as empty strings, NaN, 0, and false would succeed if they're on the left hand side.   As such, the logical OR operator makes more sense here.

Comment (viceice) [reply lib/platform/gitlab/index.ts:164]: We'll get lint issues with `||` when enabling strict null check soon.

I don't want to preserve wrong values, these should simply never happen. Otherwise we should accept them on function arg type. 😉

Comment (karen-kua) [reply lib/platform/gitlab/index.ts:164]: > I don't want to preserve wrong values, these should simply never happen. Otherwise we should accept them on function arg type. 😉

Hah, you got me there on the static typing.

> We'll get lint issues with || when enabling strict null check soon.

Given this, I'm fine with letting you two decide whether to go with nullish coalescing or not. Since you two are maintainers, you'll have a better picture of what fit better with the repo's long term vision. 👍

**Review by rarkins — APPROVED** [review]
