### PR TITLE
fix(platform): renovate should not be case sensitive

### LINKED ISSUE #14621: Renovate should not be case-sensitive regarding repository name
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.97.3

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

If a repository has been renamed, the code currently checks that the new name is strictly equals to the repository name specified:

https://github.com/renovatebot/renovate/blob/887e9f31728f768d50a7d906277ed150643487e5/lib/modules/platform/github/index.ts#L280

Using `mogztter/asciidoctor-web-pdf` instead of `Mogztter/asciidoctor-web-pdf` will throw an exception (even though GitHub repository names are case insensitive):

```
DEBUG: Repository has been renamed (repository=mogztter/asciidoctor-web-pdf)
       "this_repository": "Mogztter/asciidoctor-web-pdf"
DEBUG: Caught initRepo error (repository=mogztter/asciidoctor-web-pdf)
       "err": {
         "message": "renamed",
         "stack": "Error: renamed\n    at Proxy.initRepo (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/platform/github/index.js:183:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async getPlatformConfig (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/apis.js:38:28)\n    at async initApis (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/apis.js:47:14)\n    at async initRepo (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/index.js:25:14)\n    at async Object.renovateRepository (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/index.js:37:18)\n    at async Object.start (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/global/index.js:116:13)\n    at async /home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/renovate.js:15:24"
       }
 INFO: Repository has been renamed - skipping (repository=mogztter/asciidoctor-web-pdf)
```

### Relevant debug logs

<details><summary>Stacktrace</summary>

```
Error: renamed
    at Proxy.initRepo (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/platform/github/index.js:183:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getPlatformConfig (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/apis.js:38:28)
    at async initApis (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/apis.js:47:14)
    at async initRepo (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/index.js:25:14)
    at async Object.renovateRepository (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/index.js:37:18)
    at async Object.start (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/global/index.js:116:13)
    at async /home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/renovate.js:15:24
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by MaronHatoum**
## Changes
changed repository name to lowerCase when checking if repositor has been renamed

## Context
Closes https://github.com/renovatebot/renovate/issues/14621

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/platform/github/index.ts [hunk 1]
```diff
@@ -277,7 +277,10 @@ export async function initRepo({
     if (!repo.defaultBranchRef?.name) {
       throw new Error(REPOSITORY_EMPTY);
     }
-    if (repo.nameWithOwner && repo.nameWithOwner !== repository) {
+    if (
+      repo.nameWithOwner &&
+      repo.nameWithOwner.toLocaleLowerCase() !== repository.toLocaleLowerCase()
```
Comment (viceice) [inline lib/modules/platform/github/index.ts:282]: I think uppercase is more safe, as there are some chars which don't have a lowercase representation.

File: lib/modules/platform/github/index.spec.ts [hunk 2]
```diff
@@ -2440,7 +2464,7 @@ describe('modules/platform/github/index', () => {
     });
     it('returns empty if disabled', async () => {
       // prettier-ignore
-      httpMock.scope(githubApiHost).post('/graphql').reply(200, {data: { repository: {} }} );
+      httpMock.scope(githubApiHost).post('/graphql').reply(200, {data: {repository: {}}});
```
Comment (rarkins) [inline lib/modules/platform/github/index.spec.ts:2467]: Avoid unrelated changes in PRs like this (disable the option in your IDE if necessary)

**Review by rarkins — APPROVED** [review]

**Comment by Mogztter** [comment]
Thanks 🎉
