### PR TITLE
fix(galaxy): 5xx error throws DatasourceError

### LINKED ISSUE #5610: `galaxy` datasource 5xx errors should throw `DatasourceError`
If a 5xx error is thrown when fetching from the `galaxy` datasource then Renovate should catch that error and throw a `DatasourceError` instead, e.g. like `npm` does.

### PR DESCRIPTION
**Pull request by ViralRuparel**
5xx error handling for galaxy.

Closes #5610

### CODE REVIEW

**Comment by ViralRuparel** [comment]
Ready for review @rarkins

File: lib/datasource/galaxy/index.ts [hunk 1]
```diff
@@ -30,65 +35,73 @@ export async function getPkgReleases({
...
-      { dependency: lookupName },
-      `Received invalid crate data from ${galaxyAPIUrl}`
-    );
-    return null;
-  }
-
-  res = res.body;
-  const response = JSON.parse(res);
+    res = res.body;
+    const response = JSON.parse(res);
```
Comment (viceice) [inline lib/datasource/galaxy/index.ts]: @rarkins We should refactor this to let got the json parsing by passing `json:true` as option
