### PR TITLE
fix(config-validator): allow default `null` val for `globalOptions`

### LINKED ISSUE #27615: dryRun validation is not checking for `null`. Even though the docs say that `null` is the default.
### Discussed in https://github.com/renovatebot/renovate/discussions/27614

<div type='discussions-op-text'>

<sup>Originally posted by **frankbo** February 28, 2024</sup>
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

Base on the Docs it is fine to have `null` as a config value for dryRun
https://docs.renovatebot.com/self-hosted-configuration/#dryrun

When I set it to `null` in our config we get an error message, because the dryRun validation does not permit a `null` value in the config.

https://github.com/renovatebot/renovate/blob/main/lib/config/validation.ts#L850

It might be good to either allow `null` in the config or adjust the docs, that the default has no `dryrun` key at all.

In version 37.214.3 it was still working to have `dryRun: null`. Afterwards the validation was added.

@RahulGautamSingh . Just tagged you here, since you added the validation.

### Relevant debug logs

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>

### Have you created a minimal reproduction repository?

Placeholder value, please select the correct response from the dropdown</div>

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
Allowed default `null` value.
 I have used similar logic to one present for repo config options
 https://github.com/renovatebot/renovate/blob/9f2394680e6f15d16c16a1571b0a9945ff07368e/lib/config/validation.ts#L305

## Context
Closes: https://github.com/renovatebot/renovate/issues/27615

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/config/validation.ts [hunk 1]
```diff
@@ -818,139 +818,141 @@ async function validateGlobalConfig(
...
-      ) {
-        warnings.push({
-          topic: 'Configuration Error',
-          message: `Invalid value \`${val}\` for \`${currentPath}\`. The allowed values are ${['enabled', 'disabled', 'reset'].join(', ')}.`,
-        });
-      } else if (
-        key === 'dryRun' &&
-        !['extract', 'lookup', 'full'].includes(val)
-      ) {
+  if (val !== null) {
```
Comment (viceice) [inline lib/config/validation.ts:821]: can we warn if the default value is not `null`

Comment (RahulGautamSingh) [reply lib/config/validation.ts:821]: Will need to create a new record that stores the default values, similar to `optionTypes`, `optionParents`. Is that okay?

Comment (viceice) [reply lib/config/validation.ts:821]: sure, let's do it in separate PR

**Review by viceice — APPROVED** [review]
