### PR TITLE
fix: parentSha logic

### LINKED ISSUE #18288: Change parentSha computation logic
### Describe the proposed change(s).

For merge confidence calculations, we need to know what was the SHA on the base branch which the PR was created from. That's so that we can compare the test results of the base branch to Renovate's branch.

In a normal scenario with an up to date branch, the parentSha is same as HEAD^ which is same as baseBranch.sha.

If the base branch gets a new commit, parentSha is still HEAD^ but it's no longer same as baseBranchSha.

If the user commits on top of the renovate branch, and isModified=true, then we no longer use the branch for merge confidence so we don't need parentSha.

If the user commits on top of the renovate branch, but isModified=false (e.g. ignored committer), we need to make sure we keep the original parentSha and not accidentally treat Renovate's own commit as parentSha (HEAD^). However in theory we should be ignoring this branch for merge confidence calculations anyway, so it would be nice to detect it, but I'm not sure we can.

Essentially in our state we need to at times store two values:

The baseBranch sha at the time we made the commit, and
The bsaeBranch sha at the time we last calculate isBehindBaseBranch, isModified, isConflicted

ie.

1. When renovate makes a commit update parentSha to equal baseBranchSha
2. If baseBranch is ahead but we dont rebase then update baseBranchSha & don't touch parentSha
3. When user makes a commit
       - isModified=true delete parentSha
       - isModified=false, do nothing

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Context
- Closes: #18288

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
🤷‍♂️ code looks good

File: lib/workers/repository/cache.ts [hunk 1]
```diff
@@ -57,7 +57,7 @@ async function generateBranchCache(
     let isModified = false;
     let isBehindBase = false;
     if (sha) {
-      parentSha = await getBranchParentSha(branchName);
+      parentSha = getCachedBranchParentShaResult(branchName, sha);
```
Comment (rarkins) [inline lib/workers/repository/cache.ts:60]: How do you know it's *cached* at this point?

Comment (RahulGautamSingh) [reply lib/workers/repository/cache.ts:60]: During branch-creation it has to be there as we just added it.
For all other cases we will get either a string or null
Null if `isModified=true` and we deleted it. It will continue to remian `null` till a new commit is added.
String in all other cases as syncing branchState has no effect on `parentSha`.

One thing to note is that it can be `null` too in the cache.
