### PR TITLE
fix(github-tags): Use `releaseTimestamp` from `tagger` object

### LINKED ISSUE #16374: Renovate can't see Node 16.15.1
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Some time between 7 and 13 hours ago, Renovate stopped seeing Node.js release v16.15.1, which came out one month ago.

Repos with v16.15.1 now have a rollback PR to v16.15.0; repos with lower versions are now set to upgrade to v16.15.0. It's reproducible across 3 of 3 repos, all around 7 hours ago.

v16.15.1 was released 30 days ago, files and checksums are here: https://nodejs.org/download/release/latest-v16.x/

For some reason NPM only shows the package published 12 days ago: https://www.npmjs.com/package/node/v/16.15.1

I'm not sure what Renovate's package source is; whatever it is, it seems to have forgotten about this release!

This isn't critical, as we simply won't merge these PRs; but I wanted to flag the problem anyway. Thanks!

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Versions found before rolling back (node)(dependency="node")
{
  "versions": [
    {
      "version": "v0.0.1",
      "hash": "a3627c06f8248b8c7a1580f2985f5b566fc12672",
      "gitRef": "v0.0.1",
      "releaseTimestamp": "2009-05-27T14:29:55.000Z"
    },
```

```
    {
      "gitRef": "v16.14.2",
      "version": "v16.14.2",
      "hash": "442e84a358d75152556b5d087e4dd6a51615330d",
      "releaseTimestamp": "2022-03-17T21:34:05.000Z"
    },
    {
      "gitRef": "v16.15.0",
      "version": "v16.15.0",
      "hash": "e24328201344d58044bd34710ae1479a644ffa6f",
      "releaseTimestamp": "2022-04-26T20:45:21.000Z"
    },
    {
      "gitRef": "v17.0.0",
      "version": "v17.0.0",
      "hash": "f99ce7c1b88ff445f60e9e5575b674cb509e47f3",
      "releaseTimestamp": "2021-10-18T19:59:08.000Z"
    },
```

```
DEBUG: Setting current branch to next(branch="renovate/node-rollback")
DEBUG: latest commit(branch="renovate/node-rollback")
{
  "branchName": "next",
  "latestCommitDate": "2022-07-01T13:11:51+03:00"
}
DEBUG: getBranchPr(renovate/node-rollback)(branch="renovate/node-rollback")
DEBUG: findPr(renovate/node-rollback, undefined, open)(branch="renovate/node-rollback")
DEBUG: getPrList success(branch="renovate/node-rollback")
{
  "pullsTotal": 775,
  "requestsTotal": 1,
  "apiQuotaAffected": true
}
DEBUG: findPr(renovate/node-rollback, undefined, closed)(branch="renovate/node-rollback")
DEBUG: branchExists=false(branch="renovate/node-rollback")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/node-rollback")
DEBUG: recreateClosed is false(branch="renovate/node-rollback")
DEBUG: findPr(renovate/node-rollback, Roll back Node.js to 16.15.0, !open)(branch="renovate/node-rollback")
DEBUG: prAlreadyExisted=false(branch="renovate/node-rollback")
DEBUG: Checking schedule(at any time, null)(branch="renovate/node-rollback")
DEBUG: No schedule defined(branch="renovate/node-rollback")
DEBUG: Branch needs creating(branch="renovate/node-rollback")
DEBUG: Using reuseExistingBranch: false(branch="renovate/node-rollback")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/node-rollback")
DEBUG: npm.updateDependency(): engines.node = 16.15.0(branch="renovate/node-rollback")
DEBUG: Updating node in package.json(branch="renovate/node-rollback")
DEBUG: Updated 1 package files(branch="renovate/node-rollback")
DEBUG: Getting updated lock files(branch="renovate/node-rollback")
DEBUG: Writing package.json files(branch="renovate/node-rollback")
{
  "packageFiles": [
    "redacted"
  ]
}
DEBUG: Writing any updated package files(branch="renovate/node-rollback")
DEBUG: Writing package.json(branch="renovate/node-rollback")
DEBUG: npmrc file found in repository(branch="renovate/node-rollback")
DEBUG: Writing updated .npmrc file to .npmrc(branch="renovate/node-rollback")
DEBUG: Generating yarn.lock for .(branch="renovate/node-rollback")
DEBUG: Spawning yarn install to create yarn.lock(branch="renovate/node-rollback")
DEBUG: Enabling global cache as zero-install is not detected(branch="renovate/node-rollback")
DEBUG: Performing yarn dedupe highest(branch="renovate/node-rollback")
DEBUG: Using docker to execute(branch="renovate/node-rollback")
{
  "image": "node"
}
DEBUG: Resolved stable matching version(branch="renovate/node-rollback")
{
  "toolName": "corepack",
  "resolvedVersion": "0.11.2"
}
DEBUG: Found version constraint - checking for a compatible image to use(branch="renovate/node-rollback")
{
  "depName": "docker.io/renovate/node",
  "scheme": "node",
  "constraint": "16.15.0"
}
DEBUG: Found compatible image version(branch="renovate/node-rollback")
{
  "depName": "docker.io/renovate/node",
  "scheme": "node",
  "constraint": "16.15.0",
  "version": "16.15.0"
}
DEBUG: Resolved tag constraint(branch="renovate/node-rollback")
{
  "image": "docker.io/renovate/node",
  "tagConstraint": "16.15.0",
  "tagVersioning": "node",
  "tag": "16.15.0"
}
DEBUG: Fetching Docker image: docker.io/renovate/node:16.15.0(branch="renovate/node-rollback")
DEBUG: Finished fetching Docker image docker.io/renovate/node:16.15.0@sha256:788c33c453c7cb302a4a1e6f802bc1bf5d0bc7ace43780d4f5ba81e89914b9cb(branch="renovate/node-rollback")
DEBUG: Executing command(branch="renovate/node-rollback")
{
  "command": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/redacted\":\"/mnt/renovate/gh/redacted\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_ENABLE_IMMUTABLE_INSTALLS -e YARN_HTTP_TIMEOUT -e YARN_GLOBAL_FOLDER -e YARN_ENABLE_GLOBAL_CACHE -w \"/mnt/renovate/gh/redacted\" docker.io/renovate/node:16.15.0 bash -l -c \"install-tool corepack 0.11.2 && yarn install --mode=update-lockfile && yarn dedupe --strategy highest --mode=update-lockfile\""
}
DEBUG: exec completed(branch="renovate/node-rollback")
{
  "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/redacted\":\"/mnt/renovate/gh/redacted\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_ENABLE_IMMUTABLE_INSTALLS -e YARN_HTTP_TIMEOUT -e YARN_GLOBAL_FOLDER -e YARN_ENABLE_GLOBAL_CACHE -w \"/mnt/renovate/gh/redacted\" docker.io/renovate/node:16.15.0 bash -l -c \"install-tool corepack 0.11.2 && yarn install --mode=update-lockfile && yarn dedupe --strategy highest --mode=update-lockfile\"",
  "durationMs": 32366,
  "stdout": "redacted",
  "stderr": ""
}
DEBUG: yarn.lock needs updating(branch="renovate/node-rollback")
DEBUG: updateYarnOffline resolvedPaths(branch="renovate/node-rollback")
{
  "resolvedPaths": [
    ".yarn/cache",
    ".pnp.cjs",
    ".pnp.js",
    ".pnp.loader.mjs"
  ]
}
DEBUG: Updated 1 lock files(branch="renovate/node-rollback")
{
  "updatedArtifacts": [
    "yarn.lock"
  ]
}
DEBUG: 2 file(s) to commit(branch="renovate/node-rollback")
DEBUG: Preparing files for committing to branch renovate/node-rollback(branch="renovate/node-rollback")
DEBUG: Setting git author name(branch="renovate/node-rollback")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/node-rollback")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: git commit(branch="renovate/node-rollback")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/node-rollback",
    "commit": "c84eaa3a801922c384260286cdc7224ad8e7ffcb",
    "root": false,
    "summary": {
      "changes": 2,
      "insertions": 2,
      "deletions": 0
    }
  }
}
DEBUG: Fetching branch renovate/node-rollback(branch="renovate/node-rollback")
INFO: Branch created(branch="renovate/node-rollback")
{
  "commitSha": "c84eaa3a801922c384260286cdc7224ad8e7ffcb"
}
DEBUG: Ensuring PR(branch="renovate/node-rollback")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/node-rollback")
DEBUG: getBranchPr(renovate/node-rollback)(branch="renovate/node-rollback")
DEBUG: findPr(renovate/node-rollback, undefined, open)(branch="renovate/node-rollback")
DEBUG: findPr(renovate/node-rollback, undefined, closed)(branch="renovate/node-rollback")
DEBUG: Creating PR(branch="renovate/node-rollback")
{
  "prTitle": "Roll back Node.js to 16.15.0"
}
INFO: Creating Rollback PR(branch="renovate/node-rollback")
DEBUG: Creating PR(branch="renovate/node-rollback")
{
  "title": "Roll back Node.js to 16.15.0",
  "head": "redacted:renovate/node-rollback",
  "base": "next",
  "draft": false
}
DEBUG: PR created(branch="renovate/node-rollback")
{
  "pr": 2038,
  "draft": false
}
DEBUG: Adding labels 'type: dependencies' to #2038(branch="renovate/node-rollback")
INFO: PR created(branch="renovate/node-rollback")
{
  "pr": 2038,
  "prTitle": "Roll back Node.js to 16.15.0"
}
DEBUG: addParticipants(pr=2038)(branch="renovate/node-rollback")
DEBUG: Created Pull Request #2038(branch="renovate/node-rollback")
DEBUG: PR is not configured for automerge(branch="renovate/node-rollback")
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

- Use `releaseTimestamp` from `tagger` object
- Don't using commit date
- ⚠️ **Reset all existing caches** ⚠️

## Context

- Closes: #16374

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/datasource/github-tags/cache.ts [hunk 1]
```diff
@@ -26,9 +26,11 @@ query ($owner: String!, $name: String!, $cursor: String, $count: Int!) {
             target {
               ... on Commit {
                 hash: oid
```
Comment (zharinov) [inline lib/modules/datasource/github-tags/cache.ts:28]: I guess we still need to return commit hash instead of tag hash (e.g., how it's reflected in GitHub UI)

**Review by rarkins — APPROVED** [review]

File: lib/modules/datasource/github-tags/cache.ts (hunk 1 above)
Comment (rarkins) [reply lib/modules/datasource/github-tags/cache.ts:28]: Is this done?

File: lib/modules/datasource/github-tags/cache.spec.ts [hunk 2]
```diff
@@ -28,6 +28,8 @@ describe('modules/datasource/github-tags/cache', () => {
             type: 'Tag',
             target: {
               hash: 'abc',
+            },
+            tagger: {
               releaseTimestamp: '2020-04-09T10:00:00.000Z',
```
Comment (Shegox) [inline lib/modules/datasource/github-tags/cache.spec.ts:33]: Not sure if the date parser can do that automatically, but maybe we should adjust the test as well to reflect the data responded from graphql e.g. `2020-04-09T06:00:00.000-04:00` to ensure that it is correctly parsed

Comment (zharinov) [reply lib/modules/datasource/github-tags/cache.spec.ts:33]: I assumed downstream code has no problems with different timezone formats

Comment (Shegox) [reply lib/modules/datasource/github-tags/cache.spec.ts:33]: Wasn't sure about that, but checked as well and it seems that ` DateTime.fromISO(date);` does correctly manages to parse the date, so everything good 👍
