### PR TITLE
fix(github-actions): handle quotes

### LINKED ISSUE #14508: github-actions manager strips quotes and does not correctly handle end-of-line comments
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate seems to have issues with both quotes and end-of-line comments in GitHub actions workflow files.

With a workflow file of the following:

```yaml
name: "build"

on: ["push"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2" # comment after
```

renovate will produce update PRs that strip that information: https://github.com/zml2008/renovate-quoted-string-reproducer/pull/2

Quotes are stripped from version names even without a comment, but this only triggers PR creation when a version update is available. See the PRs on the reproduction repo for examples of the various cases.

Comments at the end of line will produce invalid PRs both with and without quotes, and even if the actual action is up-to-date

### Relevant debug logs

<details><summary>Logs of the extracted updates</summary>

```
DEBUG: Fetching changelog: https://github.com/actions/checkout (v2" # comment after -> v2)
DEBUG: Fetching changelog: https://github.com/actions/checkout (v2" # comment after -> v3)
DEBUG: Fetching changelog: https://github.com/actions/setup-java (v2 -> v3)
DEBUG: Fetching changelog: https://github.com/actions/github-script (v6 # comment after -> v6)
DEBUG: Not enough valid releases for dep actions/checkout
DEBUG: Not enough valid releases for dep actions/github-script
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "github-actions": [
      {
        "packageFile": ".github/workflows/build.yml",
        "deps": [
          {
            "depName": "actions/checkout",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "\"actions/checkout@v2\" # comment after",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v2\" # comment after",
            "depIndex": 0,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "v2",
                "newValue": "v2",
                "newMajor": 2,
                "newMinor": null,
                "updateType": "patch",
                "branchName": "renovate/actions-checkout-2.x"
              },
              {
                "bucket": "major",
                "newVersion": "v3",
                "newValue": "v3",
                "newMajor": 3,
                "newMinor": null,
                "updateType": "major",
                "branchName": "renovate/actions-checkout-3.x"
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/actions/checkout",
            "currentVersion": "v2\" # comment after",
            "isSingleVersion": true,
            "fixedVersion": "v2\" # comment after"
          },
          {
            "depName": "actions/setup-java",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "\"actions/setup-java@v2\"",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v2",
            "depIndex": 1,
            "updates": [
              {
                "bucket": "major",
                "newVersion": "v3",
                "newValue": "v3",
                "newMajor": 3,
                "newMinor": null,
                "updateType": "major",
                "branchName": "renovate/actions-setup-java-3.x"
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/actions/setup-java",
            "currentVersion": "v2",
            "isSingleVersion": true,
            "fixedVersion": "v2"
          },
          {
            "depName": "actions/setup-java",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "\"actions/setup-java@v3\"",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v3",
            "depIndex": 2,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/actions/setup-java",
            "currentVersion": "v3",
            "fixedVersion": "v3"
          },
          {
            "depName": "actions/github-script",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "replaceString": "actions/github-script@v6 # comment after",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v6 # comment after",
            "depIndex": 3,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "v6",
                "newValue": "v6",
                "newMajor": 6,
                "newMinor": null,
                "updateType": "patch",
                "branchName": "renovate/actions-github-script-6.x"
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/actions/github-script",
            "currentVersion": "v6 # comment after",
            "isSingleVersion": true,
            "fixedVersion": "v6 # comment after"
          }
        ]
      }
    ]
  }
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by hasanwhitesource**
## Changes

Replace string is now being taken without double quotes

## Context

Closes #14508 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/github-actions/extract.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ import type { PackageDependency, PackageFile } from '../types';
 
 const dockerRe = regEx(/^\s+uses: docker:\/\/([^"]+)\s*$/);
 const actionRe = regEx(
-  /^\s+-?\s+?uses: (?<replaceString>['"]?(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>[^\s'"]+)['"]?(?:\s+#\s+(?:renovate:\s+)?tag=(?<tag>\S+))?)/
+  /^\s+-?\s+?uses: ['"]?(?<replaceString>(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>[^\s'"]+)(?:['"]?\s+#\s+(?:renovate:\s+)?tag=(?<tag>\S+))?)/
```
Comment (viceice) [inline lib/modules/manager/github-actions/extract.ts:10]: i think this will cause issues with our tagging comment. did you verified the pinned dep scenario in a real repo?

Comment (rarkins) [reply lib/modules/manager/github-actions/extract.ts:10]: You mean like https://github.com/renovatebot/renovate/blob/ab8a9156007707f5cbe061515ab847e7f290c3bc/.github/workflows/build.yml#L66 ?

Comment (viceice) [reply lib/modules/manager/github-actions/extract.ts:10]: yes, or

```yaml
uses: 'actions/setup-node@56337c425554a6be30cdef71bf441f15be286854' # tag=v3.1.1 
uses: "actions/setup-node@56337c425554a6be30cdef71bf441f15be286854" # tag=v3.1.1 
``

Comment (hasanwhitesource) [reply lib/modules/manager/github-actions/extract.ts:10]: Would it be better if I convert this to `js-yaml` parsing instead of line by line regex like we did for gitlab-ci?
I thought to use the `js-yaml` library to read the file and also do some preprocessing on the file to fill a data structure that maps `uses` deps to comments if there are some. 
wdyt @viceice @rarkins ?

Comment (viceice) [reply lib/modules/manager/github-actions/extract.ts:10]: I don't think this makes it easier, as we need to parse those renovate tag comments to get the current version

**Review by rarkins — COMMENTED** [review]
Could you also test/demo this on a public repo? Can use same/similar as in the tests

**Comment by hasanwhitesource** [comment]
@rarkins yes tried it here are the prs : https://github.com/hasanwhitesource/renovate-quoted-string-reproducer/pulls

**Comment by rarkins** [comment]
@hasanwhitesource can you test some ones *without* quotes in the same repo too?

**Comment by hasanwhitesource** [comment]
Pr for a use without quotes:
https://github.com/hasanwhitesource/renovate-quoted-string-reproducer/pull/55/files

**Review by viceice — COMMENTED** [review]
LGTM, what happens on pin pr when there is a trailing comment?

**Comment by hasanwhitesource** [comment]
@viceice Can you provide an example please ? you mean something like "actions/checkout@v3.*" ?

**Comment by viceice** [comment]
> @viceice Can you provide an example please ? you mean something like "actions/checkout@v3.*" ?

no, pin digest PR. so from version to git-tag

**Comment by hasanwhitesource** [comment]
@viceice @rarkins a pr example using pinDigests : https://github.com/hasanwhitesource/renovate-quoted-string-reproducer/pull/58/files

**Review by viceice — APPROVED** [review]
