### PR TITLE
fix: optional re2 package

### LINKED ISSUE #4356: Unable to install Renovate since node-re2 was added
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Attempting to install Renovate fails due to permission issues since v19.30.11 on a fresh container. 

**To Reproduce**
```
> docker run -it node:10 /bin/bash

:/# node --version
v10.16.3

:/# npm install -g renovate
/usr/local/bin/renovate -> /usr/local/lib/node_modules/renovate/dist/renovate.js
/usr/local/bin/renovate-config-validator -> /usr/local/lib/node_modules/renovate/bin/config-validator.js

gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/10.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/renovate/node_modules/re2/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/renovate/node_modules/re2/.node-gyp'
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/renovate/node_modules/re2
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! re2@1.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the re2@1.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-23T14_46_01_169Z-debug.log
```

### PR DESCRIPTION
**Pull request by viceice**
This pr makes the `re2` package optional.

Closes #4356

### CODE REVIEW

File: lib/util/regex.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  new (pattern: string, flags?: string): RegExp;
+}
+
+const RegEx: RegExConstructor = (() => {
+  try {
+    // eslint-disable-next-line
+    const RE2 = require('re2');
+    // Test if native is working
+    new RE2('.*').exec('test');
+    logger.debug('Using RE2 as regex engine');
```
Comment (rarkins) [inline lib/util/regex.ts]: Will this debug log 1 time per run or N times?

Comment (ViceIce) [reply lib/util/regex.ts]: Should be on per run.

**Comment by ViceIce** [comment]
On a next pr i would like to move all other user regex to the new re2 package.
