### PR TITLE
fix: modified regex to use RE2

### LINKED ISSUE #11875: Consider re2 use for all regex
### Describe the proposed change(s).

Today we use `re2` for any user-provided regex, with the aim being we can't be the victim - intentionally or accidentally - of catastrophic backtracking.

But how do we make sure that we don't accidentally add a problematic regex in our own code? Wouldn't we essentially close off the risk if we used `re2` for any complex regex instead of using regex literals?

@viceice @JamieMagee

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes:

Updated regex  of these sub-folders:
`lib/config`
`lib/constants`
`lib/datasource`
to use RE2 using `regEx` function from `lib/util/regex`

## Context:

fixes #11875 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/config/migration.ts [hunk 1]
```diff
@@ -426,9 +437,14 @@ export function migrateConfig(
             schedules[i] = schedules[i].replace(' every day', '');
           }
           if (
-            /every (mon|tues|wednes|thurs|fri|satur|sun)day$/.test(schedules[i])
+            regEx(/every (mon|tues|wednes|thurs|fri|satur|sun)day$/).test(
```
Comment (viceice) [inline lib/config/migration.ts:440]: We should some of those regex to module scope const to improve memory usage and performance.

This should be done in a seperate PR

**Review by viceice — COMMENTED** [review]
Checked config folder

File: lib/config/migration.ts (hunk 1 above)
Comment (RahulGautamSingh) [reply lib/config/migration.ts:440]: I checked the `node-re2` docs and it says to use `RegExp` instead of `re2` for such cases and some other cases too.

Comment (rarkins) [reply lib/config/migration.ts:440]: @RahulGautamSingh can you be more explicit about exactly which docs sentence you are referring to?

Comment (RahulGautamSingh) [reply lib/config/migration.ts:440]: Above link takes us to the limitations section, under it we have 3 sections:
1. Backreferences
2. Lookahead Assertions
3. Mismatched Behavior

Under mismatched behavior this example
`var pattern = '(?:(a)|(b)|(c))+';`
seems similar to the one @viceice pointed out.

We also have some regex where we have lookaheads & backreferences in use so I have been testing almost each updated regex manually to prevent any failing test cases.

**Review by rarkins — CHANGES_REQUESTED** [review]

**Comment by rarkins** [comment]
@viceice I think there are advantages to leaving the current regex positioning as-is - including inside for loops - for easier review and backwards compatibility. But then should we create an issue to elevate any regexes inside loops to be outside the loop?

**Review by viceice — CHANGES_REQUESTED** [review]

**Review by rarkins — CHANGES_REQUESTED** [review]
I got through 15/36 files before finding a lot of `TODO #12070` which I have doubts about

**Comment by rarkins** [comment]
Ok, I will try going through the rest soon. I hadn't expected #12070 to have so many

**Review by rarkins — CHANGES_REQUESTED** [review]
Looks mostly good except vscode settings

**Review by rarkins — DISMISSED** [review]

**Comment by rarkins** [comment]
Needs deconflicting?

**Comment by RahulGautamSingh** [comment]
> Needs deconflicting?

yes

**Comment by rarkins** [comment]
I'm confused. Which PR do you need merged first?

**Comment by rarkins** [comment]
@RahulGautamSingh so have you added all necessary snapshot updates to this PR?

**Comment by rarkins** [comment]
@RahulGautamSingh can you update this PR to include on such example where the snapshots need updating? Then it's easier for us to understand and decide

**Comment by RahulGautamSingh** [comment]
> @RahulGautamSingh can you update this PR to include on such example where the snapshots need updating? Then it's easier for us to understand and decide

When I was rechecking the file to show an example of the error I found that the snapshots were fine and the real problem was incompatible RE2. I misunderstood the error the first time and thought that it was the snapshots. Sorry for the lapse in judgement. Also the files in which I had this problem are to be merged in future PRs.

This PR is okay to be merged and needs no further changes.

**Comment by RahulGautamSingh** [comment]
> > @RahulGautamSingh can you update this PR to include on such example where the snapshots need updating? Then it's easier for us to understand and decide
> @rarkins 
> When I was rechecking the file to show an example of the error I found that the snapshots were fine and the real problem was incompatible RE2. I misunderstood the error the first time and thought that it was the snapshots. Sorry for the lapse in judgement. Also the files in which I had this problem are to be merged in future PRs.
> 
> This PR is okay to be merged and needs no further changes.

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
