### PR TITLE
fix: allow json for endpoints argument

### LINKED ISSUE #2455: Endpoints CLI argument not parsed
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
passing `--endpoints` as an argument to the cli is not working at the moment, because this line assumes it's an object. https://github.com/renovatebot/renovate/blob/HEAD/lib/util/endpoints.js#L21
It is a string though, as the cli config parser has no coercion for json, hence platform of string is always undefined and `Failed to configure platform '${platform}': no endpoint defined` is a very confusing error for `'cannot be passed to the cli'`.

**To Reproduce**
add argument `--endpoints='{"platform":"docker","host":"docker.company.io"}'`

**Expected behavior**
I would like a coercion for json inputs for the cli argument so it's possible to pass secret docker credentials internally to the renovate cli tool.

### PR DESCRIPTION
**Pull request by eseliger**
Actually, just adding `cli: true` does not fix this problem as the parsing is still missing and it's interpreted as a string. This technically introduces a breaking change as it changes the way this command is interpreted. *BUT* this is only changing for the cli argument `--endpoints` and does not have any effect on the other ways to configure renovate. So, as it was impossible to use the `--endpoints` arg before, I would say it should be a fix and not a breaking change. Let me know what you think @rarkins 🙂 This would really be appreciated as it allows to globally configure access to internal docker registries for self deployed renovate bots!

Closes #2455

### CODE REVIEW

**Comment by rarkins** [comment]
@eseliger thanks for looking into it deeper. Because it's important for validation purposes to be considered a "list", I modified your solution to instead do a try/catch for list types so that JSON can be correctly parsed as you require. Can you confirm it's working as you expect?

File: lib/config/cli.js [hunk 1]
```diff
@@ -22,8 +22,16 @@ function getConfig(argv) {
 
   const coersions = {
     boolean: val => val === 'true',
-    list: val =>
-      val === '[]' || val === '' ? [] : val.split(',').map(el => el.trim()),
+    list: val => {
+      if (val === '[]' || val === '') {
```
Comment (eseliger) [inline lib/config/cli.js]: looks totally fine, but if I'm not mistaken, this check is not needed anymore then, as `[]` is caught by the `JSON.parse` and returns `[]` correctly, and the `''` throws an error `Unexpected end of input` so if falls back to `''.split(',')` which resolves to `[]` as well, so ll26-28 can be removed imo

Comment (rarkins) [reply lib/config/cli.js]: I decided to leave as-is, as otherwise it needs an extra test or two added to verify it. I think that `''` won't work as you expect. I might just remove the `[]` one.

Comment (eseliger) [reply lib/config/cli.js]: Alright, just wanted to keep the code clean
I can also add the two test-cases if you want me to. Otherwise this looks good-to-go to me

**Comment by rarkins** [comment]
Sure, please go ahead the simplify + add test cases if you don’t mind

**Comment by rarkins** [comment]
Thanks @eseliger

**Comment by eseliger** [comment]
Thank you for the amazing work
