### PR TITLE
fix: ignore .npmrc when the npmrc configuration is being used

### LINKED ISSUE #38794: fix(postUpgradeTasks): do not commit the `.npmrc` if the `npmrc` configuration is being used
### Describe the proposed change(s).

As noted in #38776, we should not be committing a `.npmrc` that's introduced by Renovate configuration.

We should:

- when a `postUpgradeTask` is executing, and the [`npmrc`](https://docs.renovatebot.com/configuration-options/#npmrc) configuration is specified:
  - internally override the `fileFilters` or `excludeCommitPaths` to not include the `.npmrc`
  - add a log message (`DEBUG`?) to inform the user that this is happening

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

Skip adding .npmrc file if the `npmrc` option is deteced

## Context

Please select one of the below:

- [x] This closes an existing Issue, Closes: #38794
- [ ] This doesn't close an Issue, but I accept the risk that this PR may be closed if maintainers disagree with its opening or implementation

## AI assistance disclosure

Did you use AI tools to create any part of this pull request?

Please select one option and, if yes, briefly describe how AI was used (e.g., code, tests, docs) and which tool(s) you used.

- [ ] No — I did not use AI for this contribution.
- [ ] Yes — minimal assistance (e.g., IDE autocomplete, small code completions, grammar fixes).
- [x] Yes — substantive assistance (AI generated non‑trivial portions of code, tests, or documentation).
- [ ] Yes — other (please describe):

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

The public repository: <URL>

### CODE REVIEW

**Comment by zharinov** [comment]
- https://github.com/renovate-testing/npmrc-post-upgrade-commit-5/pull/1/files

**Review by RahulGautamSingh — APPROVED** [review]

**Review by jamietanna — APPROVED** [review]
Thanks!

File: lib/workers/repository/update/branch/execute-post-upgrade-commands.ts [hunk 1]
```diff
@@ -217,7 +217,20 @@ export async function postUpgradeCommandsExecutor(
         `Checking ${addedOrModifiedFiles.length} added or modified files for post-upgrade changes`,
       );
 
+      const fileExcludes: string[] = [];
```
Comment (jamietanna) [inline lib/workers/repository/update/branch/execute-post-upgrade-commands.ts:220]: Thinking about this some more, should we be using https://docs.renovatebot.com/configuration-options/#excludecommitpaths here?

(And append `.npmrc` into here)?

Comment (zharinov) [reply lib/workers/repository/update/branch/execute-post-upgrade-commands.ts:220]: Maybe, though it's not directly used here in this post-upgrade code, so not sure how hard it'll be to make it work instead of this ad-hoc approach
