### PR TITLE
fix: Remove repository cache migrations

### LINKED ISSUE #17497: Remove cache migrations
### Describe the proposed change(s).

Let's remove all cache migration logic for v33

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

- Remove older revisions
- Leverage schema validation utility

## Context

- Closes #17497

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/cache/repository/impl/base.ts [hunk 1]
```diff
@@ -76,30 +50,12 @@ export abstract class RepoCacheBase implements RepoCache {
       }
       const oldCache = JSON.parse(rawOldCache) as unknown;
 
-      if (isValidRev13(oldCache)) {
-        await this.restoreFromRev13(oldCache);
+      if (schema.match(RepoCacheV13, oldCache)) {
```
Comment (zharinov) [inline lib/util/cache/repository/impl/base.ts:53]: @viceice @Gabriel-Ladzaretti This is our runtime schema validation with type narrowing

**Review by viceice — APPROVED** [review]

**Comment by rarkins** [comment]
I don't think it needs to wait for v33. It's hopefully unneeded by now, also the feature itself is still flagged as experimental
