### PR TITLE
Use .npmrc from repository for registry lookups

### LINKED ISSUE #291: Private module support in hosted mode
If renovate is run in "hosted" mode (e.g. GitHub app), then failures can occur when private repositories are referenced in `package.json`.

Example:

- renovate processes GitHub repository happyuser13/repo5
- This repo has a package.json referencing private npm module @happyuser13/privatemodule3

This will result in errors like:

> warn: Dependency not found: @happyuser13/privatemodule3
> error: Error updating branch renovate/eslint-4.x: Error: Could not generate new yarn.lock file

The warn happens when renovate is checking for upgrades to package.json and is not fatal. Howeve the error happens when `renovate` tries to generate an updated `yarn.lock` file and yarn fails to find/authenticate `@happyuser13/privatemodule3` and therefore renovate will fail for all other dependencies.

### PR DESCRIPTION
**Pull request by rarkins**
The goal of this PR is to allow `renovate` to use any credentials that are checked into an `.npmrc` file within the current registry. i.e. instead of searching the filesystem of the machine running `renovate` for its npm credentials, the contents of the repository's `.npmrc` would be used instead.

Important to note: if an `.npmrc` file is found in the target repository, any file system `.npmrc` credentials will be *ignored*.

Also note: Not looking up `.yarnrc` as it does not seem relevant to this

Closes #291

### CODE REVIEW

File: lib/api/npm.js [hunk 1]
```diff
@@ -7,25 +7,31 @@ const registryAuthToken = require('registry-auth-token');
...
 
+async function setNpmrc(input) {
+  npmrc = input;
+}
+
 async function getDependency(name) {
   logger.debug(`getDependency(${name})`);
   const scope = name.split('/')[0];
-  const regUrl = registryUrl(scope);
+  const regUrl = registryUrl(scope, { npmrc });
```
Comment (rarkins) [inline lib/api/npm.js]: These configuration options are always passed to `registryUrl` and `registryAuthToken`, but if they are null then the file system will be used instead.

File: lib/api/npm.js [hunk 2]
```diff
@@ -7,25 +7,31 @@ const registryAuthToken = require('registry-auth-token');
...
 };
 
 let npmCache = {};
+let npmrc = null;
 
 function resetCache() {
   npmCache = {};
 }
 
+async function setNpmrc(input) {
```
Comment (rarkins) [inline lib/api/npm.js]: This needs to be called once per-repository to overwrite previous settings.

**Comment by rarkins** [comment]
@hbetts I would appreciate your review here, particularly due to your previous experience with registry auth token. This code should result in the same behaviour for "self hosted" implementations like yours.

**Comment by rarkins** [comment]
I'm going to merge this as I think it's safely backwards-compatible

File: lib/api/npm.js (hunk 1 above)
Comment (dherges) [reply lib/api/npm.js]: @rarkins This line does not work w/ a private npm registry when the `.npmrc` is read from target repository.  Example:

```
npmrc = { registry: 'https://my.corporate.local/npm-private/' }
regUrl = https://registry.npmjs.org/
pkgUrl = https://registry.npmjs.org/sort-object
```

It looks like [registry-url does not read that second paramter](https://github.com/sindresorhus/registry-url/blob/master/index.js)

The private npm registry does work, when I put the .npmrc file to the renovate deployment folder, i.e.:

```
|- node_modules
   |- .bin/renovate
|- .npmrc
```

Comment (dherges) [reply lib/api/npm.js]: When read from that second `.npmrc`, the url is constructed right:

```
regUrl https://my.corporate.local/npm-private/
pkgUrl https://my.corporate.local/npm-private/sort-object
{ registry: 'https://my.corporate.local/npm-private/' }
```

It works when there are no private packages references. When renovate tries to read npm packages that are only available on the private registry, it errors.

Comment (rarkins) [reply lib/api/npm.js]: @dherges thanks. could you raise this as a new issue, so we can discuss there? I'll ask questions to clarify then, as otherwise they might get a little lost inside this older PR

Comment (rarkins) [reply lib/api/npm.js]: FYI the code for this has changed just recently, although it may be "differently wrong". I see what you mean about how the registry appears to be being ignored

Comment (rarkins) [reply lib/api/npm.js]: I opened #763
