### PR TITLE
fix(manager/mix): ignore comments when extracting deps

### LINKED ISSUE #18462: bot tries to update commented mix dependency
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate bot tried to update a mix dependency that is actually commented out in `mix.exs`.

imagen

It then unsurprisingly reports an artifact upload problem because the dependency is not found.

### Relevant debug logs

<details><summary>Logs</summary>

```
{
  "artifactErrors": [
    {
      "lockFile": "mix.lock",
      "stderr": "Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/scoville/poblano\":\"/mnt/renovate/gh/scoville/poblano\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/scoville/poblano\" docker.io/renovate/sidecar bash -l -c \"install-tool erlang 24.3.4.0 && install-tool elixir v1.14.1 && mix deps.update broadway_dashboard\"\n** (Mix) Unknown dependency broadway_dashboard for environment dev\n"
    }
  ]
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- modify regex to ignore comments

## Context
- Closes: #18462

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/mix/extract.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ import type { PackageDependency, PackageFile } from '../types';
 
 const depSectionRegExp = regEx(/defp\s+deps.*do/g);
 const depMatchRegExp = regEx(
-  /{:(?<depName>\w+),\s*(?<datasource>[^:"]+)?:?\s*"(?<currentValue>[^"]+)",?\s*(?:organization: "(?<organization>.*)")?.*}/gm
+  /[^#]{:(?<depName>\w+),\s*(?<datasource>[^:"]+)?:?\s*"(?<currentValue>[^"]+)",?\s*(?:organization: "(?<organization>.*)")?.*}/gm
```
Comment (viceice) [inline lib/modules/manager/mix/extract.ts:9]: 🤔 is `#` a comment line character? so we can simply skip all lines if they start with `/^\s*#/m` ?

Comment (RahulGautamSingh) [reply lib/modules/manager/mix/extract.ts:9]: I think so. Do you have in mind some cases where this might cause problems?

Comment (viceice) [reply lib/modules/manager/mix/extract.ts:9]: yes, that regex requires any non `#` char before depName. so when there is no space before it doesn't match. not sure if this can happen.

Comment (RahulGautamSingh) [reply lib/modules/manager/mix/extract.ts:9]: True, it works but isn't accurate.

Comment (RahulGautamSingh) [reply lib/modules/manager/mix/extract.ts]: One thing still remains:
To handle commets like these:

```exs
 {:postgrex, "~> 0.8.1"},    #  {:broadway_dashboard, "~> 0.2.2"},
```

**Review by rarkins — APPROVED** [review]

File: lib/modules/manager/mix/extract.ts [hunk 2]
```diff
@@ -8,15 +8,17 @@ const depSectionRegExp = regEx(/defp\s+deps.*do/g);
...
   logger.trace('mix.extractPackageFile()');
   const deps: PackageDependency[] = [];
-  const contentArr = content.split(newlineRegex);
-
+  const contentArr = content
+    .split(newlineRegex)
+    .filter((line) => !commentMatchRegExp.test(line));
   for (let lineNumber = 0; lineNumber < contentArr.length; lineNumber += 1) {
     if (contentArr[lineNumber].match(depSectionRegExp)) {
       logger.trace(`Matched dep section on line ${lineNumber}`);
```
Comment (viceice) [inline lib/modules/manager/mix/extract.ts:24]: this should be removed, as linenumer is now wrong when comment lines are skipped 😕
