### PR TITLE
fix(yarn): package.json resolutions patch in yarn was clobbered

### LINKED ISSUE #9509: Yarn 2 with patch is clobbered
**What Renovate type, platform and version are you using?**

Hosted Renovate over GitHub app

**Describe the bug**

If you use a patch file in yarn 2, for example: (there's every reason to believe this happens with any prefix, not just carat)
```
  "dependencies": {
    "my-library": "^25.14.0"
  },
  "resolutions": {
    "my-library": "patch:my-library@npm:^25.14.0#.yarn/patches/my-library.patch"
  }
```

when Renovate finds an update, it clobbers the entire line, giving me this instead:
```
  "dependencies": {
    "my-library": "^25.14.2"
  },
  "resolutions": {
    "my-library": "^25.14.2",
  },
```

Ideally, it should just update the part of the patch and let yarn patching fail if there are problems:
```
  "dependencies": {
    "my-library": "^25.14.2"
  },
  "resolutions": {
    "my-library": "patch:my-library@npm:^25.14.2#.yarn/patches/my-library.patch"
  }
```

**Relevant debug logs**

```
INFO: Repository started
{
  "renovateVersion": "24.113.0"
}
DEBUG: Using localDir: /mnt/renovate/gh/AaronBuxbaum/renovate-repro
DEBUG: Repository cache is valid
DEBUG: initRepo("AaronBuxbaum/renovate-repro")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: No dangling containers to remove
DEBUG: AaronBuxbaum/renovate-repro default branch = master
DEBUG: Using app token for git init
DEBUG: resetMemCache()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: Initializing git repository into /mnt/renovate/gh/AaronBuxbaum/renovate-repro
DEBUG: git clone completed
{
  "durationMs": 784
}
DEBUG: latest repository commit
{
  "latestCommit": {
    "hash": "c5db84984f287dce15a447655a1046a6fdd5bb2c",
    "date": "2021-04-12T13:17:34-04:00",
    "message": "Make it a little more complex",
    "refs": "HEAD -> master, origin/master, origin/HEAD",
    "body": "",
    "author_name": "Aaron Buxbaum",
    "author_email": "me@aaronbuxbaum.com"
  }
}
DEBUG: Setting git author name
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: Config file exists
{
  "fileName": "renovate.json"
}
DEBUG: Retrieving issueList
DEBUG: Retrieved 0 issues
DEBUG: Repo is onboarded
DEBUG: Found renovate.json config file
DEBUG: Repository config
{
  "fileName": "renovate.json",
  "config": {
    "extends": [
      "config:base"
    ]
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ]
  }
}
DEBUG: Found repo ignorePaths
{
  "ignorePaths": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/examples/**",
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**",
    "**/__fixtures__/**"
  ]
}
DEBUG: detectSemanticCommits()
DEBUG: getCommitMessages
DEBUG: Semantic commits detection: unknown
DEBUG: No semantic commits detected
DEBUG: Setting branchPrefix: renovate/
DEBUG: No vulnerability alerts found
DEBUG: No vulnerability alerts found
DEBUG: processRepo()
DEBUG: No baseBranches
DEBUG: extract()
DEBUG: Setting current branch to master
DEBUG: latest commit
{
  "branchName": "master",
  "latestCommitDate": "2021-04-12T13:17:34-04:00"
}
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible
DEBUG: Using file match: (^|/)requirements\.ya?ml$ for manager ansible-galaxy
DEBUG: Using file match: (^|/)galaxy\.ya?ml$ for manager ansible-galaxy
DEBUG: Using file match: azure.*pipelines?.*\.ya?ml$ for manager azure-pipelines
DEBUG: Using file match: (^|/)batect(-bundle)?\.yml$ for manager batect
DEBUG: Using file match: (^|/)batect$ for manager batect-wrapper
DEBUG: Using file match: (^|/)WORKSPACE(|\.bazel)$ for manager bazel
DEBUG: Using file match: \.bzl$ for manager bazel
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite
DEBUG: Using file match: (^|/)Gemfile$ for manager bundler
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci
DEBUG: Using file match: (^|/)cloudbuild.ya?ml for manager cloudbuild
DEBUG: Using file match: (^|/)Podfile$ for manager cocoapods
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: Using file match: (^|/|\.)Dockerfile$ for manager dockerfile
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci
DEBUG: Using file match: (^|/).gitmodules$ for manager git-submodules
DEBUG: Using file match: ^\.github\/workflows\/[^/]+\.ya?ml$ for manager github-actions
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci-include
DEBUG: Using file match: (^|/)go.mod$ for manager gomod
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle
DEBUG: Using file match: (^|/)gradle.properties$ for manager gradle
DEBUG: Using file match: (^|/)gradle.properties$ for manager gradle-lite
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle-lite
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper
DEBUG: Using file match: (^|/)requirements\.yaml$ for manager helm-requirements
DEBUG: Using file match: (^|/)values.yaml$ for manager helm-values
DEBUG: Using file match: (^|/)helmfile.yaml$ for manager helmfile
DEBUG: Using file match: (^|/)Chart.yaml$ for manager helmv3
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew
DEBUG: Using file match: \.html?$ for manager html
DEBUG: Using file match: (^|/)plugins\.(txt|ya?ml)$ for manager jenkins
DEBUG: Using file match: (^|/)kustomization\.yaml for manager kustomize
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen
DEBUG: Using file match: \.pom\.xml$ for manager maven
DEBUG: Using file match: (^|/)pom\.xml$ for manager maven
DEBUG: Using file match: (^|/)package.js$ for manager meteor
DEBUG: Using file match: (^|/)mix\.exs$ for manager mix
DEBUG: Using file match: ^.node-version$ for manager nodenv
DEBUG: Using file match: (^|/)package.json$ for manager npm
DEBUG: Using file match: \.(?:cs|fs|vb)proj$ for manager nuget
DEBUG: Using file match: \.(?:props|targets)$ for manager nuget
DEBUG: Using file match: \.config\/dotnet-tools\.json$ for manager nuget
DEBUG: Using file match: (^|/)\.nvmrc$ for manager nvm
DEBUG: Using file match: (^|/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup
DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry
DEBUG: Using file match: (^|/)\.pre-commit-config\.yaml$ for manager pre-commit
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version
DEBUG: Using file match: \.sbt$ for manager sbt
DEBUG: Using file match: project/[^/]*.scala$ for manager sbt
DEBUG: Using file match: (^|/)setup\.cfg$ for manager setup-cfg
DEBUG: Using file match: (^|/)Package\.swift for manager swift
DEBUG: Using file match: \.tf$ for manager terraform
DEBUG: Using file match: (^|/)\.terraform-version$ for manager terraform-version
DEBUG: Using file match: (^|/)terragrunt\.hcl$ for manager terragrunt
DEBUG: Using file match: (^|/)\.terragrunt-version$ for manager terragrunt-version
DEBUG: Using file match: ^.travis.yml$ for manager travis
DEBUG: Matched 1 file(s) for manager npm: package.json
DEBUG: npm file package.json has name "renovate-repro"
DEBUG: Detecting Lerna and Yarn Workspaces
DEBUG: Finding locked versions
DEBUG: Found npm package files
DEBUG: Found 1 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "master",
  "stats": {
    "managers": {
      "npm": {
        "fileCount": 1,
        "depCount": 2
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 2
    }
  }
}
DEBUG: Package releases lookups complete
{
  "baseBranch": "master"
}
DEBUG: branchifyUpgrades
DEBUG: Using group branchName template
DEBUG: Dependency lodash is part of group lodash monorepo
DEBUG: 1 flattened updates found: lodash
DEBUG: Returning 1 branch(es)
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "npm": [
      {
        "packageFile": "package.json",
        "deps": [
          {
            "depType": "dependencies",
            "depName": "lodash",
            "currentValue": "^4.16.0",
            "datasource": "npm",
            "prettyDepType": "dependency",
            "depIndex": 0,
            "updates": [
              {
                "updateType": "pin",
                "isPin": true,
                "newValue": "4.17.21",
                "newMajor": 4,
                "branchName": "renovate/pin-dependencies"
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/lodash/lodash",
            "homepage": "https://lodash.com/"
          },
          {
            "depType": "resolutions",
            "depName": "lodash",
            "currentValue": "patch:lodash@npm:4.16.0#patches/lodash.patch",
            "skipReason": "unknown-version",
            "prettyDepType": "resolutions",
            "depIndex": 1,
            "updates": []
          }
        ],
        "packageJsonName": "renovate-repro",
        "packageJsonType": "app",
        "yarnLock": "yarn.lock",
        "managerData": {},
        "skipInstalls": true,
        "constraints": {
          "yarn": "^2.2.0"
        },
        "lockFiles": [
          "yarn.lock"
        ]
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 1 branch: renovate/pin-dependencies
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 2 Pull Requests
DEBUG: currentHourStart=2021-04-12T17:00:00.000+00:00
DEBUG: PR hourly limit remaining: 1
DEBUG: Calculating prConcurrentLimit (20)
DEBUG: getBranchPr(renovate/pin-dependencies)
DEBUG: findPr(renovate/pin-dependencies, undefined, open)
DEBUG: findPr(renovate/pin-dependencies, undefined, closed)
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 20
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 1
}
DEBUG: PullRequests limit = 1
DEBUG: Calculating branchConcurrentLimit (20)
DEBUG: 0 already existing branches found:
DEBUG: Branch concurrent limit remaining: 20
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 20
}
DEBUG: Branches limit = 20
DEBUG: processBranch with 1 upgrades(branch="renovate/pin-dependencies")
DEBUG: Setting current branch to master(branch="renovate/pin-dependencies")
DEBUG: latest commit(branch="renovate/pin-dependencies")
{
  "branchName": "master",
  "latestCommitDate": "2021-04-12T13:17:34-04:00"
}
DEBUG: getBranchPr(renovate/pin-dependencies)(branch="renovate/pin-dependencies")
DEBUG: findPr(renovate/pin-dependencies, undefined, open)(branch="renovate/pin-dependencies")
DEBUG: findPr(renovate/pin-dependencies, undefined, closed)(branch="renovate/pin-dependencies")
DEBUG: branchExists=false(branch="renovate/pin-dependencies")
DEBUG: Branch has 1 upgrade(s)(branch="renovate/pin-dependencies")
DEBUG: recreateClosed is true(branch="renovate/pin-dependencies")
DEBUG: Checking schedule(at any time, null)(branch="renovate/pin-dependencies")
DEBUG: No schedule defined(branch="renovate/pin-dependencies")
DEBUG: Branch needs creating(branch="renovate/pin-dependencies")
DEBUG: Using reuseExistingBranch: false(branch="renovate/pin-dependencies")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/pin-dependencies")
DEBUG: npm.updateDependency(): dependencies.lodash = 4.17.21(branch="renovate/pin-dependencies")
DEBUG: Upgraded dependency exists in yarn resolutions but is different version(branch="renovate/pin-dependencies")
{
  "depName": "lodash",
  "depKey": "lodash",
  "oldVersion": "^4.16.0",
  "resolutionsVersion": "patch:lodash@npm:4.16.0#patches/lodash.patch"
}
DEBUG: Updating lodash in package.json(branch="renovate/pin-dependencies")
DEBUG: Updated 1 package files(branch="renovate/pin-dependencies")
DEBUG: Getting updated lock files(branch="renovate/pin-dependencies")
DEBUG: Writing package.json files(branch="renovate/pin-dependencies")
{
  "packageFiles": [
    "package.json"
  ]
}
DEBUG: Writing any updated package files(branch="renovate/pin-dependencies")
DEBUG: Writing package.json(branch="renovate/pin-dependencies")
DEBUG: No npmrc file found in repository(branch="renovate/pin-dependencies")
DEBUG: Writing updated .npmrc file to /mnt/renovate/gh/AaronBuxbaum/renovate-repro/.npmrc(branch="renovate/pin-dependencies")
DEBUG: Generating yarn.lock for .(branch="renovate/pin-dependencies")
DEBUG: Spawning yarn install to create /mnt/renovate/gh/AaronBuxbaum/renovate-repro/yarn.lock(branch="renovate/pin-dependencies")
DEBUG: No node constraint found - using latest(branch="renovate/pin-dependencies")
DEBUG: Using docker to execute(branch="renovate/pin-dependencies")
DEBUG: No tag or tagConstraint specified(branch="renovate/pin-dependencies")
{
  "image": "docker.io/renovate/node"
}
DEBUG: Fetching Docker image: docker.io/renovate/node(branch="renovate/pin-dependencies")
DEBUG: Finished fetching Docker image(branch="renovate/pin-dependencies")
DEBUG: Executing command(branch="renovate/pin-dependencies")
{
  "command": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/AaronBuxbaum/renovate-repro\":\"/mnt/renovate/gh/AaronBuxbaum/renovate-repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_HTTP_TIMEOUT -e YARN_ENABLE_SCRIPTS -w \"/mnt/renovate/gh/AaronBuxbaum/renovate-repro\" docker.io/renovate/node bash -l -c \"npm i -g yarn && yarn install\""
}
DEBUG: exec completed(branch="renovate/pin-dependencies")
{
  "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/AaronBuxbaum/renovate-repro\":\"/mnt/renovate/gh/AaronBuxbaum/renovate-repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_HTTP_TIMEOUT -e YARN_ENABLE_SCRIPTS -w \"/mnt/renovate/gh/AaronBuxbaum/renovate-repro\" docker.io/renovate/node bash -l -c \"npm i -g yarn && yarn install\"",
  "durationMs": 8897,
  "stdout": "\n> yarn@1.22.10 preinstall /home/ubuntu/.npm-global/lib/node_modules/yarn\n> :; (node ./preinstall.js > /dev/null 2>&1 || true)\n\n/home/ubuntu/.npm-global/bin/yarn -> /home/ubuntu/.npm-global/lib/node_modules/yarn/bin/yarn.js\n/home/ubuntu/.npm-global/bin/yarnpkg -> /home/ubuntu/.npm-global/lib/node_modules/yarn/bin/yarn.js\n+ yarn@1.22.10\nadded 1 package in 1.687s\n➤ YN0000: ┌ Resolution step\n➤ YN0000: └ Completed in 0s 300ms\n➤ YN0000: ┌ Fetch step\n➤ YN0013: │ No packages were cached - one package had to be fetched\n➤ YN0019: │ lodash-npm-4.16.0-63abe90291-638e47679f.zip appears to be unused - removing\n➤ YN0019: │ lodash-patch-0b3fe55333-31aafda596.zip appears to be unused - removing\n➤ YN0000: └ Completed in 2s 65ms\n➤ YN0000: ┌ Link step\n➤ YN0000: └ Completed in 0s 308ms\n➤ YN0000: Done in 2s 719ms\n",
  "stderr": ""
}
DEBUG: yarn.lock needs updating(branch="renovate/pin-dependencies")
DEBUG: updateYarnOffline resolvedPaths(branch="renovate/pin-dependencies")
{
  "resolvedPaths": [
    ".yarn/cache",
    ".pnp"
  ]
}
DEBUG: Updated 5 lock files(branch="renovate/pin-dependencies")
{
  "updatedArtifacts": [
    "yarn.lock",
    ".pnp.js",
    ".yarn/cache/lodash-npm-4.17.21-6382451519-4983720b9a.zip",
    ".yarn/cache/lodash-npm-4.16.0-63abe90291-638e47679f.zip (delete)",
    ".yarn/cache/lodash-patch-0b3fe55333-31aafda596.zip (delete)"
  ]
}
DEBUG: 5 file(s) to commit(branch="renovate/pin-dependencies")
DEBUG: Committing files to branch renovate/pin-dependencies(branch="renovate/pin-dependencies")
DEBUG: git commit(branch="renovate/pin-dependencies")
{
  "result": {
    "author": null,
    "branch": "renovate/pin-dependencies",
    "commit": "a946966",
    "root": false,
    "summary": {
      "changes": 6,
      "insertions": 31,
      "deletions": 38
    }
  }
}
DEBUG: git push(branch="renovate/pin-dependencies")
{
  "result": {
    "pushed": [
      {
        "deleted": false,
        "tag": false,
        "branch": true,
        "new": true,
        "alreadyUpdated": false,
        "local": "refs/heads/renovate/pin-dependencies",
        "remote": "refs/heads/renovate/pin-dependencies"
      }
    ],
    "branch": {
      "local": "renovate/pin-dependencies",
      "remote": "renovate/pin-dependencies",
      "remoteName": "origin"
    },
    "remoteMessages": {
      "all": [
        "Create a pull request for 'renovate/pin-dependencies' on GitHub by visiting:",
        "https://github.com/AaronBuxbaum/renovate-repro/pull/new/renovate/pin-dependencies"
      ],
      "pullRequestUrl": "https://github.com/AaronBuxbaum/renovate-repro/pull/new/renovate/pin-dependencies"
    }
  }
}
INFO: Branch created(branch="renovate/pin-dependencies")
{
  "commitSha": "a946966"
}
DEBUG: Ensuring PR(branch="renovate/pin-dependencies")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/pin-dependencies")
DEBUG: getBranchPr(renovate/pin-dependencies)(branch="renovate/pin-dependencies")
DEBUG: findPr(renovate/pin-dependencies, undefined, open)(branch="renovate/pin-dependencies")
DEBUG: findPr(renovate/pin-dependencies, undefined, closed)(branch="renovate/pin-dependencies")
DEBUG: Creating PR(branch="renovate/pin-dependencies")
{
  "prTitle": "Pin dependency lodash to 4.17.21"
}
DEBUG: Creating PR(branch="renovate/pin-dependencies")
{
  "title": "Pin dependency lodash to 4.17.21",
  "head": "AaronBuxbaum:renovate/pin-dependencies",
  "base": "master",
  "draft": false
}
DEBUG: PR created(branch="renovate/pin-dependencies")
{
  "pr": 3,
  "draft": false
}
DEBUG: Adding labels '' to #3(branch="renovate/pin-dependencies")
INFO: PR created(branch="renovate/pin-dependencies")
{
  "pr": 3,
  "prTitle": "Pin dependency lodash to 4.17.21"
}
DEBUG: Created Pull Request #3(branch="renovate/pin-dependencies")
DEBUG: Checking #3 for automerge(branch="renovate/pin-dependencies")
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge(branch="renovate/pin-dependencies")
DEBUG: getBranchPr(renovate/pin-dependencies)
DEBUG: findPr(renovate/pin-dependencies, undefined, open)
DEBUG: Found PR #3
DEBUG: Returning from graphql open PR list
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/pin-dependencies"
  ],
  "renovateBranches": [
    "renovate/pin-dependencies"
  ]
}
DEBUG: remainingBranches=
DEBUG: No branches to clean up
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {
    "init": 2949,
    "extract": 1400,
    "lookup": 130,
    "update": 18050
  },
  "total": 22937
}
DEBUG: http statistics
{
  "hostStats": [
    "api.github.com, 7 requests, 307ms request average, 0ms queue average"
  ],
  "totalRequests": 7
}
INFO: Repository finished
{
  "durationMs": 22937
}
```

**Have you created a minimal reproduction repository?**
https://github.com/AaronBuxbaum/renovate-repro

Note the issue here: https://github.com/AaronBuxbaum/renovate-repro/pull/3/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes

in npm manager inside of package.json the if resolutions section had "patch" protocol, it will get overridden by a version.
now the patch protocol will stay, and only the version will be updated: example is in the issue.

## Context

i'm making these changes because it was requested in the below issue.
Closes #9509 

Notes:
This solution applies to the Patch protocol.
We might have same issue in the future with other npm protocols, but i'm not sure how common these are.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [1] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [1] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/npm/update/dependency/index.ts [hunk 1]
```diff
@@ -25,7 +28,20 @@ function replaceAsString(
...
   const searchString = `"${oldValue}"`;
-  const newString = `"${newValue}"`;
+  let newString = `"${newValue}"`;
+
+  if (oldValue.match(patchReg)) {
+    //todo tests
+    // "patch:lodash@npm:4.16.0#patches/lodash.patch".replace(new RegExp("(patch:lodash@(npm:)?[><=~^]+).*#"), "$1"+newValue+"#");
+    // "patch:metro@0.58.0#./.patches/metro.patch".replace(new RegExp("(patch:metro@(npm:)?[><=~^]+).*#"), "$1"+newValue+"#";
+    // "patch:metro@^0.58.0#./.patches/metro.patch".replace(new RegExp("(patch:metro@(npm:)?[><=~^]+).*#"), "$1"+newValue+"#");
+    const regex = new RegExp('(patch:' + depName + '@(npm:)?).*#');
```
Comment (viceice) [inline lib/modules/manager/npm/update/dependency/index.ts:38]:
```suggestion
    const regex = new regEx('(patch:' + depName + '@(npm:)?).*#');
```
Use our regex function

File: lib/modules/manager/npm/update/dependency/index.ts [hunk 2]
```diff
@@ -25,7 +28,20 @@ function replaceAsString(
   }
   // Look for the old version number
   const searchString = `"${oldValue}"`;
-  const newString = `"${newValue}"`;
+  let newString = `"${newValue}"`;
+
+  if (oldValue.match(patchReg)) {
```
Comment (viceice) [inline lib/modules/manager/npm/update/dependency/index.ts:33]:
```suggestion
  if (patchReg.test(oldValue)) {
```

File: lib/modules/manager/npm/update/dependency/index.ts [hunk 3]
```diff
@@ -1,9 +1,12 @@
 import { dequal } from 'dequal';
 import type { PackageJson } from 'type-fest';
 import { logger } from '../../../../../logger';
+import { regEx } from '../../../../../util/regex';
 import { matchAt, replaceAt } from '../../../../../util/string';
 import type { UpdateDependencyConfig } from '../../../types';
 
+const patchReg = regEx('patch:.*@(npm:)?.*#.*');
```
Comment (viceice) [inline lib/modules/manager/npm/update/dependency/index.ts:8]: I think we should ignore dep if it has any unsupported protocol.

**Review by viceice — CHANGES_REQUESTED** [review]
Need tests and coverage

File: lib/modules/manager/npm/update/dependency/index.ts (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts:8]: These are the `npm` protocols that we might face :
``` NPM("npm"),
    GIT("git"),
    GIT_SSH("git+ssh"),
    GIT_HTTP("git+http"),
    GIT_HTTPS("git+https"),
    GIT_FILE("git+file"),
    GITHUB("github"),
    FILE("file"),
    LINK("link"),
    PATCH("patch"),
    PORTAL("portal"),
    EXEC("exec"),
    HTTP("http"),
    HTTPS("https");```

the normal versioning is the `npm` protocol, in yarn.lock of yarn v2.0+  it will show {name}@npm:{version}
you might not see it in package.json directly since its redundant and no one puts it in there but it is a thing
try it out:
add to the package.json dependencies:
```
  "dependencies": {
    "numpy": "npm:0.0.1"
  },
```
it works, its possible.
i believe you are familiar with the `git` protocols, since its commonly used in some projects..
but other stuff is a bit rare to find.

i'm not sure how to support all these protocols FULLY currently, they are not commonly used, but i believe we will face them eventually, since yarn 2.0+ uses them normally.

Comment (viceice) [reply lib/modules/manager/npm/update/dependency/index.ts:8]: we don't need to support them yet, but we should notice and ignore them to not propose wrong updates

File: lib/modules/manager/npm/update/dependency/index.ts (hunk 1 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts:38]: i'm trying but i'm not familiar with this regEx and for some reason whatever i do it doesnt work
`   const regex = regEx('(patch:.*@(npm:)?).*#');` ////// THIS WORKS
but when i try to do it with parameters, by copying the way from other regEx.. it doesnt work, 
what am i missing?
`    const regex = regEx(/^(patch:(?<depName>@(npm:)?)).*#'$/);`

Comment (viceice) [reply lib/modules/manager/npm/update/dependency/index.ts:38]: You probably need to escape special chars? Re2 is more strict in those areas

File: lib/modules/manager/npm/update/dependency/index.ts (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts:8]: well i'm not sure what we do support, so i dont want to go breaking anything,
this needs lots of testing for each protocol to make sure we dont support it. 
unless any of you guys @rarkins / @viceice can tell what we dont support for sure, so i can ignore the rest,
Do we have any documentation for what protocols we support?

Comment (viceice) [reply lib/modules/manager/npm/update/dependency/index.ts:8]: i think we don't support any other protocol, so we should ignore them. @rarkins WDYT?

File: lib/modules/manager/npm/update/dependency/index.ts [hunk 4]
```diff
@@ -25,7 +28,16 @@ function replaceAsString(
   }
   // Look for the old version number
   const searchString = `"${oldValue}"`;
-  const newString = `"${newValue}"`;
+  let newString = `"${newValue}"`;
+
+  if (patchReg.test(oldValue)) {
+    const regex = regEx('(patch:' + depName + '@(npm:)?).*#');
+    const patch = oldValue.replace(regex, '$1' + newValue + '#');
```
Comment (viceice) [inline lib/modules/manager/npm/update/dependency/index.ts:35]:
```suggestion
    const regex = regEx(`(?<value>patch:${depName}@(?:npm:)?).*#`);
    const patch = oldValue.replace(regex, `$<value>${newValue}#`);
```

use named capture group, see failed test. We propaböy need to escape `depName` somehow too. 🤔

File: lib/modules/manager/npm/update/dependency/index.ts (hunk 3 above)
Comment (rarkins) [reply lib/modules/manager/npm/update/dependency/index.ts:8]: Ignore

Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts:8]: are you saying you do not support:
image

Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts:8]: i will ignore them, but it might break some stuff you already have working, since this is the replace strings functionality of npm

Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts:8]: there you go, 
I broke it, you already support git protocols
image

File: lib/modules/manager/npm/update/dependency/index.ts (hunk 4 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts]: i can be less accurate and go with ".*" intead of "depName", will work too if i need to get rid of the depName

Comment (viceice) [reply lib/modules/manager/npm/update/dependency/index.ts]: Thats why i suggest named capture group, which always work.

Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts]: i fixed it in my own normal way  :D capturing groups dont help me here

File: lib/modules/manager/npm/update/dependency/index.ts [hunk 5]
```diff
@@ -91,6 +106,11 @@ export function updateDependency({
       logger.trace('Version is already updated');
       return fileContent;
     }
+    // istanbul ignore if
+    if (noSupportRe.test(oldVersion)) {
+      logger.trace('Version protocol is not supported');
+      return fileContent;
+    }
```
[the remark this answers is not in the document]
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts:113]: i think you are wrong, the `package.json `parsing happnes right here in the `index.ts`, the extract is for the `package-lock.json` only.

i made it part of the first 3 checks:
image

where in the extract do you wanna move it?

[the remark this answers is not in the document]
Comment (rarkins) [reply lib/modules/manager/npm/update/dependency/index.ts:113]: Somewhere within https://github.com/renovatebot/renovate/tree/main/lib/modules/manager/npm/extract

What's the extraction result for this type of `package.json` today look today? Do we have a test fixture already or need to add?

[the remark this answers is not in the document]
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts]: it goes into an npmPackage object see this:
```
export interface NpmPackage extends PackageJson {
  renovate?: unknown;
  _from?: any;
  _args?: any;
  _id?: any;
}

export type LockFileEntry = Record<
  string,
  { version: string; integrity?: boolean }
>;

export interface LockFile {
  lockedVersions: Record<string, string>;
  lockfileVersion?: number; // cache version for Yarn
  isYarn1?: boolean;
}

export interface PnpmWorkspaceFile {
  packages: string[];
}

```

and i see multiple tests on it yeah

File: lib/modules/manager/npm/update/dependency/index.ts (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts:8]: ok we have another problem with another protocol:
ok i have another suggestion, 
image


we also support file protocol,

i suggest not to ignore any protocol, as we might be supporting them while we are not aware of it. can i remove the code?

**Comment by PhilipAbed** [comment]
i think i should remove the "ignore non supported protocols" this requires lots of time to test and check every protocol and every case of every protocol, its better to wait for customers to complain before we ignore and break things, 
i broke another test:
image

File: lib/modules/manager/npm/update/dependency/index.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts]: i dont think we should add this ignore protocols at all. its the second time i find i broke some tests, i think its better to leave it as is, and if this issue occurs for any other user then we can support that or ignore it as you wish

**Comment by rarkins** [comment]
The extract function should add a `skipReason` for all unsupported protocols. This could all be covered in a single test if necessary.

**Comment by rarkins** [comment]
> The extract function should add a `skipReason` for all unsupported protocols. This could all be covered in a single test if necessary.

Although that's maybe not relevant to this issue at hand?

**Comment by PhilipAbed** [comment]
@rarkins the issue is already resolved, 
ignoring other protocols doesn't seem right since tests are failing for all protocols, apparently we have some solution to the other protocols already in code.

since adding the "ignore other protocols that we dont support" is causing tests to fail, we apparently don't know what we are breaking and what we aren't.
so i removed the code of ignoring protocols completely, its not relevant to this issue anymore.

if you wish to ignore "unsupported protocols" open a new issue for that plz

File: lib/modules/manager/npm/update/dependency/index.ts [hunk 6]
```diff
@@ -25,7 +28,18 @@ function replaceAsString(
   }
   // Look for the old version number
   const searchString = `"${oldValue}"`;
-  const newString = `"${newValue}"`;
+  let newString = `"${newValue}"`;
+
+  if (patchReg.test(oldValue)) {
+    const regex = regEx(`(patch:${depName}@(npm:)?).*#`);
```
Comment (rarkins) [inline lib/modules/manager/npm/update/dependency/index.ts:34]: Can this reuse the same regex pattern as the `.test()`? Otherwise there's a possibility of drift where the `.text()` matches while the `regex.exec()` does not.

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/modules/manager/npm/update/dependency/index.ts (hunk 6 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts]: yes, my mistake, The patchReg is supposed to be the Detection regex, 
the second regex is supposed to be the Replace part regex, thats why i'm using 2
ill change it

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/modules/manager/npm/update/dependency/index.ts [hunk 7]
```diff
@@ -25,7 +26,16 @@ function replaceAsString(
   }
   // Look for the old version number
   const searchString = `"${oldValue}"`;
-  const newString = `"${newValue}"`;
+  let newString = `"${newValue}"`;
+
+  const replaceRegex = regEx(`(patch:${depName}@(npm:)?).*#`);
+  const match = patchReg.exec(oldValue);
```
Comment (PhilipAbed) [inline lib/modules/manager/npm/update/dependency/index.ts:32]:
```suggestion
  const match = replaceRegex.exec(oldValue);
```

File: lib/modules/manager/npm/update/dependency/index.ts [hunk 8]
```diff
@@ -25,7 +28,18 @@ function replaceAsString(
...
+
+  if (patchReg.test(oldValue)) {
+    const replaceRegex = regEx(`(patch:${depName}@(npm:)?).*#`);
+    const match = patchReg.exec(oldValue);
+    const patch = oldValue.replace(replaceRegex, `${match[1]}${newValue}#`);
+    if (patch) {
+      parsedContents[depType][depName] = patch;
+      newString = `"${patch}"`;
+    }
+  }
```
[the remark this answers is not in the document]
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts]: depName cant be part of the regex testing, as it will cause regression on other tests,
the value of depName could be anything which could cause `Invalid Regex` and fail

[the remark this answers is not in the document]
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts]: on the other hand i removed the check for if patch is falsey

[the remark this answers is not in the document]
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts]: the main issue i have with 2 regexes is that :
1) i need the detection regex to make sure we are in "patch"
2) i need the replace regex, which replaces only the version part of the regex

you are trying to combine both, but it will cause other issues, its safer this way, 
if you have a better way without ruining other tests please suggest

File: lib/modules/manager/npm/update/dependency/index.ts [hunk 9]
```diff
@@ -25,7 +28,16 @@ function replaceAsString(
   }
   // Look for the old version number
   const searchString = `"${oldValue}"`;
-  const newString = `"${newValue}"`;
+  let newString = `"${newValue}"`;
+
+  if (patchReg.test(oldValue)) {
+    const replaceRegex = regEx(`(patch:${depName}@(npm:)?).*#`);
```
Comment (rarkins) [inline lib/modules/manager/npm/update/dependency/index.ts:34]: Can you unify `patchReg` and `replaceRegex` into a single regex?

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/modules/manager/npm/update/dependency/index.ts (hunk 9 above)
Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts:34]: i need the detection regex to make sure we are in "patch"
i need the replace regex, which replaces only the version part of the regex

im not sure i know a way to do merge detection+replace

Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts:34]: @rarkins is there a way to do :`StartsWith(regex)`? or contains(replaceRegex),
i tried removing detection, but when `depName` has wild characters like `**/\` it will fail on some tests with Invalid Regex

Comment (rarkins) [reply lib/modules/manager/npm/update/dependency/index.ts:34]: I'm not sure about that, but I think the current approach needs changing because you are doing a test with regex 1, then an exec with regex 2, and then a replace with the result of the exec without checking that it's non-null.

Comment (PhilipAbed) [reply lib/modules/manager/npm/update/dependency/index.ts]: @rarkins Done, i had to Escape characters in depName in order to unify them.

**Review by rarkins — DISMISSED** [review]

File: lib/modules/manager/npm/update/dependency/index.ts [hunk 10]
```diff
@@ -25,7 +26,17 @@ function replaceAsString(
...
   // Look for the old version number
   const searchString = `"${oldValue}"`;
-  const newString = `"${newValue}"`;
+  let newString = `"${newValue}"`;
+
+  const escapedDepName = escapeRegExp(depName);
+  const patchRe = regEx(`^(patch:${escapedDepName}@(npm:)?).*#`);
+  const match = patchRe.exec(oldValue);
+  if (match) {
+    const patch = oldValue.replace(patchRe, `${match[1]}${newValue}#`);
```
Comment (viceice) [inline lib/modules/manager/npm/update/dependency/index.ts:35]:
```suggestion
    const patch = oldValue.replace(match[0], `${match[1]}${newValue}#`);
```
can't we simply replace our match instead of executing the regEx again?

**Review by viceice — COMMENTED** [review]
otherwise LGTM

File: lib/modules/manager/npm/update/dependency/index.ts (hunk 10 above)
Comment (rarkins) [reply lib/modules/manager/npm/update/dependency/index.ts:35]: I'll commit and we see :)

**Review by viceice — APPROVED** [review]
