### PR TITLE
fix(gradle): Update version sorting algorithm

### LINKED ISSUE #10978: Gradle versioning version suffix handling
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: latest

**Describe the bug**

Only suspected but I think our Gradle versioning may not fully support/implement this sorting:

image

(taken from https://docs.gradle.org/current/userguide/single_versions.html)

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

Update sorting according to documentation: https://docs.gradle.org/current/userguide/single_versions.html
It's not 100% compliant, but should handle all examples from doc.

## Context:

Closes #10978

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/versioning/gradle/compare.ts [hunk 1]
```diff
@@ -83,8 +83,11 @@ export enum QualifierRank {
   Dev = -1,
   Default = 0,
   RC,
-  Release,
```
Comment (rarkins) [inline lib/versioning/gradle/compare.ts:86]: Why not keep it?

**Review by rarkins — APPROVED** [review]

File: lib/versioning/gradle/compare.ts (hunk 1 above)
Comment (zharinov) [reply lib/versioning/gradle/compare.ts:86]: It's moved below

**Review by rarkins — APPROVED** [review]
