### PR TITLE
fix(config/migration): migrate wildcard patterns for matchPackagePatterns

### LINKED ISSUE #30379: Incorrect migration of matchPackagePatterns=*
### Discussed in https://github.com/renovatebot/renovate/discussions/30377

<div type='discussions-op-text'>

<sup>Originally posted by **anthr76** July 25, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub Actions

### Please tell us more about your question or problem

we have a config like so:

```json5
{
  extends: [
    "github>foo/renovate-config"
  ],
  "packageRules": [
    {
      "matchPackagePatterns": [
        "*"
      ],
      "enabled": false
    }
    {
      "matchFileNames": [
        "apps/foobar/**"
      ],
      "enabled": true,
    }
  ],
}
```

Renovate 38.0.0 ran a few hours ago and essentially did the opposite of the first package rule here opening a bunch of PRs. I ran `37.439.0` and that caused the PRs to autoclose.

I assume this is a bug?

Maybe it's due to the added slashes in matchPackagesNames apart of the migrated config.

### Logs (if relevant)

<details><summary>Logs</summary>

```
2024-07-25T14:04:00.9050238Z  WARN: /github-action/renovate.json5 needs migrating
2024-07-25T14:04:00.9051950Z        "originalConfig": {
2024-07-25T14:04:00.9053210Z          "extends": ["github>foo/renovate-config"],
2024-07-25T14:04:00.9054456Z          "packageRules": [
2024-07-25T14:04:00.9055509Z            {"matchPackagePatterns": ["*"], "enabled": false},
2024-07-25T14:04:00.9063071Z            {
2024-07-25T14:04:00.9064294Z              "matchFileNames": ["apps/foobar/**"],
2024-07-25T14:04:00.9065450Z              "enabled": true
2024-07-25T14:04:00.9068104Z            }
2024-07-25T14:04:00.9068930Z          ]
2024-07-25T14:04:00.9070090Z        },
2024-07-25T14:04:00.9071205Z        "migratedConfig": {
2024-07-25T14:04:00.9072515Z          "extends": ["github>foo/renovate-config"],
2024-07-25T14:04:00.9074101Z          "packageRules": [
2024-07-25T14:04:00.9075302Z            {"enabled": false, "matchPackageNames": ["/*/"]},
2024-07-25T14:04:00.9083243Z            {
2024-07-25T14:04:00.9084430Z              "matchFileNames": ["apps/foobar/**"],
2024-07-25T14:04:00.9085598Z              "enabled": true
2024-07-25T14:04:00.9088012Z            }
2024-07-25T14:04:00.9088830Z          ]
2024-07-25T14:04:00.9089757Z        }
```

</details>
</div>

### PR DESCRIPTION
**Pull request by secustor**
## Changes
Migrates `"matchPackagePatterns": ["*"]` to `"matchPackageNames": ["/.*/"]`

## Context
Closes #30379

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/config/migrations/custom/package-rules-migration.ts [hunk 1]
```diff
@@ -78,7 +78,15 @@ function mergeMatchers(packageRule: PackageRule): PackageRule {
       const patterns = is.string(val) ? [val] : val;
       if (is.array(patterns, is.string)) {
         newPackageRule.matchPackageNames ??= [];
-        newPackageRule.matchPackageNames.push(...patterns.map((v) => `/${v}/`));
+        newPackageRule.matchPackageNames.push(
+          ...patterns.map((v) => {
+            let value = v;
+            if (value === '*') {
+              value = '.*';
```
Comment (rarkins) [inline lib/config/migrations/custom/package-rules-migration.ts:85]:
```suggestion
              value = '**';
```

**Review by rarkins — CHANGES_REQUESTED** [review]
Can we leave this as * instead? More intuitive

File: lib/config/migrations/custom/package-rules-migration.ts [hunk 2]
```diff
@@ -78,7 +78,15 @@ function mergeMatchers(packageRule: PackageRule): PackageRule {
       const patterns = is.string(val) ? [val] : val;
       if (is.array(patterns, is.string)) {
         newPackageRule.matchPackageNames ??= [];
-        newPackageRule.matchPackageNames.push(...patterns.map((v) => `/${v}/`));
+        newPackageRule.matchPackageNames.push(
+          ...patterns.map((v) => {
+            let value = v;
```
Comment (rarkins) [inline lib/config/migrations/custom/package-rules-migration.ts]:
```suggestion
```

File: lib/config/migrations/custom/package-rules-migration.ts [hunk 3]
```diff
@@ -78,7 +78,15 @@ function mergeMatchers(packageRule: PackageRule): PackageRule {
...
+            if (value === '*') {
```
Comment (rarkins) [inline lib/config/migrations/custom/package-rules-migration.ts]:
```suggestion
            if (v === '*') {
```

File: lib/config/migrations/custom/package-rules-migration.ts (hunk 1 above)
Comment (rarkins) [inline lib/config/migrations/custom/package-rules-migration.ts]:
```suggestion
              return v;
```

**Review by rarkins — APPROVED** [review]
