### PR TITLE
fix: Downgrade log level for http cache cleanup

### LINKED ISSUE #28440: cleanupHttpCache: invalid cache data warning
### Discussed in https://github.com/renovatebot/renovate/discussions/28432

<div type='discussions-op-text'>

<sup>Originally posted by **amezin** April 16, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Bitbucket Server, Docker image ghcr.io/renovatebot/renovate:37.296.0-full

### Please tell us more about your question or problem

Since a recent update I'm getting "cleanupHttpCache: invalid cache data":

- once for every repository if RENOVATE_REPOSITORY_CACHE=enabled

- twice if RENOVATE_REPOSITORY_CACHE=reset

- no warnings if RENOVATE_REPOSITORY_CACHE=disabled

Removing all directories doesn't seem to help.

### Logs (if relevant)

<details><summary>Logs</summary>

```
DEBUG: validateReconfigureBranch() (repository=TEST/repo)

DEBUG: No reconfigure branch found (repository=TEST/repo)

 WARN: cleanupHttpCache: invalid cache data (repository=TEST/repo)

DEBUG: Removing any stale branches (repository=TEST/repo)

DEBUG: config.repoIsOnboarded=true (repository=TEST/repo)
```

</details>
</div>

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

- This message isn't a big deal anyway: no cache means nothing to clean up

## Context

- Closes #28440

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/cache/repository/http-cache.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ import { HttpCacheSchema } from '../../http/cache/schema';
 
 export function cleanupHttpCache(cacheData: unknown): void {
   if (!is.plainObject(cacheData) || !is.plainObject(cacheData['httpCache'])) {
-    logger.warn('cleanupHttpCache: invalid cache data');
+    logger.debug('cleanupHttpCache: invalid cache data');
```
Comment (rarkins) [inline lib/util/cache/repository/http-cache.ts:9]: This is a workaround instead of a fix. Anyone reading the log would assume they have a problem which needs fixing

**Review by rarkins — APPROVED** [review]
