### PR TITLE
fix(yarn): try/catch .yarnrc.yml parsing

### LINKED ISSUE #19786: Error: Expected an indexed object, got a string instead. Does your file follow Yaml's rules?
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Exceptions found in the hosted github app

### Relevant debug logs

<details><summary>Logs</summary>

```
Error: Expected an indexed object, got a string instead. Does your file follow Yaml's rules?
at parseViaJsYaml (/home/ubuntu/renovateapp/node_modules/@yarnpkg/parsers/lib/syml.js:131:15)
at parseSyml (/home/ubuntu/renovateapp/node_modules/@yarnpkg/parsers/lib/syml.js:137:12)
at getZeroInstallPaths (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/npm/extract/yarn.js:50:42)
at isZeroInstall (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/npm/extract/yarn.js:66:23)
at async extractPackageFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/npm/extract/index.js:107:29)
at async Object.extractAllPackageFiles (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/npm/extract/index.js:434:26)
at async extractAllPackageFiles (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/index.js:39:21)
at async getManagerPackageFiles (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/extract/manager-files.js:25:33)
at async /home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/extract/index.js:40:30
at async Promise.all (index 10)
at async extractAllDependencies (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/extract/index.js:39:28)
at async checkOnboardingBranch (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/onboarding/branch/index.js:50:28)
at async getRepoConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:10:14)
at async initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:33:14)
at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:44:18)
at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:260:26)
at async /home/ubuntu/renovateapp/app/worker/index.js:454:5
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by rarkins**
## Context

Closes #19786

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/npm/extract/yarn.ts [hunk 1]
```diff
@@ -51,14 +51,22 @@ export async function getYarnLock(filePath: string): Promise<LockFile> {
 }
 
 export function getZeroInstallPaths(yarnrcYml: string): string[] {
-  const conf = parseSyml(yarnrcYml);
+  let conf: any;
```
Comment (viceice) [inline lib/modules/manager/npm/extract/yarn.ts:54]: doesn't yarn has an appropriate type? 🤔

**Review by viceice — APPROVED** [review]

File: lib/modules/manager/npm/extract/yarn.ts (hunk 1 above)
Comment (rarkins) [reply lib/modules/manager/npm/extract/yarn.ts:54]: I just matched what's returned
