### PR TITLE
fix(npm): Fix titles for PRs grouped with @types package

### LINKED ISSUE #6555: individual @types/react pr includes react
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

yes, nothing relevant that I could see

### What would you like to do?

When a repo has `@types/react` and `react` in it and mono repo grouping has been turned off, it will create a pr titled `Update dependency @types/react` but this pr contains both `react` & `@types/react`.

Is this expected behaviour and is there a config option which will allow splitting those 2 out?

### PR DESCRIPTION
**Pull request by zharinov**
Closes #6555

### CODE REVIEW

**Comment by zharinov** [comment]
Example: https://github.com/zharinov/renovate-react-testcase/pulls

**Review by viceice — COMMENTED** [review]
We should add some tests for it

File: lib/workers/repository/updates/generate.ts [hunk 1]
```diff
@@ -154,10 +167,11 @@ export function generateBranchConfig(
     delete upgrade.group;
     delete upgrade.lazyGrouping;
 
-    const isTypesGroup = ifTypesGroup(depNames, hasGroupName, branchUpgrades);
```
Comment (viceice) [inline lib/workers/repository/updates/generate.ts:157]: Should we reuse this instead of recompute it multiple times?
