### PR TITLE
fix(bitbucket-cloud): Remove reviewers no longer member of the workspace

### LINKED ISSUE #13176: bitbucket-cloud: Updating PR fails with reviewers removed from the workspace
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest (31.3.1 as of writing)

### Please select which platform you are using if self-hosting.

Bitbucket Cloud (bitbucket.org)

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Describe the bug

Similar to #10700, except the user is still active, but no longer a member of the workspace, thus they would need to be removed from the reviewers when updating the PR.

User membership can be checked with this endpoint:
```
GET /2.0/workspaces/${workspace}/members/${account_id}
```

https://developer.atlassian.com/cloud/bitbucket/rest/api-group-workspaces/#api-workspaces-workspace-members-member-get

### Relevant debug logs

<details><summary>Logs</summary>

```json
{
  "name": "renovate",
  "level": 50,
  "logContext": "Hl5cP1Q9FueOWp1A1dJw4",
  "repository": "myworkspace/myrepo",
  "branch": "renovate/some-dep-1.x",
  "err": {
    "name": "HTTPError",
    "code": "ERR_NON_2XX_3XX_RESPONSE",
    "timings": {
      "start": 1639764168231,
      "socket": 1639764168231,
      "lookup": 1639764168234,
      "connect": 1639764168419,
      "secureConnect": 1639764168786,
      "upload": 1639764168786,
      "response": 1639764169542,
      "end": 1639764169542,
      "phases": {
        "wait": 0,
        "dns": 3,
        "tcp": 185,
        "tls": 367,
        "request": 0,
        "firstByte": 756,
        "download": 0,
        "total": 1311
      }
    },
    "message": "Response code 400 (Bad Request)",
    "stack": "HTTPError: Response code 400 (Bad Request)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "options": {
      "headers": {
        "user-agent": "RenovateBot/31.3.1 (https://github.com/renovatebot/renovate)",
        "authorization": "***********",
        "accept": "application/json",
        "content-type": "application/json",
        "content-length": "6158",
        "accept-encoding": "gzip, deflate, br"
      },
      "url": "https://api.bitbucket.org/2.0/repositories/myworkspace/myrepo/pullrequests/1234",
      "hostType": "bitbucket",
      "username": "",
      "password": "",
      "method": "PUT",
      "http2": false
    },
    "response": {
      "statusCode": 400,
      "statusMessage": "Bad Request",
      "body": {
        "type": "error",
        "error": {
          "fields": {
            "reviewers": [
              "John Doe is not a member of this workspace and cannot be added to this pull request"
            ]
          },
          "message": "reviewers: John Doe is not a member of this workspace and cannot be added to this pull request"
        }
      },
      "headers": {
        "server": "nginx",
        "vary": "Authorization, Origin",
        "cache-control": "no-cache, no-store, must-revalidate, max-age=0",
        "content-type": "application/json; charset=utf-8",
        "x-b3-traceid": "1234567890",
        "x-oauth-scopes": "issue:write, pullrequest:write, team, account",
        "x-usage-output-ops": "0",
        "x-dc-location": "Micros",
        "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
        "date": "Fri, 17 Dec 2021 18:02:49 GMT",
        "x-usage-user-time": "0.170621",
        "x-usage-system-time": "0.032723",
        "expires": "Fri, 17 Dec 2021 18:02:49 GMT",
        "x-served-by": "1ef5b856f662",
        "x-view-name": "bitbucket.apps.pullrequests.api.v20.handlers.PullRequestHandler",
        "x-static-version": "5dbb5578d1c1",
        "x-credential-type": "apppassword",
        "x-render-time": "0.559585094452",
        "x-accepted-oauth-scopes": "pullrequest:write",
        "connection": "close",
        "x-usage-input-ops": "1432",
        "x-request-count": "2697",
        "x-frame-options": "SAMEORIGIN",
        "x-version": "5dbb5578d1c1",
        "content-length": "261"
      },
      "httpVersion": "1.1"
    }
  },
  "msg": "Failed to ensure PR: chore(deps): update some dep to v1.2.3"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by maxbrunet**
## Changes:

If Bitbucket returns HTTP 400 when updating the PR and the message contains some similar to `John Doe is not a member of this workspace and cannot be added to this pull request`, check all the reviewers and only update the PR with those for whom the Workspace Members API endpoint returns HTTP 200 (the user is part of the workspace).

It also tries to detect both inactive and not-a-member message in the same `error.message`, but I am not sure what the response body would actually look like if both cases arise simultaneously. `error.fields.reviewers` is a list, so it may be able to contain multiple error messages. Probably a case to look into in the future if it happens

## Context:

Closes #13176

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/platform/bitbucket/index.ts [hunk 1]
```diff
@@ -749,28 +749,65 @@ export async function updatePr({
       }
     );
   } catch (err) {
+    const inactiveReviewersMessage = 'reviewers: Malformed reviewers list';
+    const notMemberReviewersMessage =
+      'is not a member of this workspace and cannot be added to this pull request';
```
Comment (viceice) [inline lib/platform/bitbucket/index.ts:754]: Move to module scope

File: lib/platform/bitbucket/index.spec.ts [hunk 2]
```diff
@@ -803,6 +803,73 @@ describe('platform/bitbucket/index', () => {
...
+            message:
+              'reviewers: Bob Smith is not a member of this workspace and cannot be added to this pull request',
+          },
+        })
+        .head('/2.0/workspaces/some/members/123')
+        .reply(401);
+      await expect(() =>
+        bitbucket.updatePr({ number: 5, prTitle: 'title', prBody: 'body' })
+      ).rejects.toThrowErrorMatchingSnapshot();
+      expect(httpMock.getTrace()).toMatchSnapshot();
```
Comment (viceice) [inline lib/platform/bitbucket/index.spec.ts:871]: Remove, no longer needed.

File: lib/platform/bitbucket/index.spec.ts [hunk 3]
```diff
@@ -803,6 +803,73 @@ describe('platform/bitbucket/index', () => {
...
+          },
+        })
+        .head('/2.0/workspaces/some/members/123')
+        .reply(404)
+        .head('/2.0/workspaces/some/members/456')
+        .reply(200)
+        .put('/2.0/repositories/some/repo/pullrequests/5')
+        .reply(200);
+      await bitbucket.updatePr({ number: 5, prTitle: 'title', prBody: 'body' });
+      expect(httpMock.getTrace()).toMatchSnapshot();
```
Comment (viceice) [inline lib/platform/bitbucket/index.spec.ts:841]: Remove this line, no longer needed

File: lib/platform/bitbucket/index.ts [hunk 4]
```diff
@@ -749,28 +749,65 @@ export async function updatePr({
...
+        );
+
+        // Validate that each previous PR reviewer account is still a member of this workspace
+        for (const reviewer of pr.reviewers) {
+          try {
+            const membership = await bitbucketHttp.head(
+              `/2.0/workspaces/${config.repository.split('/')[0]}/members/${
+                reviewer.account_id
+              }`
+            );
```
Comment (viceice) [inline lib/platform/bitbucket/index.ts:799]: Add `throwHttpErrors:false` option, so it won't throw for 400+ http odes

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/platform/bitbucket/index.ts (hunk 4 above)
Comment (maxbrunet) [reply lib/platform/bitbucket/index.ts:799]: It was my initial approach, but I think we want it to throw an error for anything which is not 404, like 401

File: lib/platform/bitbucket/index.spec.ts (hunk 2 above)
Comment (maxbrunet) [reply lib/platform/bitbucket/index.spec.ts:871]: Could you explain why it is not needed anymore, please?
And should all occurrences in this file of `expect(httpMock.getTrace()).toMatchSnapshot();` be removed? or only the ones I added?

Comment (viceice) [reply lib/platform/bitbucket/index.spec.ts:871]: It's just some legacy test code, which will be removed in future. We just had no time yet to do that.

File: lib/platform/bitbucket/index.ts (hunk 4 above)
Comment (viceice) [reply lib/platform/bitbucket/index.ts:799]: OK, is there any api description, which http codes are returned? I assume it will now always return 200 below, so the condition isn't needed.

**Review by viceice — COMMENTED** [review]
see comments

File: lib/platform/bitbucket/index.ts (hunk 4 above)
Comment (maxbrunet) [reply lib/platform/bitbucket/index.ts:799]: Yes, 200 if member, 404 if not:
https://developer.atlassian.com/cloud/bitbucket/rest/api-group-workspaces/#api-workspaces-workspace-members-member-get-responses

401 is also documented, I would assume 403 is also possible (e.g. misconfigured App password), and as a general rule, it is hard to know what else could go wrong, thus I did not want errors to be silently ignored

Please do not hesitate to let me know if you still think there is a better approach

File: lib/platform/bitbucket/index.spec.ts (hunk 2 above)
Comment (maxbrunet) [reply lib/platform/bitbucket/index.spec.ts]: I have removed the ones I added, the rest is one `git grep -l 'expect(httpMock\.getTrace())\.toMatchSnapshot();' | xargs sed -i '/expect(httpMock.getTrace())\.toMatchSnapshot();/d' && npx jest --updateSnapshot` away 😁

**Comment by maxbrunet** [comment]
Hello @viceice, could you have another look at this PR, please? 🙏

File: lib/platform/bitbucket/index.spec.ts [hunk 5]
```diff
@@ -803,6 +803,71 @@ describe('platform/bitbucket/index', () => {
       await bitbucket.updatePr({ number: 5, prTitle: 'title', prBody: 'body' });
       expect(httpMock.getTrace()).toMatchSnapshot();
     });
+    it('removes reviewers no longer member of the workspace when updating pr', async () => {
```
Comment (viceice) [inline lib/platform/bitbucket/index.spec.ts:806]: test need assertion!

File: lib/platform/bitbucket/__snapshots__/index.spec.ts.snap [hunk 6]
```diff
@@ -1908,3 +1908,5 @@ Array [
   },
 ]
 `;
+
+exports[`platform/bitbucket/index updatePr() throws exception when unable to check reviewers workspace membership 1`] = `"Response code 401 (Unauthorized)"`;
```
Comment (viceice) [inline lib/platform/bitbucket/__snapshots__/index.spec.ts.snap:1912]: use `toEqual` mathcer for such simple values

File: lib/platform/bitbucket/index.ts [hunk 7]
```diff
@@ -751,26 +755,59 @@ export async function updatePr({
...
+        logger.warn(
+          { err },
+          'PR contains reviewer accounts which are no longer member of this workspace.  Will try setting only member reviewers'
+        );
+
+        // Validate that each previous PR reviewer account is still a member of this workspace
+        for (const reviewer of pr.reviewers) {
+          try {
+            const membership = await bitbucketHttp.head(
+              `/2.0/workspaces/${config.repository.split('/')[0]}/members/${
```
Comment (viceice) [inline lib/platform/bitbucket/index.ts:796]: move `config.repository.split('/')[0]` as const out of loop

File: lib/platform/bitbucket/index.ts (hunk 4 above)
Comment (viceice) [reply lib/platform/bitbucket/index.ts:799]: all 400+ code will throw, so i really expect to not have other success codes than `200`, to remove the  200 check below

File: lib/platform/bitbucket/index.spec.ts (hunk 5 above)
Comment (maxbrunet) [reply lib/platform/bitbucket/index.spec.ts:806]: Ah it was the `expect(httpMock.getTrace()).toMatchSnapshot();` 😅
Should I just add it back? What would be the alternative approach?

Comment (maxbrunet) [reply lib/platform/bitbucket/index.spec.ts:806]: I have added `expect(httpMock.getTrace()).toMatchSnapshot();` back for now

File: lib/platform/bitbucket/index.spec.ts [hunk 8]
```diff
@@ -803,6 +803,72 @@ describe('platform/bitbucket/index', () => {
...
+          },
+        })
+        .head('/2.0/workspaces/some/members/123')
+        .reply(404)
+        .head('/2.0/workspaces/some/members/456')
+        .reply(200)
+        .put('/2.0/repositories/some/repo/pullrequests/5')
+        .reply(200);
+      await bitbucket.updatePr({ number: 5, prTitle: 'title', prBody: 'body' });
+      expect(httpMock.getTrace()).toMatchSnapshot();
```
Comment (viceice) [inline lib/platform/bitbucket/index.spec.ts:841]:
```suggestion
      expect (await bitbucket.updatePr({ number: 5, prTitle: 'title', prBody: 'body' })).toBeUndefined ();
```

**Review by viceice — APPROVED** [review]
