### PR TITLE
fix(dashboard): undefined currentValue

### LINKED ISSUE #15906: Dependency dashboard  undefined currentValue
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Repository list on dependency dashboard shows `undefined` when no `currentValue` is used:

image

### Relevant debug logs

Not relevant

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by Gabriel-Ladzaretti**
## Changes
Closes #15906 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by Gabriel-Ladzaretti** [comment]
https://github.com/ladzaretti/15906-undefined-dash/issues/2

File: lib/workers/repository/package-files.ts [hunk 1]
```diff
@@ -46,12 +46,24 @@ export class PackageFiles {
         deps += pad ? '</blockquote>\n</details>\n\n' : '';
         continue;
       }
+
+      const placeHolder = `no version found`;
+      let ver = '';
+      let digest = '';
+      let version = '';
```
Comment (rarkins) [inline lib/workers/repository/package-files.ts:53]: Why define these at this top level? Aren't they applicable only to the dep scope only?

Comment (Gabriel-Ladzaretti) [reply lib/workers/repository/package-files.ts:53]: micro-optimizations, I guess it is neglectable in our application.

**Review by viceice — APPROVED** [review]
