### PR TITLE
fix(gradle): gradle/libs.versions.toml should replace version not comment

### LINKED ISSUE #15044: gradle/libs.versions.toml replaces comment, not the version value
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

`gradle/libs.versions.toml` has contents like:
```toml
[versions]
# GitHub releases: https://github.com/mockk/mockk/releases
# TODO can't go farther than 1.12.3 yet https://github.com/mockk/mockk/issues/794
mockk = "1.12.2"

[libraries]
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
```

renovate updates the comment, not the version number:

https://github.com/TWiStErRob/net.twisterrob.gradle.renovate.test/pull/4/files#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR55-R56

### Relevant debug logs

<details><summary>Logs</summary>

https://app.renovatebot.com/dashboard#github/TWiStErRob/net.twisterrob.gradle.renovate.test/628749206

```json
 {
            "depName": "io.mockk:mockk",
            "groupName": "io.mockk",
            "currentValue": "1.12.2",
            "managerData": {
              "fileReplacePosition": 2420,
              "packageFile": "gradle/libs.versions.toml"
            },
            "fileReplacePosition": 2420,
            "registryUrls": [
              "https://repo.maven.apache.org/maven2",
              "https://dl.google.com/android/maven2/",
              "https://plugins.gradle.org/m2/",
              "https://jcenter.bintray.com/"
            ],
            "depIndex": 44,
            "updates": [
              {
                "bucket": "patch",
                "newVersion": "1.12.3",
                "newValue": "1.12.3",
                "releaseTimestamp": "2022-02-28T13:53:38.000Z",
                "newMajor": 1,
                "newMinor": 12,
                "updateType": "patch",
                "branchName": "renovate/patch-io.mockk"
              }
            ],
            "warnings": [],
            "versioning": "gradle",
            "sourceUrl": "https://github.com/mockk/mockk",
            "homepage": "http://mockk.io",
            "currentVersion": "1.12.2",
            "isSingleVersion": true,
            "fixedVersion": "1.12.2"
          },
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes

refactored the way we extract version locations for version strings 

## Context

Closes #15044 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [X] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/gradle/extract/catalog.ts [hunk 1]
```diff
@@ -14,6 +15,22 @@ import type {
   VersionPointer,
 } from '../types';
 
+function findVersionIndex(
+  content: string,
+  depName: string,
+  version: string
+): number {
+  const contents = content.replaceAll('\r\n', '\n');
```
Comment (PhilipAbed) [inline lib/modules/manager/gradle/extract/catalog.ts:23]: it works without this line on windows, but when i moved created a file in github and tried on a real repo, it failed cuz of this \r\n instead of \n. :/

File: lib/modules/manager/gradle/extract/catalog.ts [hunk 2]
```diff
@@ -14,6 +15,28 @@ import type {
   VersionPointer,
 } from '../types';
 
+function findVersionIndex(
+  content: string,
+  depName: string,
+  version: string
+): number {
+  const contents = content.replace(regEx(/\r\n/g), '\n');
```
Comment (viceice) [inline lib/modules/manager/gradle/extract/catalog.ts:23]: Wouldn't this cause wrong `fileReplacePosition` when file contains `\r\n` ?

File: lib/modules/manager/gradle/extract/catalog.ts [hunk 3]
```diff
@@ -14,6 +15,28 @@ import type {
...
+  const eDn = escapeRegExp(depName);
+  const eVer = escapeRegExp(version);
+  const re = regEx(
+    `(id\\s*=\\s*)?['"]?${eDn}["']?((\\s*=\\s*)|:|,\\s*)(.*version(\\.ref)?(\\s*\\=\\s*))?["']?${eVer}['"]?`
```
Comment (viceice) [inline lib/modules/manager/gradle/extract/catalog.ts:27]: Are you sure single quotes are allowed in toml files?

Comment (zharinov) [reply lib/modules/manager/gradle/extract/catalog.ts:27]: Please, prefer non-capturing groups when possible, i.e. `(?:foobar)` instead of `(foobar)`.

**Review by zharinov — CHANGES_REQUESTED** [review]

File: lib/modules/manager/gradle/extract/catalog.ts (hunk 2 above)
Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract/catalog.ts:23]: nope that's why this code is here, so that \r\n is back to \n... windows fix.

File: lib/modules/manager/gradle/extract/catalog.ts (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract/catalog.ts:27]: michael, yes i tested single quotes, double quotes, no spaces, all toml, we failed at this many times i know from experience and i tested on a toml validator online.

Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract/catalog.ts:27]: Zharinov why do u care about the capturing groups, im looking just for the "index" of the first match it doesn't mean anything in this case.
u mean u want it like this? `(?:id\\s*=\\s*)?['"]?${eDn}["']?(?:(?:\\s*=\\s*)|:|,\\s*)(?:.*version(?:\\.ref)?(?:\\s*\\=\\s*))?["']?${eVer}['"]?`

i dont think this is necessary though

File: lib/modules/manager/gradle/extract/catalog.ts (hunk 2 above)
Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract/catalog.ts:23]: i tested this on linux and windows, on unit tests and real repository. with both formats. all good.

File: lib/modules/manager/gradle/extract/catalog.ts (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract/catalog.ts:27]: or is there a way to get the Index of a Specific group so i can make code easier?

Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract/catalog.ts:27]: i tried to research that, you can't get the index of a specific group in the regex need to match the whole thing.. so its not necessary, do you still think i should add those extra non-capture groups and complicate the regex even more? XD

Comment (viceice) [reply lib/modules/manager/gradle/extract/catalog.ts:27]: use named capture groups for the parts you're interested in.

regex101.com is a good helper to test out.

**Comment by zharinov** [comment]
By the way, instead of dealing with the pretty complex regex, can we achieve the same effect by just getting rid of comments before processing?

**Comment by viceice** [comment]
> By the way, instead of dealing with the pretty complex regex, can we achieve the same effect by just getting rid of comments before processing?

that makes replace position computation even more complex.

**Comment by zharinov** [comment]
> that makes replace position computation even more complex.

Not necessary, as we may replace each comment string with space-filled string of the same length

**Comment by zharinov** [comment]
In `gradle/extract/catalog.ts`:
```ts
import moo from 'moo';

const lexer = moo.states({
  main: {
    lineComment: { match: /#.*?$/, value: (x) => x.replaceAll(/./g, ' ') },
    longDoubleQuoted: {
      match: '"""',
      push: 'longDoubleQuoted',
    },
    doubleQuoted: {
      match: '"',
      push: 'doubleQuoted',
    },
    longSingleQuoted: {
      match: "'''",
      push: 'longSingleQuoted',
    },
    singleQuoted: {
      match: "'",
      push: 'singleQuoted',
    },
    unknown: moo.fallback,
  },
  longDoubleQuoted: {
    stringFinish: { match: '"""', pop: 1 },
    char: moo.fallback,
  },
  doubleQuoted: {
    stringFinish: { match: '"', pop: 1 },
    char: moo.fallback,
  },
  longSingleQuoted: {
    stringFinish: { match: "'''", pop: 1 },
    char: moo.fallback,
  },
  singleQuoted: {
    stringFinish: { match: "'", pop: 1 },
    char: moo.fallback,
  },
});

function eraseComments(input: string): string {
  lexer.reset(input);
  const tokens = [...lexer];
  const substrings = tokens.map((token) => token.value);
  const output = substrings.join('');
  return output;
}
```

And then,
```ts
export function parseCatalog(
  packageFile: string,
  input: string
): PackageDependency<GradleManagerData>[] {
  const content = eraseComments(input);
```

**Comment by zharinov** [comment]
The above snippet erases comments and handles this edge-case:
```toml
# This is a full-line comment
key = "value"  # This is a comment at the end of a line
another = "# This is not a comment"
```

**Comment by PhilipAbed** [comment]
No, we had an issue in parsing also because the dependency name could be a substring of another dependency.
we could also have the same version on different dependencies. 
we need a way to make sure we capture the right dependency and version together, which made this regex complex.

File: lib/modules/manager/gradle/extract/catalog.ts (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract/catalog.ts:27]: Thanks viceice/zharinov for teaching me new stuff about regex i never thought i'd use, 
after testing your theory, 
image
There's no way to get the Index of an Individual group, i researched google too.

I don't think i need to change anything in here, since all i need is the index.

**Comment by PhilipAbed** [comment]
According to documentation i solved all cases except 1 or 2 which didn't even reach the extraction point.. they had problem being parsed in the first place so unit tests didn't work.. apparently renovate don't support them
but this solution of the extraction will solve the user's problem for sure, i checked his repository.

see issue comments for more info about other cases: https://github.com/renovatebot/renovate/issues/15044

File: lib/modules/manager/gradle/extract/catalog.ts (hunk 3 above)
Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract/catalog.ts:27]: i might be able to if i use this: https://stackoverflow.com/questions/15934353/get-index-of-each-capture-in-a-javascript-regex

String.prototype.matchAll but then i wouldn;t be using our `regEx`

Comment (viceice) [reply lib/modules/manager/gradle/extract/catalog.ts:27]:
```suggestion
    `(?:id\\s*=\\s*)?['"]?${eDn}["']?(?:(?:\\s*=\\s*)|:|,\\s*)(?:.*version(?:\\.ref)?(?:\\s*\\=\\s*))?["']?${eVer}['"]?`
```

@PhilipAbed this is what @zharinov means, you'll still get your index for full match, but regex engine won't track individual match groups. So `match.length` will be `1`

**Comment by viceice** [comment]
@zharinov would it make sense to write a small `toml` parser in `moo` to get all information in one step?

I don't like the double parse we use now. We first use `toml` to get the data, then we use `regex` to get again with file position.

**Comment by PhilipAbed** [comment]
@zharinov 
according to the design, we have 2 phases,
1) `extraction + lookup` 
2) `update` 
Getting version position is the current most generic way of extracting the right data.
If you want to extract specific information you need to create an Object that holds that information for each manager.
thus making a new design, new abstraction level, where every manager has it's own extraction data, and that's where the Update will take the data from.
You might be right, this might be the right design instead of having such a large update/upgrade object,
but this requires a new EPIC task which holds lots of refactor tasks which is a lot of work, i don't think its a good idea to start it right now.. i donno :D

**Comment by zharinov** [comment]
> @zharinov would it make sense to write a small `toml` parser in `moo` to get all information in one step?

I thought about this. Toml format doesn't seem so hard, so I think it's possible to tokenize small set of relevant parts and then write state machine of reasonable complexity to extract both data+offsets. The downside: it requires rewrite the `catalog.ts` from scratch.

File: lib/modules/manager/gradle/extract/catalog.ts (hunk 2 above)
Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract/catalog.ts:23]: you are right, ill change the `readLocalFile` from `util/fs/index.ts`

**Comment by PhilipAbed** [comment]
you will have to change the whole extraction, and the update, Currently the Update is Generic. u just prepare the big data for it, and it works, but if you want Specific extraction for each manager, you will need to de-generalize that. 
it means every manager will have its own way to update its files.

For example..
extraction: Toml.. Read it.. find the info you need, its location in the object.
Update: update the object.. after you are done, Rewrite the file.

are we sure the file is the positions are the same as before? 
does the toml read comments? 
can we rewrite everything in the file back? 
i think its doable, but not in this scope :D it needs a higher level of dedication to pass all current tests

**Comment by zharinov** [comment]
Right, update implementation is generic, though allows for custom update function (if provided). Most of custom update functions do pretty much the same: find the previous version at the position specified by `update.managerData.fileReplacePosition` and replace it with the new one. If I understand correctly, if we re-implement `catalog.ts` with correct `fileReplacePosition`, nothing else should be changed in the code base (except more tests being added maybe).

**Comment by viceice** [comment]
> @viceice according to the design, we have 2 phases,
> 
> 1. `extraction + lookup`
> 2. `update`
>    Getting version position is the current most generic way of extracting the right data.
>    If you want to extract specific information you need to create an Object that holds that information for each manager.
>    thus making a new design, new abstraction level, where every manager has it's own extraction data, and that's where the Update will take the data from.
>    You might be right, this might be the right design instead of having such a large update/upgrade object,
>    but this requires a new EPIC task which holds lots of refactor tasks which is a lot of work, i don't think its a good idea to start it right now.. i donno :D

Currently we do a two step extraction for toml and pom.xml.
1. use toml / xml parser, extract deps
2. use regex to find `fileReplacePosition`

This is what i like to avoid. I like to have this in one step, as the second phase had a lot of buggy behavior in past, which caused wrong replacements.

I think best is to open a new issue to discuss how we can handle this with auto-replace.
So the dep can define an additional filename where the version is written to, so the auto-replace uses that instad of normal package file.

File: lib/util/fs/index.ts [hunk 4]
```diff
@@ -38,7 +39,7 @@ export async function readLocalFile(
     const fileContent = encoding
       ? await fs.readFile(localFileName, encoding)
       : await fs.readFile(localFileName);
-    return fileContent;
+    return fileContent.toString().replace(regEx(/\r\n/g), '\n');
```
Comment (viceice) [inline lib/util/fs/index.ts:42]: NO, don't change this file. This should be only be done in maven manager, but normally is shouldn't necessary at all.

Comment (PhilipAbed) [reply lib/util/fs/index.ts:42]: you mean gradle right?  this is gradle task

Comment (PhilipAbed) [reply lib/util/fs/index.ts]: `gradle/extract.ts` sounds good?

File: lib/modules/manager/gradle/extract/catalog.ts (hunk 2 above)
Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract/catalog.ts]: moved it to gradle/extract.ts

File: lib/modules/manager/gradle/extract.ts [hunk 5]
```diff
@@ -52,7 +53,8 @@ export async function extractAllPackageFiles(
     };
 
     try {
-      const content = await readLocalFile(packageFile, 'utf8');
+      let content = await readLocalFile(packageFile, 'utf8');
+      content = content.replace(regEx(/\r\n/g), '\n');
```
Comment (viceice) [inline lib/modules/manager/gradle/extract.ts:57]: i still think this is wrong, the `updateDependency` function doesn't change those, so `fileReplacePosition` will be off by those removed chars

export function updateDependency({
  fileContent,
  upgrade,
}: UpdateDependencyConfig): string | null {
  if (upgrade.updateType === 'replacement') {
    logger.warn('maven manager does not support replacement updates yet');
    return null;
  }
  const offset = fileContent.indexOf('<');
  const spaces = fileContent.slice(0, offset);
  const restContent = fileContent.slice(offset);
  const updatedContent = updateAtPosition(restContent, upgrade, '</');
  if (!updatedContent) {
    return null;
  }
  if (updatedContent === restContent) {
    return fileContent;
  }
  return `${spaces}${updatedContent}`;
}

@zharinov WDYT?

Needs real runs to verify with windows newlines

Comment (zharinov) [reply lib/modules/manager/gradle/extract.ts:57]: Yes, I think it'll break for some repos

Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract.ts:57]: take a look at this:
image

it doesn't reach the update functionality with `\r\n`, it gets removed before that.
well, if it fails before that, what should we do then?
i put it on the file read, it breaks everything
i put it once we get it to gradle resolver, you say it might break in the update, 
what should i do then?

Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract.ts:57]: it might happen only if a repository has windows attributes in `.gitattributes` since we are reading file from the repository itself, so should i add it also to the global `update/branch/get-updated`?

or should i remove it from this task, create a refactor task and change it for all read files over all code?
xD i dont know what to do

Comment (zharinov) [reply lib/modules/manager/gradle/extract.ts:57]: > it doesn't reach the update functionality with \r\n, it gets removed before that.

What is the reason it doesn't get updated with `\r\n`? Sounds like a bug to me.

Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract.ts:57]: @zharinov  
in extraction phase, we Clone the repo, we take the file from our system, which is windows in my case

When we update, we take the file from the Repository itself, but by default, the repository is linux in all gitX i believe,
Unless you change the `.gitattributes` in the repository itself.

Comment (zharinov) [reply lib/modules/manager/gradle/extract.ts:57]: Hmm, now I have two more questions:
1. In the `main` branch, does it lead to same error?
2. Is it possible to point to exact place in code where this bug finally causes `update` function not to be called? I.e. condition check or something...
🤔

Comment (zharinov) [reply lib/modules/manager/gradle/extract.ts:57]: Anyway, I don't think Windows newline handling should be related to the original issue

Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract.ts:57]: 1) i am on the main branch , the file content is taken from : git/index.ts
```
 const content = await git.show([
      'origin/' + (branchName || config.currentBranch) + ':' + filePath,
    ]);
```

2) what do u mean, the update is always called it's another step completely.. 
the Extraction itself fails to find specific format of dependencies, and it doesnt extract at all.. which means there is no upgrade to do in the update functionality
see https://github.com/renovatebot/renovate/blob/main/docs/development/assets/renovate-flow.md

3) you are right, i will just remove this fix, even though it fixes it for windows. and i dont think it would break anything still, but we need a better task to handle windows issues because when we clone from windows files will be read with `\r\n` instead even if the repository is in github(linux)

Comment (viceice) [reply lib/modules/manager/gradle/extract.ts]: @PhilipAbed Until all windows line ending issues are fixed, you should set `core.autocrlf = input` on windows for your bot, so files will have linux endings by default if not overridden by `.gitattributes`

File: lib/modules/manager/gradle/extract.ts [hunk 6]
```diff
@@ -1,6 +1,7 @@
 import upath from 'upath';
 import { logger } from '../../../logger';
 import { readLocalFile } from '../../../util/fs';
+import { regEx } from '../../../util/regex';
```
Comment (viceice) [inline lib/modules/manager/gradle/extract.ts:4]:
```suggestion
```

File: lib/modules/manager/gradle/extract.ts (hunk 5 above)
Comment (PhilipAbed) [reply lib/modules/manager/gradle/extract.ts]: do we have documentation/discussion for this?

**Review by viceice — DISMISSED** [review]

**Comment by viceice** [comment]
need deconfliction

**Review by viceice — APPROVED** [review]
