### PR TITLE
fix: warn if force push commit has no diff

### LINKED ISSUE #5009: Git submodules always result in a new commit on each CLI run
Hey there, first of all I'd like to thank you for this awesome tool, it's really nice.

**What Renovate type are you using?**

I'm using self-hosted renovate CLI from your official docker hub image, with my self-hosted local gitlab server. Latest version at the time of posting.

**Describe the bug**

Normally, for example with nuget updates, renovate bot creates a branch with the update and asks for a merge request. With subsequent runs of the CLI tool, assuming that the state of the repos/versions didn't change, it'll find out that merge request for that version is already created and there is no new version, so nothing to update in this regard. PR will remain in the same state as it was before.

With git submodules, creation works in a similar way, but for some reason each run of the CLI results in **a new commit** in the branch with the merge request, updating to exactly the same digest, without submodule change. This isn't problematic in terms of the history, because of rebase and cleanup, but it's problematic in terms of CI and auto-merge, as if we assume that CI takes e.g. 15 minutes to finish and renovate bot runs each 10, then it means CI will never be able to finish fast enough for renovate bot to merge the PR, and actually each run of renovate bot will cause extra overhead for the CI to do, which can be very devastating if renovate bot CLI is run often enough. The solution is to have it act exactly the same as with nuget (and probably other) managers, which is, do not change the state of the branch if no new update is found.

**Did you see anything helpful in debug logs?**

Full debug log from a single run attached below. I didn't see anything helpful, but I'm not familiar enough with your project. I hope it'll come useful.

<details>
  <summary>Expand</summary>

```
docker.io/renovate/renovate:slim
DEBUG: File config
       "config": {
         "autodiscover": false,
         "autodiscoverFilter": "redacted_orgName/*",
         "baseBranches": ["develop", "master"],
         "endpoint": "https://redacted_selfHostedRepoURL.corp/api/v4/",
         "git-submodules": {"enabled": true},
         "logLevel": "debug",
         "onboardingConfig": {
           "extends": [
             "config:base",
             ":automergeDigest",
             ":automergeMinor",
             ":disableRateLimiting"
           ]
         },
         "packageRules": [
           {"updateTypes": ["minor", "patch", "pin", "digest"], "automerge": true}
         ],
         "persistRepoData": true,
         "platform": "gitlab",
         "repositories": ["redacted_orgName/srv/redacted_mainProjectName"],
         "token": "***********"
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {"hostRules": [], "binarySource": "docker"}
DEBUG: Combined config
       "config": {
         "autodiscover": false,
         "autodiscoverFilter": "redacted_orgName/*",
         "baseBranches": ["develop", "master"],
         "endpoint": "https://redacted_selfHostedRepoURL.corp/api/v4/",
         "git-submodules": {"enabled": true},
         "logLevel": "debug",
         "onboardingConfig": {
           "extends": [
             "config:base",
             ":automergeDigest",
             ":automergeMinor",
             ":disableRateLimiting"
           ]
         },
         "packageRules": [
           {"updateTypes": ["minor", "patch", "pin", "digest"], "automerge": true}
         ],
         "persistRepoData": true,
         "platform": "gitlab",
         "repositories": ["redacted_orgName/srv/redacted_mainProjectName"],
         "token": "***********",
         "hostRules": [],
         "binarySource": "docker"
       }
(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
 INFO: Using platform gitAuthor: Domeradzki Łukasz <redacted_email@company.com>
DEBUG: Using baseDir: /tmp/renovate
DEBUG: Using cacheDir: /tmp/renovate/cache
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
DEBUG: Limits.init enter method
DEBUG: Limits.init prCommitsPerRunLimit processing
DEBUG: Limits.init prCommitsPerRunLimit variable is not set. Ignoring prCommitsPerRunLimit
 INFO: Renovating repository (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using localDir: /tmp/renovate/repos/gitlab/redacted_orgName/srv/redacted_mainProjectName (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: redacted_orgName/srv/redacted_mainProjectName default branch = develop (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Bot email=redacted_email@company.com (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Enabling Git FS (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: redacted_orgName/srv/redacted_mainProjectName http URL = https://redacted_selfHostedRepoURL.corp/redacted_orgName/srv/redacted_mainProjectName.git (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: Initialising git repository into /tmp/renovate/repos/gitlab/redacted_orgName/srv/redacted_mainProjectName (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: git clone completed (repository=redacted_orgName/srv/redacted_mainProjectName)
       "cloneSeconds": 0.5
DEBUG: Cloning git submodule at submodules/redacted_submoduleProjectName (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: latest commit (repository=redacted_orgName/srv/redacted_mainProjectName)
       "latestCommitDate": "2019-12-17 09:29:38 +0100"
DEBUG: No git private key present - commits will be unsigned (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: Setting git author (repository=redacted_orgName/srv/redacted_mainProjectName)
       "gitAuthor": {"name": "Domeradzki Łukasz", "email": "redacted_email@company.com"}
DEBUG: resetMemCache() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: detectSemanticCommits() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: getCommitMessages (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Semantic commits detection: unknown (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: No semantic commits detected (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: checkOnboarding() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: isOnboarded() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: findFile(renovate.json) (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: config file exists (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: ensureIssueClosing() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Repo is onboarded (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Found renovate.json config file (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: Repository config (repository=redacted_orgName/srv/redacted_mainProjectName)
       "configFile": "renovate.json",
       "config": {
         "extends": [
           "config:base",
           ":automergeDigest",
           ":automergeMinor",
           ":disableRateLimiting"
         ]
       }
DEBUG: migrateAndValidate() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: No config migration necessary (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: massaged config (repository=redacted_orgName/srv/redacted_mainProjectName)
       "config": {
         "extends": [
           "config:base",
           ":automergeDigest",
           ":automergeMinor",
           ":disableRateLimiting"
         ]
       }
DEBUG: migrated config (repository=redacted_orgName/srv/redacted_mainProjectName)
       "config": {
         "extends": [
           "config:base",
           ":automergeDigest",
           ":automergeMinor",
           ":disableRateLimiting"
         ]
       }
DEBUG: Found repo ignorePaths (repository=redacted_orgName/srv/redacted_mainProjectName)
       "ignorePaths": [
         "**/node_modules/**",
         "**/bower_components/**",
         "**/vendor/**",
         "**/examples/**",
         "**/__tests__/**",
         "**/test/**",
         "**/tests/**"
       ]
DEBUG: checkBaseBranch() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: config.repoIsOnboarded=true (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Setting baseBranch to develop (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Setting baseBranch to develop (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: latest commit (repository=redacted_orgName/srv/redacted_mainProjectName)
       "branchName": "develop",
       "latestCommitDate": "2019-12-17 09:29:38 +0100"
DEBUG: Setting branchPrefix: renovate/ (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: No vulnerability alerts found (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: processRepo() (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: baseBranches (repository=redacted_orgName/srv/redacted_mainProjectName)
       "baseBranches": ["develop", "master"]
DEBUG: baseBranch: develop (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Setting baseBranch to develop (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Setting baseBranch to develop (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: latest commit (repository=redacted_orgName/srv/redacted_mainProjectName)
       "branchName": "develop",
       "latestCommitDate": "2019-12-17 09:29:38 +0100"
DEBUG: extractAndUpdate() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)WORKSPACE$ for manager bazel (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.bzl$ for manager bazel (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Gemfile$ for manager bundler (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Dockerfile$ for manager dockerfile (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Matched 1 file(s) for manager dockerfile: Dockerfile (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Found a multistage build stage name (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Found a multistage build stage name (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Found a multistage build stage name (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: Found dockerfile package files (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/).gitmodules$ for manager git-submodules (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Matched 1 file(s) for manager git-submodules: .gitmodules (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: Found git-submodules package files (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^\.github/main.workflow$ for manager github-actions (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^\.github/workflows/[^/]+\.ya?ml$ for manager github-actions (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Matched 1 file(s) for manager gitlabci: .gitlab-ci.yml (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: Found gitlabci package files (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci-include (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Matched 1 file(s) for manager gitlabci-include: .gitlab-ci.yml (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)go.mod$ for manager gomod (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)gradle.properties$ for manager gradle (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)requirements.yaml$ for manager helm-requirements (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.pom\.xml$ for manager maven (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)pom\.xml$ for manager maven (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)package.js$ for manager meteor (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)mix\.exs$ for manager mix (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)package.json$ for manager npm (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.csproj$ for manager nuget (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Matched 1 file(s) for manager nuget: src/redacted_mainProjectName.csproj (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: Found nuget package files (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^.nvmrc$ for manager nvm (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.sbt$ for manager sbt (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Package\.swift for manager swift (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.tf$ for manager terraform (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^.travis.yml$ for manager travis (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Found 4 package file(s) (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: manager.fetchUpdates() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Dependency docker has unsupported value stable (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Dependency docker has unsupported value stable (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: getLabels(https://mcr.microsoft.com, dotnet/core/sdk, latest) (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: getManifestResponse(https://mcr.microsoft.com, dotnet/core/sdk, latest) (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: packageFiles with updates (repository=redacted_orgName/srv/redacted_mainProjectName)
       "config": {
         "dockerfile": [
           {
             "packageFile": "Dockerfile",
             "manager": "dockerfile",
             "deps": [
               {
                 "skipReason": "contains-variable",
                 "datasource": "docker",
                 "managerData": {
                   "lineNumber": 3,
                   "fromPrefix": "FROM",
                   "fromSuffix": "AS protogen"
                 },
                 "depType": "stage",
                 "updates": []
               },
               {
                 "skipReason": "contains-variable",
                 "datasource": "docker",
                 "managerData": {
                   "lineNumber": 7,
                   "fromPrefix": "FROM",
                   "fromSuffix": "AS build"
                 },
                 "depType": "stage",
                 "updates": []
               },
               {
                 "skipReason": "contains-variable",
                 "datasource": "docker",
                 "managerData": {
                   "lineNumber": 14,
                   "fromPrefix": "FROM",
                   "fromSuffix": "AS runtime"
                 },
                 "depType": "final",
                 "updates": []
               }
             ]
           }
         ],
         "git-submodules": [
           {
             "packageFile": ".gitmodules",
             "manager": "git-submodules",
             "deps": [
               {
                 "depName": "submodules/redacted_submoduleProjectName",
                 "registryUrls": [
                   "https://oauth2:**redacted**@redacted_selfHostedRepoURL.corp/redacted_orgName/srv/redacted_submoduleProjectName.git",
                   "develop"
                 ],
                 "currentValue": "82172a4a48db8327c37177b8869aa24eeefb7c96",
                 "currentDigest": "82172a4a48db8327c37177b8869aa24eeefb7c96",
                 "updates": [
                   {
                     "updateType": "digest",
                     "newValue": "6a447e6fe4b854fc6abccdf7c9746e82a646a62d",
                     "newVersion": "6a447e6fe4b854fc6abccdf7c9746e82a646a62d",
                     "newDigest": "6a447e6fe4b854fc6abccdf7c9746e82a646a62d",
                     "newDigestShort": "6a447e6"
                   }
                 ],
                 "warnings": [],
                 "sourceUrl": "https://:**redacted**@redacted_selfHostedRepoURL.corp/redacted_orgName/srv/redacted_submoduleProjectName.git"
               }
             ],
             "datasource": "gitSubmodules"
           }
         ],
         "gitlabci": [
           {
             "packageFile": ".gitlab-ci.yml",
             "manager": "gitlabci",
             "deps": [
               {
                 "depName": "mcr.microsoft.com/dotnet/core/sdk",
                 "currentValue": "3.1",
                 "datasource": "docker",
                 "managerData": {"lineNumber": 0},
                 "depType": "image",
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": null,
                 "dockerRegistry": "https://mcr.microsoft.com",
                 "dockerRepository": "dotnet/core/sdk"
               },
               {
                 "depName": "docker",
                 "currentValue": "stable",
                 "datasource": "docker",
                 "managerData": {"lineNumber": 37},
                 "depType": "image",
                 "updates": [],
                 "warnings": [],
                 "skipReason": "unsupported-value"
               },
               {
                 "depName": "docker",
                 "currentValue": "stable",
                 "datasource": "docker",
                 "managerData": {"lineNumber": 72},
                 "depType": "image",
                 "updates": [],
                 "warnings": [],
                 "skipReason": "unsupported-value"
               }
             ]
           }
         ],
         "nuget": [
           {
             "packageFile": "src/redacted_mainProjectName.csproj",
             "manager": "nuget",
             "deps": [
               {
                 "depType": "nuget",
                 "depName": "Newtonsoft.Json",
                 "currentValue": "12.0.3",
                 "managerData": {"lineNumber": 10},
                 "datasource": "nuget",
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": "https://github.com/JamesNK/Newtonsoft.Json"
               },
               {
                 "depType": "nuget",
                 "depName": "Dapper",
                 "currentValue": "1.60.6",
                 "managerData": {"lineNumber": 12},
                 "datasource": "nuget",
                 "updates": [
                   {
                     "fromVersion": "1.60.6",
                     "toVersion": "2.0.30",
                     "newValue": "2.0.30",
                     "newMajor": 2,
                     "newMinor": 0,
                     "updateType": "major",
                     "isSingleVersion": true
                   }
                 ],
                 "warnings": [],
                 "sourceUrl": "https://github.com/StackExchange/Dapper"
               },
               {
                 "depType": "nuget",
                 "depName": "Google.Protobuf",
                 "currentValue": "3.11.2",
                 "managerData": {"lineNumber": 13},
                 "datasource": "nuget",
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": "https://github.com/protocolbuffers/protobuf"
               },
               {
                 "depType": "nuget",
                 "depName": "Microsoft.Extensions.Hosting",
                 "currentValue": "2.2.0",
                 "managerData": {"lineNumber": 14},
                 "datasource": "nuget",
                 "updates": [
                   {
                     "fromVersion": "2.2.0",
                     "toVersion": "3.1.0",
                     "newValue": "3.1.0",
                     "newMajor": 3,
                     "newMinor": 1,
                     "updateType": "major",
                     "isSingleVersion": true
                   }
                 ],
                 "warnings": [],
                 "sourceUrl": "https://github.com/aspnet/Extensions"
               },
               {
                 "depType": "nuget",
                 "depName": "Npgsql",
                 "currentValue": "4.1.2",
                 "managerData": {"lineNumber": 15},
                 "datasource": "nuget",
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": "https://github.com/npgsql/npgsql"
               },
               {
                 "depType": "nuget",
                 "depName": "RabbitMQ.Client",
                 "currentValue": "5.1.2",
                 "managerData": {"lineNumber": 16},
                 "datasource": "nuget",
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": null
               }
             ]
           }
         ]
       }
DEBUG: branchifyUpgrades (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: 3 flattened updates found: submodules/redacted_submoduleProjectName, Dapper, Microsoft.Extensions.Hosting (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using group branchName template (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Dependency Microsoft.Extensions.Hosting is part of group aspnet Extensions monorepo (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Returning 3 branch(es) (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: generateBranchConfig(1) (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: hasGroupName: false (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: groupEligible: false (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: useGroupSettings: false (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: generateBranchConfig(1) (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-dapper-2.x)
DEBUG: hasGroupName: false (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-dapper-2.x)
DEBUG: groupEligible: false (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-dapper-2.x)
DEBUG: useGroupSettings: false (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-dapper-2.x)
DEBUG: generateBranchConfig(1) (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: hasGroupName: true (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: groupEligible: false (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: useGroupSettings: false (repository=redacted_orgName/srv/redacted_mainProjectName, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: config.repoIsOnboarded=true (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: Processing 3 branches: renovate/develop-dapper-2.x, renovate/develop-major-aspnet-extensions-monorepo, renovate/develop-submodules-redacted_submoduleProjectName-digest (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: processBranch with 1 upgrades (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Setting baseBranch to develop (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Setting baseBranch to develop (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: latest commit (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
       "branchName": "develop",
       "latestCommitDate": "2019-12-17 09:29:38 +0100"
DEBUG: getBranchPr(renovate/develop-submodules-redacted_submoduleProjectName-digest) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Got res with 1 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getPr(16) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getBranchStatus(renovate/develop-submodules-redacted_submoduleProjectName-digest) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Got res with 3 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: branchExists=true (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Branch pr rebase requested: false (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Branch has 1 upgrade(s) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Checking if PR has been edited (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Found existing branch PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Checking schedule(at any time, null) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: No schedule defined (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Branch already exists (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getBranchPr(renovate/develop-submodules-redacted_submoduleProjectName-digest) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Got res with 1 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getPr(16) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getBranchStatus(renovate/develop-submodules-redacted_submoduleProjectName-digest) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Got res with 3 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Branch does not need rebasing (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Using parentBranch: renovate/develop-submodules-redacted_submoduleProjectName-digest (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: manager.getUpdatedPackageFiles() (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Updated 1 package files (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Updated 1 lock files (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
       "updatedArtifacts": ["submodules/redacted_submoduleProjectName"]
DEBUG: 2 file(s) to commit (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Committing files to branch renovate/develop-submodules-redacted_submoduleProjectName-digest (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
 INFO: files committed (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Checking if we can automerge branch (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: mergeStatus=no automerge (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Ensuring PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: There are 0 errors and 0 warnings (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getBranchPr(renovate/develop-submodules-redacted_submoduleProjectName-digest) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Got res with 1 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getPr(16) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getBranchStatus(renovate/develop-submodules-redacted_submoduleProjectName-digest) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Got res with 0 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Found existing PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getBranchStatus(renovate/develop-submodules-redacted_submoduleProjectName-digest) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Got res with 0 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Processing existing PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getBranchStatus(renovate/develop-submodules-redacted_submoduleProjectName-digest) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Got res with 0 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: getBranchStatus() result (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
       "branchStatus": "pending",
       "branchName": "renovate/develop-submodules-redacted_submoduleProjectName-digest"
 INFO: PR updated (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
       "committedFiles": true,
       "pr": 16
DEBUG: Ensuring comment ":warning: Artifact update problem" in #16 is removed (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Getting comments for #16 (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Found 1 comments (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: Checking #16 for automerge (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
       "automerge": true,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: PR is configured for automerge (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
 INFO: PR is not ready for merge (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=submodules/redacted_submoduleProjectName, branch=renovate/develop-submodules-redacted_submoduleProjectName-digest)
DEBUG: processBranch with 1 upgrades (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Setting baseBranch to develop (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Setting baseBranch to develop (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: latest commit (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
       "branchName": "develop",
       "latestCommitDate": "2019-12-17 09:29:38 +0100"
DEBUG: getBranchPr(renovate/develop-dapper-2.x) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Got res with 1 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: getPr(13) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: getBranchStatus(renovate/develop-dapper-2.x) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Got res with 3 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: branchExists=true (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Branch pr rebase requested: false (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Branch has 1 upgrade(s) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Checking if PR has been edited (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Found existing branch PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Checking schedule(at any time, null) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: No schedule defined (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Branch already exists (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: getBranchPr(renovate/develop-dapper-2.x) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Got res with 1 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: getPr(13) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: getBranchStatus(renovate/develop-dapper-2.x) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Got res with 3 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Branch does not need rebasing (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Using parentBranch: renovate/develop-dapper-2.x (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: manager.getUpdatedPackageFiles() (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: nuget.updateDependency(): undefined (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: No changes necessary (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: No package files need updating (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: No updated lock files in branch (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: No files to commit (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Checking if we can automerge branch (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: mergeStatus=no automerge (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Ensuring PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: There are 0 errors and 0 warnings (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: getBranchPr(renovate/develop-dapper-2.x) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Got res with 1 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: getPr(13) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: getBranchStatus(renovate/develop-dapper-2.x) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Got res with 3 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Found existing PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Repository URL does not match any known hosts (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Processing existing PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Merge Request #13 does not need updating (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: Checking #13 for automerge (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
       "automerge": false,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: No automerge (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Dapper, branch=renovate/develop-dapper-2.x)
DEBUG: processBranch with 1 upgrades (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Setting baseBranch to develop (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Setting baseBranch to develop (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: latest commit (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
       "branchName": "develop",
       "latestCommitDate": "2019-12-17 09:29:38 +0100"
DEBUG: getBranchPr(renovate/develop-major-aspnet-extensions-monorepo) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Got res with 1 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: getPr(14) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: getBranchStatus(renovate/develop-major-aspnet-extensions-monorepo) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Got res with 3 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: branchExists=true (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Branch pr rebase requested: false (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Branch has 1 upgrade(s) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Checking if PR has been edited (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Found existing branch PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Checking schedule(at any time, null) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: No schedule defined (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Branch already exists (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: getBranchPr(renovate/develop-major-aspnet-extensions-monorepo) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Got res with 1 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: getPr(14) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: getBranchStatus(renovate/develop-major-aspnet-extensions-monorepo) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Got res with 3 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Branch does not need rebasing (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Using parentBranch: renovate/develop-major-aspnet-extensions-monorepo (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: manager.getUpdatedPackageFiles() (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: nuget.updateDependency(): undefined (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: No changes necessary (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: No package files need updating (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: No updated lock files in branch (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: No files to commit (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Checking if we can automerge branch (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: mergeStatus=no automerge (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Ensuring PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: There are 0 errors and 0 warnings (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: getBranchPr(renovate/develop-major-aspnet-extensions-monorepo) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Got res with 1 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: getPr(14) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: getBranchStatus(renovate/develop-major-aspnet-extensions-monorepo) (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Got res with 3 results (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Found existing PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Repository URL does not match any known hosts (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Processing existing PR (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Merge Request #14 does not need updating (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: Checking #14 for automerge (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
       "automerge": false,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: No automerge (repository=redacted_orgName/srv/redacted_mainProjectName, dependencies=Microsoft.Extensions.Hosting, branch=renovate/develop-major-aspnet-extensions-monorepo)
DEBUG: baseBranch: master (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Setting baseBranch to master (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Setting baseBranch to master (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: latest commit (repository=redacted_orgName/srv/redacted_mainProjectName)
       "branchName": "master",
       "latestCommitDate": "2019-11-21 11:08:29 +0100"
DEBUG: extractAndUpdate() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)WORKSPACE$ for manager bazel (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.bzl$ for manager bazel (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Gemfile$ for manager bundler (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Dockerfile$ for manager dockerfile (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/).gitmodules$ for manager git-submodules (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^\.github/main.workflow$ for manager github-actions (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^\.github/workflows/[^/]+\.ya?ml$ for manager github-actions (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci-include (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)go.mod$ for manager gomod (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)gradle.properties$ for manager gradle (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)requirements.yaml$ for manager helm-requirements (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.pom\.xml$ for manager maven (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)pom\.xml$ for manager maven (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)package.js$ for manager meteor (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)mix\.exs$ for manager mix (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)package.json$ for manager npm (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.csproj$ for manager nuget (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^.nvmrc$ for manager nvm (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.sbt$ for manager sbt (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)Package\.swift for manager swift (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: \.tf$ for manager terraform (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: ^.travis.yml$ for manager travis (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Found 0 package file(s) (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: manager.fetchUpdates() (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: packageFiles with updates (repository=redacted_orgName/srv/redacted_mainProjectName)
       "config": {}
DEBUG: branchifyUpgrades (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: 0 flattened updates found:  (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Returning 0 branch(es) (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: config.repoIsOnboarded=true (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: Processing 0 branches:  (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: branchPrefix: renovate/ (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Found 0 Renovate PRs (repository=redacted_orgName/srv/redacted_mainProjectName)
       "renovatePrs": []
DEBUG: Removing any stale branches (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: config.repoIsOnboarded=true (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Branch lists (repository=redacted_orgName/srv/redacted_mainProjectName)
       "branchList": [
         "renovate/develop-submodules-redacted_submoduleProjectName-digest",
         "renovate/develop-dapper-2.x",
         "renovate/develop-major-aspnet-extensions-monorepo"
       ],
       "renovateBranches": [
         "renovate/develop-dapper-2.x",
         "renovate/develop-major-aspnet-extensions-monorepo",
         "renovate/develop-submodules-redacted_submoduleProjectName-digest"
       ]
DEBUG: remainingBranches= (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: No branches to clean up (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: ensureIssueClosing() (repository=redacted_orgName/srv/redacted_mainProjectName)
 INFO: Finished repository (repository=redacted_orgName/srv/redacted_mainProjectName)
DEBUG: Host request stats (milliseconds)
       "hostStats": {
         "redacted_selfHostedRepoURL.corp": {
           "requests": 20,
           "sum": 7908,
           "average": 395,
           "median": 177
         },
         "registry.npmjs.org": {
           "requests": 6,
           "sum": 1030,
           "average": 172,
           "median": 27
         },
         "api.nuget.org": {"requests": 7, "sum": 226, "average": 32, "median": 36},
         "mcr.microsoft.com": {
           "requests": 4,
           "sum": 430,
           "average": 108,
           "median": 101
         },
         "azuresearch-usnc.nuget.org": {
           "requests": 6,
           "sum": 3216,
           "average": 536,
           "median": 534
         }
       }
 INFO: Renovate finished
```
</details>

**To Reproduce**

It should be enough to run a CLI tool with available submodule update and notice that renovate bot updates the PR on each run. If you have any CI attached, you'll see that (without automerge) it's triggered to rebuild the PR, even if the digest of the submodule to update to doesn't change.

I didn't test this in other environments than my own, so I can say that it works at least with self-hosted gitlab and official renovate docker image, but it's likely that other environments suffer from the same problem.

**Additional context**

None for now, but I'll be happy to provide any extra info you may need to reproduce/solve this problem. Thank you in advance for your time.

### PR DESCRIPTION
**Pull request by JamieMagee**
Warns whenever commits appear to be empty. This will be monitored in the hosted app for false positives before later being used to skip commits and solve the below issues.

References: #5009 #5083 #5074

### CODE REVIEW

File: lib/platform/git/storage.ts [hunk 1]
```diff
@@ -498,7 +506,10 @@ export class Storage {
         }
       }
       // istanbul ignore if
-      if (fileNames.length === 1 && fileNames[0] === 'renovate.json') {
+      if (
+        fileNames.length === 1 &&
+        (fileNames[0] === 'renovate.json' || fileNames[0] === '.gitmodules')
+      ) {
         fileNames.unshift('-f');
```
Comment (rarkins) [inline lib/platform/git/storage.ts]: I actually forget why this was originally added. Why is it also necessary for `.gitmodules`?

Comment (JamieMagee) [reply lib/platform/git/storage.ts]: I added it from an earlier version of this change, and I should be able to remove it. Should I remove the check for `renovate.json` as well?

Comment (rarkins) [reply lib/platform/git/storage.ts]: I don’t know.. leave it for now

Comment (ViceIce) [reply lib/platform/git/storage.ts]: I think `.gitmodules` was added for git submodule support.
