### PR TITLE
fix(pnpm): modify locked version extraction

### LINKED ISSUE #22382: pnpm lockedVersion should come from importers, not packages
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

Renovate gets `lockedVersion` wrong for some pnpm packages, which results in confused PRs as described in https://github.com/renovatebot/renovate/discussions/22375

Instead of iterating through the `packages` section of the pnpm lock file, Renovate needs to iterate through the `importers` section instead

### Relevant debug logs

<details><summary>Logs</summary>

```
            "currentValue": "^5.1.1",
            "currentVersion": "7.1.1",
            "datasource": "npm",
            "depName": "execa",
            "depType": "devDependencies",
            "fixedVersion": "7.1.1",
            "isSingleVersion": false,
            "lockedVersion": "7.1.1",
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- Use `importers` section to extract locked verison of deps when dealing with monorepos
- Modify existing extraction logic for normal repos(ie. non monorepo) and use `dependencies` section instead of `packages`
- Modify logic a bit further to handle the different formatting of `dependencies` section of the lockfile in v6 and v5

## Context
- Closes: https://github.com/renovatebot/renovate/issues/22382

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/npm/post-update/types.ts [hunk 1]
```diff
@@ -30,9 +30,16 @@ export interface GenerateLockFileResult {
   stdout?: string;
 }
 
+// the dependencies schema is different for v6 and other lockfile versions
```
Comment (rarkins) [inline lib/modules/manager/npm/post-update/types.ts:33]: Seems like this should be in a common types file instead of post-update, but perhaps it can be changed later

**Review by rarkins — COMMENTED** [review]
Please test against some examples

**Comment by RahulGautamSingh** [comment]
Reproductions:
1. Normal Repo [v5.3](https://github.com/RahulGautamSingh-testing/pnpm2) [v6](https://github.com/RahulGautamSingh-testing/pnpm1)
2. Monorepo [v5.3](https://github.com/RahulGautamSingh-testing/pnpm3) [v6](https://github.com/RahulGautamSingh-testing/pnpm4)
3. [Repro-22375](https://github.com/RahulGautamSingh-testing/pnpm-repro-22375)

**Review by rarkins — APPROVED** [review]
