### PR TITLE
fix(helmfile): lock update for multidoc YAML

### LINKED ISSUE #31651: Helmfile lock update fails if helmfile.yaml is multidoc
### Discussed in https://github.com/renovatebot/renovate/discussions/31572

<div type='discussions-op-text'>

<sup>Originally posted by **BjoernPetersen** September 24, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

_No response_

### Please tell us more about your question or problem

The Helmfile manager has supported multidoc YAMLs for a while (#8682), but it fails to update the corresponding lockfile if a dependency is updated (see logs). Please use the `parseYaml` instead of the `parseSingleYaml` function in [the artifacts.ts](https://github.com/renovatebot/renovate/blob/1781ba1826253c0eee91cce1a86eb306f3062f6e/lib/modules/manager/helmfile/artifacts.ts#L16).

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: updateArtifacts for updatedPackageFiles (branch="renovate/argo-cd-7.6.x")
DEBUG: Failed to update Helmfile lock file (branch="renovate/argo-cd-7.6.x")
{
  "err": {
    "name": "YAMLException",
    "reason": "expected a single document in the stream, but found more",
    "message": "expected a single document in the stream, but found more",
    "stack": "YAMLException: expected a single document in the stream, but found more\n    at load (/usr/local/renovate/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/lib/loader.js:1722:9)\n    at parseSingleYaml (/usr/local/renovate/lib/util/yaml.ts:63:29)\n    at updateArtifacts (/usr/local/renovate/lib/modules/manager/helmfile/artifacts.ts:73:32)\n    at managerUpdateArtifacts (/usr/local/renovate/lib/workers/repository/update/branch/get-updated.ts:505:12)\n    at getUpdatedPackageFiles (/usr/local/renovate/lib/workers/repository/update/branch/get-updated.ts:360:25)\n    at processBranch (/usr/local/renovate/lib/workers/repository/update/branch/index.ts:476:19)\n    at writeUpdates (/usr/local/renovate/lib/workers/repository/process/write.ts:166:17)\n    at update (/usr/local/renovate/lib/workers/repository/process/extract-update.ts:213:11)\n    at Object.renovateRepository (/usr/local/renovate/lib/workers/repository/index.ts:89:19)\n    at attributes.repository (/usr/local/renovate/lib/workers/global/index.ts:202:11)\n    at start (/usr/local/renovate/lib/workers/global/index.ts:187:7)\n    at /usr/local/renovate/lib/renovate.ts:18:22"
  }
}

DEBUG: Updated 1 package files (branch="renovate/argo-cd-7.6.x")
DEBUG: No updated lock files in branch (branch="renovate/argo-cd-7.6.x")

```

</details>
</div>

### PR DESCRIPTION
**Pull request by rarkins**
Fixes #31651

Update Helmfile manager to handle multidoc YAMLs correctly.

* Replace `parseSingleYaml` with `parseYaml` in `lib/modules/manager/helmfile/artifacts.ts` to handle multiple YAML documents.
* Update the `doc` variable to handle multiple documents in the `updateArtifacts` function.
* Add a test case in `lib/modules/manager/helmfile/artifacts.spec.ts` for updating the lockfile with a multidoc YAML.
* Mock the `parseYaml` function to handle multiple documents in the test case.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/renovatebot/renovate/issues/31651?shareId=997cb85a-5b7e-4545-82be-d91f888770d7).

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

File: lib/modules/manager/helmfile/artifacts.ts [hunk 1]
```diff
@@ -70,21 +70,23 @@ export async function updateArtifacts({
     }
 
     const cmd: string[] = [];
-    const doc = parseSingleYaml(newPackageFileContent, {
+    const docs = parseYaml(newPackageFileContent, {
       removeTemplates: true,
       customSchema: Doc,
```
Comment (viceice) [inline lib/modules/manager/helmfile/artifacts.ts:75]: error handling should probably be filter

Comment (rarkins) [reply lib/modules/manager/helmfile/artifacts.ts:75]: ?

Comment (secustor) [reply lib/modules/manager/helmfile/artifacts.ts:75]: Right now it will throw completely if any of the docs does not fit the schema. 

see https://github.com/renovatebot/renovate/blob/main/lib/util/yaml.ts#L27

**Review by viceice — APPROVED** [review]
