### PR TITLE
fix(pipenv): detect 'any-version' packages

### LINKED ISSUE #3477: Pipfile with extras specifications and no version fails to parse
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
reonvate fails to parse a Pipfile with a dependency with extras and no version

**Did you see anything helpful in debug logs?**
```
 INFO: Renovating repository (repository=my/repository)
 INFO: Repository config (repository=my/repository)
       "configFile": "renovate.json",
       "config": {
         "extends": ["config:base"],
         "pipenv": {"enabled": true},
         "pip_setup": {"enabled": true},
         "labels": ["dependencies"]
       }
 INFO: Found gitlabci package files (repository=my/repository)
 INFO: Found npm package files (repository=my/repository)
ERROR: Repository has unknown error (repository=my/repository)
       "err": {
         "message": "Cannot convert object to primitive value",
         "stack": "TypeError: Cannot convert object to primitive value\n    at RegExp.exec (<anonymous>)\n    at Object.entries.map.x (/builds/continous-integration/renovate/node_modules/renovate/lib/manager/pipenv/extract.js:65:47)\n    at Array.map (<anonymous>)\n    at extractFromSection (/builds/continous-integration/renovate/node_modules/renovate/lib/manager/pipenv/extract.js:47:6)\n    at Object.extractPackageFile (/builds/continous-integration/renovate/node_modules/renovate/lib/manager/pipenv/extract.js:32:8)\n    at module.exports.(anonymous function).params (/builds/continous-integration/renovate/node_modules/renovate/lib/manager/index.js:67:34)\n    at getManagerPackageFiles (/builds/continous-integration/renovate/node_modules/renovate/lib/workers/repository/extract/manager-files.js:54:25)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Finished repository (repository=my/repository)
```

**To Reproduce**

1.  Create repository with the following pipfile
```
[packages]
raven = {extras = ['flask']}
```
2. Enable pipenv for the repository
3. Run renovate

**Expected behavior**
`"*"` is used as version and the additional dependencies added by the extras are considered.

### PR DESCRIPTION
**Pull request by Dmitry9**
When renovate set up to use pipenv as a manager and target repo contains a Pipfile with next content:
```
[packages]
raven = {extras = ['flask']}
```
it reports an error:
```
ERROR: Repository has unknown error (repository=my/repository)
       "err": {
         "message": "Cannot convert object to primitive value" ...
```
This PR marks packages with skip reason 'any-version' when they declare `extras` dependencies. See this [comment](https://github.com/renovatebot/renovate/issues/3477#issuecomment-483059611)

> <cite>Probably best to just ignore extras, as the additional dependencies they pull in have no effect for our purposes here.</cite>

Closes #3477

### CODE REVIEW

**Comment by rarkins** [comment]
Does this really handle all the use cases mentioned in the issue it closes? e.g.

```
[packages]
# all of these version specifiers make pipenv use the same version as "*"
Flask = "*"
Flask-Caching = '*'
flask-mako = {}
Flask-SQLAlchemy = {version = "*"}
Flask-Login = {editable = true}
```

**Comment by rarkins** [comment]
@Dmitry9 I think what you need to do is:

1. Add or edit a fixture to reproduce the problem in the for of one or more failing tests
2. Improve the code so that tests pass and not fail

So really there should be fixtures and tests added first before you add code

**Comment by rarkins** [comment]
@Delphinator can you confirm if this is as you expected?

**Comment by Delphinator** [comment]
Why strip that stuff using a regex? That just seems like a recipe for breaking in weird ways in the future.

In https://github.com/renovatebot/renovate/issues/3477#issuecomment-479701310 I suggested a more general approach to handling the version specification, that should be trivial to implement. If that's implemented extra fields like `extra` just don't matter anymore.

**Comment by rarkins** [comment]
@Dmitry9 can you read the suggestion that @Delphinator linked to and re-implement?

File: lib/manager/pipenv/extract.js [hunk 1]
```diff
@@ -18,7 +19,15 @@ function extractPackageFile(content) {
...
-    pipfile = toml.parse(content);
+    const afterDiscard = content
+      .split(os.EOL)
+      .filter(
+        str =>
+          !str.match(/{\s*extras\s*=|"\*"|'\*'|=\s*{}|editable\s*=\s*true/g)
+      )
+      .join(os.EOL);
+
+    pipfile = toml.parse(afterDiscard);
```
Comment (rarkins) [inline lib/manager/pipenv/extract.js]: In general let's try to avoid this type of regex and rely on parsing instead. The parsing was not the problem I believe, it was our handling of the post-parsed content.

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/manager/pipenv/extract.js (hunk 1 above)
Comment (Dmitry9) [reply lib/manager/pipenv/extract.js]: Done.

**Comment by Dmitry9** [comment]
@rarkins take a look.

File: lib/manager/pipenv/extract.js [hunk 2]
```diff
@@ -43,11 +43,32 @@ function extractFromSection(pipfile, section, registryUrls) {
...
   const specifierRegex = new RegExp(`^${specifierPattern}$`);
-  const deps = Object.entries(pipfile[section])
+  const oneSection = pipfile[section];
+
+  if (section === 'packages') {
+    Object.keys(oneSection).forEach(key => {
+      if (typeof oneSection[key] === 'string') return;
+
+      const isObject =
+        !Array.isArray(oneSection[key]) &&
```
Comment (rarkins) [inline lib/manager/pipenv/extract.js]: Please use the `@sindresorhus/is` package for this instead

**Review by rarkins — CHANGES_REQUESTED** [review]
- Please update PR title and description to better reflect what this PR now does.
- Make sure the `Closes #` statements are up to date
- Instead of returning null, we should be doing like in `npm` where we record the package file and each dependency like in the new fixture is marked as `dep.skipReason = 'any-version'`.

File: lib/manager/pipenv/extract.js [hunk 3]
```diff
@@ -43,11 +43,32 @@ function extractFromSection(pipfile, section, registryUrls) {
...
+  }
+
+  const deps = Object.entries(oneSection)
     .map(x => {
       const [depName, requirements] = x;
       let currentValue;
       let pipenvNestedVersion;
+      if ([requirements, requirements.version].find(r => r === '*')) {
+        logger.debug(`Skipping extras dependency. depName: ${depName}`);
+        return null;
```
[the remark this answers is not in the document]
Comment (Dmitry9) [reply lib/manager/pipenv/extract.js]: Done.

File: lib/manager/pipenv/extract.js (hunk 2 above)
Comment (Dmitry9) [reply lib/manager/pipenv/extract.js]: Done.

File: lib/manager/pipenv/extract.js [hunk 4]
```diff
@@ -47,14 +48,8 @@ function extractFromSection(pipfile, section, registryUrls) {
...
-      if (typeof oneSection[key] === 'string') return;
-
-      const isObject =
-        !Array.isArray(oneSection[key]) &&
-        typeof oneSection[key] === 'object' &&
-        oneSection[key] !== null;
-
-      if (!isObject) oneSection[key] = {};
+      if (is.string(oneSection[key])) return;
+      if (!is.object(oneSection[key])) oneSection[key] = {};
```
Comment (rarkins) [inline lib/manager/pipenv/extract.js]: Do you have any examples of pipfiles where the value is not a string but also not an object?

File: test/manager/pipenv/extract.spec.js [hunk 5]
```diff
@@ -27,6 +31,20 @@ describe('lib/manager/pipenv/extract', () => {
       expect(res).toMatchSnapshot();
       expect(res).toHaveLength(4);
     });
+    it('returns null for packages with "extras" ', () => {
```
[the remark this answers is not in the document]
Comment (Dmitry9) [reply test/manager/pipenv/extract.spec.js]: done

File: lib/manager/pipenv/extract.js (hunk 4 above)
Comment (Dmitry9) [reply lib/manager/pipenv/extract.js]: No, I don't. Please give me one and I will update tests.

**Comment by Dmitry9** [comment]
@rarkins take a look one more time please.

File: lib/manager/pipenv/extract.js [hunk 6]
```diff
@@ -43,11 +44,31 @@ function extractFromSection(pipfile, section, registryUrls) {
     return [];
   }
   const specifierRegex = new RegExp(`^${specifierPattern}$`);
-  const deps = Object.entries(pipfile[section])
+  const oneSection = pipfile[section];
+
+  if (section === 'packages') {
```
Comment (rarkins) [inline lib/manager/pipenv/extract.js]: Why is this only applicable for 'packages' and not 'dev-packages'?

File: lib/manager/pipenv/extract.js [hunk 7]
```diff
@@ -43,11 +44,31 @@ function extractFromSection(pipfile, section, registryUrls) {
     return [];
   }
   const specifierRegex = new RegExp(`^${specifierPattern}$`);
-  const deps = Object.entries(pipfile[section])
+  const oneSection = pipfile[section];
```
Comment (rarkins) [inline lib/manager/pipenv/extract.js]: Rename oneSection -> pipfileSection

File: lib/manager/pipenv/extract.js [hunk 8]
```diff
@@ -43,11 +44,31 @@ function extractFromSection(pipfile, section, registryUrls) {
...
+
+  if (section === 'packages') {
+    Object.keys(oneSection).forEach(key => {
+      if (!is.string(oneSection[key]))
```
Comment (rarkins) [inline lib/manager/pipenv/extract.js]: Isn't it safer to check for an object? Or are we sure it can only be a string or an object?

File: lib/manager/pipenv/extract.js [hunk 9]
```diff
@@ -43,11 +44,31 @@ function extractFromSection(pipfile, section, registryUrls) {
...
       const [depName, requirements] = x;
       let currentValue;
       let pipenvNestedVersion;
+      if ([requirements, requirements.version].find(r => r === '*')) {
+        logger.debug(`Skipping extras dependency. depName: ${depName}`);
+        return {
+          depName,
+          skipReason: 'any-version',
+          currentValue,
+          pipenvNestedVersion,
```
Comment (rarkins) [inline lib/manager/pipenv/extract.js]: This pipenvNestedVersion field doesn't seem useful.

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/manager/pipenv/extract.js (hunk 6 above)
Comment (Dmitry9) [reply lib/manager/pipenv/extract.js]: Agreed.

File: lib/manager/pipenv/extract.js (hunk 8 above)
Comment (Dmitry9) [reply lib/manager/pipenv/extract.js]: Done.

File: lib/manager/pipenv/extract.js (hunk 9 above)
Comment (Dmitry9) [reply lib/manager/pipenv/extract.js]: Done.

File: lib/manager/pipenv/extract.js (hunk 7 above)
Comment (Dmitry9) [reply lib/manager/pipenv/extract.js]: Done.

File: lib/manager/pipenv/extract.js [hunk 10]
```diff
@@ -43,11 +44,28 @@ function extractFromSection(pipfile, section, registryUrls) {
...
+    if (is.object(pipfileSection[key]))
+      pipfileSection[key].version = pipfileSection[key].version || '*';
+  });
+
+  const deps = Object.entries(pipfileSection)
     .map(x => {
       const [depName, requirements] = x;
       let currentValue;
       let pipenvNestedVersion;
+      if ([requirements, requirements.version].find(r => r === '*')) {
```
Comment (rarkins) [inline lib/manager/pipenv/extract.js]: Couldn't this section now be replaced with a check near the bottom like this? `if (dep.currentValue === '*') dep.skipReason = 'any-version';` ?

Comment (Dmitry9) [reply lib/manager/pipenv/extract.js]: This wouldn't work.
ifail

Cannot read property `deps` of NULL

return-null

**Comment by rarkins** [comment]
@Dmitry9 could you also add [this example pipfile](https://github.com/pypa/pipfile/blob/7d7c3126dcfc519d7250c3ed4f311f8e58c3197c/examples/Pipfile) as a fixture and ensure we handle this? I would like to solve #3482 at the same time. If it's a file reference then we should probably have a different `skipReason` than `any-version` too - please check other managers to find an appropriate one.
