### PR TITLE
fix(manager/github-actions): allow dot `.` in reusable workflow repository name

### LINKED ISSUE #20872: Update GitHub Actions reusable workflows not working on `.github` repository
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Reusable workflow in github-actions manager not detected for `.github` repositories. This issue is related to #12212 as that was about the reusable workflows in general, but this issue is specifically about reusable workflows from a `.github` repository.

Looks like this is related to the regex that extracts the dependencies: https://github.com/renovatebot/renovate/blob/35.1.1/lib/modules/manager/github-actions/extract.ts#L12-L14. Running that on my action file results in only the non-`.github` dependency being matched (see https://regex101.com/r/NzyfGc/1). I think we should change the regex to allow a dot as well as GitHub repositories are allowed to have dots in the name. I've tested this by adjusting the regex to allow for a dot, see https://regex101.com/r/U9DR43/1, and that works. Happy to create a PR for this, just let me know!

Reproduction: https://github.com/vidavidorra/test.

### Relevant debug logs

<details><summary>Logs</summary>

For my reference, this was Job ID 1018880366.

```
DEBUG: Matched 1 file(s) for manager github-actions: .github/workflows/build.yml
DEBUG: manager extract durations (ms)
{
  "managers": {
    "github-actions": 2
  }
}
DEBUG: Found github-actions package files
DEBUG: Found 1 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "main",
  "stats": {
    "managers": {
      "github-actions": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 1
    }
  }
}
DEBUG: PackageFiles.add() - Package file saved for base branch
{
  "baseBranch": "main"
}
DEBUG: Package releases lookups complete
{
  "baseBranch": "main"
}
DEBUG: branchifyUpgrades
DEBUG: detectSemanticCommits()
DEBUG: getCommitMessages
DEBUG: semanticCommits: detected "angular"
DEBUG: semanticCommits: enabled
DEBUG: 1 flattened updates found: iterative/link-check

```

</details>

### Have you created a minimal reproduction repository?

I have read the minimal reproductions documentation and linked to such a repository in the bug description

### PR DESCRIPTION
**Pull request by jdbruijn**
Closes #20872.

## Changes

Allow dot `.` in GitHub Actions reusable workflow repository name.

## Context

- closes #20872

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/github-actions/extract.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ import type { Workflow } from './types';
 
 const dockerActionRe = regEx(/^\s+uses: ['"]?docker:\/\/([^'"]+)\s*$/);
 const actionRe = regEx(
-  /^\s+-?\s+?uses: (?<replaceString>['"]?(?<depName>[\w-]+\/[\w-]+)(?<path>\/.*)?@(?<currentValue>[^\s'"]+)['"]?(?:\s+#\s*(?:renovate\s*:\s*)?(?:pin\s+|tag\s*=\s*)?@?(?<tag>v?\d+(?:\.\d+(?:\.\d+)?)?))?)/
+  /^\s+-?\s+?uses: (?<replaceString>['"]?(?<depName>[\w-]+\/[.\w-]+)(?<path>\/.*)?@(?<currentValue>[^\s'"]+)['"]?(?:\s+#\s*(?:renovate\s*:\s*)?(?:pin\s+|tag\s*=\s*)?@?(?<tag>v?\d+(?:\.\d+(?:\.\d+)?)?))?)/
```
Comment (HonkingGoose) [inline lib/modules/manager/github-actions/extract.ts:13]: For the Renovate maintainers: I don't see any new tests with this PR. Do we have tests that cover this regex?

**Review by viceice — APPROVED** [review]

File: lib/modules/manager/github-actions/extract.ts (hunk 1 above)
Comment (rarkins) [reply lib/modules/manager/github-actions/extract.ts:13]: I think it's ok this time
