### PR TITLE
fix(datasource/cdnjs): update logic to accomodate api changes

### LINKED ISSUE #26662: CDNJS Datasource Broken after API changes
### Discussed in https://github.com/renovatebot/renovate/discussions/26650

<div type='discussions-op-text'>

<sup>Originally posted by **mlec1** January 15, 2024</sup>
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v37.133.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

None

### Describe the problem

The cdnjs datasource can't look up the package as Renovate fails with the following message:

```
Renovate failed to look up the following dependencies:
Can't find version matching 1.10.5 for cdnjs package bootstrap-icons/font/bootstrap-icons.css,
Can't find version matching 5.2.3 for cdnjs package bootstrap/js/bootstrap.min.js,
Can't find version matching 5.2.3 for cdnjs package bootstrap/js/bootstrap.bundle.min.js.
```

Here is the minimal repo: https://github.com/mlec1/renovate-broken-cdnjs-reproduction

I tried to look at it. At [this line](https://github.com/renovatebot/renovate/blob/de68769fc241cf15afc32ae4eddc264194dedc48/lib/modules/datasource/cdnjs/index.ts#L48), Renovate call the API of cdnjs. For example for bootstrap, it will call https://api.cdnjs.com/libraries/bootstrap?fields=homepage,repository,assets

However, due to a recent change [in the API,](https://cdnjs.com/api) the assets for all versions are not served using this endpoint anymore (only the assets of the latest version are served). In order to get the assets of a given version, we should use `https://api.cdnjs.com/libraries/:librairies/:version`

image

To get the list of all versions, we could make a request to https://api.cdnjs.com/libraries/bootstrap?fields=homepage,repository,versions and later do a request to https://api.cdnjs.com/libraries/bootstrap/:version for all versions.

I wanted to make a fix myself, but I have never touched typescript, and I am taking longer than expected, so if someone makes a fix before, feel free to open an MR before me.

### Relevant debug logs

<details><summary>Logs</summary>

```

DEBUG: Matched 1 file(s) for manager html: base.html (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: manager extract durations (ms) (repository=mlec1/test-renovate-dev, baseBranch=main)
       "managers": {"html": 1}
DEBUG: Found html package files (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: Found 1 package file(s) (repository=mlec1/test-renovate-dev, baseBranch=main)
 INFO: Dependency extraction complete (repository=mlec1/test-renovate-dev, baseBranch=main)
       "stats": {
         "managers": {"html": {"fileCount": 1, "depCount": 3}},
         "total": {"fileCount": 1, "depCount": 3}
       }
DEBUG: baseBranch: main (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: hostRules: no authentication for api.cdnjs.com (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: Found no satisfying versions with 'semver' versioning (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: Missing version has nothing to roll back to (repository=mlec1/test-renovate-dev, baseBranch=main, packageFile=base.html)
       "depName": "bootstrap-icons",
       "currentValue": "1.10.5"
DEBUG: Found no satisfying versions with 'semver' versioning (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: Missing version has nothing to roll back to (repository=mlec1/test-renovate-dev, baseBranch=main, packageFile=base.html)
       "depName": "bootstrap",
       "currentValue": "5.2.3"
DEBUG: Found no satisfying versions with 'semver' versioning (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: Missing version has nothing to roll back to (repository=mlec1/test-renovate-dev, baseBranch=main, packageFile=base.html)
       "depName": "bootstrap",
       "currentValue": "5.2.3"
DEBUG: PackageFiles.add() - Package file saved for base branch (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: Package releases lookups complete (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: branchifyUpgrades (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: detectSemanticCommits() (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: getCommitMessages (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: semanticCommits: detected "unknown" (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: semanticCommits: disabled (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: 0 flattened updates found:  (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: Returning 0 branch(es) (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: config.repoIsOnboarded=true (repository=mlec1/test-renovate-dev, baseBranch=main)
DEBUG: packageFiles with updates (repository=mlec1/test-renovate-dev, baseBranch=main)
       "config": {
         "html": [
           {
             "deps": [
               {
                 "datasource": "cdnjs",
                 "depName": "bootstrap-icons",
                 "packageName": "bootstrap-icons/font/bootstrap-icons.css",
                 "currentValue": "1.10.5",
                 "replaceString": "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.css\" integrity=\"sha512-0yYhCyiMB+6XOis4qvWA42kPkKb54+uMaOhbsta6m+aQ7cZOm5hzERPrRkkknlpEdoxVCwYui+yM0jRazpDFuA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />",
                 "currentDigest": "sha512-0yYhCyiMB+6XOis4qvWA42kPkKb54+uMaOhbsta6m+aQ7cZOm5hzERPrRkkknlpEdoxVCwYui+yM0jRazpDFuA==",
                 "updates": [],
                 "versioning": "semver",
                 "warnings": [
                   {
                     "topic": "bootstrap-icons/font/bootstrap-icons.css",
                     "message": "Can't find version matching 1.10.5 for cdnjs package bootstrap-icons/font/bootstrap-icons.css"
                   }
                 ],
                 "sourceUrl": "https://github.com/twbs/icons",
                 "registryUrl": "https://api.cdnjs.com/",
                 "homepage": "https://icons.getbootstrap.com/"
               },
               {
                 "datasource": "cdnjs",
                 "depName": "bootstrap",
                 "packageName": "bootstrap/js/bootstrap.min.js",
                 "currentValue": "5.2.3",
                 "replaceString": "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js\" integrity=\"sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\">",
                 "currentDigest": "sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g==",
                 "updates": [],
                 "versioning": "semver",
                 "warnings": [
                   {
                     "topic": "bootstrap/js/bootstrap.min.js",
                     "message": "Can't find version matching 5.2.3 for cdnjs package bootstrap/js/bootstrap.min.js"
                   }
                 ],
                 "sourceUrl": "https://github.com/twbs/bootstrap",
                 "registryUrl": "https://api.cdnjs.com/",
                 "homepage": "http://getbootstrap.com/"
               },
               {
                 "datasource": "cdnjs",
                 "depName": "bootstrap",
                 "packageName": "bootstrap/js/bootstrap.bundle.min.js",
                 "currentValue": "5.2.3",
                 "replaceString": "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.bundle.min.js\" integrity=\"sha512-i9cEfJwUwViEPFKdC1enz4ZRGBj8YQo6QByFTF92YXHi7waCqyexvRD75S5NVTsSiTv7rKWqG9Y5eFxmRsOn0A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\">",
                 "currentDigest": "sha512-i9cEfJwUwViEPFKdC1enz4ZRGBj8YQo6QByFTF92YXHi7waCqyexvRD75S5NVTsSiTv7rKWqG9Y5eFxmRsOn0A==",
                 "updates": [],
                 "versioning": "semver",
                 "warnings": [
                   {
                     "topic": "bootstrap/js/bootstrap.bundle.min.js",
                     "message": "Can't find version matching 5.2.3 for cdnjs package bootstrap/js/bootstrap.bundle.min.js"
                   }
                 ],
                 "sourceUrl": "https://github.com/twbs/bootstrap",
                 "registryUrl": "https://api.cdnjs.com/",
                 "homepage": "http://getbootstrap.com/"
               }
             ],
             "packageFile": "base.html"
           }
         ]
       }
DEBUG: detectSemanticCommits() (repository=mlec1/test-renovate-dev)
DEBUG: semanticCommits: returning "disabled" from cache (repository=mlec1/test-renovate-dev)
DEBUG: processRepo() (repository=mlec1/test-renovate-dev)
DEBUG: Processing 0 branches:  (repository=mlec1/test-renovate-dev)
DEBUG: Calculating hourly PRs remaining (repository=mlec1/test-renovate-dev)
DEBUG: currentHourStart=2024-01-15T20:00:00.000+00:00 (repository=mlec1/test-renovate-dev)
DEBUG: PR hourly limit remaining: 2 (repository=mlec1/test-renovate-dev)
DEBUG: Calculating prConcurrentLimit (10) (repository=mlec1/test-renovate-dev)
DEBUG: 0 PRs are currently open (repository=mlec1/test-renovate-dev)
DEBUG: PR concurrent limit remaining: 10 (repository=mlec1/test-renovate-dev)
DEBUG: Calculated maximum PRs remaining this run: 2 (repository=mlec1/test-renovate-dev)
DEBUG: PullRequests limit = 2 (repository=mlec1/test-renovate-dev)
DEBUG: Calculating hourly PRs remaining (repository=mlec1/test-renovate-dev)
DEBUG: currentHourStart=2024-01-15T20:00:00.000+00:00 (repository=mlec1/test-renovate-dev)
DEBUG: PR hourly limit remaining: 2 (repository=mlec1/test-renovate-dev)
DEBUG: Calculating branchConcurrentLimit (10) (repository=mlec1/test-renovate-dev)
DEBUG: 0 already existing branches found:  (repository=mlec1/test-renovate-dev)
DEBUG: Branch concurrent limit remaining: 10 (repository=mlec1/test-renovate-dev)
DEBUG: Calculated maximum branches remaining this run: 2 (repository=mlec1/test-renovate-dev)
DEBUG: Branches limit = 2 (repository=mlec1/test-renovate-dev)
DEBUG: ensureDependencyDashboard() (repository=mlec1/test-renovate-dev)
DEBUG: Ensuring Dependency Dashboard (repository=mlec1/test-renovate-dev)
 WARN: Package lookup failures (repository=mlec1/test-renovate-dev)
       "warnings": [
         "Can't find version matching 1.10.5 for cdnjs package bootstrap-icons/font/bootstrap-icons.css",
         "Can't find version matching 5.2.3 for cdnjs package bootstrap/js/bootstrap.min.js",
         "Can't find version matching 5.2.3 for cdnjs package bootstrap/js/bootstrap.bundle.min.js"
       ],
       "files": ["base.html"]
DEBUG: ensureIssue() (repository=mlec1/test-renovate-dev)
DEBUG: Updating issue (repository=mlec1/test-renovate-dev)
DEBUG: validateReconfigureBranch() (repository=mlec1/test-renovate-dev)
DEBUG: No reconfigure branch found (repository=mlec1/test-renovate-dev)
DEBUG: checkConfigMigrationBranch() (repository=mlec1/test-renovate-dev)
DEBUG: checkConfigMigrationBranch() Config does not need migration (repository=mlec1/test-renovate-dev)
DEBUG: Removing any stale branches (repository=mlec1/test-renovate-dev)
DEBUG: config.repoIsOnboarded=true (repository=mlec1/test-renovate-dev)
DEBUG: No renovate branches found (repository=mlec1/test-renovate-dev)
DEBUG: ensureIssueClosing() (repository=mlec1/test-renovate-dev)
DEBUG: ensureIssueClosing() (repository=mlec1/test-renovate-dev)
DEBUG: PackageFiles.clear() - Package files deleted (repository=mlec1/test-renovate-dev)
DEBUG: Branch summary (repository=mlec1/test-renovate-dev)
       "cacheModified": undefined,
       "baseBranches": [{"branchName": "main", "sha": "9e7af82eb45c11faeda6ecb35acc7b42fe076f4c"}],
       "branches": [],
       "defaultBranch": "main",
       "inactiveBranches": []
DEBUG: Renovate repository PR statistics (repository=mlec1/test-renovate-dev)
       "stats": {"total": 0, "open": 0, "closed": 0, "merged": 0}
DEBUG: Repository result: done, status: onboarded, enabled: true, onboarded: true (repository=mlec1/test-renovate-dev)
DEBUG: repository problems (repository=mlec1/test-renovate-dev)
       "repoProblems": ["WARN: Package lookup failures"]

```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above</div>

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- Use [https://api.cdnjs.com/libraries/vue?fields=homepage,repository,versions](https://api.cdnjs.com/libraries/vue?fields=homepage,repository,versions) to fetch the list of versions

- Implement `getDigest` function which uses [https://api.cdnjs.com/libraries/vue/0.10.0?fields=sri](https://api.cdnjs.com/libraries/vue/0.10.0?fields=sri )to fetch list of sris. We return the `sri` corresponding to the package and filename. 

- Change the caching of `getReleases` function from default datasource caching which used the `packageName` in the key to using a cache decorator function which uses only the `library`'s name as the key as suggested by [Michael ](https://github.com/renovatebot/renovate/pull/27212#pullrequestreview-1874329078)

> Note:
We are discontinuing support for file-based matching of releases. This entails a shift in our update mechanism: rather than filtering releases based on filenames and subsequently selecting the version to update to, we will now determine the update version first and then verify if the required filename is present within it. If the necessary file is not found, we will refrain from suggesting an update, regardless of whether a newer version exists that may include the file.

## Context
Closes: https://github.com/renovatebot/renovate/issues/26662

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/datasource/cdnjs/index.ts [hunk 1]
```diff
@@ -18,13 +24,7 @@ const Repository = z
...
   .catch(undefined);
 
-const Assets = z.array(
-  z.object({
-    version: z.string(),
-    files: z.string().array(),
-    sri: z.record(z.string()).optional(),
-  }),
-);
+const Versions = z.string().array();
```
Comment (zharinov) [inline lib/modules/datasource/cdnjs/index.ts:27]:
```suggestion
const Versions = z.string().transform((version): Release => ({ version })).array();
```

File: lib/modules/datasource/cdnjs/index.ts [hunk 2]
```diff
@@ -43,33 +43,24 @@ export class CdnJsDatasource extends Datasource {
...
-                  res.newDigest = newDigest;
-                }
-
-                return res;
-              }),
+          versions: Versions.transform((versions) =>
+            versions.map((version) => {
+              const res: Release = { version };
+              return res;
+            }),
```
Comment (zharinov) [inline lib/modules/datasource/cdnjs/index.ts:56]: Previously, we needed to create the schema instance dynamically, because we needed transform to be closed over `assetName` variable. Now it seems like the schema could be defined statically in single place.

**Review by zharinov — CHANGES_REQUESTED** [review]

File: lib/modules/datasource/cdnjs/index.ts [hunk 3]
```diff
@@ -98,6 +89,27 @@ export class CdnJsDatasource extends Datasource {
...
+    { packageName, registryUrl }: DigestConfig,
+    newValue: string,
+  ): Promise<string | null> {
+    const [library] = packageName.split('/');
+    const assetName = packageName.replace(`${library}/`, '');
+
+    const url = `${registryUrl}libraries/${library}/${newValue}?fields=sri`;
+
+    const sri = (
+      await this.http.getJson<Record<'sri', Record<string, string>>>(url)
```
Comment (viceice) [inline lib/modules/datasource/cdnjs/index.ts:107]: use zod Schema

**Review by viceice — CHANGES_REQUESTED** [review]
please use static zod Schema

File: lib/modules/datasource/cdnjs/index.ts [hunk 4]
```diff
@@ -18,14 +24,12 @@ const Repository = z
...
   .catch(undefined);
 
-const Assets = z.array(
-  z.object({
-    version: z.string(),
-    files: z.string().array(),
-    sri: z.record(z.string()).optional(),
-  }),
-);
+const Versions = z
```
Comment (viceice) [inline lib/modules/datasource/cdnjs/index.ts:27]: can we move those to `./schema.ts` like we do on other places now?

File: lib/modules/datasource/cdnjs/index.ts [hunk 5]
```diff
@@ -43,33 +47,19 @@ export class CdnJsDatasource extends Datasource {
     const result = Result.parse(config, ReleasesConfig)
       .transform(({ packageName, registryUrl }) => {
         const [library] = packageName.split('/');
-        const assetName = packageName.replace(`${library}/`, '');
 
-        const url = `${registryUrl}libraries/${library}?fields=homepage,repository,assets`;
+        const url = `${registryUrl}libraries/${library}?fields=homepage,repository,versions`;
 
         const schema = z.object({
```
Comment (viceice) [inline lib/modules/datasource/cdnjs/index.ts:53]: move to schema.ts too, it's now static

File: lib/modules/datasource/cdnjs/index.ts [hunk 6]
```diff
@@ -98,6 +69,43 @@ export class CdnJsDatasource extends Datasource {
     return val;
   }
 
+  @cache({
+    namespace: `datasource-${CdnJsDatasource.id}-sri`,
```
Comment (viceice) [inline lib/modules/datasource/cdnjs/index.ts:73]:
```suggestion
    namespace: `datasource-${CdnJsDatasource.id}-digest`,
```
we should be consistent with other data sources.

**Review by viceice — COMMENTED** [review]
I think we should also change caching of releases to only include the library in name and drop the asset. this will reduce cache storage size (deduplicate)

**Review by viceice — APPROVED** [review]
