### PR TITLE
fix(manager/terragrunt): add missing registry host

### LINKED ISSUE #26668: Custom registry missing from terragrunt tfr extract result
### Describe the proposed change(s).

This test should pass in terragrunt:

```js
    it('extracts terragrunt sources with custom registry', () => {
      const input = `terraform {
        source = "tfr://registry.domain.com/abc/helloworld/aws?version=1.0.0"
      }`;
      const res = extractPackageFile(input);
      expect(res).toEqual({
        deps: [
          {
            currentValue: '1.0.0',
            datasource: 'terraform-module',
            depName: 'abc/helloworld/aws',
            depType: 'terragrunt',
            registryUrls: ['https://registry.domain.com'],
          },
        ],
      });
    });
```

Ref: https://github.com/renovatebot/renovate/discussions/26644

### PR DESCRIPTION
**Pull request by ismtabo**
## Changes

Added registry url to extraction result at Terragrunt Manager when source uses tfr protocol and contains custom registry hostname.

Now, if the source link in a Terragrunt file using `tfr://` protocol contains a hostname it is included in the extraction result inside the `registryUrls` property. For example, given the following `terraform` block:

```hcl
terraform {
  source = "tfr://registry.domain.com/abc/helloworld/aws?version=1.0.0"
}
```

The extraction of dependencies will produce the following dependency:

```json
{
  "depType": "terragrunt",
  "depName": "abc/helloworld/aws",
  "currentValue": "1.0.0",
  "datasource": "terraform-module",
  "registryUrls": [
    "https://registry.domain.com"
  ]
}
```

## Context

Closes: #26668

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — APPROVED** [review]

File: lib/modules/manager/terragrunt/modules.ts [hunk 1]
```diff
@@ -72,6 +72,9 @@ export function analyseTerragruntModule(
       tfrVersionMatch.groups.cloud;
     dep.currentValue = tfrVersionMatch.groups.currentValue;
     dep.datasource = TerraformModuleDatasource.id;
+    if (tfrVersionMatch.groups.registry) {
+      dep.registryUrls = [`https://${tfrVersionMatch.groups.registry}`];
+    }
```
Comment (viceice) [inline lib/modules/manager/terragrunt/modules.ts:77]: should only be set if not default registry
