### PR TITLE
fix(lerna): Fix support for Lerna when package.json is not at the root of the repo

### LINKED ISSUE #6574: "Could not detect lerna version in package.json" because Renovate expects it to be at the root of the repo
**What Renovate type are you using?**

Hosted

**Describe the bug**

My repo uses Lerna - but its package.json is not at the root of the repo. It seems to work to a degree, but [https://github.com/renovatebot/renovate/blob/e4e76f8f49770b8d14c6bc289038ba74ff27a6b9/lib/manager/npm/post-update/lerna.ts#L84](post-update/lerna.ts) expects the file to be at the repo root ("Could not detect lerna version in package.json")

**Did you see anything helpful in debug logs?**

Just `WARN: Could not detect lerna version in package.json` but I've confirmed the git show command to get the file looks for `origin/master:package.json` rather than `origin/master:wherever-it-is/package.json`

**To Reproduce**

https://github.com/gjoseph/Tichu/ (the Lerna package.json is under `tichu-clients/`)

**Additional context**

### PR DESCRIPTION
**Pull request by gjoseph**
Pass the PackageFile object to generateLockFiles, and use that rather than hardcode 'package.json'
Closes #6574

### CODE REVIEW

**Comment by gjoseph** [comment]
Hmm I just signed the CLA before raising the PR, not sure what's up there.

File: lib/manager/npm/post-update/lerna.ts [hunk 1]
```diff
@@ -84,12 +86,12 @@ export async function generateLockFiles(
     cmd.push(`${lernaClient} install ${cmdOptions}`);
     let lernaVersion: string;
     try {
-      const pJson = JSON.parse(await platform.getFile('package.json'));
+      const pJson = JSON.parse(await platform.getFile(packageJson));
```
Comment (gjoseph) [inline lib/manager/npm/post-update/lerna.ts:89]: I wasn't actually sure if there was a reason for this to delegate to a git show command, rather than read the file from the filesystem?

Comment (rarkins) [reply lib/manager/npm/post-update/lerna.ts:89]: We're in the process of removing as many of these git.* commands to replace with fs.*

**Comment by gjoseph** [comment]
Sorry I realised there's a bunch of checks that aren't passing -- fixing this and pushing again soon.

**Comment by gjoseph** [comment]
> Sorry I realised there's a bunch of checks that aren't passing -- fixing this and pushing again soon.

Should be good now.

**Comment by gjoseph** [comment]
I'd add tests, but I'm not quite sure how to go about it - it doesn't look like the calls to `getFile` are mocked currently?

File: lib/manager/npm/post-update/lerna.spec.ts [hunk 2]
```diff
@@ -20,26 +20,26 @@ describe('generateLockFiles()', () => {
     env.getChildProcessEnv.mockReturnValue(envMock.basic);
   });
   it('returns if no lernaClient', async () => {
+    const res = await lernaHelper.generateLockFiles({}, 'some-dir', {}, {});
```
Comment (gjoseph) [inline lib/manager/npm/post-update/lerna.spec.ts:23]: If you feel that `undefined` should still be supported here I can make that work again, let me know what you think.

File: lib/manager/npm/post-update/lerna.ts (hunk 1 above)
Comment (gjoseph) [reply lib/manager/npm/post-update/lerna.ts]: That said -- now that a `PackageFile` is passed to this method, rather than just `lernaClient: string`, does it even really need to do this at all? `PackageFile` has a `deps` property (no idea if it's set at this stage)

Comment (gjoseph) [reply lib/manager/npm/post-update/lerna.ts]: Here's an alternative approach that doesn't require re-loading this file:
```
diff --git a/lib/manager/npm/post-update/lerna.ts b/lib/manager/npm/post-update/lerna.ts
index 5a628aa34..7fa155ea7 100644
--- a/lib/manager/npm/post-update/lerna.ts
+++ b/lib/manager/npm/post-update/lerna.ts
@@ -3,7 +3,6 @@ import { quote } from 'shlex';
 import { join } from 'upath';
 import { logger } from '../../../logger';
 import { ExecOptions, exec } from '../../../util/exec';
-import { getFile } from '../../../util/git';
 import { PackageFile, PostUpdateConfig } from '../../common';
 import { getNodeConstraint } from './node-version';
 import { optimizeCommand } from './yarn';
@@ -86,12 +85,10 @@ export async function generateLockFiles(
     cmd.push(`${lernaClient} install ${cmdOptions}`);
     let lernaVersion: string;
     try {
-      const pJson = JSON.parse(await getFile(packageJson));
-      lernaVersion =
-        (pJson.dependencies && pJson.dependencies.lerna) ||
-        (pJson.devDependencies && pJson.devDependencies.lerna);
+      lernaVersion = lernaPackageFile.deps.find((d) => d.depName === 'lerna')
+        .currentValue;
     } catch (err) {
-      logger.warn(`Could not detect lerna version in ${packageJson}`);
+      logger.warn(`Could not detect lerna version in ${packageJson}: ${err}`);
     }
     if (!lernaVersion || !semver.validRange(lernaVersion)) {
       lernaVersion = 'latest';
```
Would that work for all scenarios?

Comment (rarkins) [reply lib/manager/npm/post-update/lerna.ts]: Yes, if the packageFile has `deps` then that could be a cleaner solution

**Review by rarkins — CHANGES_REQUESTED** [review]
Please try with your `deps` idea

File: lib/manager/npm/post-update/lerna.ts (hunk 1 above)
Comment (viceice) [reply lib/manager/npm/post-update/lerna.ts]: The try catch can be removed then too

Comment (gjoseph) [reply lib/manager/npm/post-update/lerna.ts]: @rarkins @viceice 👍 I pushed a commit that does that. Since docker preCommands don't seem to be captured by snapshots, I'm unsure how to test this though.
Happy to hop on to Slack to discuss this if I get an invite :)

Comment (gjoseph) [reply lib/manager/npm/post-update/lerna.ts]: This lack of test is also probably why coverage isn't reached anymore.

**Review by viceice — COMMENTED** [review]
needs coverage fixes: https://codecov.io/gh/renovatebot/renovate/pull/6675/src/lib/manager/npm/post-update/lerna.ts?before=lib/manager/npm/post-update/lerna.ts

image

File: lib/manager/npm/post-update/lerna.ts [hunk 3]
```diff
@@ -82,18 +93,7 @@ export async function generateLockFiles(
       execOptions.docker.volumes = [[homeNpmrc, '/home/ubuntu/.npmrc']];
     }
     cmd.push(`${lernaClient} install ${cmdOptions}`);
-    let lernaVersion: string;
-    try {
-      const pJson = JSON.parse(await getFile('package.json'));
```
Comment (viceice) [inline lib/manager/npm/post-update/lerna.ts:87]: I see one new issue now. What if lerna dep is only added to root `package.json` as dependency? Will that be a supported scenario? If yes we won't find lerna version any more.

Comment (gjoseph) [reply lib/manager/npm/post-update/lerna.ts:87]: That's how it should be setup, right? Only the root package should depend on lerna? And that root package _is_ the `lernaPackageFile` we pass above, or am I missing sthg?

**Comment by gjoseph** [comment]
> needs coverage fixes: https://codecov.io/gh/renovatebot/renovate/pull/6675/src/lib/manager/npm/post-update/lerna.ts?before=lib/manager/npm/post-update/lerna.ts
> 
> image

yep, testing for the method returning "latest" was what I wasn't sure how to -- must have been late as I extracted that function among other things for exactly that reason. I've just pushed a change that should address this.

File: lib/manager/npm/post-update/lerna.ts (hunk 3 above)
Comment (rarkins) [reply lib/manager/npm/post-update/lerna.ts:87]: image
^^ this is the root `package.json`, right?

File: lib/manager/npm/post-update/lerna.spec.ts [hunk 4]
```diff
@@ -1,45 +1,54 @@
 import { exec as _exec } from 'child_process';
 import { envMock, mockExecAll } from '../../../../test/execUtil';
-import { git, mocked } from '../../../../test/util';
+import { mocked } from '../../../../test/util';
```
Comment (viceice) [inline lib/manager/npm/post-update/lerna.spec.ts:3]:
```suggestion
import { getName, mocked } from '../../../../test/util';
```

File: lib/manager/npm/post-update/lerna.spec.ts [hunk 5]
```diff
@@ -1,45 +1,54 @@
...
+  };
+}
+
+function lernaPkgFileWithoutLernaDep(lernaClient: string) {
+  return {
+    lernaClient,
+  };
+}
+
 describe('generateLockFiles()', () => {
```
Comment (viceice) [inline lib/manager/npm/post-update/lerna.spec.ts:28]:
```suggestion
describe(getName(__filename), () => {
  describe('generateLockFiles()', () => {
```

File: lib/manager/npm/post-update/lerna.spec.ts [hunk 6]
```diff
@@ -101,12 +107,51 @@ describe('generateLockFiles()', () => {
...
+    const pkg = {};
+    expect(lernaHelper.getLernaVersion(pkg)).toBe('latest');
+  });
+  it('returns latest if specified lerna version is not a valid semVer range', () => {
+    const pkg = {
+      deps: [{ depName: 'lerna', currentValue: '[a.b.c;' }],
+    };
+    expect(lernaHelper.getLernaVersion(pkg)).toBe('latest');
+  });
+});
```
Comment (viceice) [inline lib/manager/npm/post-update/lerna.spec.ts:157]:
```suggestion
  });
});
```

needs prettier fix

File: lib/manager/npm/post-update/lerna.ts [hunk 7]
```diff
@@ -13,13 +12,28 @@ export interface GenerateLockFileResult {
...
+      `Could not detect lerna version in ${lernaPackageFile.packageFile}, using 'latest'`
+    );
+    return 'latest';
+  }
+  return lernaDep.currentValue;
+}
+
 export async function generateLockFiles(
-  lernaClient: string,
+  lernaPackageFile: Partial<PackageFile>,
```
Comment (viceice) [inline lib/manager/npm/post-update/lerna.ts:30]: Why do we use `Partial` here?

**Review by viceice — CHANGES_REQUESTED** [review]
some small changes, will need snapshot update

File: lib/manager/npm/post-update/lerna.ts (hunk 3 above)
Comment (gjoseph) [reply lib/manager/npm/post-update/lerna.ts:87]: root as far as Lerna is concerned yes, but may not be in the root directory of the git repo

File: lib/manager/npm/post-update/lerna.spec.ts (hunk 6 above)
Comment (gjoseph) [reply lib/manager/npm/post-update/lerna.spec.ts:157]: Cool, I'll do these and prettier all at once (although I'm curious if Github's "commit suggestion" feature would execute the hook 🤔 )

File: lib/manager/npm/post-update/lerna.ts (hunk 7 above)
Comment (gjoseph) [reply lib/manager/npm/post-update/lerna.ts:30]: That's what https://github.com/renovatebot/renovate/blob/master/lib/manager/npm/post-update/index.ts#L637 is passing to this function -- is there a way to assert that the given object is _not_ partial and unwrap it?

I do not know why `AdditionalPackageFiles.npm` is an array of `Partial<PackageFile>` however. (since PackageFile's properties are all (?) optional, this seems indeed perhaps unnecessary?

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
