### PR TITLE
fix(go): Add source URLs to releases obtained via GOPROXY

### LINKED ISSUE #12486: Release notes are disappered on Go module update PRs
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Describe the bug

`Release Notes` and link to the repository on Go module update PRs have been disappeared since Oct 31.
Other managers like `npm` seems not affected.

Reproduction: https://github.com/at-wat/renovate-repro-go-release-notes/pull/3
There seems no error in the log.

PR update log on an actual repository: https://github.com/at-wat/gh-pr-comment/pull/162
image
(4 days ago is `2021-10-31T09:27:47Z`)

### Relevant debug logs

<details><summary>Logs</summary>

https://app.renovatebot.com/dashboard#github/at-wat/renovate-repro-go-release-notes/499131692

```
INFO: Repository started
{
  "renovateVersion": "28.23.2"
}

DEBUG: 1 flattened updates found: github.com/at-wat/mqtt-go
DEBUG: Returning 1 branch(es)
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "gomod": [
      {
        "packageFile": "go.mod",
        "constraints": {
          "go": "^1.17"
        },
        "deps": [
          {
            "managerData": {
              "lineNumber": 4
            },
            "depName": "github.com/at-wat/mqtt-go",
            "depType": "require",
            "currentValue": "v0.15.0",
            "datasource": "go",
            "depIndex": 0,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "v0.16.0",
                "newValue": "v0.16.0",
                "releaseTimestamp": "2021-10-20T02:27:46.000Z",
                "newMajor": 0,
                "newMinor": 16,
                "updateType": "minor",
                "branchName": "renovate/github.com-at-wat-mqtt-go-0.x"
              }
            ],
            "warnings": [],
            "versioning": "semver",
            "currentVersion": "v0.15.0",
            "isSingleVersion": true,
            "fixedVersion": "v0.15.0"
          }
        ]
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 1 branch: renovate/github.com-at-wat-mqtt-go-0.x
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 1 Pull Requests
DEBUG: currentHourStart=2021-11-04T06:00:00.000+00:00
DEBUG: PR hourly limit remaining: 1
DEBUG: Calculating prConcurrentLimit (20)
DEBUG: getBranchPr(renovate/github.com-at-wat-mqtt-go-0.x)
DEBUG: findPr(renovate/github.com-at-wat-mqtt-go-0.x, undefined, open)
DEBUG: findPr(renovate/github.com-at-wat-mqtt-go-0.x, undefined, closed)
DEBUG: Found PR #2
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 20
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 1
}
DEBUG: PullRequests limit = 1
DEBUG: Calculating hourly PRs remaining
DEBUG: currentHourStart=2021-11-04T06:00:00.000+00:00
DEBUG: PR hourly limit remaining: 1
DEBUG: Calculating branchConcurrentLimit (20)
DEBUG: 0 already existing branches found:
DEBUG: Branch concurrent limit remaining: 20
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 1
}
DEBUG: Branches limit = 1
DEBUG: Setting current branch to master(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: latest commit(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "branchName": "master",
  "latestCommitDate": "2021-11-04T15:31:55+09:00"
}
DEBUG: getBranchPr(renovate/github.com-at-wat-mqtt-go-0.x)(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: findPr(renovate/github.com-at-wat-mqtt-go-0.x, undefined, open)(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: findPr(renovate/github.com-at-wat-mqtt-go-0.x, undefined, closed)(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Found PR #2(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: branchExists=false(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: dependencyDashboardCheck=recreate(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: recreateClosed is false(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: findPr(renovate/github.com-at-wat-mqtt-go-0.x, Update module github.com/at-wat/mqtt-go to v0.16.0, !open)(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: prAlreadyExisted=false(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: No schedule defined(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Branch needs creating(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Using reuseExistingBranch: false(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: gomod.updateDependency: v0.16.0(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Updating github.com/at-wat/mqtt-go in go.mod(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: gomod.updateArtifacts(go.mod)(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Adding Git authentication for Go Module retrieval for https://api.github.com/ using token auth.(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: go get command included(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "cmd": "go",
  "args": "get -d ./..."
}
DEBUG: Using docker to execute(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Found version constraint - checking for a compatible image to use(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "depName": "docker.io/renovate/go",
  "scheme": "npm",
  "constraint": "^1.17"
}
DEBUG: getLabels(https://index.docker.io, renovate/go, latest)(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Found compatible image version(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "depName": "docker.io/renovate/go",
  "scheme": "npm",
  "constraint": "^1.17",
  "version": "1.17.2"
}
DEBUG: Resolved tag constraint(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "image": "docker.io/renovate/go",
  "tagConstraint": "^1.17",
  "tagVersioning": "npm",
  "tag": "1.17.2"
}
DEBUG: Fetching Docker image: docker.io/renovate/go:1.17.2(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Finished fetching Docker image(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Executing command(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "command": [
    "docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/at-wat/renovate-repro-go-release-notes\":\"/mnt/renovate/gh/at-wat/renovate-repro-go-release-notes\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOPROXY -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_COUNT -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -w \"/mnt/renovate/gh/at-wat/renovate-repro-go-release-notes\" docker.io/renovate/go:1.17.2 bash -l -c \"go get -d ./...\""
  ]
}
DEBUG: exec completed(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "cmd": "docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/at-wat/renovate-repro-go-release-notes\":\"/mnt/renovate/gh/at-wat/renovate-repro-go-release-notes\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOPROXY -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_COUNT -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -w \"/mnt/renovate/gh/at-wat/renovate-repro-go-release-notes\" docker.io/renovate/go:1.17.2 bash -l -c \"go get -d ./...\"",
  "durationMs": 3460,
  "stdout": "",
  "stderr": "go: downloading github.com/at-wat/mqtt-go v0.16.0\ngo: downloading golang.org/x/net v0.0.0-20211004220534-69340ce214a7\n"
}
DEBUG: Returning updated go.sum(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Updated 1 package files(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Updated 1 lock files(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "updatedArtifacts": [
    "go.sum"
  ]
}
DEBUG: 2 file(s) to commit(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Committing files to branch renovate/github.com-at-wat-mqtt-go-0.x(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Setting git author name(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: git commit(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/github.com-at-wat-mqtt-go-0.x",
    "commit": "9356c88",
    "root": false,
    "summary": {
      "changes": 2,
      "insertions": 3,
      "deletions": 0
    }
  }
}
DEBUG: git push(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "result": {
    "pushed": [
      {
        "deleted": false,
        "tag": false,
        "branch": true,
        "new": true,
        "alreadyUpdated": false,
        "local": "refs/heads/renovate/github.com-at-wat-mqtt-go-0.x",
        "remote": "refs/heads/renovate/github.com-at-wat-mqtt-go-0.x"
      }
    ],
    "branch": {
      "local": "renovate/github.com-at-wat-mqtt-go-0.x",
      "remote": "renovate/github.com-at-wat-mqtt-go-0.x",
      "remoteName": "origin"
    },
    "ref": {
      "local": "refs/remotes/origin/renovate/github.com-at-wat-mqtt-go-0.x"
    },
    "remoteMessages": {
      "all": [
        "Create a pull request for 'renovate/github.com-at-wat-mqtt-go-0.x' on GitHub by visiting:",
        "https://github.com/at-wat/renovate-repro-go-release-notes/pull/new/renovate/github.com-at-wat-mqtt-go-0.x"
      ],
      "pullRequestUrl": "https://github.com/at-wat/renovate-repro-go-release-notes/pull/new/renovate/github.com-at-wat-mqtt-go-0.x"
    }
  }
}
INFO: Branch created(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "commitSha": "9356c88"
}
DEBUG: Ensuring PR(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: getBranchPr(renovate/github.com-at-wat-mqtt-go-0.x)(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: findPr(renovate/github.com-at-wat-mqtt-go-0.x, undefined, open)(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: findPr(renovate/github.com-at-wat-mqtt-go-0.x, undefined, closed)(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Found PR #2(branch="renovate/github.com-at-wat-mqtt-go-0.x")
DEBUG: Creating PR(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "prTitle": "Update module github.com/at-wat/mqtt-go to v0.16.0"
}
DEBUG: Creating PR(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "title": "Update module github.com/at-wat/mqtt-go to v0.16.0",
  "head": "at-wat:renovate/github.com-at-wat-mqtt-go-0.x",
  "base": "master",
  "draft": false
}
DEBUG: PR created(branch="renovate/github.com-at-wat-mqtt-go-0.x")
{
  "pr": 3,
  "draft": false
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

Share same `getSourceUrl()` function between `releases-direct.ts` and `releases-goproxy.ts`

## Context:

Closes #12486

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
These PRs were updated with source urls: https://github.com/renovate-testing/test-12229-go-storage/pulls

File: lib/datasource/go/releases-direct.ts [hunk 1]
```diff
@@ -103,5 +105,5 @@ export async function getReleases(
     );
   }
 
-  return res;
+  return { ...res, sourceUrl };
```
Comment (zharinov) [inline lib/datasource/go/releases-direct.ts:108]: Not necessary, but just for consistency

Comment (zharinov) [reply lib/datasource/go/releases-direct.ts:108]: Actually, I've called it here just to be sure tests are producing same results, like if `sourceUrl` from `res` is used

**Review by rarkins — APPROVED** [review]
