### PR TITLE
fix(core/schedule): accept matching cron schedules when run on Sundays

### LINKED ISSUE #19737: Cron schedules don't run on Sundays
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

The cron parser returns the scheduled weekdays as [numbers from 0 (Sunday) to 6 (Saturday)](https://github.com/cheap-glitch/mi-cron/blob/main/src/index.ts#L54).

Luxon returns the current weekday as [a number from 1 (Monday) to 7 (Sunday)](https://moment.github.io/luxon/api-docs/index.html#datetimeweekday).

As a result, [checking whether the current weekday is included in the cron schedule](https://github.com/renovatebot/renovate/blob/e70e6c7d71824c03fd00b98100c07c9c54f9e33c/lib/workers/repository/update/branch/schedule.ts#L101) will always fail on Sundays, because 7 is not in the range 0-6:

```ts
  if (parsedCron.weekDays.indexOf(now.weekday) === -1) {
    // Weekdays mismatch
    return false;
  }
```

Suggested fix:

```diff
-  if (parsedCron.weekDays.indexOf(now.weekday) === -1) {
+  if (parsedCron.weekDays.indexOf(now.weekday % 7) === -1) {
```

### Relevant debug logs

<details><summary>Logs</summary>

The following log was recorded on Sunday, January 8th 2023, 4:38:58 am.

```
DEBUG: Checking schedule(* 0-5 8 * *, null)(branch="renovate/dev-dependencies")
DEBUG: Checking 1 schedule(s)(branch="renovate/dev-dependencies")
DEBUG: Package not scheduled(branch="renovate/dev-dependencies")
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by benj-dobs**
## Changes

Schedules (when interpreted with `mi-cron`) use 0 for Sundays, but today's date (interpreted with `luxon`) uses 7, so the weekday comparison for cron schedules was always failing on Sundays. This PR corrects the comparison between the two schemes.

## Context

- Closes: #19737

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

File: lib/workers/repository/update/branch/schedule.ts [hunk 1]
```diff
@@ -98,7 +98,7 @@ function cronMatches(cron: string, now: DateTime): boolean {
     return false;
   }
 
-  if (parsedCron.weekDays.indexOf(now.weekday) === -1) {
+  if (parsedCron.weekDays.includes(now.weekday % 7)) {
```
Comment (viceice) [inline lib/workers/repository/update/branch/schedule.ts:101]:
```suggestion
  if (!parsedCron.weekDays.includes(now.weekday % 7)) {
```

**Review by viceice — APPROVED** [review]
