### PR TITLE
fix(pep440): added support for widen & replace rangeStrategies

### LINKED ISSUE #6241: [Python] Complex range update should keep same precision
Hi,

The `PR` https://github.com/the-benchmarker/web-frameworks/pull/2683 update `sanic` dependency.

The **pep 440** range `>=19.12.2,<19.13.0` is understood.

However, as the last release is `20.3.0`, the `PR` should update to  `>=20.3.0,<20.4.0` instead of `>=19.12.2,<21.0.0`. The proposal does not keep consistency in range (to allow only patch level upgrades).

Regards,

### PR DESCRIPTION
**Pull request by Gabriel-Ladzaretti**
## Changes
Split current behavior for "replace" range strategy into discrete "widen" and "replace" modes. 
Added fine range precision detection from currently defined user range.

  

Up until now, pep440 versioning did not truly support "replace" range strategy.
As the former behavior for replace was in fact "widen".

## Context
Closes #6241 

## Documentation (please check one with an [x])

- [x] Documentation update is required
- [ ] I have updated the documentation

From [rangeStrategy](https://docs.renovatebot.com/configuration-options/#rangestrategy):

> allowedValues	auto,pin,bump,replace,widen,update-lockfile,in-range-only

While [PEP440 Versioning](https://docs.renovatebot.com/modules/versioning/#pep440-versioning) states:

> ✅ Ranges are supported.
> Valid rangeStrategy values are: bump, extend, pin, replace

Note the extend vs widen mismatch.
the same can be found in pretty much every type of versioning.

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/versioning/pep440/range.ts [hunk 1]
```diff
@@ -5,29 +5,78 @@ import { logger } from '../../logger';
 import { regEx } from '../../util/regex';
 import type { NewValueConfig } from '../types';
 
+// eslint-disable-next-line typescript-enum/no-enum
```
Comment (HonkingGoose) [inline lib/versioning/pep440/range.ts:8]: I think you can update the documentation by changing the `allowedValues` property for the `rangeStrategy` option:

https://github.com/renovatebot/renovate/blob/15c393f79115c0a5fe6429396c5a9e51127ffc67/lib/config/options/index.ts#L1168-L1184

---

@viceice do you know where we keep the source for the autogenerated stuff on this page? https://docs.renovatebot.com/modules/versioning/#pep440-versioning

**Comment by nabeelsaabna** [comment]
Hi @rarkins, @viceice 
can you please review this PR (pending 2 days)
thanks

File: lib/versioning/pep440/range.ts (hunk 1 above)
Comment (viceice) [reply lib/versioning/pep440/range.ts:8]: It's generated from the exports of `index.ts`

File: lib/versioning/pep440/range.ts [hunk 2]
```diff
@@ -244,6 +313,71 @@ function updateRangeValue(
...
+  });
+  return mode;
+}
+
+function trimTrailingZeros(numbers: number[]): number[] {
+  const arr: number[] = [];
+  for (let i = numbers.length - 1; i >= 0; i--) {
+    while (numbers[i] === 0) {
+      i--;
+    }
```
Comment (viceice) [inline lib/versioning/pep440/range.ts:339]: This will also remove zero from `1,0,1`, so this is wrong.

File: lib/versioning/rez/index.spec.ts [hunk 3]
```diff
@@ -257,23 +257,23 @@ describe('versioning/rez/index', () => {
     ${'<=1.3'}           | ${'widen'}    | ${'1.2.3'}     | ${'2.2.5'} | ${'<=2.2.5'}
     ${'<=1.2.3'}         | ${'widen'}    | ${'1.2.3'}     | ${'2.2.5'} | ${'<=2.2.5'}
     ${'<8'}              | ${'replace'}  | ${'7.2.3'}     | ${'8.2.5'} | ${'<9'}
-    ${'<7.3'}            | ${'replace'}  | ${'7.2.3'}     | ${'8.2.5'} | ${'<9.0'}
+    ${'<7.3'}            | ${'replace'}  | ${'7.2.3'}     | ${'8.2.5'} | ${'<9'}
```
Comment (viceice) [inline lib/versioning/rez/index.spec.ts:260]: Not sure if this is right for `rez`, we need some `rez` user to review

**Review by viceice — DISMISSED** [review]

File: lib/versioning/pep440/range.ts [hunk 4]
```diff
@@ -101,7 +161,7 @@ export function getNewValue({
       );
       return getNewValue({
         currentValue,
-        rangeStrategy: 'auto',
+        rangeStrategy: 'replace',
```
[the remark this answers is not in the document]
Comment (Gabriel-Ladzaretti) [reply lib/versioning/pep440/range.ts:164]: Replace was the original behavior prior to the refactor done in this file:
https://github.com/renovatebot/renovate/blob/1e6ec07d8a22ad9c880fb287ac627618b1e7b2c6/lib/versioning/pep440/range.ts#L68-L80

and more importantly to keep renovate unopinionated and inline with the default value for ["rangeStrategy"](https://docs.renovatebot.com/configuration-options/#rangestrategy).

File: lib/versioning/pep440/index.spec.ts [hunk 5]
```diff
@@ -84,71 +84,84 @@ describe('versioning/pep440/index', () => {
...
+    ${'invalid'}            | ${'replace'}     | ${'1.0.0'}     | ${'1.2.3'}   | ${null}
+    ${'invalid'}            | ${'pin'}         | ${'1.0.0'}     | ${'1.2.3'}   | ${'==1.2.3'}
+    ${'===1.0.3'}           | ${'bump'}        | ${'1.0.0'}     | ${'1.2.3'}   | ${null}
+    ${'===1.0.3'}           | ${'replace'}     | ${'1.0.0'}     | ${'1.2.3'}   | ${null}
+    ${'===1.0.3'}           | ${'pin'}         | ${'1.0.0'}     | ${'1.2.3'}   | ${'==1.2.3'}
+    ${'!=1.2.3'}            | ${'bump'}        | ${'1.0.0'}     | ${'1.2.3'}   | ${null}
+    ${'!=1.2.3'}            | ${'replace'}     | ${'1.0.0'}     | ${'1.2.3'}   | ${null}
+    ${'!=1.2.3'}            | ${'pin'}         | ${'1.0.0'}     | ${'1.2.3'}   | ${'==1.2.3'}
+    ${'~=1.1.0,!=1.1.1'}    | ${'unsupported'} | ${'1.0.0'}     | ${'1.2.3'}   | ${'~=1.2.3,!=1.1.1'}
+    ${'>=19.12.2,<20.13.9'} | ${'replace'}     | ${'19.12.2'}   | ${'21.3.1'}  | ${'>=21.3.1,<22.0.0'}
```
Comment (rarkins) [inline lib/versioning/pep440/index.spec.ts:152]: Very hard to know how to replace this one, because it spanned major ranges for no discernible reason. The result doesn't make too much sense either.. but that's ok

File: lib/versioning/pep440/index.spec.ts [hunk 6]
```diff
@@ -84,71 +84,84 @@ describe('versioning/pep440/index', () => {
...
+    ${'>=19.12.2,<19.13.9'} | ${'replace'}     | ${'19.12.2'}   | ${'20.3.1'}  | ${'>=20.3.1,<20.4.0'}
+    ${'>=19.12.2,<19.13.0'} | ${'replace'}     | ${'19.12.2'}   | ${'20.3.1'}  | ${'>=20.3.1,<20.4.0'}
+    ${'>=19.12.2,<19.13.0'} | ${'replace'}     | ${'19.12.2'}   | ${'20.3.0'}  | ${'>=20.3.0,<20.4.0'}
+    ${'>=19.12.2,<19.13.0'} | ${'replace'}     | ${'19.12.2'}   | ${'19.13.1'} | ${'>=19.13.1,<19.14.0'}
+    ${'>=19.12.2,<19.13.0'} | ${'replace'}     | ${'19.12.2'}   | ${'19.13.0'} | ${'>=19.13.0,<19.14.0'}
+    ${'>=19.12.2,<19.13.0'} | ${'auto'}        | ${'19.12.2'}   | ${'19.13.0'} | ${'>=19.13.0,<19.14.0'}
+    ${'>=19.12.2,<20.13.9'} | ${'widen'}       | ${'19.12.2'}   | ${'21.3.1'}  | ${'>=19.12.2,<22.0.0'}
+    ${'>=19.12.2,<19.13.9'} | ${'widen'}       | ${'19.12.2'}   | ${'20.3.1'}  | ${'>=19.12.2,<20.4.0'}
```
Comment (rarkins) [inline lib/versioning/pep440/index.spec.ts:160]:
```suggestion
    ${'>=19.12.2,<20.13.9'} | ${'widen'}       | ${'19.12.2'}   | ${'21.3.1'}  | ${'>=19.12.2,<21.3.2'}
    ${'>=19.12.2,<19.13.9'} | ${'widen'}       | ${'19.12.2'}   | ${'20.3.1'}  | ${'>=19.12.2,<20.3.2'}
```

I suggest to match the "patch precision" of the upper bound here

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/versioning/pep440/index.spec.ts (hunk 5 above)
Comment (Gabriel-Ladzaretti) [reply lib/versioning/pep440/index.spec.ts:152]: yep, this is a wild one 😄.
guess we can remove this test rather than changing any of the current behavior as it is indeed doesnt portrays any "real world" use case.

Comment (rarkins) [reply lib/versioning/pep440/index.spec.ts:152]: Sure, feel free to remove it if it made your code complex for any good reason. Otherwise OK to keep the test

File: lib/versioning/pep440/range.ts (hunk 1 above)
Comment (Gabriel-Ladzaretti) [reply lib/versioning/pep440/range.ts]: so which approach are we going for?
widen -> extend (1 file change)
or the other way around
extend -> widen? (change in 11 files)

Comment (Gabriel-Ladzaretti) [reply lib/versioning/pep440/range.ts]: see pr #14432

**Comment by rarkins** [comment]
@Gabriel-Ladzaretti needs deconflicting

File: lib/versioning/rez/index.spec.ts (hunk 3 above)
Comment (rarkins) [inline lib/versioning/rez/index.spec.ts:260]:
```suggestion
    ${'<7.3'}            | ${'replace'}  | ${'7.2.3'}     | ${'8.2.5'} | ${'<8.3'}
```

Retain same precision

**Review by rarkins — CHANGES_REQUESTED** [review]

**Comment by Gabriel-Ladzaretti** [comment]
not sure about those two,
should we keep <1.2.4.0 or below is sufficient enough?
https://github.com/renovatebot/renovate/blob/3d4c87e2d80d54cb2340a1f6b0c674d810869393/lib/versioning/pep440/index.spec.ts#L109-L110

**Review by rarkins — APPROVED** [review]

**Review by rarkins — APPROVED** [review]

**Comment by HonkingGoose** [comment]
This PR cannot be automerged. There is a review comment that must be resolved first. 😉
