### PR TITLE
fix(config): remove empty items from comma-separated env-supplied config options

### LINKED ISSUE #18045: "RENOVATE_REPOSITORIES: repo1,repo2, " can lead to unexpected bahavior
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.208.1

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.8

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

```
variables:
  RENOVATE_REPOSITORIES: repo1,repo2,
```
with accidental trailing `,` resolves into:

```
         "repositories": [
           "repo1",
           "repo2",
           ""
         ],
```

Let's imagine that you are playing with Renovate using 2 test repos and accidentally add a trailing coma adding the 3rd repo. Unhappily, using a user with too wide access, could generate (for example) an onboarding message in large number of repositories (assuming no dry-run mode was used).

Of course, it is a user mistake and some other circumstances must occur to make a great impact, but maybe Renovate could detect that kind of environment definition and avoid adding `""`for the sake of peace?

### Relevant debug logs

Included above.

I can provide a minimal repo if needed, but I believe my description should be enough.

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by colinodell**
## Changes

Modifies the env var string-to-array coercion function to remove any empty items which may have been caused by an extra trailing comma.

## Context

Closes #18045

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/global/config/parse/env.ts [hunk 1]
```diff
@@ -76,7 +76,11 @@ export function getConfig(inputEnv: NodeJS.ProcessEnv): AllConfig {
 
   const coersions = {
     boolean: (val: string): boolean => val === 'true',
-    array: (val: string): string[] => val.split(',').map((el) => el.trim()),
+    array: (val: string): string[] =>
+      val
+        .split(',')
+        .map((el) => el.trim())
+        .filter((el) => el !== ''),
```
Comment (viceice) [inline lib/workers/global/config/parse/env.ts:83]:
```suggestion
        .filter(is.nonEmptyString),
```

**Review by rarkins — APPROVED** [review]
