### PR TITLE
fix(azure): correctly map autoApprove response

### LINKED ISSUE #12303: Error getBranchNameWithoutRefsheadsPrefix(undefined) during PR creation
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

Azure DevOps Server

### If you're self-hosting Renovate, tell us what version of Renovate you run.

28.8.5

### Describe the bug

Occasionally, renovate throws the following error, while creating a Pull Request:

> getBranchNameWithoutRefsheadsPrefix(undefined)

In this case, the Pull Request is actually created, but it seems like Renovate is missing its details, and is not able to continue to work with it. For example, Reviewers are not added, and Artifact Update Problems are not reported.

It doesn't happen every time, sometimes everything works like expected. I wasn't able yet to find a pattern, currently it seems quite random to me. The behaviour is not consistent within a run, so during one run, it can happen that some PRs are created with and some without errors.

We are running Azure DevOps Server 2020, and latest version of renovate.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /home/build-service-agent/buildAgent/_work/72/s/config
DEBUG: File config
       "config": {
         "platform": "azure",
         "endpoint": "https://our-self-hosted-azure-devops.com/OurCollection/",
         "token": "***********",
         "repositories": [
           "MyProject/my-repo"
         ],
         "secrets": {"GITHUB_TOKEN": "***********"},
         "allowedPostUpgradeCommands": ["^npm ci --ignore-scripts$", "^npm run "]
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {"hostRules": []}
DEBUG: Combined config
       "config": {
         "platform": "azure",
         "endpoint": "https://our-self-hosted-azure-devops.com/OurCollection/",
         "token": "***********",
         "repositories": [
           "MyProject/my-repo"
         ],
         "secrets": {"GITHUB_TOKEN": "***********"},
         "allowedPostUpgradeCommands": ["^npm ci --ignore-scripts$", "^npm run "],
         "hostRules": []
       }
DEBUG: Adding trailing slash to endpoint
DEBUG: Adding token authentication for our-self-hosted-azure-devops.com to hostRules
DEBUG: Using baseDir: /tmp/renovate
DEBUG: Using cacheDir: /tmp/renovate/cache
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
DEBUG: Commits limit = null
DEBUG: Clearing hostRules
DEBUG: Adding token authentication for our-self-hosted-azure-devops.com to hostRules
 INFO: Repository started (repository=MyProject/my-repo)
       "renovateVersion": "28.8.5"
DEBUG: Using localDir: /tmp/renovate/repos/azure/MyProject/my-repo (repository=MyProject/my-repo)
DEBUG: initRepo("MyProject/my-repo") (repository=MyProject/my-repo)
DEBUG: Repository details (repository=MyProject/my-repo)
       "repositoryDetails": {
         "id": "66c6fb80-afd4-47f5-9457-43de6b3fa651",
         "name": "my-repo",
         "url": "https://our-self-hosted-azure-devops.com/OurCollection/d9c0aae6-4b21-474e-bb9a-6460b1585094/_apis/git/repositories/66c6fb80-afd4-47f5-9457-43de6b3fa651",
         "project": {
           "id": "d9c0aae6-4b21-474e-bb9a-6460b1585094",
           "name": "MyProject",
           "url": "https://our-self-hosted-azure-devops.com/OurCollection/_apis/projects/d9c0aae6-4b21-474e-bb9a-6460b1585094",
           "state": "wellFormed",
           "revision": 297,
           "visibility": 0,
           "lastUpdateTime": "2020-09-16T13:46:23.073Z"
         },
         "defaultBranch": "refs/heads/develop",
         "size": 240886,
         "remoteUrl": "https://our-self-hosted-azure-devops.com/OurCollection/MyProject/_git/my-repo",
         "sshUrl": "ssh://our-self-hosted-azure-devops.com:22/OurCollection/MyProject/_git/my-repo",
         "webUrl": "https://our-self-hosted-azure-devops.com/OurCollection/MyProject/_git/my-repo"
       }
DEBUG: MyProject/my-repo owner = ?owner? (repository=MyProject/my-repo)
DEBUG: MyProject/my-repo default branch = develop (repository=MyProject/my-repo)
DEBUG: resetMemCache() (repository=MyProject/my-repo)
DEBUG: Resetting npmrc (repository=MyProject/my-repo)
DEBUG: checkOnboarding() (repository=MyProject/my-repo)
DEBUG: isOnboarded() (repository=MyProject/my-repo)
DEBUG: findFile(renovate.json) (repository=MyProject/my-repo)
DEBUG: Initializing git repository into /tmp/renovate/repos/azure/MyProject/my-repo (repository=MyProject/my-repo)
DEBUG: Performing blobless clone (repository=MyProject/my-repo)
DEBUG: git clone completed (repository=MyProject/my-repo)
       "durationMs": 351
DEBUG: latest repository commit (repository=MyProject/my-repo)
       "latestCommit": {
         "hash": "addc8048ebe40fd0b4ba5b1f17728fd410248f8a",
         "date": "2021-10-25T09:11:51+02:00",
         "message": "Merged PR 3390: PLC-1374 setup renovate",
         "refs": "HEAD -> develop, origin/develop, origin/HEAD",
         "body": "PLC-1374 setup renovate\n",
         "author_name": "D Simon"
       }
DEBUG: Config file exists (repository=MyProject/my-repo)
       "fileName": "renovate.json"
DEBUG: Repo is onboarded (repository=MyProject/my-repo)
DEBUG: Found renovate.json config file (repository=MyProject/my-repo)
DEBUG: Repository config (repository=MyProject/my-repo)
       "fileName": "renovate.json",
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "extends": [
           "MyProject/renovate-config",
           "MyProject/renovate-config:lint-and-test"
         ],
         "reviewers": ["DEVELOPMENT\\d.simon"],
         "packageRules": [
           {
             "matchPackageNames": ["iso3166-2-db"],
             "postUpgradeTasks": {
               "commands": [
                 "npm ci --ignore-scripts",
                 "npm run generate-locale-files"
               ],
               "fileFilters": ["**/**"]
             }
           }
         ]
       }
DEBUG: migrateAndValidate() (repository=MyProject/my-repo)
DEBUG: No config migration necessary (repository=MyProject/my-repo)
DEBUG: massaged config (repository=MyProject/my-repo)
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "extends": [
           "MyProject/renovate-config",
           "MyProject/renovate-config:lint-and-test"
         ],
         "reviewers": ["DEVELOPMENT\\d.simon"],
         "packageRules": [
           {
             "matchPackageNames": ["iso3166-2-db"],
             "postUpgradeTasks": {
               "commands": [
                 "npm ci --ignore-scripts",
                 "npm run generate-locale-files"
               ],
               "fileFilters": ["**/**"]
             }
           }
         ]
       }
DEBUG: migrated config (repository=MyProject/my-repo)
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "extends": [
           "MyProject/renovate-config",
           "MyProject/renovate-config:lint-and-test"
         ],
         "reviewers": ["DEVELOPMENT\\d.simon"],
         "packageRules": [
           {
             "matchPackageNames": ["iso3166-2-db"],
             "postUpgradeTasks": {
               "commands": [
                 "npm ci --ignore-scripts",
                 "npm run generate-locale-files"
               ],
               "fileFilters": ["**/**"]
             }
           }
         ]
       }
DEBUG: Ignoring any .npmrc files in repository due to configured npmrc (repository=MyProject/my-repo)
DEBUG: Setting npmrc (repository=MyProject/my-repo)
DEBUG: Setting hostRules from config (repository=MyProject/my-repo)
DEBUG: Adding token authentication for github.com to hostRules (repository=MyProject/my-repo)
DEBUG: Found repo ignorePaths (repository=MyProject/my-repo)
       "ignorePaths": ["**/node_modules/**", "**/bower_components/**"]
DEBUG: detectSemanticCommits() (repository=MyProject/my-repo)
DEBUG: getCommitMessages (repository=MyProject/my-repo)
DEBUG: Semantic commits detection: unknown (repository=MyProject/my-repo)
DEBUG: No semantic commits detected (repository=MyProject/my-repo)
DEBUG: No vulnerability alerts found (repository=MyProject/my-repo)
DEBUG: No baseBranches (repository=MyProject/my-repo)
DEBUG: extract() (repository=MyProject/my-repo)
DEBUG: Setting current branch to develop (repository=MyProject/my-repo)
DEBUG: latest commit (repository=MyProject/my-repo)
       "branchName": "develop",
       "latestCommitDate": "2021-10-25T09:11:51+02:00"
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)requirements\.ya?ml$ for manager ansible-galaxy (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)galaxy\.ya?ml$ for manager ansible-galaxy (repository=MyProject/my-repo)
DEBUG: Using file match: azure.*pipelines?.*\.ya?ml$ for manager azure-pipelines (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)batect(-bundle)?\.yml$ for manager batect (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)batect$ for manager batect-wrapper (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)WORKSPACE(|\.bazel)$ for manager bazel (repository=MyProject/my-repo)
DEBUG: Using file match: \.bzl$ for manager bazel (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)\.?bitbucket-pipelines\.ya?ml$ for manager bitbucket-pipelines (repository=MyProject/my-repo)
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite (repository=MyProject/my-repo)
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)Gemfile$ for manager bundler (repository=MyProject/my-repo)
DEBUG: Using file match: \.cake$ for manager cake (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)cloudbuild.ya?ml for manager cloudbuild (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)Podfile$ for manager cocoapods (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/|\.)Dockerfile$ for manager dockerfile (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/).gitmodules$ for manager git-submodules (repository=MyProject/my-repo)
DEBUG: Using file match: ^(workflow-templates|\.github\/workflows)\/[^/]+\.ya?ml$ for manager github-actions (repository=MyProject/my-repo)
DEBUG: Using file match: (^|\/)action\.ya?ml$ for manager github-actions (repository=MyProject/my-repo)
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci (repository=MyProject/my-repo)
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci-include (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)go.mod$ for manager gomod (repository=MyProject/my-repo)
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle (repository=MyProject/my-repo)
DEBUG: Using file match: (^|\/)gradle\.properties$ for manager gradle (repository=MyProject/my-repo)
DEBUG: Using file match: (^|\/)gradle\/.+\.toml$ for manager gradle (repository=MyProject/my-repo)
DEBUG: Using file match: \.versions\.toml$ for manager gradle (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)requirements\.yaml$ for manager helm-requirements (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)values.yaml$ for manager helm-values (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)helmfile.yaml$ for manager helmfile (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)Chart.yaml$ for manager helmv3 (repository=MyProject/my-repo)
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew (repository=MyProject/my-repo)
DEBUG: Using file match: \.html?$ for manager html (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)plugins\.(txt|ya?ml)$ for manager jenkins (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)kustomization\.yaml for manager kustomize (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen (repository=MyProject/my-repo)
DEBUG: Using file match: \.pom\.xml$ for manager maven (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)pom\.xml$ for manager maven (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)package.js$ for manager meteor (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)mix\.exs$ for manager mix (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/).node-version$ for manager nodenv (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)package.json$ for manager npm (repository=MyProject/my-repo)
DEBUG: Using file match: \.(?:cs|fs|vb)proj$ for manager nuget (repository=MyProject/my-repo)
DEBUG: Using file match: \.(?:props|targets)$ for manager nuget (repository=MyProject/my-repo)
DEBUG: Using file match: \.config\/dotnet-tools\.json$ for manager nuget (repository=MyProject/my-repo)
DEBUG: Using file match: (^|//)global\.json$ for manager nuget (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)\.nvmrc$ for manager nvm (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)([\w-]*)requirements\.(txt|pip)$ for manager pip_requirements (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)\.pre-commit-config\.yaml$ for manager pre-commit (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/).python-version$ for manager pyenv (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version (repository=MyProject/my-repo)
DEBUG: Using file match: \.sbt$ for manager sbt (repository=MyProject/my-repo)
DEBUG: Using file match: project/[^/]*.scala$ for manager sbt (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)setup\.cfg$ for manager setup-cfg (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)Package\.swift for manager swift (repository=MyProject/my-repo)
DEBUG: Using file match: \.tf$ for manager terraform (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)\.terraform-version$ for manager terraform-version (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)terragrunt\.hcl$ for manager terragrunt (repository=MyProject/my-repo)
DEBUG: Using file match: (^|/)\.terragrunt-version$ for manager terragrunt-version (repository=MyProject/my-repo)
DEBUG: Using file match: ^.travis.yml$ for manager travis (repository=MyProject/my-repo)
DEBUG: Matched 1 file(s) for manager azure-pipelines: azure-pipelines.yaml (repository=MyProject/my-repo)
DEBUG: Matched 1 file(s) for manager npm: package.json (repository=MyProject/my-repo)
DEBUG: npm file package.json has name "my-repo" (repository=MyProject/my-repo)
DEBUG: Detecting pnpm Workspaces (repository=MyProject/my-repo)
DEBUG: Detecting Lerna and Yarn Workspaces (repository=MyProject/my-repo)
DEBUG: Finding locked versions (repository=MyProject/my-repo)
DEBUG: Found package-lock.json for package.json (repository=MyProject/my-repo)
DEBUG: Found npm package files (repository=MyProject/my-repo)
DEBUG: Found 1 package file(s) (repository=MyProject/my-repo)
 INFO: Dependency extraction complete (repository=MyProject/my-repo)
       "baseBranch": "develop",
       "stats": {
         "managers": {"npm": {"fileCount": 1, "depCount": 3}},
         "total": {"fileCount": 1, "depCount": 3}
       }
DEBUG: Package releases lookups complete (repository=MyProject/my-repo)
       "baseBranch": "develop"
DEBUG: branchifyUpgrades (repository=MyProject/my-repo)
DEBUG: 3 flattened updates found: @types/node, iso3166-2-db (repository=MyProject/my-repo)
DEBUG: Returning 3 branch(es) (repository=MyProject/my-repo)
DEBUG: Fetching changelog: https://github.com/DefinitelyTyped/DefinitelyTyped (16.11.3 -> 16.11.4) (repository=MyProject/my-repo)
DEBUG: Fetching changelog: https://github.com/esosedi/3166 (2.3.8 -> 2.3.9) (repository=MyProject/my-repo)
DEBUG: config.repoIsOnboarded=true (repository=MyProject/my-repo)
DEBUG: packageFiles with updates (repository=MyProject/my-repo)
       "config": {
         "npm": [
           {
             "packageFile": "package.json",
             "deps": [
               {
                 "depType": "devDependencies",
                 "depName": "@types/node",
                 "currentValue": "16.11.3",
                 "datasource": "npm",
                 "prettyDepType": "devDependency",
                 "lockedVersion": "16.11.3",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "16.11.4",
                     "newValue": "16.11.4",
                     "releaseTimestamp": "2021-10-25T06:50:02.663Z",
                     "newMajor": 16,
                     "newMinor": 11,
                     "updateType": "patch",
                     "branchName": "renovate/node-16.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "npm",
                 "sourceUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped",
                 "sourceDirectory": "types/node",
                 "currentVersion": "16.11.3",
                 "isSingleVersion": true,
                 "fixedVersion": "16.11.3"
               },
               {
                 "depType": "devDependencies",
                 "depName": "iso3166-2-db",
                 "currentValue": "2.3.8",
                 "datasource": "npm",
                 "prettyDepType": "devDependency",
                 "lockedVersion": "2.3.8",
                 "depIndex": 1,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "2.3.9",
                     "newValue": "2.3.9",
                     "releaseTimestamp": "2021-10-16T08:25:52.424Z",
                     "newMajor": 2,
                     "newMinor": 3,
                     "updateType": "patch",
                     "branchName": "renovate/iso3166-2-db-2.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "npm",
                 "sourceUrl": "https://github.com/esosedi/3166",
                 "currentVersion": "2.3.8",
                 "isSingleVersion": true,
                 "fixedVersion": "2.3.8"
               },
               {
                 "depType": "devDependencies",
                 "depName": "typescript",
                 "currentValue": "4.4.4",
                 "datasource": "npm",
                 "prettyDepType": "devDependency",
                 "lockedVersion": "4.4.4",
                 "depIndex": 2,
                 "updates": [],
                 "warnings": [],
                 "versioning": "npm",
                 "sourceUrl": "https://github.com/Microsoft/TypeScript",
                 "homepage": "https://www.typescriptlang.org/",
                 "currentVersion": "4.4.4",
                 "fixedVersion": "4.4.4"
               }
             ],
             "packageJsonName": "my-repo",
             "packageFileVersion": "1.0.0",
             "packageJsonType": "library",
             "npmLock": "package-lock.json",
             "managerData": {"yarnZeroInstall": false},
             "skipInstalls": true,
             "constraints": {},
             "lockFiles": ["package-lock.json"]
           }
         ]
       }
DEBUG: processRepo() (repository=MyProject/my-repo)
DEBUG: Processing 3 branches: renovate/iso3166-2-db-2.x, renovate/lock-file-maintenance, renovate/node-16.x (repository=MyProject/my-repo)
DEBUG: Calculated maximum PRs remaining this run (repository=MyProject/my-repo)
       "prsRemaining": 99
DEBUG: PullRequests limit = 99 (repository=MyProject/my-repo)
DEBUG: Calculated maximum branches remaining this run (repository=MyProject/my-repo)
       "branchesRemaining": 99
DEBUG: Branches limit = 99 (repository=MyProject/my-repo)
DEBUG: Setting current branch to develop (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: latest commit (repository=MyProject/my-repo, branch=renovate/node-16.x)
       "branchName": "develop",
       "latestCommitDate": "2021-10-25T09:11:51+02:00"
DEBUG: getBranchPr(renovate/node-16.x) (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: getPrList() (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: Retrieved Pull Requests (repository=MyProject/my-repo, branch=renovate/node-16.x)
       "length": 7
DEBUG: branchExists=false (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: dependencyDashboardCheck=undefined (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: recreateClosed is false (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: getPrList() (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: prAlreadyExisted=false (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: Checking schedule(before 3am on the first day of the month, null) (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: Checking 1 schedule(s) (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: Checking schedule "before 3am on the first day of the month" (repository=MyProject/my-repo, branch=renovate/node-16.x)
       "parsedSchedule": {"schedules": [{"t_b": [10800], "D": [1]}], "exceptions": [], "error": -1}
DEBUG: Package not scheduled (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: Skipping branch creation as not within schedule (repository=MyProject/my-repo, branch=renovate/node-16.x)
DEBUG: Setting current branch to develop (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: latest commit (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "branchName": "develop",
       "latestCommitDate": "2021-10-25T09:11:51+02:00"
DEBUG: getBranchPr(renovate/iso3166-2-db-2.x) (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: getPrList() (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: branchExists=false (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: dependencyDashboardCheck=undefined (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: recreateClosed is false (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: getPrList() (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: prAlreadyExisted=false (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Checking schedule(at any time, null) (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: No schedule defined (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Branch needs creating (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Using reuseExistingBranch: false (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: npm.updateDependency(): devDependencies.iso3166-2-db = 2.3.9 (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Updating iso3166-2-db in package.json (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Updated 1 package files (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Getting updated lock files (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Writing package.json files (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "packageFiles": ["package.json"]
DEBUG: Writing package-lock.json (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Writing any updated package files (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Writing package.json (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: npmrc file found in repository (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Generating package-lock.json for . (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Spawning npm install to create /tmp/renovate/repos/azure/MyProject/my-repo/package-lock.json (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: No npm compatibility range found - installing npm latest (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Updating lock file only (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: No node constraint found - using latest (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Executing command (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "command": ["npm install --package-lock-only --no-audit --ignore-scripts"]
DEBUG: exec completed (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "cmd": "npm install --package-lock-only --no-audit --ignore-scripts",
       "durationMs": 690,
       "stdout": "\nup to date in 434ms\n",
       "stderr": ""
DEBUG: package-lock.json needs updating (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Updated 1 lock files (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "updatedArtifacts": ["package-lock.json"]
DEBUG: 2 file(s) to commit (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Committing files to branch renovate/iso3166-2-db-2.x (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Setting git author name (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "gitAuthorName": "Renovate Bot"
DEBUG: Setting git author email (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "gitAuthorEmail": "renovate@whitesourcesoftware.com"
DEBUG: git commit (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/iso3166-2-db-2.x",
         "commit": "96861bf",
         "root": false,
         "summary": {"changes": 2, "insertions": 152, "deletions": 152}
       }
DEBUG: git push (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "result": {
         "pushed": [
           {
             "deleted": false,
             "tag": false,
             "branch": true,
             "new": true,
             "alreadyUpdated": false,
             "local": "refs/heads/renovate/iso3166-2-db-2.x",
             "remote": "refs/heads/renovate/iso3166-2-db-2.x"
           }
         ],
         "branch": {
           "local": "renovate/iso3166-2-db-2.x",
           "remote": "renovate/iso3166-2-db-2.x",
           "remoteName": "origin"
         },
         "ref": {"local": "refs/remotes/origin/renovate/iso3166-2-db-2.x"},
         "remoteMessages": {"all": []}
       }
 INFO: Branch created (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "commitSha": "96861bf"
DEBUG: Ensuring PR (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: There are 0 errors and 0 warnings (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: getBranchPr(renovate/iso3166-2-db-2.x) (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: getPrList() (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Creating PR (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "prTitle": "Update dependency iso3166-2-db to v2.3.9"
ERROR: getBranchNameWithoutRefsheadsPrefix(undefined) (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
ERROR: getBranchNameWithoutRefsheadsPrefix(undefined) (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
 INFO: PR created (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "pr": undefined,
       "prTitle": "Update dependency iso3166-2-db to v2.3.9"
DEBUG: Reviewer added: DEVELOPMENT\d.simon (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Added reviewers (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
       "reviewers": ["DEVELOPMENT\\d.simon"]
DEBUG: Created Pull Request #undefined (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: PR is not configured for automerge (repository=MyProject/my-repo, branch=renovate/iso3166-2-db-2.x)
DEBUG: Setting current branch to develop (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
DEBUG: latest commit (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
       "branchName": "develop",
       "latestCommitDate": "2021-10-25T09:11:51+02:00"
DEBUG: getBranchPr(renovate/lock-file-maintenance) (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
DEBUG: getPrList() (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
DEBUG: branchExists=false (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
DEBUG: dependencyDashboardCheck=undefined (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
DEBUG: recreateClosed is true (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
DEBUG: Checking schedule(before 5am on monday, null) (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
DEBUG: Checking 1 schedule(s) (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
DEBUG: Checking schedule "before 5am on monday" (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
       "parsedSchedule": {"schedules": [{"t_b": [18000], "d": [2]}], "exceptions": [], "error": -1}
DEBUG: Package not scheduled (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
DEBUG: Skipping branch creation as not within schedule (repository=MyProject/my-repo, branch=renovate/lock-file-maintenance)
DEBUG: getBranchPr(renovate/iso3166-2-db-2.x) (repository=MyProject/my-repo)
DEBUG: getPrList() (repository=MyProject/my-repo)
DEBUG: Closing Dependency Dashboard (repository=MyProject/my-repo)
DEBUG: Removing any stale branches (repository=MyProject/my-repo)
DEBUG: config.repoIsOnboarded=true (repository=MyProject/my-repo)
DEBUG: Branch lists (repository=MyProject/my-repo)
       "branchList": [
         "renovate/iso3166-2-db-2.x",
         "renovate/lock-file-maintenance",
         "renovate/node-16.x"
       ],
       "renovateBranches": ["renovate/iso3166-2-db-2.x"]
DEBUG: remainingBranches= (repository=MyProject/my-repo)
DEBUG: No branches to clean up (repository=MyProject/my-repo)
DEBUG: Repository timing splits (milliseconds) (repository=MyProject/my-repo)
       "splits": {"init": 1621, "extract": 512, "lookup": 5941, "update": 65912},
       "total": 75944
DEBUG: http statistics (repository=MyProject/my-repo)
       "urls": {
         "https://api.github.com/repos/esosedi/3166 (GET)": 1,
         "https://api.github.com/repos/esosedi/3166/git/trees/master (GET)": 1,
         "https://api.github.com/repos/esosedi/3166/releases (GET)": 1,
         "https://api.github.com/repos/esosedi/3166/tags (GET)": 1,
         "https://our-custom-registry.com/npm/iso3166-2-db (GET)": 1
       },
       "hostStats": {
         "api.github.com": {"requestCount": 4, "requestAvgMs": 1211, "queueAvgMs": 0},
         "our-custom-registry.com": {
           "requestCount": 1,
           "requestAvgMs": 868,
           "queueAvgMs": 0
         }
       },
       "totalRequests": 5
 INFO: Repository finished (repository=MyProject/my-repo)
       "durationMs": 75944
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "cfYtBMFNs",
           "repository": "MyProject/my-repo",
           "branch": "renovate/iso3166-2-db-2.x",
           "msg": "getBranchNameWithoutRefsheadsPrefix(undefined)"
         },
         {
           "name": "renovate",
           "level": 50,
           "logContext": "cfYtBMFNs",
           "repository": "MyProject/my-repo",
           "branch": "renovate/iso3166-2-db-2.x",
           "msg": "getBranchNameWithoutRefsheadsPrefix(undefined)"
         }
       ]
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by dkimmich-onventis**
## Changes:

Currently there is a type mismatch when autoApproving a pull request in Azure. When adding a reviewer with the Azure API, the response type is `IdentityRefWithVote`, see [here](https://github.com/microsoft/azure-devops-node-api/blob/e3daeea0d23b9d011a88b120e53eb4f8aa475542/api/GitApi.ts#L100). However, the `pr` variable which should have type `GitPullRequest` is overriden with the response, which leads to the PR information getting lost.

## Context:

Closes #12303

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
I think this needs a little more. reviewers needs to be a string array.

**Comment by dsimon-onventis** [comment]
> I think this needs a little more. reviewers needs to be a string array.

You are right, should the `reviewerUrl` be used then?

File: lib/platform/azure/index.ts [hunk 1]
```diff
@@ -410,17 +410,19 @@ export async function createPr({
...
-        reviewerUrl: pr.createdBy.url,
-        vote: AzurePrVote.Approved,
-        isFlagged: false,
-        isRequired: false,
-      },
-      config.repoId,
-      pr.pullRequestId,
-      pr.createdBy.id
-    );
+    pr.reviewers = [
```
Comment (viceice) [inline lib/platform/azure/index.ts:413]:
```suggestion
```
I think we should just skip the assignment here, as it's unused anyways.

File: lib/platform/azure/index.ts [hunk 2]
```diff
@@ -410,17 +410,19 @@ export async function createPr({
...
+          reviewerUrl: pr.createdBy.url,
+          vote: AzurePrVote.Approved,
+          isFlagged: false,
+          isRequired: false,
+        },
+        config.repoId,
+        pr.pullRequestId,
+        pr.createdBy.id
+      ),
+    ];
```
Comment (viceice) [inline lib/platform/azure/index.ts:425]:
```suggestion
```

File: lib/platform/azure/util.ts [hunk 3]
```diff
@@ -116,6 +118,7 @@ export function getRenovatePRFormat(azurePr: GitPullRequest): AzurePr {
     targetBranch,
     createdAt,
     ...(isConflicted && { isConflicted }),
+    ...(reviewers && { reviewers }),
```
Comment (viceice) [inline lib/platform/azure/util.ts:121]: I think this should be reverted, as it's not necessary.

**Comment by JamieMagee** [comment]
Good catch! How did TypeScript not warn on this?

It looks like we have an update for the Azure DevOps API too!

**Review by viceice — APPROVED** [review]
