### PR TITLE
fix(docker-compose): support docker-compose.yml version 1

### LINKED ISSUE #6570: docker-compose.extractPackageFile silently assumes version 2+
**What Renovate type are you using?**
Self-hosted.

**Describe the bug**
Renovate assumes that a `docker-compose.yaml` file will have a `services` key, which is only true of version 2 and 3 docker-compose files; version 1 puts all of the services on the top level. This causes renovate to silently fail to find anything to update on older compose files.

Ideally Renovate should check the `version` and load the services from the root if it's absent, or at least log a message explaining that this is what happened.

**To Reproduce**
Run renovate on a docker-compose v1 file and then spend several hours trying to figure out what you've misconfigured to make it not try to update anything.

### PR DESCRIPTION
**Pull request by wolfgang42**
Closes #6570. Also contains some other refactorings of the function and its related tests; I recommend reviewing the commits individually rather than trying to look at all the changes at once.

### CODE REVIEW

File: lib/manager/docker-compose/extract.ts [hunk 1]
```diff
@@ -79,9 +90,6 @@ export function extractPackageFile(
       .filter(Boolean);
 
     logger.trace({ deps }, 'Docker Compose image');
-    if (!deps.length) {
```
Comment (rarkins) [inline lib/manager/docker-compose/extract.ts:82]: The getPkgReleases() logic in datasource/index will actually convert an empty file to null anyway. We generally prefer to ignore files with no dependencies.
