### PR TITLE
fix(config): improve config migration PR body and title

### LINKED ISSUE #16354: Config Migration PR title should not be "Configure Renovate"
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

After enabling `configMigration`, a resulting PR is titled "Configure Renovate". It should instead be "Migrate Renovate Config".

Example: https://github.com/renovatebot/docker-helm/pull/13

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Fixes config migration PR to not use onboarding title, and improves PR body text. Also flags feature as experimental.

## Context

Closes #16354

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
image

Example PR. Note that the PR title does not follow conventional commits although the commit message does - this needs to be fixed later.

File: lib/config/options/index.ts [hunk 1]
```diff
@@ -129,6 +129,9 @@ const options: RenovateOptions[] = [
     stage: 'repository',
     type: 'boolean',
     default: false,
+    experimental: true,
+    experimentalDescription:
+      'Config migration PRs are still being improved, in particular to reduce the amount of reordering and whitespace changes.',
```
Comment (HonkingGoose) [inline lib/config/options/index.ts:134]:
```suggestion
      'We're improving config migration PRs, focusing on reducing the amount of reordering and whitespace changes. We recommend you avoid this feature for now.',
```

How about something like this? We should probably warn our users to stay away while we work on this feature some more. 😄 

We should also be clear on who's doing the work. 😉

File: lib/workers/repository/config-migration/pr/index.ts [hunk 2]
```diff
@@ -35,8 +34,10 @@ export async function ensureConfigMigrationPr(
   });
   const filename = migratedConfigData.filename;
   logger.debug('Filling in config migration PR template');
-  let prTemplate = `Config migration needed, merge this PR to update your Renovate configuration file.\n\n`;
-  prTemplate += emojify(
+  let prBody = `The Renovate config in this repository needs migrating. Typically this is because one or more configuration options you are using have been renamed.
+
+  This PR does not need to be merged urgently, because Renovate will continue to migrate these fields internally each time it runs, but in future some of these fields may be fully deprecated and migrations removed, so it's best to apply such migrations when they are suggested.\n\n`;
```
Comment (HonkingGoose) [inline lib/workers/repository/config-migration/pr/index.ts:39]:
```suggestion
  You don't need to merge this PR right away, because Renovate will continue to migrate these fields internally each time it runs. But later some of these fields may be fully deprecated and the migrations removed. So it's a good idea to merge this migration PR soon. \n\n`;
```

What's the key point ? I guess it's something like:

> Please merge this PR sometimes in the next few weeks, so you're up to date with current terms, and don't get problems when the Renovate team deprecates the feature, and removes the migrations.

File: lib/workers/repository/config-migration/pr/index.ts [hunk 3]
```diff
@@ -45,33 +46,12 @@ ${
...
-#### Migration completed successfully, No errors or warnings found.
-{{/if}}
----
-
 
-:question: Got questions? Check out Renovate's [Docs](${
-      config.productLinks?.documentation
-    }), particularly the Getting Started section.
-If you need any further assistance then you can also [request help here](${
+:question: Got questions? Something look not right? Please don't hesitate to [request help here](${
```
Comment (HonkingGoose) [inline lib/workers/repository/config-migration/pr/index.ts:50]: > Something look not right?

Is this proper English? It looks off to me. 😄 I expected something like:

```suggestion
:question: Got questions? Does something look wrong to you? Please don't hesitate to [request help here](${
```

**Review by HonkingGoose — CHANGES_REQUESTED** [review]

File: lib/config/options/index.ts (hunk 1 above)
Comment (rarkins) [reply lib/config/options/index.ts:134]: After this PR is complete, I don't want people to avoid it. In fact I would like for people to test it out. I just want to make sure they don't go enabling it org-wide without thought

Comment (HonkingGoose) [reply lib/config/options/index.ts:134]:
```suggestion
      'We're improving config migration PRs, focusing on reducing the amount of reordering and whitespace changes.',
```

Let's drop the "stay away, here be dragons" warning then.

File: lib/workers/repository/config-migration/pr/index.ts (hunk 2 above)
Comment (rarkins) [reply lib/workers/repository/config-migration/pr/index.ts:39]: I don't want to alarm people that "you must merge this now or Renovate won't keep running"

Comment (HonkingGoose) [reply lib/workers/repository/config-migration/pr/index.ts:39]: I agree that we shouldn't scare our users. I'm not happy with the current wording though.

How about something like this:

> You do not need to merge this PR right away, because Renovate will continue to migrate these fields internally each time it runs. But later we may fully deprecate some of these fields and remove the migrations. We recommend you apply our migrations when they are suggested.

This text makes it clear who does what, and puts the reader into the picture:

- Use `we` to talk about us as Renovate developers:
  - We remove the fields and drop the migrations
  - We recommend the user merge the config migration PR
- Use `you` to talk about our user:
  - You don't need to merge this PR right away
  - You should apply our migrations

**Review by HonkingGoose — APPROVED** [review]
The text of the PR looks good to go now.

File: lib/workers/repository/config-migration/pr/index.ts [hunk 4]
```diff
@@ -45,33 +46,12 @@ ${
...
     : ''
 }
----
-{{#if hasWarningsErrors}}
-{{{warnings}}}
-{{{errors}}}
-{{else}}
-#### Migration completed successfully, No errors or warnings found.
-{{/if}}
----
```
Comment (viceice) [inline lib/workers/repository/config-migration/pr/index.ts:55]: are we sure we don't want those?

**Review by viceice — COMMENTED** [review]
Otherwise LGTM

File: lib/workers/repository/config-migration/pr/index.ts (hunk 4 above)
Comment (rarkins) [reply lib/workers/repository/config-migration/pr/index.ts:55]: I am not sure they will be related to the config migration.

**Review by viceice — APPROVED** [review]
