### PR TITLE
fix(dry-run): don't check non existing branch in dry-run

### LINKED ISSUE #6892: Dry-run throws false errors related to onboarding PRs
**What Renovate type are you using?**

I'm running renovate self-hosted on a self-hosted GitLab instance using the official docker container.

**Describe the bug**

In my CI pipeline for renovate, i usually first check with `--dry-run` to see if there are any errors that might occur due to a renovate update or anything else (as renovate also submits PRs to update itself :D ).
When giving the Renovate Bot access to a repository with the correct permissions, it will scan the repository and notice, that it has to create an onboarding PR, which is correct. Then in the next step, it throws an error (only logs it due to dry-run) about checking the non-existant `renovate/configure` branch. But this branch would have been created in the prior step, if i would not have used `--dry-run`. 
It would be nice, if the modification check / onboarding branch check would recognize the `--dry-run` and check if it would have been created prior.

This makes the dry-run check unusable in my pipeline at the moment. :( 

**Relevant debug logs**

```
 INFO: Repository started (repository=REPO)
       "renovateVersion": "22.7.0"
 INFO: DRY-RUN: Would commit files to onboarding branch (repository=REPO)
 INFO: Dependency extraction complete (repository=REPO)
       "baseBranch": "master",
       "stats": {
         "managers": {
           "dockerfile": {"fileCount": 1, "depCount": 1},
           "gitlabci": {"fileCount": 1, "depCount": 2}
         },
         "total": {"fileCount": 2, "depCount": 3}
       }
ERROR: Repository has unknown error (repository=REPO)
       "err": {
         "message": "Cannot check modification for branch that does not exist: renovate/configure",
         "stack": "Error: Cannot check modification for branch that does not exist: renovate/configure\n    at Object.isBranchModified (/usr/src/app/node_modules/renovate/lib/util/git/index.ts:406:11)\n    at Object.ensureOnboardingPr (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/pr/index.ts:69:7)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:40:5)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:66:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:10:22"
       }
 INFO: Repository finished (repository=REPO)
       "durationMs": 6379
```

**To Reproduce**

1. Create a repository and add the renovate bot to it.
2. Run `renovate --dry-run`

### PR DESCRIPTION
**Pull request by pulish**
Closes #6892

### CODE REVIEW

File: lib/workers/repository/onboarding/pr/index.ts [hunk 1]
```diff
@@ -65,7 +65,10 @@ If you need any further assistance then you can also [request help here](${confi
     prBody = prBody.replace('{{PACKAGE FILES}}\n', '');
   }
   let configDesc = '';
-  if (await isBranchModified(config.onboardingBranch)) {
+  // istanbul ignore if
```
Comment (viceice) [inline lib/workers/repository/onboarding/pr/index.ts:68]: Please try to add a test case

Comment (pulish) [reply lib/workers/repository/onboarding/pr/index.ts]: I add test cases for the dry run.

**Review by viceice — APPROVED** [review]
