### PR TITLE
fix(kustomize): lookup Github dependency using HTTP

### LINKED ISSUE #121: git-tags datasource could not create directory '/usr/sbin/.ssh'
I'm experiencing the following ssh related error for git-tags datasource:

```
DEBUG: Datasource unknown error (repository=[redacted]])
       "datasource": "git-tags",
       "lookupName": "git@github.com:[redacted].git",
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "git@github.com:[redacted].git"
           ],
           "format": "utf-8"
         },
         "message": "Could not create directory '/usr/sbin/.ssh'.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
         "stack": "Error: Could not create directory '/usr/sbin/.ssh'.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
```

From the configuration I use, it is coming from the kustomize manager. I'm also using Terraform and the git repo referenced in the Terraform modules are correctly being processed.

The issue is definitely related to SSH and the simple-git package cannot find the key but I couldn't find the exact logic that could trigger such issue. I used the latest version v1.1.0-rc.0 which use `/usr/sbin` as home directory. 

I have the Github private key located at `/usr/src/app/renovate.private-key.pem` (as described in the [documentation](https://github.com/whitesource/renovate-on-prem/blob/9caa45424bc60706fead9fcb66ef1d25ed136df9/docs/configuration-github.md#configure-whitesource-renovate)).

I also tried using renovate cli in an isolated container and experienced similar error.

Any idea?

### LINKED ISSUE #7455: Kustomize require SSH to lookup git@github.com dependencies
**What Renovate type, platform and version are you using?**

Renovate 23.47.2 via CLI in a Docker container without SSH key.

**Describe the bug**

The kustomize manager fail to lookup Github dependency that make use of SSH, for example:

```yaml
bases:
  - git@github.com:moredhel/remote-kustomize.git?ref=v0.0.0
```

[Here](https://github.com/etiennetremel/renovate-kustomize-temp/pull/1) is an example of the on-boarding process for 2 different package file (kustomize and terraform). Renovate fail with kustomize but succeed with Terraform.

**Relevant debug logs**

```
DEBUG: Datasource unknown error (repository=[redacted])
       "datasource": "git-tags",
       "lookupName": "github.com/[redacted]",
       "err": {
         "task": {
           "commands": ["ls-remote", "github.com/[redacted]"],
           "format": "utf-8"
         },
         "message": "fatal: 'github.com/[redacted]' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
         "stack": "Error: fatal: 'github.com/[redacted]' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
```

**To Reproduce**

```bash
$ docker run -ti \
    -e GITHUB_TOKEN=$GITHUB_TOKEN \
    -v $PWD:/app \
    -v renovate.private-key.pem:/usr/src/app/renovate.private-key.pem \
    -w /app \
    node:14 bash
root@d03b97c8e859:/app# yarn start --log-level debug --token $GITHUB_TOKEN etiennetremel/renovate-kustomize-temp
```

**Additional context**

https://github.com/whitesource/renovate-on-prem/issues/121

### PR DESCRIPTION
**Pull request by etiennetremel**
- use github-tags when the base contains github.com
- refactor to make the extractBase function more readable and adjust the regular expression to match git url

close #7455
close https://github.com/whitesource/renovate-on-prem/issues/121

### CODE REVIEW

File: lib/manager/kustomize/extract.ts [hunk 1]
```diff
@@ -18,49 +18,34 @@ interface Kustomize {
...
+  if (match?.groups.path.includes('github.com')) {
     return {
-      datasource: datasourceGitTags.id,
-      depName: root,
-      lookupName: url,
-      currentValue,
+      currentValue: match.groups.currentValue,
+      datasource: datasourceGitHubTags.id,
+      depName: match.groups.project.replace('.git', ''),
+      depType: 'github',
```
Comment (rarkins) [inline lib/manager/kustomize/extract.ts:37]:
```suggestion
```

File: lib/manager/kustomize/extract.ts [hunk 2]
```diff
@@ -18,49 +18,34 @@ interface Kustomize {
...
     };
   }
 
-  return null;
+  return {
+    datasource: datasourceGitTags.id,
+    depName: match.groups.path.replace('.git', ''),
+    depNameShort: match.groups.project.replace('.git', ''),
+    depType: 'gitTags',
```
Comment (rarkins) [inline lib/manager/kustomize/extract.ts:45]:
```suggestion
```

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/manager/kustomize/extract.ts [hunk 3]
```diff
@@ -18,49 +18,32 @@ interface Kustomize {
...
-    const root = basenameVersion.groups.basename;
-
-    const urlResult = extractUrl.exec(root);
-    let url = root;
-    // if a match, then there was a subdir, update
-    if (urlResult && !url.startsWith('http')) {
-      url = urlResult.groups.url;
-    }
-
+  if (match?.groups.path.includes('github.com')) {
```
Comment (JamieMagee) [inline lib/manager/kustomize/extract.ts:32]:
```suggestion
  if (match?.groups.path.startsWith('github.com')) {
```

This should fix the CodeQL alert

File: lib/manager/kustomize/__snapshots__/extract.spec.ts.snap [hunk 4]
```diff
@@ -22,14 +20,16 @@ Array [
   Object {
     "currentValue": "v0.0.1",
     "datasource": "git-tags",
-    "depName": "https://moredhel/remote-kustomize.git",
```
Comment (rarkins) [inline lib/manager/kustomize/__snapshots__/extract.spec.ts.snap:25]: This one is a little confusing because `https://moredhel/` is a strange host to begin with. But if this is a `git-tags` resource, would it expect the protocol prefix and `.git` suffix or not?

Comment (etiennetremel) [reply lib/manager/kustomize/__snapshots__/extract.spec.ts.snap:25]: If you look at the [git-fetch manual](https://git-scm.com/docs/git-fetch#_git_urls), `.git` is always defined.
Isn't git-tags executing `git ls-remote` using the `lookupName` key?

Comment (viceice) [reply lib/manager/kustomize/__snapshots__/extract.spec.ts.snap:25]: It's falling back to `depName` if `lookupName` is undefined. So `depName` is mandatory.

Comment (etiennetremel) [reply lib/manager/kustomize/__snapshots__/extract.spec.ts.snap:25]: ok, in this case we always define lookupName for dependency of type git-tags. So that should be fine to keep depName as it is?

Comment (viceice) [reply lib/manager/kustomize/__snapshots__/extract.spec.ts.snap:25]: That would probably ok even if the test snapshots looking strange for now. We can fix that later.

Comment (etiennetremel) [reply lib/manager/kustomize/__snapshots__/extract.spec.ts.snap:25]: I agree, some of these tests are a bit confusing and I can definitely see some duplication of the logic.

I could probably simplify the whole thing and merge all these fixtures into 2 files (one empty, and one with all the variation of dependencies like https, ssh, etc.). What do you think? If you have manager in mind which can be use as model let me know.

Comment (viceice) [reply lib/manager/kustomize/__snapshots__/extract.spec.ts.snap:25]: Sure, but the refactoring should be done in a seperate pr.

This pr needs at least one more test to get back  100% code coverage.

**Review by viceice — COMMENTED** [review]
LGTM, have you done some real repo tests?

**Comment by etiennetremel** [comment]
> LGTM, have you done some real repo tests?

Yes, you can see a list of open PR here: https://github.com/etiennetremel/renovate-kustomize-temp/pulls

Test were executed from this PR using:
```bash
$ yarn start --log-level debug --token $GITHUB_TOKEN  etiennetremel/renovate-kustomize-temp
```

**Review by viceice — APPROVED** [review]
