### PR TITLE
fix(azure): use target branch to select platform automerge strategy

### LINKED ISSUE #21639: Azure platform automerge selects a merge strategy for a different target branch
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.55.1

### If you're self-hosting Renovate, select which platform you are using.

Azure DevOps (dev.azure.com)

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

When [populating `config.defaultMergeMethod`](https://github.com/renovatebot/renovate/blob/main/lib/modules/platform/azure/index.ts#L206-L212), the Azure platform module fetches all policy configurations from the project.  Because it passes a null `branchRef` parameter to `getMergeMethod`, `isRelevantScope` returns every policy matching the current repository regardless of target branch.  getMergeMethod then [picks the first one](https://github.com/renovatebot/renovate/blob/main/lib/modules/platform/azure/azure-helper.ts#L150), which in our case is not the main branch of the repository.  I'm not sure why this is or how to cause Azure DevOps to behave this way for a reproduction, but I believe I have identified a resolution.

When creating the PR, the Azure platform module then [blindly applies the default merge method](https://github.com/renovatebot/renovate/blob/main/lib/modules/platform/azure/index.ts#L457-L474), which in our case is not valid for the default branch.

I believe this could be simply fixed by borrowing the [merge method lookup code](https://github.com/renovatebot/renovate/blob/main/lib/modules/platform/azure/index.ts#L686-L693) from `mergePr` in the same module.  As the PR is created before autocomplete is applied, the targetRefName will be populated.

### Relevant debug logs

```
DEBUG: ProjectName/RepoName default branch = develop (repository=ProjectName/RepoName)
TRACE: getProjectAndRepo(ProjectName/RepoName) (repository=ProjectName/RepoName)
TRACE: getMergeMethod(01234567-89ab-cdef-0123-456789abcdef, ProjectName, null) determining mergeMethod from matched policy:
       {
           "allowRebase": true,
           "allowRebaseMerge": true,
           "scope": [
               {
                   "refName": "refs/heads/release",
                   "matchKind": "Prefix",
                   "repositoryId": "01234567-89ab-cdef-0123-456789abcdef"
               }
           ]
       } (repository=ProjectName/RepoName)
```
In our case. policy attached to develop does not permit rebases, and instead is as follows:
```
{
    "allowSquash": true,
    "allowRebaseMerge": true,
    "scope": [
        {
            "refName": "refs/heads/develop",
            "matchKind": "Exact",
            "repositoryId": "01234567-89ab-cdef-0123-456789abcdef"
        }
    ]
}
```
### Have you created a minimal reproduction repository?

~~I have explained in the description why a minimal reproduction is impossible~~

I have been able to reproduce this at https://dev.azure.com/chrisvanderpennen/public/_git/renovate-21639-repro

### PR DESCRIPTION
**Pull request by chrisvanderpennen**
## Changes
The Azure platform module now uses the target branch to select an appropriate completion strategy when enabling platform autocomplete.

## Context
- Closes #21639

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on [a real repository](https://dev.azure.com/chrisvanderpennen/public/_git/renovate-21639-lab)

### CODE REVIEW

File: lib/modules/platform/azure/index.ts [hunk 1]
```diff
@@ -427,6 +417,21 @@ export async function getBranchStatus(
...
+  targetRefName: string
+): Promise<GitPullRequestMergeStrategy> {
+  // TODO #7154
+  return (
+    config.mergeMethods[targetRefName] ??
+    (config.mergeMethods[targetRefName] = await azureHelper.getMergeMethod(
+      config.repoId,
+      config.project,
+      targetRefName,
+      config.defaultBranch
```
Comment (viceice) [inline lib/modules/platform/azure/index.ts:430]: what if base branches are in use? is this the target branch to merge against? we probably need to pass the base branch here.

Comment (chrisvanderpennen) [reply lib/modules/platform/azure/index.ts:430]: `targetRefName` is the target of the already-created PR.  By the time this is called, Renovate is either updating a PR it just created to enable platform autocomplete, or it's merging it.

This unifies the logic in both cases - previously when enabling platform autocomplete it was possible to select an invalid strategy depending on the order the DevOps API returns its policy list.

Comment (viceice) [reply lib/modules/platform/azure/index.ts:430]: but why do we pass the default branch? for what it is used?

Comment (chrisvanderpennen) [reply lib/modules/platform/azure/index.ts:430]: There is (apparently, I've never seen one in the wild) a way to make a DevOps policy targeting the default branch of a repo instead of a prefix or exact ref, and my read of `isRelevantScope` in azure-helper suggests that it needs to be passed the default branch name of that repo in order to correctly match against such a policy: https://github.com/renovatebot/renovate/blob/7f4c8ebeb919091b4773c177fa30f96873c6ac95/lib/modules/platform/azure/azure-helper.ts#L123-L141

Comment (chrisvanderpennen) [reply lib/modules/platform/azure/index.ts:430]: I've worked out how to create a default branch policy - they apply to the default branch of every repository in a project, and have `null` as their `refName`.  An example from the API response on my test repo:
```json
"settings": {
    "allowSquash": true,
    "allowRebase": true,
    "allowRebaseMerge": true,
    "scope": [
        {
            "refName": null,
            "matchKind": "DefaultBranch",
            "repositoryId": null
        }
    ]
},
```
So the function in azure-helper.ts does need to know the default branch name of the repository being worked on in order to check if there is a relevant policy.

File: lib/modules/platform/azure/index.spec.ts [hunk 2]
```diff
@@ -730,47 +730,129 @@ describe('modules/platform/azure/index', () => {
...
+              deleteSourceBranch: true,
+              mergeCommitMessage: 'The Second Title',
+            },
+          },
+        ];
+        const updateFn = jest
+          .fn(() => prUpdateResults.shift())
+          .mockName('updatePullRequest');
+
+        azureHelper.getMergeMethod = jest
```
[the remark this answers is not in the document]
Comment (chrisvanderpennen) [reply lib/modules/platform/azure/index.spec.ts:823]: sure, would you like me to update the other tests in this file as well?

[the remark this answers is not in the document]
Comment (chrisvanderpennen) [reply lib/modules/platform/azure/index.spec.ts:823]: actually, azureHelper is a mocked import so would this be better?
```
azureHelper.getMergeMethod.mockReturnValue(
  Promise.resolve(GitPullRequestMergeStrategy.Squash)
);
```

[the remark this answers is not in the document]
Comment (viceice) [reply lib/modules/platform/azure/index.spec.ts:823]: yes, but only changed tests. 🤗

**Review by JamieMagee — DISMISSED** [review]

File: lib/modules/platform/azure/index.spec.ts [hunk 3]
```diff
@@ -820,9 +820,9 @@ describe('modules/platform/azure/index', () => {
           .fn(() => prUpdateResults.shift())
           .mockName('updatePullRequest');
 
-        azureHelper.getMergeMethod = jest
-          .fn()
-          .mockReturnValue(GitPullRequestMergeStrategy.Squash);
+        azureHelper.getMergeMethod.mockReturnValue(
```
Comment (JamieMagee) [inline lib/modules/platform/azure/index.spec.ts:823]: You can use `mockResolvedValueOnce` instead of having to create a new `Promise` here
```suggestion
    azureHelper.getMergeMethod.mockResolvedValueOnce(
```

File: lib/modules/platform/azure/index.spec.ts [hunk 4]
```diff
@@ -730,47 +730,129 @@ describe('modules/platform/azure/index', () => {
...
+        const updateFn = jest
+          .fn(() => prUpdateResult)
+          .mockName('updatePullRequest');
+        azureApi.gitApi.mockImplementationOnce(
+          () =>
+            ({
+              createPullRequest: jest.fn(() => prResult),
+              createPullRequestLabel: jest.fn(() => ({})),
+              updatePullRequest: updateFn,
+            } as any)
```
Comment (viceice) [inline lib/modules/platform/azure/index.spec.ts:763]: i would also see to use our `partial<T>` helper to have more type safety

Comment (chrisvanderpennen) [reply lib/modules/platform/azure/index.spec.ts:763]: good call, this picked up some type errors

File: lib/modules/platform/azure/index.spec.ts [hunk 5]
```diff
@@ -730,47 +730,130 @@ describe('modules/platform/azure/index', () => {
...
+          completionOptions: {
+            squashMerge: true,
+            deleteSourceBranch: true,
+            mergeCommitMessage: 'The Title',
+          },
+        };
+        const updateFn = jest
+          .fn()
+          .mockResolvedValue(prUpdateResult)
+          .mockName('updatePullRequest');
```
Comment (viceice) [inline lib/modules/platform/azure/index.spec.ts:757]: remove this, we don't need or use it.

File: lib/modules/platform/azure/__snapshots__/index.spec.ts.snap [hunk 6]
```diff
@@ -30,10 +30,10 @@ exports[`modules/platform/azure/index createPr() should create and return a PR o
 }
 `;
 
-exports[`modules/platform/azure/index createPr() should create and return a PR object with auto-complete set 1`] = `
+exports[`modules/platform/azure/index createPr() when usePlatformAutomerge is set should create and return a PR object with auto-complete set 1`] = `
 {
   "autoCompleteSetBy": {
-    "id": 123,
+    "id": "123",
```
Comment (viceice) [inline lib/modules/platform/azure/__snapshots__/index.spec.ts.snap:36]: why does this change?

File: lib/modules/platform/azure/index.spec.ts [hunk 7]
```diff
@@ -730,47 +730,130 @@ describe('modules/platform/azure/index', () => {
...
+            completionOptions: {
+              squashMerge: true,
+              deleteSourceBranch: true,
+              mergeCommitMessage: 'The Second Title',
+            },
+          },
+        ];
+        const updateFn = jest
+          .fn(() => Promise.resolve(prUpdateResults.shift()!))
+          .mockName('updatePullRequest');
```
Comment (viceice) [inline lib/modules/platform/azure/index.spec.ts:821]: same here

**Review by viceice — COMMENTED** [review]
last round 🤗

File: lib/modules/platform/azure/__snapshots__/index.spec.ts.snap (hunk 6 above)
Comment (chrisvanderpennen) [reply lib/modules/platform/azure/__snapshots__/index.spec.ts.snap:36]: The response object from `azureApi.gitApi.updatePullRequest` is spread onto the return value from `azure.createPr`.  `id` is `string` on both `createdBy` and `autoCompleteSetBy`, which was revealed as a type error once I converted these tests to `partial<IGitApi>`.  It's not actually declared on the interface `createPr` returns, but it did affect the snapshot.

**Review by viceice — APPROVED** [review]

**Review by JamieMagee — APPROVED** [review]
