### PR TITLE
fix(npm): update npmrc before executing corepack cmd

### LINKED ISSUE #32116: Updates to the `packageManager` digest fail on project with private dependencies
### Discussed in https://github.com/renovatebot/renovate/discussions/32098

<div type='discussions-op-text'>

<sup>Originally posted by **wtrep** October 22, 2024</sup>
### How are you running Renovate?

A Mend.io-hosted app

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

_No response_

### Please tell us more about your question or problem

Updates to the `packageManager` digest fails on projects with private dependencies.

Reproduction: [corepack-private-repo-npmrc-reproduction](https://github.com/wtrep/corepack-private-repo-npmrc-reproduction).

We can see that renovate will run `corepack use pnpm@9.12.2` to update the pnpm digest. The command fails because it is executed before the `.npmrc` file is generated.

This is not an issue with the `.npmrc` file as updates to private dependencies are working as expected (see [Update dependency @private/dependency to v1.0.1](https://github.com/wtrep/corepack-private-repo-npmrc-reproduction/pull/2)).

### Logs (if relevant)

<details><summary>Logs</summary>

```
DEBUG: Executing command (branch="renovate/pnpm-9.x")
{
  "command": "corepack use pnpm@9.12.2"
}

DEBUG: rawExec err (branch="renovate/pnpm-9.x")
{
  "err": {
    "cmd": "/bin/sh -c corepack use pnpm@9.12.2",
    "stderr": "",
    "stdout": "Installing pnpm@9.12.2 in the project...\n\nLockfile is up to date, resolution step is skipped\nProgress: resolved 1, reused 0, downloaded 0, added 0\nPackages: +1\n+\n ERR_PNPM_FETCH_404  GET https://**redacted**@private/dependency/-/dependency-1.0.0.tgz: Not Found - 404\n\nNo authorization header was set for the request.\n",
    "options": {
      "cwd": "/tmp/renovate/repos/github/wtrep/corepack-private-repo-npmrc-reproduction",
      "encoding": "utf-8",
      "env": {
        "HOME": "/home/ubuntu",
        "PATH": "/home/ubuntu/.local/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "LC_ALL": "C.UTF-8",
        "LANG": "C.UTF-8",
        "CONTAINERBASE_CACHE_DIR": "/tmp/renovate/cache/containerbase"
      },
      "maxBuffer": 10485760,
      "timeout": 900000
    },
    "exitCode": 1,
    "name": "ExecError",
    "message": "Command failed: corepack use pnpm@9.12.2\n",
    "stack": "ExecError: Command failed: corepack use pnpm@9.12.2\n\n    at ChildProcess.<anonymous> (/usr/local/renovate/lib/util/exec/common.ts:101:11)\n    at ChildProcess.emit (node:events:531:35)\n    at ChildProcess.emit (node:domain:488:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)"
  }
  "durationMs": 1738
}

WARN: Error updating package.json (branch="renovate/pnpm-9.x")
{
  "err": {
    "cmd": "/bin/sh -c corepack use pnpm@9.12.2",
    "stderr": "",
    "stdout": "Installing pnpm@9.12.2 in the project...\n\nLockfile is up to date, resolution step is skipped\nProgress: resolved 1, reused 0, downloaded 0, added 0\nPackages: +1\n+\n ERR_PNPM_FETCH_404  GET https://**redacted**@private/dependency/-/dependency-1.0.0.tgz: Not Found - 404\n\nNo authorization header was set for the request.\n",
    "options": {
      "cwd": "/tmp/renovate/repos/github/wtrep/corepack-private-repo-npmrc-reproduction",
      "encoding": "utf-8",
      "env": {
        "HOME": "/home/ubuntu",
        "PATH": "/home/ubuntu/.local/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "LC_ALL": "C.UTF-8",
        "LANG": "C.UTF-8",
        "CONTAINERBASE_CACHE_DIR": "/tmp/renovate/cache/containerbase"
      },
      "maxBuffer": 10485760,
      "timeout": 900000
    },
    "exitCode": 1,
    "name": "ExecError",
    "message": "Command failed: corepack use pnpm@9.12.2\n",
    "stack": "ExecError: Command failed: corepack use pnpm@9.12.2\n\n    at ChildProcess.<anonymous> (/usr/local/renovate/lib/util/exec/common.ts:101:11)\n    at ChildProcess.emit (node:events:531:35)\n    at ChildProcess.emit (node:domain:488:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)"
  }
}

DEBUG: Updated 1 package files (branch="renovate/pnpm-9.x")
DEBUG: Getting updated lock files (branch="renovate/pnpm-9.x")
DEBUG: Writing package.json files (branch="renovate/pnpm-9.x")
{
  "packageFiles": [
    "package.json"
  ]
}

DEBUG: Writing any updated package files (branch="renovate/pnpm-9.x")
DEBUG: Writing package.json (branch="renovate/pnpm-9.x")
DEBUG: Found 1 npm host rule(s) (branch="renovate/pnpm-9.x")
DEBUG: Adding npmrc entry for //**redacted** with key _authToken (branch="renovate/pnpm-9.x")
DEBUG: npmrc file .npmrc found in repository (branch="renovate/pnpm-9.x")
DEBUG: Writing updated .npmrc file to .npmrc (branch="renovate/pnpm-9.x")
```

</details>
</div>

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
Update npmrc before executing corepack command so that it uses correct registry & token to fetch dep info

## Context
- Closes: https://github.com/renovatebot/renovate/issues/32116

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository https://github.com/Rahul-renovate-testing/repro-32116/pulls

### CODE REVIEW

File: lib/modules/manager/npm/artifacts.ts [hunk 1]
```diff
@@ -43,6 +49,9 @@ export async function updateArtifacts({
   // Asumming that corepack only needs to modify the package.json file in the root folder
   // As it should not be regular practice to have different package managers in different workspaces
   const pkgFileDir = upath.dirname(packageFileName);
+  const { additionalNpmrcContent } = processHostRules();
+  const npmrcContent = await getNpmrcContent(pkgFileDir);
+  await updateNpmrcContent(pkgFileDir, npmrcContent, additionalNpmrcContent);
```
Comment (viceice) [inline lib/modules/manager/npm/artifacts.ts:54]: shouldn't this be right before the exec call instead? so it doesn't collide with other reads below?

Comment (RahulGautamSingh) [reply lib/modules/manager/npm/artifacts.ts:54]: Diff filenames so it shouldn't collide

Comment (viceice) [reply lib/modules/manager/npm/artifacts.ts:54]: not yet, but probably later.

**Review by viceice — APPROVED** [review]
