### PR TITLE
fix(maven): Use fallback maven registry

### LINKED ISSUE #5609: "No repositories defined for.." warnings
**What Renovate type are you using?**

Log messages come from the hosted app

**Describe the bug**

**Did you see anything helpful in debug logs?**

Lots like this:

```
    "msg": "No repositories defined for org.jetbrains.kotlin:kotlin-stdlib",
```

**To Reproduce**

Fork https://github.com/adrw/misk-web and run Renovate against it

### PR DESCRIPTION
**Pull request by zharinov**
Closes #5609

### CODE REVIEW

File: lib/datasource/maven/common.ts [hunk 1]
```diff
@@ -1 +1,5 @@
 export const id = 'maven';
+
+export const MAVEN_REPO = 'https://repo.maven.apache.org/maven2';
+export const MAVEN_REPO_DEPRECATED = 'https://central.maven.org/maven2';
+export const CLOJARS_REPO = 'https://clojars.org/repo';
```
Comment (viceice) [inline lib/datasource/maven/common.ts]: `https://repo.clojars.org`? See https://clojars.org/.

Shouldn't this be moved to `deps-edn`, because it's only used there?

Comment (zharinov) [reply lib/datasource/maven/common.ts]: Not only, it's also used with`leiningen`

Comment (rarkins) [reply lib/datasource/maven/common.ts]: Could we simplify any logic by splitting the maven datasource into multiple?

Comment (zharinov) [reply lib/datasource/maven/common.ts]: Don't think so, `sbt` already is separate, but clojure differs only with additional `registryUrl`

**Comment by rarkins** [comment]
What’s the level of risk of this PR? Eg Needs any more testing? Should be watched closely after merge? Etc

**Comment by zharinov** [comment]
For gradle it can lead to more traffic with Maven central repo (for cases when it currently logs `warn` and null result). Also there is some probability of new errors, but other JVM-based managers should perform as usual.
