### PR TITLE
fix(platform): handle unexpected github-graphql error

### LINKED ISSUE #21861: Handle rate limit exceeded response for github.initRepo
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

The initRepo GraphQL query can return this result:

```json
{
  "level": 20,
  "res": {
    "errors": [
      {
        "type": "RATE_LIMITED",
        "message": "API rate limit exceeded for installation ID 9306189."
      }
    ]
  },
  "msg": "No repository returned",
  "time": "2023-04-27T19:58:46.771Z"
}
```

It should throw a more appropriate error than "repo not found"

### Relevant debug logs

See above

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
There are some graphQL errors that are returned with a 200 status code, eg. RATE_LIMITED. There isn't any official documentation for these errors so we can't be sure if it happens only for `rate-limited` or not. Therefore, I have added a new error-constant `PLATFORM_UNKNOWN_ERROR` for such errors. 

## Context
- Closes: https://github.com/renovatebot/renovate/issues/21861

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/constants/error-messages.ts [hunk 1]
```diff
@@ -9,6 +9,7 @@ export const PLATFORM_GPG_FAILED = 'gpg-failed';
 export const PLATFORM_INTEGRATION_UNAUTHORIZED = 'integration-unauthorized';
 export const PLATFORM_NOT_FOUND = 'platform-not-found';
 export const PLATFORM_RATE_LIMIT_EXCEEDED = 'rate-limit-exceeded';
+export const PLATFORM_UNKOWN_ERROR = 'rate-limit-exceeded';
```
Comment (rarkins) [inline lib/constants/error-messages.ts:12]:
```suggestion
export const PLATFORM_UNKNOWN_ERROR = 'platform-unknown-error';
```

File: lib/modules/platform/github/index.spec.ts [hunk 2]
```diff
@@ -3,6 +3,7 @@ import * as httpMock from '../../../../test/http-mock';
 import { logger, mocked, partial } from '../../../../test/util';
 import { GlobalConfig } from '../../../config/global';
 import {
+  PLATFORM_UNKOWN_ERROR,
```
Comment (rarkins) [inline lib/modules/platform/github/index.spec.ts:6]:
```suggestion
  PLATFORM_UNKNOWN_ERROR,
```

File: lib/modules/platform/github/index.spec.ts [hunk 3]
```diff
@@ -542,6 +543,23 @@ describe('modules/platform/github/index', () => {
...
+          errors: [
+            {
+              type: 'RATE_LIMITED',
+              message: 'API rate limit exceeded for installation ID XXXXXXX.',
+            },
+          ],
+        });
+      await expect(
+        github.initRepo({ repository: 'some/repo' })
+      ).rejects.toThrow(PLATFORM_UNKOWN_ERROR);
```
Comment (rarkins) [inline lib/modules/platform/github/index.spec.ts:560]: I would prefer you return the rate limited error when you _know_ that's what it is, and the unknown error only when there's an unknown response

File: lib/modules/platform/github/index.ts [hunk 4]
```diff
@@ -394,6 +395,12 @@ export async function initRepo({
         name: config.repositoryName,
       },
     });
+
+    if (res?.errors) {
+      logger.debug({ res }, 'Unexpected Graph QL errors');
+      throw new Error(PLATFORM_UNKOWN_ERROR);
+    }
```
Comment (rarkins) [inline lib/modules/platform/github/index.ts:402]: Throw rate limited if it's got the rate limited string, otherwise throw unknown

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by rarkins — APPROVED** [review]
