### PR TITLE
fix(platform/github): detect pr-edited if target changed

### LINKED ISSUE #20915: platform(github): unable to detect edited pr target branch
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate is unable to detect that a pr is edited, when user manually changes the `targetBranch` of the update PR

This happens because the `targetBranch` isn't part of `getBranchPr` result for `github`due to the [coerce ](https://github.com/renovatebot/renovate/blob/39caa803157de4d1ec245d7c1aa5663bcf073639/lib/modules/platform/github/common.ts#L10)function not including it.(Not sure why?)
Thus `targetBranch=undefined` and the following code can't detect if user edited the target branch
https://github.com/renovatebot/renovate/blob/39caa803157de4d1ec245d7c1aa5663bcf073639/lib/workers/repository/update/branch/index.ts#L201-L205

I think this bug was introduced after this [merge](https://github.com/renovatebot/renovate/pull/14907/files#diff-02818e53b112f2984e86a70880277589bd4f84b1b6ac5f0af2343cf97dd30b7d)

Reproduction: https://github.com/RahulGautamSingh-testing/nvmrc-matching/pull/2

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have read the minimal reproductions documentation and linked to such a repository in the bug description

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- Add `targetBranch` to the list of returned fields after the PR info is coerced

## Context
- Closes: https://github.com/renovatebot/renovate/issues/20915

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/platform/github/common.ts [hunk 1]
```diff
@@ -50,6 +50,10 @@ export function coerceRestPr(pr: GhRestPr): GhPr {
     result.closedAt = pr.closed_at;
   }
 
+  if (pr.base) {
```
Comment (rarkins) [inline lib/modules/platform/github/common.ts:53]:
```suggestion
  if (pr.base?.ref) {
```

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by rarkins — DISMISSED** [review]

**Review by viceice — DISMISSED** [review]

**Comment by RahulGautamSingh** [comment]
@viceice  Sorry I had to make a change to the test. The test was working but it was testing a different case than intended.

**Review by viceice — APPROVED** [review]
