### PR TITLE
fix(presets): Handle MUI (previously: Material-UI) organization change in material-ui monorepo

### LINKED ISSUE #14241: React material-ui monorepo preset stopped working
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

27.25.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.7.2

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Renovate used to assemble merge requests for material ui monorepo automatically. This stopped working as per the screenshot below

Screenshot_20220215-200408_Chrome

Maybe they did rename something? I know they changed their organization name recently... 

Thx guys! 

Cheers, 
David 

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by ddolcimascolo**
Fixes #14241

## Changes:

This handles the new organization name of MUI (previously Material-UI) in the corresponding monorepo preset

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/config/presets/internal/monorepo.ts [hunk 1]
```diff
@@ -129,7 +129,10 @@ const repoGroups = {
   'material-components-web':
     'https://github.com/material-components/material-components-web',
   mdx: 'https://github.com/mdx-js/mdx',
-  'material-ui': 'https://github.com/mui-org/material-ui',
+  'material-ui': [
+    'https://github.com/mui-org/material-ui', // Previous organization name (see: https://github.com/mui/material-ui/pull/30944)
```
Comment (HonkingGoose) [inline lib/config/presets/internal/monorepo.ts:133]: @viceice It sounds like it would be good to add a `replacement` preset for the rename as well?

https://docs.renovatebot.com/presets-replacements/

**Comment by HonkingGoose** [comment]
@ddolcimascolo Can you edit your PR body text so it has `Fixes #14241` in it? That way the linked issue gets closed once we merge the PR. 😉

**Comment by ddolcimascolo** [comment]
> @ddolcimascolo Can you edit your PR body text so it has `Fixes #14241` in it? That way the linked issue gets closed once we merge the PR. wink

Done

File: lib/config/presets/internal/monorepo.ts (hunk 1 above)
Comment (HonkingGoose) [reply lib/config/presets/internal/monorepo.ts:133]: MUI has a [blog post that explains the rename](https://mui.com/blog/material-ui-is-now-mui/).

Comment (viceice) [reply lib/config/presets/internal/monorepo.ts:133]: @HonkingGoose let's do it in separate PR, please open a new feature request for it.

**Review by viceice — APPROVED** [review]

File: lib/config/presets/internal/monorepo.ts (hunk 1 above)
Comment (HonkingGoose) [reply lib/config/presets/internal/monorepo.ts:133]: See issue #14254. 😉

Comment (ddolcimascolo) [reply lib/config/presets/internal/monorepo.ts:133]: Thx @HonkingGoose

**Comment by ddolcimascolo** [comment]
Thx for the review
