### PR TITLE
fix(instrumentation): ensure instrumentation is initialised first

### LINKED ISSUE #42470: OpenTelemetry instrumentation does not fully instrument since 43.93.0
Changes in https://github.com/renovatebot/renovate/pull/42183 inadvertently led to a change in ordering of loading configuration (and our HTTP client, when `getOptions()` is called) which means that the instrumentation is initialised too late to then instrument HTTP calls (and may affect other instrumentation)

### PR DESCRIPTION
**Pull request by viceice**
## Changes

- regression of #42183

## Context

Please select one of the following:

- [x] This closes an existing Issue, Closes: # 
- [ ] This doesn't close an Issue, but I accept the risk that this PR may be closed if maintainers disagree with its opening or implementation

## AI assistance disclosure

Did you use AI tools to create any part of this pull request?

Please select one option and, if yes, briefly describe how AI was used (e.g., code, tests, docs) and which tool(s) you used.

- [ ] No — I did not use AI for this contribution.
- [x] Yes — minimal assistance (e.g., IDE autocomplete, small code completions, grammar fixes).
- [ ] Yes — substantive assistance (AI-generated non‑trivial portions of code, tests, or documentation).
- [ ] Yes — other (please describe):

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests, but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

The public repository: <URL>

### CODE REVIEW

File: lib/renovate.ts [hunk 1]
```diff
@@ -4,18 +4,19 @@ import 'source-map-support/register.js';
 import './punycode.cjs';
 
 void (async (): Promise<void> => {
+  // Don't add code before this!
+  // This has to be imported before logger and other libraries which are instrumentalised.
```
Comment (jamietanna) [inline lib/renovate.ts]:
```suggestion
  // This has to be imported before logger and other libraries which are instrumented.
```

File: lib/renovate.ts [hunk 2]
```diff
@@ -4,18 +4,19 @@ import 'source-map-support/register.js';
 import './punycode.cjs';
 
 void (async (): Promise<void> => {
+  // Don't add code before this!
```
Comment (jamietanna) [inline lib/renovate.ts]:
```suggestion
  // ⚠️ Don't add code before this!
```

**Review by jamietanna — APPROVED** [review]
Running locally, I can now see HTTP spans 👍
