### PR TITLE
fix: call every `postUpgradeTasks` in the branch

### LINKED ISSUE #7729: `postUpgradeTasks` are not executed in a multi-dependency branch
**What Renovate type, platform and version are you using?**

Self-hosted Renovate on GitLab

**Describe the bug**

I'd like to execute some `postUpgradeTasks` on a dependency in `group` presets. Currently, it does not work.

**Relevant debug logs**

The log from these lines output empty tasks.

https://github.com/renovatebot/renovate/blob/276a01fdd743d270fd2662cabb3b0e1e465aec83/lib/workers/branch/index.ts#L345-L351

**To Reproduce**

https://github.com/sarunint/ng-v10-minimal

**Additional context**

I've debug Renovate's code and I found out that these lines cause the problem.

https://github.com/renovatebot/renovate/blob/276a01fdd743d270fd2662cabb3b0e1e465aec83/lib/workers/repository/updates/generate.ts#L289-L310

Because the `generateBranchConfig` function uses the first dependency's configuration, the `processBranch` function only execute its first dependency's `postUpgradeTasks`, denoted here.

https://github.com/renovatebot/renovate/blob/276a01fdd743d270fd2662cabb3b0e1e465aec83/lib/workers/branch/index.ts#L345-L351

### PR DESCRIPTION
**Pull request by sarunint**
## Changes:

This PR ensures that the `postUpgradeTasks` in every dependencies in the branch is run.

## Context:

Closes #7729

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [x] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by JamieMagee** [comment]
Can you share the sample repository you ran your changes against? Does is work against the sample repository you shared in the issue: https://github.com/sarunint/ng-v10-minimal?

Also, the diff for this change looks gnarly, but it's quite a minor change. I checked out your branch locally, and my git diff looks _a lot_ better.

**Review by rarkins — COMMENTED** [review]
> Also, the diff for this change looks gnarly, but it's quite a minor change. I checked out your branch locally, and my git diff looks _a lot_ better.

Mostly white-space change?

**Comment by sarunint** [comment]
> Can you share the sample repository you ran your changes against? Does is work against the sample repository you shared in the issue: https://github.com/sarunint/ng-v10-minimal?

@JamieMagee Yes

File: lib/workers/branch/index.ts [hunk 1]
```diff
@@ -342,92 +342,108 @@ export async function processBranch(
...
-        {
-          tasks: config.postUpgradeTasks,
-          allowedCommands: config.allowedPostUpgradeCommands,
-        },
-        'Checking for post-upgrade tasks'
-      );
-      const commands = config.postUpgradeTasks.commands || [];
-      const fileFilters = config.postUpgradeTasks.fileFilters || [];
+      for (const upgrade of config.upgrades) {
+        logger.debug(
```
[the remark this answers is not in the document]
Comment (sarunint) [reply lib/workers/branch/index.ts:346]: I agree. I think I'll trace this statement and add the depName to line 391 instead.

[the remark this answers is not in the document]
Comment (sarunint) [reply lib/workers/branch/index.ts]: EDIT: I added the depName to logger's meta instead.

**Comment by JamieMagee** [comment]
@sarunint Can you open a PR in that repo? your changes look fine, but showing a PR would increase the confidence in this change.

**Review by JamieMagee — DISMISSED** [review]

**Comment by sarunint** [comment]
@JamieMagee Please do not merge yet. I found a potential bug while testing by hand.

**Comment by sarunint** [comment]
@JamieMagee here it is: https://github.com/sarunint/ng-v10-minimal/pull/2

Turns out, there are no bugs! It is my poor `renovate.json` configuration file.

File: lib/workers/branch/index.ts [hunk 2]
```diff
@@ -342,97 +342,115 @@ export async function processBranch(
...
-        {
-          tasks: config.postUpgradeTasks,
-          allowedCommands: config.allowedPostUpgradeCommands,
-        },
-        'Checking for post-upgrade tasks'
-      );
-      const commands = config.postUpgradeTasks.commands || [];
-      const fileFilters = config.postUpgradeTasks.fileFilters || [];
+      for (const upgrade of config.upgrades) {
+        addMeta({ dep: upgrade.depName });
```
Comment (rarkins) [inline lib/workers/branch/index.ts:346]:
```suggestion
```

It's not necessary to include this if you're adding `dep` in the `logger.trace` command anyway.

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/workers/branch/index.ts (hunk 2 above)
Comment (sarunint) [reply lib/workers/branch/index.ts:346]: That's for `logger.debug` down below. (Line 380, 392, 398, 436)

Comment (rarkins) [reply lib/workers/branch/index.ts:346]: In that case, can you remove the explicit `dep` from any `logger` commands, as there's no reason to duplicate them

File: lib/workers/branch/index.ts [hunk 3]
```diff
@@ -342,97 +342,115 @@ export async function processBranch(
...
+              if (minimatch(relativePath, pattern)) {
+                logger.debug(
+                  { file: relativePath, pattern },
+                  'Post-upgrade file saved'
+                );
+                const existingContent = await readLocalFile(relativePath);
+                const existingUpdatedArtifacts = config.updatedArtifacts.find(
+                  (ua) => ua.name === relativePath
+                );
+                if (!existingUpdatedArtifacts) {
```
Comment (rarkins) [inline lib/workers/branch/index.ts:418]:
```suggestion
                if (existingUpdatedArtifacts) {
```

Please flip around this if/else so that there's no negation here

File: lib/workers/branch/index.ts [hunk 4]
```diff
@@ -342,97 +342,115 @@ export async function processBranch(
...
+                  config.updatedArtifacts.push({
+                    name: relativePath,
+                    contents: existingContent,
+                  });
+                } else {
+                  existingUpdatedArtifacts.contents = existingContent;
+                }
+                config.updatedArtifacts = config.updatedArtifacts.filter(
+                  (ua) => ua.name !== '|delete|' || ua.contents !== relativePath
+                );
```
Comment (rarkins) [inline lib/workers/branch/index.ts:428]: Can you comment the code so that it's clear why this filter is required?

File: lib/workers/branch/index.ts [hunk 5]
```diff
@@ -342,97 +342,115 @@ export async function processBranch(
...
+                  { file: relativePath, pattern },
+                  'Post-upgrade file removed'
+                );
+                config.updatedArtifacts.push({
+                  name: '|delete|',
+                  contents: relativePath,
+                });
+                config.updatedArtifacts = config.updatedArtifacts.filter(
+                  (ua) => ua.name !== relativePath
+                );
```
Comment (rarkins) [inline lib/workers/branch/index.ts:446]: Also explain or comment the reason for this

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by rarkins — APPROVED** [review]
