### PR TITLE
fix(gradle): Avoid crash for missing managerData

### LINKED ISSUE #11723: TypeError: Cannot read property 'packageFile' of undefined
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Describe the bug

Error occurs during Gradle extract, reproduced here: https://github.com/renovate-tests/escapade

### Relevant debug logs

<details><summary>Logs</summary>

```
ERROR: Repository has unknown error (repository=renovate-tests/escapade)
       "err": {
         "message": "Cannot read property 'packageFile' of undefined",
         "stack": "TypeError: Cannot read property 'packageFile' of undefined\n    at /Users/rhys/src/renovatebot/renovate/lib/manager/gradle/shallow/extract.ts:101:33\n    at Array.forEach (<anonymous>)\n    at Object.extractAllPackageFiles (/Users/rhys/src/renovatebot/renovate/lib/manager/gradle/shallow/extract.ts:100:50)\n    at async extractAllPackageFiles (/Users/rhys/src/renovatebot/renovate/lib/manager/index.ts:60:17)\n    at async getManagerPackageFiles (/Users/rhys/src/renovatebot/renovate/lib/workers/repository/extract/manager-files.ts:33:29)\n    at async /Users/rhys/src/renovatebot/renovate/lib/workers/repository/extract/index.ts:45:28\n    at async Promise.all (index 0)\n    at async extractAllDependencies (/Users/rhys/src/renovatebot/renovate/lib/workers/repository/extract/index.ts:43:26)\n    at async checkOnboardingBranch (/Users/rhys/src/renovatebot/renovate/lib/workers/repository/onboarding/branch/index.ts:57:22)\n    at async getRepoConfig (/Users/rhys/src/renovatebot/renovate/lib/workers/repository/init/config.ts:12:12)\n    at async initRepo (/Users/rhys/src/renovatebot/renovate/lib/workers/repository/init/index.ts:31:12)\n    at async Object.renovateRepository (/Users/rhys/src/renovatebot/renovate/lib/workers/repository/index.ts:44:14)\n    at async Object.start (/Users/rhys/src/renovatebot/renovate/lib/workers/global/index.ts:111:7)\n    at async /Users/rhys/src/renovatebot/renovate/lib/renovate.ts:16:22"
       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

Make an additional nil check

## Context:

Closes #11723

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/manager/gradle/shallow/extract.ts [hunk 1]
```diff
@@ -98,20 +100,27 @@ export async function extractAllPackageFiles(
...
+            ...(dep.registryUrls || []),
+            ...registryUrls,
+          ]),
+        ],
+      });
+      packageFilesByName[key] = pkgFile;
+    } /* istanbul ignore next */ else {
+      logger.warn(
+        { dep },
+        `Failed to process Gradle dependency: ${dep.lookupName}`
```
Comment (rarkins) [inline lib/manager/gradle/shallow/extract.ts:121]:
```suggestion
        `Failed to process Gradle dependency`
```

I need this to be ignorable by making the string constant

File: lib/manager/gradle/shallow/extract.ts [hunk 2]
```diff
@@ -98,20 +98,24 @@ export async function extractAllPackageFiles(
...
+        registryUrls: [
+          ...new Set([
+            ...defaultRegistryUrls,
+            ...(dep.registryUrls || []),
+            ...registryUrls,
+          ]),
+        ],
+      });
+      packageFilesByName[key] = pkgFile;
+    } /* istanbul ignore next */ else {
```
Comment (rarkins) [inline lib/manager/gradle/shallow/extract.ts:116]:
```suggestion
    } else /* istanbul ignore next */ {
```

**Review by viceice — APPROVED** [review]
