### PR TITLE
fix(cache): add extract revision, stop deleting skipReason

### LINKED ISSUE #33171: Incorrect removal of skipReason from extract cache
### Discussed in https://github.com/renovatebot/renovate/discussions/33148

<div type='discussions-op-text'>

<sup>Originally posted by **Turbo87** December 16, 2024</sup>
### How are you running Renovate?

A Mend.io-hosted app

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

_No response_

### Please tell us more about your question or problem

> [!WARNING]
> Renovate failed to look up the following dependencies: `Failed to look up crate package crates_io_cdn_logs`, `Failed to look up crate package crates_io_database`, `Failed to look up crate package crates_io_database_dump`, `Failed to look up crate package crates_io_env_vars`, `Failed to look up crate package crates_io_github`, `Failed to look up crate package crates_io_index`, `Failed to look up crate package crates_io_markdown`, `Failed to look up crate package crates_io_pagerduty`, `Failed to look up crate package crates_io_tarball`, `Failed to look up crate package crates_io_team_repo`, `Failed to look up crate package crates_io_worker`, `Failed to look up crate package crates_io_test_db`.
> 
> Files affected: `Cargo.toml`, `crates/crates_io_database/Cargo.toml`, `crates/crates_io_database_dump/Cargo.toml`, `crates/crates_io_index/Cargo.toml`, `crates/crates_io_smoke_test/Cargo.toml`, `crates/crates_io_test_db/Cargo.toml`, `crates/crates_io_worker/Cargo.toml`

but these crates are workspace-internal packages/dependencies, so renovatebot would not find them on the registry. This is the first time I've seen this warning, so it seems likely to be caused by a recent change?

### Logs (if relevant)

see https://developer.mend.io/github/rust-lang/crates.io/-/job/0193cffc-1761-7268-964b-6771a7233971, but I didn't spot anything particularly relevant in them</div>

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Removes problematic `skipReason` removal (it's unreliable, and I want to reduce complexity in this PR), and adds an extract cache revision to "cache bust" all extract caches due to this mistake.

## Context

- closes #33171

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/repository/process/extract-update.ts [hunk 1]
```diff
@@ -18,6 +18,8 @@ import { Vulnerabilities } from './vulnerabilities';
 import type { WriteUpdateResult } from './write';
 import { writeUpdates } from './write';
 
+export const EXTRACT_CACHE_REVISION = 1;
```
Comment (rarkins) [inline lib/workers/repository/process/extract-update.ts:21]:
```suggestion
// Increment this if needing to cache bust ALL extract caches
export const EXTRACT_CACHE_REVISION = 1;
```

File: lib/workers/repository/process/extract-update.ts [hunk 2]
```diff
@@ -128,10 +147,6 @@ export async function extract(
         for (const file of files) {
           for (const dep of file.deps) {
             delete dep.updates;
-            if (dep.skipStage && dep.skipStage !== 'extract') {
-              delete dep.skipReason;
-              delete dep.skipStage;
-            }
```
Comment (rarkins) [inline lib/workers/repository/process/extract-update.ts:134]: When debugging, I found that this was set to `lookup` for cargo extracts. I choose to remove this, instead of attempt to properly implement it

**Review by viceice — APPROVED** [review]

**Review by secustor — APPROVED** [review]
