### PR TITLE
fix(python): remove default versioning

### LINKED ISSUE #15427: pip requirements with git references create the update incorrectly
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

`==` is being added to the newValue when creating an update. While this is valid for pip packages install from repositories, it isn't in the case of git references.

Sample repo with problematic PR: https://github.com/mikhailadvani/use_pip_package/pull/2

### Relevant debug logs

<details><summary>Logs</summary>

https://github.com/mikhailadvani/use_pip_package/runs/6276936064?check_suite_focus=true
</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by mikhailadvani**
## Changes

Rely on versioning for python packages based on package types e.g. git & pyp

## Context

Closes #15427
Replaces #15428 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Review by viceice — CHANGES_REQUESTED** [review]
please force push with a semantic commit title and update PR title

File: lib/config/options/index.ts [hunk 1]
```diff
@@ -1885,9 +1884,6 @@ const options: RenovateOptions[] = [
     description: 'Configuration object for Python.',
     stage: 'package',
     type: 'object',
-    default: {
```
Comment (rarkins) [inline lib/config/options/index.ts:1888]: Please set an empty default, i.e. `default: {}`

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by rarkins — APPROVED** [review]

**Comment by mikhailadvani** [comment]
@viceice can you please approve as well

**Review by viceice — APPROVED** [review]
