### PR TITLE
fix(datasource/dotnet-version): use sdks property to find all sdk version

### LINKED ISSUE #23888: dotnet-sdk datasource only retrieves latest-sdk for each major-minor combination, not all available versions
### Discussed in https://github.com/renovatebot/renovate/discussions/23788

<div type='discussions-op-text'>

<sup>Originally posted by **SjoerdvE** August  9, 2023</sup>
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

-

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the problem

Background: Microsoft has three 'tracks' of SDK versions: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
Since our builder image has the 'oldest' track installed, that is the version that we want updated. (So there are 6.0.4xx, 6.0.3yy and 6.0.1zz tracks. We are currently running `6.0.110` and want to update this within the `6.0.1zz` track.)

When trying to get Renovate to get me the latest version of a .NET SDK track it only gets the latest-sdk version of a major-minor combination, not all available packages.

I've tried the following situations with allowedVersions (current version is 6.0.110):
- `<7` which correctly gets me `6.0.413`
- `<6.0.200` which does not show any updates, while there is a `6.0.121` available.

For the files and minimal reproduction see the files in this repo: https://github.com/Sjoerde/renovatebot-issue-allowedversions

After some discussion (see below for more details) I found out that:
- Renovate retrieves the dotnet-sdk datasource from: 
  `"registryUrl": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json"`
- This `releases-index.json` only contains the latest-sdk version of each major-minor combination.
- The linked datasources for each specific major-minor combination are referenced, but I assume not loaded in Renovate:
  `"releases.json": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json"`
- The `6.0.121` that I want and want to use the `<6.0.200` for is available in this linked/nested datasource.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: packageFiles with updates
{
  "baseBranch": "main"
  "config": {
    "nuget": [
      {
        "deps": [
          {
            "depType": "dotnet-sdk",
            "depName": "dotnet-sdk",
            "currentValue": "6.0.110",
            "datasource": "dotnet-version",
            "updates": [],
            "packageName": "dotnet-sdk",
            "versioning": "semver-coerced",
            "warnings": [],
            "sourceUrl": "https://github.com/dotnet/sdk",
            "registryUrl": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json",
            "currentVersion": "6.0.110",
            "fixedVersion": "6.0.110"
          }
        ],
        "packageFile": "global.json"
      }
    ]
  }
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above
- https://github.com/Sjoerde/renovatebot-issue-allowedversions
- https://github.com/renovate-reproductions/23888-renovatebot-issue-allowedversions

### PR DESCRIPTION
**Pull request by viceice**
## Changes
- use `releases[].sdks[]` as source for dotnet sdk versions.

## Context
- fixes #23888
- https://github.com/renovate-reproductions/23888-renovatebot-issue-allowedversions/pull/1

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/datasource/dotnet-version/schema.ts [hunk 1]
```diff
@@ -26,17 +26,22 @@ export const DotnetSdkReleases = z
   .object({
     releases: LooseArray(
       ReleaseBase.extend({
-        sdk: ReleaseDetails,
```
Comment (rarkins) [inline lib/modules/datasource/dotnet-version/schema.ts:29]: Was this a bug and fields doesn't exist? Or it exists but is superseded by sdks?

Comment (viceice) [reply lib/modules/datasource/dotnet-version/schema.ts:29]: this exists, but same version is also contained in `sdks` array, so i removed the duplicate

**Review by rarkins — APPROVED** [review]
