### PR TITLE
fix(composer): Add GitLab token to composer.

### LINKED ISSUE #2660: GitLab authentication token not implicitly passed to Composer
**What Renovate type are you using?**
Renovate Docker + GitLab CI

**Describe the bug**
When a project contains a private composer package under a private GitLab repository, `composer` fails with error message `Could not authenticate against gitlab.com` because Renovate doesn't share the auth token with `composer`

**Did you see anything helpful in debug logs?**
```
Installing my/package (v5.0.3): Downloading    Failed to download my/package from dist: Could not authenticate against gitlab.com
```

**To Reproduce**

1.  Create a satis repository hosting a `composer` package from a private GitLab repository
2.  Configure Renovate with the satis basic auth credentials and a GitLab token.
3.  Create a project for Renovate to work on which asks for the private package from the satis repository
4.  Run renovate to update the package, see the authentication failure

**Expected behavior**
Package to be upgraded successfully.

**Additional context**
The fix for this, is to ensure that the token given in `--token` on CLI is also saved in `composer`. It seems this may only be done for GitHub, it needs to also be done for GitLab.

### PR DESCRIPTION
**Pull request by Jamesking56**
Closes #2660

Needs testing, not sure if this edit is right.

### CODE REVIEW

File: lib/manager/composer/artifacts.js [hunk 1]
```diff
@@ -38,17 +38,24 @@ async function getArtifacts(
...
+      authJson['github-oauth'] = {
+        'github.com': credentials.token,
+      };
+    }
+    credentials = hostRules.find({
+      platform: 'gitlab',
+      host: 'gitlab.com',
+    });
+    if (credentials && credentials.token) {
+      authJson['gitlab-oauth'] = {
```
Comment (rarkins) [inline lib/manager/composer/artifacts.js]: GitLab treats personal access tokens and oauth tokens completely differently, so this may not work. It’s there an option for a non-oauth GitLab token in auth.json?

Comment (Jamesking56) [reply lib/manager/composer/artifacts.js]: Theres `gitlab-oauth` and `gitlab-token`. Which one should this be using?

https://getcomposer.org/doc/06-config.md#gitlab-oauth

**Comment by rarkins** [comment]
Yes I think so, once I’m back to my keyboard

**Comment by Jamesking56** [comment]
Thanks @rarkins :tada:
