### PR TITLE
fix(github): Shrink GraphQL page size and retry for any ExternalHostError

### LINKED ISSUE #12687: Handle GitHub GraphQL ECONNRESET
### Describe the proposed change(s).

Example log from the hosted app:

```
{
err: {
code: ECONNRESET, 
message: The server aborted pending request, 
name: ReadError, 
options: [Object], 
response: [Object], 
stack: 
ReadError: The server aborted pending request
    at PassThrough.<anonymous> (/home/ubuntu/renovateapp/node_modules/got/dist/source/core/index.js:803:31)
    at Object.onceWrapper (events.js:519:28)
    at PassThrough.emit (events.js:400:28)
    at PassThrough.emit (domain.js:470:12)
    at IncomingMessage.<anonymous> (/home/ubuntu/renovateapp/node_modules/decompress-response/node_modules/mimic-response/index.js:59:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:470:12)
    at IncomingMessage.origin.emit (/home/ubuntu/renovateapp/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketCloseListener (_http_client.js:432:11)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:470:12)
    at net.js:675:12
    at TCP.done (_tls_wrap.js:563:7)
, 
timings: [Object]
}, 
hostType: github, 
message: external-host-error, 
stack: 
Error: external-host-error
    at handleGotError (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/github.js:33:15)
    at GithubHttp.request (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/github.js:160:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async GithubHttp.requestJson (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/index.js:176:21)
    at async GithubHttp.requestGraphql (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/github.js:184:25)
    at async GithubHttp.queryRepoField (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/github.js:214:25)
    at async getOpenPrs (/home/ubuntu/renovateapp/node_modules/renovate/dist/platform/github/index.js:459:27)
    at async getPr (/home/ubuntu/renovateapp/node_modules/renovate/dist/platform/github/index.js:534:21)
    at async Proxy.getBranchPr (/home/ubuntu/renovateapp/node_modules/renovate/dist/platform/github/index.js:649:40)
    at async getConcurrentPrsRemaining (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/limits.js:43:32)
    at async getPrsRemaining (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/limits.js:69:33)
    at async writeUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/write.js:16:26)
    at async update (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/extract-update.js:110:15)
    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:68:21)
    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:402:26)
    at async /home/ubuntu/renovateapp/app/worker/index.js:652:5
}
```

We should try reducing the pagination count in such a case

### PR DESCRIPTION
**Pull request by zharinov**
## Context:

Closes #12687

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]

File: lib/util/http/github.ts [hunk 1]
```diff
@@ -284,19 +284,9 @@ export class GithubHttp extends Http<GithubHttpOptions, GithubHttpOptions> {
...
-          count &&
-          count > 10 &&
-          statusCode &&
-          statusCode >= 500 &&
-          statusCode < 600
-        ) {
-          logger.info('Reducing pagination count to workaround graphql 5xx');
-          return null;
-        }
+      if (err instanceof ExternalHostError && count && count > 10) {
```
Comment (HonkingGoose) [inline lib/util/http/github.ts:287]: @zharinov will having this PR close issue #12687 maybe?

**Comment by rarkins** [comment]
This appears to have had a very positive effect in the app. Here's the stats for `getOpenPrs(): error`:

image
