### PR TITLE
fix(yarn): allow overwriting of yarnrc file

### LINKED ISSUE #6884: Not respecting yarnrc configuration
**What Renovate type are you using?**

Hosted Gitlab App

**Describe the bug**

When executing against a repo containing a `.yarnrc` with the `yarnrc` parameter set to `""` in the `renovate.json` configuration, I would expect Renovate to use all the default configuration for `yarn`.
When doing so, specifically with `modules-folder` set in the `.yarnrc` file, I am seeing renovate attempt to create the `node_modules` folder in the wrong location.

**Relevant debug logs**

I see in the `migrated config` message that there is a `yarnrc` parameter:
```
DEBUG: migrated config
{
  "config": {
    "extends": [
      "config:base"
    ],
    "yarnrc": "***********"
  }
}
```
I also see some log lines relating to writing `.yarnrc` which I think indicate that renovate is, at some point, writing its own `.yarnrc` into the checkout folder:
```
DEBUG: Writing repo .yarnrc (/mnt/renovate/gl/rconan/renovate-yarnrc)(branch="renovate/yarn-1.x")
DEBUG: Writing package.json files(branch="renovate/yarn-1.x")
{
  "packageFiles": [
    "package.json"
  ]
}
DEBUG: Writing .yarnrc to /mnt/renovate/gl/rconan/renovate-yarnrc(branch="renovate/yarn-1.x")
```

**To Reproduce**

There is a simple reproducer for this here:
https://gitlab.com/rconan/renovate-yarnrc

**Additional context**

Is the repo being `reset --hard` or similar after renovate has written `.yarnrc`?
Is renovate interpretting `""` as some kind of "falsey" value at some point and not respecting it?

### PR DESCRIPTION
**Pull request by rarkins**
Skip reading the `.yarnrc` file if `yarnrc` is already in config.

Closes #6884

### CODE REVIEW

File: lib/manager/npm/post-update/index.ts [hunk 1]
```diff
@@ -129,9 +130,10 @@ export async function writeExistingFiles(
     logger.debug('Removing ignored .npmrc file before artifact generation');
     await remove(npmrcFile);
   }
-  if (config.yarnrc) {
+  if (is.string(config.yarnrc)) {
     logger.debug(`Writing repo .yarnrc (${config.localDir})`);
-    await outputFile(upath.join(config.localDir, '.yarnrc'), config.yarnrc);
+    const yarnrcFileName = upath.join(config.localDir, '.yarnrc');
```
Comment (viceice) [inline lib/manager/npm/post-update/index.ts:135]: I think this will already be done by outputFile?

Comment (rarkins) [reply lib/manager/npm/post-update/index.ts:135]: actually this change isn't necessary, i will revert it. We could refactor to use outputLocalFile but I don't want to complicated it right now

File: lib/manager/npm/post-update/index.ts [hunk 2]
```diff
@@ -129,9 +130,10 @@ export async function writeExistingFiles(
...
+    await outputFile(yarnrcFileName, config.yarnrc);
```
Comment (viceice) [inline lib/manager/npm/post-update/index.ts:136]:
```suggestion
    await writeLocalFile('.yarnrc', config.yarnrc);
```

should do the trick

**Review by viceice — APPROVED** [review]
