### PR TITLE
fix(manager/mix): support lockfiles in subdirs

### LINKED ISSUE #9992: [mix] renovate does not update mix.lock in a subfolder
**What Renovate type, platform and version are you using?**

**Renovate type**

- [x] Hosted app
- [ ] Self hosted

**Renovate platform**

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server (self-hosted)
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server (self-hosted)
- [ ] Gitea (gitea.com, self-hosted)
- [x] GitHub (github.com, GitHub Enterprise)
- [ ] GitLab (gitlab.com, self-hosted)

**Renovate version (if self hosting)**

I'm self hosting Renovate with version: ...

**Describe the bug**

If a mix project is located in a repo's root, renovate is able to update both dependencies file `mix.ex` and lock-file `mix.lock`. However, if mix project is in the subdirectory, renovate only updates `mix.ex`. 

**Relevant debug logs**

Here we can see that renovate successfully identified both `mix.ex` files and their corresponding `mix.lock` files:
<details><summary>Click me to see logs</summary>

```
{
  "config": {
    "mix": [
      {
        "packageFile": "app/mix.exs",
        "deps": [
          {
            "depName": "plug",
            "currentValue": "1.10.4",
            "managerData": {
              "lineNumber": 23
            },
            "datasource": "hex",
            "lookupName": "plug",
            "depIndex": 0,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "1.11.1",
                "newValue": "== 1.11.1",
                "releaseTimestamp": "2021-03-08T09:15:53.623Z",
                "newMajor": 1,
                "newMinor": 11,
                "updateType": "minor",
                "isRange": true,
                "branchName": "renovate/plug-1.x"
              }
            ],
            "warnings": [],
            "homepage": "https://hex.pm/packages/plug",
            "currentVersion": "1.10.4",
            "isSingleVersion": false,
            "fixedVersion": "1.10.4"
          },
          {
            "depName": "dep_from_hexpm",
            "currentValue": "~> 0.3.0",
            "managerData": {
              "lineNumber": 24
            },
            "datasource": "hex",
            "lookupName": "dep_from_hexpm",
            "depIndex": 1,
            "updates": [],
            "warnings": [],
            "homepage": "https://hex.pm/packages/dep_from_hexpm",
            "currentVersion": "0.3.0"
          },
          {
            "depName": "dep_from_git",
            "currentValue": "https://github.com/elixir-lang/my_dep.git",
            "managerData": {
              "lineNumber": 25
            },
            "datasource": "git",
            "skipReason": "non-hex depTypes",
            "depIndex": 2,
            "updates": []
          }
        ],
        "lockFiles": [
          "app/mix.lock"
        ]
      },
      {
        "packageFile": "mix.exs",
        "deps": [
          {
            "depName": "plug",
            "currentValue": "1.10.4",
            "managerData": {
              "lineNumber": 23
            },
            "datasource": "hex",
            "lookupName": "plug",
            "depIndex": 0,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "1.11.1",
                "newValue": "== 1.11.1",
                "releaseTimestamp": "2021-03-08T09:15:53.623Z",
                "newMajor": 1,
                "newMinor": 11,
                "updateType": "minor",
                "isRange": true,
                "branchName": "renovate/plug-1.x"
              }
            ],
            "warnings": [],
            "homepage": "https://hex.pm/packages/plug",
            "currentVersion": "1.10.4",
            "isSingleVersion": false,
            "fixedVersion": "1.10.4"
          },
          {
            "depName": "dep_from_hexpm",
            "currentValue": "~> 0.3.0",
            "managerData": {
              "lineNumber": 24
            },
            "datasource": "hex",
            "lookupName": "dep_from_hexpm",
            "depIndex": 1,
            "updates": [],
            "warnings": [],
            "homepage": "https://hex.pm/packages/dep_from_hexpm",
            "currentVersion": "0.3.0"
          },
          {
            "depName": "dep_from_git",
            "currentValue": "https://github.com/elixir-lang/my_dep.git",
            "managerData": {
              "lineNumber": 25
            },
            "datasource": "git",
            "skipReason": "non-hex depTypes",
            "depIndex": 2,
            "updates": []
          }
        ],
        "lockFiles": [
          "mix.lock"
        ]
      }
    ]
  }
}
```

</details>

But here something goes wrong and nested `mix.lock` is not updated:
<details><summary>Click me to see logs</summary>

```
DEBUG: mix.getArtifacts(mix.exs)(branch="renovate/plug-1.x")
DEBUG: Using docker to execute(branch="renovate/plug-1.x")
DEBUG: No tag or tagConstraint specified(branch="renovate/plug-1.x")
{
  "image": "docker.io/renovate/elixir"
}
DEBUG: Fetching Docker image: docker.io/renovate/elixir(branch="renovate/plug-1.x")
DEBUG: Finished fetching Docker image(branch="renovate/plug-1.x")
DEBUG: Executing command(branch="renovate/plug-1.x")
{
  "command": "docker run --rm --name=renovate_elixir --label=renovate_child -v \"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest\":\"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest\" docker.io/renovate/elixir bash -l -c \"mix deps.update plug\""
}
DEBUG: exec completed(branch="renovate/plug-1.x")
{
  "cmd": "docker run --rm --name=renovate_elixir --label=renovate_child -v \"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest\":\"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest\" docker.io/renovate/elixir bash -l -c \"mix deps.update plug\"",
  "durationMs": 8787,
  "stdout": "Resolving Hex dependencies...\nDependency resolution completed:\nUnchanged:\n  mime 1.6.0\n  plug_crypto 1.2.2\n  telemetry 0.4.3\nUpgraded:\n  plug 1.10.4 => 1.11.1\n* Getting plug (Hex package)\n",
  "stderr": ""
}
DEBUG: Returning updated mix.lock(branch="renovate/plug-1.x")
DEBUG: mix.getArtifacts(app/mix.exs)(branch="renovate/plug-1.x")
DEBUG: Using docker to execute(branch="renovate/plug-1.x")
DEBUG: No tag or tagConstraint specified(branch="renovate/plug-1.x")
{
  "image": "docker.io/renovate/elixir"
}
DEBUG: Docker image is already prefetched: docker.io/renovate/elixir(branch="renovate/plug-1.x")
DEBUG: Executing command(branch="renovate/plug-1.x")
{
  "command": "docker run --rm --name=renovate_elixir --label=renovate_child -v \"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest\":\"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest/app\" docker.io/renovate/elixir bash -l -c \"mix deps.update plug\""
}
DEBUG: exec completed(branch="renovate/plug-1.x")
{
  "cmd": "docker run --rm --name=renovate_elixir --label=renovate_child -v \"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest\":\"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gh/amartsinovich-dialpad/renovatetest/app\" docker.io/renovate/elixir bash -l -c \"mix deps.update plug\"",
  "durationMs": 5922,
  "stdout": "Resolving Hex dependencies...\nDependency resolution completed:\nUnchanged:\n  mime 1.6.0\n  plug_crypto 1.2.2\n  telemetry 0.4.3\nUpgraded:\n  plug 1.10.4 => 1.11.1\n* Getting plug (Hex package)\n",
  "stderr": ""
}
DEBUG: mix.lock is unchanged(branch="renovate/plug-1.x")
DEBUG: Updated 2 package files(branch="renovate/plug-1.x")
DEBUG: Updated 1 lock files(branch="renovate/plug-1.x")
{
  "updatedArtifacts": [
    "mix.lock"
  ]
}
```

</details>

**Have you created a minimal reproduction repository?**
Yes https://github.com/amartsinovich-dialpad/renovatetest/pull/2/files

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

### PR DESCRIPTION
**Pull request by TheKevJames**
## Changes:

Fixes a bug where the `mix.exs` file may be in a subdir of the repo but
the `mix.lock` file is always searched for in the root -- they should
always be in the same folder.

I suspect a better TypeScript programmer more familiar with this repo
could come up with a better way to do this -- let me know if you have
any suggestions!

## Context:

Closes #9992

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/manager/mix/artifacts.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ export async function updateArtifacts({
     return null;
   }
 
-  const lockFileName = 'mix.lock';
+  const lockFileName = [...packageFileName.split('/').slice(0, -1), 'mix.lock'].join('/');
```
Comment (viceice) [inline lib/manager/mix/artifacts.ts:19]: Use `getSilblingFile` from fs utils instead.

**Review by viceice — CHANGES_REQUESTED** [review]
Needs a test

**Comment by TheKevJames** [comment]
@viceice updated with usage of `getSiblingFileName()` and relevant test.

File: lib/manager/mix/__snapshots__/artifacts.spec.ts.snap [hunk 2]
```diff
@@ -90,3 +90,5 @@ Array [
   },
 ]
 `;
+
+exports[`manager/mix/artifacts returns updated mix.lock in subdir 1`] = `null`;
```
Comment (viceice) [inline lib/manager/mix/__snapshots__/artifacts.spec.ts.snap:94]: Why null? Shouldn't there be extracted deps?

File: lib/manager/mix/artifacts.spec.ts [hunk 3]
```diff
@@ -96,8 +97,25 @@ describe(getName(), () => {
...
+    fs.getSiblingFileName.mockReturnValueOnce('subdir/mix.lock');
+    const execSnapshots = mockExecAll(exec);
+    expect(
+      await updateArtifacts({
+        packageFileName: 'subdir/mix.exs',
+        updatedDeps: [{ depName: 'plug' }],
+        newPackageFileContent: '{}',
+        config,
+      })
+    ).toMatchSnapshot();
```
Comment (viceice) [inline lib/manager/mix/artifacts.spec.ts:112]: Do not use snapshot test, when you expect null. Use `toBeNull()` matcher.

Shouldn't we expected some non null response here?

Comment (TheKevJames) [reply lib/manager/mix/artifacts.spec.ts:112]: I'm not sure it much matters? I'm basically just testing whether it hits the `expect(fs.readLocalFile).toBeCalledWith('subdir/mix.lock', 'utf8');` line with the correct subdirectory. If that's correct, I don't think we much care about the rest of the update method, since that's already tested in the various other methods here and doesn't change behaviour for the subdir usecase.

Comment (viceice) [reply lib/manager/mix/artifacts.spec.ts]: Ok,then use `toBeNull` matcher if the result is null anyways.

**Comment by TheKevJames** [comment]
@viceice swapped out the snapshots with a direct null check

**Review by viceice — APPROVED** [review]
