### PR TITLE
fix(gradle-lite): Upgrade deps in reverse order for grouped dependencies

### LINKED ISSUE #8224: Gradle update fails when using gradle-lite with specific dependencies
**What Renovate type, platform and version are you using?**

  "renovateVersion": "24.11.5"

**Describe the bug**

build.gradle update fails to fill version updates properly when updating the versions in a specific way. 

`kotlin("plugin.spring") version "1.4.0"`

becomes for example

`kotlin("plugin.spring") versio1.4.21-2 "1.4.0"`

**Relevant debug logs**

There seemed not to be relevant problems in logs about this issue. Update numbers in the logs were correct, and they did not seem to break there. Such as:

```
... 
{
            "depName": "org.jetbrains.kotlin:kotlin-reflect",
            "currentValue": "1.4.21",
            "managerData": {
              "fileReplacePosition": 1335,
              "packageFile": "build.gradle.kts"
            },
            "registryUrls": [],
            "depIndex": 12,
            "updates": [
              {
                "fromVersion": "1.4.21",
                "toVersion": "1.4.21-2",
                "newValue": "1.4.21-2",
                "newMajor": 1,
                "newMinor": 4,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "Mon, 28 Dec 2020 17:12:00 GMT"
              }
            ],
            "warnings": [],
            "fixedVersion": "1.4.21",
            "sourceUrl": "https://github.com/JetBrains/kotlin",
            "homepage": "https://kotlinlang.org/",
            "dependencyUrl": "org/jetbrains/kotlin/kotlin-reflect"
          },
...
```

**Have you created a minimal reproduction repository?** 

[Repository found here](https://github.com/taavipyry/renovate-showcase-gradle-lite-bug/pull/1/commits/839b390003e6e4ce5ad7ba9cfe29ae0bc64f3977
)
- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [X] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Happens also with self hosted renovate docker image version `24.10.1-slim`.

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

Copy `fileReplacePosition` from `managerData`, so it will be recognized by mechanism we recently used for this problem in other Maven-based managers.

## Context:

Closes #8224

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [x] ~~Unit tests~~ + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
Example: https://github.com/renovate-testing/test-8224-gradle-lite-conflict-with-gradle/pull/7/files

File: lib/manager/gradle-lite/extract.ts [hunk 1]
```diff
@@ -13,6 +13,21 @@ import {
...
+// Required for grouped dependencies to be upgraded
+// correctly in single branch.
+//
+// https://github.com/renovatebot/renovate/issues/8224
+function elevateFileReplacePositionField(
+  deps: PackageDependency<ManagerData>[]
+): PackageDependency<ManagerData>[] {
+  return deps.map((dep) => ({
+    ...dep,
+    fileReplacePosition: dep?.managerData?.fileReplacePosition,
```
Comment (zharinov) [inline lib/manager/gradle-lite/extract.ts:27]: Why not make sure we use `managerData` everywhere? Because I'm not sure this field will be available from all the places where `fileReplacePosition` is needed. Potentially, maybe it can be pretty big refactoring for the thing which is pretty hacky.
