### PR TITLE
fix(automerge): assign failing PRs

### LINKED ISSUE #12561: Renovate does not add assignee when pipeline failed and automerge=true
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

29.3.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Describe the bug

When an assignee is set and automerge is enabled, Renovate does not seem to assign the person anymore when the status check failed. I think this was the case in earlier versions and the documentation still mention this.

I have the following config:
```
{
  "extends": [
    ":automergeMinor",
    ":assignee(micheh)"
  ]
}
```

When Renovate creates the PR for the first time, the assignees are skipped. This make sense, as the automerge is true and the status check is still unknown.

<details><summary>Log (first run)</summary>

```
INFO: PR created(branch="renovate/psr-log-1.x")
{
  "pr": 4,
  "prTitle": "Update dependency psr/log to ~1.1.0"
}
DEBUG: Skipping assignees and reviewers as automerge=true(branch="renovate/psr-log-1.x")
DEBUG: Created Pull Request #4(branch="renovate/psr-log-1.x")
DEBUG: PR is configured for automerge(branch="renovate/psr-log-1.x")
DEBUG: PR is not ready for merge(branch="renovate/psr-log-1.x")
```

</details>

On the next run, Renovate identifies the red status check and updates the PR body with the information that an automerge is not possible, as the status check failed. This is as expected. However, no assignees are assigned.

<details><summary>Log (second run)</summary>

```
DEBUG: Found existing PR(branch="renovate/psr-log-1.x")
DEBUG: resolveBranchStatus(branchName=renovate/psr-log-1.x, ignoreTests=false)(branch="renovate/psr-log-1.x")
DEBUG: getBranchStatus(renovate/psr-log-1.x)(branch="renovate/psr-log-1.x")
DEBUG: branch status check result(branch="renovate/psr-log-1.x")
{
  "state": "pending",
  "statuses": []
}
DEBUG: check runs result(branch="renovate/psr-log-1.x")
{
  "checkRuns": [
    {
      "name": "test",
      "status": "completed",
      "conclusion": "failure"
    },
    {
      "name": "test",
      "status": "completed",
      "conclusion": "failure"
    }
  ]
}
DEBUG: Branch status red(branch="renovate/psr-log-1.x")
DEBUG: Processing existing PR(branch="renovate/psr-log-1.x")
DEBUG: PR body changed(branch="renovate/psr-log-1.x")
{
  "prTitle": "Update dependency psr/log to ~1.1.0"
}
DEBUG: updatePr(4, Update dependency psr/log to ~1.1.0, body)(branch="renovate/psr-log-1.x")
DEBUG: PR updated(branch="renovate/psr-log-1.x")
{
  "pr": 4
}
INFO: PR updated(branch="renovate/psr-log-1.x")
{
  "pr": 4,
  "prTitle": "Update dependency psr/log to ~1.1.0"
}
DEBUG: PR is configured for automerge(branch="renovate/psr-log-1.x")
DEBUG: resolveBranchStatus(branchName=renovate/psr-log-1.x, ignoreTests=false)(branch="renovate/psr-log-1.x")
DEBUG: getBranchStatus(renovate/psr-log-1.x)(branch="renovate/psr-log-1.x")
DEBUG: branch status check result(branch="renovate/psr-log-1.x")
{
  "state": "pending",
  "statuses": []
}
DEBUG: check runs result(branch="renovate/psr-log-1.x")
{
  "checkRuns": [
    {
      "name": "test",
      "status": "completed",
      "conclusion": "failure"
    },
    {
      "name": "test",
      "status": "completed",
      "conclusion": "failure"
    }
  ]
}
DEBUG: Branch status red(branch="renovate/psr-log-1.x")
DEBUG: PR is not ready for merge (branch status is red)(branch="renovate/psr-log-1.x")
```

</details>

Reproduction: https://github.com/micheh/renovate-test

https://github.com/micheh/renovate-test/pull/4 failed but the assignee was not added when Renovate run the second time and detected that the status check failed.

### Relevant debug logs

See above

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### LINKED ISSUE #12621: Assignees is not working on GitLab
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:29

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

13.3.5

### Describe the bug

I have set assignees on renovate.json in my repo, but assignee was not set for any MRs (with automerge(with failed pipeline) and without automerge).
I tried use e-mail, full name and login.
renovate.json in repo:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "assignees": ["ivanov123"]
}
```
or
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "assignees": ["ivanov@company.com"]
}
```
or
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "assignees": ["Ivan Ivanov"]
}
```

Also tried like this:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    ":assignee(ivanov123)"
  ]
}
```

Config in docker:
```json
{
    "labels": ["Dependency Bot"],
    "repositories": [
        "my-repo1"
    ],
    "extends": ["config:base", ":prHourlyLimitNone"],
    "commitMessagePrefix": "JIRA-0000",
    "packageRules": [
      { 
        "matchUpdateTypes": ["minor", "patch", "pin", "digest"], "automerge": true
      },
      {
        "matchManagers": ["maven"],
        "enabled": false
      },
      {
        "matchUpdateTypes": ["major"],
        "labels": ["Dependency Bot","UPDATE-MAJOR"]
      },
      {
        "groupName": "git.company.com/prod.platform.cloud_core",
        "matchPackagePatterns": ["git.company.com/prod.platform.cloud_core"],
        "separateMinorPatch": false,
        "automerge": false
      }
	],
    "recreateClosed": true,
    "platformAutomerge": true,
    "rebaseWhen": "behind-base-branch"
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /usr/src/app/config
DEBUG: File config
       "config": {
         "labels": ["Dependency Bot"],
         "repositories": ["my-repo1"],
         "extends": ["config:base", ":prHourlyLimitNone"],
         "commitMessagePrefix": "JIRA-0000",
         "packageRules": [
           {
             "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
             "automerge": true
           },
           {"matchManagers": ["maven"], "enabled": false},
           {
             "matchUpdateTypes": ["major"],
             "labels": ["Dependency Bot", "UPDATE-MAJOR"]
           },
           {
             "groupName": "git.company.com/prod.platform.cloud_core",
             "matchPackagePatterns": ["git.company.com/prod.platform.cloud_core"],
             "separateMinorPatch": false,
             "automerge": false
           }
         ],
         "recreateClosed": true,
         "platformAutomerge": true,
         "rebaseWhen": "behind-base-branch"
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {
         "hostRules": [],
         "platform": "gitlab",
         "endpoint": "https://git.company.com/api/v4",
         "token": "***********",
         "autodiscover": false
       }
DEBUG: Combined config
       "config": {
         "labels": ["Dependency Bot"],
         "repositories": ["my-repo1"],
         "extends": ["config:base", ":prHourlyLimitNone"],
         "commitMessagePrefix": "JIRA-0000",
         "packageRules": [
           {
             "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
             "automerge": true
           },
           {"matchManagers": ["maven"], "enabled": false},
           {
             "matchUpdateTypes": ["major"],
             "labels": ["Dependency Bot", "UPDATE-MAJOR"]
           },
           {
             "groupName": "git.company.com/prod.platform.cloud_core",
             "matchPackagePatterns": ["git.company.com/prod.platform.cloud_core"],
             "separateMinorPatch": false,
             "automerge": false
           }
         ],
         "recreateClosed": true,
         "platformAutomerge": true,
         "rebaseWhen": "behind-base-branch",
         "hostRules": [],
         "platform": "gitlab",
         "endpoint": "https://git.company.com/api/v4",
         "token": "***********",
         "autodiscover": false
       }
DEBUG: Adding trailing slash to endpoint
DEBUG: GitLab version is: 13.3.5
DEBUG: Using platform gitAuthor: x_dependency_bot <x_dependency_bot@company.com>
DEBUG: Adding token authentication for git.company.com to hostRules
DEBUG: Using baseDir: /tmp/renovate
DEBUG: Using cacheDir: /tmp/renovate/cache
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
DEBUG: Commits limit = null
DEBUG: Clearing hostRules
DEBUG: Adding token authentication for git.company.com to hostRules
 INFO: Repository started (repository=my-repo1)
       "renovateVersion": "29.6.0"
DEBUG: Using localDir: /tmp/renovate/repos/gitlab/my-repo1 (repository=my-repo1)
DEBUG: my-repo1 default branch = master (repository=my-repo1)
DEBUG: Enabling Git FS (repository=my-repo1)
DEBUG: using http URL (repository=my-repo1)
       "url": "https://git.company.com/my-repo1.git"
DEBUG: resetMemCache() (repository=my-repo1)
DEBUG: Resetting npmrc (repository=my-repo1)
DEBUG: detectSemanticCommits() (repository=my-repo1)
DEBUG: Initializing git repository into /tmp/renovate/repos/gitlab/my-repo1 (repository=my-repo1)
DEBUG: Performing blobless clone (repository=my-repo1)
DEBUG: git clone completed (repository=my-repo1)
       "durationMs": 1149
DEBUG: latest repository commit (repository=my-repo1)
       "latestCommit": {
         "hash": "1fc43238d16d0ebed592f3b1267b7de142946c50",
         "date": "2021-11-12T06:58:57-05:00",
         "message": "FAKE-0000 Update renovate.json",
         "refs": "HEAD -> master, origin/master, origin/HEAD",
         "body": "",
         "author_name": "Ivan Ivanov",
         "author_email": "Ivan.Ivanov@company.com"
       }
DEBUG: getCommitMessages (repository=my-repo1)
DEBUG: Semantic commits detection: unknown (repository=my-repo1)
DEBUG: No semantic commits detected (repository=my-repo1)
DEBUG: checkOnboarding() (repository=my-repo1)
DEBUG: isOnboarded() (repository=my-repo1)
DEBUG: findFile(renovate.json) (repository=my-repo1)
DEBUG: Config file exists (repository=my-repo1)
       "fileName": "renovate.json"
DEBUG: ensureIssueClosing() (repository=my-repo1)
DEBUG: Repo is onboarded (repository=my-repo1)
DEBUG: Found renovate.json config file (repository=my-repo1)
DEBUG: Repository config (repository=my-repo1)
       "fileName": "renovate.json",
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "assignees": ["ivanov123"]
       }
DEBUG: migrateAndValidate() (repository=my-repo1)
DEBUG: No config migration necessary (repository=my-repo1)
DEBUG: massaged config (repository=my-repo1)
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "assignees": ["ivanov123"],
         "extends": ["config:base", ":prHourlyLimitNone"]
       }
DEBUG: migrated config (repository=my-repo1)
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "assignees": ["ivanov123"],
         "extends": ["config:base", ":prHourlyLimitNone"]
       }
DEBUG: Setting hostRules from config (repository=my-repo1)
DEBUG: Found repo ignorePaths (repository=my-repo1)
       "ignorePaths": [
         "**/node_modules/**",
         "**/bower_components/**",
         "**/vendor/**",
         "**/examples/**",
         "**/__tests__/**",
         "**/test/**",
         "**/tests/**",
         "**/__fixtures__/**"
       ]
DEBUG: No vulnerability alerts found (repository=my-repo1)
DEBUG: findIssue(Dependency Dashboard) (repository=my-repo1)
DEBUG: No baseBranches (repository=my-repo1)
DEBUG: extract() (repository=my-repo1)
DEBUG: Setting current branch to master (repository=my-repo1)
DEBUG: latest commit (repository=my-repo1)
       "branchName": "master",
       "latestCommitDate": "2021-11-12T06:58:57-05:00"
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible (repository=my-repo1)
DEBUG: Using file match: (^|/)requirements\.ya?ml$ for manager ansible-galaxy (repository=my-repo1)
DEBUG: Using file match: (^|/)galaxy\.ya?ml$ for manager ansible-galaxy (repository=my-repo1)
DEBUG: Using file match: azure.*pipelines?.*\.ya?ml$ for manager azure-pipelines (repository=my-repo1)
DEBUG: Using file match: (^|/)batect(-bundle)?\.yml$ for manager batect (repository=my-repo1)
DEBUG: Using file match: (^|/)batect$ for manager batect-wrapper (repository=my-repo1)
DEBUG: Using file match: (^|/)WORKSPACE(|\.bazel)$ for manager bazel (repository=my-repo1)
DEBUG: Using file match: \.bzl$ for manager bazel (repository=my-repo1)
DEBUG: Using file match: (^|/)\.?bitbucket-pipelines\.ya?ml$ for manager bitbucket-pipelines (repository=my-repo1)
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite (repository=my-repo1)
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite (repository=my-repo1)
DEBUG: Using file match: (^|/)Gemfile$ for manager bundler (repository=my-repo1)
DEBUG: Using file match: \.cake$ for manager cake (repository=my-repo1)
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo (repository=my-repo1)
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci (repository=my-repo1)
DEBUG: Using file match: (^|/)cloudbuild.ya?ml for manager cloudbuild (repository=my-repo1)
DEBUG: Using file match: (^|/)Podfile$ for manager cocoapods (repository=my-repo1)
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer (repository=my-repo1)
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn (repository=my-repo1)
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose (repository=my-repo1)
DEBUG: Using file match: (^|/|\.)Dockerfile$ for manager dockerfile (repository=my-repo1)
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile (repository=my-repo1)
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci (repository=my-repo1)
DEBUG: Using file match: (^|/).gitmodules$ for manager git-submodules (repository=my-repo1)
DEBUG: Using file match: ^(workflow-templates|\.github\/workflows)\/[^/]+\.ya?ml$ for manager github-actions (repository=my-repo1)
DEBUG: Using file match: (^|\/)action\.ya?ml$ for manager github-actions (repository=my-repo1)
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci (repository=my-repo1)
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci-include (repository=my-repo1)
DEBUG: Using file match: (^|/)go.mod$ for manager gomod (repository=my-repo1)
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle (repository=my-repo1)
DEBUG: Using file match: (^|\/)gradle\.properties$ for manager gradle (repository=my-repo1)
DEBUG: Using file match: (^|\/)gradle\/.+\.toml$ for manager gradle (repository=my-repo1)
DEBUG: Using file match: \.versions\.toml$ for manager gradle (repository=my-repo1)
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper (repository=my-repo1)
DEBUG: Using file match: (^|/)requirements\.yaml$ for manager helm-requirements (repository=my-repo1)
DEBUG: Using file match: (^|/)values.yaml$ for manager helm-values (repository=my-repo1)
DEBUG: Using file match: (^|/)helmfile.yaml$ for manager helmfile (repository=my-repo1)
DEBUG: Using file match: (^|/)Chart.yaml$ for manager helmv3 (repository=my-repo1)
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew (repository=my-repo1)
DEBUG: Using file match: \.html?$ for manager html (repository=my-repo1)
DEBUG: Using file match: (^|/)plugins\.(txt|ya?ml)$ for manager jenkins (repository=my-repo1)
DEBUG: Using file match: (^|/)kustomization\.yaml for manager kustomize (repository=my-repo1)
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen (repository=my-repo1)
DEBUG: Using file match: \.pom\.xml$ for manager maven (repository=my-repo1)
DEBUG: Using file match: (^|/)pom\.xml$ for manager maven (repository=my-repo1)
DEBUG: Using file match: (^|/)package.js$ for manager meteor (repository=my-repo1)
DEBUG: Using file match: (^|/)mix\.exs$ for manager mix (repository=my-repo1)
DEBUG: Using file match: (^|/).node-version$ for manager nodenv (repository=my-repo1)
DEBUG: Using file match: (^|/)package.json$ for manager npm (repository=my-repo1)
DEBUG: Using file match: \.(?:cs|fs|vb)proj$ for manager nuget (repository=my-repo1)
DEBUG: Using file match: \.(?:props|targets)$ for manager nuget (repository=my-repo1)
DEBUG: Using file match: (^|\/)dotnet-tools\.json$ for manager nuget (repository=my-repo1)
DEBUG: Using file match: (^|\/)global\.json$ for manager nuget (repository=my-repo1)
DEBUG: Using file match: (^|/)\.nvmrc$ for manager nvm (repository=my-repo1)
DEBUG: Using file match: (^|/)([\w-]*)requirements\.(txt|pip)$ for manager pip_requirements (repository=my-repo1)
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup (repository=my-repo1)
DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv (repository=my-repo1)
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry (repository=my-repo1)
DEBUG: Using file match: (^|/)\.pre-commit-config\.yaml$ for manager pre-commit (repository=my-repo1)
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub (repository=my-repo1)
DEBUG: Using file match: (^|/).python-version$ for manager pyenv (repository=my-repo1)
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version (repository=my-repo1)
DEBUG: Using file match: \.sbt$ for manager sbt (repository=my-repo1)
DEBUG: Using file match: project/[^/]*.scala$ for manager sbt (repository=my-repo1)
DEBUG: Using file match: (^|/)setup\.cfg$ for manager setup-cfg (repository=my-repo1)
DEBUG: Using file match: (^|/)Package\.swift for manager swift (repository=my-repo1)
DEBUG: Using file match: \.tf$ for manager terraform (repository=my-repo1)
DEBUG: Using file match: (^|/)\.terraform-version$ for manager terraform-version (repository=my-repo1)
DEBUG: Using file match: (^|/)terragrunt\.hcl$ for manager terragrunt (repository=my-repo1)
DEBUG: Using file match: (^|/)\.terragrunt-version$ for manager terragrunt-version (repository=my-repo1)
DEBUG: Using file match: ^.travis.yml$ for manager travis (repository=my-repo1)
DEBUG: Matched 2 file(s) for manager docker-compose: control-plane-integration-tests/docker-compose.yml, deployments/docker/docker-compose.yml (repository=my-repo1)
DEBUG: Matched 2 file(s) for manager dockerfile: Dockerfile, control-plane-test-service/Dockerfile (repository=my-repo1)
DEBUG: Matched 2 file(s) for manager gomod: control-plane-service/go.mod, control-plane-test-service/go.mod (repository=my-repo1)
DEBUG: Matched 1 file(s) for manager helm-values: deployments/charts/control-plane/values.yaml (repository=my-repo1)
DEBUG: Matched 1 file(s) for manager helmv3: deployments/charts/control-plane/Chart.yaml (repository=my-repo1)
DEBUG: Matched 5 file(s) for manager maven: control-plane-documents/pom.xml, control-plane-integration-tests/pom.xml, control-plane-service/pom.xml, control-plane-test-service/pom.xml, pom.xml (repository=my-repo1)
DEBUG: docker-compose.extractPackageFile() (repository=my-repo1)
DEBUG: Chart has no dependencies (repository=my-repo1)
       "fileName": "deployments/charts/control-plane/Chart.yaml"
DEBUG: No multi-line match: 	github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/Microsoft/go-winio v0.5.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/Nvveen/Gotty v0.0.0-20120604004816-cd527374f1e5 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/armon/go-metrics v0.0.0-20180917152333-f0300d1749da // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/beorn7/perks v1.0.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/cenkalti/backoff/v3 v3.0.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/census-instrumentation/opencensus-proto v0.2.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/cespare/xxhash/v2 v2.1.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/cncf/udpa/go v0.0.0-20201120205902-5459f2c99403 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/codemodus/kace v0.5.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/containerd/continuity v0.0.0-20190827140505-75bee3e2ccb6 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/davecgh/go-spew v1.1.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/docker/go-connections v0.4.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/docker/go-units v0.4.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/envoyproxy/protoc-gen-validate v0.1.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/go-pg/zerochecker v0.2.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/go-stack/stack v1.8.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/golang/snappy v0.0.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/google/btree v1.0.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/errwrap v1.0.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/go-cleanhttp v0.5.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/go-immutable-radix v1.3.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/go-msgpack v0.5.3 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/go-multierror v1.1.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/go-retryablehttp v0.5.4 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/go-rootcerts v1.0.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/go-sockaddr v1.0.2 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/golang-lru v0.5.4 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/hcl v1.0.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/vault/api v1.0.4 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/hashicorp/vault/sdk v0.1.13 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/jinzhu/inflection v1.0.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/konsorten/go-windows-terminal-sequences v1.0.2 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/matttproud/golang_protobuf_extensions v1.0.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/miekg/dns v1.1.26 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/mitchellh/go-homedir v1.1.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/moby/term v0.0.0-20201216013528-df9cb8a40635 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/opencontainers/go-digest v1.0.0-rc1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/opencontainers/image-spec v1.0.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/opencontainers/runc v1.0.2 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/openzipkin/zipkin-go v0.2.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/pierrec/lz4 v2.0.5+incompatible // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/pmezard/go-difflib v1.0.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/prometheus/client_golang v1.5.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/prometheus/client_model v0.2.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/prometheus/common v0.9.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/prometheus/procfs v0.0.8 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/ryanuber/go-glob v1.0.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/sean-/seed v0.0.0-20170313163322-e2103e2c3529 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/segmentio/encoding v0.1.15 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/sirupsen/logrus v1.8.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/tidwall/match v1.1.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/tidwall/pretty v1.2.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/vmihailenco/bufpool v0.1.11 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/vmihailenco/msgpack/v4 v4.3.12 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/vmihailenco/tagparser v0.1.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	golang.org/x/net v0.0.0-20201224014010-6772e930b67b // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	golang.org/x/sys v0.0.0-20210426230700-d19ff857e887 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	golang.org/x/text v0.3.3 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	golang.org/x/time v0.0.0-20190308202827-9d24e82272b4 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	google.golang.org/appengine v1.6.6 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	gopkg.in/resty.v1 v1.12.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	gopkg.in/square/go-jose.v2 v2.3.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	gopkg.in/yaml.v2 v2.3.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	mellium.im/sasl v0.2.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/beorn7/perks v1.0.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/cespare/xxhash/v2 v2.1.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/dgrijalva/jwt-go v3.2.0+incompatible // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/go-errors/errors v1.0.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/go-stack/stack v1.8.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/google/uuid v1.1.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/gorilla/websocket v1.4.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/matttproud/golang_protobuf_extensions v1.0.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/openzipkin/zipkin-go v0.2.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/prometheus/client_golang v1.5.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/prometheus/client_model v0.2.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/prometheus/common v0.9.1 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	github.com/prometheus/procfs v0.0.8 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	golang.org/x/net v0.0.0-20190628185345-da137c7871d7 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	golang.org/x/sys v0.0.0-20200122134326-e047566fdf82 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	golang.org/x/text v0.3.2 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	gopkg.in/resty.v1 v1.12.0 // indirect (repository=my-repo1)
DEBUG: No multi-line match: 	gopkg.in/yaml.v2 v2.2.5 // indirect (repository=my-repo1)
DEBUG: docker-compose.extractPackageFile() (repository=my-repo1)
DEBUG: Found docker-compose package files (repository=my-repo1)
DEBUG: Found dockerfile package files (repository=my-repo1)
DEBUG: Found gomod package files (repository=my-repo1)
DEBUG: Found maven package files (repository=my-repo1)
DEBUG: Found 11 package file(s) (repository=my-repo1)
 INFO: Dependency extraction complete (repository=my-repo1)
       "baseBranch": "master",
       "stats": {
         "managers": {
           "docker-compose": {"fileCount": 2, "depCount": 2},
           "dockerfile": {"fileCount": 2, "depCount": 2},
           "gomod": {"fileCount": 2, "depCount": 32},
           "maven": {"fileCount": 5, "depCount": 31}
         },
         "total": {"fileCount": 11, "depCount": 67}
       }
DEBUG: Dependency nexus.cloud-lab.cf:17004/cloud-core/control-plane-assembly-master has unsupported value build23 (repository=my-repo1)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.openapitools:openapi-generator-maven-plugin)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.apache.httpcomponents:httpclient)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=com.company.cloud.junit.cloudcore:cloud-core-extension)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.hamcrest:hamcrest)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.junit.jupiter:junit-jupiter-engine)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=commons-io:commons-io)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=com.igormaznitsa:mvn-golang-wrapper)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=com.company.cloud.core:control-plane)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=com.igormaznitsa:mvn-golang-wrapper)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=io.fabric8:docker-maven-plugin)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.apache.commons:commons-lang3)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.kohsuke:wordnet-random-name)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.springframework:spring-websocket)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.springframework:spring-messaging)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=io.undertow:undertow-websockets-jsr)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=com.fasterxml.jackson.core:jackson-databind)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=ch.qos.logback:logback-classic)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.projectlombok:lombok)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=com.company.cloud.core:id-generator-java-impl)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=com.google.code.gson:gson)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.assertj:assertj-core)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=io.grpc:grpc-netty-shaded)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=io.grpc:grpc-protobuf)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=io.grpc:grpc-stub)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=kr.motd.maven:os-maven-plugin)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.springframework.boot:spring-boot-maven-plugin)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.apache.maven.plugins:maven-surefire-plugin)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.junit.platform:junit-platform-surefire-provider)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.apache.maven.plugins:maven-antrun-plugin)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=ant:ant-junit)
DEBUG: Dependency is disabled (repository=my-repo1, dependency=org.xolstice.maven.plugins:protobuf-maven-plugin)
DEBUG: getLabels(https://artifactorycn.company.com:17003, general/alpine-base-image, 3.14-b01) (repository=my-repo1)
DEBUG: getManifestResponse(https://artifactorycn.company.com:17003, general/alpine-base-image, 3.14-b01) (repository=my-repo1)
DEBUG: Retrying Tags for https://artifactorycn.company.com:17064/alpine using library/ prefix (repository=my-repo1)
DEBUG: Go lookup source url (repository=my-repo1)
       "goModule": "git.company.com/prod.platform.cloud_core/go-stomp-websocket",
       "goSourceUrl": "https://git.company.com/prod.platform.cloud_core/go-stomp-websocket"
DEBUG: getLabels(https://artifactorycn.company.com:17064, alpine, latest) (repository=my-repo1)
DEBUG: getManifestResponse(https://artifactorycn.company.com:17064, alpine, latest) (repository=my-repo1)
DEBUG: getManifestResponse(https://artifactorycn.company.com:17064, alpine, sha256:69704ef328d05a9f806b6b8502915e6a0a4faa4d72018dc42343f511490daf8a) (repository=my-repo1)
DEBUG: Failed to look up dependency google.golang.org/genproto (repository=my-repo1, packageFile=control-plane-service/go.mod, dependency=google.golang.org/genproto)
DEBUG: Go lookup source url (repository=my-repo1)
       "goModule": "git.company.com/prod.platform.cloud_core/go-microservice-core",
       "goSourceUrl": "https://git.company.com/prod.platform.cloud_core/go-microservice-core"
DEBUG: Goproxy error: trying next URL provided with GOPROXY (repository=my-repo1)
       "err": {
         "name": "RequestError",
         "code": "ECONNRESET",
         "timings": {
           "start": 1636719080763,
           "socket": 1636719080763,
           "lookup": 1636719080780,
           "connect": 1636719080808,
           "error": 1636719080842,
           "phases": {"wait": 0, "dns": 17, "tcp": 28, "total": 79}
         },
         "message": "read ECONNRESET",
         "stack": "RequestError: read ECONNRESET\n    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:956:111)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:412:35)\n    at ClientRequest.emit (domain.js:475:12)\n    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/29.6.0 (https://github.com/renovatebot/renovate)",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://google.golang.org/protobuf?go-get=1",
           "hostType": "go",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         }
       }
DEBUG: Failed to look up dependency google.golang.org/protobuf (repository=my-repo1, packageFile=control-plane-test-service/go.mod, dependency=google.golang.org/protobuf)
DEBUG: Failed to look up dependency google.golang.org/protobuf (repository=my-repo1, packageFile=control-plane-service/go.mod, dependency=google.golang.org/protobuf)
DEBUG: Goproxy error: trying next URL provided with GOPROXY (repository=my-repo1)
       "err": {
         "name": "RequestError",
         "code": "ECONNRESET",
         "timings": {
           "start": 1636719081887,
           "socket": 1636719081887,
           "lookup": 1636719081892,
           "connect": 1636719081922,
           "error": 1636719081958,
           "phases": {"wait": 0, "dns": 5, "tcp": 30, "total": 71}
         },
         "message": "read ECONNRESET",
         "stack": "RequestError: read ECONNRESET\n    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:956:111)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:412:35)\n    at ClientRequest.emit (domain.js:475:12)\n    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/29.6.0 (https://github.com/renovatebot/renovate)",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://google.golang.org/grpc?go-get=1",
           "hostType": "go",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         }
       }
DEBUG: Failed to look up dependency google.golang.org/grpc (repository=my-repo1, packageFile=control-plane-test-service/go.mod, dependency=google.golang.org/grpc)
DEBUG: Failed to look up dependency google.golang.org/grpc (repository=my-repo1, packageFile=control-plane-service/go.mod, dependency=google.golang.org/grpc)
DEBUG: Package releases lookups complete (repository=my-repo1)
       "baseBranch": "master"
DEBUG: branchifyUpgrades (repository=my-repo1)
DEBUG: 2 flattened updates found: github.com/envoyproxy/go-control-plane, github.com/mustafaturan/bus (repository=my-repo1)
DEBUG: Returning 2 branch(es) (repository=my-repo1)
DEBUG: Fetching changelog: https://github.com/envoyproxy/go-control-plane (v0.9.8 -> v0.10.0) (repository=my-repo1)
DEBUG: Fetching changelog: https://github.com/mustafaturan/bus (v0.1.3 -> v1.0.2) (repository=my-repo1)
 WARN: No github.com token has been configured. Skipping release notes retrieval (repository=my-repo1)
       "manager": "gomod",
       "depName": "github.com/envoyproxy/go-control-plane",
       "sourceUrl": "https://github.com/envoyproxy/go-control-plane"
 WARN: No github.com token has been configured. Skipping release notes retrieval (repository=my-repo1)
       "manager": "gomod",
       "depName": "github.com/mustafaturan/bus",
       "sourceUrl": "https://github.com/mustafaturan/bus"
DEBUG: config.repoIsOnboarded=true (repository=my-repo1)
DEBUG: packageFiles with updates (repository=my-repo1)
       "config": {
         "docker-compose": [
           {
             "packageFile": "control-plane-integration-tests/docker-compose.yml",
             "deps": [
               {
                 "depName": "artifactorycn.company.com:17064/ajoergensen/openssh-server",
                 "replaceString": "artifactorycn.company.com:17064/ajoergensen/openssh-server",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "docker",
                 "skipReason": "invalid-value"
               }
             ]
           },
           {
             "packageFile": "deployments/docker/docker-compose.yml",
             "deps": [
               {
                 "depName": "nexus.cloud-lab.cf:17004/cloud-core/control-plane-assembly-master",
                 "currentValue": "build23",
                 "replaceString": "nexus.cloud-lab.cf:17004/cloud-core/control-plane-assembly-master:build23",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "docker",
                 "skipReason": "invalid-value"
               }
             ]
           }
         ],
         "dockerfile": [
           {
             "packageFile": "Dockerfile",
             "deps": [
               {
                 "depName": "artifactorycn.company.com:17003/general/alpine-base-image",
                 "currentValue": "3.14-b01",
                 "replaceString": "artifactorycn.company.com:17003/general/alpine-base-image:3.14-b01",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "final",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "docker",
                 "currentVersion": "3.14",
                 "fixedVersion": "3.14-b01"
               }
             ]
           },
           {
             "packageFile": "control-plane-test-service/Dockerfile",
             "deps": [
               {
                 "depName": "artifactorycn.company.com:17064/alpine",
                 "currentValue": "3.14",
                 "replaceString": "artifactorycn.company.com:17064/alpine:3.14",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "final",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "docker",
                 "currentVersion": "3.14",
                 "fixedVersion": "3.14"
               }
             ]
           }
         ],
         "gomod": [
           {
             "packageFile": "control-plane-service/go.mod",
             "constraints": {"go": "^1.17"},
             "deps": [
               {
                 "managerData": {"lineNumber": 5, "multiLine": true},
                 "depName": "git.company.com/prod.platform.cloud_core/go-microservice-core",
                 "depType": "require",
                 "currentValue": "v1.10.8",
                 "datasource": "go",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://git.company.com/prod.platform.cloud_core/go-microservice-core",
                 "currentVersion": "v1.10.8",
                 "fixedVersion": "v1.10.8"
               },
               {
                 "managerData": {"lineNumber": 6, "multiLine": true},
                 "depName": "git.company.com/prod.platform.cloud_core/go-stomp-websocket",
                 "depType": "require",
                 "currentValue": "v1.0.3",
                 "datasource": "go",
                 "depIndex": 1,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://git.company.com/prod.platform.cloud_core/go-stomp-websocket",
                 "currentVersion": "v1.0.3",
                 "fixedVersion": "v1.0.3"
               },
               {
                 "managerData": {"lineNumber": 7, "multiLine": true},
                 "depName": "github.com/dgrijalva/jwt-go",
                 "depType": "require",
                 "currentValue": "v3.2.0+incompatible",
                 "datasource": "go",
                 "depIndex": 2,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/dgrijalva/jwt-go",
                 "currentVersion": "v3.2.0+incompatible",
                 "fixedVersion": "v3.2.0+incompatible"
               },
               {
                 "managerData": {"lineNumber": 8, "multiLine": true},
                 "depName": "github.com/envoyproxy/go-control-plane",
                 "depType": "require",
                 "currentValue": "v0.9.8",
                 "datasource": "go",
                 "depIndex": 3,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "v0.10.0",
                     "newValue": "v0.10.0",
                     "releaseTimestamp": "2021-10-28T20:49:26.000Z",
                     "newMajor": 0,
                     "newMinor": 10,
                     "updateType": "minor",
                     "branchName": "renovate/github.com-envoyproxy-go-control-plane-0.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/envoyproxy/go-control-plane",
                 "currentVersion": "v0.9.8",
                 "isSingleVersion": true,
                 "fixedVersion": "v0.9.8"
               },
               {
                 "managerData": {"lineNumber": 9, "multiLine": true},
                 "depName": "github.com/ghodss/yaml",
                 "depType": "require",
                 "currentValue": "v1.0.0",
                 "datasource": "go",
                 "depIndex": 4,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/ghodss/yaml",
                 "currentVersion": "v1.0.0",
                 "fixedVersion": "v1.0.0"
               },
               {
                 "managerData": {"lineNumber": 10, "multiLine": true},
                 "depName": "github.com/go-errors/errors",
                 "depType": "require",
                 "currentValue": "v1.4.1",
                 "datasource": "go",
                 "depIndex": 5,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/go-errors/errors",
                 "currentVersion": "v1.4.1",
                 "fixedVersion": "v1.4.1"
               },
               {
                 "managerData": {"lineNumber": 11, "multiLine": true},
                 "depName": "github.com/go-pg/migrations/v7",
                 "depType": "require",
                 "currentValue": "v7.1.11",
                 "datasource": "go",
                 "depIndex": 6,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/go-pg/migrations",
                 "currentVersion": "v7.1.11",
                 "fixedVersion": "v7.1.11"
               },
               {
                 "managerData": {"lineNumber": 12, "multiLine": true},
                 "depName": "github.com/go-pg/pg/v9",
                 "depType": "require",
                 "currentValue": "v9.2.1",
                 "datasource": "go",
                 "depIndex": 7,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/go-pg/pg",
                 "currentVersion": "v9.2.1",
                 "fixedVersion": "v9.2.1"
               },
               {
                 "managerData": {"lineNumber": 13, "multiLine": true},
                 "depName": "github.com/golang/protobuf",
                 "depType": "require",
                 "currentValue": "v1.5.2",
                 "datasource": "go",
                 "depIndex": 8,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/golang/protobuf",
                 "currentVersion": "v1.5.2",
                 "fixedVersion": "v1.5.2"
               },
               {
                 "managerData": {"lineNumber": 14, "multiLine": true},
                 "depName": "github.com/google/uuid",
                 "depType": "require",
                 "currentValue": "v1.3.0",
                 "datasource": "go",
                 "depIndex": 9,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/google/uuid",
                 "currentVersion": "v1.3.0",
                 "fixedVersion": "v1.3.0"
               },
               {
                 "managerData": {"lineNumber": 15, "multiLine": true},
                 "depName": "github.com/gorilla/mux",
                 "depType": "require",
                 "currentValue": "v1.8.0",
                 "datasource": "go",
                 "depIndex": 10,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/gorilla/mux",
                 "currentVersion": "v1.8.0",
                 "fixedVersion": "v1.8.0"
               },
               {
                 "managerData": {"lineNumber": 16, "multiLine": true},
                 "depName": "github.com/gorilla/websocket",
                 "depType": "require",
                 "currentValue": "v1.4.2",
                 "datasource": "go",
                 "depIndex": 11,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/gorilla/websocket",
                 "currentVersion": "v1.4.2",
                 "fixedVersion": "v1.4.2"
               },
               {
                 "managerData": {"lineNumber": 17, "multiLine": true},
                 "depName": "github.com/hashicorp/go-memdb",
                 "depType": "require",
                 "currentValue": "v1.3.2",
                 "datasource": "go",
                 "depIndex": 12,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/hashicorp/go-memdb",
                 "currentVersion": "v1.3.2",
                 "fixedVersion": "v1.3.2"
               },
               {
                 "managerData": {"lineNumber": 18, "multiLine": true},
                 "depName": "github.com/hashicorp/go-uuid",
                 "depType": "require",
                 "currentValue": "v1.0.2",
                 "datasource": "go",
                 "depIndex": 13,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/hashicorp/go-uuid",
                 "currentVersion": "v1.0.2",
                 "fixedVersion": "v1.0.2"
               },
               {
                 "managerData": {"lineNumber": 19, "multiLine": true},
                 "depName": "github.com/hashicorp/memberlist",
                 "depType": "require",
                 "currentValue": "v0.2.4",
                 "datasource": "go",
                 "depIndex": 14,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/hashicorp/memberlist",
                 "currentVersion": "v0.2.4",
                 "fixedVersion": "v0.2.4"
               },
               {
                 "managerData": {"lineNumber": 20, "multiLine": true},
                 "depName": "github.com/hashicorp/serf",
                 "depType": "require",
                 "currentValue": "v0.9.5",
                 "datasource": "go",
                 "depIndex": 15,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/hashicorp/serf",
                 "currentVersion": "v0.9.5",
                 "fixedVersion": "v0.9.5"
               },
               {
                 "managerData": {"lineNumber": 21, "multiLine": true},
                 "depName": "github.com/mitchellh/mapstructure",
                 "depType": "require",
                 "currentValue": "v1.4.2",
                 "datasource": "go",
                 "depIndex": 16,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/mitchellh/mapstructure",
                 "currentVersion": "v1.4.2",
                 "fixedVersion": "v1.4.2"
               },
               {
                 "managerData": {"lineNumber": 22, "multiLine": true},
                 "depName": "github.com/mustafaturan/bus",
                 "depType": "require",
                 "currentValue": "v0.1.3",
                 "datasource": "go",
                 "depIndex": 17,
                 "updates": [
                   {
                     "bucket": "major",
                     "newVersion": "v1.0.2",
                     "newValue": "v1.0.2",
                     "releaseTimestamp": "2020-02-05T08:31:44.000Z",
                     "newMajor": 1,
                     "newMinor": 0,
                     "updateType": "major",
                     "branchName": "renovate/github.com-mustafaturan-bus-1.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/mustafaturan/bus",
                 "currentVersion": "v0.1.3",
                 "isSingleVersion": true,
                 "fixedVersion": "v0.1.3"
               },
               {
                 "managerData": {"lineNumber": 23, "multiLine": true},
                 "depName": "github.com/mustafaturan/monoton",
                 "depType": "require",
                 "currentValue": "v1.0.0",
                 "datasource": "go",
                 "depIndex": 18,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/mustafaturan/monoton",
                 "currentVersion": "v1.0.0",
                 "fixedVersion": "v1.0.0"
               },
               {
                 "managerData": {"lineNumber": 24, "multiLine": true},
                 "depName": "github.com/ory/dockertest/v3",
                 "depType": "require",
                 "currentValue": "v3.8.0",
                 "datasource": "go",
                 "depIndex": 19,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/ory/dockertest",
                 "currentVersion": "v3.8.0",
                 "fixedVersion": "v3.8.0"
               },
               {
                 "managerData": {"lineNumber": 25, "multiLine": true},
                 "depName": "github.com/pkg/errors",
                 "depType": "require",
                 "currentValue": "v0.9.1",
                 "datasource": "go",
                 "depIndex": 20,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/pkg/errors",
                 "currentVersion": "v0.9.1",
                 "fixedVersion": "v0.9.1"
               },
               {
                 "managerData": {"lineNumber": 26, "multiLine": true},
                 "depName": "github.com/stretchr/testify",
                 "depType": "require",
                 "currentValue": "v1.7.0",
                 "datasource": "go",
                 "depIndex": 21,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/stretchr/testify",
                 "currentVersion": "v1.7.0",
                 "fixedVersion": "v1.7.0"
               },
               {
                 "managerData": {"lineNumber": 27, "multiLine": true},
                 "depName": "github.com/tidwall/gjson",
                 "depType": "require",
                 "currentValue": "v1.11.0",
                 "datasource": "go",
                 "depIndex": 22,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/tidwall/gjson",
                 "currentVersion": "v1.11.0",
                 "fixedVersion": "v1.11.0"
               },
               {
                 "managerData": {"lineNumber": 28, "multiLine": true},
                 "depName": "google.golang.org/genproto",
                 "depType": "require",
                 "currentValue": "v0.0.0-20200526211855-cb27e3aa2013",
                 "datasource": "go",
                 "currentDigest": "cb27e3aa2013",
                 "digestOneAndOnly": true,
                 "depIndex": 23,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "google.golang.org/genproto",
                     "message": "Failed to look up dependency google.golang.org/genproto"
                   }
                 ],
                 "versioning": "semver"
               },
               {
                 "managerData": {"lineNumber": 29, "multiLine": true},
                 "depName": "google.golang.org/grpc",
                 "depType": "require",
                 "currentValue": "v1.32.0",
                 "datasource": "go",
                 "depIndex": 24,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "google.golang.org/grpc",
                     "message": "Failed to look up dependency google.golang.org/grpc"
                   }
                 ],
                 "versioning": "semver"
               },
               {
                 "managerData": {"lineNumber": 30, "multiLine": true},
                 "depName": "google.golang.org/protobuf",
                 "depType": "require",
                 "currentValue": "v1.27.1",
                 "datasource": "go",
                 "depIndex": 25,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "google.golang.org/protobuf",
                     "message": "Failed to look up dependency google.golang.org/protobuf"
                   }
                 ],
                 "versioning": "semver"
               }
             ]
           },
           {
             "packageFile": "control-plane-test-service/go.mod",
             "constraints": {"go": "^1.17"},
             "deps": [
               {
                 "managerData": {"lineNumber": 5, "multiLine": true},
                 "depName": "git.company.com/prod.platform.cloud_core/go-microservice-core",
                 "depType": "require",
                 "currentValue": "v1.10.8",
                 "datasource": "go",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://git.company.com/prod.platform.cloud_core/go-microservice-core",
                 "currentVersion": "v1.10.8",
                 "fixedVersion": "v1.10.8"
               },
               {
                 "managerData": {"lineNumber": 6, "multiLine": true},
                 "depName": "github.com/golang/protobuf",
                 "depType": "require",
                 "currentValue": "v1.5.2",
                 "datasource": "go",
                 "depIndex": 1,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/golang/protobuf",
                 "currentVersion": "v1.5.2",
                 "fixedVersion": "v1.5.2"
               },
               {
                 "managerData": {"lineNumber": 7, "multiLine": true},
                 "depName": "github.com/gorilla/mux",
                 "depType": "require",
                 "currentValue": "v1.8.0",
                 "datasource": "go",
                 "depIndex": 2,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/gorilla/mux",
                 "currentVersion": "v1.8.0",
                 "fixedVersion": "v1.8.0"
               },
               {
                 "managerData": {"lineNumber": 8, "multiLine": true},
                 "depName": "github.com/pkg/errors",
                 "depType": "require",
                 "currentValue": "v0.9.1",
                 "datasource": "go",
                 "depIndex": 3,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://github.com/pkg/errors",
                 "currentVersion": "v0.9.1",
                 "fixedVersion": "v0.9.1"
               },
               {
                 "managerData": {"lineNumber": 9, "multiLine": true},
                 "depName": "google.golang.org/grpc",
                 "depType": "require",
                 "currentValue": "v1.32.0",
                 "datasource": "go",
                 "depIndex": 4,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "google.golang.org/grpc",
                     "message": "Failed to look up dependency google.golang.org/grpc"
                   }
                 ],
                 "versioning": "semver"
               },
               {
                 "managerData": {"lineNumber": 10, "multiLine": true},
                 "depName": "google.golang.org/protobuf",
                 "depType": "require",
                 "currentValue": "v1.27.1",
                 "datasource": "go",
                 "depIndex": 5,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "google.golang.org/protobuf",
                     "message": "Failed to look up dependency google.golang.org/protobuf"
                   }
                 ],
                 "versioning": "semver"
               }
             ]
           }
         ],
         "maven": [
           {
             "datasource": "maven",
             "packageFile": "control-plane-documents/pom.xml",
             "deps": [
               {
                 "datasource": "maven",
                 "depName": "org.openapitools:openapi-generator-maven-plugin",
                 "currentValue": "4.3.1",
                 "fileReplacePosition": 713,
                 "registryUrls": ["https://repo.maven.apache.org/maven2"],
                 "depIndex": 0,
                 "updates": [],
                 "skipReason": "disabled"
               }
             ]
           },
           {
             "datasource": "maven",
             "packageFile": "control-plane-integration-tests/pom.xml",
             "deps": [
               {
                 "datasource": "maven",
                 "depName": "org.apache.httpcomponents:httpclient",
                 "currentValue": "4.5",
                 "fileReplacePosition": 835,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 0,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "com.company.cloud.junit.cloudcore:cloud-core-extension",
                 "currentValue": "2.0.1",
                 "fileReplacePosition": 1039,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 1,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.hamcrest:hamcrest",
                 "currentValue": "2.2",
                 "fileReplacePosition": 1242,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 2,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.junit.jupiter:junit-jupiter-engine",
                 "currentValue": "5.7.2",
                 "fileReplacePosition": 1460,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 3,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "commons-io:commons-io",
                 "currentValue": "2.5",
                 "fileReplacePosition": 1663,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 4,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.apache.commons:commons-lang3",
                 "currentValue": "3.12.0",
                 "fileReplacePosition": 1843,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 5,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.kohsuke:wordnet-random-name",
                 "currentValue": "1.3",
                 "fileReplacePosition": 2025,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 6,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.springframework:spring-websocket",
                 "currentValue": "5.1.5.RELEASE",
                 "fileReplacePosition": 2240,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 7,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.springframework:spring-messaging",
                 "currentValue": "5.1.5.RELEASE",
                 "fileReplacePosition": 2465,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 8,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "io.undertow:undertow-websockets-jsr",
                 "currentValue": "2.2.5.Final",
                 "fileReplacePosition": 2988,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 9,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "com.fasterxml.jackson.core:jackson-databind",
                 "currentValue": "2.9.8",
                 "fileReplacePosition": 3404,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 10,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "ch.qos.logback:logback-classic",
                 "currentValue": "1.0.13",
                 "fileReplacePosition": 3615,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 11,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.projectlombok:lombok",
                 "currentValue": "1.18.12",
                 "fileReplacePosition": 3789,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 12,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "com.company.cloud.core:id-generator-java-impl",
                 "currentValue": "1.0.0",
                 "fileReplacePosition": 3989,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 13,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "com.google.code.gson:gson",
                 "currentValue": "2.8.0",
                 "fileReplacePosition": 4195,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 14,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.assertj:assertj-core",
                 "currentValue": "3.11.1",
                 "fileReplacePosition": 4400,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 15,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "io.grpc:grpc-netty-shaded",
                 "currentValue": "1.41.0",
                 "fileReplacePosition": 4643,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 16,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "io.grpc:grpc-protobuf",
                 "currentValue": "1.41.0",
                 "fileReplacePosition": 4846,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 17,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "io.grpc:grpc-stub",
                 "currentValue": "1.41.0",
                 "fileReplacePosition": 5045,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depType": "test",
                 "depIndex": 18,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "kr.motd.maven:os-maven-plugin",
                 "currentValue": "1.6.2",
                 "fileReplacePosition": 5325,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 19,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.springframework.boot:spring-boot-maven-plugin",
                 "currentValue": "2.1.6.RELEASE",
                 "fileReplacePosition": 5578,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 20,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.apache.maven.plugins:maven-surefire-plugin",
                 "currentValue": "2.22.2",
                 "fileReplacePosition": 5896,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 21,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.junit.platform:junit-platform-surefire-provider",
                 "currentValue": "1.3.2",
                 "fileReplacePosition": 6454,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 22,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.apache.maven.plugins:maven-antrun-plugin",
                 "currentValue": "1.8",
                 "fileReplacePosition": 6665,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 23,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "ant:ant-junit",
                 "currentValue": "1.6.2",
                 "fileReplacePosition": 7822,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 24,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "org.xolstice.maven.plugins:protobuf-maven-plugin",
                 "currentValue": "0.6.1",
                 "fileReplacePosition": 8098,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://artifactorycn.company.com/pd.saas-release.mvn.group",
                   "https://artifactorycn.company.com/pd.saas.mvn.group"
                 ],
                 "depIndex": 25,
                 "updates": [],
                 "skipReason": "disabled"
               }
             ]
           },
           {
             "datasource": "maven",
             "packageFile": "control-plane-service/pom.xml",
             "deps": [
               {
                 "datasource": "maven",
                 "depName": "com.igormaznitsa:mvn-golang-wrapper",
                 "currentValue": "2.3.8",
                 "fileReplacePosition": 1471,
                 "registryUrls": ["https://repo.maven.apache.org/maven2"],
                 "depIndex": 0,
                 "updates": [],
                 "skipReason": "disabled"
               }
             ]
           },
           {
             "datasource": "maven",
             "packageFile": "control-plane-test-service/pom.xml",
             "deps": [
               {
                 "datasource": "maven",
                 "depName": "com.company.cloud.core:control-plane",
                 "currentValue": "1.0-SNAPSHOT",
                 "fileReplacePosition": 392,
                 "registryUrls": ["https://repo.maven.apache.org/maven2"],
                 "depIndex": 0,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "com.igormaznitsa:mvn-golang-wrapper",
                 "currentValue": "2.3.8",
                 "fileReplacePosition": 1201,
                 "registryUrls": ["https://repo.maven.apache.org/maven2"],
                 "depIndex": 1,
                 "updates": [],
                 "skipReason": "disabled"
               },
               {
                 "datasource": "maven",
                 "depName": "io.fabric8:docker-maven-plugin",
                 "currentValue": "0.34.1",
                 "fileReplacePosition": 2874,
                 "registryUrls": ["https://repo.maven.apache.org/maven2"],
                 "depIndex": 2,
                 "updates": [],
                 "skipReason": "disabled"
               }
             ],
             "parent": "pom.xml"
           },
           {"datasource": "maven", "packageFile": "pom.xml", "deps": []}
         ]
       }
DEBUG: processRepo() (repository=my-repo1)
DEBUG: Processing 2 branches: renovate/github.com-envoyproxy-go-control-plane-0.x, renovate/github.com-mustafaturan-bus-1.x (repository=my-repo1)
DEBUG: Calculating prConcurrentLimit (20) (repository=my-repo1)
DEBUG: getBranchPr(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1)
DEBUG: findPr(renovate/github.com-envoyproxy-go-control-plane-0.x, undefined, open) (repository=my-repo1)
DEBUG: getPr(964) (repository=my-repo1)
DEBUG: getMR(964) (repository=my-repo1)
DEBUG: getBranchStatus(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1)
DEBUG: Got res with 2 results (repository=my-repo1)
DEBUG: getBranchPr(renovate/github.com-mustafaturan-bus-1.x) (repository=my-repo1)
DEBUG: findPr(renovate/github.com-mustafaturan-bus-1.x, undefined, open) (repository=my-repo1)
DEBUG: getPr(975) (repository=my-repo1)
DEBUG: getMR(975) (repository=my-repo1)
DEBUG: getBranchStatus(renovate/github.com-mustafaturan-bus-1.x) (repository=my-repo1)
DEBUG: Got res with 1 results (repository=my-repo1)
DEBUG: 2 PRs are currently open (repository=my-repo1)
DEBUG: PR concurrent limit remaining: 18 (repository=my-repo1)
DEBUG: Calculated maximum PRs remaining this run (repository=my-repo1)
       "prsRemaining": 18
DEBUG: PullRequests limit = 18 (repository=my-repo1)
DEBUG: Calculating branchConcurrentLimit (20) (repository=my-repo1)
DEBUG: 2 already existing branches found: renovate/github.com-envoyproxy-go-control-plane-0.x,renovate/github.com-mustafaturan-bus-1.x (repository=my-repo1)
DEBUG: Branch concurrent limit remaining: 18 (repository=my-repo1)
DEBUG: Calculated maximum branches remaining this run (repository=my-repo1)
       "branchesRemaining": 18
DEBUG: Branches limit = 18 (repository=my-repo1)
DEBUG: Setting current branch to master (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: latest commit (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
       "branchName": "master",
       "latestCommitDate": "2021-11-12T06:58:57-05:00"
DEBUG: getBranchPr(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: findPr(renovate/github.com-envoyproxy-go-control-plane-0.x, undefined, open) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getPr(964) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getMR(964) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getBranchStatus(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Got res with 2 results (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: branchExists=true (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: dependencyDashboardCheck=undefined (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: PR rebase requested=false (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Checking if PR has been edited (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Found existing branch PR (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Checking schedule(at any time, null) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: No schedule defined (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Branch already exists (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getBranchPr(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: findPr(renovate/github.com-envoyproxy-go-control-plane-0.x, undefined, open) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getPr(964) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getMR(964) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getBranchStatus(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Got res with 2 results (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: isBranchStale=false (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
       "isStale": false,
       "currentBranch": "master",
       "currentBranchSha": "1fc43238d16d0ebed592f3b1267b7de142946c50"
DEBUG: Branch is up-to-date (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Branch does not need rebasing (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Using reuseExistingBranch: true (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=true (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: gomod.updateDependency: v0.10.0 (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: No changes necessary (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: No package files need updating (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: No updated lock files in branch (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: No files to commit (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Checking if we can automerge branch (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: mergeStatus=no automerge (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Ensuring PR (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: There are 0 errors and 0 warnings (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getBranchPr(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: findPr(renovate/github.com-envoyproxy-go-control-plane-0.x, undefined, open) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getPr(964) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getMR(964) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getBranchStatus(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Got res with 2 results (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Found existing PR (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: resolveBranchStatus(branchName=renovate/github.com-envoyproxy-go-control-plane-0.x, ignoreTests=false) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: getBranchStatus(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Got res with 2 results (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Branch status red (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: GitLab versions earlier than 13.4 have issues with long descriptions, truncating to 25K characters (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
       "version": "13.3.5"
DEBUG: Processing existing PR (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: Merge Request #964 does not need updating (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: PR is configured for automerge (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
DEBUG: PR is not ready for merge (repository=my-repo1, branch=renovate/github.com-envoyproxy-go-control-plane-0.x)
       "canMergeReason": undefined
DEBUG: Setting current branch to master (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: latest commit (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
       "branchName": "master",
       "latestCommitDate": "2021-11-12T06:58:57-05:00"
DEBUG: getBranchPr(renovate/github.com-mustafaturan-bus-1.x) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: findPr(renovate/github.com-mustafaturan-bus-1.x, undefined, open) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getPr(975) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getMR(975) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getBranchStatus(renovate/github.com-mustafaturan-bus-1.x) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Got res with 1 results (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: branchExists=true (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: dependencyDashboardCheck=undefined (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: PR rebase requested=false (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Checking if PR has been edited (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Found existing branch PR (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Checking schedule(at any time, null) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: No schedule defined (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Branch already exists (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getBranchPr(renovate/github.com-mustafaturan-bus-1.x) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: findPr(renovate/github.com-mustafaturan-bus-1.x, undefined, open) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getPr(975) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getMR(975) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getBranchStatus(renovate/github.com-mustafaturan-bus-1.x) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Got res with 1 results (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: isBranchStale=false (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
       "isStale": false,
       "currentBranch": "master",
       "currentBranchSha": "1fc43238d16d0ebed592f3b1267b7de142946c50"
DEBUG: Branch is up-to-date (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Branch does not need rebasing (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Using reuseExistingBranch: true (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=true (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: gomod.updateDependency: v1.0.2 (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: gomod: major update (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
       "depName": "github.com/mustafaturan/bus"
DEBUG: No changes necessary (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: No package files need updating (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: No updated lock files in branch (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: No files to commit (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Checking if we can automerge branch (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: mergeStatus=no automerge (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Ensuring PR (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: There are 0 errors and 0 warnings (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getBranchPr(renovate/github.com-mustafaturan-bus-1.x) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: findPr(renovate/github.com-mustafaturan-bus-1.x, undefined, open) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getPr(975) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getMR(975) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getBranchStatus(renovate/github.com-mustafaturan-bus-1.x) (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Got res with 1 results (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Found existing PR (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: GitLab versions earlier than 13.4 have issues with long descriptions, truncating to 25K characters (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
       "version": "13.3.5"
DEBUG: Processing existing PR (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: Merge Request #975 does not need updating (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: PR is not configured for automerge (repository=my-repo1, branch=renovate/github.com-mustafaturan-bus-1.x)
DEBUG: getBranchPr(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1)
DEBUG: findPr(renovate/github.com-envoyproxy-go-control-plane-0.x, undefined, open) (repository=my-repo1)
DEBUG: getPr(964) (repository=my-repo1)
DEBUG: getMR(964) (repository=my-repo1)
DEBUG: getBranchStatus(renovate/github.com-envoyproxy-go-control-plane-0.x) (repository=my-repo1)
DEBUG: Got res with 2 results (repository=my-repo1)
DEBUG: getBranchPr(renovate/github.com-mustafaturan-bus-1.x) (repository=my-repo1)
DEBUG: findPr(renovate/github.com-mustafaturan-bus-1.x, undefined, open) (repository=my-repo1)
DEBUG: getPr(975) (repository=my-repo1)
DEBUG: getMR(975) (repository=my-repo1)
DEBUG: getBranchStatus(renovate/github.com-mustafaturan-bus-1.x) (repository=my-repo1)
DEBUG: Got res with 1 results (repository=my-repo1)
DEBUG: Ensuring Dependency Dashboard (repository=my-repo1)
DEBUG: ensureIssue() (repository=my-repo1)
DEBUG: GitLab versions earlier than 13.4 have issues with long descriptions, truncating to 25K characters (repository=my-repo1)
       "version": "13.3.5"
DEBUG: Updating issue (repository=my-repo1)
DEBUG: Removing any stale branches (repository=my-repo1)
DEBUG: config.repoIsOnboarded=true (repository=my-repo1)
DEBUG: Branch lists (repository=my-repo1)
       "branchList": [
         "renovate/github.com-envoyproxy-go-control-plane-0.x",
         "renovate/github.com-mustafaturan-bus-1.x"
       ],
       "renovateBranches": [
         "renovate/github.com-envoyproxy-go-control-plane-0.x",
         "renovate/github.com-mustafaturan-bus-1.x"
       ]
DEBUG: remainingBranches= (repository=my-repo1)
DEBUG: No branches to clean up (repository=my-repo1)
DEBUG: ensureIssueClosing() (repository=my-repo1)
DEBUG: Repository timing splits (milliseconds) (repository=my-repo1)
       "splits": {"init": 2271, "extract": 1640, "lookup": 5831, "update": 3381},
       "total": 13657
DEBUG: http statistics (repository=my-repo1)
       "urls": {
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.0.0-427.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.7-JIRA1979.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.7-logs.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.7.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.10.8.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.2.3-test.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.4.1-hotfix.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.4.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.4.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.4.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.5.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.5.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.6.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.6.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.6.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.6.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.6.4-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.6.4-dev1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.6.4-dev2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.6.4-dev4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.6.4-dev5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.6.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.7.0-RC1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.7.0-rc1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.7.1-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.7.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.7.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.7.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.7.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.8.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.8.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.9.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.9.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.9.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.9.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.9.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.9.5-982.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.9.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-microservice-core/@v/v1.9.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-stomp-websocket/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-stomp-websocket/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-stomp-websocket/@v/v1.0.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/git.company.com/prod.platform.cloud_core/go-stomp-websocket/@v/v1.0.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/dgrijalva/jwt-go/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/dgrijalva/jwt-go/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/dgrijalva/jwt-go/@v/v1.0.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/dgrijalva/jwt-go/@v/v1.0.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.10.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.5.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.6.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.6.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.6.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.6.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.6.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.6.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.6.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.6.7.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.6.8.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.6.9.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.7.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.7.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.8.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.8.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.8.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.8.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.8.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.8.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.8.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.9.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.9.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.9.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.9.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.9.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.9.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.9.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.9.7.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.9.8.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/envoyproxy/go-control-plane/@v/v0.9.9.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ghodss/yaml/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ghodss/yaml/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-errors/errors/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-errors/errors/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-errors/errors/@v/v1.0.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-errors/errors/@v/v1.0.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-errors/errors/@v/v1.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-errors/errors/@v/v1.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-errors/errors/@v/v1.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-errors/errors/@v/v1.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-errors/errors/@v/v1.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-errors/errors/@v/v1.4.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.10.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.11.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.7.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.8.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/migrations/v7/@v/v7.1.9.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.10.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.11.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.12.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.13.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.14.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.15.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.7.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.8.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.9.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0-beta.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.0.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.1.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.1.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.1.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.1.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.1.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.1.7.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/go-pg/pg/v9/@v/v9.2.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.3.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.3.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.3.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.3.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.3.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.4.0-rc.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.4.0-rc.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.4.0-rc.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.4.0-rc.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.4.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.4.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.4.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.5.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.5.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/golang/protobuf/@v/v1.5.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/google/uuid/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/google/uuid/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/google/uuid/@v/v1.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/google/uuid/@v/v1.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/google/uuid/@v/v1.1.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/google/uuid/@v/v1.1.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/google/uuid/@v/v1.1.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/google/uuid/@v/v1.1.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/google/uuid/@v/v1.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/google/uuid/@v/v1.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.5.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.6.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.6.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.6.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.7.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.7.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.7.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.7.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.7.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/mux/@v/v1.8.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/websocket/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/websocket/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/websocket/@v/v1.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/websocket/@v/v1.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/websocket/@v/v1.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/websocket/@v/v1.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/websocket/@v/v1.4.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/gorilla/websocket/@v/v1.4.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.0.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.0.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.0.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.0.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.1.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.2.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.3.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-memdb/@v/v1.3.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-uuid/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-uuid/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-uuid/@v/v1.0.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/go-uuid/@v/v1.0.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.1.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.1.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.1.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.1.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.1.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.1.7.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.2.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.2.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.2.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/memberlist/@v/v0.2.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.2.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.4.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.4.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.5.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.6.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.6.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.6.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.6.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.6.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.7.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.8.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.8.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.8.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.8.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.8.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.8.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.8.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.9.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.9.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.9.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.9.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.9.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/hashicorp/serf/@v/v0.9.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.1.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.2.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.2.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.2.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.3.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.3.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.3.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.4.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mitchellh/mapstructure/@v/v1.4.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/bus/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/bus/@v/v0.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/bus/@v/v0.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/bus/@v/v0.1.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/bus/@v/v0.1.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/bus/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/bus/@v/v1.0.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/bus/@v/v1.0.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/monoton/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/monoton/@v/v0.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/monoton/@v/v0.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/monoton/@v/v0.2.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/monoton/@v/v0.2.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/monoton/@v/v0.2.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/monoton/@v/v0.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/monoton/@v/v0.3.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/monoton/@v/v0.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/mustafaturan/monoton/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.5.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.5.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.5.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.5.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.5.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.5.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.6.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.6.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.6.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.6.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.6.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.6.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.7.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/ory/dockertest/v3/@v/v3.8.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.5.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.5.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.6.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.7.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.7.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.8.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.8.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.9.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/pkg/errors/@v/v0.9.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.1.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.1.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.1.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.2.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.2.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.5.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.5.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.6.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.6.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/stretchr/testify/@v/v1.7.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.0.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.0.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.0.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.0.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.0.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.0.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.1.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.1.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.1.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.1.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.1.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.1.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.1.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.10.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.10.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.10.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.11.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.2.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.2.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.3.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.3.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.3.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.3.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.3.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.3.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.5.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.6.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.6.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.6.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.6.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.6.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.6.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.6.6.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.6.7.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.6.8.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.7.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.7.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.7.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.7.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.7.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.7.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.8.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.8.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.9.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.9.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.9.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.9.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/github.com/tidwall/gjson/@v/v1.9.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/genproto/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.0.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.0.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.0.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.0.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.0.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.10.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.10.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.11.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.11.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.11.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.11.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.12.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.12.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.12.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.13.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.14.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.15.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.16.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.17.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.18.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.18.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.19.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.19.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.2.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.2.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.20.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.20.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.21.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.21.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.21.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.21.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.21.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.22.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.22.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.22.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.22.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.23.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.23.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.24.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.25.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.25.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.26.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.27.0-pre.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.27.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.27.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.28.0-pre.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.28.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.28.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.29.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.29.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.29.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.3.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.30.0-dev.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.30.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.30.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.30.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.31.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.31.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.31.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.32.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.32.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.33.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.33.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.33.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.33.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.33.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.34.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.34.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.34.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.34.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.35.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.35.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.35.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.36.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.36.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.36.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.37.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.37.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.37.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.38.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.38.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.38.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.39.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.39.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.39.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.4.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.4.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.4.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.40.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.40.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.41.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.41.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.42.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.42.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.43.0-dev.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.5.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.5.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.5.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.6.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.7.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.7.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.7.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.7.3.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.7.4.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.7.5.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.8.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.8.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.9.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.9.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/grpc/@v/v1.9.2.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/list (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.20.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.20.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.21.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.22.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.23.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.24.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.25.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.26.0-rc.1.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.26.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.27.0.info (GET)": 1,
         "https://artifactorycn.company.com/api/go/pd.saas-release.golang.group/google.golang.org/protobuf/@v/v1.27.1.info (GET)": 1,
         "https://artifactorycn.company.com:17003/artifactory/api/docker/pd.saas.docker/v2/token (GET)": 1,
         "https://artifactorycn.company.com:17003/v2/ (GET)": 1,
         "https://artifactorycn.company.com:17003/v2/general/alpine-base-image/blobs/sha256:3a8833674550a809800ecce4614a32a2426514d3b5780e373311cc5f8ba3b0d3 (GET)": 1,
         "https://artifactorycn.company.com:17003/v2/general/alpine-base-image/manifests/3.14-b01 (GET)": 1,
         "https://artifactorycn.company.com:17003/v2/general/alpine-base-image/tags/list (GET)": 1,
         "https://artifactorycn.company.com:17064/artifactory/api/docker/hub_docker_io.docker.proxy/v2/token (GET)": 2,
         "https://artifactorycn.company.com:17064/v2/ (GET)": 1,
         "https://artifactorycn.company.com:17064/v2/alpine/blobs/sha256:14119a10abf4669e8cdbdff324a9f9605d99697215a0d21c360fe8dfa8471bab (GET)": 1,
         "https://artifactorycn.company.com:17064/v2/alpine/manifests/latest (GET)": 1,
         "https://artifactorycn.company.com:17064/v2/alpine/manifests/sha256:69704ef328d05a9f806b6b8502915e6a0a4faa4d72018dc42343f511490daf8a (GET)": 1,
         "https://artifactorycn.company.com:17064/v2/library/alpine/tags/list (GET)": 1,
         "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Fcontrol-plane (GET)": 1,
         "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Fcontrol-plane/issues (GET)": 1,
         "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Fcontrol-plane/issues/2 (GET)": 2,
         "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Fcontrol-plane/issues/2 (PUT)": 1,
         "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Fcontrol-plane/merge_requests (GET)": 3,
         "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Fcontrol-plane/merge_requests/964 (GET)": 1,
         "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Fcontrol-plane/merge_requests/975 (GET)": 1,
         "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Fcontrol-plane/repository/commits/028445bcf0d8971ab9264c6825cb5313be7d7baf/statuses (GET)": 1,
         "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Fcontrol-plane/repository/commits/b28786df3f3a0ab0785d341f3c103693c3b0184d/statuses (GET)": 1,
         "https://git.company.com/prod.platform.cloud_core/go-microservice-core (GET)": 1,
         "https://git.company.com/prod.platform.cloud_core/go-stomp-websocket (GET)": 1
       },
       "hostStats": {
         "artifactorycn.company.com": {
           "requestCount": 527,
           "requestAvgMs": 77,
           "queueAvgMs": 0
         },
         "git.company.com": {
           "requestCount": 14,
           "requestAvgMs": 208,
           "queueAvgMs": 0
         }
       },
       "totalRequests": 541
 INFO: Repository finished (repository=my-repo1)
       "durationMs": 13657
DEBUG: Renovate exiting
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Ensures branchStatus is always resolved in PR worker.

## Context:

Fixes #12676, Fixes #12621, Fixes #12561

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/pr/index.ts [hunk 1]
```diff
@@ -149,6 +149,16 @@ export type EnsurePrResult = ResultWithPr | ResultWithoutPr;
 export async function ensurePr(
```
Comment (HonkingGoose) [inline lib/workers/pr/index.ts:149]: Maybe this PR fixes issue https://github.com/renovatebot/renovate/issues/12561 as well?

Comment (rarkins) [reply lib/workers/pr/index.ts:149]: Added to the list, thanks

**Review by viceice — APPROVED** [review]
