### PR TITLE
fix(dashboard): filter deps with skip reason

### LINKED ISSUE #17255: Invalid deps are shown on dashboard detected dependencies
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We still show invalid deps on dashboard
image

https://github.com/visualon/docker-proget/issues/1

regression of ?
- #15418

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: packageFiles with updates
{
  "baseBranch": "main",
  "config": {
    "docker-compose": [
      {
        "packageFile": "linux/docker-compose.test.yml",
        "deps": [
          {
            "skipReason": "invalid-name",
            "replaceString": "${IMAGE}",
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "datasource": "docker",
            "depIndex": 0,
            "updates": []
          }
        ]
      }
    ],
    "dockerfile": [
      {
        "packageFile": "linux/Dockerfile",
        "deps": [
          {
            "depName": "proget.inedo.com/productimages/inedo/proget",
            "currentValue": "22.0.5",
            "currentDigest": "sha256:ad625caaf9200022c5016fe8f8677c4089c210cc1780a7934b6a06c9a646ca9f",
            "replaceString": "proget.inedo.com/productimages/inedo/proget:22.0.5@sha256:ad625caaf9200022c5016fe8f8677c4089c210cc1780a7934b6a06c9a646ca9f",
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "datasource": "docker",
            "depType": "final",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "versioning": "docker",
            "currentVersion": "22.0.5",
            "fixedVersion": "22.0.5"
          }
        ]
      }
    ],
    "github-actions": [
      {
        "packageFile": ".github/workflows/build.yml",
        "deps": [
          {
            "depName": "actions/checkout",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "regex:^v(?<major>\\d+)(\\.(?<minor>\\d+)\\.(?<patch>\\d+))?$",
            "depType": "action",
            "replaceString": "actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v3.0.2",
            "currentDigest": "2541b1294d2704b0964813337f33b291d3f8596b",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/actions/checkout",
            "currentVersion": "v3.0.2",
            "fixedVersion": "v3.0.2"
          },
          {
            "depName": "renovatebot/internal-tools",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "regex:^v(?<major>\\d+)(\\.(?<minor>\\d+)\\.(?<patch>\\d+))?$",
            "depType": "action",
            "replaceString": "renovatebot/internal-tools@ac2a85780492e013c8fa9d87aa72a788b78fbd58 # tag=v1.14.2",
            "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
            "currentValue": "v1.14.2",
            "currentDigest": "ac2a85780492e013c8fa9d87aa72a788b78fbd58",
            "depIndex": 1,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/renovatebot/internal-tools",
            "currentVersion": "v1.14.2",
            "fixedVersion": "v1.14.2"
          }
        ]
      }
    ]
  }
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by viceice**
## Changes
 - filter all deps with `skipReason`
 - simplify code

## Context
- fixes #17255

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/repository/package-files.ts [hunk 1]
```diff
@@ -53,28 +47,30 @@ export class PackageFiles {
...
+    const data = new Map(clone(Array.from(this.data)));
+
+    // filter all deps with skip reason
+    for (const managers of [...data.values()].filter(is.truthy)) {
+      for (const files of Object.values(managers).filter(is.truthy)) {
+        for (const file of files.filter((f) => is.truthy(f.deps))) {
+          file.deps = file.deps.filter(is.truthy).filter((d) => !d.skipReason);
+        }
+      }
+    }
```
Comment (Gabriel-Ladzaretti) [inline lib/workers/repository/package-files.ts:60]: does the two first `is.truthy` needed? say for example we set a value of `undefiend|null` for some key in the map, is it possible to set a prop on an `undefiend|null`? i.e. `undefined.files = []`?
i know js is quirky but wouldnt this fail on runtime?

**Review by Gabriel-Ladzaretti — COMMENTED** [review]
Otherwise no other input 😀

File: lib/workers/repository/package-files.ts (hunk 1 above)
Comment (rarkins) [reply lib/workers/repository/package-files.ts:60]: But this is Object.values(). not Object.keys()?

Comment (viceice) [reply lib/workers/repository/package-files.ts:60]: yes, i only get `values` which can be `null` or `undefined`. it's just defense code because  of some misbehaving managers

Comment (Gabriel-Ladzaretti) [reply lib/workers/repository/package-files.ts:60]: all i meant to say is that say we have some manager that has undefined as its value i.e.
```json
{
  "baseBranch": "main",
  "config": {
    "docker-compose":  undefined | null | empty Array
}
```

if will be filtered out in the next for loop regardless of `is.truthy`
and also i think that it should be `manager` and not `managers`, as we have files per a single manager

```suggestion
    // filter all deps with skip reason
    for (const manager of [...data.values()].filter(is.truthy)) {
      for (const files of Object.values(manager).filter(is.truthy)) {
        for (const file of files.filter((f) => is.truthy(f.deps))) {
          file.deps = file.deps.filter(is.truthy).filter((d) => !d.skipReason);
        }
      }
    }
```

File: lib/workers/repository/package-files.ts [hunk 2]
```diff
@@ -53,28 +47,30 @@ export class PackageFiles {
     let header = '';
     let removed = false;
     let truncated = false;
-    let restore: (() => void) | null = null;
+
+    const data = new Map(clone(Array.from(this.data)));
+
+    // filter all deps with skip reason
+    for (const managers of [...data.values()].filter(is.truthy)) {
+      for (const files of Object.values(managers).filter(is.truthy)) {
```
Comment (Gabriel-Ladzaretti) [inline lib/workers/repository/package-files.ts:55]:
```suggestion
    for (const manager of [...data.values()].filter(is.truthy)) {
      for (const files of Object.values(manager).filter(is.truthy)) {
```

i think manager is more accurate in this context

**Review by Gabriel-Ladzaretti — APPROVED** [review]
apart from below nit, LGTM

File: lib/workers/repository/package-files.ts (hunk 2 above)
Comment (viceice) [reply lib/workers/repository/package-files.ts:55]: nope, it's the magaers dictionary
image

**Review by rarkins — APPROVED** [review]
I'm happy if you two are happy

File: lib/workers/repository/package-files.ts (hunk 2 above)
Comment (Gabriel-Ladzaretti) [reply lib/workers/repository/package-files.ts:55]: i think this is a manager with all of its detected manifest files.
`[...data.values()]` are indeed managers but when iteration over them each entry is a manger, might be wrong, im fine either way :)

Comment (viceice) [reply lib/workers/repository/package-files.ts:55]: nope. those are the records of all manager per branch ;-)
