### PR TITLE
fix(git-refs): git-refs always returning null

### LINKED ISSUE #5847: git-tags datasource doesnt work anymore
**What Renovate type are you using?**

Self hosted on GitLab 12.9 CE

Broken on version **19.189.3**
Works on version **19.183.1**

Possibly introduced in #5727

**Describe the bug**

Renovate cannot upgrade our terraform modules anymore. They are implemented like this:

```hcl
module "database" {
  source = "git::https://company-gitlab/tf-modules/database.git?ref=1.1.4"
  application_identifier = var.application_identifier
  stage = var.stage
  application_user = aws_iam_user.user.name
}
```

**Did you see anything helpful in debug logs?**

```
TypeError: Cannot read property 'filter' of null
    at Object.getPkgReleases (renovate/dist/datasource/git-tags/index.js:19:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async fetchReleases (renovate/dist/datasource/index.js:39:17)
    at async Object.getPkgReleases (renovate/dist/datasource/index.js:64:15)
    at async Object.lookupUpdates (renovate/dist/workers/repository/process/lookup/index.js:89:42)
    at async fetchDepUpdates (renovate/dist/workers/repository/process/fetch.js:41:29)
```

**To Reproduce**

i hope the stack is enough. basically you try to update a terraform module.

**Additional context**

Quick fix for now is to downgrade to an older renovate version.

Other configurations:
We inject a ssh key into the docker image to be used by simple-git
```
# .gitconfig to force ssh usage when cloning with git (worked perfectly fine before)
[url "git@mycompany.com:"]
	insteadOf = https://mycompany.com/
```

### PR DESCRIPTION
**Pull request by Tanuel**
Closes #5847

Also adds a missing null-check to git-tags  datasource

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
needs test coverage

**Comment by Tanuel** [comment]
> needs test coverage

Yes, there is also still another bug. Apparently this changes have never been tested against a real repository, since the responses defined in the tests are not actual responses simple-git would return with the wrong parameter order. it would always return nothing

**Comment by viceice** [comment]
@Tanuel Are you able to fix the tests?

**Comment by Tanuel** [comment]
> @Tanuel Are you able to fix the tests?

To have a 100% fail-save solution would require to set up an actual git repository for the tests which seems kinda overkill in the scope of this bugfix. I am testing all changes against my current renovate configuration against real repos tho.

Fun fact: i have ran into this issue before when i initially implemented this feature back in july :D

**Comment by Tanuel** [comment]
Also i propose escalating `logger.debug({ err }, `Git-Raw-Refs lookup error in ${lookupName}`);` to a warning or error since this should usually only occur when an internal error within renovate occurs?

**Comment by viceice** [comment]
I think fixing the mocked results should be enough here for now.

We should open another issue to do real git tests.

**Comment by Tanuel** [comment]
> I think fixing the mocked results should be enough here for now.
> 
> We should open another issue to do real git tests.

The mocked results where never the problem, the call itsself was just wrong. The code coverage problem right now is because i have added a null-check to git-tags that has not been there before

**Comment by Tanuel** [comment]
@viceice which log level do you suggest for the error message? i would say `error` since it is an internal issue

File: lib/datasource/git-refs/index.ts [hunk 1]
```diff
@@ -32,23 +32,34 @@ export async function getRawRefs({
     }
 
     // fetch remote tags
-    const lsRemote = await git.listRemote([lookupName, '--sort=-v:refname']);
+    const lsRemote = await git.listRemote([
+      '--sort=-v:refname',
+      '--tags',
+      '--heads',
```
Comment (viceice) [inline lib/datasource/git-refs/index.ts:38]:
```suggestion
      '--refs',
```

This will remove all pseudo refs
https://git-scm.com/docs/git-ls-remote.html

**Comment by rarkins** [comment]
If something should never happen, log it as error.
If it's a problem, but someone else's problem, then log it as a warning.

File: lib/datasource/git-tags/index.ts [hunk 2]
```diff
@@ -29,7 +32,7 @@ export async function getPkgReleases({
 
     return result;
   } catch (err) {
-    logger.debug({ err }, `Git-Tags lookup error in ${lookupName}`);
+    logger.error({ err }, `Git-Tags lookup error in ${lookupName}`);
```
Comment (Tanuel) [inline lib/datasource/git-tags/index.ts:35]: @viceice i cannot figure out how to run into this block since a potential null response from git-refs is now caught. i would want to avoid ignoring this from coverage if possible

Comment (viceice) [reply lib/datasource/git-tags/index.ts:35]: I think the catch can removed completely then

File: lib/datasource/git-refs/index.ts (hunk 1 above)
Comment (Tanuel) [reply lib/datasource/git-refs/index.ts:38]: I initially tried that, but this will also add other things like merge requests which are not useful actually
```
16c8ebeab61d5f86a6ea1f2bfec80a65d1cfead9	refs/heads/master
ac23d58cf398f0c31a05dea5e5d78dea6663cba4	refs/heads/renovate/configure
2b7667fb5f40b32ae7d52c88c5cc295f52b97898	refs/pipelines/1/head
2b7667fb5f40b32ae7d52c88c5cc295f52b97898	refs/environments/1/head
2b7667fb5f40b32ae7d52c88c5cc295f52b97898	refs/pipelines/1/head
f3ec126e31331019ec135c4c093f6f249c04a7c6	refs/merge-requests/1/merge
84c41c73ebf1fcce52a3de07682d07473943f92a	refs/merge-requests/2/head
c689af53089e7409f69e0469d9bdd422ab8f8da8	refs/merge-requests/2/merge
e8b5c41ddf75770ed29d5f924a686052bb376bab	refs/tags/1.2.0
ee85705ee6d770a66cc143dc1a3d49de410965ba	refs/tags/1.3.0
16c8ebeab61d5f86a6ea1f2bfec80a65d1cfead9	refs/tags/2.0.0
```

Comment (viceice) [reply lib/datasource/git-refs/index.ts:38]: See updated suggestion

Comment (Tanuel) [reply lib/datasource/git-refs/index.ts:38]: adding --refs to --heads and --tags will not help us here, since only tags and heads are required for now. adding --refs for the sake seems not necessary. I think it would be better to add more flags only if they are required.

Comment (viceice) [reply lib/datasource/git-refs/index.ts:38]: `--refs` will remove rows like `bd237d0c9c55f42e5ef8a2ca1d5e99f30662097a        refs/tags/v8.9.3^{}`

Comment (Tanuel) [reply lib/datasource/git-refs/index.ts:38]: til about annotated tags, thanks!

**Comment by Tanuel** [comment]
I think the MR is ready now!

File: lib/datasource/git-refs/index.ts [hunk 3]
```diff
@@ -32,23 +32,35 @@ export async function getRawRefs({
...
+      .trim()
+      .replace(/^.+?refs\//gm, '')
+      .split('\n');
 
-    const result = refs.map(ref => ({
-      type: /(.*?)\//.exec(ref)[1],
-      value: /\/(.*)/.exec(ref)[1],
-    }));
+    const result = refs.map(ref => {
+      const match = /(?<type>\w+)\/(?<value>.*)/.exec(ref);
```
Comment (viceice) [inline lib/datasource/git-refs/index.ts:53]: perf: move regex to const in module scope

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/datasource/git-refs/index.ts (hunk 3 above)
Comment (Tanuel) [reply lib/datasource/git-refs/index.ts]: Rather odd request considering this has not been requested on the initial implementation, but i have extracted all regexes to const for git-refs and git-tags ;)

Comment (viceice) [reply lib/datasource/git-refs/index.ts]: sorry, havn't seen it before. 🙈 😅

File: lib/datasource/git-refs/index.ts [hunk 4]
```diff
@@ -10,6 +10,11 @@ const cacheMinutes = 10;
 // git will prompt for known hosts or passwords, unless we activate BatchMode
 process.env.GIT_SSH_COMMAND = 'ssh -o BatchMode=yes';
 
+const refMatchPattern = /(?<type>\w+)\/(?<value>.*)/;
+const lsRemoteReplace = /^.+?refs\//gm;
```
Comment (viceice) [inline lib/datasource/git-refs/index.ts:14]: Sorry to say, global matching regex needs to be reinstantiated, otherwise it will not work on next run
```suggestion
```

File: lib/datasource/git-refs/index.ts [hunk 5]
```diff
@@ -32,23 +37,35 @@ export async function getRawRefs({
...
+    ]);
 
     if (!lsRemote) {
       return null;
     }
 
-    const refs = lsRemote.replace(/^.+?refs\//gm, '').split('\n');
+    const refs = lsRemote
+      .trim()
+      .replace(lsRemoteReplace, '')
```
Comment (viceice) [inline lib/datasource/git-refs/index.ts:54]:
```suggestion
      .replace(/^.+?refs\//gm, '')
```

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/datasource/git-refs/index.ts (hunk 4 above)
Comment (Tanuel) [reply lib/datasource/git-refs/index.ts]: I have reverted the previous commit and just extracted the ref-match out of the loop, which has the most performance impact.
The other regex patterns should have neglible performance impact especially compared to the io-delay of making remote (git) calls.

**Review by viceice — APPROVED** [review]
