### PR TITLE
fix(gomod): explicitly match Gitlab ID for gitlab enterprise servers

### LINKED ISSUE #17570: Go package hosted in github enterprise no longer resolves
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.186.1

### If you're self-hosting Renovate, select which platform you are using.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

3.5.4

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Repos referencing github enterprise hosted go packages in their go.mod now no longer functions correctly.
It thinks the URL belongs to gitlab and starts using gitlab api calls to resolve the github enterprise package.
You can see in the logs that it is clearly a github url, but it fails with a "Gitlab api error" which is not correct.

I suspect this PR would be the cause of this:
https://github.com/renovatebot/renovate/pull/17105

It used to work in renovate `32.92.0` and stopped working sometime after that. The next version we tried was `32.159.5` and that had this issue.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Gitlab API error (repository=myOrg/team.repo-name)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1662030048940,
           "socket": 1662030048940,
           "lookup": 1662030048949,
           "connect": 1662030048951,
           "secureConnect": 1662030048953,
           "upload": 1662030048953,
           "response": 1662030048979,
           "end": 1662030048979,
           "abort": 1662030048980,
           "phases": {
             "wait": 0,
             "dns": 9,
             "tcp": 2,
             "tls": 2,
             "request": 0,
             "firstByte": 26,
             "download": 0,
             "total": 40
           }
         },
         "message": "Response code 406 (Not Acceptable)",
         "stack": "HTTPError: Response code 406 (Not Acceptable)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/32.186.1 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://github.org.internal.myCompany.com/login?return_to=https%3A%2F%2Fgithub.org.internal.myCompany.com%2Fapi%2Fv4%2Fprojects%2FmyOrg%252Fteam.package-name%2Frepository%2Ftags%3Fper_page%3D100",
           "hostType": "gitlab-tags",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 406,
           "statusMessage": "Not Acceptable",
           "body": "",
           "headers": {
             "server": "GitHub.com",
             "date": "Thu, 01 Sep 2022 11:00:48 GMT",
             "content-type": "application/json",
             "transfer-encoding": "chunked",
             "vary": "X-PJAX, X-PJAX-Container",
             "permissions-policy": "interest-cohort=()",
             "cache-control": "no-store",
             "set-cookie": [
               "logged_in=no; domain=github.org.internal.myCompany.com; path=/; expires=Fri, 01 Sep 2023 11:00:48 GMT; secure; HttpOnly; SameSite=Lax",
               "_fi_sess=Rfg08SudNKAE86rDuNE6m7QuGExZdWVVXHAHala5K5p4LwAoFfc2DbNepcKwmQ9ziDZex5uVpwH0cCJT7WAn8bPnVS%2FpZzaSC4NjcCP2n71Ex1388UD7GRDCR40eVzyNpqu4vZeR4AiVp7cPfD21D5fQZ3sXXjrYzRmonkv41%2FE%3D--BiETnZ1dx5Fir2KR--LX2K0lJBtTrVEjbRim0f5g%3D%3D; path=/; secure; HttpOnly; SameSite=Lax"
             ],
             "x-runtime": "0.011462",
             "x-github-request-id": "5e32c4d7-6ad7-4367-9869-d0bdc4050422",
             "strict-transport-security": "max-age=31536000; includeSubdomains",
             "x-frame-options": "deny",
             "x-content-type-options": "nosniff",
             "x-xss-protection": "0",
             "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
             "content-security-policy": "default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src github.org.internal.myCompany.com/assets-cdn/worker/ gist.github.org.internal.myCompany.com/assets-cdn/worker/; connect-src 'self' uploads.github.org.internal.myCompany.com media.github.org.internal.myCompany.com www.githubstatus.com raw.github.org.internal.myCompany.com github.org.internal.myCompany.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com online.visualstudio.com/api/v1/locations github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://github.org.internal.myCompany.com; font-src assets.github.org.internal.myCompany.com; form-action 'self' github.org.internal.myCompany.com gist.github.org.internal.myCompany.com; frame-ancestors 'none'; frame-src render.github.org.internal.myCompany.com viewscreen.github.org.internal.myCompany.com notebooks.github.org.internal.myCompany.com; img-src * data:; manifest-src 'self'; media-src media.github.org.internal.myCompany.com; script-src assets.github.org.internal.myCompany.com; style-src 'unsafe-inline' assets.github.org.internal.myCompany.com; worker-src github.org.internal.myCompany.com/assets-cdn/worker/ gist.github.org.internal.myCompany.com/assets-cdn/worker/",
             "x-runtime-rack": "0.016442",
             "connection": "close"
           },
           "httpVersion": "1.1"
         }
       }
DEBUG: Datasource connection error (repository=myOrg/team.repo-name)
       "datasource": "go",
       "packageName": "github.org.internal.myCompany.com/myOrg/team.package-name",
       "url": "https://github.org.internal.myCompany.com/login?return_to=https%3A%2F%2Fgithub.org.internal.myCompany.com%2Fapi%2Fv4%2Fprojects%2FmyOrg%252Fteam.package-name%2Frepository%2Ftags%3Fper_page%3D100",
       "errCode": "ERR_NON_2XX_3XX_RESPONSE"
DEBUG: Failed to look up dependency github.org.internal.myCompany.com/myOrg/team.package-name (repository=myOrg/team.repo-name, packageFile=go.mod, dependency=github.org.internal.myCompany.com/myOrg/team.package-name)
       "datasource": "go",
       "registryUrls": null
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by bastianccm**
## Changes

This change checks for the correct hostType for a given URL to decide if it should try to match it as a Gitlab Enterprise repository for go modules hosted on URLs which do not include "gitlab".

This should fix #17570 

## Context

~~The `HostRuleSearchResult` does not return the `hostType`. The host-rules `find` method will match on hostnames only, if no matching `hostType` is set.~~

~~This means, that it is impossible to ask for a hostRule _only if_ it matches the `hostType`.~~

~~To be non-breaking, we use this value to match that the hostRule is actually a Gitlab host rule in the gomod datasource, otherwise there is no way of telling a Github Enterprise and Gitlab Enterprise configuration apart.~~

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/host-rules.ts [hunk 1]
```diff
@@ -155,7 +155,6 @@ export function find(search: HostRuleSearch): HostRuleSearchResult {
     .forEach((rule) => {
       res = merge(res, rule);
     });
-  delete res.hostType;
```
Comment (viceice) [inline lib/util/host-rules.ts:158]: this can break other code, because the returned object is directly used.

@rarkins any better solution?

Comment (bastianccm) [reply lib/util/host-rules.ts:158]: Yes, I suspected that... Would there be any other way of getting the hostType, if configured, for a given host? Otherwise we can't tell gitlab and github enterprise apart, as both can have completely custom domains, and I think that doing a network request and checking for the result is not a good solution at all...

It would be possible to define a `findHostRule` method which returns the `HostRule`, and `find` is just a wrapper around `findHostRule` which casts to `HostRuleSearchResult`? But then we have another method exported...

Comment (bastianccm) [reply lib/util/host-rules.ts:158]: actually there is `hostType`, I'll adjust the MR

Comment (bastianccm) [reply lib/util/host-rules.ts]: This should be much better, as it also does not take any assumptions about how the repository is accessed (which was implicitly done by checking for the `token`)

**Review by viceice — APPROVED** [review]
