### PR TITLE
fix(git): wrong config argument passing

### LINKED ISSUE #7148: Version 23.11.0 introduces error "fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n"
**What Renovate type, platform and version are you using?**
Using the RenovateMe add-in for azure devops,  which means 
ubuntu-20.04
node 12.18.3
renovate version anything equal to or greater than 23.11.0 fails

**Describe the bug**

Renovate is failing duing the initilisation stages with the error 
"fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n"

**Relevant debug logs**
```
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "JutA_tmt7",
           "repository": "REDACTED/REDACTED",
           "err": {
             "task": {
               "commands": [
                 "ls-remote",
                 "--heads",
                 "https://dev.azure.com/avius/REDACTED/_git/REDACTED"
               ],
               "format": "utf-8"
             },
             "message": "fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n",
             "stack": "Error: fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n\n    at GitExecutorChain.onFatalException (/home/vsts/.npm/_npx/3595/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/home/vsts/.npm/_npx/3595/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/home/vsts/.npm/_npx/3595/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
           },
           "msg": "Repository has unknown error"
         }
       ]
```

**To Reproduce**

run against azure?

**Additional context**
I have tested with different versions and can confirm that 
version 23.10.2 - works
version 23.11.0 - fails 
version 23.14.0 - (latest) still failing.

### PR DESCRIPTION
**Pull request by viceice**
For `git ls-remote` the `--config` argument mus come before `ls-remote` and the short version `-c` must be used.

Looks very hacki now. I like to refactor it later.

closes #7148

### CODE REVIEW

**Comment by viceice** [comment]
So coming back to my idea added to slack:

* do a git init on `initRepo`:
  * configure remote and other config options
* on `syncGit`:
  * fetch (prune) remote
  * reset and checkout default branch

**Comment by stocksr** [comment]
today i learnt that the --config (-c) option is specific to git clone and sets up the local config in the clone
 https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---configltkeygtltvaluegt 

there is a different -c option that if you put it before the subcommand it overrides the config for that command only 
https://git-scm.com/docs/git#Documentation/git.txt--cltnamegtltvaluegt

File: lib/util/git/index.ts [hunk 1]
```diff
@@ -112,14 +112,14 @@ let privateKeySet = false;
...
   if (config.extraCloneOpts) {
-    opts.push(
-      ...Object.entries(config.extraCloneOpts).map((e) => `${e[0]}=${e[1]}`)
+    Object.entries(config.extraCloneOpts).forEach((e) =>
+      opts.unshift(e[0], `${e[1]}`)
     );
   }
   try {
-    (await git.listRemote(opts))
+    (await git.raw(opts))
```
Comment (JamieMagee) [inline lib/util/git/index.ts:122]: Why the change to `raw` here?

**Review by JamieMagee — APPROVED** [review]

File: lib/util/git/index.ts (hunk 1 above)
Comment (viceice) [reply lib/util/git/index.ts:122]: because the `-c` arg must be come before `ls-remote` and `SimpleGit.listRemote` would pass it after, which would be ignored then

**Review by rarkins — APPROVED** [review]
