### PR TITLE
fix(datasource/go): fix parsing go-source and go-import without quotation

### LINKED ISSUE #15333: go-source meta header isn't parsed correctly
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.32.2

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.10.0-ee

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

minimal reproduction repository: https://github.com/rstdm/minimal-renovate-reproduction

I'm using renovate to update the versions in my Go project. Unfortunately, renovate isn't able to update my helm dependency: `Failed to look up dependency helm.sh/helm/v3`.

After a long debugging session I located the bug.

`$curl https://helm.sh/helm/v3/?go-get=1`
`<!doctype html><html lang=en-us><head><meta charset=utf-8><meta name=go-import content="helm.sh/helm/v3 git https://github.com/helm/helm"><meta name=go-source content="helm.sh/helm/v3 git https://github.com/helm/helm https://github.com/helm/helm/tree/main{/dir} https://github.com/helm/helm/blob/main{/dir}/{file}#L{line}"><meta http-equiv=refresh content="0; url=https://github.com/helm/helm"></head><body>Nothing to see here; <a href=https://github.com/helm/helm>move along</a>.</body></html>`

The server returns *minified* html. It's `<meta name=go-source content=...` instead of  `<meta name="go-source" content=...`

But renovate requires quotation marks: 
https://github.com/renovatebot/renovate/blob/1268dac93775b7e9e99592873d6baa7b35590e0c/lib/modules/datasource/go/base.ts#L65-L67
https://github.com/renovatebot/renovate/blob/1268dac93775b7e9e99592873d6baa7b35590e0c/lib/modules/datasource/go/base.ts#L138-L145

That's the main reason why helm is not working but I'm not completely sure it's the only bug in the go datasource. From my understanding the go commands (go get, go mod, etc.) only make use of go-import, which means that go get on a module without the go-source header works just fine ([source](https://pkg.go.dev/cmd/go#hdr-Remote_import_paths)). But renovate checks for the presence of go-source. If the go-source header is missing it is assumed that the module has to be located on GitHub Enterprise which might cause false positives.

In case of helm the go-source header *seems* to be missing because helm returns an incorrect header. They return `<meta name=go-source content="helm.sh/helm/v3 git https://github.com/helm/helm https://github.com/helm/helm/tree/main{/dir} https://github.com/helm/helm/blob/main{/dir}/{file}#L{line}">` but the specification requires it to be `<meta name="go-source" content="prefix home directory file">` ([source](https://github.com/golang/gddo/wiki/Source-Code-Links)). `git` shouldn't be part of the header.The header is incorrect but go get works just fine because it uses the go-import header (which is correct). Renovate, on the other hand, will fail to parse the header. Therefore I would suggest to primarily rely on the go-import header and to use the go-source header only as a fallback.

Documentation:

- go-import header: https://pkg.go.dev/cmd/go#hdr-Remote_import_paths
- go-source header: https://pkg.go.dev/about#source-links

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found gomod package files (repository=rstdm/minimal-renovate-reproduction)
DEBUG: Found 1 package file(s) (repository=rstdm/minimal-renovate-reproduction)
 INFO: Dependency extraction complete (repository=rstdm/minimal-renovate-reproduction)
       "baseBranch": "master",
       "stats": {
         "managers": {"gomod": {"fileCount": 1, "depCount": 1}},
         "total": {"fileCount": 1, "depCount": 1}
       }
 INFO: Unsupported go host - cannot look up versions (repository=rstdm/minimal-renovate-reproduction)
       "packageName": "helm.sh/helm/v3"
DEBUG: Failed to look up dependency helm.sh/helm/v3 (repository=rstdm/minimal-renovate-reproduction, packageFile=go.mod, dependency=helm.sh/helm/v3)
DEBUG: Package releases lookups complete (repository=rstdm/minimal-renovate-reproduction)
       "baseBranch": "master"
DEBUG: branchifyUpgrades (repository=rstdm/minimal-renovate-reproduction)
DEBUG: 0 flattened updates found:  (repository=rstdm/minimal-renovate-reproduction)
DEBUG: Returning 0 branch(es) (repository=rstdm/minimal-renovate-reproduction)
DEBUG: config.repoIsOnboarded=false (repository=rstdm/minimal-renovate-reproduction)
DEBUG: packageFiles with updates (repository=rstdm/minimal-renovate-reproduction)
       "config": {
         "gomod": [
           {
             "packageFile": "go.mod",
             "constraints": {"go": "^1.18"},
             "deps": [
               {
                 "managerData": {"lineNumber": 4},
                 "depName": "helm.sh/helm/v3",
                 "depType": "require",
                 "currentValue": "v3.8.0",
                 "datasource": "go",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "helm.sh/helm/v3",
                     "message": "Failed to look up dependency helm.sh/helm/v3"
                   }
                 ],
                 "versioning": "semver"
               }
             ]
           }
         ]
       }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes

fix go datasource parsing without quotes.

## Context

Closes #15333

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [X] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by PhilipAbed** [comment]
refactor is in : https://github.com/renovatebot/renovate/pull/15401
this is blocked by 15401

**Review by rarkins — APPROVED** [review]

File: lib/modules/datasource/go/base.ts [hunk 1]
```diff
@@ -73,7 +73,7 @@ export class BaseGoDatasource {
     goModule: string
   ): DataSource | null {
     const sourceMatch = regEx(
-      `<meta\\s+name="go-source"\\s+content="([^\\s]+)\\s+([^\\s]+)`
+      `<meta\\s+name="?go-source"?\\s+content="([^\\s]+)\\s+([^\\s]+)`
```
Comment (viceice) [inline lib/modules/datasource/go/base.ts:76]: this is strange, as this violates html standards, so this is a workaround for misbehaving API. 😕

Comment (rarkins) [reply lib/modules/datasource/go/base.ts:76]: :shrug:
