### PR TITLE
fix(manager/gradle): Add `groupName` for toml parser and plugins

### LINKED ISSUE #12983: Duplicate PR when referencing both plugin and library in gradle toml file
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Describe the bug

In a repository that uses gradle and version catalogs, if version is referenced by both a plugin and a library, like this:
<details><summary>libs.versions.toml</summary>

```
[versions]
detekt = "1.18.1"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
```

</details>
Then renovatebot will create two conflicting PRs that update the version but both will only mention one of the things that will get updated.

<p>

[Link](/baardsen/renovate-duplicate-pr) to a reproduction repository where there are currently two PRs open that want to make the same change.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: No dangling containers to remove
INFO: Repository started
{
  "renovateVersion": "29.32.4"
}
DEBUG: Using localDir: /mnt/renovate/gh/baardsen/renovate-duplicate-pr
DEBUG: Repository cache is valid
DEBUG: initRepo("baardsen/renovate-duplicate-pr")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: baardsen/renovate-duplicate-pr default branch = main
DEBUG: Using app token for git init
DEBUG: resetMemCache()
DEBUG: Resetting npmrc
DEBUG: detectSemanticCommits()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: Checking cached config file name
DEBUG: Existing config file confirmed
DEBUG: Repo is onboarded
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ]
  }
}
DEBUG: Setting hostRules from config
DEBUG: Found repo ignorePaths
{
  "ignorePaths": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/examples/**",
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**",
    "**/__fixtures__/**"
  ]
}
DEBUG: No vulnerability alerts found
DEBUG: No vulnerability alerts found
DEBUG: findIssue(Dependency Dashboard)
DEBUG: Retrieving issueList
DEBUG: Retrieved 0 issues
DEBUG: No baseBranches
DEBUG: extract()
DEBUG: Setting current branch to main
DEBUG: Initializing git repository into /mnt/renovate/gh/baardsen/renovate-duplicate-pr
DEBUG: Performing blobless clone
DEBUG: git clone completed
{
  "durationMs": 1056
}
DEBUG: latest repository commit
{
  "latestCommit": {
    "hash": "97fd3f85d6f71a4015e70a7cc48bfff2fee65fab",
    "date": "2021-12-07T01:25:15+01:00",
    "message": "Add renovate.json (#1)",
    "refs": "HEAD -> main, origin/main, origin/HEAD",
    "body": "Co-authored-by: Renovate Bot <bot@renovateapp.com>",
    "author_name": "renovate[bot]",
    "author_email": "29139614+renovate[bot]@users.noreply.github.com"
  }
}
DEBUG: latest commit
{
  "branchName": "main",
  "latestCommitDate": "2021-12-07T01:25:15+01:00"
}
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible
DEBUG: Using file match: (^|/)requirements\.ya?ml$ for manager ansible-galaxy
DEBUG: Using file match: (^|/)galaxy\.ya?ml$ for manager ansible-galaxy
DEBUG: Using file match: azure.*pipelines?.*\.ya?ml$ for manager azure-pipelines
DEBUG: Using file match: (^|/)batect(-bundle)?\.yml$ for manager batect
DEBUG: Using file match: (^|/)batect$ for manager batect-wrapper
DEBUG: Using file match: (^|/)WORKSPACE(|\.bazel)$ for manager bazel
DEBUG: Using file match: \.bzl$ for manager bazel
DEBUG: Using file match: (^|/)\.?bitbucket-pipelines\.ya?ml$ for manager bitbucket-pipelines
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite
DEBUG: Using file match: (^|/)Gemfile$ for manager bundler
DEBUG: Using file match: \.cake$ for manager cake
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci
DEBUG: Using file match: (^|/)cloudbuild.ya?ml for manager cloudbuild
DEBUG: Using file match: (^|/)Podfile$ for manager cocoapods
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: Using file match: (^|/|\.)Dockerfile$ for manager dockerfile
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci
DEBUG: Using file match: (^|/).gitmodules$ for manager git-submodules
DEBUG: Using file match: ^(workflow-templates|\.github\/workflows)\/[^/]+\.ya?ml$ for manager github-actions
DEBUG: Using file match: (^|\/)action\.ya?ml$ for manager github-actions
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci-include
DEBUG: Using file match: (^|/)go.mod$ for manager gomod
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle
DEBUG: Using file match: (^|\/)gradle\.properties$ for manager gradle
DEBUG: Using file match: (^|\/)gradle\/.+\.toml$ for manager gradle
DEBUG: Using file match: \.versions\.toml$ for manager gradle
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper
DEBUG: Using file match: (^|/)requirements\.yaml$ for manager helm-requirements
DEBUG: Using file match: (^|/)values.yaml$ for manager helm-values
DEBUG: Using file match: (^|/)helmfile.yaml$ for manager helmfile
DEBUG: Using file match: (^|/)Chart.yaml$ for manager helmv3
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew
DEBUG: Using file match: \.html?$ for manager html
DEBUG: Using file match: (^|/)plugins\.(txt|ya?ml)$ for manager jenkins
DEBUG: Using file match: (^|/)jsonnetfile.json$ for manager jsonnet-bundler
DEBUG: Using file match: (^|/)kustomization\.yaml for manager kustomize
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen
DEBUG: Using file match: \.pom\.xml$ for manager maven
DEBUG: Using file match: (^|/)pom\.xml$ for manager maven
DEBUG: Using file match: (^|/)package.js$ for manager meteor
DEBUG: Using file match: (^|/)mix\.exs$ for manager mix
DEBUG: Using file match: (^|/).node-version$ for manager nodenv
DEBUG: Using file match: (^|/)package.json$ for manager npm
DEBUG: Using file match: \.(?:cs|fs|vb)proj$ for manager nuget
DEBUG: Using file match: \.(?:props|targets)$ for manager nuget
DEBUG: Using file match: (^|\/)dotnet-tools\.json$ for manager nuget
DEBUG: Using file match: (^|\/)global\.json$ for manager nuget
DEBUG: Using file match: (^|/)\.nvmrc$ for manager nvm
DEBUG: Using file match: (^|/)([\w-]*)requirements\.(txt|pip)$ for manager pip_requirements
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup
DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry
DEBUG: Using file match: (^|/)\.pre-commit-config\.yaml$ for manager pre-commit
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub
DEBUG: Using file match: (^|/).python-version$ for manager pyenv
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version
DEBUG: Using file match: \.sbt$ for manager sbt
DEBUG: Using file match: project/[^/]*.scala$ for manager sbt
DEBUG: Using file match: (^|/)setup\.cfg$ for manager setup-cfg
DEBUG: Using file match: (^|/)Package\.swift for manager swift
DEBUG: Using file match: \.tf$ for manager terraform
DEBUG: Using file match: (^|/)\.terraform-version$ for manager terraform-version
DEBUG: Using file match: (^|/)terragrunt\.hcl$ for manager terragrunt
DEBUG: Using file match: (^|/)\.terragrunt-version$ for manager terragrunt-version
DEBUG: Using file match: ^.travis.yml$ for manager travis
DEBUG: Matched 3 file(s) for manager gradle: build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
DEBUG: Matched 1 file(s) for manager gradle-wrapper: gradle/wrapper/gradle-wrapper.properties
DEBUG: Found gradle package files
DEBUG: Found gradle-wrapper package files
DEBUG: Found 4 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "main",
  "stats": {
    "managers": {
      "gradle": {
        "fileCount": 3,
        "depCount": 2
      },
      "gradle-wrapper": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 4,
      "depCount": 3
    }
  }
}
DEBUG: Looking up io.gitlab.arturbosch.detekt:detekt-formatting in repository https://repo.maven.apache.org/maven2/
DEBUG: Looking up io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin in repository https://repo.maven.apache.org/maven2/
DEBUG: Found 68 new releases for io.gitlab.arturbosch.detekt:detekt-formatting in repository https://repo.maven.apache.org/maven2/
DEBUG: Content is not found for Maven url
{
  "url": "https://repo.maven.apache.org/maven2/io/gitlab/arturbosch/detekt/io.gitlab.arturbosch.detekt.gradle.plugin/maven-metadata.xml"
}
DEBUG: Looking up io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin in repository https://plugins.gradle.org/m2/
DEBUG: Found 100 new releases for io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin in repository https://plugins.gradle.org/m2/
DEBUG: Package releases lookups complete
{
  "baseBranch": "main"
}
DEBUG: branchifyUpgrades
DEBUG: Using group branchName template
DEBUG: Dependency io.gitlab.arturbosch.detekt:detekt-formatting is part of group io.gitlab.arturbosch.detekt
DEBUG: 2 flattened updates found: io.gitlab.arturbosch.detekt:detekt-formatting, io.gitlab.arturbosch.detekt
DEBUG: Returning 2 branch(es)
DEBUG: Fetching changelog: https://github.com/detekt/detekt (1.18.1 -> 1.19.0)
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "gradle": [
      {
        "packageFile": "settings.gradle.kts",
        "datasource": "maven",
        "deps": []
      },
      {
        "packageFile": "build.gradle.kts",
        "datasource": "maven",
        "deps": []
      },
      {
        "packageFile": "gradle/libs.versions.toml",
        "datasource": "maven",
        "deps": [
          {
            "depName": "io.gitlab.arturbosch.detekt:detekt-formatting",
            "groupName": "io.gitlab.arturbosch.detekt",
            "currentValue": "1.18.1",
            "managerData": {
              "fileReplacePosition": 21,
              "packageFile": "gradle/libs.versions.toml"
            },
            "fileReplacePosition": 21,
            "registryUrls": [
              "https://repo.maven.apache.org/maven2"
            ],
            "depIndex": 0,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "1.19.0",
                "newValue": "1.19.0",
                "releaseTimestamp": "2021-11-29T10:05:23.000Z",
                "newMajor": 1,
                "newMinor": 19,
                "updateType": "minor",
                "branchName": "renovate/io.gitlab.arturbosch.detekt"
              }
            ],
            "warnings": [],
            "versioning": "gradle",
            "sourceUrl": "https://github.com/detekt/detekt",
            "homepage": "https://detekt.github.io/detekt",
            "currentVersion": "1.18.1",
            "isSingleVersion": true,
            "fixedVersion": "1.18.1"
          },
          {
            "depType": "plugin",
            "depName": "io.gitlab.arturbosch.detekt",
            "lookupName": "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2",
              "https://plugins.gradle.org/m2/"
            ],
            "currentValue": "1.18.1",
            "commitMessageTopic": "plugin detekt",
            "managerData": {
              "fileReplacePosition": 21,
              "packageFile": "gradle/libs.versions.toml"
            },
            "fileReplacePosition": 21,
            "depIndex": 1,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "1.19.0",
                "newValue": "1.19.0",
                "newMajor": 1,
                "newMinor": 19,
                "updateType": "minor",
                "branchName": "renovate/io.gitlab.arturbosch.detekt-1.x"
              }
            ],
            "warnings": [],
            "versioning": "gradle",
            "currentVersion": "1.18.1",
            "isSingleVersion": true,
            "fixedVersion": "1.18.1"
          }
        ]
      }
    ],
    "gradle-wrapper": [
      {
        "packageFile": "gradle/wrapper/gradle-wrapper.properties",
        "deps": [
          {
            "depName": "gradle",
            "currentValue": "7.3.1",
            "replaceString": "https\\://services.gradle.org/distributions/gradle-7.3.1-bin.zip",
            "datasource": "gradle-version",
            "versioning": "gradle",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/gradle/gradle",
            "homepage": "https://gradle.org",
            "currentVersion": "7.3.1",
            "fixedVersion": "7.3.1"
          }
        ]
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 2 branches: renovate/io.gitlab.arturbosch.detekt, renovate/io.gitlab.arturbosch.detekt-1.x
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 1 Pull Requests
DEBUG: currentHourStart=2021-12-07T00:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating prConcurrentLimit (20)
DEBUG: getBranchPr(renovate/io.gitlab.arturbosch.detekt)
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt, undefined, open)
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt, undefined, closed)
DEBUG: getBranchPr(renovate/io.gitlab.arturbosch.detekt-1.x)
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt-1.x, undefined, open)
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt-1.x, undefined, closed)
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 20
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 2
}
DEBUG: PullRequests limit = 2
DEBUG: Calculating hourly PRs remaining
DEBUG: currentHourStart=2021-12-07T00:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating branchConcurrentLimit (20)
DEBUG: 0 already existing branches found:
DEBUG: Branch concurrent limit remaining: 20
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 2
}
DEBUG: Branches limit = 2
DEBUG: Setting current branch to main(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: latest commit(branch="renovate/io.gitlab.arturbosch.detekt")
{
  "branchName": "main",
  "latestCommitDate": "2021-12-07T01:25:15+01:00"
}
DEBUG: getBranchPr(renovate/io.gitlab.arturbosch.detekt)(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt, undefined, open)(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt, undefined, closed)(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: branchExists=false(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: recreateClosed is false(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt, Update dependency io.gitlab.arturbosch.detekt:detekt-formatting to v1.19.0, !open)(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: prAlreadyExisted=false(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: Checking schedule(at any time, null)(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: No schedule defined(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: Branch needs creating(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: Using reuseExistingBranch: false(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: Updating io.gitlab.arturbosch.detekt:detekt-formatting in gradle/libs.versions.toml(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: Updated 1 package files(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: No updated lock files in branch(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: 1 file(s) to commit(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: Committing files to branch renovate/io.gitlab.arturbosch.detekt(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: Setting git author name(branch="renovate/io.gitlab.arturbosch.detekt")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/io.gitlab.arturbosch.detekt")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: git commit(branch="renovate/io.gitlab.arturbosch.detekt")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/io.gitlab.arturbosch.detekt",
    "commit": "bdc9f4d",
    "root": false,
    "summary": {
      "changes": 1,
      "insertions": 1,
      "deletions": 1
    }
  }
}
DEBUG: git push(branch="renovate/io.gitlab.arturbosch.detekt")
{
  "result": {
    "pushed": [
      {
        "deleted": false,
        "tag": false,
        "branch": true,
        "new": true,
        "alreadyUpdated": false,
        "local": "refs/heads/renovate/io.gitlab.arturbosch.detekt",
        "remote": "refs/heads/renovate/io.gitlab.arturbosch.detekt"
      }
    ],
    "branch": {
      "local": "renovate/io.gitlab.arturbosch.detekt",
      "remote": "renovate/io.gitlab.arturbosch.detekt",
      "remoteName": "origin"
    },
    "ref": {
      "local": "refs/remotes/origin/renovate/io.gitlab.arturbosch.detekt"
    },
    "remoteMessages": {
      "all": [
        "Create a pull request for 'renovate/io.gitlab.arturbosch.detekt' on GitHub by visiting:",
        "https://github.com/baardsen/renovate-duplicate-pr/pull/new/renovate/io.gitlab.arturbosch.detekt"
      ],
      "pullRequestUrl": "https://github.com/baardsen/renovate-duplicate-pr/pull/new/renovate/io.gitlab.arturbosch.detekt"
    }
  }
}
INFO: Branch created(branch="renovate/io.gitlab.arturbosch.detekt")
{
  "commitSha": "bdc9f4d"
}
DEBUG: Ensuring PR(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: getBranchPr(renovate/io.gitlab.arturbosch.detekt)(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt, undefined, open)(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt, undefined, closed)(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: Creating PR(branch="renovate/io.gitlab.arturbosch.detekt")
{
  "prTitle": "Update dependency io.gitlab.arturbosch.detekt:detekt-formatting to v1.19.0"
}
DEBUG: Creating PR(branch="renovate/io.gitlab.arturbosch.detekt")
{
  "title": "Update dependency io.gitlab.arturbosch.detekt:detekt-formatting to v1.19.0",
  "head": "baardsen:renovate/io.gitlab.arturbosch.detekt",
  "base": "main",
  "draft": false
}
DEBUG: PR created(branch="renovate/io.gitlab.arturbosch.detekt")
{
  "pr": 2,
  "draft": false
}
DEBUG: Adding labels '' to #2(branch="renovate/io.gitlab.arturbosch.detekt")
INFO: PR created(branch="renovate/io.gitlab.arturbosch.detekt")
{
  "pr": 2,
  "prTitle": "Update dependency io.gitlab.arturbosch.detekt:detekt-formatting to v1.19.0"
}
DEBUG: addAssigneesReviewers(pr=2)(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: Created Pull Request #2(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: PR is not configured for automerge(branch="renovate/io.gitlab.arturbosch.detekt")
DEBUG: Setting current branch to main(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: latest commit(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
{
  "branchName": "main",
  "latestCommitDate": "2021-12-07T01:25:15+01:00"
}
DEBUG: getBranchPr(renovate/io.gitlab.arturbosch.detekt-1.x)(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt-1.x, undefined, open)(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt-1.x, undefined, closed)(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: branchExists=false(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: recreateClosed is false(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt-1.x, Update plugin detekt to v1.19.0, !open)(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: prAlreadyExisted=false(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: No schedule defined(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: Branch needs creating(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: Using reuseExistingBranch: false(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: Updating io.gitlab.arturbosch.detekt in gradle/libs.versions.toml(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: Updated 1 package files(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: No updated lock files in branch(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: 1 file(s) to commit(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: Committing files to branch renovate/io.gitlab.arturbosch.detekt-1.x(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: Setting git author name(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: git commit(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/io.gitlab.arturbosch.detekt-1.x",
    "commit": "114db44",
    "root": false,
    "summary": {
      "changes": 1,
      "insertions": 1,
      "deletions": 0
    }
  }
}
DEBUG: git push(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
{
  "result": {
    "pushed": [
      {
        "deleted": false,
        "tag": false,
        "branch": true,
        "new": true,
        "alreadyUpdated": false,
        "local": "refs/heads/renovate/io.gitlab.arturbosch.detekt-1.x",
        "remote": "refs/heads/renovate/io.gitlab.arturbosch.detekt-1.x"
      }
    ],
    "branch": {
      "local": "renovate/io.gitlab.arturbosch.detekt-1.x",
      "remote": "renovate/io.gitlab.arturbosch.detekt-1.x",
      "remoteName": "origin"
    },
    "ref": {
      "local": "refs/remotes/origin/renovate/io.gitlab.arturbosch.detekt-1.x"
    },
    "remoteMessages": {
      "all": [
        "Create a pull request for 'renovate/io.gitlab.arturbosch.detekt-1.x' on GitHub by visiting:",
        "https://github.com/baardsen/renovate-duplicate-pr/pull/new/renovate/io.gitlab.arturbosch.detekt-1.x"
      ],
      "pullRequestUrl": "https://github.com/baardsen/renovate-duplicate-pr/pull/new/renovate/io.gitlab.arturbosch.detekt-1.x"
    }
  }
}
INFO: Branch created(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
{
  "commitSha": "114db44"
}
DEBUG: Ensuring PR(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: getBranchPr(renovate/io.gitlab.arturbosch.detekt-1.x)(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt-1.x, undefined, open)(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt-1.x, undefined, closed)(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: Creating PR(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
{
  "prTitle": "Update plugin detekt to v1.19.0"
}
DEBUG: Creating PR(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
{
  "title": "Update plugin detekt to v1.19.0",
  "head": "baardsen:renovate/io.gitlab.arturbosch.detekt-1.x",
  "base": "main",
  "draft": false
}
DEBUG: PR created(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
{
  "pr": 3,
  "draft": false
}
DEBUG: Adding labels '' to #3(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
INFO: PR created(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
{
  "pr": 3,
  "prTitle": "Update plugin detekt to v1.19.0"
}
DEBUG: addAssigneesReviewers(pr=3)(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: Created Pull Request #3(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: PR is not configured for automerge(branch="renovate/io.gitlab.arturbosch.detekt-1.x")
DEBUG: getBranchPr(renovate/io.gitlab.arturbosch.detekt)
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt, undefined, open)
DEBUG: Found PR #2
DEBUG: Returning from graphql open PR list
DEBUG: getBranchPr(renovate/io.gitlab.arturbosch.detekt-1.x)
DEBUG: findPr(renovate/io.gitlab.arturbosch.detekt-1.x, undefined, open)
DEBUG: Found PR #3
DEBUG: Returning from graphql open PR list
DEBUG: Ensuring Dependency Dashboard
DEBUG: ensureIssue(Dependency Dashboard)
INFO: Issue created
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/io.gitlab.arturbosch.detekt",
    "renovate/io.gitlab.arturbosch.detekt-1.x"
  ],
  "renovateBranches": [
    "renovate/configure",
    "renovate/io.gitlab.arturbosch.detekt",
    "renovate/io.gitlab.arturbosch.detekt-1.x"
  ]
}
DEBUG: remainingBranches=renovate/configure
DEBUG: findPr(renovate/configure, undefined, open)
INFO: Deleting orphan branch(branch="renovate/configure")
DEBUG: Deleted remote branch
{
  "branchName": "renovate/configure"
}
DEBUG: No local branch to delete
{
  "branchName": "renovate/configure"
}
DEBUG: Retrieving issueList
DEBUG: Retrieved 1 issues
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {
    "init": 1820,
    "extract": 2469,
    "lookup": 1398,
    "update": 9844
  },
  "total": 18304
}
DEBUG: http statistics
{
  "urls": {
    "https://api.github.com/graphql (POST)": 5,
    "https://api.github.com/repos/baardsen/renovate-duplicate-pr/contents/renovate.json (GET)": 1,
    "https://api.github.com/repos/baardsen/renovate-duplicate-pr/issues (POST)": 1,
    "https://api.github.com/repos/baardsen/renovate-duplicate-pr/pulls (GET)": 1,
    "https://api.github.com/repos/baardsen/renovate-duplicate-pr/pulls (POST)": 2,
    "https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json (GET)": 1,
    "https://plugins.gradle.org/m2/io/gitlab/arturbosch/detekt/io.gitlab.arturbosch.detekt.gradle.plugin/1.19.0/io.gitlab.arturbosch.detekt.gradle.plugin-1.19.0.pom (GET)": 1,
    "https://repo.maven.apache.org/maven2/io/gitlab/arturbosch/detekt/detekt-formatting/1.19.0/detekt-formatting-1.19.0.pom (GET)": 1
  },
  "hostStats": {
    "api.github.com": {
      "requestCount": 11,
      "requestAvgMs": 568,
      "queueAvgMs": 0
    },
    "plugins.gradle.org": {
      "requestCount": 1,
      "requestAvgMs": 264,
      "queueAvgMs": 0
    },
    "repo.maven.apache.org": {
      "requestCount": 1,
      "requestAvgMs": 60,
      "queueAvgMs": 0
    }
  },
  "totalRequests": 13
}
INFO: Repository finished
{
  "durationMs": 18304
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by hasanwhitesource**
## Changes

- Added `groupName` values for deps defined in toml files to be equal to variable references.
- Added `groupName` values for plugins in `parser.ts` when the version value has a variable reference.
- Before deps final result removed `commitMessageTopic` field for each dep having a `groupName` value as a variable reference.

Discussed in : #12983 

## Context

Edited `groupName` values for some of tests after agreeing that we want version variable references to
have higher priority than other `groupName` values.

Closes #12983 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/gradle/parser.ts [hunk 1]
```diff
@@ -230,6 +230,7 @@ function processPlugin({
       const fileReplacePosition = varData.fileReplacePosition;
       dep.currentValue = currentValue;
       dep.managerData = { fileReplacePosition, packageFile };
+      dep.groupName = varData.key;
```
Comment (zharinov) [inline lib/modules/manager/gradle/parser.ts:233]: Please, handle similar case for `pluginVersion.type === TokenType.StringInterpolation` below

File: lib/modules/manager/gradle/extract/catalog.ts [hunk 2]
```diff
@@ -207,7 +211,7 @@ function extractDependency({
 export function parseCatalog(
   packageFile: string,
   content: string
-): PackageDependency<GradleManagerData>[] {
+): [PackageDependency<GradleManagerData>[], string[]] {
```
Comment (zharinov) [inline lib/modules/manager/gradle/extract/catalog.ts:214]: I would like to return `{ deps, urls, vars }` structure, just like `parseProps` and `parseGradle` do

File: lib/modules/manager/gradle/extract/catalog.ts [hunk 3]
```diff
@@ -184,19 +184,23 @@ function extractDependency({
...
     };
   }
-
+  const versionRef = isVersionPointer(descriptor.version)
+    ? descriptor.version.ref
+    : null;
   if (isArtifactDescriptor(descriptor)) {
-    const { group: groupName, name } = descriptor;
+    const { group, name } = descriptor;
+    const groupName = is.nullOrUndefined(versionRef) ? group : versionRef; // usage of common variable should have higher priority than other values
```
Comment (zharinov) [inline lib/modules/manager/gradle/extract/catalog.ts:192]: Does it mean we always have some grouping, i.e. `com.example` for `com.example:foo:1.2.3` and `bar` for `com.example:foo:${bar}`? If so, do we want to extend this behavior to `build.gradle` and `gradle.properties` parsing as well?

**Review by zharinov — CHANGES_REQUESTED** [review]

File: lib/modules/manager/gradle/extract/catalog.ts (hunk 3 above)
Comment (hasanwhitesource) [reply lib/modules/manager/gradle/extract/catalog.ts:192]: @zharinov Yes groupName will be the variable name in case where there is a variable. (yes correct to your example)
As for the second question I think yes. wdyt @rarkins ?

Comment (hasanwhitesource) [reply lib/modules/manager/gradle/extract/catalog.ts:192]: @zharinov 

`build.gradle`:
- Checked the code and it seems you were already setting the `groupName` values to variables when there are variable substitutions in the dependencies block of `build.gradle`. Here is a test for it https://github.com/hasanwhitesource/renovate/blob/5946790b6601471363ab06907638d3b9ec81a862/lib/modules/manager/gradle/parser.spec.ts#L62
- After handling plugins in this pr we will also handle plugins in `build.gradle`

As for the `gradle.properties` could there be a reference to a variable that is defined in the same file ? Kind of new to the gradle files but looked around a bit and saw that users just define their properties to be used there.

Comment (zharinov) [reply lib/modules/manager/gradle/extract/catalog.ts:192]: Initially, I've assumed `gradle.properties` to contain only variable definitions.
But in some cases people define the entire coordinates, e.g. `com.example:foo:1.2.3`.
I don't think variable references are possible inside `gradle.properties`, so it should be okay as is.

Comment (zharinov) [reply lib/modules/manager/gradle/extract/catalog.ts:192]: In order to keep the scope of this PR smaller, it seems reasonable to delay decision about `groupName` fields for `build.gradle` files, implementing it in separate PR if needed.

Comment (hasanwhitesource) [reply lib/modules/manager/gradle/extract/catalog.ts:192]: I will only keep the logic for toml parsing then 👍🏻

**Comment by hasanwhitesource** [comment]
@zharinov any updates here wdyt?

File: lib/modules/manager/gradle/extract/catalog.ts [hunk 4]
```diff
@@ -266,16 +272,25 @@ export function parseCatalog(
...
+            managerData: { fileReplacePosition },
+            groupName,
+          };
     }
 
     extractedDeps.push(dependency);
   }
-  return extractedDeps.map((dep) =>
+  const deps = extractedDeps.map((dep) =>
     deepmerge(dep, { managerData: { packageFile } })
```
Comment (zharinov) [inline lib/modules/manager/gradle/extract/catalog.ts:293]: I don't like this `deepmerge`, but let's not touch it for now.
Instead, let's also add processing from `gradle/extract.ts`, i.e. this logic:
```ts
if (
  !is.nullOrUndefined(dep.groupName) &&
  versionRefs.has(dep.groupName)
) {
  delete dep.commitMessageTopic;
}
```

**Review by zharinov — CHANGES_REQUESTED** [review]

File: lib/modules/manager/gradle/extract/catalog.ts [hunk 5]
```diff
@@ -259,23 +262,30 @@ export function parseCatalog(
...
     }
 
     extractedDeps.push(dependency);
   }
-  return extractedDeps.map((dep) =>
-    deepmerge(dep, { managerData: { packageFile } })
-  );
+
+  const versionRefs: Set<string> = new Set();
+  Object.keys(versions).forEach((ref) => versionRefs.add(ref));
```
Comment (viceice) [inline lib/modules/manager/gradle/extract/catalog.ts:282]: please use a `for...of` loop

**Review by viceice — COMMENTED** [review]
otherwise LGTM

**Review by rarkins — APPROVED** [review]

**Review by zharinov — APPROVED** [review]
