### PR TITLE
fix(gitlabci): gracefully handle errors

### LINKED ISSUE #9162: GitLab !reference Keyword causes YAMLException
**What Renovate type, platform and version are you using?**

Renovate 24.85.1, both on self-hosted GitLab and GitLab.com

**Describe the bug**

I recently added a project to renovate's scope that includes a gitlab-ci.yml that uses the `!reference` keyword:

```
include:
  - local: setup.yml
  
test:
  script:
    - !reference [.setup, script]
    - echo running my own command
```

When running renovate, it tries to validate the yml file but failes, cause !reference is not a valid identifier in yml. 

**Relevant debug logs**

```
ERROR: Repository has unknown error (repository=deveth0/renovate-runner-demo)
       "err": {
         "name": "YAMLException",
         "reason": "unknown tag !<!reference>",
         "mark": {
           "name": null,
           "buffer": "\ninclude:\n  - local: setup.yml\n  \ntest:\n  script:\n    - !reference [.setup, script]\n    - echo running my own command\n\u0000",
           "position": 83,
           "line": 6,
           "column": 33
         },
         "message": "unknown tag !<!reference> at line 7, column 34:\n        - !reference [.setup, script]\n                                     ^",
         "stack": "YAMLException: unknown tag !<!reference> at line 7, column 34:\n        - !reference [.setup, script]\n                                     ^\n    at generateError (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)\n    at throwError (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)\n    at composeNode (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1434:7)\n    at readBlockSequence (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:955:5)\n    at composeNode (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1358:12)\n    at readBlockMapping (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)\n    at composeNode (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)\n    at readBlockMapping (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)\n    at composeNode (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)\n    at readDocument (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)\n    at loadDocuments (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)\n    at load (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)\n    at Object.safeLoad (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)\n    at Object.extractAllPackageFiles (/usr/src/app/node_modules/renovate/lib/manager/gitlabci/extract.ts:99:22)\n    at Object.extractAllPackageFiles (/usr/src/app/node_modules/renovate/lib/manager/index.ts:62:17)\n    at Object.getManagerPackageFiles (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:33:29)\n    at /usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:52:28\n    at async Promise.all (index 0)\n    at Object.extractAllDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:50:26)\n    at Object.checkOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/index.ts:45:24)"
       }
 INFO: Repository finished (repository=deveth0/renovate-runner-demo)
       "durationMs": 2242
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "3YKhMDSqL",
           "repository": "deveth0/renovate-runner-demo",
           "err": {
             "name": "YAMLException",
             "reason": "unknown tag !<!reference>",
             "mark": {
               "name": null,
               "buffer": "\ninclude:\n  - local: setup.yml\n  \ntest:\n  script:\n    - !reference [.setup, script]\n    - echo running my own command\n\u0000",
               "position": 83,
               "line": 6,
               "column": 33
             },
             "message": "unknown tag !<!reference> at line 7, column 34:\n        - !reference [.setup, script]\n                                     ^",
             "stack": "YAMLException: unknown tag !<!reference> at line 7, column 34:\n        - !reference [.setup, script]\n                                     ^\n    at generateError (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)\n    at throwError (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)\n    at composeNode (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1434:7)\n    at readBlockSequence (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:955:5)\n    at composeNode (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1358:12)\n    at readBlockMapping (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)\n    at composeNode (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)\n    at readBlockMapping (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)\n    at composeNode (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)\n    at readDocument (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)\n    at loadDocuments (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)\n    at load (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)\n    at Object.safeLoad (/usr/src/app/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)\n    at Object.extractAllPackageFiles (/usr/src/app/node_modules/renovate/lib/manager/gitlabci/extract.ts:99:22)\n    at Object.extractAllPackageFiles (/usr/src/app/node_modules/renovate/lib/manager/index.ts:62:17)\n    at Object.getManagerPackageFiles (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:33:29)\n    at /usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:52:28\n    at async Promise.all (index 0)\n    at Object.extractAllDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:50:26)\n    at Object.checkOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/index.ts:45:24)"
           },
           "msg": "Repository has unknown error"
         }
       ]
```

**Have you created a minimal reproduction repository?**

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

Sure :)

* GitLab Renovate Runner Project: https://gitlab.com/deveth0/renovate-runner
* Project with `!reference`: https://gitlab.com/deveth0/renovate-runner-demo

**Additional context**

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

- gracefully handle parser errors with warning
- ignore `!reference` reference tags
- fix seen files

## Context:

fixes #9162

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/manager/gitlabci/utils.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// !reference [.setup, script]
+const re = /!reference \[\.\w+?(?:, \w+?)\]/g;
+
+/**
+ * Replaces gitlab reference tags before parsing, because we our yaml parser doesn't support that.
```
Comment (HonkingGoose) [inline lib/manager/gitlabci/utils.ts:5]:
```suggestion
 * Replaces GitLab reference tags before parsing, because our yaml parser doesn't support that.
```

**Review by HonkingGoose — CHANGES_REQUESTED** [review]
Small typo and grammar fix.

File: lib/manager/gitlabci/extract.spec.ts [hunk 2]
```diff
@@ -1,8 +1,12 @@
-import { getName } from '../../../test/util';
+import { getName, logger } from '../../../test/util';
 import type { PackageDependency } from '../types';
 import { extractAllPackageFiles } from './extract';
 
 describe(getName(__filename), () => {
+  jest
+    .spyOn(logger.logger, 'warn')
+    .mockImplementation((...args) => console.warn(...args));
```
Comment (rarkins) [inline lib/manager/gitlabci/extract.spec.ts:8]: Still want this included?

**Review by rarkins — COMMENTED** [review]
console.warn

File: lib/manager/gitlabci/extract.spec.ts (hunk 2 above)
Comment (viceice) [reply lib/manager/gitlabci/extract.spec.ts]: ups, removed

File: lib/manager/gitlabci/utils.ts [hunk 3]
```diff
@@ -0,0 +1,13 @@
+// !reference [.setup, script]
```
Comment (HonkingGoose) [inline lib/manager/gitlabci/utils.ts:1]:
```suggestion

```

Do we need this comment to remind us to do something later? Or can this be removed?

File: lib/manager/gitlabci/utils.ts [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+const re = /!reference \[\.\w+?(?:, \w+?)\]/g;
+
+/**
+ * Replaces GitLab reference tags before parsing, because our yaml parser doesn't support that.
```
Comment (HonkingGoose) [inline lib/manager/gitlabci/utils.ts:5]:
```suggestion
 * Replaces GitLab reference tags before parsing, because our yaml parser cannot process them anyway.
```

Maybe this is clearer?

File: lib/manager/gitlabci/utils.ts (hunk 3 above)
Comment (viceice) [reply lib/manager/gitlabci/utils.ts:1]: not sure, it's just a reminder about the format. I'll remove.

**Review by rarkins — APPROVED** [review]
