### PR TITLE
fix: remove leading '@' symbol from usernames

### LINKED ISSUE #9857: filterUnavailableUsers causes failures when usernames start with `@`
**What Renovate type, platform and version are you using?**

Self-hosted Renovate v25 on GitLab

**Describe the bug**

The new option `filterUnavailableUsers` causes request failures when assignees or reviewers have a leading `@`  character (which is not supported by the GitLab API). This can for example be the case when they are retrieved from a `CODEOWNERS` file (where the leading `@` is usually required).

**Relevant debug logs**

_Currently don't have them at hand, ping me if required._

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

### PR DESCRIPTION
**Pull request by fgreinacher**
## Changes:

Remove leading `@` symbol from usernames before passing them to `platform.filterUnavailableUsers` as the platform layer expects usernames to be normalized.

## Context:

Fixes #9857

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/workers/pr/index.ts [hunk 1]
```diff
@@ -42,6 +42,14 @@ function filterUnavailableUsers(
     : Promise.resolve(users);
 }
 
+function prepareAssigneesReviewers(
+  config: RenovateConfig,
+  usernames: string[]
+): Promise<string[]> {
+  const normalizedUsernames = [...new Set(usernames.map(noLeadingAtSymbol))];
+  return filterUnavailableUsers(config, normalizedUsernames);
```
Comment (fgreinacher) [inline lib/workers/pr/index.ts:50]: That's the important change: _First_ normalize usernames, _then_ check availability.

File: lib/workers/pr/index.ts [hunk 2]
```diff
@@ -50,10 +58,9 @@ export async function addAssigneesReviewers(
   if (config.assigneesFromCodeOwners) {
     assignees = await addCodeOwners(assignees, pr);
   }
-  assignees = await filterUnavailableUsers(config, assignees);
   if (assignees.length > 0) {
     try {
-      assignees = assignees.map(noLeadingAtSymbol);
```
Comment (fgreinacher) [inline lib/workers/pr/index.ts:56]: Tiny behavior change: We now remove duplicate assignees (as we already did for reviewers). I cannot imagine a situation where this would cause problems, happy to have another brain think about this 🧐

**Review by viceice — APPROVED** [review]
