### PR TITLE
fix(versioning/ubuntu): support suffixed codename versions

### LINKED ISSUE #30667: Allow suffix on Ubuntu dated codename versions
### Describe the proposed change(s).

Update this regex so it accepts suffixed codename versions for Ubuntu:

https://github.com/renovatebot/renovate/blob/ce6bf18988eb4107de9a422c65896d981668a65f/lib/modules/versioning/ubuntu/common.ts#L3-L5

#### Background info

Renovate does _not_ pick up the latest version of Jammy from Docker Hub. For example: [`ubuntu-jammy-20240627.1` on Docker Hub](https://hub.docker.com/layers/library/ubuntu/jammy-20240627.1/images/sha256-0eb0f877e1c869a300c442c41120e778db7161419244ee5cbc6fa5f134e74736?context=explore).

The current regex never matches on `ubuntu-jammy-20240627.1`, because of the suffixed `.1` at the end.

`@rarkins` will accept a PR to fix this problem, so I'm creating this issue to track the work. :wink:

Related discussion:

- #30560

### PR DESCRIPTION
**Pull request by ivankatliarchuk**
## Changes

- updated regex
- added function getDatedContainerImageSuffix
- added tests to cover missed functionality

## Context

- resolves #30667

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository. https://github.com/ik-workshop/renovate-issue-30667-docker-ubuntu

### CODE REVIEW

File: lib/modules/versioning/ubuntu/common.ts [hunk 1]
```diff
@@ -1,28 +1,40 @@
...
   if (!groups?.groups) {
     return null;
   }
 
   return parseInt(groups.groups.date, 10);
 }
 
+function getDatedContainerImageSuffix(version: string): null | string {
+  const groups = regex.exec(version);
+  if (!groups?.groups) {
```
Comment (rarkins) [inline lib/modules/versioning/ubuntu/common.ts:28]:
```suggestion
  if (!groups?.groups?.suffix) {
```

Otherwise this function can return `undefined`

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
