### PR TITLE
fix(dependency-dashboard): Don't create dependency dashboard during onboarding

### LINKED ISSUE #7450: Dependency Dashboard should not be created while still onboarding
**What Renovate type, platform and version are you using?**

App, but it shouldn't be relevant

**Describe the bug**

Dependency Dashboard is created prior to the onboarding PR being merged

**To Reproduce**

Here is an example 
1. Create a new repo with `.nvmrc` = `12.16.0`
2. Trigger an onboarding
3. Add `"dependencyDashboard": true` to the onboarding `renovate.json`
4. Run Renovate again

You will see the Dependency Dashboard created

### PR DESCRIPTION
**Pull request by zharinov**
Closes #7450

### CODE REVIEW

File: lib/workers/repository/init/config.ts [hunk 1]
```diff
@@ -140,8 +140,11 @@ export async function mergeRenovateConfig(
   config: RenovateConfig
 ): Promise<RenovateConfig> {
   let returnConfig = { ...config };
-  const repoConfig = await detectRepoFileConfig();
-  checkForRepoConfigError(repoConfig);
+  let repoConfig: RepoFileConfig = {};
+  if (!config.onboarding) {
```
Comment (rarkins) [inline lib/workers/repository/init/config.ts:144]: doesn't this potentially have other repercussions? I had expected some evaluation added closer to the dashboard logic

Comment (zharinov) [reply lib/workers/repository/init/config.ts:144]: I think merging onboarding config is the wrong thing, but yes maybe it can break something.

File: lib/workers/repository/init/config.ts [hunk 2]
```diff
@@ -140,7 +140,8 @@ export async function mergeRenovateConfig(
   config: RenovateConfig
 ): Promise<RenovateConfig> {
   let returnConfig = { ...config };
-  const repoConfig = await detectRepoFileConfig();
+  let repoConfig: RepoFileConfig = {};
+  repoConfig = await detectRepoFileConfig();
```
Comment (rarkins) [inline lib/workers/repository/init/config.ts:144]: Revert these?

Comment (zharinov) [reply lib/workers/repository/init/config.ts:144]: Ah, yes
