### PR TITLE
fix: GITLAB_IGNORE_REPO_URL with relative URL

### LINKED ISSUE #9968: GITLAB_IGNORE_REPO_URL does not work with relative url
**What Renovate type, platform and version are you using?**

**Renovate type**

- [ ] Hosted app
- [x] Self hosted

**Renovate platform**

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server (self-hosted)
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server (self-hosted)
- [ ] Gitea (gitea.com, self-hosted)
- [ ] GitHub (github.com, GitHub Enterprise)
- [x] GitLab (gitlab.com, self-hosted)

**Renovate version (if self hosting)**

25 (docker)

**Describe the bug**

We have an internal url that exposes the gitlab api on a different port that can be used via http in the format `http://sub.mycompany:11181/gitlab`. Unfortunatly the API shows `https://sub.mycompany/gitlab` so I have set `GITLAB_IGNORE_REPO_URL`.

Now that leads to URLs like `http://sub.mycompany:11181/group/repo.git` which is missing the `/gitlab` part.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
docker run --rm -u 0 -e GITLAB_IGNORE_REPO_URL=true -e RENOVATE_TOKEN -e NEXUS_PASSWORD -e NEXUS_USERNAME -e no_proxy -e NO_PROXY -e PROXY_HOST -e PROXY_PORT -e NON_PROXY_HOSTS -e NODE_TLS_REJECT_UNAUTHORIZED  -e GRADLE_USER_HOME -e GIT_SSL_NO_VERIFY -e GITHUB_COM_TOKEN -v$PWD/config.js:/usr/src/app/config.js -v$PWD/gradle.properties:/usr/src/app/gradle.properties $IMAGE
 INFO: Repository started (repository=group/repo)
       "renovateVersion": "25.5.0"
ERROR: Repository has unknown error (repository=group/repo)
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "--heads",
             "http://oauth2:**redacted**@sub.mycompany:11181/group/repo.git"
           ],
           "format": "utf-8"
         },
         "message": "fatal: repository 'http://sub.mycompany:11181/group/repo.git/' not found\n",
         "stack": "Error: fatal: repository 'http://sub.mycompany:11181/group/repo.git/' not found\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:109:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.hagroupeTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:106:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:83:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
 INFO: Repository finished (repository=group/repo)
       "durationMs": 152
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "Uz2hvoY9U",
           "repository": "group/repo",
           "err": {
             "task": {
               "commands": [
                 "ls-remote",
                 "--heads",
                 "http://oauth2:**redacted**@sub.mycompany:11181/group/repo.git"
               ],
               "format": "utf-8"
             },
             "message": "fatal: repository 'http://sub.mycompany:11181/group/repo.git/' not found\n",
             "stack": "Error: fatal: repository 'http://sub.mycompany:11181/group/repo.git/' not found\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:109:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.hagroupeTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:106:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:83:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
           },
           "msg": "Repository has unknown error"
         }
       ]

```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

### PR DESCRIPTION
**Pull request by david0**
## Changes:
This PR fixes the GITLAB_IGNORE_REPO_URL if gitlab is installed with an relative url `/gitlab`.

It also respects GITLAB_IGNORE_REPO_URL when pagination is used now.

## Context:

Closes #9968

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/util/http/gitlab.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import URL from 'url';
```
Comment (viceice) [inline lib/util/http/gitlab.ts:1]:
```suggestion
```

Deprecated, use global `URL` object

File: lib/util/http/gitlab.ts [hunk 2]
```diff
@@ -42,8 +43,16 @@ export class GitlabHttp extends Http<GitlabHttpOptions, GitlabHttpOptions> {
         try {
           const linkHeader = parseLinkHeader(result.headers.link as string);
           if (linkHeader?.next) {
+            const nextUrl = new URL.URL(linkHeader.next.url);
+            if (process.env.GITLAB_IGNORE_REPO_URL) {
+              const defaultEndpoint = new URL.URL(baseUrl);
```
Comment (viceice) [inline lib/util/http/gitlab.ts:48]:
```suggestion
              const defaultEndpoint = new URL(baseUrl);
```

**Review by viceice — CHANGES_REQUESTED** [review]
This needs new tests.

**Comment by david0** [comment]
I added some tests. Not sure if thats the best way how to control the side effects of `process.env`.

File: lib/util/http/gitlab.spec.ts [hunk 3]
```diff
@@ -11,6 +11,7 @@ hostRules.add({
 });
 
 const gitlabApiHost = 'https://gitlab.com';
+const selfHostedUrl = 'http://mycompany.com';
```
Comment (viceice) [inline lib/util/http/gitlab.spec.ts:14]:
```suggestion
const selfHostedUrl = 'http://mycompany.com/gitlab';
```

File: lib/util/http/gitlab.spec.ts [hunk 4]
```diff
@@ -48,6 +49,33 @@ describe(getName(), () => {
     expect(trace).toHaveLength(3);
     expect(trace).toMatchSnapshot();
   });
+  it('paginates with GITLAB_IGNORE_REPO_URL set', async () => {
+    const gitlabIgnoreRepoUrlBefore = process.env.GITLAB_IGNORE_REPO_URL;
+    process.env.GITLAB_IGNORE_REPO_URL = 'true';
+    setBaseUrl(`${selfHostedUrl}/gitlab/api/v4/`);
```
Comment (viceice) [inline lib/util/http/gitlab.spec.ts:55]:
```suggestion
    setBaseUrl(`${selfHostedUrl}/api/v4/`);
```

File: lib/util/http/gitlab.spec.ts [hunk 5]
```diff
@@ -67,9 +95,7 @@ describe(getName(), () => {
     expect(httpMock.getTrace()).toMatchSnapshot();
   });
   it('sets baseUrl', () => {
-    expect(() =>
-      setBaseUrl('https://gitlab.renovatebot.com/api/v4/')
-    ).not.toThrow();
+    expect(() => setBaseUrl(`${selfHostedUrl}/gitlab/api/v4/`)).not.toThrow();
```
Comment (viceice) [inline lib/util/http/gitlab.spec.ts:98]:
```suggestion
    expect(() => setBaseUrl(`${selfHostedUrl}/api/v4/`)).not.toThrow();
```

File: lib/platform/gitlab/index.spec.ts [hunk 6]
```diff
@@ -300,6 +300,39 @@ describe(getName(), () => {
       });
       expect(httpMock.getTrace()).toMatchSnapshot();
     });
+    it('should fall back respecting when GITLAB_IGNORE_REPO_URL is set', async () => {
+      const gitlabIgnoreRepoUrlBefore = process.env.GITLAB_IGNORE_REPO_URL;
+      process.env.GITLAB_IGNORE_REPO_URL = 'true';
+      const selfHostedUrl = 'http://mycompany.com';
```
Comment (viceice) [inline lib/platform/gitlab/index.spec.ts:306]:
```suggestion
      const selfHostedUrl = 'http://mycompany.com/gitlab';
```

Just url visibillity, maybe better to add `/api/v4` here too.

File: lib/platform/gitlab/index.spec.ts [hunk 7]
```diff
@@ -300,6 +300,39 @@ describe(getName(), () => {
...
+      httpMock
+        .scope(selfHostedUrl)
+        .get('/gitlab/api/v4/user')
```
Comment (viceice) [inline lib/platform/gitlab/index.spec.ts:309]:
```suggestion
        .get('/api/v4/user')
```

File: lib/platform/gitlab/index.spec.ts [hunk 8]
```diff
@@ -300,6 +300,39 @@ describe(getName(), () => {
...
+        .reply(200, {
+          email: 'a@b.com',
+          name: 'Renovate Bot',
+        })
+        .get('/gitlab/api/v4/version')
```
Comment (viceice) [inline lib/platform/gitlab/index.spec.ts:314]:
```suggestion
        .get('/api/v4/version')
```

File: lib/platform/gitlab/index.spec.ts [hunk 9]
```diff
@@ -300,6 +300,39 @@ describe(getName(), () => {
...
+        .reply(200, {
+          version: '13.8',
+        });
+      gitlab.initPlatform({
+        endpoint: `${selfHostedUrl}/gitlab/api/v4`,
```
Comment (viceice) [inline lib/platform/gitlab/index.spec.ts:319]:
```suggestion
        endpoint: `${selfHostedUrl}/api/v4`,
```

File: lib/platform/gitlab/index.spec.ts [hunk 10]
```diff
@@ -300,6 +300,39 @@ describe(getName(), () => {
...
+        token: 'mytoken',
+      });
+      httpMock
+        .scope(selfHostedUrl)
+        .get('/gitlab/api/v4/projects/some%2Frepo%2Fproject')
```
Comment (viceice) [inline lib/platform/gitlab/index.spec.ts:324]:
```suggestion
        .get('/api/v4/projects/some%2Frepo%2Fproject')
```

File: lib/platform/gitlab/index.spec.ts [hunk 11]
```diff
@@ -300,6 +300,39 @@ describe(getName(), () => {
...
+        .reply(200, {
+          default_branch: 'master',
+          http_url_to_repo: `${selfHostedUrl}/gitlab/repo.git`,
```
Comment (viceice) [inline lib/platform/gitlab/index.spec.ts:327]:
```suggestion
          http_url_to_repo: `${selfHostedUrl}/some/repo/project.git`,
```

File: lib/platform/gitlab/index.spec.ts [hunk 12]
```diff
@@ -300,6 +300,39 @@ describe(getName(), () => {
...
+        .reply(200, {
+          default_branch: 'master',
+          http_url_to_repo: `${selfHostedUrl}/some/repo/project.git`,
+        });
+      await gitlab.initRepo({
+        repository: 'some/repo/project',
+        localDir: '',
+      });
+      expect(httpMock.getTrace()).toMatchSnapshot();
+      process.env.GITLAB_IGNORE_REPO_URL = gitlabIgnoreRepoUrlBefore;
```
Comment (viceice) [inline lib/platform/gitlab/index.spec.ts:334]: please do this in `beforeEach` and `afterEach`, so it's always reset.

File: lib/util/http/gitlab.spec.ts [hunk 13]
```diff
@@ -48,6 +49,33 @@ describe(getName(), () => {
...
+      })
+      .get('/api/v4/some-url&page=3')
+      .reply(200, ['d']);
+    const res = await gitlabApi.getJson('some-url', { paginate: true });
+    expect(res.body).toHaveLength(4);
+
+    const trace = httpMock.getTrace();
+    expect(trace).toHaveLength(3);
+    expect(trace).toMatchSnapshot();
+    process.env.GITLAB_IGNORE_REPO_URL = gitlabIgnoreRepoUrlBefore;
```
Comment (viceice) [inline lib/util/http/gitlab.spec.ts:77]: see other comment

File: lib/util/http/gitlab.ts [hunk 14]
```diff
@@ -42,8 +42,16 @@ export class GitlabHttp extends Http<GitlabHttpOptions, GitlabHttpOptions> {
...
           const linkHeader = parseLinkHeader(result.headers.link as string);
           if (linkHeader?.next) {
+            const nextUrl = new URL(linkHeader.next.url);
+            if (process.env.GITLAB_IGNORE_REPO_URL) {
+              const defaultEndpoint = new URL(baseUrl);
+              nextUrl.protocol = defaultEndpoint.protocol;
+              nextUrl.host = defaultEndpoint.host;
+            }
+            logger.debug(`following pagination, next url: ${nextUrl}`);
+
```
Comment (viceice) [inline lib/util/http/gitlab.ts:52]:
```suggestion
```

To many log messages

File: lib/platform/gitlab/index.ts [hunk 15]
```diff
@@ -228,13 +228,15 @@ export async function initRepo({
...
+      const { protocol, host, pathname } = URL.parse(defaults.endpoint);
+      const newPathname = pathname.slice(0, pathname.indexOf('/api'));
       url = git.getUrl({
         protocol: protocol.slice(0, -1) as any,
         auth: 'oauth2:' + opts.token,
         host,
-        repository,
+        repository: newPathname + '/' + repository,
       });
+      logger.debug(`using URL ${url} based on configured endpoint`);
```
Comment (viceice) [inline lib/platform/gitlab/index.ts:239]:
```suggestion
      logger.debug({ url }, `using URL based on configured endpoint`);
```

File: lib/platform/gitlab/index.spec.ts [hunk 16]
```diff
@@ -45,9 +46,11 @@ describe(getName(), () => {
     });
     httpMock.reset();
     httpMock.setup();
+    process.env = { ...envBefore };
   });
   afterEach(() => {
     httpMock.reset();
+    process.env = envBefore;
```
Comment (viceice) [inline lib/platform/gitlab/index.spec.ts:53]:
```suggestion
```

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/util/http/gitlab.spec.ts [hunk 17]
```diff
@@ -11,19 +11,23 @@ hostRules.add({
...
 
 describe(getName(), () => {
   let gitlabApi: GitlabHttp;
+  const envBefore = process.env;
 
   beforeEach(() => {
     gitlabApi = new GitlabHttp();
     setBaseUrl(`${gitlabApiHost}/api/v4/`);
     httpMock.setup();
+    process.env = { ...envBefore };
```
[the remark this answers is not in the document]
Comment (david0) [reply lib/util/http/gitlab.spec.ts:24]: I can do that, but if GITLAB_IGNORE_REPO_URL was set before it will vanish then too.

[the remark this answers is not in the document]
Comment (viceice) [reply lib/util/http/gitlab.spec.ts:24]: sure, but it shouldn't be set for tests anyways and it will only be deletet in jest tests, not when you do a real run.

File: lib/platform/gitlab/index.ts [hunk 18]
```diff
@@ -228,13 +228,15 @@ export async function initRepo({
       res.body.http_url_to_repo === null
     ) {
       logger.debug('no http_url_to_repo found. Falling back to old behaviour.');
-      const { host, protocol } = URL.parse(defaults.endpoint);
+      const { protocol, host, pathname } = URL.parse(defaults.endpoint);
```
[the remark this answers is not in the document]
Comment (david0) [reply lib/platform/gitlab/index.ts:231]: Your wish is my command, but is there any advantage here in the exception-swallowing `parseUrl` vs plain `new URL(baseUrl)`?

[the remark this answers is not in the document]
Comment (viceice) [reply lib/platform/gitlab/index.ts:231]: We are unifying our url handling, so all parsings should be done with same function. Also `parseUrl` never throws for invalid urls and returns `null`

File: lib/platform/gitlab/index.spec.ts [hunk 19]
```diff
@@ -300,6 +301,37 @@ describe(getName(), () => {
...
+        .get('/api/v4/projects/some%2Frepo%2Fproject')
+        .reply(200, {
+          default_branch: 'master',
+          http_url_to_repo: `${selfHostedUrl}/some/repo/project.git`,
+        });
+      await gitlab.initRepo({
+        repository: 'some/repo/project',
+        localDir: '',
+      });
+      expect(httpMock.getTrace()).toMatchSnapshot();
```
Comment (viceice) [inline lib/platform/gitlab/index.spec.ts:333]:
```suggestion
      expect(git.initRepo.mock.calls).toMatchSnapshot();
      expect(httpMock.getTrace()).toMatchSnapshot();
```
so we can match and see if the url is patched the right way

**Comment by viceice** [comment]
Please do a real run against gitlab again to verify latest implementation.

**Comment by david0** [comment]
I've re-run against our gitlab and it still works 👍

**Review by viceice — COMMENTED** [review]
I think you missed the snapshot updates

**Comment by viceice** [comment]
also a `yarn lint-fix` needs to be run

File: lib/util/http/gitlab.spec.ts [hunk 20]
```diff
@@ -46,6 +48,29 @@ describe(getName(), () => {
...
   });
+  it('paginates with GITLAB_IGNORE_REPO_URL set', async () => {
+    process.env.GITLAB_IGNORE_REPO_URL = 'true';
+    setBaseUrl(`${selfHostedUrl}/api/v4/`);
+
+    httpMock
+      .scope(selfHostedUrl)
+      .get('/api/v4/some-url')
+      .reply(200, ['a'], {
+        link: '<https://mycompany.com/gitlab/api/v4/some-url&page=2>; rel="next", <https://mycompany.com/gitlab/api/v4/some-url&page=3>; rel="last"',
```
Comment (viceice) [inline lib/util/http/gitlab.spec.ts:59]:
```suggestion
        link: '<https://other.host.com/gitlab/api/v4/some-url&page=2>; rel="next", <https://other.host.com/gitlab/api/v4/some-url&page=3>; rel="last"',
```

You want to test the hostname overide, so you should send back a wrong hostname too.

File: lib/util/http/gitlab.spec.ts [hunk 21]
```diff
@@ -46,6 +48,29 @@ describe(getName(), () => {
...
+      })
+      .get('/api/v4/some-url&page=2')
+      .reply(200, ['b', 'c'], {
+        link: '<https://mycompany.com/gitlab/api/v4/some-url&page=3>; rel="next", <https://mycompany.com/gitlab/api/v4/some-url&page=3>; rel="last"',
```
Comment (viceice) [inline lib/util/http/gitlab.spec.ts:63]:
```suggestion
        link: '<https://other.host.com/gitlab/api/v4/some-url&page=3>; rel="next", <https://other.host.com/gitlab/api/v4/some-url&page=3>; rel="last"',
```

File: lib/platform/gitlab/__snapshots__/index.spec.ts.snap [hunk 22]
```diff
@@ -2039,6 +2039,61 @@ Array [
...
+  Array [
+    Object {
+      "cloneSubmodules": undefined,
+      "defaultBranch": "master",
+      "gitAuthorEmail": undefined,
+      "gitAuthorName": undefined,
+      "ignorePrAuthor": undefined,
+      "mergeMethod": "merge",
+      "repository": "some%2Frepo%2Fproject",
+      "url": undefined,
```
Comment (viceice) [inline lib/platform/gitlab/__snapshots__/index.spec.ts.snap:2053]: You test seems to behave wrong, this url shouldn't be `undefined`

File: lib/platform/gitlab/index.spec.ts [hunk 23]
```diff
@@ -290,6 +291,38 @@ describe(getName(), () => {
...
+      await gitlab.initPlatform({
+        endpoint: `${selfHostedUrl}/api/v4`,
+        token: 'mytoken',
+      });
+      httpMock
+        .scope(selfHostedUrl)
+        .get('/api/v4/projects/some%2Frepo%2Fproject')
+        .reply(200, {
+          default_branch: 'master',
+          http_url_to_repo: `${selfHostedUrl}/some/repo/project.git`,
```
Comment (viceice) [inline lib/platform/gitlab/index.spec.ts:318]:
```suggestion
          http_url_to_repo: `https://other.host.com/gitlab/some/repo/project.git`,
```

See other comments, you like to test that it really ingores this url.

**Review by viceice — CHANGES_REQUESTED** [review]

File: lib/util/http/gitlab.spec.ts (hunk 20 above)
Comment (david0) [reply lib/util/http/gitlab.spec.ts:59]: It kind of is already (http vs https) but I guess it would be more obvious if i change the hostname too.

File: lib/platform/gitlab/__snapshots__/index.spec.ts.snap (hunk 22 above)
Comment (viceice) [reply lib/platform/gitlab/__snapshots__/index.spec.ts.snap:2053]: sure, use `URL.format`

Comment (david0) [reply lib/platform/gitlab/__snapshots__/index.spec.ts.snap]: Done (also tested on our gitlab)

**Review by viceice — APPROVED** [review]
