### PR TITLE
fix(docker): fix manifest list handling

### LINKED ISSUE #8468: Docker Cannot read property 'digest' of undefined
<!--
      PLEASE DO NOT REPORT ANY SECURITY CONCERNS THIS WAY
      Email renovate-disclosure@whitesourcesoftware.com instead.
-->

**What Renovate type, platform and version are you using?**

Kubernetes Self Hosted Renovate 24.30.0 and Gitlab as the platform.

**Describe the bug**

Looks like the dockerfiles are not being parsed correctly nor something related.

**Relevant debug logs**

```
  INFO: Repository started (repository=gitlab/repository/foo)                                                                                                                                                                    
        "renovateVersion": "24.30.0"                                                                                                                                                                                                           
  INFO: Dependency extraction complete (repository=gitlab/repository/foo)                                                                                                                                                        
        "baseBranch": "master",                                                                                                                                                                                                                
        "stats": {                                                                                                                                                                                                                             
          "managers": {                                                                                                                                                                                                                        
            "dockerfile": {"fileCount": 1, "depCount": 1},                                                                                                                                                                                     
            "gitlabci-include": {"fileCount": 1, "depCount": 1},                                                                                                                                                                               
            "pip_requirements": {"fileCount": 1, "depCount": 1}                                                                                                                                                                                
          },                                                                                                                                                                                                                                   
          "total": {"fileCount": 3, "depCount": 3}                                                                                                                                                                                             
        }                                                                                                                                                                                                                                      
  INFO: Repository finished (repository=gitlab/repository/foo)                                                                                                                                                                   
        "durationMs": 6696                                                                                                                                                                                                                     
  INFO: Repository started (repository=gitlab/repository/bar)                                                                                                                                                                       
        "renovateVersion": "24.30.0"                                                                                                                                                                                                           
  INFO: Dependency extraction complete (repository=gitlab/repository/bar)                                                                                                                                                           
        "baseBranch": "master",                                                                                                                                                                                                                
        "stats": {                                                                                                                                                                                                                             
          "managers": {                                                                                                                                                                                                                        
            "dockerfile": {"fileCount": 2, "depCount": 2},                                                                                                                                                                                     
            "gitlabci": {"fileCount": 1, "depCount": 6},                                                                                                                                                                                       
            "pip_requirements": {"fileCount": 1, "depCount": 2}                                                                                                                                                                                
          },                                                                                                                                                                                                                                   
          "total": {"fileCount": 4, "depCount": 10}                                                                                                                                                                                            
        }                                                                                                                                                                                                                                      
  INFO: Unknown error getting Docker labels (repository=gitlab/repository/bar)                                                                                                                                                      
        "registry": "https://index.docker.io",                                                                                                                                                                                                 
        "dockerRepository": "library/alpine",                                                                                                                                                                                                  
        "tag": "latest",                                                                                                                                                                                                                       
        "err": {                                                                                                                                                                                                                               
          "message": "Cannot read property 'digest' of undefined",                                                                                                                                                                             
          "stack": "TypeError: Cannot read property 'digest' of undefined\n    at getLabels (/usr/src/app/node_modules/renovate/lib/datasource/docker/index.ts:513:38)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5 
 )\n    at Object.getReleases (/usr/src/app/node_modules/renovate/lib/datasource/docker/index.ts:623:18)\n    at getRegistryReleases (/usr/src/app/node_modules/renovate/lib/datasource/index.ts:55:15)\n    at fetchReleases (/usr/src/app/no 
 de_modules/renovate/lib/datasource/index.ts:192:15)\n    at Object.getPkgReleases (/usr/src/app/node_modules/renovate/lib/datasource/index.ts:253:7)\n    at Object.lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/ 
 process/lookup/index.ts:166:30)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:44:26)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"                                            
        }                                                                                                                                                                                                                                      
  INFO: Unknown error getting Docker labels (repository=gitlab/repository/bar)                                                                                                                                                      
        "registry": "https://index.docker.io",                                                                                                                                                                                                 
        "dockerRepository": "library/docker",                                                                                                                                                                                                  
        "tag": "latest",                                                                                                                                                                                                                       
        "err": {                                                                                                                                                                                                                               
          "message": "Cannot read property 'digest' of undefined",                                                                                                                                                                             
          "stack": "TypeError: Cannot read property 'digest' of undefined\n    at getLabels (/usr/src/app/node_modules/renovate/lib/datasource/docker/index.ts:513:38)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5 
 )\n    at Object.getReleases (/usr/src/app/node_modules/renovate/lib/datasource/docker/index.ts:623:18)\n    at getRegistryReleases (/usr/src/app/node_modules/renovate/lib/datasource/index.ts:55:15)\n    at fetchReleases (/usr/src/app/no 
 de_modules/renovate/lib/datasource/index.ts:192:15)\n    at Object.getPkgReleases (/usr/src/app/node_modules/renovate/lib/datasource/index.ts:253:7)\n    at Object.lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/ 
 process/lookup/index.ts:166:30)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:44:26)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"                                            
        }                                                                                                                                                                                                                                      
  INFO: Repository finished (repository=gitlab/repository/bar)                                                                                                                                                                      
        "durationMs": 9378 
```

**Have you created a minimal reproduction repository?**

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I can provide any additional info if you need it.

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

If we get a manifest list, we need to fetch the image manifest (using first image). hopefully there is always atleast one child image.

## Context:

closes #8468

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

File: lib/datasource/docker/index.ts [hunk 1]
```diff
@@ -328,6 +328,52 @@ async function getManifestResponse(
...
+  // istanbul ignore if
+  if (!manifestResponse) {
+    logger.debug(
+      {
+        registry,
+        dockerRepository: repository,
+        tag,
+      },
+      'docker registry failure: failed to get manifest for tag'
+    );
```
Comment (viceice) [inline lib/datasource/docker/index.ts:349]: I think we can remove this, as `getManifestResponse` already logs any errors before returning `null`
```suggestion
```

**Review by rarkins — APPROVED** [review]
