### PR TITLE
fix(manager/helm): add hostType for helm dependencies during artifactupdate

### LINKED ISSUE #17573: Helm lock repo auth for private github repositories
### What would you like Renovate to be able to do?

Make sure that renovate can update the lock file of private helm charts.

Part of an issue I was having with Helmv3 lock file updates

https://github.com/renovatebot/renovate/discussions/17567

I have put together a test repo [here](https://github.com/robgordon89/renovate-test) and a test helm chart repo [here](https://github.com/robgordon89/charts-test)

You should be able to reproduce this easily using the above examples.

Without auth, it works as intended 👍 

### If you have any ideas on how this should be implemented, please tell us here.

unsure how to resolve but more information can be found on https://github.com/renovatebot/renovate/discussions/17567

### Is this a feature you are interested in implementing yourself?

No

### PR DESCRIPTION
**Pull request by secustor**
## Changes
Adds hostType during search for host rules in the case of Helm registries and not only if looking up a Docker registry. 

## Context
Closes #17573

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/helmv3/artifacts.ts [hunk 1]
```diff
@@ -71,6 +72,7 @@ async function helmCommands(
         ...value,
         hostRule: hostRules.find({
           url: value.repository,
+          hostType: HelmDatasource.id,
```
Comment (viceice) [inline lib/modules/manager/helmv3/artifacts.ts:75]: please add some info about this to the readme

**Review by viceice — COMMENTED** [review]
otherwise LGTM

**Review by viceice — APPROVED** [review]
