### PR TITLE
fix(docker): Skip lookup of dependencies with variable in image name

### LINKED ISSUE #13425: Dockerfile and gitlabci manager fail to detect variables at the start of image strings
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.21.0

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

github.com

### Describe the bug

Dockerfile (and gitlabci manager through the same function) try filter out image strings that contain variables. It seems to fail to detect a variable if it is at the start of the string. 

Reproduction repo [is here](https://github.com/rv2673/renovate-test)

I think(though haven't confirmed it yet) [the condition here](https://github.com/renovatebot/renovate/blob/f32871e496ab8a4a675b8b40124d76fd77b68a6a/lib/manager/dockerfile/extract.ts#L28) should be updated. 

### Relevant debug logs
<details><summary>Logs</summary>

```
DEBUG: Found dockerfile package files (repository=rv2673/renovate-test)
DEBUG: Found github-actions package files (repository=rv2673/renovate-test)
DEBUG: Found gitlabci package files (repository=rv2673/renovate-test)
DEBUG: Found 6 package file(s) (repository=rv2673/renovate-test)
 INFO: Dependency extraction complete (repository=rv2673/renovate-test)
       "baseBranch": "main",
       "stats": {
         "managers": {
           "dockerfile": {"fileCount": 4, "depCount": 4},
           "github-actions": {"fileCount": 1, "depCount": 2},
           "gitlabci": {"fileCount": 1, "depCount": 3}
         },
         "total": {"fileCount": 6, "depCount": 9}
       }
DEBUG: Dependency ubuntu has unsupported value focal-20211006 (repository=rv2673/renovate-test)
DEBUG: getDigest(https://index.docker.io, library/ubuntu, focal-20211006) (repository=rv2673/renovate-test)
DEBUG: Dependency ${REGISTRY:-docker.io}/ubuntu has unsupported value focal-20211006 (repository=rv2673/renovate-test)
DEBUG: getDigest(https://${REGISTRY:-docker.io}, ubuntu, focal-20211006) (repository=rv2673/renovate-test)
DEBUG: Dependency $REGISTRY/ubuntu has unsupported value focal-20211006 (repository=rv2673/renovate-test)
DEBUG: getDigest(https://index.docker.io, $REGISTRY/ubuntu, focal-20211006) (repository=rv2673/renovate-test)
DEBUG: Dependency ${REGISTRY}/ubuntu has unsupported value focal-20211006 (repository=rv2673/renovate-test)
DEBUG: getDigest(https://index.docker.io, ${REGISTRY}/ubuntu, focal-20211006) (repository=rv2673/renovate-test)
DEBUG: getManifestResponse(https://index.docker.io, library/ubuntu, focal-20211006) (repository=rv2673/renovate-test)
DEBUG: getManifestResponse(https://${REGISTRY:-docker.io}, ubuntu, focal-20211006) (repository=rv2673/renovate-test)
 WARN: Error obtaining docker token (repository=rv2673/renovate-test)
       "registryHost": "https://${REGISTRY:-docker.io}",
       "dockerRepository": "ubuntu",
       "err": {
         "input": "https://${REGISTRY:-docker.io}/v2/",
         "code": "ERR_INVALID_URL",
         "message": "Invalid URL: https://${REGISTRY:-docker.io}/v2/",
         "stack": "TypeError [ERR_INVALID_URL]: Invalid URL: https://${REGISTRY:-docker.io}/v2/\n    at new NodeError (internal/errors.js:322:7)\n    at onParseError (internal/url.js:270:9)\n    at new URL (internal/url.js:346:5)\n    at Object.exports.default (/usr/src/app/node_modules/got/dist/source/core/utils/options-to-url.js:35:17)\n    at normalizeArguments (/usr/src/app/node_modules/got/dist/source/core/index.js:486:51)\n    at got (/usr/src/app/node_modules/got/dist/source/create.js:112:39)\n    at gotRoutine (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:96:25)\n    at queueTask (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:174:16)\n    at Http.request (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:181:45)\n    at Http.get (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:201:17)\n    at getAuthHeaders (/usr/src/app/node_modules/renovate/lib/datasource/docker/common.ts:65:41)\n    at getManifestResponse (/usr/src/app/node_modules/renovate/lib/datasource/docker/common.ts:286:27)\n    at Object.getDigest (/usr/src/app/node_modules/renovate/lib/datasource/docker/index.ts:195:53)\n    at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:352:34)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:38:13)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       }
DEBUG: No docker auth found - returning (repository=rv2673/renovate-test)
DEBUG: getManifestResponse(https://index.docker.io, $REGISTRY/ubuntu, focal-20211006) (repository=rv2673/renovate-test)
DEBUG: getManifestResponse(https://index.docker.io, ${REGISTRY}/ubuntu, focal-20211006) (repository=rv2673/renovate-test)
DEBUG: Datasource 404 (repository=rv2673/renovate-test)
       "datasource": "docker",
       "lookupName": "$CI_REGISTRY/nginx",
       "url": "https://index.docker.io/v2/$CI_REGISTRY/nginx/tags/list?n=10000"
DEBUG: Failed to look up dependency $CI_REGISTRY/nginx (repository=rv2673/renovate-test, packageFile=.gitlab-ci.yml, dependency=$CI_REGISTRY/nginx)
DEBUG: Datasource 404 (repository=rv2673/renovate-test)
       "datasource": "docker",
       "lookupName": "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/hadolint/hadolint",
       "url": "https://index.docker.io/v2/$%7BCI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX%7D/hadolint/hadolint/tags/list?n=10000"
DEBUG: Failed to look up dependency ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/hadolint/hadolint (repository=rv2673/renovate-test, packageFile=.gitlab-ci.yml, dependency=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/hadolint/hadolint)
DEBUG: Docker Manifest is unknown (repository=rv2673/renovate-test)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1641569710783,
           "socket": 1641569710784,
           "lookup": 1641569710870,
           "connect": 1641569710926,
           "secureConnect": 1641569711035,
           "upload": 1641569711035,
           "response": 1641569711092,
           "end": 1641569711092,
           "phases": {
             "wait": 1,
             "dns": 86,
             "tcp": 56,
             "tls": 109,
             "request": 0,
             "firstByte": 57,
             "download": 0,
             "total": 309
           }
         },
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/31.21.0 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v2+json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://index.docker.io/v2/$%7BREGISTRY%7D/ubuntu/manifests/focal-20211006",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "HEAD",
           "http2": false
         },
         "response": {
           "statusCode": 404,
           "statusMessage": "Not Found",
           "body": "",
           "headers": {
             "content-type": "text/plain; charset=utf-8",
             "docker-distribution-api-version": "registry/2.0",
             "x-content-type-options": "nosniff",
             "date": "Fri, 07 Jan 2022 15:35:11 GMT",
             "content-length": "19",
             "strict-transport-security": "max-age=31536000",
             "docker-ratelimit-source": "20.118.170.218",
             "connection": "close"
           },
           "httpVersion": "1.1"
         }
       },
       "registryHost": "https://index.docker.io",
       "dockerRepository": "${REGISTRY}/ubuntu",
       "tag": "focal-20211006"
DEBUG: Docker Manifest is unknown (repository=rv2673/renovate-test)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1641569710778,
           "socket": 1641569710778,
           "lookup": 1641569710869,
           "connect": 1641569710926,
           "secureConnect": 1641569711044,
           "upload": 1641569711044,
           "response": 1641569711102,
           "end": 1641569711102,
           "phases": {
             "wait": 0,
             "dns": 91,
             "tcp": 57,
             "tls": 118,
             "request": 0,
             "firstByte": 58,
             "download": 0,
             "total": 324
           }
         },
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/31.21.0 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v2+json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://index.docker.io/v2/$REGISTRY/ubuntu/manifests/focal-20211006",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "HEAD",
           "http2": false
         },
         "response": {
           "statusCode": 404,
           "statusMessage": "Not Found",
           "body": "",
           "headers": {
             "content-type": "text/plain; charset=utf-8",
             "docker-distribution-api-version": "registry/2.0",
             "x-content-type-options": "nosniff",
             "date": "Fri, 07 Jan 2022 15:35:11 GMT",
             "content-length": "19",
             "strict-transport-security": "max-age=31536000",
             "docker-ratelimit-source": "20.118.170.218",
             "connection": "close"
           },
           "httpVersion": "1.1"
         }
       },
       "registryHost": "https://index.docker.io",
       "dockerRepository": "$REGISTRY/ubuntu",
       "tag": "focal-20211006"
DEBUG: getLabels(https://index.docker.io, library/alpine, latest) (repository=rv2673/renovate-test)
DEBUG: getManifestResponse(https://index.docker.io, library/alpine, latest) (repository=rv2673/renovate-test)
DEBUG: Got docker digest (repository=rv2673/renovate-test)
       "digest": "sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322"
DEBUG: getManifestResponse(https://index.docker.io, library/alpine, sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3) (repository=rv2673/renovate-test)
DEBUG: getDigest(https://index.docker.io, library/alpine, 3.15.0) (repository=rv2673/renovate-test)
DEBUG: getManifestResponse(https://index.docker.io, library/alpine, 3.15.0) (repository=rv2673/renovate-test)
DEBUG: Got docker digest (repository=rv2673/renovate-test)
       "digest": "sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300"
DEBUG: getDigest(https://index.docker.io, library/alpine, 3.13.6) (repository=rv2673/renovate-test)
DEBUG: getManifestResponse(https://index.docker.io, library/alpine, 3.13.6) (repository=rv2673/renovate-test)
DEBUG: Got docker digest (repository=rv2673/renovate-test)
       "digest": "sha256:2582893dec6f12fd499d3a709477f2c0c0c1dfcd28024c93f1f0626b9e3540c8"
DEBUG: Package releases lookups complete (repository=rv2673/renovate-test)
       "baseBranch": "main"
DEBUG: branchifyUpgrades (repository=rv2673/renovate-test)
DEBUG: Using group branchName template (repository=rv2673/renovate-test)
DEBUG: Dependency ubuntu is part of group Docker digests (repository=rv2673/renovate-test)
DEBUG: Using group branchName template (repository=rv2673/renovate-test)
DEBUG: Dependency actions/checkout is part of group all minor dependencies (repository=rv2673/renovate-test)
DEBUG: Using group branchName template (repository=rv2673/renovate-test)
DEBUG: Dependency actions/checkout is part of group Pin Dependencies (repository=rv2673/renovate-test)
DEBUG: Using group branchName template (repository=rv2673/renovate-test)
DEBUG: Dependency renovatebot/github-action is part of group Pin Dependencies (repository=rv2673/renovate-test)
DEBUG: Using group branchName template (repository=rv2673/renovate-test)
DEBUG: Dependency alpine is part of group all minor dependencies (repository=rv2673/renovate-test)
DEBUG: Using group branchName template (repository=rv2673/renovate-test)
DEBUG: Dependency alpine is part of group Docker digests (repository=rv2673/renovate-test)
DEBUG: 6 flattened updates found: ubuntu, actions/checkout, actions/checkout, renovatebot/github-action, alpine, alpine (repository=rv2673/renovate-test)
DEBUG: Returning 3 branch(es) (repository=rv2673/renovate-test)
DEBUG: Fetching changelog: https://github.com/actions/checkout (v2.0.0 -> v2.4.0) (repository=rv2673/renovate-test)
DEBUG: config.repoIsOnboarded=true (repository=rv2673/renovate-test)
DEBUG: packageFiles with updates (repository=rv2673/renovate-test)
       "config": {
         "dockerfile": [
           {
             "packageFile": "Dockerfile",
             "deps": [
               {
                 "depName": "ubuntu",
                 "currentValue": "focal-20211006",
                 "replaceString": "ubuntu:focal-20211006",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "versioning": "ubuntu",
                 "depType": "final",
                 "depIndex": 0,
                 "updates": [
                   {
                     "updateType": "pin",
                     "newValue": "focal-20211006",
                     "newDigest": "sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322",
                     "branchName": "renovate/digests-pin"
                   }
                 ],
                 "warnings": []
               }
             ]
           },
           {
             "packageFile": "var_with_default.Dockerfile",
             "deps": [
               {
                 "depName": "${REGISTRY:-docker.io}/ubuntu",
                 "currentValue": "focal-20211006",
                 "replaceString": "${REGISTRY:-docker.io}/ubuntu:focal-20211006",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "final",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "docker"
               }
             ]
           },
           {
             "packageFile": "var_without_bracket.Dockerfile",
             "deps": [
               {
                 "depName": "$REGISTRY/ubuntu",
                 "currentValue": "focal-20211006",
                 "replaceString": "$REGISTRY/ubuntu:focal-20211006",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "final",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "docker"
               }
             ]
           },
           {
             "packageFile": "var_without_default.Dockerfile",
             "deps": [
               {
                 "depName": "${REGISTRY}/ubuntu",
                 "currentValue": "focal-20211006",
                 "replaceString": "${REGISTRY}/ubuntu:focal-20211006",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "final",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "docker"
               }
             ]
           }
         ],
         "github-actions": [
           {
             "packageFile": ".github/workflows/main.yml",
             "deps": [
               {
                 "depName": "actions/checkout",
                 "commitMessageTopic": "{{{depName}}} action",
                 "datasource": "github-tags",
                 "versioning": "docker",
                 "depType": "action",
                 "replaceString": "actions/checkout@v2.0.0",
                 "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # renovate: tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
                 "currentValue": "v2.0.0",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "v2.4.0",
                     "newValue": "v2.4.0",
                     "releaseTimestamp": "2021-11-02T17:48:06.000Z",
                     "newMajor": 2,
                     "newMinor": 4,
                     "updateType": "minor",
                     "newDigest": "ec3a7ce113134d7a93b817d10a8272cb61118579",
                     "branchName": "renovate/all-minor"
                   },
                   {
                     "updateType": "pin",
                     "newValue": "v2.0.0",
                     "newDigest": "722adc63f1aa60a57ec37892e133b1d319cae598",
                     "branchName": "renovate/pin-dependencies"
                   }
                 ],
                 "warnings": [],
                 "sourceUrl": "https://github.com/actions/checkout",
                 "currentVersion": "v2.0.0",
                 "isSingleVersion": true,
                 "fixedVersion": "v2.0.0"
               },
               {
                 "depName": "renovatebot/github-action",
                 "commitMessageTopic": "{{{depName}}} action",
                 "datasource": "github-tags",
                 "versioning": "docker",
                 "depType": "action",
                 "replaceString": "renovatebot/github-action@v31.21.0",
                 "autoReplaceStringTemplate": "{{depName}}@{{#if newDigest}}{{newDigest}}{{#if newValue}} # renovate: tag={{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
                 "currentValue": "v31.21.0",
                 "depIndex": 1,
                 "updates": [
                   {
                     "updateType": "pin",
                     "newValue": "v31.21.0",
                     "newDigest": "92f55e94f29c376445df6ef9eead1967b40dee02",
                     "branchName": "renovate/pin-dependencies"
                   }
                 ],
                 "warnings": [],
                 "sourceUrl": "https://github.com/renovatebot/github-action",
                 "currentVersion": "v31.21.0",
                 "fixedVersion": "v31.21.0"
               }
             ]
           }
         ],
         "gitlabci": [
           {
             "packageFile": ".gitlab-ci.yml",
             "deps": [
               {
                 "depName": "alpine",
                 "currentValue": "3.13.6",
                 "replaceString": "alpine:3.13.6",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "image",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "3.15.0",
                     "newValue": "3.15.0",
                     "newMajor": 3,
                     "newMinor": 15,
                     "updateType": "minor",
                     "newDigest": "sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300",
                     "branchName": "renovate/all-minor"
                   },
                   {
                     "updateType": "pin",
                     "newValue": "3.13.6",
                     "newDigest": "sha256:2582893dec6f12fd499d3a709477f2c0c0c1dfcd28024c93f1f0626b9e3540c8",
                     "branchName": "renovate/digests-pin"
                   }
                 ],
                 "warnings": [],
                 "versioning": "docker",
                 "currentVersion": "3.13.6",
                 "isSingleVersion": true,
                 "fixedVersion": "3.13.6"
               },
               {
                 "depName": "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/hadolint/hadolint",
                 "currentValue": "v2.7.0",
                 "replaceString": "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/hadolint/hadolint:v2.7.0",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "image",
                 "depIndex": 1,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/hadolint/hadolint",
                     "message": "Failed to look up dependency ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/hadolint/hadolint"
                   }
                 ],
                 "versioning": "docker"
               },
               {
                 "depName": "$CI_REGISTRY/nginx",
                 "currentValue": "1.21.4",
                 "replaceString": "$CI_REGISTRY/nginx:1.21.4",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "image",
                 "depIndex": 2,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "$CI_REGISTRY/nginx",
                     "message": "Failed to look up dependency $CI_REGISTRY/nginx"
                   }
                 ],
                 "versioning": "docker"
               }
             ]
           }
         ]
       }
DEBUG: processRepo() (repository=rv2673/renovate-test)
DEBUG: Processing 3 branches: renovate/all-minor, renovate/digests-pin, renovate/pin-dependencies (repository=rv2673/renovate-test)
DEBUG: Calculating hourly PRs remaining (repository=rv2673/renovate-test)
DEBUG: Retrieving PR list (repository=rv2673/renovate-test)
DEBUG: Retrieved 2 Pull Requests (repository=rv2673/renovate-test)
DEBUG: currentHourStart=2022-01-07T15:00:00.000+00:00 (repository=rv2673/renovate-test)
DEBUG: PR hourly limit remaining: 1 (repository=rv2673/renovate-test)
DEBUG: Calculating prConcurrentLimit (10) (repository=rv2673/renovate-test)
DEBUG: getBranchPr(renovate/digests-pin) (repository=rv2673/renovate-test)
DEBUG: findPr(renovate/digests-pin, undefined, open) (repository=rv2673/renovate-test)
DEBUG: Found PR #6 (repository=rv2673/renovate-test)
DEBUG: Returning from graphql open PR list (repository=rv2673/renovate-test)
DEBUG: getBranchPr(renovate/pin-dependencies) (repository=rv2673/renovate-test)
DEBUG: findPr(renovate/pin-dependencies, undefined, open) (repository=rv2673/renovate-test)
DEBUG: findPr(renovate/pin-dependencies, undefined, closed) (repository=rv2673/renovate-test)
DEBUG: getBranchPr(renovate/all-minor) (repository=rv2673/renovate-test)
DEBUG: findPr(renovate/all-minor, undefined, open) (repository=rv2673/renovate-test)
DEBUG: findPr(renovate/all-minor, undefined, closed) (repository=rv2673/renovate-test)
DEBUG: 1 PRs are currently open (repository=rv2673/renovate-test)
DEBUG: PR concurrent limit remaining: 9 (repository=rv2673/renovate-test)
DEBUG: Calculated maximum PRs remaining this run (repository=rv2673/renovate-test)
       "prsRemaining": 1
DEBUG: PullRequests limit = 1 (repository=rv2673/renovate-test)
DEBUG: Calculating hourly PRs remaining (repository=rv2673/renovate-test)
DEBUG: currentHourStart=2022-01-07T15:00:00.000+00:00 (repository=rv2673/renovate-test)
DEBUG: PR hourly limit remaining: 1 (repository=rv2673/renovate-test)
DEBUG: Calculating branchConcurrentLimit (10) (repository=rv2673/renovate-test)
DEBUG: 1 already existing branches found: renovate/digests-pin (repository=rv2673/renovate-test)
DEBUG: Branch concurrent limit remaining: 9 (repository=rv2673/renovate-test)
DEBUG: Calculated maximum branches remaining this run (repository=rv2673/renovate-test)
       "branchesRemaining": 1
DEBUG: Branches limit = 1 (repository=rv2673/renovate-test)
DEBUG: Setting current branch to main (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: latest commit (repository=rv2673/renovate-test, branch=renovate/digests-pin)
       "branchName": "main",
       "latestCommitDate": "2022-01-07T16:34:23+01:00"
DEBUG: branchExists=true (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: dependencyDashboardCheck=undefined (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: PR rebase requested=false (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Checking if PR has been edited (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Branch has not been modified (repository=rv2673/renovate-test, branch=renovate/digests-pin)
       "branchName": "renovate/digests-pin"
DEBUG: Found existing branch PR (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Checking schedule(at any time, null) (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: No schedule defined (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Branch already exists (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: isBranchStale=true (repository=rv2673/renovate-test, branch=renovate/digests-pin)
       "isStale": true,
       "currentBranch": "main",
       "currentBranchSha": "95bafafbce20fc538204966fb20a6bf8c8ae4a21"
DEBUG: Branch is stale and needs rebasing (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Branch is unmodified, so can be rebased (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Using reuseExistingBranch: false (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Starting search at index 42 (repository=rv2673/renovate-test, packageFile=.gitlab-ci.yml, branch=renovate/digests-pin)
       "depName": "alpine"
DEBUG: Found match at index 42 (repository=rv2673/renovate-test, packageFile=.gitlab-ci.yml, branch=renovate/digests-pin)
       "depName": "alpine"
DEBUG: Contents updated (repository=rv2673/renovate-test, packageFile=.gitlab-ci.yml, branch=renovate/digests-pin)
       "depName": "alpine"
DEBUG: Starting search at index 20 (repository=rv2673/renovate-test, packageFile=Dockerfile, branch=renovate/digests-pin)
       "depName": "ubuntu"
DEBUG: Found match at index 20 (repository=rv2673/renovate-test, packageFile=Dockerfile, branch=renovate/digests-pin)
       "depName": "ubuntu"
DEBUG: Contents updated (repository=rv2673/renovate-test, packageFile=Dockerfile, branch=renovate/digests-pin)
       "depName": "ubuntu"
DEBUG: Updated 2 package files (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: No updated lock files in branch (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: 2 file(s) to commit (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Committing files to branch renovate/digests-pin (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Setting git author name (repository=rv2673/renovate-test, branch=renovate/digests-pin)
       "gitAuthorName": "Renovate Bot"
DEBUG: Setting git author email (repository=rv2673/renovate-test, branch=renovate/digests-pin)
       "gitAuthorEmail": "renovate@whitesourcesoftware.com"
DEBUG: git commit (repository=rv2673/renovate-test, branch=renovate/digests-pin)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/digests-pin",
         "commit": "f362455",
         "root": false,
         "summary": {"changes": 2, "insertions": 2, "deletions": 2}
       }
DEBUG: git push (repository=rv2673/renovate-test, branch=renovate/digests-pin)
       "result": {
         "pushed": [],
         "branch": {
           "local": "renovate/digests-pin",
           "remote": "renovate/digests-pin",
           "remoteName": "origin"
         },
         "ref": {"local": "refs/remotes/origin/renovate/digests-pin"},
         "remoteMessages": {"all": []}
       }
 INFO: Branch updated (repository=rv2673/renovate-test, branch=renovate/digests-pin)
       "commitSha": "f362455"
DEBUG: Checking if we can automerge branch (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: mergeStatus=no automerge (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Ensuring PR (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: There are 0 errors and 0 warnings (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Found existing PR (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Processing existing PR (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Pull Request #6 does not need updating (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: PR is not configured for automerge (repository=rv2673/renovate-test, branch=renovate/digests-pin)
DEBUG: Setting current branch to main (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: latest commit (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
       "branchName": "main",
       "latestCommitDate": "2022-01-07T16:34:23+01:00"
DEBUG: getBranchPr(renovate/pin-dependencies) (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: findPr(renovate/pin-dependencies, undefined, open) (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: findPr(renovate/pin-dependencies, undefined, closed) (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: branchExists=false (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: dependencyDashboardCheck=undefined (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: recreateClosed is true (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: Checking schedule(at any time, null) (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: No schedule defined (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: Branch needs creating (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: Using reuseExistingBranch: false (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: Starting search at index 136 (repository=rv2673/renovate-test, packageFile=.github/workflows/main.yml, branch=renovate/pin-dependencies)
       "depName": "actions/checkout"
DEBUG: Found match at index 136 (repository=rv2673/renovate-test, packageFile=.github/workflows/main.yml, branch=renovate/pin-dependencies)
       "depName": "actions/checkout"
DEBUG: Contents updated (repository=rv2673/renovate-test, packageFile=.github/workflows/main.yml, branch=renovate/pin-dependencies)
       "depName": "actions/checkout"
DEBUG: Starting search at index 266 (repository=rv2673/renovate-test, packageFile=.github/workflows/main.yml, branch=renovate/pin-dependencies)
       "depName": "renovatebot/github-action"
DEBUG: Found match at index 266 (repository=rv2673/renovate-test, packageFile=.github/workflows/main.yml, branch=renovate/pin-dependencies)
       "depName": "renovatebot/github-action"
DEBUG: Contents updated (repository=rv2673/renovate-test, packageFile=.github/workflows/main.yml, branch=renovate/pin-dependencies)
       "depName": "renovatebot/github-action"
DEBUG: Updated 1 package files (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: No updated lock files in branch (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: 1 file(s) to commit (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: Committing files to branch renovate/pin-dependencies (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: Setting git author name (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
       "gitAuthorName": "Renovate Bot"
DEBUG: Setting git author email (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
       "gitAuthorEmail": "renovate@whitesourcesoftware.com"
DEBUG: git commit (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/pin-dependencies",
         "commit": "263578b",
         "root": false,
         "summary": {"changes": 1, "insertions": 2, "deletions": 0}
       }
DEBUG: commitFiles error (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
       "err": {
         "task": {
           "commands": [
             "push",
             "origin",
             "renovate/pin-dependencies:renovate/pin-dependencies",
             "--force-with-lease",
             "-u",
             "--no-verify",
             "--verbose",
             "--porcelain"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "To https://github.com/rv2673/renovate-test.git\n!\trefs/heads/renovate/pin-dependencies:refs/heads/renovate/pin-dependencies\t[remote rejected] (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/main.yml` without `workflow` scope)\nDone\nPushing to https://github.com/rv2673/renovate-test.git\nPOST git-receive-pack (702 bytes)\nerror: failed to push some refs to 'https://github.com/rv2673/renovate-test.git'\n",
         "stack": "Error: To https://github.com/rv2673/renovate-test.git\n!\trefs/heads/renovate/pin-dependencies:refs/heads/renovate/pin-dependencies\t[remote rejected] (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/main.yml` without `workflow` scope)\nDone\nPushing to https://github.com/rv2673/renovate-test.git\nPOST git-receive-pack (702 bytes)\nerror: failed to push some refs to 'https://github.com/rv2673/renovate-test.git'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
       }
 INFO: Workflows update rejection - aborting branch. (repository=rv2673/renovate-test, branch=renovate/pin-dependencies)
DEBUG: Setting current branch to main (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: latest commit (repository=rv2673/renovate-test, branch=renovate/all-minor)
       "branchName": "main",
       "latestCommitDate": "2022-01-07T16:34:23+01:00"
DEBUG: getBranchPr(renovate/all-minor) (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: findPr(renovate/all-minor, undefined, open) (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: findPr(renovate/all-minor, undefined, closed) (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: branchExists=false (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: dependencyDashboardCheck=undefined (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: recreateClosed is true (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: Checking schedule(at any time, null) (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: No schedule defined (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: Branch needs creating (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: Using reuseExistingBranch: false (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: Starting search at index 136 (repository=rv2673/renovate-test, packageFile=.github/workflows/main.yml, branch=renovate/all-minor)
       "depName": "actions/checkout"
DEBUG: Found match at index 136 (repository=rv2673/renovate-test, packageFile=.github/workflows/main.yml, branch=renovate/all-minor)
       "depName": "actions/checkout"
DEBUG: Contents updated (repository=rv2673/renovate-test, packageFile=.github/workflows/main.yml, branch=renovate/all-minor)
       "depName": "actions/checkout"
DEBUG: Starting search at index 42 (repository=rv2673/renovate-test, packageFile=.gitlab-ci.yml, branch=renovate/all-minor)
       "depName": "alpine"
DEBUG: Found match at index 42 (repository=rv2673/renovate-test, packageFile=.gitlab-ci.yml, branch=renovate/all-minor)
       "depName": "alpine"
DEBUG: Contents updated (repository=rv2673/renovate-test, packageFile=.gitlab-ci.yml, branch=renovate/all-minor)
       "depName": "alpine"
DEBUG: Updated 2 package files (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: No updated lock files in branch (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: 2 file(s) to commit (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: Committing files to branch renovate/all-minor (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: Setting git author name (repository=rv2673/renovate-test, branch=renovate/all-minor)
       "gitAuthorName": "Renovate Bot"
DEBUG: Setting git author email (repository=rv2673/renovate-test, branch=renovate/all-minor)
       "gitAuthorEmail": "renovate@whitesourcesoftware.com"
DEBUG: git commit (repository=rv2673/renovate-test, branch=renovate/all-minor)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/all-minor",
         "commit": "b292ac1",
         "root": false,
         "summary": {"changes": 2, "insertions": 2, "deletions": 2}
       }
DEBUG: commitFiles error (repository=rv2673/renovate-test, branch=renovate/all-minor)
       "err": {
         "task": {
           "commands": [
             "push",
             "origin",
             "renovate/all-minor:renovate/all-minor",
             "--force-with-lease",
             "-u",
             "--no-verify",
             "--verbose",
             "--porcelain"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "To https://github.com/rv2673/renovate-test.git\n!\trefs/heads/renovate/all-minor:refs/heads/renovate/all-minor\t[remote rejected] (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/main.yml` without `workflow` scope)\nDone\nPushing to https://github.com/rv2673/renovate-test.git\nPOST git-receive-pack (820 bytes)\nerror: failed to push some refs to 'https://github.com/rv2673/renovate-test.git'\n",
         "stack": "Error: To https://github.com/rv2673/renovate-test.git\n!\trefs/heads/renovate/all-minor:refs/heads/renovate/all-minor\t[remote rejected] (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/main.yml` without `workflow` scope)\nDone\nPushing to https://github.com/rv2673/renovate-test.git\nPOST git-receive-pack (820 bytes)\nerror: failed to push some refs to 'https://github.com/rv2673/renovate-test.git'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
       }
 INFO: Workflows update rejection - aborting branch. (repository=rv2673/renovate-test, branch=renovate/all-minor)
DEBUG: Ensuring Dependency Dashboard (repository=rv2673/renovate-test)
DEBUG: ensureIssue(Dependency Dashboard) (repository=rv2673/renovate-test)
DEBUG: Issue is open and up to date - nothing to do (repository=rv2673/renovate-test)
DEBUG: Removing any stale branches (repository=rv2673/renovate-test)
DEBUG: config.repoIsOnboarded=true (repository=rv2673/renovate-test)
DEBUG: Branch lists (repository=rv2673/renovate-test)
       "branchList": ["renovate/all-minor", "renovate/digests-pin", "renovate/pin-dependencies"],
       "renovateBranches": ["renovate/digests-pin"]
DEBUG: remainingBranches= (repository=rv2673/renovate-test)
DEBUG: No branches to clean up (repository=rv2673/renovate-test)
DEBUG: Repository timing splits (milliseconds) (repository=rv2673/renovate-test)
       "splits": {"init": 3214, "extract": 619, "lookup": 5637, "update": 4887},
       "total": 14644
DEBUG: http statistics (repository=rv2673/renovate-test)
       "urls": {
         "https://api.github.com/graphql (POST)": 4,
         "https://api.github.com/repos/actions/checkout (GET)": 1,
         "https://api.github.com/repos/actions/checkout/git/blobs/6f40def823505ef8b1bd109de531a1c05af6bacd (GET)": 1,
         "https://api.github.com/repos/actions/checkout/git/refs/tags/v2.0.0 (GET)": 1,
         "https://api.github.com/repos/actions/checkout/git/refs/tags/v2.4.0 (GET)": 1,
         "https://api.github.com/repos/actions/checkout/git/trees/main (GET)": 1,
         "https://api.github.com/repos/actions/checkout/releases (GET)": 1,
         "https://api.github.com/repos/actions/checkout/tags (GET)": 1,
         "https://api.github.com/repos/renovatebot/github-action/git/refs/tags/v31.21.0 (GET)": 1,
         "https://api.github.com/repos/renovatebot/github-action/git/tags/4a649a0d179729e83504422b901a21e4b3485627 (GET)": 1,
         "https://api.github.com/repos/renovatebot/github-action/releases (GET)": 1,
         "https://api.github.com/repos/renovatebot/github-action/tags (GET)": 1,
         "https://api.github.com/repos/rv2673/renovate-test/issues/7 (GET)": 2,
         "https://api.github.com/repos/rv2673/renovate-test/pulls (GET)": 1,
         "https://api.github.com/repositories/252754603/releases (GET)": 7,
         "https://api.github.com/repositories/252754603/tags (GET)": 7,
         "https://auth.docker.io/token (GET)": 6,
         "https://index.docker.io/v2/ (GET)": 1,
         "https://index.docker.io/v2/library/alpine/blobs/sha256:c059bfaa849c4d8e4aecaeb3a10c2d9b3d85f5165c66ad3a4d937758128c4d18 (GET)": 1,
         "https://index.docker.io/v2/library/alpine/manifests/3.13.6 (HEAD)": 1,
         "https://index.docker.io/v2/library/alpine/manifests/3.15.0 (HEAD)": 1,
         "https://index.docker.io/v2/library/alpine/manifests/latest (GET)": 1,
         "https://index.docker.io/v2/library/alpine/manifests/sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3 (GET)": 1,
         "https://index.docker.io/v2/library/alpine/tags/list (GET)": 1,
         "https://index.docker.io/v2/library/ubuntu/manifests/focal-20211006 (HEAD)": 1
       },
       "hostStats": {
         "api.github.com": {"requestCount": 32, "requestAvgMs": 425, "queueAvgMs": 0},
         "auth.docker.io": {"requestCount": 6, "requestAvgMs": 248, "queueAvgMs": 0},
         "index.docker.io": {"requestCount": 8, "requestAvgMs": 254, "queueAvgMs": 0}
       },
       "totalRequests": 46
 INFO: Repository finished (repository=rv2673/renovate-test)
       "durationMs": 14644
DEBUG: Renovate exiting
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by rv2673**
## Changes:

- Check for variable in cleaned depName. (Just like with variable check in docker image tag)

## Context:

Closes #13425

This check should be safe since according to [docker documentation](https://docs.docker.com/engine/reference/commandline/tag/#extended-description) it is not valid character in name components segments nor is it an allowed character in dns hostnames.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/manager/dockerfile/extract.ts [hunk 1]
```diff
@@ -56,6 +56,13 @@ export function splitImageParts(currentFrom: string): PackageDependency {
     depName = depTagSplit.join(':');
   }
 
+  if (depName && depName.indexOf(variableMarker) !== -1) {
```
Comment (rarkins) [inline lib/manager/dockerfile/extract.ts:59]:
```suggestion
  if (depName?.includes(variableMarker)) {
```

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
