### PR TITLE
fix(github): Return remote commit hash for `platformCommit=true`

### LINKED ISSUE #16384: Status checks not set correctly with platformCommit=true
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

`renovate/artifacts` is not being set correctly, I think caused by `platformCommit`.

This example failing PR has no status check visible: https://github.com/renovate-reproductions/16356/pull/1

From the log:

```
DEBUG: git commit(branch="renovate/left-pad-1.x")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/left-pad-1.x",
    "commit": "9b4751f519df48ee0ffcb9343adc5327151181ad",
    "root": false,
    "summary": {
      "changes": 1,
      "insertions": 1,
      "deletions": 1
    }
  }
}
DEBUG: Fetching branch renovate/left-pad-1.x(branch="renovate/left-pad-1.x")
INFO: Branch created(branch="renovate/left-pad-1.x")
{
  "commitSha": "9b4751f519df48ee0ffcb9343adc5327151181ad"
}
DEBUG: Updating status check state to failed(branch="renovate/left-pad-1.x")
DEBUG: Setting branch status(branch="renovate/left-pad-1.x")
{
  "context": "renovate/artifacts",
  "state": "red"
}
```

The reality is that the commit associated with the PR is https://github.com/renovate-reproductions/16356/pull/1/commits/67dc298a811c0b886b4b0e7f5c4185c8b6dd88a3 and not `9b4751f519df48ee0ffcb9343adc5327151181ad`.

### Relevant debug logs

See above

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

- Ensure remotely created commit is present locally after API-based commit

## Context

- Closes: #16384

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/platform/github/index.ts [hunk 1]
```diff
@@ -1706,7 +1706,9 @@ export async function commitFiles(
   if (!pushResult) {
     return null;
   }
-  // Because the branch commit was done remotely via REST API, now we git fetch it locally.
-  // We also do this step when committing/pushing using local git tooling.
-  return git.fetchCommit(config);
+  // Replace locally created branch with the remotely created one
+  // and return the remote commit SHA
+  await git.resetToCommit(commitResult.parentCommitSha);
```
Comment (viceice) [inline lib/modules/platform/github/index.ts:1711]: does it do a git fetch before reset? otherwise it's a no-op

**Comment by zharinov** [comment]
Example: https://github.com/renovate-testing/test-16356-platform-commit-artifacts/pull/3

File: lib/modules/platform/github/index.ts (hunk 1 above)
Comment (zharinov) [reply lib/modules/platform/github/index.ts:1711]: Earlier in this function we've created local commit that has been used for the sake of obtaining trees and blobs required to construct remote commit via GitHub API. Once it's created, we have to pull it, and this `resetToCommit` just removes the initial commit, so that we don't have any conflicts.

Comment (viceice) [reply lib/modules/platform/github/index.ts:1711]: ok, just wanted bro verify that we don't silently miss the pull. 🙃

File: lib/util/git/index.ts [hunk 2]
```diff
@@ -975,7 +981,7 @@ export async function fetchCommit({
   logger.debug(`Fetching branch ${branchName}`);
   try {
     const ref = `refs/heads/${branchName}:refs/remotes/origin/${branchName}`;
-    await gitRetry(() => git.fetch(['origin', ref, '--force']));
+    await gitRetry(() => git.pull(['origin', ref, '--force']));
```
Comment (zharinov) [inline lib/util/git/index.ts:984]: Seems like we use it only on GitHub, so no problems should occur here

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
