### PR TITLE
fix(validation): support customDatasources.description strings

### LINKED ISSUE #28442: Support `description` on custom datasources
### Describe the proposed change(s).

Support `description` on custom datasources. Currently validation fails.

```
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Location: `.github/renovate.json`
Error type: The renovate configuration file contains some invalid settings
Message: Invalid `customDatasources.customDatasources.description` configuration: is a string
```

### PR DESCRIPTION
**Pull request by rarkins**
## Context

Closes #28442

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by secustor — DISMISSED** [review]

File: lib/config/validation.ts [hunk 1]
```diff
@@ -712,19 +712,31 @@ export async function validateConfig(
...
                         topic: 'Configuration Error',
-                        message: `Invalid \`${currentPath}.${key}.${subKey}\` configuration: is not an array of string`,
+                        message: `Invalid \`${currentPath}.${subKey}\` configuration: is not an array of string`,
+                      });
+                    }
+                  } else if (subKey === 'description') {
+                    if (
+                      !(
+                        is.string(subValue) ||
+                        (is.array(subValue) && subValue.every(is.string))
```
Comment (viceice) [inline lib/config/validation.ts:728]:
```suggestion
                        (is.array(subValue, is.string))
```
simplify

**Review by viceice — DISMISSED** [review]
needs prettier fix

**Review by secustor — APPROVED** [review]
