### PR TITLE
fix(reconfigure/pr): find reconfigure pr separately

### LINKED ISSUE #25754: Reconfigure Renovate PR check fails to create PR comment
### Describe the proposed change(s).

On GitHub, Renovate fails to find the PR associated with the `renovate/reconfigure` branch, because the author is not Renovate Bot and we retrieve only PRs by Renovate's username.

Same problem may occur on other platforms too.

We probably don't want to fetch _all_ PRs by every author, although maybe we need to fetch all _open_ PRs plus all closed ones by Renovate. Alternatively maybe there's a way to efficiently find just one (open) PR for a particular branch?

Related discussion: #25721

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- Added a new `findReconfigurePr` function in supported platforms (GitHub, GitLab, Gitea).
- For GitHub and GitLab, these functions now make separate GET requests to fetch PRs based on the source branch name.
- For Gitlab: Modified its `toRenovatePR` function to ensure that reconfigure PRs are not filtered out from the list of PRs fetched.
 

## Context
Closes: https://github.com/renovatebot/renovate/issues/25754

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/datasource/docker/index.ts
Comment (rarkins) [inline lib/modules/datasource/docker/index.ts:1]: Unrelated changes

**Comment by RahulGautamSingh** [comment]
Test runs:

For testing I created two accounts on each platform one user another bot. Then added the bot account as a memebr/collaborator on the test repos. After this I created a repo with renovate-config and reconfigure branch and PR.
And ran renovate against all the repos with the token of the bot account.

[Gitlab ](https://gitlab.com/rahultesnik/config-labels/-/merge_requests/6) - [Github ](https://github.com/RahulGautamSingh/repro-24170/pull/11) - [Gitea](https://try.gitea.io/RahulGautamSingh/reconfigure-test/pulls/3)

File: lib/modules/datasource/docker/index.ts
Comment (RahulGautamSingh) [reply lib/modules/datasource/docker/index.ts:1]: Looking into it, maybe local prettier is behind renovate's

**Comment by rarkins** [comment]
What's the reason for only certain platforms?

I think: some platforms retrieve every PR already and do filtering on the Renovate client-side. So for those we don't need a new function and can fall back to findPr()

**Comment by RahulGautamSingh** [comment]
> What's the reason for only certain platforms?

Pushing them soon

> I think: some platforms retrieve every PR already and do filtering on the Renovate client-side. So for those we don't need a new function and can fall back to findPr()

Since we have to add a new fn for github, and gitlab which will be available via the platform class. I thought it was cleaner to have the function in all platforms. And in the ones that don't need extra logic just pass it onto `findPr` from there.

```ts
// platform/gitea/index.ts

async function findReconfigurePr(branchName: string){
  return await findPr({ branchName });
},
```

```js
// workers/repository/reconfigure/index.ts

const reconfigurePr = platform.findReconfigurePr(branchName);
```

Instead of adding an if-logic to handle this in the reconfigure logic.

```js
// workers/repository/reconfigure/index.ts

let reconfigurePr: Pr|null = null;
switch(platform){
  case "github": reconfigurePr = platform.findReconfigurePr(branchName); break;
  case "gitlab": reconfigurePr = platform.findReconfigurePr(branchName); break;
  default: reconfigurePr = platform.findPr({ branchName, ...});
}
```

**Comment by rarkins** [comment]
You could check for the existence of platform.findReconfigurePr() - you don't need to embed platform-awareness into the worker layer

**Comment by RahulGautamSingh** [comment]
> You could check for the existence of platform.findReconfigurePr() - you don't need to embed platform-awareness into the worker layer

Yes, missed that. Thanks.

**Comment by RahulGautamSingh** [comment]
Test Run for BitBucket Server remaining, might take some time since I am configuring it for the first time.

File: lib/modules/platform/bitbucket-server/index.ts [hunk 1]
```diff
@@ -336,6 +336,32 @@ export async function findPr({
...
+): Promise<Pr | null> {
+  logger.debug(`findReconfigurePr(${branchName}`);
+  const searchParams: Record<string, string> = {
+    state: 'OPEN',
+  };
+  searchParams['direction'] = 'outgoing';
+  searchParams['at'] = `refs/heads/${branchName}`;
+
+  const query = getQueryString(searchParams);
+  const prList = await utils.accumulateValues(
```
Comment (viceice) [inline lib/modules/platform/bitbucket-server/index.ts:350]: do we really need to fetch all pages? isn't the first enough?

File: lib/modules/platform/gitea/index.ts [hunk 2]
```diff
@@ -80,6 +80,11 @@ let config: GiteaRepoConfig = {} as any;
 let botUserID: number;
 let botUserName: string;
 
+function isReconfigurePr(branchName: string): boolean {
+  logger.debug({ branchName }, 'isReconfigurePr');
+  return branchName === 'renovate/reconfigure';
```
Comment (viceice) [inline lib/modules/platform/gitea/index.ts:85]: are you sure we don't use the branch prefix for reconfigure?

File: lib/modules/platform/gitlab/index.ts [hunk 3]
```diff
@@ -871,6 +871,31 @@ export async function findPr({
...
+    `projects/${config.repository}/merge_requests?source_branch=${branchName}`,
+  );
+  let { body: prList } = response;
+  prList = prList.filter((pr) => pr.state === 'opened');
+  if (prList.length > 1) {
+    logger.debug('More than one reconfigure pR');
+    return null;
+  }
+  const mr = prList[0];
+  // only pass nexessary info
```
Comment (viceice) [inline lib/modules/platform/gitlab/index.ts:888]: typo

File: lib/workers/repository/reconfigure/index.ts [hunk 4]
```diff
@@ -131,11 +131,17 @@ export async function validateReconfigureBranch(
       'Validation Errors',
     );
 
-    // add comment to reconfigure PR if it exists
-    const branchPr = await platform.getBranchPr(
+    await platform.setBranchStatus({
```
Comment (viceice) [inline lib/workers/repository/reconfigure/index.ts:134]: why moving this?

File: lib/modules/platform/gitlab/index.ts [hunk 5]
```diff
@@ -871,6 +871,36 @@ export async function findPr({
...
 
+export async function findReconfigurePr(
+  branchName: string,
+): Promise<Pr | null> {
+  logger.debug(`findReconfigurePr(${branchName}`);
+  const response = await gitlabApi.getJson<GitLabMergeRequest[]>(
+    `projects/${config.repository}/merge_requests?source_branch=${branchName}`,
+  );
+  let { body: prList } = response;
+  prList = prList.filter((pr) => pr.state === 'opened');
```
Comment (rarkins) [inline lib/modules/platform/gitlab/index.ts:882]:
```suggestion
  const response = await gitlabApi.getJson<GitLabMergeRequest[]>(
    `projects/${config.repository}/merge_requests?source_branch=${branchName}&state=opened`,
  );
  const { body: prList } = response;
```

Does this work?

File: lib/modules/platform/gitlab/index.ts [hunk 6]
```diff
@@ -871,6 +871,36 @@ export async function findPr({
...
+
+  if (!prList.length) {
+    logger.debug({ prList }, 'No reconfigure Pr found');
```
Comment (rarkins) [inline lib/modules/platform/gitlab/index.ts:885]:
```suggestion
    logger.debug(`No reconfigure MR found for branch ${branchName}`);
```

File: lib/modules/platform/gitlab/index.ts [hunk 7]
```diff
@@ -871,6 +871,36 @@ export async function findPr({
...
+    return null;
+  }
+  if (prList.length > 1) {
+    logger.debug('More than one reconfigure pR');
+    return null;
+  }
```
Comment (rarkins) [inline lib/modules/platform/gitlab/index.ts:891]: I don't see how this is possible, and I think we should take the latest if so

File: lib/modules/platform/github/index.ts [hunk 8]
```diff
@@ -826,6 +826,32 @@ export async function findPr({
...
+export async function findReconfigurePr(
+  branchName: string,
+): Promise<GhPr | null> {
+  logger.debug(`findReconfigurePr(${branchName}`);
+  const repo = config.parentRepo ?? config.repository;
+  const response = await githubApi.getJson<GhRestPr[]>(
+    `repos/${repo}/pulls?head=${repo}:${branchName}`,
+  );
+  let { body: prList } = response;
+  prList = prList.filter((pr) => pr.state === 'open');
```
Comment (rarkins) [inline lib/modules/platform/github/index.ts:838]:
```suggestion
  const response = await githubApi.getJson<GhRestPr[]>(
    `repos/${repo}/pulls?head=${repo}:${branchName}&state=open`,
  );
  const { body: prList } = response;
```

**Review by rarkins — CHANGES_REQUESTED** [review]
Please also make these changes:
- Use "PR" in logs for GitHub, "MR" for GitLab
- Try to make debug logs a single line whenever possible (i.e. embed metadata into the message)

File: lib/modules/platform/gitlab/index.ts (hunk 5 above)
Comment (RahulGautamSingh) [reply lib/modules/platform/gitlab/index.ts:882]: Yes

**Review by rarkins — CHANGES_REQUESTED** [review]
Sorry, change of plan. I would like for you to remove the findReconfigurePr function and instead add a new option to the existing findPr function called `includeOtherAuthors` which defaults to false/undefined and is ignored by the platforms which already fetch every PR. Then for the platforms which have findReconfigurePr() in your current proposed, add an "if" logic to put that code inside findPr whenever includeOtherAuthors is true

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/modules/platform/bitbucket-server/index.ts [hunk 9]
```diff
@@ -324,8 +324,40 @@ export async function findPr({
...
+    const query = getQueryString(searchParams);
+    const prs = await utils.accumulateValues(
+      `./rest/api/1.0/projects/${config.projectKey}/repos/${config.repositorySlug}/pull-requests?${query}`,
+      'get',
+      {},
+      1, // only fetch the latest pr
+    );
+
+    if (!prs.length) {
+      logger.debug(`No reconfigure Pr found for branch ${branchName}`);
```
Comment (rarkins) [inline lib/modules/platform/bitbucket-server/index.ts:348]:
```suggestion
      logger.debug(`No reconfigure PR found for branch ${branchName}`);
```

File: lib/modules/platform/bitbucket-server/index.ts [hunk 10]
```diff
@@ -324,8 +324,40 @@ export async function findPr({
...
+      return null;
+    }
+
+    // return the latest pr
+    const pr = utils.prInfo(prs[0]);
+    if (pr) {
+      logger.debug(`Found PR #${pr.number}`);
+    }
+
+    return pr;
```
Comment (rarkins) [inline lib/modules/platform/bitbucket-server/index.ts:358]:
```suggestion
    return utils.prInfo(prs[0]);
```

File: lib/modules/platform/bitbucket/index.ts [hunk 11]
```diff
@@ -296,8 +296,31 @@ export async function findPr({
...
+      logger.debug(`No reconfigure Pr found for branch ${branchName}`);
+      return null;
+    }
+
+    // return the latest pr
+    const pr = utils.prInfo(prs[0]);
+    if (pr) {
+      logger.debug(`Found PR #${pr.number}`);
+    }
+    return pr;
```
Comment (rarkins) [inline lib/modules/platform/bitbucket/index.ts:321]:
```suggestion
    return utils.prInfo(prs[0]);
```

File: lib/modules/platform/gitea/index.ts [hunk 12]
```diff
@@ -491,9 +498,10 @@ const platform: Platform = {
     branchName,
     prTitle: title,
     state = 'all',
+    includeOtherAuthors,
   }: FindPRConfig): Promise<Pr | null> {
     logger.debug(`findPr(${branchName}, ${title!}, ${state})`);
-    const prList = await platform.getPrList();
+    const prList = await platform.getPrList(includeOtherAuthors);
```
Comment (rarkins) [inline lib/modules/platform/gitea/index.ts:504]: I think this is incorrect. The pr list from getPrList() is computed only once and returned from cache every other time. Instead the PR list should be filtered to also include branches ending in `reconfigure`

File: lib/modules/platform/github/index.ts [hunk 13]
```diff
@@ -798,8 +798,31 @@ export async function findPr({
...
+      logger.debug(`No reconfigure Pr found for branch ${branchName}`);
+      return null;
+    }
+
+    // return the latest pull request
+    const pr = coerceRestPr(prList[0]);
+    if (pr) {
+      logger.debug(`Found PR #${pr.number}`);
+    }
+    return pr;
```
Comment (rarkins) [inline lib/modules/platform/github/index.ts:823]:
```suggestion
    return coerceRestPr(prList[0]);
```

File: lib/modules/platform/types.ts [hunk 14]
```diff
@@ -192,7 +193,7 @@ export interface Platform {
     branchOrTag?: string,
   ): Promise<any>;
   initRepo(config: RepoParams): Promise<RepoResult>;
-  getPrList(): Promise<Pr[]>;
+  getPrList(includeOtherAuthors?: boolean): Promise<Pr[]>;
```
Comment (rarkins) [inline lib/modules/platform/types.ts:196]: revert this

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/modules/platform/bitbucket-server/index.ts [hunk 15]
```diff
@@ -324,8 +324,34 @@ export async function findPr({
   prTitle,
   state = 'all',
   refreshCache,
+  includeOtherAuthors,
 }: FindPRConfig): Promise<Pr | null> {
   logger.debug(`findPr(${branchName}, "${prTitle!}", "${state}")`);
+
+  if (includeOtherAuthors) {
+    // only fetch open prs from other authors
```
Comment (rarkins) [inline lib/modules/platform/bitbucket-server/index.ts:332]:
```suggestion
    // PR might have been created by anyone, so don't use the cached Renovate PR list
```

File: lib/modules/platform/bitbucket-server/index.ts [hunk 16]
```diff
@@ -324,8 +324,34 @@ export async function findPr({
...
+    const query = getQueryString(searchParams);
+    const prs = await utils.accumulateValues(
+      `./rest/api/1.0/projects/${config.projectKey}/repos/${config.repositorySlug}/pull-requests?${query}`,
+      'get',
+      {},
+      1, // only fetch the latest pr
+    );
+
+    if (!prs.length) {
+      logger.debug(`No reconfigure PR found for branch ${branchName}`);
```
Comment (rarkins) [inline lib/modules/platform/bitbucket-server/index.ts:348]:
```suggestion
      logger.debug(`No PR found for branch ${branchName}`);
```

File: lib/modules/platform/bitbucket/index.ts [hunk 17]
```diff
@@ -296,8 +296,26 @@ export async function findPr({
   branchName,
   prTitle,
   state = 'all',
+  includeOtherAuthors,
 }: FindPRConfig): Promise<Pr | null> {
   logger.debug(`findPr(${branchName}, ${prTitle}, ${state})`);
+
+  if (includeOtherAuthors) {
+    // only fetch open prs from other authors
```
Comment (rarkins) [inline lib/modules/platform/bitbucket/index.ts:304]:
```suggestion
    // PR might have been created by anyone, so don't use the cached Renovate PR list
```

File: lib/modules/platform/bitbucket/index.ts [hunk 18]
```diff
@@ -296,8 +296,26 @@ export async function findPr({
...
+    const prs = (
+      await bitbucketHttp.getJson<PagedResult<PrResponse>>(
+        `/2.0/repositories/${config.repository}/pullrequests?q=source.branch.name="${branchName}"&state=open`,
+      )
+    ).body.values;
+
+    if (prs.length === 0) {
+      logger.debug(`No reconfigure PR found for branch ${branchName}`);
```
Comment (rarkins) [inline lib/modules/platform/bitbucket/index.ts:312]:
```suggestion
      logger.debug(`No PR found for branch ${branchName}`);
```

File: lib/modules/platform/github/index.ts [hunk 19]
```diff
@@ -798,8 +798,26 @@ export async function findPr({
   branchName,
   prTitle,
   state = 'all',
+  includeOtherAuthors,
 }: FindPRConfig): Promise<GhPr | null> {
   logger.debug(`findPr(${branchName}, ${prTitle}, ${state})`);
+
+  if (includeOtherAuthors) {
+    const repo = config.parentRepo ?? config.repository;
+    // only fetch open prs from other authors
```
Comment (rarkins) [inline lib/modules/platform/github/index.ts:807]:
```suggestion
    // PR might have been created by anyone, so don't use the cached Renovate PR list
```

File: lib/modules/platform/github/index.ts [hunk 20]
```diff
@@ -798,8 +798,26 @@ export async function findPr({
...
+    const response = await githubApi.getJson<GhRestPr[]>(
+      `repos/${repo}/pulls?head=${repo}:${branchName}&state=open`,
+    );
+
+    const { body: prList } = response;
+    if (!prList.length) {
+      logger.debug(`No reconfigure PR found for branch ${branchName}`);
```
Comment (rarkins) [inline lib/modules/platform/github/index.ts:814]:
```suggestion
      logger.debug(`No PR found for branch ${branchName}`);
```

File: lib/modules/platform/gitlab/index.ts [hunk 21]
```diff
@@ -858,8 +858,36 @@ export async function findPr({
   branchName,
   prTitle,
   state = 'all',
+  includeOtherAuthors,
 }: FindPRConfig): Promise<Pr | null> {
   logger.debug(`findPr(${branchName}, ${prTitle!}, ${state})`);
+
+  if (includeOtherAuthors) {
+    // only fetch open mrs from other authors
```
Comment (rarkins) [inline lib/modules/platform/gitlab/index.ts:866]:
```suggestion
    // PR might have been created by anyone, so don't use the cached Renovate MR list
```

File: lib/modules/platform/gitlab/index.ts [hunk 22]
```diff
@@ -858,8 +858,36 @@ export async function findPr({
...
+    const response = await gitlabApi.getJson<GitLabMergeRequest[]>(
+      `projects/${config.repository}/merge_requests?source_branch=${branchName}&state=opened`,
+    );
+
+    const { body: mrList } = response;
+    if (!mrList.length) {
+      logger.debug(`No reconfigure MR found for branch ${branchName}`);
```
Comment (rarkins) [inline lib/modules/platform/gitlab/index.ts:873]:
```suggestion
      logger.debug(`No MR found for branch ${branchName}`);
```

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by rarkins — DISMISSED** [review]

File: lib/modules/platform/gitea/index.ts [hunk 23]
```diff
@@ -81,6 +82,11 @@ let config: GiteaRepoConfig = {} as any;
 let botUserID: number;
 let botUserName: string;
 
+function isReconfigurePr(branchName: string): boolean {
+  logger.debug({ branchName }, 'isReconfigurePr');
+  return regEx(/reconfigure$/g).test(branchName);
```
Comment (viceice) [inline lib/modules/platform/gitea/index.ts:87]: do we really need this logging for every PR?

I think we should just inline the regex test and store the regex outside the loop for performance

File: lib/modules/platform/github/index.spec.ts [hunk 24]
```diff
@@ -2428,6 +2428,44 @@ describe('modules/platform/github/index', () => {
...
+          },
+        ]);
+      await github.initRepo({ repository: 'some/repo' });
+      expect(
+        await github.findPr({
+          branchName: 'branch',
+          state: 'open',
+          includeOtherAuthors: true,
+        }),
+      ).toMatchSnapshot();
```
Comment (viceice) [inline lib/modules/platform/github/index.spec.ts:2452]: ☝️

File: lib/modules/platform/gitlab/index.spec.ts [hunk 25]
```diff
@@ -1678,6 +1678,44 @@ describe('modules/platform/gitlab/index', () => {
...
+            state: 'opened',
+          },
+        ]);
+      expect(
+        await gitlab.findPr({
+          branchName: 'branch',
+          state: 'open',
+          includeOtherAuthors: true,
+        }),
+      ).toMatchSnapshot();
```
Comment (viceice) [inline lib/modules/platform/gitlab/index.spec.ts:1702]: ☝️

**Review by viceice — COMMENTED** [review]
otherwise LGTM

File: lib/modules/platform/bitbucket-server/index.ts [hunk 26]
```diff
@@ -324,8 +324,34 @@ export async function findPr({
...
+  if (includeOtherAuthors) {
+    // PR might have been created by anyone, so don't use the cached Renovate PR list
+    const searchParams: Record<string, string> = {
+      state: 'OPEN',
+    };
+    searchParams['direction'] = 'outgoing';
+    searchParams['at'] = `refs/heads/${branchName}`;
+
+    const query = getQueryString(searchParams);
+    const prs = await utils.accumulateValues(
```
[the remark this answers is not in the document]
Comment (RahulGautamSingh) [reply lib/modules/platform/bitbucket-server/index.ts:340]: I seemed repetitive to write the api call here, since we already have a fn which does the same thing. Both ways ie. calling api directly from there or calling the accumulator we get the same result array and accumulator loop breaks after one run, so not much of a difference ig.

File: lib/modules/platform/gitea/index.ts [hunk 27]
```diff
@@ -81,6 +83,10 @@ let config: GiteaRepoConfig = {} as any;
 let botUserID: number;
 let botUserName: string;
 
+function isReconfigurePr(branchName: string): boolean {
+  return reconfigurePrRegex.test(branchName);
+}
+
```
Comment (viceice) [inline lib/modules/platform/gitea/index.ts:89]: inline this, there is no benefit and this causes a function call overhead only

**Review by viceice — APPROVED** [review]
