### PR TITLE
fix(gradle): Fix registry url parsing

### LINKED ISSUE #14730: Renovate ignores gradle custom repository
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

docker

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When running an out of the box gradle project, if I add a custom repository, Renovate will only scan the default Maven and Gradle Plugin repositories. This behavior is different from gradle's own dependency resolution.

It used to work and I'm not sure when it stopped working. I think I started using Renovate on version 23 and it worked then. I only noticed just last week that it wasn't seeing my custom repo.

Here is the relevant part of the gradle file (see repro for full details). It adds a custom maven repo that doesn't actually exist. For the reproduction, I just wanted to see if it would look for the custom repo.

```gradle
repositories {
    mavenLocal()
    maven {
        url = "https://renovate-reproduction-test.io/repository"
        credentials {
            username 'username'
            password 'password'
        }
    }
    mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'not.a.real.dependency:not-real-dep-name:1.2.3'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

When running the build, gradle's output shows that it is indeed looking for the custom repository. And it doesn't find it because it's fake, but that is expected for the reproduction.

```shell
$ ./gradlew build
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve not.a.real.dependency:not-real-dep-name:1.2.3.
     Required by:
         project :
      > Could not resolve not.a.real.dependency:not-real-dep-name:1.2.3.
         > Could not get resource 'https://renovate-reproduction-test.io/repository/not/a/real/dependency/not-real-dep-name/1.2.3/not-real-dep-name-1.2.3.pom'.
            > Could not GET 'https://renovate-reproduction-test.io/repository/not/a/real/dependency/not-real-dep-name/1.2.3/not-real-dep-name-1.2.3.pom'.
               > renovate-reproduction-test.io

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

Renovates logs (pasted below) show that it does not even attempt to look up the custom repo.

See the reproduction here: https://github.com/cmplank/renovate-gradle-repo-repro

A note on the repro - I didn't create a renovate.json because the issue manifests without it and it seemed simpler to me to leave it out. If that's a problem, let me know and I'll be glad to update it.

Many thanks for creating and supporting this product!

### Relevant debug logs

<details><summary>Logs</summary>

```
March 18th 2022, 16:00:17.247	rp/renovate-repro	Found gradle-wrapper package files
March 18th 2022, 16:00:17.247	rp/renovate-repro	Found 3 package file(s)
March 18th 2022, 16:00:17.247	rp/renovate-repro	Dependency extraction complete
March 18th 2022, 16:00:17.247	rp/renovate-repro	Looking up org.springframework.boot:org.springframework.boot.gradle.plugin in repository https://repo.maven.apache.org/maven2/
March 18th 2022, 16:00:17.247	rp/renovate-repro	Looking up io.spring.dependency-management:io.spring.dependency-management.gradle.plugin in repository https://repo.maven.apache.org/maven2/
March 18th 2022, 16:00:17.247	rp/renovate-repro	Looking up not.a.real.dependency:not-real-dep-name in repository https://repo.maven.apache.org/maven2/
March 18th 2022, 16:00:17.356	rp/renovate-repro	Content is not found for Maven url
March 18th 2022, 16:00:17.450	rp/renovate-repro	Looking up io.spring.dependency-management:io.spring.dependency-management.gradle.plugin in repository https://plugins.gradle.org/m2/
March 18th 2022, 16:00:17.487	rp/renovate-repro	Content is not found for Maven url
March 18th 2022, 16:00:17.907	rp/renovate-repro	Failed to look up dependency not.a.real.dependency:not-real-dep-name
March 18th 2022, 16:00:18.527	rp/renovate-repro	Found 29 new releases for io.spring.dependency-management:io.spring.dependency-management.gradle.plugin in repository https://plugins.gradle.org/m2/
March 18th 2022, 16:00:18.656	rp/renovate-repro	Found 57 new releases for org.springframework.boot:org.springframework.boot.gradle.plugin in repository https://repo.maven.apache.org/maven2/
March 18th 2022, 16:00:18.719	rp/renovate-repro	Looking up org.springframework.boot:org.springframework.boot.gradle.plugin in repository https://plugins.gradle.org/m2/
March 18th 2022, 16:00:20.540	rp/renovate-repro	Found 115 new releases for org.springframework.boot:org.springframework.boot.gradle.plugin in repository https://plugins.gradle.org/m2/
March 18th 2022, 16:00:20.786	rp/renovate-repro	Package releases lookups complete
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

- Add one more syntax variation
- Allow the section to contain other definitions (e.g. auth)

## Context

- Closes: #14730

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/modules/manager/gradle/extract.ts [hunk 1]
```diff
@@ -118,5 +118,6 @@ export async function extractAllPackageFiles(
     }
   });
 
-  return Object.values(packageFilesByName);
+  const result = Object.values(packageFilesByName);
+  return result;
```
Comment (zharinov) [inline lib/modules/manager/gradle/extract.ts:122]: Sometimes it's convenient to set a breakpoint here, so let's don't revert it

**Review by rarkins — CHANGES_REQUESTED** [review]
Add a test

**Review by rarkins — APPROVED** [review]
