### PR TITLE
fix(cargo): skip `--precise` for range-bumped crates to avoid stale `Cargo.lock` errors

### LINKED ISSUE #39137: Renovate fails to update an unpinned Cargo version, when attempting to update it
### Describe the proposed change(s).

As noted in https://github.com/renovatebot/renovate/discussions/38778, we're seeing a case where:

- Cargo specificies an imprecise version number (`0.12`) with a lockfile locked to a specific version (`0.12.23`)
- Renovate detects this correctly: 
  ```json
            {
              "currentValue": "0.12",
              "datasource": "crate",
              "depName": "reqwest",
              "depType": "dependencies",
              "lockedVersion": "0.12.23",
              "updates": [
                {
                  "newVersion": "0.12.24",
                  "newValue": "0.12.24",
                }
              ],
              "currentVersion": "0.12.23",
              "isSingleVersion": false,
              "fixedVersion": "0.12.23"
            }

  ```
- When Renovate attempts to upgrade this version, it uses the `lockedVersion`/`fixedVersion` instead of the `currentValue`, resulting in the `cargo` CLI failing

Interestingly, running:

```
$ install-tool rust 1.90.0
$ cargo --version
cargo 1.90.0 (840b83a10 2025-07-30)
$ cargo update --config net.git-fetch-with-cli=true --manifest-path subdir2/Cargo.toml --package reqwest@0.12.23 --precise 0.12.24
    Updating crates.io index
    Updating reqwest v0.12.23 -> v0.12.24
      Adding subdir v0.1.0 (/app/subdir)
      Adding subdir2 v0.1.0 (/app/subdir2)
note: pass `--verbose` to see 32 unchanged dependencies behind latest
```

Seems to work for me - but seems to fail when `renovate` runs it.

### PR DESCRIPTION
**Pull request by just-in-chang**
## Changes

Skips updating a specific entry with the `--precise` flag for Crates where the `Cargo.toml` range was bumped, delegating the resolution to the later update call with the `--workspace` flag. 

## Context

Please select one of the following:

- [x] This closes an existing Issue, Closes: #39137
- [ ] This doesn't close an Issue, but I accept the risk that this PR may be closed if maintainers disagree with its opening or implementation

I put a bit of thought into this and iterated over a few possible solutions:
1. Omitting the `@lockedVersion` from `--package`. It keeps the `--precise` but doesn't work when there are multiple versions of the same crate in the `Cargo.lock`.
2. Proactively reading `Cargo.lock` to skip crates already at their target version. This introduced unnecessary complexity and duplicated the existing retry logic in `artifacts.ts`.
3. [Current Approach] Skips `--precise` entirely for range-bumped crates, letting the later `--workspace` update command re-resolve them. This avoids both the stale version and ambiguity issues cleanly.

## AI assistance disclosure

Did you use AI tools to create any part of this pull request?

Please select one option and, if yes, briefly describe how AI was used (e.g., code, tests, docs) and which tool(s) you used.

- [ ] No — I did not use AI for this contribution.
- [ ] Yes — minimal assistance (e.g., IDE autocomplete, small code completions, grammar fixes).
- [x] Yes — substantive assistance (AI-generated non‑trivial portions of code, tests, or documentation).
- [ ] Yes — other (please describe):

Claude Code was used to help generate the unit and real repository tests.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests, but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

The public repository: https://github.com/just-in-chang/renovate-39137-tests

Please read the `README.md` there for more details about the tests.

### CODE REVIEW

**Comment by jamietanna** [comment]
Would you mind also checking that it works against https://github.com/tommyjcarpenter/rust-repro-example-38778 ?

File: lib/modules/manager/cargo/artifacts.ts [hunk 1]
```diff
@@ -51,6 +51,13 @@ async function cargoUpdatePrecise(
   // First update individual dependencies to their `newVersion`. Necessary when
   // using the `update-lockfile` rangeStrategy which doesn't touch Cargo.toml.
   for (const dep of updatedDeps) {
+    // If the range is bumped in Cargo.toml, the old lockedVersion may no longer
+    // exist in Cargo's dependency graph, so let the --workspace update at the
+    // end re-resolve it instead.
```
Comment (viceice) [inline lib/modules/manager/cargo/artifacts.ts:56]: Wouldn't this mean the real locked version can be higher than the range renovate bumped to?

Maybe we should extract the locked version in extract, so bump isn't done at all, because the resolved value is already updated?

**Review by viceice — COMMENTED** [review]
Sorry, i don't know how cargo works for resolving.

File: lib/modules/manager/cargo/artifacts.ts (hunk 1 above)
Comment (just-in-chang) [reply lib/modules/manager/cargo/artifacts.ts:56]: Thanks for the review!

> Wouldn't this mean the real locked version can be higher than the range renovate bumped to?

The version updated by the `--workspace` update at the end will always satisfy the range bounds used in `Cargo.toml`. It just might resolve to a higher version than what is specified in `newVersion` specifically. It's also consistent with the existing behavior by calling the `--workspace` update at the end.

> Maybe we should extract the locked version in extract, so bump isn't done at all, because the resolved value is already updated?

If I understand correctly, the extraction is already happening! The bump is a separate concern though from when new version exceeds the current range or `rangeStrategy` is configured to do so (i.e. setting it to `bump`).

**Comment by just-in-chang** [comment]
> Would you mind also checking that it works against https://github.com/tommyjcarpenter/rust-repro-example-38778 ?

@jamietanna Updated my public test repo to include it in the test cases and also updated the test suite to be more comprehensive. Please take a look!

For the new E2E tests, I'm spinning up two Docker containers containing a few Rust fixtures per test: one with the upstream `main` branch and one with my Renovate fork. We utilize Docker Compose and Gitea along with the two Docker containers because Renovate expects a real Git platform. We then show that the upstream Renovate fails and my fork containing the fix succeeds.

**Review by viceice — APPROVED** [review]
