### PR TITLE
fix(manager/npm): support git@github.com repository urls

### LINKED ISSUE #10717: Support git@github.com repository url for npm packages
**What would you like Renovate to be able to do?**

It should be able to parse repository urls of the format: `git@github.com:tophat/monodeploy.git` and convert it to: `https://github.com/tophat/monodeploy.git` for the sourceUrl.

**Did you already have any implementation ideas?**

In monodeploy we parse the repository url using a list of regular expressions. See: https://github.com/tophat/monodeploy/blob/a5c703e75789af5567c9f67425986a32d460bc28/packages/git/src/parseRepositoryProperty.ts#L10

Yes I'd be open to implementing this.

### PR DESCRIPTION
**Pull request by stroncium**
## Changes:

Added support for ssh style github URLs in npm repository fields.

## Context:

Closes #10717 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/manager/npm/extract/index.ts [hunk 1]
```diff
@@ -253,17 +256,28 @@ export async function extractPackageFile(
       return dep;
     }
     const [depNamePart, depRefPart] = hashSplit;
-    const githubOwnerRepo = depNamePart
-      .replace(/^github:/, '')
-      .replace(/^git\+/, '')
-      .replace(/^https:\/\/github\.com\//, '')
```
Comment (ylemkimon) [inline lib/manager/npm/extract/index.ts:259]: I think the same can be acheived by adding another `replace`:
```js
.replace(/^git@github.com:/, '')
```

Comment (stroncium) [reply lib/manager/npm/extract/index.ts:259]: Theoretically, yes, but I think ideally we would want to arrive at a point where there are a few formats we try to parse separately instead of magical replaces massaging everything to become a string formatted in one way.

Comment (stroncium) [reply lib/manager/npm/extract/index.ts:259]: For debugability and idiomacy.

Comment (rarkins) [reply lib/manager/npm/extract/index.ts:259]: Which change would be more maintainable?

Comment (stroncium) [reply lib/manager/npm/extract/index.ts:259]: I'd argue separate parsers are more maintainable. Though as existing replace stuff seems to work well enough for its cases I don't think there is need to refactor until something breaks or more cases are added.

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by rarkins — APPROVED** [review]
