### PR TITLE
fix(exec): Don't call bash for non-docker commands

### LINKED ISSUE #5172: Renovate Artifact Update Problem related to bash after upgrading to 19.97.2
**What Renovate type are you using?**

Gitlab Self-hosted (using the npmjs renovate package)

**Describe the bug**

I upgraded Renovate from `19.93.2` to `19.97.2`, and the next time Renovate ran it added a comment to many MRs with a package lock issue using bash:

----
### :warning: Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this MR as-is.

:recycle: Renovate will retry this branch, including artifacts, only when one of the following happens:

 - any of the package files in this branch needs updating, or 
 - the branch becomes conflicted, or
 - you check the rebase/retry checkbox if found above, or
 - you rename this MR's title to start with "rebase!" to trigger it manually

The artifact failure details are included below:

##### File name: package-lock.json

```
/bin/sh: bash: not found

```

---

I resolved this by adding bash to the docker image the Renovate bot runs in, and it resolved the issue for future Renovate runs. But, many renovate MRs are stuck in a state of having this message and renovate will not run on these MRs until the conditions in the message are met.

**Did you see anything helpful in debug logs?**

 INFO: Need to update package file so will rebase first (repository=repo, branch=renovate/minor-and-patch-packages)
 INFO: lock file error (repository=repo, branch=renovate/minor-and-patch-packages)
       "cmd": "node /builds/group/renovate/node_modules/npm/bin/npm-cli.js",
       "args": "install --package-lock-only --no-audit",
       "err": {
         "killed": false,
         "code": 127,
         "signal": null,
         "cmd": "bash -l -c \"node /builds/group/renovate/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\"",
         "stdout": "",
         "stderr": "/bin/sh: bash: not found\n",
         "message": "Command failed: bash -l -c \"node /builds/group/renovate/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\"\n/bin/sh: bash: not found\n",
         "stack": "Error: Command failed: bash -l -c \"node /builds/group/renovate/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\"\n/bin/sh: bash: not found\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       },
       "stdout": "",
       "stderr": "",
       "type": "npm"
 INFO: PR is less than a day old but branchExists so updating anyway (repository=repo, branch=renovate/minor-and-patch-packages)
 INFO: files committed (repository=repo, branch=renovate/minor-and-patch-packages)

**To Reproduce**

Run renovate in an environment where bash is not installed.

**Additional context**

Aside, Is there some way to force a rebase en-masse from the Renovate bot itself, to rebase all of the renovate MR/PRs that have this message? There are 74 instances of this message across many repos I'm looking to clean up but hoping to address it programmatically.

### PR DESCRIPTION
**Pull request by zharinov**
Closes #5172

### CODE REVIEW

File: lib/util/exec/index.ts [hunk 1]
```diff
@@ -84,28 +84,34 @@ export async function exec(
...
-    pExecCommand = dockerCmd(pExecCommand, dockerOptions);
+    let singleCommand = commands.join(' && ');
+    singleCommand = `bash -l -c "${singleCommand.replace(/"/g, '\\"')}"`;
+    singleCommand = dockerCmd(singleCommand, dockerOptions);
+    commands = [singleCommand];
+  }
+
+  let res: ExecResult | null = null;
+  for (let pExecCommand of commands) {
+    res = await pExec(pExecCommand, pExecOptions);
```
Comment (zharinov) [inline lib/util/exec/index.ts]: should be good enough, but ideally need to handle short-circuit logic

File: lib/util/exec/index.ts [hunk 2]
```diff
@@ -84,28 +84,34 @@ export async function exec(
...
 
-  const res = await pExec(pExecCommand, pExecOptions);
   const duration = hrtime(startTime);
   const seconds = Math.round(duration[0] + duration[1] / 1e9);
-  logger.debug(
-    { cmd, seconds, stdout: res.stdout, stderr: res.stderr },
-    'exec completed'
-  );
+
+  if (res) {
```
Comment (rarkins) [inline lib/util/exec/index.ts]: I think this timing should be moved inside the for loop so that we capture every command and not not just the last one

**Comment by zharinov** [comment]
Ready for review
