### PR TITLE
fix(config): migrate language objects

### LINKED ISSUE #23155: Migrate top level language config (v36)
### Describe the proposed change(s).

Renovate must be able to migrate language objects to avoid config errors. Example repo: https://github.com/renovate-reproductions/top-level-migrate

### Describe why we need/want these change(s).

Many people use this config convention

### PR DESCRIPTION
**Pull request by rarkins**
## Context

Closes #23155

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/config/migration.ts [hunk 1]
```diff
@@ -104,6 +104,31 @@ export function migrateConfig(config: RenovateConfig): MigratedConfig {
...
+    for (const language of languages) {
+      if (is.nonEmptyObject(migratedConfig[language])) {
+        logger.debug(`Migrating ${language} config`);
+        migratedConfig.packageRules ??= [];
+        const currentContent = migratedConfig[language] as any;
+        const packageRule = {
+          matchCategories: [language],
+          ...currentContent,
+        };
+        migratedConfig.packageRules.push(packageRule);
```
Comment (viceice) [inline lib/config/migration.ts:128]:
```suggestion
        migratedConfig.packageRules.unshift(packageRule);
```
because they where applied first previously? Otherwise they would now override other package rules?

**Comment by rarkins** [comment]
```
DEBUG: Config migration necessary (repository=renovate-reproductions/top-level-migrate)
       "oldConfig": {
         "docker": {"pinDigests": true},
         "dotnet": {"packageRules": [{"matchPackageNames": ["foo"], "enabled": false}]}
       },
       "newConfig": {
         "packageRules": [
           {"matchCategories": ["docker"], "pinDigests": true},
           {
             "matchCategories": ["dotnet"],
             "matchPackageNames": ["foo"],
             "enabled": false
           }
         ]
       }
```

File: lib/config/migration.spec.ts [hunk 2]
```diff
@@ -133,6 +136,14 @@ describe('config/migration', () => {
           automerge: 'minor',
           schedule: null,
         },
+        python: {
+          packageRules: [
+            {
+              matchPackageNames: ['foo'],
```
Comment (secustor) [inline lib/config/migration.spec.ts:142]: What should happen if the nested `packageRule` already contains a `matchCategories` field?
Merge or overwrite? 
The second one is the case right now.

Comment (rarkins) [reply lib/config/migration.spec.ts:142]: I think overwrite is fine in such an extreme edge case

**Review by secustor — APPROVED** [review]

**Review by viceice — APPROVED** [review]
