### PR TITLE
fix: always show dependency dashboard footer

### LINKED ISSUE #7035: Add checkbox to "trigger a request for Renovate to run again on this repository" to up-to-date dependency dashboard issues
**What would you like Renovate to be able to do?**

The current implementation is like so:

image

I'd like to be able to see something like this, even when everything is up-to-date:

image

Related: [https://github.com/renovatebot/config-help/issues/814](https://github.com/renovatebot/config-help/issues/814)

### PR DESCRIPTION
**Pull request by rarkins**
Closes #7035

### CODE REVIEW

File: lib/workers/repository/dependency-dashboard.ts [hunk 1]
```diff
@@ -204,8 +189,13 @@ export async function ensureMasterIssue(
...
   }
 
-  // istanbul ignore if
+  if (!hasBranches) {
+    issueBody +=
+      'This repository currently has no open or pending branches.\n\n';
+  }
+
   if (config.dependencyDashboardFooter?.length) {
+    // istanbul ignore if
```
Comment (viceice) [inline lib/workers/repository/dependency-dashboard.ts:198]:
```suggestion
```

Does not work as intented 🙃

**Review by viceice — COMMENTED** [review]
just a small issue
