### PR TITLE
fix(pypi): handle data-requires-python from simple endpoint

### LINKED ISSUE #6951: pypi: unable to detect packages with data-requires-python from Artifactory's simple html
**What Renovate type are you using?**

Self-hosted renovate on GitHub enterprise.

**Describe the bug**

When running Renovate on a Python project with dependencies from Artifactory that contains a `data-requires-python` field, I expected Renovate to find the latest version, but it does not.

Artifactory simple.html:

```html
<html><head><title>Simple Index</title><meta name="api-version" value="2" /></head><body>
<a href="../../mypackage/0.0.1/mypackage-0.0.1-py3-none-any.whl#md5=35c85ed2ca9c18538b2ed3f4f0822288" rel="internal" >mypackage-0.0.1-py3-none-any.whl</a><br/>
<a href="../../mypackage/0.0.1/mypackage-0.0.1.tar.gz#md5=ef11cc48fd3db1a2346f3c7b6607e227" rel="internal" >mypackage-0.0.1.tar.gz</a><br/>
<a href="../../mypackage/0.0.2/mypackage-0.0.2-py3-none-any.whl#md5=049a3bac606a1e12a6442e9101cac2ed" rel="internal" >mypackage-0.0.2-py3-none-any.whl</a><br/>
<a href="../../mypackage/0.0.2/mypackage-0.0.2-py3.7.egg#md5=cfa683f962b96c4e61952a3e0b67739e" rel="internal" >mypackage-0.0.2-py3.7.egg</a><br/>
<a href="../../mypackage/0.0.2/mypackage-0.0.2.tar.gz#md5=65d63d826183c781298cc19b057f4708" rel="internal" >mypackage-0.0.2.tar.gz</a><br/>
<a data-requires-python=">=3.6,<4.0" href="../../mypackage/0.0.3/mypackage-0.0.3-py3-none-any.whl#md5=965accb7cfba0481336f284f42e3a89a" rel="internal" >mypackage-0.0.3-py3-none-any.whl</a><br/>
<a data-requires-python=">=3.6,<4.0" href="../../mypackage/0.0.3/mypackage-0.0.3.tar.gz#md5=49cf268a34abfdea8bfd77bb2e0228e7" rel="internal" >mypackage-0.0.3.tar.gz</a><br/>
</body></html>
```

pyproject.toml

```toml
[tool.poetry.dev-dependencies]
mypackage = "^0.0.1"
```

The PR opened by renovate for `mypackage` is to upgrade to version 0.0.2, instead of 0.0.3. Manually installing 0.0.3 with `poetry update mypackage` or `pip install --upgrade mypackage` is successful.

**Relevant debug logs**

```
DEBUG: packageFiles with updates (repository=satish-ravi/test-repo)
       "config": {
         "poetry": [
           {
             "packageFile": "pyproject.toml",
             "manager": "poetry",
             "deps": [
               {
                 "depName": "mypackage",
                 "depType": "dev-dependencies",
                 "currentValue": "^0.0.1",
                 "managerData": {"nestedVersion": false},
                 "datasource": "pypi",
                 "versioning": "poetry",
                 "depIndex": 4,
                 "updates": [
                   {
                     "fromVersion": "0.0.1",
                     "toVersion": "0.0.2",
                     "newValue": "^0.0.2",
                     "newMajor": 0,
                     "newMinor": 0,
                     "updateType": "minor",
                     "isSingleVersion": false,
                     "isRange": true
                   }
                 ],
                 "warnings": [],
                 "sourceUrl": null
               }
             ],
             "registryUrls": [
               "https://myartifactory/artifactory/api/pypi/python-virt/simple/",
               "https://pypi.org/pypi/"
             ],
             "compatibility": {"python": "^3.7"}
           }
         ]
       }
```

**To Reproduce**

1. Setup a python project with a package from Artifactory.
1. Publish a new version of the package to Artifactory with poetry (or with setuptools with setup.py containing `python_requires=[">3.6"]`).
1. Run renovate and expect package to not be upgraded to the latest version

**Additional context**

I believe this is due to the HTML parser [here](https://github.com/renovatebot/renovate/blob/9154bc76807e6cb4c614ef03679bdeb9a2df9511/lib/datasource/pypi/index.ts#L183) parsing the `a` link texts as below:

```js
const { parse } = require('node-html-parser');
const html = `<the above html>`;
const root = parse(html);
const links = root.querySelectorAll('a');
console.log(links.map(links => links.text));
// [
//  'mypackage-0.0.1-py3-none-any.whl',
//  'mypackage-0.0.1.tar.gz',
//  'mypackage-0.0.2-py3-none-any.whl',
//  'mypackage-0.0.2-py3.7.egg',
//  'mypackage-0.0.2.tar.gz',
//  '=3.6,<4.0" href="../../mypackage/0.0.3/mypackage-0.0.3-py3-none-any.whl#md5=965accb7cfba0481336f284f42e3a89a" rel="internal" >mypackage-0.0.3-py3-none-any.whl',
//  '=3.6,<4.0" href="../../mypackage/0.0.3/mypackage-0.0.3.tar.gz#md5=49cf268a34abfdea8bfd77bb2e0228e7" rel="internal" >mypackage-0.0.3.tar.gz'
// ]
```

Maybe we could remove the `data-requires-python` field before parsing the HTML since it is not used anywhere. I am happy to send a PR for this.

### PR DESCRIPTION
**Pull request by satish-ravi**
Closes #6951

### CODE REVIEW

File: lib/datasource/pypi/index.ts [hunk 1]
```diff
@@ -180,21 +203,26 @@ async function getSimpleDependency(
     logger.trace({ dependency: packageName }, 'pip package not found');
     return null;
   }
-  const root: HTMLElement = parse(dep.replace(/<\/?pre>/, '')) as any;
+  const root: HTMLElement = parse(cleanSimpleHtml(dep)) as any;
   const links = root.querySelectorAll('a');
-  const releases = new Map<string, Release>();
```
Comment (rarkins) [inline lib/datasource/pypi/index.ts:185]: I think this Map was serving to also de-duplicate. If you shift to an array approach, you will need to add a de-duplication step manually to get equivalent results. However I'm not sure why we had concerns with duplication in the first place.

**Review by rarkins — CHANGES_REQUESTED** [review]

File: lib/datasource/pypi/index.ts (hunk 1 above)
Comment (satish-ravi) [reply lib/datasource/pypi/index.ts:185]: The deduplication now happens in this function https://github.com/renovatebot/renovate/pull/6966/files#diff-de5edfc564f5473b7f2a5a8c48e82629R58-R80, which also takes care of the deduplication when getting dependency from the JSON endpoint. 

I believe the deduplication is needed because a version could have both sdist (tar.gz) and wheel published.

I've updated the test to validate deduplication. The simple endpoint [fixture](https://github.com/renovatebot/renovate/pull/6966/files#diff-531b485f5ecf91b58397404a8b03c674R13-R14) contains both sdist and wheel releases for 0.2.2 and the [response](https://github.com/renovatebot/renovate/pull/6966/files#diff-6d852fa0319be1d392d9f04edba65ea9R101-R103) contains only one entry for 0.0.2

Comment (rarkins) [reply lib/datasource/pypi/index.ts:185]: `getCompatibleReleases` is intended for comparing compatibility and not de-duplicating. It would be very easy to accidentally regress this in future so I'd prefer it's done explicitly.

Comment (satish-ravi) [reply lib/datasource/pypi/index.ts:185]: Oh `getCompatibleReleases` is a function I added in this PR which pulls together the shared logic between `getDependency` and `getSimpleDependency` (now that simple also supports compatibility check) to do the compatibility check by invoking `compatibleVersions`, deduplicate versions and transform dependencies from pypi specific JSON to a more generic `Release` object. Maybe this function can be named better? E.g., `deduplicateAndTransformReleases`?

Comment (rarkins) [reply lib/datasource/pypi/index.ts:185]: Explicit and maintainable is always better than succinct and clever, so therefore please split it into two steps - compatibility and de-duplication. It will make it much easier for the next person who needs to understand and change the code.

Comment (satish-ravi) [reply lib/datasource/pypi/index.ts:185]: 👍 Updated to keep compatibility and de-duplication separate.

File: lib/datasource/pypi/index.ts [hunk 2]
```diff
@@ -180,21 +195,35 @@ async function getSimpleDependency(
...
+      if (!releases[version]) {
+        releases[version] = [];
       }
-      releases.set(version, release);
+      releases[version].push(release);
     }
   }
-  dependency.releases = [...releases.values()];
+  const versions = compatibleVersions(releases, compatibility);
+  dependency.releases = versions.map((version) => {
```
Comment (rarkins) [inline lib/datasource/pypi/index.ts:218]: Is this meant as the de-duplication? How is it achieving it if you map 1:1 between inputs and outputs?

Comment (satish-ravi) [reply lib/datasource/pypi/index.ts:218]: Oh actually `versions` is already de-duplicated. The `releases` object constructed [here](https://github.com/renovatebot/renovate/pull/6966/files#diff-de5edfc564f5473b7f2a5a8c48e82629R211-R214) is a map of versions -> array of releases. After the compatibility check, this function just de-duplicates releases per compatible version and returns one release per version.

It's similar to the map function [here](https://github.com/renovatebot/renovate/pull/6966/files#diff-de5edfc564f5473b7f2a5a8c48e82629R125-R136) in `getDependency`

Comment (rarkins) [reply lib/datasource/pypi/index.ts:218]: If this works then let's merge it. In future I would like to move compatibility concepts out of pypi and into the generic datasource layer anyway

**Comment by rarkins** [comment]
Thanks for the PR!
