### PR TITLE
fix(go): Mimic Go logic for `GOPRIVATE` parsing

### LINKED ISSUE #13138: `GOPRIVATE`/`GONOPROXY` parsed incorrectly
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.2.2

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Describe the bug

When parsing the `GOPRIVATE`/`GONOPROXY` environment variables, Renovate incorrectly parses the values, Go handles this as glob patterns, in the syntax of it's [path.Match](https://pkg.go.dev/path#Match) function (See https://pkg.go.dev/cmd/go#hdr-Environment_variables detailing this). The value is converted into a regex via some known mappings, however Go fails to mention that it is a prefix match https://github.com/golang/go/blob/2580d0e08d5e9f979b943758d3c49877fb2324cb/src/cmd/go/internal/modfetch/repo.go#L219 meaning that trailing wildcards may not match in the manner expected.

This causes issues with correct detection of when to use the `GOPROXY` that is set - In our case, causing it to fail to correctly renovate internal go modules.

For example, setting `GOPRIVATE` to `gitlab.example.com/*`, should result in matches for `gitlab.example.com/group/repository`, however this does not occur.

See https://github.com/renovatebot/renovate/blob/ee2e155f1fd032ec77bed942ee7b797137bb5dd2/lib/datasource/go/releases-goproxy.ts#L99-L113 for the proxy parsing code.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by 56KBs**
## Changes:

Ensure that the parsing of `GOPRIVATE`/`GONOPROXY` matches the behaviour of Go itself.

The documentation for these values state it matches the logic of `path.Match`, however in reality it's actually a prefix based match.

Updating the regex to allow for either an exact match, or a match where the configured value is a prefix of the package, when a `/` is added.

Additionally, strip any trailing `/`'s from the configured value, as this matches the logic that Go takes when matching.

## Context:

Closes #13138

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

File: lib/datasource/go/releases-goproxy.ts [hunk 1]
```diff
@@ -72,6 +72,10 @@ const lexer = moo.states({
       push: 'characterRange',
       value: (_: string) => '[',
     },
+    trailingSlash: {
```
Comment (HonkingGoose) [inline lib/datasource/go/releases-goproxy.ts:75]: > The documentation for these values state it matches the logic of `path.Match`, however in reality it's actually a prefix based match.

Do you mean that we need to change the Renovate docs? If so can you please edit our docs in this PR as well?

Comment (56KBs) [reply lib/datasource/go/releases-goproxy.ts:75]: Sorry - I meant that the Go documentation states this is the case - There aren't any docs in Renovate that explain the logic behind `GOPRIVATE`/`GONOPROXY`, they just link through to Go's documentation

Comment (HonkingGoose) [reply lib/datasource/go/releases-goproxy.ts:75]: Oh okay! Thanks for the clarification!

**Review by zharinov — COMMENTED** [review]
Looks good to me 👍

**Review by zharinov — APPROVED** [review]
