### PR TITLE
fix(yarn): don't rely on shell semantics for ignoring command failures

### LINKED ISSUE #40294: Yarn 1 update fails with `sed: can't read ||:` since `42.68.5`
### Describe the proposed change(s).

As noted in #40259, and similar to #40284

### PR DESCRIPTION
**Pull request by jamietanna**
## Changes

As reported in #40259, since https://github.com/renovatebot/renovate/pull/40228
we've seen Yarn 1 failing to update.

We can take advantage of the new `ignoreFailure` option to replace the
usage of shell semantics.

## Context

#40259

Please select one of the following:

- [x] This closes an existing Issue, Closes: #40294
- [ ] This doesn't close an Issue, but I accept the risk that this PR may be closed if maintainers disagree with its opening or implementation

## AI assistance disclosure

Did you use AI tools to create any part of this pull request?

Please select one option and, if yes, briefly describe how AI was used (e.g., code, tests, docs) and which tool(s) you used.

- [x] No — I did not use AI for this contribution.
- [ ] Yes — minimal assistance (e.g., IDE autocomplete, small code completions, grammar fixes).
- [ ] Yes — substantive assistance (AI-generated non‑trivial portions of code, tests, or documentation).
- [ ] Yes — other (please describe):

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests, but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

The public repository: <URL>

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

File: lib/modules/manager/npm/post-update/yarn.ts [hunk 1]
```diff
@@ -158,7 +159,10 @@ export async function generateLockFile(
           // The following change causes Yarn 1.x to exit gracefully after updating the lock file but without installing node_modules
           yarnTool.toolName = 'yarn-slim';
           if (yarnPath) {
-            commands.push(getOptimizeCommand(yarnPath) + ' || true');
+            commands.push({
+              command: split(getOptimizeCommand(yarnPath)),
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/yarn.ts]: please change `getOptimizeCommand` to return string array, so we don't need to split again.

**Review by viceice — COMMENTED** [review]
otherwise LGTM

File: lib/modules/manager/npm/post-update/yarn.ts [hunk 2]
```diff
@@ -84,8 +85,8 @@ export async function checkYarnrc(
   return { offlineMirror, yarnPath };
 }
 
-export function getOptimizeCommand(fileName: string): string {
-  return `sed -i 's/ steps,/ steps.slice(0,1),/' ${quote(fileName)}`;
+export function getOptimizeCommand(fileName: string): string[] {
+  return split(`sed -i 's/ steps,/ steps.slice(0,1),/' ${quote(fileName)}`);
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/yarn.ts]:
```suggestion
  return ['sed', '-i', 's/ steps,/ steps.slice(0,1),/', fileName];
```

File: lib/modules/manager/npm/post-update/yarn.ts [hunk 3]
```diff
@@ -1,6 +1,6 @@
 import { isString } from '@sindresorhus/is';
 import semver from 'semver';
-import { quote } from 'shlex';
+import { quote, split } from 'shlex';
```
Comment (viceice) [inline lib/modules/manager/npm/post-update/yarn.ts]:
```suggestion
import { quote } from 'shlex';
```

**Review by viceice — COMMENTED** [review]
keep it simple

**Review by viceice — APPROVED** [review]
