### PR TITLE
fix(manager/composer): match composer's handling of the patch number for platform PHP version

### LINKED ISSUE #17308: Renovate handles `config.platform.php` different from composer
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

There is a setting for composer as documented here https://getcomposer.org/doc/06-config.md#platform, that allows the user to override the detected PHP version when installing packages. Say for example you are locally running PHP 7.4, but in production you are running PHP 8.1. In order to obtain the correct packages for production, this would be set to e.g. `"config": {"platform": {"php": "8.1.3"}}`.

A feature was added to renovate to read the value from this setting in order to override the detected PHP version.

There are 2 large differences however, with how composer and renovate treat these values.

- A setting of `7.4`, would be treated by composer as `7.4.0` and by renovate as `7.4.30` (the latest patch version for this minor) due to the use of docker tags.
- A setting of `7.4.99`, would be treated by composer as a real version, obtaining packages that satisfy this PHP version requirement (the end result being the same as specifying `7.4.30` (the latest patch version for this minor). Renovate on the other hand will fall back to using the `latest` docker tag (which could be a completely different major, e.g. `8.1` when a docker tag with that version number is not found.

The ideal scenario to this would be that if the docker tag for a specific patch is not found, it would fallback to the latest for that minor, and if a docker tag for a specific minor is not found, it would fallback to the latest for that major.

As a compromise, and to mimic how this setting is used in the wild, either specifying a specific PHP version to run against, or by specifying a non-existent version to mean the latest, the following PR will treat a composer override of `7.4` as `7.4.0` in renovate (matching composer) and and override of `7.4.99` as `7.4` in renovate (matching composer).

- PR: https://github.com/renovatebot/renovate/pull/17299
- Example where the wrong PHP version is used: https://github.com/laminas/laminas-skeleton-installer/pull/39

### Relevant debug logs

_No response_

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

### PR DESCRIPTION
**Pull request by internalsystemerror**
## Changes

When specifying a deliberately high patch version (i.e. a never to be released version) e.g. `7.4.99` for `config.platform.php` inside `composer.json`, this is currently handled by composer to imply the latest available patch version. This PR brings renovate in line with that usage, by replacing any patch version number greater than 0 with `<=`, (i.e. `7.4.99` becomes `<=7.4.99` for the purpose of resolving the docker tag).

## Context

At present when users are specifying a non-existent patch number, this tells composer to retrieve updates using the latest available patch for that PHP minor. Although not ubiquitous (as some will want to specify a specific patch version), nor a written standard (composer documentation only mentions the case where no patch is specified, which is treated the same as patch 0 (i.e. `7.4` is taken to be `7.4.0`).

- Related Issue: Closes https://github.com/renovatebot/renovate/issues/17308

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required
Although this is a change to renovate, we are using a feature of composer, and this PR simply brings it into line with that usage. However, I'm happy to include documentation changes if someone could point me to what and where.

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

There will still be examples where a version such as `7.4.50` is specified, which is a non-existent version. In this case, composer will use `7.4.30` (latest patch for minor) whereas renovate will request the docker tag `7.4.50` which doesn't exist and so will fall back to the latest tag (which is `8.0` currently).

In our discussions it had been suggested to drop the patch version altogether as we couldn't think of a case where the latest patch version wouldn't be allowed, quite the reverse, this is usually to require a minimum version that includes a specific fix. ~~However, as we did not want to prevent users from being able to specify a patch version, a patch of `>=99` appeared to be a suitable compromise.~~ After further discussion in the issue above, the approach will now be to replace any patch version number greater than 0 with `<=`, (i.e. `7.4.99` becomes `<=7.4.99` for the purpose of resolving the docker tag).

### CODE REVIEW

**Comment by internalsystemerror** [comment]
Some points regarding, whether a PHP version with a patch of `.99` would ever be released:

Latest patch versions...
`5.6.40`
(there is no v6)
`7.0.33`
`7.1.33`
`7.2.34`
`7.3.33`
`7.4.30` (security-only)
`8.0.22` (actively maintained)
`8.1.9`

**Comment by rarkins** [comment]
Sounds like composer treats a plain version as like <=, would it be better or we did that too?

**Comment by Xerkus** [comment]
Composer treats `7.4` as `7.4.0`. For packages defining php dependency as say `~7.4.1` (a shorthand for `>=7.4.1 <8.0.0`) platform defined as `7.4` would not be compatible.

So, to say we have the latest of the 7.4.x we use arbitrary high patch number to ensure platform version will satisfy packages requiring any of the existing releases as their minimum. Packages require specific PHP patch version as minimum when there was a php bug affecting the package that was fixed by a particular patch version. I never seen package that will not accept latest patch version.

Composer itself does not have any special treatment to the number. It just needs to be within the range for the purposes of dependency resolution. I've seen `.99` and `.999` used most often for that purpose.  

My understanding is that the issue we experience comes from the fact that `7.3.99` is not a real version and renovate does not have a matching docker tag, falling back to `:latest` and using wrong php version altogether.

Eg lock file maintenance https://github.com/laminas/laminas-skeleton-installer/pull/39  creates lock file against package versions that require php 7.4 as a minimum where defined platform and expected lock file is for php 7.3.
Composer itself deals with `7.3.99` defined in platform properly.

**Comment by internalsystemerror** [comment]
Composer allows the use of `config.platform.php` in order to override the detected PHP version and specify the specific PHP version to use when fetching dependencies. We are reading from this setting in order to override the specific PHP version used for renovate.

The difference currently lies with how composer vs renovate handles a non-existent version. Composer will obtain packages using `7.4.99` as the PHP version matching packages that require `"php": "^7.4.27"` and `"php": "<8.0.0"`.

Renovate however, passes this as a docker tag to fetch the correct PHP version. The ideal scenario would be to check if the patch version exists and if not, drop the patch number and check again.

Specifying a setting of `"7.4"` in `composer.json` is treated by composer as `"7.4.0"`. This currently differs from renovate too, and now I think about it, I may wish to amend this PR to set the patch number to 0, if there is none.

Also note we're talking specifically about the `config.platform.php` setting which is a specific version used only when the root `composer.json` to override a PHP range in `require`.

See https://getcomposer.org/doc/06-config.md#platform for composer's documentation on this feature.

**Comment by rarkins** [comment]
I think we need to discuss this in an issue to reach consensus on how Renovate should treat these edge cases, including composer's undocumented behaviour. @internalsystemerror Could you create one and we move the dissuasion there?

**Comment by internalsystemerror** [comment]
It's not that the behaviour is undocumented, this is how composer treats this version tag. `7.4` means `7.4.0` (different from docker tags) and a non-existent version number is used as is (again different from docker tags).

I've opened the following issue https://github.com/renovatebot/renovate/issues/17308 anyway. Hopefully this PR will bridge the differences whilst not having to make multiple round trips to docker in order to resolve the correct docker tag to use.

File: lib/modules/manager/composer/utils.ts [hunk 1]
```diff
@@ -75,7 +75,18 @@ export function extractConstraints(
 
   // extract php
   if (composerJson.config?.platform?.php) {
-    res.php = composerJson.config.platform.php;
+    const major = api.getMajor(composerJson.config.platform.php);
+    const minor = api.getMinor(composerJson.config.platform.php);
+    const patch = api.getPatch(composerJson.config.platform.php);
+    if (patch === null || patch < 1) {
```
Comment (viceice) [inline lib/modules/manager/composer/utils.ts:81]: patch will never be negative.

**Review by viceice — CHANGES_REQUESTED** [review]
where is the discussion? link do some docs/ source code about composer behavior

**Comment by internalsystemerror** [comment]
> where is the discussion? link do some docs/ source code about composer behavior

In the comment above, I opened an issue for discussion. I've also provided a comment to try and clearly explain the current error with examples, and then a further comment to show why this doesn't occur with e.g. node.

The issue again for brevity: https://github.com/renovatebot/renovate/issues/17308

File: lib/modules/manager/composer/utils.ts (hunk 1 above)
Comment (internalsystemerror) [reply lib/modules/manager/composer/utils.ts:81]: What's returned is a number, so this handles a float of 0.0 also. But if the return is always an integer, I can update this line to be:
```ts
if (patch === null || patch === 0) {
```

**Comment by viceice** [comment]
please move the issue link to context section and add ` - ` to the issue, so the issue title is visible.

**Comment by internalsystemerror** [comment]
> please move the issue link to context section and add `-` to the issue, so the issue title is visible.

Ah! I didn't know that was a GitHub feature, glad I learnt it. Done!

**Comment by Xerkus** [comment]
For the docker latest tag replaces previous. It makes sense that builds tagged with `7.4` will be replacing previous builds and end up meaning latest build (and release)

In the context of platform overrides we talk about specific versions so it can not be expanded with anything implied other than `.0`.

> link do some docs/ source code about composer behavior

For the constraints the Stability Constraints indirectly covers implicit behavior: https://getcomposer.org/doc/articles/versions.md#stability-constraints

**Comment by internalsystemerror** [comment]
I rebased and squashed however you guys update quicker than I can keep up. Now ready for review.

**Review by viceice — DISMISSED** [review]
🤷‍♂️

**Comment by internalsystemerror** [comment]
I assume you guys are able to update the branch prior to merge, but if not just let me know.

**Comment by internalsystemerror** [comment]
@rarkins sorry for the ping, I know your time is precious but a) I wanted to make sure that this is on your radar, and b) I wanted to ask if there are any other changes needed from me, or if I just need to wait patiently?

File: lib/modules/manager/composer/utils.ts [hunk 2]
```diff
@@ -75,7 +75,22 @@ export function extractConstraints(
 
   // extract php
   if (composerJson.config?.platform?.php) {
-    res.php = composerJson.config.platform.php;
+    const major = api.getMajor(composerJson.config.platform.php);
+    const minor = api.getMinor(composerJson.config.platform.php);
+    const patch = api.getPatch(composerJson.config.platform.php);
+
+    // handle where x is taken by composer to mean lowest patch of the lowest minor (x.0.0)
+    if (minor === null || minor === 0) {
```
Comment (rarkins) [inline lib/modules/manager/composer/utils.ts:83]: What if the version is 7.0.5? Is it intentional that you'd use 7.0.0 instead?

File: lib/modules/manager/composer/utils.ts [hunk 3]
```diff
@@ -75,7 +75,22 @@ export function extractConstraints(
...
+      res.php = `${major}.0.0`;
+    }
+    // handle where x.x is taken by composer to mean lowest patch (x.x.0)
+    else if (patch === null || patch === 0) {
```
Comment (rarkins) [inline lib/modules/manager/composer/utils.ts:87]: This covers both 7.2 and 7.2.0. Intended?

File: lib/modules/manager/composer/utils.ts (hunk 2 above)
Comment (internalsystemerror) [reply lib/modules/manager/composer/utils.ts:83]: ah good spot! Ty, I will update to:
`${major}.0.${patch}`

File: lib/modules/manager/composer/utils.ts (hunk 3 above)
Comment (internalsystemerror) [reply lib/modules/manager/composer/utils.ts:87]: Correct, if the patch number is missing or already 0, then it will be set to 0. This covers the  first difference where:
NPM: `7.4` => `7.4.*`
Composer: `7.4` => `7.4.0`

File: lib/modules/manager/composer/utils.ts [hunk 4]
```diff
@@ -75,7 +75,22 @@ export function extractConstraints(
...
+      res.php = `${major}.${minor}.0`;
+    }
+    // handle non-existent patch numbers
+    else {
+      res.php = `<=${major}.${minor}.${patch}`;
```
Comment (internalsystemerror) [inline lib/modules/manager/composer/utils.ts:92]: And the `<=` covers the second difference where non existent version numbers are used.

File: lib/modules/manager/composer/utils.ts (hunk 3 above)
Comment (internalsystemerror) [reply lib/modules/manager/composer/utils.ts]: I decided to use a much simpler approach and added tests to confirm these use cases are covered

File: lib/modules/manager/composer/utils.ts (hunk 4 above)
Comment (internalsystemerror) [reply lib/modules/manager/composer/utils.ts]: I decided to use a much simpler approach and added tests to confirm these use cases are covered

**Review by rarkins — APPROVED** [review]
