### PR TITLE
fix(goproxy): check for major updates

### LINKED ISSUE #16663: Major version update of Go module is not detected when GOPROXY is set
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Minimal reproduction: https://github.com/at-wat/renovate-repro-major-not-updated

Reproduction repository has dependency to `github.com/google/go-github/v44 v44.0.0`.
New versions `v44.1.0` and `v45.2.0` are available.

**Expected behavior**:
Major version update PR (`Update module github.com/google/go-github/v44 to v45`) and minor version update PR (`Update module github.com/google/go-github/v44 to v44.1.0`) is created.
**Actual behavior**:
Major version update PR of Go module is not created.
Only minor version update PR (`Update module github.com/google/go-github/v44 to v44.1.0`) is created.

---

Hosted Renovate doesn't detect major version update of Go module.
Self-hosted Renovate detects.
(Logs below)

On my private repository, the last major version update PR for github.com/google/go-github was v39 on Oct 4, 2021.
v40.0.0 was released on [Nov 08, 2021](https://github.com/google/go-github/releases/tag/v40.0.0), so something goes wrong in this period.

I tested several version of self-hosted Renovate from 28.3.0 to 32.119.2 and all of them seems detecting major update of github.com/google/go-github.
I also added an another Go module (github.com/go-chi/chi/v4 -> github.com/go-chi/chi/v5) to the reproduction repository and same problem occurred. (removed now to make it minimal)

### Relevant debug logs

<details><summary>Logs on hosted Renovate (32.117.4)</summary>

```
DEBUG: packageFiles with updates
{
  "config": {
    "gomod": [
      {
        "packageFile": "go.mod",
        "constraints": {
          "go": "^1.18"
        },
        "deps": [
          {
            "managerData": {
              "lineNumber": 4
            },
            "depName": "github.com/google/go-github/v44",
            "depType": "require",
            "currentValue": "v44.0.0",
            "datasource": "go",
            "depIndex": 0,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "v44.1.0",
                "newValue": "v44.1.0",
                "releaseTimestamp": "2022-05-13T17:01:22.000Z",
                "newMajor": 44,
                "newMinor": 1,
                "updateType": "minor",
                "branchName": "renovate/github.com-google-go-github-v44-44.x"
              }
            ],
            "warnings": [],
            "versioning": "semver",
            "sourceUrl": "https://github.com/google/go-github",
            "currentVersion": "v44.0.0",
            "isSingleVersion": true,
            "fixedVersion": "v44.0.0"
          }
        ]
      }
    ]
  }
}
```

</details>

<details><summary>Logs on self-hosted Renovate (32.117.4)</summary>

```
DEBUG: packageFiles with updates (repository=at-wat/renovate-repro-major-not-updated)
"config": {
  "gomod": [
    {
      "packageFile": "go.mod",
      "constraints": {"go": "^1.18"},
      "deps": [
        {       
          "managerData": {"lineNumber": 4},
          "depName": "github.com/google/go-github/v44",
          "depType": "require",
          "currentValue": "v44.0.0",
          "datasource": "go",
          "depIndex": 0,
          "updates": [
            {       
              "bucket": "non-major",
              "newVersion": "v44.1.0",
              "newValue": "v44.1.0",
              "releaseTimestamp": "2022-05-13T17:01:22.000Z",
              "newMajor": 44,
              "newMinor": 1,
              "updateType": "minor",
              "branchName": "renovate/github.com-google-go-github-v44-44.x"
            },      
            {       
              "bucket": "major",
              "newVersion": "v45.2.0",
              "newValue": "v45.2.0",
              "releaseTimestamp": "2022-06-20T10:54:32.000Z",
              "newMajor": 45,
              "newMinor": 2,
              "updateType": "major",
              "branchName": "renovate/github.com-google-go-github-v44-45.x"
            }       
          ],      
          "warnings": [],
          "versioning": "semver",
          "sourceUrl": "https://github.com/google/go-github",
          "currentVersion": "v44.0.0",
          "isSingleVersion": true,
          "fixedVersion": "v44.0.0"
        }       
      ]
    }
  ]
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### LINKED ISSUE #19062: Go datasource does not find major updates for gopkg.in modules
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

The Go datasource does not find major updates for `gopkg.in` modules, it may be due to the use of `goproxy` (`direct` should work), it only requests versions for the current major release, for example: https://proxy.golang.org/gopkg.in/yaml.v2/@v/list (oddly I do not see the request for this URL in the HTTP statistics)

It would need to be able to request all possible major URLs as a project could skip versions.  Maybe `gopkg.in` should always use `direct`?

Minimal reproduction: https://github.com/maxbrunet/renovate-gopkgin-major

### Relevant debug logs

<details><summary>Logs</summary>

```json
          {
            "managerData": {
              "lineNumber": 4
            },
            "depName": "gopkg.in/yaml.v2",
            "depType": "require",
            "currentValue": "v2.4.0",
            "datasource": "go",
            "depIndex": 1,
            "updates": [],
            "warnings": [],
            "versioning": "semver",
            "sourceUrl": "https://github.com/go-yaml/yaml",
            "currentVersion": "v2.4.0",
            "fixedVersion": "v2.4.0"
          }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by maxbrunet**
## Changes

In the Go datasource when using `GOPROXY`, check for new major releases of Go modules.

Includes handling for `gopkg.in/` special case:

> As a special case, modules paths starting with `gopkg.in/` must always have a major version suffix, even at `v0` and `v1`. The suffix must start with a dot rather than a slash (for example, `gopkg.in/yaml.v2`).

## Context

Reference: https://go.dev/ref/mod#major-version-suffixes

Fixes #16663
Fixes #19062

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by zharinov — DISMISSED** [review]

**Comment by rarkins** [comment]
@maxbrunet is it possible you can split this into a refactoring PR + fix PR? It's a little challenging to code review for breaking changes this way

**Comment by maxbrunet** [comment]
@rarkins I have restructured the PR in 2 commits, let me know if that helps

File: lib/modules/datasource/go/releases-goproxy.ts [hunk 1]
```diff
@@ -52,21 +52,38 @@ export class GoProxyDatasource extends Datasource {
...
-          if (releaseTimestamp) {
-            return { version, releaseTimestamp };
+        let releases: Release[] = [];
+        if (packageName.startsWith('gopkg.in/')) {
+          const versionSuffixRegex = regEx(/\.v(\d+)$/);
+          const versionSuffixMatch = packageName.match(versionSuffixRegex);
+          if (versionSuffixMatch === null || versionSuffixMatch.length < 2) {
+            releases = await this.getVersionsWithInfo(url, packageName);
+          } else {
+            const versionSuffix = Number(versionSuffixMatch[1]);
```
Comment (viceice) [inline lib/modules/datasource/go/releases-goproxy.ts:62]: use parseInt instead of number constructor

File: lib/modules/datasource/go/releases-goproxy.ts [hunk 2]
```diff
@@ -240,6 +257,28 @@ export class GoProxyDatasource extends Datasource {
     return result;
   }
 
+  async getVersionsWithInfo(
+    baseUrl: string,
+    packageName: string
+  ): Promise<Release[]> {
+    const releasesIndex = await this.listVersions(baseUrl, packageName);
+    const releases = await p.map(releasesIndex, async (versionInfo) => {
```
Comment (viceice) [inline lib/modules/datasource/go/releases-goproxy.ts:265]: i think we need to limit concurrency here. otherwise we'll hammering the API too much.

@rarkins WDYT?

Comment (rarkins) [reply lib/modules/datasource/go/releases-goproxy.ts:265]: Isn't this just copied from deleted line 56? I think if it's Google's GOPROXY then it can probably handle load, we'd be more likely to swamp *ourselves*

Comment (maxbrunet) [reply lib/modules/datasource/go/releases-goproxy.ts:265]: > Isn't this just copied from deleted line 56?

Yes

File: lib/modules/datasource/go/releases-goproxy.ts [hunk 3]
```diff
@@ -52,21 +52,38 @@ export class GoProxyDatasource extends Datasource {
...
+                      versionSuffixRegex,
+                      `.v${versionSuffix + i}`
+                    )
+                  )
+                );
+              } catch (err) {
+                const statusCode = err?.response?.statusCode;
+                if (i > 0 && (statusCode === 404 || statusCode === 410)) {
+                  break;
+                }
```
Comment (rarkins) [inline lib/modules/datasource/go/releases-goproxy.ts:78]: These are the *expected* error codes if the major release doesn't exist?

Comment (maxbrunet) [reply lib/modules/datasource/go/releases-goproxy.ts:78]: Yes, catching them avoids to fallback to another proxy, if the current major was available, I think we can expect the following would be too

https://github.com/renovatebot/renovate/blob/21ee796d6bd718d208ae0c862bf96106478eb79a/lib/modules/datasource/go/releases-goproxy.ts#L86-L87

File: lib/modules/datasource/go/releases-goproxy.ts [hunk 4]
```diff
@@ -52,21 +52,38 @@ export class GoProxyDatasource extends Datasource {
...
+              try {
+                releases = releases.concat(
+                  await this.getVersionsWithInfo(
+                    url,
+                    packageName.replace(
+                      versionSuffixRegex,
+                      `.v${versionSuffix + i}`
+                    )
+                  )
+                );
```
Comment (rarkins) [inline lib/modules/datasource/go/releases-goproxy.ts:73]: Please add a break here too if `releases` is empty

**Review by rarkins — CHANGES_REQUESTED** [review]

**Comment by rarkins** [comment]
Is this the expected result? https://github.com/renovate-reproductions/19062/pull/1/files

**Comment by maxbrunet** [comment]
> Is this the expected result? [renovate-reproductions/19062#1 (files)](https://github.com/renovate-reproductions/19062/pull/1/files)

Yes, ideally need to run `go mod tidy` and update the import paths to complete the update:

```
diff --git a/renovate.json b/renovate.json
index 39a2b6e..237494a 100644
--- a/renovate.json
+++ b/renovate.json
@@ -2,5 +2,11 @@
   "$schema": "https://docs.renovatebot.com/renovate-schema.json",
   "extends": [
     "config:base"
-  ]
+  ],
+  "golang": {
+    "postUpdateOptions": [
+      "gomodTidy",
+      "gomodUpdateImportPaths"
+    ]
+  }
 }
```

It looks like the import paths update does not work: :slightly_frowning_face:

https://github.com/maxbrunet/renovate-gopkgin-major/pull/3/files

It seems to be a problem with [github.com/marwan-at-work/mod](https://github.com/marwan-at-work/mod), I will see if I can get `gopkg.in` supported over there. On Renovate's side we should be good.

**Comment by maxbrunet** [comment]
I have opened the PR marwan-at-work/mod#18. If it gets merged, I'll open another PR in this repo to remove the `gomodUpdateImportPaths` restriction here:

https://github.com/renovatebot/renovate/blob/9599b850fd12d4ab4fe01639f584cc5c7f53eeb1/lib/modules/manager/gomod/artifacts.ts#L117-L122

**Comment by maxbrunet** [comment]
Ah indeed, it would be a matter of detecting the separator (`.` or `/`), I'll try.

**Comment by maxbrunet** [comment]
@rarkins I generalized the major releases check to all Go modules :)

**Comment by rarkins** [comment]
Unfortunately this hangs for me locally when I test against https://github.com/renovate-reproductions/16663

The strange thing is that sometimes it hangs on v45 and sometimes on v46

**Comment by maxbrunet** [comment]
@rarkins I am not able to reproduce the issue you are observing, here is how I run it:

```shell
GOPROXY=https://proxy.golang.org RENOVATE_TOKEN=<redacted> LOG_LEVEL=debug yarn run start maxbrunet/renovate-gopkgin-major
```

**Comment by maxbrunet** [comment]
@rarkins I re-run today without any changes and it works as expected :confused:: maxbrunet/renovate-reproductions-16663#5

```shell
GOPROXY=https://proxy.golang.org RENOVATE_TOKEN=<redacted> LOG_LEVEL=debug yarn run start maxbrunet/renovate-reproductions-16663
```

Could you try again on your side? (Could it have anything to do with the cache?)

**Review by rarkins — DISMISSED** [review]

File: lib/modules/datasource/go/releases-goproxy.ts [hunk 5]
```diff
@@ -52,21 +60,31 @@ export class GoProxyDatasource extends Datasource {
...
+              mod = baseMod;
+              i++; // v0 and v1 are the same module
+            } else {
+              mod = `${baseMod}${majorSuffixSeparator}v${major}`;
+            }
+            const result = await this.getVersionsWithInfo(url, mod);
+            if (result.length === 0) {
+              break;
+            }
+            releases = releases.concat(result);
```
Comment (viceice) [inline lib/modules/datasource/go/releases-goproxy.ts:78]:
```suggestion
            releases.push(...result);
```
https://dev.to/uilicious/javascript-array-push-is-945x-faster-than-array-concat-1oki

**Review by viceice — DISMISSED** [review]

File: lib/modules/datasource/go/releases-goproxy.ts [hunk 6]
```diff
@@ -52,21 +60,31 @@ export class GoProxyDatasource extends Datasource {
...
 
-        const releasesIndex = await this.listVersions(url, packageName);
-        const releases = await p.map(releasesIndex, async (versionInfo) => {
-          const { version, releaseTimestamp } = versionInfo;
-
-          if (releaseTimestamp) {
-            return { version, releaseTimestamp };
-          }
-
+        let releases: Release[] = [];
```
Comment (viceice) [inline lib/modules/datasource/go/releases-goproxy.ts:63]:
```suggestion
        const releases: Release[] = [];
```

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
