### PR TITLE
fix(workers/branch): skip branch update if `pendingChecks=true`

### LINKED ISSUE #38719: Prevent branch updates when minimumReleaseAge is not met
### Describe the proposed change(s).

When a new version is released before an existing renovate branch/pr is merged. Then, in some cases the branch gets updated with the newer version even if the version does not meet the `minimumReleaseAge` criteria.

Some examples:

1. https://github.com/renovatebot/renovate/discussions/38324
2. https://github.com/renovatebot/renovate/discussions/38247

## Fix

If a branch exists and `pendingChecks=true` do not update the branch.

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- Skip updating an existing branch if `pendingChecks=true`

## Context

Closes: #38719 

Please select one of the below:

- [x] This closes an existing Issue: #38719
- [ ] This doesn't close an Issue, but I accept the risk that this PR may be closed if maintainers disagree with its opening or implementation

## AI assistance disclosure

Did you use AI tools to create any part of this pull request?

Please select one option and, if yes, briefly describe how AI was used (e.g., code, tests, docs) and which tool(s) you used.

- [x] No — I did not use AI for this contribution.
- [ ] Yes — minimal assistance (e.g., IDE autocomplete, small code completions, grammar fixes).
- [ ] Yes — substantive assistance (AI generated non‑trivial portions of code, tests, or documentation).
- [ ] Yes — other (please describe):

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

The public repository: https://github.com/Rahul-renovate-testing/min-release-age-branch-update-old-behavior

### CODE REVIEW

**Review by jamietanna — COMMENTED** [review]
Can we please give this a go with a real repo? I'd like us to get a bit more confidence that this does solve the reported issue, given it's fairly significant

Also, whether we can add any other test(s) as necessary

**Comment by RahulGautamSingh** [comment]
Reproduction:

Current Behaviour: https://github.com/Rahul-renovate-testing/min-release-age-branch-update-old-behavior/pull/2
Behaviour with changes from this PR: https://github.com/Rahul-renovate-testing/min-release-age-branch-update/pulls

In both cases, an update branch exists which can be used to create a PR namely, `renovate/node-22.x`

File: lib/workers/repository/update/branch/index.ts [hunk 1]
```diff
@@ -279,6 +279,17 @@ export async function processBranch(
...
         }
+
+        if (config.pendingChecks) {
+          logger.info(
+            'Branch updating is skipped because it contains updates with unmet release age',
+          );
+          return {
+            branchExists: true,
+            prNo: branchPr?.number,
+            result: 'no-work',
```
Comment (RahulGautamSingh) [inline lib/workers/repository/update/branch/index.ts]: Should we make it `pending`?

Comment (jamietanna) [reply lib/workers/repository/update/branch/index.ts]: I think `pending` would be more self-explanatory? It clarifies that this branch can't be created because it's pending checks, rather than "we didn't have anything to do" i.e. because things are up-to-date

Comment (RahulGautamSingh) [reply lib/workers/repository/update/branch/index.ts]: The branch is present and maybe even PR. We are just not going to update it with the latest version cause that version is pending ie. no work to be done here ... since the user themselves chose the release age

Comment (secustor) [reply lib/workers/repository/update/branch/index.ts]: `no-work` is semantically correct, though a debugging user would wonder why it is `no-work`. 

Yes, they could cross checks logs, so I`m in favour of `pending` and maybe a `reasoning` field or similar in the future.

File: lib/workers/repository/update/branch/index.ts [hunk 2]
```diff
@@ -279,6 +279,17 @@ export async function processBranch(
             result: 'no-work',
           };
         }
+
+        if (config.pendingChecks) {
+          logger.info(
+            'Branch updating is skipped because it contains updates with unmet release age',
```
Comment (jamietanna) [inline lib/workers/repository/update/branch/index.ts]: Is `pendingChecks` _only_ ever for Minimum Release Age? If not, we should amend the wording here

File: lib/workers/repository/update/branch/index.ts [hunk 3]
```diff
@@ -268,8 +268,8 @@ export async function processBranch(
 
       const prRebaseChecked = !!branchPr?.bodyStruct?.rebaseRequested;
 
-      if (branchExists && !dependencyDashboardCheck && config.stopUpdating) {
-        if (!prRebaseChecked) {
+      if (branchExists && !dependencyDashboardCheck) {
+        if (config.stopUpdating && !prRebaseChecked) {
```
Comment (jamietanna) [inline lib/workers/repository/update/branch/index.ts]: Did this need to change?

**Review by jamietanna — COMMENTED** [review]
I wonder if https://github.com/zharinov/renovate/blob/1cbfe082d3646e3b6ef721462e682b494a0cafb9/lib/workers/repository/update/branch/index.ts#L201-L213 could be amended / added to instead?

**Review by jamietanna — COMMENTED** [review]
Validating this against another real repo, https://github.com/JamieTanna-Mend-testing/renovate-iss-38324, I can see that this works as expected

File: lib/workers/repository/update/branch/index.ts (hunk 2 above)
Comment (jamietanna) [reply lib/workers/repository/update/branch/index.ts]: It looks like yes, right now - but I'd recommend consistency with other logs in this file:


```suggestion
        if (config.pendingChecks) {
          logger.info(
            `Branch ${config.branchName} updating is disabled because internalChecksFilter was not met`,
```

**Comment by jamietanna** [comment]
Interestingly, this shows as ([via](https://github.com/JamieTanna-Mend-testing/renovate-iss-38324/issues/2)) (I believe due to the `pending` result:

Screenshot 2025-10-27 at 13 52 24

Is that what we're expecting?

**Review by jamietanna — DISMISSED** [review]
Few comments, otherwise LGTM - thanks!

**Comment by onigoetz** [comment]
Hi, that looks like a nice improvement.

I wonder what happens in the case of grouped updates?

__Given__
- default branch contains
  - a: 1.0.0
  - b: 1.0.0
- renovate branch contains
  - a: 1.0.1 (matching minimumReleaseAge)
  - b: 1.0.0

__When__
renovate finds two new updates
  - a: 1.0.2 (matching minimumReleaseAge)
  - b: 1.0.1 (NOT matching minimumReleaseAge)

__Then__
I would expect the branch to be updated in the following way:
- a: 1.0.2 (matching minimumReleaseAge)
- b: 1.0.0

Is it what happens with this change?

**Comment by RahulGautamSingh** [comment]
> Interestingly, this shows as ([via](https://github.com/JamieTanna-Mend-testing/renovate-iss-38324/issues/2)) (I believe due to the `pending` result:
> 
> Screenshot 2025-10-27 at 13 52 24
> Is that what we're expecting?

Yes

File: lib/workers/repository/update/branch/index.ts (hunk 3 above)
Comment (RahulGautamSingh) [reply lib/workers/repository/update/branch/index.ts]: Yes, as it checks whether the stopUpdating lavels is present or not, which is what the check is for. Also, present in the info log below it.

File: lib/workers/repository/update/branch/index.ts (hunk 2 above)
Comment (jamietanna) [reply lib/workers/repository/update/branch/index.ts]: @RahulGautamSingh can we please make this change?

File: lib/workers/repository/update/branch/index.ts [hunk 4]
```diff
@@ -279,6 +279,17 @@ export async function processBranch(
             result: 'no-work',
           };
         }
+
+        if (config.pendingChecks) {
+          logger.info(
+            'Branch updating is skipped because it contains updates with pendingChecks=true',
```
Comment (jamietanna) [inline lib/workers/repository/update/branch/index.ts]: Do you not think it's worth logging the branch name, here?

File: lib/workers/repository/update/branch/index.ts (hunk 2 above)
Comment (RahulGautamSingh) [reply lib/workers/repository/update/branch/index.ts]: Branch name will be present in the metadata so no need to add.

File: lib/workers/repository/update/branch/index.ts (hunk 4 above)
Comment (RahulGautamSingh) [reply lib/workers/repository/update/branch/index.ts]: No, present in metadata, like this:
image

**Review by jamietanna — APPROVED** [review]
